spack/spack

var/spack/packages/jdk/package.py
var/spack/packages/rose/add_spack_compiler_recognition.patch
var/spack/packages/rose/package.py

Squashed commits from Pull Request #8.

Add Packages for ROSE and JDK

---

var/spack/packages/Mitos/package.py
var/spack/packages/memaxes/package.py

Fixed MemAxes checksum and added one for Mitos as well.

MemAxes and Mitos

---

var/spack/packages/libuuid/package.py
var/spack/packages/task/package.py
var/spack/packages/taskd/package.py

Also packages for taskwarrior and its sync daemon.

package files for libuuid, needed for flux and taskwarrior packages

---

var/spack/packages/py-cffi/package.py
var/spack/packages/py-pycparser/package.py

Package for a python-native FFI wrapper.

Python cffi

---

var/spack/packages/vim/package.py

This adds support for some of the basic options of the vim build.  Many remain to be added, but these are the ones with straightforward support based on existing package availability.

partial upgrade to vim package

---

lib/spack/spack/modules.py
var/spack/packages/ruby/package.py
var/spack/packages/tmuxinator/package.py

See commit messages.  Ruby/gem support could use some more work, but thought on how all of that is going to work is necessary first.

Partial ruby extension and tmuxinator package

---

lib/spack/spack/fetch_strategy.py

Certain remote protocols don't support the `--depth` option.  Since this can't
be checked by URL type or in any sane way locally, this version attempts to
clone git repositories with the --depth option, and if that fails attempts the
clone again without it.

adding a fallback on failure with git --depth

---

var/spack/packages/libpciaccess/package.py
var/spack/packages/libxml2/package.py
var/spack/packages/mesa/package.py
var/spack/packages/py-mock/package.py
var/spack/packages/py-pandas/package.py
var/spack/packages/py-setuptools/package.py

Py-pandas was missing some dependencies, and _those_ dependencies were also missing some dependencies. 
Fixed with help from @karenyyng , thanks!

Fixed py-pandas package

---

var/spack/packages/bowtie2/bowtie2-2.5.patch
var/spack/packages/bowtie2/package.py
var/spack/packages/samtools/package.py
var/spack/packages/samtools/samtools1.2.patch

Going to start adding bioinformatics software once I know it works without any hiccups. 
Samtools comes with a patch that changes D_CURSES_LIB=1 to 0.

Added samtools bioinformatics software

---

README.md

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

README.md: trivial typo fix

---

var/spack/packages/ncdu/package.py

Pretty useful for dealing with quota issues on remote machines.

Added ncdu package

---

var/spack/packages/mpich/package.py

Similar to the Open MPI and MVAPICH packages.
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

mpich: add fine-grained MPI conformance versions

---

var/spack/packages/openmpi/package.py

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

openmpi: update package versions of Open MPI

---

var/spack/packages/zsh/package.py

The ZSH archives are now on SourceForge.

Update ZSH version

---

var/spack/packages/judy/package.py

add judy dynamic array/meta-trie/hash table lib

---

var/spack/packages/openssl/package.py

Reverts scalability-llnl/spack#189.  Mistakenly merged WIP.

Revert "WIP: openssl: set KERNEL_BITS to make ./config work"

---

var/spack/packages/Mitos/package.py

"Fix" for Mitos by removing the unnecessary Boost dependency like we talked about.

Fixed Mitos dependency and added new version

---

var/spack/packages/binutils/package.py
var/spack/packages/gcc/package.py

gcc : changed objdir to something out of srcdir and added '--with-sysroot=/'
binutils : added '--with-sysroot=/'

Fix for #177

---

var/spack/packages/gdb/package.py
var/spack/packages/texinfo/package.py

Just a basic installation of gdb

gdb : added package

---

var/spack/packages/fftw/package.py

Available variants:
* floating point precision
* mpi

fftw : added package

---

lib/spack/spack/directory_layout.py

Fix #206: need to make deps AND root concrete when read in.

---

var/spack/packages/gsl/package.py

gsl : added package

---

bin/spack

added option to enable pdb debug

---

var/spack/packages/lmod/package.py

Added Lmod package

---

lib/spack/spack/cmd/fetch.py
lib/spack/spack/cmd/mirror.py
lib/spack/spack/mirror.py
var/spack/packages/py-cffi/package.py

Small additions to fetch to make it easier to fetch all files necessary for a
build on a system without network connectivity.

fetch: add options to fetch missing or all deps

---

var/spack/packages/valgrind/package.py

valgrind : added package

---

lib/spack/spack/package.py

@alalazo: can you take a look at this fix?  I haven't tested it rigorously but I believe it provides better patch semantics.  If you approve I'll merge.
This fixes #154

Fix #154 -- better log messages for do_patch()

---

var/spack/packages/libedit/package.py
var/spack/packages/ninja/package.py
var/spack/packages/py-blessings/package.py
var/spack/packages/py-coverage/package.py
var/spack/packages/py-mysqldb1/package.py
var/spack/packages/py-tappy/package.py
var/spack/packages/py-urwid/package.py

A pile of libraries and tools, libedit is actually important as a
replacement of readline for non-GPL projects.  Also ninja may be
worthwhile for some of the larger CMake projects, like llvm/clang.
Found these as I was cleaning up my spack tree, thought they might as well go in.

python libraries, libedit, and ninja

---

var/spack/packages/pcre2/package.py

This is a major update of the package PCRE. It seems both PCRE and PCRE2 can be installed at the same time; their APIs are different.

New package PCRE2

---

var/spack/packages/julia/package.py

Note that this branch is based on the `correct-cc` branch, not on the `develop` branch.

Add package for Julia

---

var/spack/packages/fftw/package.py

FFTW can build only one floating point precision (float, double, long double, quad) at once, but they can all be installed simultaneously as the libraries have different names. It is common packages to decide only at run time which precision FFTW they need, and thus FFTW should offer all precisions at once.

Build multiple FFTW variants simultaneously

---

var/spack/packages/boost/package.py

Ensure that builds on Darwin use the "darwin" toolset.
Also update Boost to 1.60.0.

Support Darwin for Boost

---

var/spack/packages/atop/package.py

`atop` is a `top`-like process viewer.

New package atop

---

var/spack/packages/hdf5/package.py

+cxx, +fortran: Enable support for the respective languages
+threadsafe: Enable multi-threading

Enable several variants for HDF5

---

var/spack/packages/cgal/package.py

Notes:
- no support yet for Qt or external libraries

Added package : cgal

---

var/spack/packages/fltk/font.patch
var/spack/packages/fltk/package.py
var/spack/packages/gmsh/package.py

Features : 
Notes : 
Support for `gmm`, `mumps`, `petsc`, `tetgen` is still missing. I will provide it in a later PR.

Added package : gmsh

---

var/spack/packages/R/package.py

Modifications :
Manually tested :
- Ubuntu 14.04 with GCC 5.3

R : updated package

---

var/spack/repos/builtin/packages/eigen/package.py

Notes:
- some dependencies are still missing, I plan to add them at a later stage.

eigen : added package

---

var/spack/repos/builtin/packages/mpfr/package.py

This pull request is in response to the decision reached in #341

Remove constraint on dependency version

---

var/spack/repos/builtin/packages/boost/boost_11856.patch
var/spack/repos/builtin/packages/boost/package.py

See: https://svn.boost.org/trac/boost/ticket/11856

Patch fix for boost@1.60.0%gcc@4.4.7

---

lib/spack/spack/repository.py

proposed fix for #398
I just copied the implementation from the Repo class and it appears to fix the issue.

fix for issue 398, added extensions_for in RepoPath

---

var/spack/repos/builtin/packages/cmocka/package.py

adding the cmocka unit testing library

---

var/spack/repos/builtin/packages/netcdf/package.py

This pull request is currently blocked by #339. Until the new HDF package is added, I won't be able to test my changes. Please let me know if there is anything preventing #339 from being merged and I will fix it.
I'm not sure how well the new experimental feature for building NetCDF-Fortran works. If it doesn't work, I'll just have to add a separate NetCDF-Fortran package.

Extensive modifications to NetCDF package

---

lib/spack/spack/cmd/md5.py

As I needed it and it was mentioned in #283, here is a modification to `spack md5` to pass the url to the stager in case if is not a local file.

spack md5 on urls

---

var/spack/repos/builtin/packages/fish/package.py

This change is in response to Issue #103. See the issue for details on why this change is necessary.

Modify url settings for fish package

---

var/spack/repos/builtin/packages/opencv/package.py

Added : 
Notes:
- still misses GUI and additional packages support. They will eventually come in a later PR

Added package : OpenCV

---

var/spack/repos/builtin/packages/dakota/package.py

Basic installation of the package. Misses options for advanced customizations (external trilinos, X windows support, etc. ) that can be added in later PRs.

Added package : dakota

---

var/spack/repos/builtin/packages/arpack-ng/package.py

Notes : 
- this package is a maintained version of `arpack` and `parpack` based on autotools
- it may be worth considering the removal of `arpack` and `parpack` from `builtin`

Added package : arpack-ng

---

var/spack/repos/builtin/packages/fftw/package.py
var/spack/repos/builtin/packages/gromacs/package.py

Added package : gromacs

---

var/spack/repos/builtin/packages/llvm/package.py

Version `develop` and `trunk` seem to be duplicate of each other. Removed one of them.

Cleaned package : llvm

---

lib/spack/docs/basic_usage.rst
lib/spack/spack/modules.py

This pull request adds CPATH to the module files. This will allow the header files to be available for development outside of spack.

Add CPATH pointing to include directories.

---

lib/spack/spack/cmd/checksum.py
lib/spack/spack/cmd/compiler.py
lib/spack/spack/cmd/create.py
lib/spack/spack/cmd/mirror.py
lib/spack/spack/cmd/module.py
lib/spack/spack/cmd/repo.py
lib/spack/spack/config.py
lib/spack/spack/database.py
lib/spack/spack/directives.py
lib/spack/spack/directory_layout.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/mirror.py
lib/spack/spack/package.py
lib/spack/spack/repository.py
lib/spack/spack/stage.py

Periods have been removed from ends of message.

Removed periods.  Should help use of cut'n'paste from console windows.

---

var/spack/repos/builtin/packages/zfp/package.py

Adding zfp for @markcmiller86.

Adding zfp package.

---

var/spack/repos/builtin/packages/llvm/package.py

I copied the LLVM 3.7.0 stanza from `llvm/package.py` into a new LLVM 3.7.1 stanza and updated all the MD5 hashes.

Added LLVM 3.7.1 support

---

var/spack/repos/builtin/packages/libsigsegv/package.py
var/spack/repos/builtin/packages/m4/package.py

http://www.perzl.org/aix/index.php?n=Main.M4

GNU m4 depends on libsigsegv

---

var/spack/repos/builtin/packages/petsc/package.py

After `do_install` the build will possibly fail with an error that is unrelated to the package modifications: 
```
File "/home/culpo/github/spack/bin/spack", line 176, in <module>
main()
File "/home/culpo/github/spack/bin/spack", line 154, in main
return_val = command(parser, args)
File "/home/culpo/github/spack/lib/spack/spack/cmd/install.py", line 81, in install
fake=args.fake)
File "/home/culpo/github/spack/lib/spack/spack/package.py", line 946, in do_install
spack.hooks.post_install(self)
File "/home/culpo/github/spack/lib/spack/spack/hooks/__init__.py", line 69, in __call__
hook(pkg)
File "/home/culpo/github/spack/lib/spack/spack/hooks/sbang.py", line 75, in post_install
if shebang_too_long(path):
File …
```

Improved package : petsc

---

var/spack/repos/builtin/packages/petsc/package.py

For review by @citibeth and @alalazo.  I have attempted to merge the concurrent changes to petsc.

Merge @citibeth and @alalazo's petsc fixes from #515 and #517

---

lib/spack/spack/preferred_packages.py

This should fix issue issue #530

Fix type error that was causing mis-ordering of compiler versions

---

lib/spack/spack/concretize.py

The new preferred packages system wasn't working for satisfies.  This should fix those issues.  I'll work on expanding regressions tests for this and the other issue soon.

Fix issue with preferred satisfies not being respected

---

var/spack/repos/builtin/packages/emacs/package.py

Added Emacs package.
Q: What to do about Emacs dependencies on the window system, libtiff, etc.  For now, I just assume Emacs will pick them all up from the system.  This is a fair assumption: Emacs is just for using, not linking against; we will be less particular about its dependencies.

Added Emacs package

---

var/spack/repos/builtin/packages/emacs/package.py
var/spack/repos/builtin/packages/netlib-lapack/package.py

Minor comment change to Emacs
New version of LAPACK

Misc. Updates

---

var/spack/repos/builtin/packages/gl2ps/package.py
var/spack/repos/builtin/packages/octave/package.py
var/spack/repos/builtin/packages/qrupdate/package.py

Note: I haven't even tried installing this package myself yet
Just wanted to get this PR out there so people can take a look at it. I still have to add package files for a couple of optional dependencies and actually try to install Octave.

Add GNU Octave package

---

lib/spack/spack/cmd/diy.py

Small bug in DIY found and fixed.

---

var/spack/repos/builtin/packages/paraview/package.py

Paraview python

---

var/spack/repos/builtin/packages/petsc/package.py

I think the proper fix is to add `-Qunused-arguments` to Spack wrappers when using clang. If someone tells me where that is, i will update the PR and test it.

fix petsc on osx

---

var/spack/repos/builtin/packages/tbb/package.py

work-in-progress. Funny enough download fails in Spack, but it works with the same link manually or with homebrew.

add Intel TBB package

---

var/spack/repos/builtin/packages/hypre/package.py

@eschnett: I took your changes to the hypre in this PR.

temporary fix Hypre for OSX by building static lib by default

---

var/spack/repos/builtin/packages/openblas/package.py

fixes https://github.com/LLNL/spack/issues/621

blacklist Openblas 0.2.16 for missing _dggsvd_ and _sggsvd_

---

lib/spack/spack/modules.py
var/spack/repos/builtin/packages/python/package.py

Fix : PYTHONPATH missing in module files

---

var/spack/repos/builtin/packages/py-netcdf/package.py

When I add new packages to Spack, they go here; merge at your convenience.

New Package: py-netcdf

---

var/spack/repos/builtin/packages/mumps/Makefile.inc
var/spack/repos/builtin/packages/mumps/package.py

@nrichart: any comments/wishes?

add shared variant to mumps (needed for Trilinos) plus tests

---

lib/spack/spack/fetch_strategy.py

- Restage previously only removed the source directory from the stage.
- Now removes any other directories in stage as well.

Fix bug in restage

---

var/spack/repos/builtin/packages/hypre/package.py
var/spack/repos/builtin/packages/muparser/package.py

@tgamblin these are very minor fixes i found out when building on Ubuntu.

minor fixes to hypre and muparser on Linux

---

var/spack/repos/builtin/packages/gdal/package.py
var/spack/repos/builtin/packages/kealib/package.py
var/spack/repos/builtin/packages/openjpeg/package.py
var/spack/repos/builtin/packages/py-tuiview/package.py

A few packages; GDAL, kealib, openjpeg, tuiview.
kealib and openjpeg are optional additional drivers for GDAL to operate with. And tuiview is an image and vector GUI utilising GDAL.

Upload of GDAL, kealib, openjpeg, py-tuiview package builds.

---

var/spack/repos/builtin/packages/trilinos/package.py
var/spack/repos/builtin/packages/trilinos/umfpack_from_suitesparse.patch

blocked by:
https://github.com/LLNL/spack/issues/634 (OSX only)

Trilinos extra

---

var/spack/repos/builtin/packages/petsc/package.py

fixed by https://github.com/LLNL/spack/pull/677

petsc: remove no longer needed -Qunused-arguments hack

---

var/spack/repos/builtin/packages/py-bottleneck/package.py
var/spack/repos/builtin/packages/py-dateutil/package.py
var/spack/repos/builtin/packages/py-matplotlib/package.py
var/spack/repos/builtin/packages/py-nose/package.py
var/spack/repos/builtin/packages/py-numexpr/package.py
var/spack/repos/builtin/packages/py-numpy/package.py
var/spack/repos/builtin/packages/py-pandas/package.py
var/spack/repos/builtin/packages/py-pytz/package.py
var/spack/repos/builtin/packages/py-setuptools/package.py
var/spack/repos/builtin/packages/py-six/package.py
var/spack/repos/builtin/packages/py-virtualenv/package.py

The goal of this PR is to get py-pandas working. Along the way, I updated some of the python packages. The py-pandas package had some dependencies that, as far as I can tell, are not needed. I also removed some other python dependencies that are optional according to the pandas project.
http://pandas.pydata.org/pandas-docs/stable/install.html
I also added a couple of python packages that are recommended, one of which, py-bottleneck, is a new spack package.

Get py-pandas working plus some python package updates

---

README.md

---
@tgamblin @eschnett Partially addresses #171.

docs: add a link to the spack repo in the PR section

---

var/spack/repos/builtin/packages/doxygen/package.py

fixes https://github.com/LLNL/spack/issues/686

doxygen: add missing dependencies

---

var/spack/repos/builtin/packages/dealii/package.py

add deal.ii package

---

var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/oce/null.patch
var/spack/repos/builtin/packages/oce/package.py

i also added TBB to OCE and removed FIXME in deal.ii.

oce: fix bugs related to NULL pointers and compiler optimisation

---

var/spack/repos/builtin/packages/espresso/package.py

Also, better(?) fix for #454, in that espresso is installed to
cannonical unix subdir.

Fixes install issues on OS/X for Quantum Espresso

---

var/spack/repos/builtin/packages/qt/package.py

I messed up #427 when trying to resolve conflicts, so here it is again.

Add url_for_version function and gtk variant

---

var/spack/repos/builtin/packages/zoltan/package.py

The changes in this pull request add the `zoltan` package to Spack, which is a dynamic load-balancing and problem partitioning library developed at Sandia National Laboratory.  Please let me know if there are any problems with this new package and I'll try to fix them as soon as I can!

Add Package : Zoltan

---

lib/spack/spack/build_environment.py
lib/spack/spack/test/install.py
var/spack/repos/builtin.mock/packages/cmake-client/package.py
var/spack/repos/builtin.mock/packages/cmake/package.py

- Also added better regression tests for build environment.

Fix #620, Resolve #664. Fix issues with build environment.

---

var/spack/repos/builtin/packages/git/package.py

Comments used to describe an additional latent dependency.

git: added comment about newly discovered dependency

---

var/spack/repos/builtin/packages/tcl/package.py
var/spack/repos/builtin/packages/tk/package.py

Added recent versions and fixed a bug.

Fixed TCL/Tk

---

lib/spack/env/cc

This is just a cleanup, no functionality should change.

Clean up cc script

---

var/spack/repos/builtin/packages/netlib-lapack/package.py

@tgamblin I am resubmitting this proposed change because it was accidentally overwritten. These modifications were accepted as PR#741 but somehow I clobbered them when PR#742 was merged. There was some unintentional overlap in my local repository that I didn't straighten out before pushing. Sorry.  Can you merge this again?

Second attempt at PR#741

---

lib/spack/spack/cmd/module.py
lib/spack/spack/modules.py
lib/spack/spack/test/mock_database.py

fix : module files are deleted on uninstall (fixes #216)

---

var/spack/repos/builtin/packages/global/package.py

I added an explicit dependency on ncurses.

Package global depends on ncurses

---

var/spack/repos/builtin/packages/elk/package.py
var/spack/repos/builtin/packages/libxc/package.py
var/spack/repos/builtin/packages/openblas/package.py

The OpenBLAS changes were discussed in #771

Add Elk package

---

var/spack/repos/builtin/packages/papi/package.py

- don't use <malloc.h>
- run install_name_tool

Make PAPI build on Darwin

---

lib/spack/docs/basic_usage.rst

@citibeth have a look. These changes reflect my experience on Ubuntu 14.04.

minor cleanup of environment-modules documentation

---

lib/spack/spack/cmd/compiler.py

---
Not sure about the second commit; can back it out if wanted.
Cc: @davydden @tgamblin

Spack compiler find

---

var/spack/repos/builtin/packages/mfem/package.py

MFEM is a free, lightweight, scalable C++ library for finite element
methods.

MFEM version 3.1

---

lib/spack/docs/basic_usage.rst

Compiler find docs

---

var/spack/repos/builtin/packages/py-SQLAlchemy/package.py
var/spack/repos/builtin/packages/py-csvkit/package.py
var/spack/repos/builtin/packages/py-dbf/package.py
var/spack/repos/builtin/packages/py-jdcal/package.py
var/spack/repos/builtin/packages/py-openpyxl/package.py
var/spack/repos/builtin/packages/py-xlrd/package.py

This adds the py-csvkit package and needed dependencies for working with
csv files.

Add py-csvkit package

---

var/spack/repos/builtin/packages/openblas/package.py

See: https://github.com/xianyi/OpenBLAS/wiki/faq#static_link

openblas: Added +fpic variant to package.

---

share/spack/setup-env.sh

check that a target directory exists before committing to cd

---

share/spack/setup-env.sh

More appropriate test, and fixed spacing.

switched test to use -d for location check

---

var/spack/repos/builtin/packages/glm/package.py

Add CMake as a dependency for building glm

Add missing dependency for glm

---

var/spack/repos/builtin/packages/raja/package.py

Added a package for the RAJA system

---

var/spack/repos/builtin/packages/mrnet/package.py

added git commit for clang support

---

var/spack/repos/builtin/packages/gcc/package.py

I would love to test this, but gmp won't download for me...

Add latest version of GCC

---

var/spack/repos/builtin/packages/netcdf/package.py

See #414 for the preliminary discussion on this.

Remove hdf5 ~cxx constraint on netcdf

---

lib/spack/spack/compiler.py
lib/spack/spack/compilers/gcc.py

Submitting on behalf of Adam Lyon.

Handle c++11 and c++14 correctly

---

var/spack/repos/builtin/packages/mpich/package.py
var/spack/repos/builtin/packages/openmpi/package.py

Adding pmi variants and support, along with hydra support in MPICH.

add pmi support and process managers to the MPIs

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/compiler.py
lib/spack/spack/compilers/clang.py
lib/spack/spack/compilers/gcc.py
lib/spack/spack/compilers/intel.py
lib/spack/spack/compilers/nag.py
lib/spack/spack/compilers/pgi.py
lib/spack/spack/compilers/xl.py

fixes https://github.com/LLNL/spack/issues/876
@adamjstewart ping.

Compiler::openmp_flag()

---

var/spack/repos/builtin/packages/gdb/package.py

Added gdb 7.11 to the available versions.

Added gdb 7.11 released on 24 Feb 2016

---

lib/spack/spack/build_environment.py

This lets me build against the pure-include package Eigen.

Add  to sub dirs checked for pkg-config files.

---

var/spack/repos/builtin/packages/openblas/package.py

fixes https://github.com/LLNL/spack/issues/799 .
@adamjstewart @gartung ping.

openblas: do not use OpenMP with Clang

---

bin/spack
lib/spack/spack/cmd/compiler.py
lib/spack/spack/config.py
lib/spack/spack/test/config.py

fix: proper update of config file

---

var/spack/repos/builtin/packages/silo/package.py
var/spack/repos/builtin/packages/visit/package.py

- Adds VisIt v2.10.1
- Useful as is, but can be enhanced later by adding more variants and more dependencies from spack

VisIt v2.10.1

---

var/spack/repos/builtin/packages/moab/package.py
var/spack/repos/builtin/packages/py-flake8/package.py

This commit provides a basic MOAB installation.  MOAB has many optional features that I did not setup or test.  I will leave the addition of those variants to someone who is actually using them.
Information on MOAB: https://bitbucket.org/fathomteam/moab
MOAB is a component for representing and evaluating mesh data. MOAB can store structured and unstructured mesh, consisting of elements in the finite element 'zoo.' The functional interface to MOAB is simple yet powerful, allowing the representation of many types of metadata commonly found on the mesh. MOAB is optimized for efficiency in space and time, based on access to mesh in chunks rather than through individual entities, while also versatile enough to support individual entity access

Provide new package: MOAB

---

var/spack/repos/builtin/packages/openblas/package.py

as discussed here https://github.com/LLNL/spack/issues/846#issuecomment-215633754, the "fix" introduced in https://github.com/LLNL/spack/pull/751 does not actually work. Therefore better revert it  and add a comment on possible pitfalls and workarounds.

openblas: use spack_cc/spack_f77 and add a note on compiler mixing

---

var/spack/repos/builtin/packages/turbomole/package.py

This PR updates the turbomole package file but does not introduce any
new funtionality. The updates are:
- use spack interface for subprocess.PIPE and subprocess.Popen
- clean up based on flake8
- remove some extra whitespace

Updated turbomole package file.

---

lib/spack/spack/spec.py

Patch generously provided by @becker33.
Closes #928.

Remove duplicate providers that can concretize to the same result

---

lib/spack/spack/cmd/find.py

The relevant change is :
```python
explicit = any
```
instead of
```python
explicit = None
```
The other bits are just to please `flake8`.

Fix : spack find

---

lib/spack/docs/basic_usage.rst
lib/spack/spack/cmd/find.py
lib/spack/spack/database.py
lib/spack/spack/spec.py
var/spack/repos/builtin/packages/py-autopep8/package.py
var/spack/repos/builtin/packages/py-pep8/package.py

Small doc addition for explicit on find and various flake8 fixes related to same.

initial docs for find and flake8 cleanup

---

var/spack/repos/builtin/packages/openmpi/package.py

Auto-detect location of verbs library.
Enable verbs by default if verbs library is detected.
Closes #970.

Auto-detect verbs location

---

var/spack/repos/builtin/packages/dealii/package.py

Included additional versions for Deal.II package.

Dealii, Versions added

---

var/spack/repos/builtin/packages/fenics/package.py
var/spack/repos/builtin/packages/py-ply/package.py

I put all the components (ufl, ffc, fiat, instant, dolphin) in one package, this is how they package it for debian and ubuntu.

Adding package FEniCS

---

lib/spack/spack/config.py

Fixed config format to allow default compiler flags

---

var/spack/repos/builtin/packages/libdwarf/package.py

fixing my aggressive removal of old versions

put older versions back + version-specific dwarfdump dir

---

lib/spack/spack/test/versions.py
lib/spack/spack/version.py
var/spack/repos/builtin/packages/lmod/package.py
var/spack/repos/builtin/packages/lua-luafilesystem/package.py
var/spack/repos/builtin/packages/lua/package.py

lmod : updated package and dependencies

---

var/spack/repos/builtin/packages/c-blosc/package.py
var/spack/repos/builtin/packages/hdf5-blosc/package.py

"Blosc, an extremely fast, multi-threaded, meta-compressor library".

Add packages c-blosc and hdf5-blosc

---

var/spack/repos/builtin/packages/bertini/package.py
var/spack/repos/builtin/packages/flex/package.py

Also add missing dependency. Flex would not build for me without bison. It complained about not being able to find `yacc`.

Add bertini package

---

var/spack/repos/builtin/packages/py-astropy/package.py
var/spack/repos/builtin/packages/py-beautifulsoup4/package.py
var/spack/repos/builtin/packages/py-emcee/package.py
var/spack/repos/builtin/packages/py-h5py/package.py
var/spack/repos/builtin/packages/py-iminuit/package.py
var/spack/repos/builtin/packages/py-nestle/package.py
var/spack/repos/builtin/packages/py-sncosmo/package.py
var/spack/repos/builtin/packages/py-wcsaxes/package.py
var/spack/repos/builtin/packages/python/package.py

Everything installs and activates just fine. I'm getting errors when importing sncosmo at the moment, but I'll work on those on Monday.

Add py-sncosmo package

---

var/spack/repos/builtin/packages/armadillo/package.py
var/spack/repos/builtin/packages/arpack/package.py
var/spack/repos/builtin/packages/superlu/package.py

Had to add `-fPIC` to ARPACK and SuperLU to get Armadillo to build.

Add Armadillo and SuperLU packages

---

lib/spack/llnl/util/filesystem.py
var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/petsc/package.py
var/spack/repos/builtin/packages/slepc/package.py
var/spack/repos/builtin/packages/superlu-dist/package.py
var/spack/repos/builtin/packages/trilinos/package.py

mostly add new versions and specify version dependencies plus clean-up of superlu-dist.

update Petsc, Slepc, Trilinos, Superlu-dist and deal.II

---

var/spack/repos/builtin/packages/r-packrat/package.py

Manage the R packages your project depends on in an isolated, portable,
and reproducible way.
https://github.com/rstudio/packrat/

new package: r-packrat

---

var/spack/repos/builtin/packages/r-R6/package.py
var/spack/repos/builtin/packages/r-curl/package.py
var/spack/repos/builtin/packages/r-devtools/package.py
var/spack/repos/builtin/packages/r-digest/package.py
var/spack/repos/builtin/packages/r-git2r/package.py
var/spack/repos/builtin/packages/r-httr/package.py
var/spack/repos/builtin/packages/r-jsonlite/package.py
var/spack/repos/builtin/packages/r-memoise/package.py
var/spack/repos/builtin/packages/r-mime/package.py
var/spack/repos/builtin/packages/r-openssl/package.py
var/spack/repos/builtin/packages/r-rstudioapi/package.py
var/spack/repos/builtin/packages/r-whisker/package.py
var/spack/repos/builtin/packages/r-withr/package.py

This PR brings in the R devtools package and it dependencies.

new package: r-devtools

---

lib/spack/spack/hooks/sbang.py

do not create shebang.bak file

---

lib/spack/docs/packaging_guide.rst

fixes https://github.com/LLNL/spack/issues/894

document blas and lapack usage in packages

---

lib/spack/docs/basic_usage.rst
lib/spack/spack/cmd/list.py

Generally making list a little more flexible.

cmd/list: adding description search and glob by default

---

lib/spack/spack/cmd/compiler.py
lib/spack/spack/compilers/__init__.py
lib/spack/spack/compilers/gcc.py

Fix for #1071 Should now tell you when compilers are added when config is empty using compiler add/find and should also find gfortran compilers.

Bugfix/compiler find and gfortran fix.

---

lib/spack/spack/build_environment.py

This addresses the symptoms I see in #1095.

Import which from spack.util.executable; Fixes #1095

---

bin/sbang
lib/spack/spack/hooks/sbang.py
lib/spack/spack/test/sbang.py

Fixes #1101.
@alalazo: does this work for you?

Make sbang handle lua

---

lib/spack/spack/database.py

Improved error messages should be self explanatory.

Improved Spack database errors to help users fix them.

---

var/spack/repos/builtin/packages/autoconf/package.py
var/spack/repos/builtin/packages/automake/package.py
var/spack/repos/builtin/packages/libtool/package.py
var/spack/repos/builtin/packages/swift/package.py
var/spack/repos/builtin/packages/swiftsim/package.py

swift : added new package

---

var/spack/repos/builtin/packages/dealii/package.py

fixes minor issue introduced in https://github.com/LLNL/spack/pull/1001 where some tests were not executed when compiling `dev` version.

dealii: run more unit tests when building @dev

---

lib/spack/spack/cmd/create.py

Make spack create automatically add dependencies for build system

---

var/spack/repos/builtin/packages/py-docutils/package.py
var/spack/repos/builtin/packages/py-restview/package.py

Restview is a program that allows you to view .rst (reStructuredText) files and live-edit them.

Add py-restview package

---

var/spack/repos/builtin/packages/r-bh/package.py
var/spack/repos/builtin/packages/r-colorspace/package.py
var/spack/repos/builtin/packages/r-dichromat/package.py
var/spack/repos/builtin/packages/r-ggplot2/package.py
var/spack/repos/builtin/packages/r-gridextra/package.py
var/spack/repos/builtin/packages/r-gtable/package.py
var/spack/repos/builtin/packages/r-inline/package.py
var/spack/repos/builtin/packages/r-labeling/package.py
var/spack/repos/builtin/packages/r-lattice/package.py
var/spack/repos/builtin/packages/r-magrittr/package.py
var/spack/repos/builtin/packages/r-mass/package.py
var/spack/repos/builtin/packages/r-matrix/package.py
var/spack/repos/builtin/packages/r-munsell/package.py
var/spack/repos/builtin/packages/r-plyr/package.py
var/spack/repos/builtin/packages/r-rcolorbrewer/package.py
var/spack/repos/builtin/packages/r-rcpp/package.py
var/spack/repos/builtin/packages/r-rcppeigen/package.py
var/spack/repos/builtin/packages/r-reshape2/package.py
var/spack/repos/builtin/packages/r-rstan/package.py
var/spack/repos/builtin/packages/r-scales/package.py
var/spack/repos/builtin/packages/r-stanheaders/package.py
var/spack/repos/builtin/packages/r-stringi/package.py
var/spack/repos/builtin/packages/r-stringr/package.py

This PR creates the RStan package and its dependencies.

New package - RStan

---

var/spack/repos/builtin/packages/openssl/package.py

fixes : reserved name for system packages

---

var/spack/repos/builtin/packages/py-h5py/package.py

Don't enforce `hdf5~mpi`

---

var/spack/repos/builtin/packages/arpack-ng/make_install.patch
var/spack/repos/builtin/packages/arpack-ng/package.py
var/spack/repos/builtin/packages/arpack-ng/parpack_cmake.patch

update arpack, fix their cmake.
tested on macOS.

Pkg/arpack 3.4.0

---

var/spack/repos/builtin/packages/libjson-c/package.py

json-c: fix build by running serially

---

var/spack/repos/builtin/packages/r-lubridate/package.py

Functions to work with date-times and timespans.

New package - r-lubridate

---

var/spack/repos/builtin/packages/r-assertthat/package.py
var/spack/repos/builtin/packages/r-dplyr/package.py
var/spack/repos/builtin/packages/r-lazyeval/package.py
var/spack/repos/builtin/packages/r-tibble/package.py

This brings in dplyr and dependencies.

New package - r-dplyr

---

var/spack/repos/builtin/packages/dealii/package.py

@jppelteret let me know if you have any comments on this update of deal.ii.
p.s. for convenience, here are the changes without whitespaces https://github.com/LLNL/spack/pull/1207/files?w=1

dealii: update for petsc37

---

var/spack/repos/builtin/packages/r-tidyr/package.py

Tools for changing the layout of data sets.

New package - r-tidyr

---

var/spack/repos/builtin/packages/bzip2/package.py

Fixes #1212. There were a lot of flake8 changes, so I separated them out into two commits.

Patch both bzip2 makefiles

---

lib/spack/docs/basic_usage.rst

the packages that depends on => the packages that depend on

Minor typo fix

---

var/spack/repos/builtin/packages/r-ggvis/package.py
var/spack/repos/builtin/packages/r-htmltools/package.py
var/spack/repos/builtin/packages/r-httpuv/package.py
var/spack/repos/builtin/packages/r-shiny/package.py
var/spack/repos/builtin/packages/r-xtable/package.py

Bring in ggvis and dependencies.
GGvis is an implementaion of the 'Grammar of Graphics', combined with
shiny.

New package - r-ggvis

---

lib/spack/docs/packaging_guide.rst

doc : fixes #1239

---

var/spack/repos/builtin/packages/mkl/package.py

@adamjstewart ping.
tested with Arpack on macOS with external MKL.

mkl: add provide blas/lapack

---

var/spack/repos/builtin/packages/py-numpy/package.py

py-numpy: Add py-setuptools dependencies

---

lib/spack/spack/cmd/bootstrap.py

Fixes #352.
---
@JohnWestlund @tgamblin

bootstrap: fall back to the default upstream URL

---

var/spack/repos/builtin/packages/cmake/package.py

cmake@3.6.0

---

.gitignore

Re-ignore licenses directory

---

var/spack/repos/builtin/packages/cdo/package.py

Magic tool for dealing with grib and netcdf files. Builds with cray-netcdf, woohoo!

Climate Data Operators

---

lib/spack/docs/basic_usage.rst
lib/spack/spack/architecture.py
lib/spack/spack/build_environment.py
lib/spack/spack/platforms/cray_xc.py

Make default link behavior on cray platform dynamic to be more similar to other systems.

Cray linker

---

var/spack/repos/builtin/packages/R/package.py

This commit adds `setup_environment` to export the libraries and
headers.
Fixes #1314.

Set environment variables for R

---

lib/spack/docs/basic_usage.rst

This PR updates the documentation to make use of the functionality added in #1246.

Update documentation for recursive module loading

---

var/spack/repos/builtin/packages/openssl/package.py

Resolves #1332.  
- OpenSSL no longer checks remote versions on the openssl site.
- Spack is used on systems that aren't connected to the internet, and
this check is probably in the wrong place and affects too many
commands.  We can work on figuring out a better, more configurable
place to put a check like this.
@alalazo @KineticTheory @citibeth @adamjstewart

Remove remote website pinging from OpenSSL

---

var/spack/repos/builtin/packages/r-base64enc/package.py
var/spack/repos/builtin/packages/r-cluster/package.py
var/spack/repos/builtin/packages/r-codetools/package.py
var/spack/repos/builtin/packages/r-diagrammer/package.py
var/spack/repos/builtin/packages/r-doparallel/package.py
var/spack/repos/builtin/packages/r-dt/package.py
var/spack/repos/builtin/packages/r-dygraphs/package.py
var/spack/repos/builtin/packages/r-foreach/package.py
var/spack/repos/builtin/packages/r-gridbase/package.py
var/spack/repos/builtin/packages/r-htmlwidgets/package.py
var/spack/repos/builtin/packages/r-igraph/package.py
var/spack/repos/builtin/packages/r-influencer/package.py
var/spack/repos/builtin/packages/r-irlba/package.py
var/spack/repos/builtin/packages/r-iterators/package.py
var/spack/repos/builtin/packages/r-leaflet/package.py
var/spack/repos/builtin/packages/r-markdown/package.py
var/spack/repos/builtin/packages/r-networkd3/package.py
var/spack/repos/builtin/packages/r-nmf/package.py
var/spack/repos/builtin/packages/r-pkgmaker/package.py
var/spack/repos/builtin/packages/r-png/package.py
var/spack/repos/builtin/packages/r-raster/package.py
var/spack/repos/builtin/packages/r-registry/package.py
var/spack/repos/builtin/packages/r-rngtools/package.py
var/spack/repos/builtin/packages/r-sp/package.py
var/spack/repos/builtin/packages/r-threejs/package.py
var/spack/repos/builtin/packages/r-visnetwork/package.py
var/spack/repos/builtin/packages/r-xts/package.py
var/spack/repos/builtin/packages/r-yaml/package.py
var/spack/repos/builtin/packages/r-zoo/package.py

This PR add R packages for htmlwidgets.

New packages - R htmlwidgets

---

lib/spack/spack/spec.py
lib/spack/spack/test/cmd/test_install.py

qa : minor cleanup

---

var/spack/repos/builtin/packages/openssl/package.py

Fixes #1349, which was broken by #1333

Fix OpenSSL url_for_version

---

var/spack/repos/builtin/packages/r-car/package.py
var/spack/repos/builtin/packages/r-lme4/package.py
var/spack/repos/builtin/packages/r-matrixmodels/package.py
var/spack/repos/builtin/packages/r-mgcv/package.py
var/spack/repos/builtin/packages/r-minqa/package.py
var/spack/repos/builtin/packages/r-nlme/package.py
var/spack/repos/builtin/packages/r-nloptr/package.py
var/spack/repos/builtin/packages/r-nnet/package.py
var/spack/repos/builtin/packages/r-pbkrtest/package.py
var/spack/repos/builtin/packages/r-quantreg/package.py
var/spack/repos/builtin/packages/r-sparsem/package.py

Companion to Applied Regression.

New package r-car

---

var/spack/repos/builtin/packages/r-randomforest/package.py

Breiman and Cutler's Random Forests for Classification and Regression.

New package r-randomforest

---

var/spack/repos/builtin/packages/r-multcomp/package.py
var/spack/repos/builtin/packages/r-mvtnorm/package.py
var/spack/repos/builtin/packages/r-sandwich/package.py
var/spack/repos/builtin/packages/r-survival/package.py
var/spack/repos/builtin/packages/r-thdata/package.py

Simultaneous Inference in General Parametric Models.

New package - r-multcomp

---

var/spack/repos/builtin/packages/r-lmtest/package.py
var/spack/repos/builtin/packages/r-vcd/package.py

New package - r-vcd

---

var/spack/repos/builtin/packages/r-glmnet/package.py

Lasso and Elastic-Net Regularized Generalized Linear Models

New package - r-glmnet

---

var/spack/repos/builtin/packages/r-caret/package.py

Classification and Regression Training

New package - r-caret

---

var/spack/repos/builtin/packages/r-maps/package.py

New package - r-maps

---

var/spack/repos/builtin/packages/r-geosphere/package.py
var/spack/repos/builtin/packages/r-ggmap/package.py
var/spack/repos/builtin/packages/r-jpeg/package.py
var/spack/repos/builtin/packages/r-mapproj/package.py
var/spack/repos/builtin/packages/r-proto/package.py
var/spack/repos/builtin/packages/r-rgooglemaps/package.py
var/spack/repos/builtin/packages/r-rjson/package.py
var/spack/repos/builtin/packages/r-rjsonio/package.py

Spatial visualization with ggplot2

New package - r-ggmap and dependencies

---

var/spack/repos/builtin/packages/r-quantmod/package.py
var/spack/repos/builtin/packages/r-ttr/package.py

Qualitative Financial modelling framework.

New package - r-quantmod

---

var/spack/repos/builtin/packages/r-chron/package.py
var/spack/repos/builtin/packages/r-datatable/package.py

New package - r-datatable

---

var/spack/repos/builtin/packages/r-xml/package.py

Tools for parsing and generating XML within R and S-Plus.

New package - r-xml

---

var/spack/repos/builtin/packages/r-crayon/package.py
var/spack/repos/builtin/packages/r-praise/package.py
var/spack/repos/builtin/packages/r-testthat/package.py

New package - r-testthat

---

var/spack/repos/builtin/packages/r-brew/package.py
var/spack/repos/builtin/packages/r-roxygen2/package.py

In-source documentation for R.

New package - r-roxygen2

---

var/spack/repos/builtin/packages/r-gdata/package.py
var/spack/repos/builtin/packages/r-gtools/package.py

New package - r-gdata

---

var/spack/repos/builtin/packages/r-plotrix/package.py

New package - r-plotrix

---

var/spack/repos/builtin/packages/r-class/package.py
var/spack/repos/builtin/packages/r-e1071/package.py

Misc functions of the Department of Statistics, Probability Theory Group
(Formerly: E1071), TU Wien.

New package - r-e1071

---

var/spack/repos/builtin/packages/r-tarifx/package.py

A collection of various utility and convenience functions.

New package - r-tarifx

---

var/spack/repos/builtin/packages/r-survey/package.py

Analysis of complex survey samples.

New package - r-survey

---

var/spack/repos/builtin/packages/r-boot/package.py
var/spack/repos/builtin/packages/r-cubature/package.py
var/spack/repos/builtin/packages/r-np/package.py

Nonparametric kernel smoothing methods for mixed data types.

New package - r-np

---

var/spack/repos/builtin/packages/r-ncdf4/package.py

Interface to Unidata netCDF (version 4 or earlier) format data files.

New package - r-ncdf4

---

var/spack/repos/builtin/packages/cp2k/package.py

This should be a good initial version of the package. I'll add optional features (including plumed) asap.

cp2k : added package

---

lib/spack/llnl/util/filesystem.py

I was trying to debug a problem in the patch method of the libxsmm package (#1413), so I set `backup=True` to compare the Makefile.inc and it's backup copy. Much to my chagrin, I discovered that only one line of the file had changed. Upon further inspection, I discovered that the backup file wasn't the same as the original file.
For packages like libxsmm that call the `filter` method multiple times, `filter_file` was taking the current file, overwriting the old backup with it, and applying the change. In effect, Makefile.inc contained all replaced text, and the backup file contained all replaced text except for the last filter.
The solution was to create a backup file only if one does not already exist. This required me to edit the new file in place. After applying these changes, the …

Fix backup=True for filter_file

---

lib/spack/spack/platforms/cray.py

Add missing import statement for join_path

Add import statement

---

var/spack/repos/builtin/packages/kdiff3/package.py
var/spack/repos/builtin/packages/libxau/package.py

~~blocked by https://github.com/LLNL/spack/issues/863 which is a requirement for `qt`~~

kdiff3: initial version of the package

---

var/spack/repos/builtin/packages/texlive/package.py

Install texlive using various "schemes" (default is "small").
This `depends_on('perl')`.

Add package for texlive

---

var/spack/repos/builtin/packages/nextflow/package.py

This is my first cut at a package to support nextflow.  It's also my
first package.  It works, but has issues.  I'm going to submit a pull
request and get some coaching on how to deal with it.
One issue particular: if I install, then uninstall, then try to install
again (which uses the cached copy of the "distribution file"), it
explodes.

First cut package for nextflow, has issues

---

var/spack/repos/builtin/packages/ocaml/package.py
var/spack/repos/builtin/packages/unison/package.py

Add package for the Unison file sync tool.  It's written in ocaml, so add a package for that too.

Add package for unison (and ocaml)

---

var/spack/repos/builtin/packages/dealii/package.py

dealii: add optional python bindings

---

var/spack/repos/builtin/packages/cube/package.py
var/spack/repos/builtin/packages/opari2/package.py
var/spack/repos/builtin/packages/scorep/package.py

This PR updates Score-P to version 2.0. It also updates its dependencies to the appropriate versions.

Update Score-P to 2.0

---

var/spack/repos/builtin/packages/bwa/package.py

Add a package for bwa (bioinformatics sequence analysis tool).

Add package for bwa

---

var/spack/repos/builtin/packages/seqtk/package.py

Seqtk is a tool for working with fast[aq] files.

Add package for seqtk

---

var/spack/repos/builtin/packages/fastx_toolkit/package.py
var/spack/repos/builtin/packages/libgtextutils/package.py

Add package for fastx toolkit (tools for working with FASTA/Q sequence files).

Add package for fastx toolkit

---

var/spack/repos/builtin/packages/bpp-core/package.py
var/spack/repos/builtin/packages/bpp-phyl/package.py
var/spack/repos/builtin/packages/bpp-seq/package.py
var/spack/repos/builtin/packages/bpp-suite/package.py
var/spack/repos/builtin/packages/exonerate/package.py
var/spack/repos/builtin/packages/mafft/package.py
var/spack/repos/builtin/packages/prank/package.py

Add a package for prank (a probabilistic multiple alignment program for DNA, codon and amino-acid sequences), and the various tools that it uses.

Add package for prank and supporting tools

---

lib/spack/llnl/util/filesystem.py

Only strip newline chars, not spaces

---

var/spack/repos/builtin/packages/cp2k/package.py
var/spack/repos/builtin/packages/gromacs/package.py
var/spack/repos/builtin/packages/plumed/package.py

plumed : added dependents (gromacs, cp2k)

---

lib/spack/spack/repository.py

Fixes #1494.
@adamjstewart: does this work for you?

Fix superclass constructor args.

---

var/spack/repos/builtin/packages/cgns/package.py

CGNS is a dependency of Paraview, although I think we're currently using the builtin one that comes with Paraview. I've been meaning to overhaul Paraview but I'll do that at a later date.

Add CGNS package

---

lib/spack/spack/util/web.py

stripping the links to remove spaces and '\n'

---

var/spack/repos/builtin/packages/bpp-core/package.py
var/spack/repos/builtin/packages/bpp-phyl/package.py
var/spack/repos/builtin/packages/bpp-seq/package.py
var/spack/repos/builtin/packages/bpp-suite/package.py
var/spack/repos/builtin/packages/cp2k/package.py
var/spack/repos/builtin/packages/go/package.py
var/spack/repos/builtin/packages/ibmisc/package.py
var/spack/repos/builtin/packages/opencv/package.py
var/spack/repos/builtin/packages/openspeedshop/package.py
var/spack/repos/builtin/packages/parmetis/package.py
var/spack/repos/builtin/packages/qt/package.py
var/spack/repos/builtin/packages/r-datatable/package.py
var/spack/repos/builtin/packages/texlive/package.py

---
List of contributors who have packages touched here:

Fix deptypes

---

var/spack/repos/builtin/packages/gcc/package.py

Also add some missing older versions.
Update download location to original GNU location.

Update gcc to @6.2.0

---

var/spack/repos/builtin/packages/boost/package.py

This is the same patch provided by PR #550, but rebased against the current develop branch. It also passes the flake8 checks.
Tested with intel/16.0.3 and gcc/4.8.5 on RHEL.

Boost: fix recipe for Intel compilers.

---

var/spack/repos/builtin/packages/ape/package.py
var/spack/repos/builtin/packages/octopus/package.py

ape octopus: in-code comments

---

var/spack/repos/builtin/packages/nano/package.py

Strong to medium-strong text editor.

Ole' GNU nano

---

bin/spack

Change spack --profile sort key for 2.6 compatibility.

---

lib/spack/spack/provider_index.py

Fix exception constructors.

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/directives.py

resources : added docs

---

var/spack/repos/builtin/packages/cmake/intel-c-gnu11.patch
var/spack/repos/builtin/packages/cmake/package.py
var/spack/repos/builtin/packages/expat/package.py
var/spack/repos/builtin/packages/jsoncpp/package.py
var/spack/repos/builtin/packages/libarchive/package.py
var/spack/repos/builtin/packages/libxml2/package.py
var/spack/repos/builtin/packages/lz4/package.py
var/spack/repos/builtin/packages/lzma/package.py
var/spack/repos/builtin/packages/lzo/package.py
var/spack/repos/builtin/packages/nettle/package.py
var/spack/repos/builtin/packages/xz/package.py
var/spack/repos/builtin/packages/zlib/package.py

The reason I started this PR was because I couldn't get CMake to build when using the Intel compilers. I then noticed that CMake was missing a ton of dependencies, which were in turn missing other dependencies. After all of that trouble... I still can't get CMake to build with Intel! I'll file a separate issue for CMake, but regardless I think this PR should be merged.

Overhaul of CMake package and compression libraries

---

var/spack/repos/builtin/packages/git-lfs/package.py

Resolve #1636.
@IanLee1521 @xjrc @davydden

Add git-lfs package.

---

var/spack/repos/builtin/packages/ImageMagick/package.py
var/spack/repos/builtin/packages/ghostscript-fonts/package.py

- Add pango as a dependency.
- Add (new package) ghostscript-fonts as a dependency.
Fixes #1694.

Fixes for the ImageMagick package.

---

var/spack/repos/builtin/packages/globus_toolkit/package.py

Data transfer and auth stuff.  Handy for folks working at multiple computing centers.

Globus Toolkit

---

lib/spack/spack/compilers/gcc.py
lib/spack/spack/compilers/intel.py
var/spack/repos/builtin/packages/cp2k/package.py
var/spack/repos/builtin/packages/mpich/package.py
var/spack/repos/builtin/packages/mvapich2/package.py
var/spack/repos/builtin/packages/openmpi/package.py
var/spack/repos/builtin/packages/pexsi/make.inc
var/spack/repos/builtin/packages/pexsi/package.py
var/spack/repos/builtin/packages/superlu-dist/package.py

added package : pexsi

---

var/spack/repos/builtin/packages/itstool/package.py

This is a dependency for Meld, which is still a WIP.

ITS XML Translation Tool

---

var/spack/repos/builtin/packages/h5hut/package.py
var/spack/repos/builtin/packages/hdf5/package.py

H5hut (HDF5 Utility Toolkit):
High-Performance I/O Library for Particle-based Simulations

New package h5hut

---

var/spack/repos/builtin/packages/git/package.py

Also remove "--without-pcre" flag that git does not understand any more.

Add libiconv dependency for git

---

lib/spack/spack/directory_layout.py

Fix format string (in class RemoveFailedError)

---

var/spack/repos/builtin/packages/zoltan/package.py

The changes in this pull request make the following improvements to the `zoltan` package:
- Fix numerous bugs with `zoltan+mpi` installation variants.
- Fix a couple of bugs with `zoltan@:3.6+fortran` installation variants.
- Improve the overall structure of the installation script.
Please let me know if there are any problems with these updates and I'll fix them as soon as I can!

Update Package : Zoltan

---

var/spack/repos/builtin/packages/uberftp/package.py

Because regular ftp obviously isn't good enough...

Add UberFTP utility

---

var/spack/repos/builtin/packages/bpp-suite/package.py
var/spack/repos/builtin/packages/icu/package.py
var/spack/repos/builtin/packages/libuuid/package.py
var/spack/repos/builtin/packages/py-py2neo/package.py
var/spack/repos/builtin/packages/xorg-util-macros/package.py

Just some leftovers from people who created packages but never deleted all of the FIXMEs, or who couldn't find a homepage for their software.

Remove lingering boilerplate FIXMEs

---

lib/spack/spack/operating_systems/mac_os.py

fixes https://github.com/LLNL/spack/issues/1810
appreciate if someone with lower macOS can test that nothing is broken.

fix MacOs class for Sierra

---

var/spack/repos/builtin/packages/py-yt/package.py

yt is a python package for analyzing and visualizing volumetric, multi-resolution data from astrophysical simulations, radio telescopes, and a burgeoning interdisciplinary community.

Wrap "yt" package

---

var/spack/repos/builtin/packages/cp2k/package.py
var/spack/repos/builtin/packages/elpa/package.py
var/spack/repos/builtin/packages/wannier90/make.sys
var/spack/repos/builtin/packages/wannier90/package.py

cp2k : added dependencies

---

lib/spack/spack/platforms/cray.py

This PR adds a feature were all CrayPE targets that are available on a Cray are added to the `Platform.targets` list by default. This way, users can do builds targetting the front-end without explicitly setting a config file for the front end target as long as they know the correct architecture.
The Cray platform initialization now also requires modulecmd to be found in the PATH. This lets Spack fail with a useful error message if `modulecmd` is not in the PATH, whereas before it would just hang.

Adds all available CrayPE CPU targets to Cray platform by default.

---

var/spack/repos/builtin/packages/bamtools/package.py

bamtools provides a C++ API & command-line toolkit for working with BAM
data.

Add package for bamtools

---

var/spack/repos/builtin/packages/charm/mpi.patch
var/spack/repos/builtin/packages/charm/package.py

Charm++ is a parallel programming framework in C++ supported by
an adaptive runtime system, which enhances user productivity and
allows programs to run portably from small multicore computers
(your laptop) to the largest supercomputers.

New package charm

---

var/spack/repos/builtin/packages/hypre/package.py

fixes https://github.com/LLNL/spack/issues/1840
@sarich ping

hypre: fix a bug with blas/lapack names

---

var/spack/repos/builtin/packages/m4/package.py

fixes https://github.com/LLNL/spack/issues/1838
@ashkan2200 ping.

m4: fix compilation on Sierra with GCC

---

bin/spack

Prohibit Python3 in Python version check.

---

var/spack/repos/builtin/packages/grib-api/package.py

Needed for building grib support into CDO and some other climate tools.

Library for manipulating grib1 and grib2 files

---

var/spack/repos/builtin/packages/gmp/package.py
var/spack/repos/builtin/packages/libint/package.py
var/spack/repos/builtin/packages/libxc/package.py

`libint@1.1` is a dependency for CP2K. I also added support for newer versions as well.

Add libint package

---

var/spack/repos/builtin/packages/libxstream/package.py

This package will compile using gcc. I couldn't get it to work with intel but I opened an issue here https://github.com/hfp/libxstream/issues/2. Hopefully the developers will be able to help with this issue.

Added libxstream package

---

var/spack/repos/builtin/packages/pdt/package.py

URL change similar to #1466 and discussion in #1651.

pdt url change to download full installer tarball

---

var/spack/repos/builtin/packages/libquo/package.py

QUO is a high-level, easy to use programming interface tailored specifically for MPI/MPI+X codes that may benefit from evolving process binding policies during their execution. QUO allows for arbitrary process binding policies to be enacted and reverted during the execution of an MPI/MPI+X application as different computational phases are entered and exited, respectively.
https://github.com/losalamos/libquo

New package: libquo

---

var/spack/repos/builtin/packages/hadoop/package.py
var/spack/repos/builtin/packages/spark/package.py

Added hadoop, spark, and variant spark+hadoop

---

var/spack/repos/builtin/packages/hpctoolkit-externals/package.py
var/spack/repos/builtin/packages/hpctoolkit/package.py

Package for HPCToolkit performance analysis tool

Spack package for HPCToolkit 

---

var/spack/repos/builtin/packages/mpip/package.py

First time submitting a package for Spack, so this will be a learning experience for me.

Adds mpip package

---

var/spack/repos/builtin/packages/cdo/package.py
var/spack/repos/builtin/packages/grib-api/package.py
var/spack/repos/builtin/packages/harfbuzz/package.py
var/spack/repos/builtin/packages/libemos/package.py
var/spack/repos/builtin/packages/magics/no_hardcoded_python.patch
var/spack/repos/builtin/packages/magics/package.py
var/spack/repos/builtin/packages/magics/resolve_isnan_ambiguity.patch
var/spack/repos/builtin/packages/pango/package.py

Updated CDO package to support all its features.
Several minor changes of existing packages to support for compilation under Mac OS.

A set of tools used in climate modeling and numerical weather prediction.

---

lib/spack/docs/Makefile
lib/spack/docs/command_index.in
lib/spack/docs/conf.py

Fixes #1741
@adamjstewart 
- Fix issue with package_list.py regeneration confusing Sphinx.
- Add -E option to avoid caching and make Sphinx happy.

Fix some documentation build warnings.

---

var/spack/repos/builtin/packages/darshan-runtime/package.py
var/spack/repos/builtin/packages/darshan-util/package.py

@tgamblin and all: this is tested on x86 cluster. bg-q specific configuration options are not added but once there will be something ready for #1784,  I will update and test this package for bg-q system.

Packages for Darshan I/O performance characterization tool from ANL

---

lib/spack/spack/build_environment.py

Added missing function for CMake builds.

---

lib/spack/docs/contribution_guide.rst
lib/spack/docs/index.rst

with the reference to https://groups.google.com/forum/?fromgroups#!topic/spack/2Rs3BMLeTFk
~~p.s. anyone knows how to visualize changes in `atom`? Markdown preview does not follow the same rules...~~

add contribution guide focused on Git and PRs

---

lib/spack/spack/cmd/uninstall.py

Fix spack uninstall -f

---

lib/spack/env/cc

Check for `-r` in ccld mode too

---

lib/spack/docs/packaging_guide.rst

Add documentation for standard python repositories.

---

var/spack/repos/builtin/packages/hpx5/package.py

hpx5 version update

---

lib/spack/spack/cmd/md5.py

md5 : normalizes input before computing md5

---

lib/spack/spack/cmd/uninstall.py

uninstall : permits to uninstall all installed software

---

lib/spack/spack/provider_index.py

Fixed set operation from undefined += to a union

---

var/spack/repos/builtin/packages/hypre/package.py

minor follow-up fix to https://github.com/LLNL/spack/pull/1987

hypre: fix blas/lapack for MKL

---

lib/spack/spack/environment.py
lib/spack/spack/test/data/sourceme_parameters.sh
lib/spack/spack/test/environment.py

environment modifications : pass parameters along with files to be sourced

---

bin/spack
lib/spack/spack/__init__.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/util/executable.py
var/spack/repos/builtin/packages/jdk/package.py

Fixes #1779. 
@eschnett: I haven't tested this extensively yet but feel free to try it out.  This makes `-k` work with `git`.

[WIP] Make `insecure` option work with curl AND git.

---

lib/spack/docs/basic_usage.rst

spack list : updated documentation

---

lib/spack/spack/build_environment.py
lib/spack/spack/compiler.py
lib/spack/spack/compilers/clang.py
var/spack/repos/builtin/packages/icu4c/package.py
var/spack/repos/builtin/packages/qt/package.py

---
@tgamblin Here's a WIP for the Xcode mockup. Now to test on a real macOS machine.

Mock up Xcode devdir to make Qt5 work on Mac OS X

---

var/spack/repos/builtin/packages/py-matplotlib/package.py

@adamjstewart 
As with CGAL, this PR adds new variants and makes optional dependencies optional.

py-matplotlib: Add variants for optional dependencies.

---

var/spack/repos/builtin/packages/py-macs2/package.py

Genomics software. This is my first PR, all feedback welcome.

py-macs2: New package

---

lib/spack/spack/cmd/create.py
var/spack/repos/builtin/packages/bazel/cc_configure.patch
var/spack/repos/builtin/packages/bazel/fix_env_handling.patch
var/spack/repos/builtin/packages/bazel/link.patch
var/spack/repos/builtin/packages/bazel/package.py

Google's own build tool (needed for tensorflow => there will be a follow-up PR).
We have to patch some of the code to pass through SPACK's environment variables (i.e. we spoil the spirit of bazel ;) ).

Support for bazel

---

lib/spack/spack/cmd/install.py
lib/spack/spack/cmd/setup.py
lib/spack/spack/cmd/test_install.py
lib/spack/spack/package.py

`Package.do_install` : removed `install_self` from arguments

---

lib/spack/env/cc

Don't clear LD_LIBRARY_PATH and friends from compiler wrappers

---

var/spack/repos/builtin/packages/glew/package.py
var/spack/repos/builtin/packages/gource/package.py
var/spack/repos/builtin/packages/sdl2/package.py
var/spack/repos/builtin/packages/sdl2_image/package.py

This has been built successfully on OS X 10.11.

Add new package "gource" and dependencies "glew, sdl, sdl-image".

---

lib/spack/docs/getting_started.rst

Transferring the following PR:
https://github.com/citibeth/spack/pull/1

Small fix to docs.

---

var/spack/repos/builtin/packages/eigen/package.py

Adds new versions to eigen

---

var/spack/repos/builtin/packages/netlib-lapack/package.py

Get netlib-lapack to compile with Intel and add deprecated routines

---

var/spack/repos/builtin/packages/gmp/package.py

fixes https://github.com/LLNL/spack/issues/2113

gmp: fix a bug

---

var/spack/repos/builtin/packages/py-xpyb/package.py

Rename xpyb to py-xpyb

---

var/spack/repos/builtin/packages/openblas/openblas_icc.patch
var/spack/repos/builtin/packages/openblas/package.py

openblas: Fixes to get OpenBLAS to install with Intel compilers

---

lib/spack/spack/build_environment.py
lib/spack/spack/test/environment.py
lib/spack/spack/util/environment.py

fixes https://github.com/LLNL/spack/issues/2079
fixes https://github.com/LLNL/spack/issues/1224
~~If this is a right way, i will look through `cc` to filter it as well.~~

filter system paths

---

var/spack/repos/builtin/packages/ant/package.py

Add a package for ant, a java build tool.

Add package for ant

---

lib/spack/docs/getting_started.rst

fixes https://github.com/LLNL/spack/issues/2067  (more precisely https://github.com/LLNL/spack/issues/2067#issuecomment-255498874 ).

document recommended usage of system blas/lapack

---

lib/spack/docs/configuration.rst
lib/spack/docs/getting_started.rst

Removed documentation on false paths as per #2083

---

var/spack/repos/builtin/packages/trilinos/package.py

Get Trilinos 12.6.2 to build with Intel compilers and spack

---

var/spack/repos/builtin/packages/intel-parallel-studio/package.py

Fixes #2153, thanks @lee218llnl!

Update license directory for intel-paralel-studio

---

var/spack/repos/builtin/packages/gobject-introspection/package.py
var/spack/repos/builtin/packages/gtkplus/package.py

Found some dependences for these packages that were not available on one of our new systems.

updated gtk and gobject dependences

---

var/spack/repos/builtin/packages/nmap/package.py

I added this for the ncat which is missing on some distro's but very useful for debugging network issues.

Nmap package added

---

var/spack/repos/builtin/packages/ncl/package.py
var/spack/repos/builtin/packages/ncl/spack_ncl.patch

Without GRIB2 and HDF-EOS support yet.

Added first version of the NCL package.

---

lib/spack/spack/cmd/flake8.py

Fix bug mentioned in #2198 and #1573

Fix style checker bug.

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/find.py
lib/spack/spack/cmd/module.py
lib/spack/spack/test/cmd/find.py
lib/spack/spack/test/cmd/module.py

@adamjstewart @davydden Could you try this out and see if there are issues that I overlooked ?

spack find: accepts anonymous specs as arguments

---

lib/spack/docs/getting_started.rst

in reference to https://github.com/LLNL/spack/pull/2192#issuecomment-257427916

remove obsolete instructions on hacking clang+gfortran

---

var/spack/repos/builtin/packages/dealii/package.py

dealii: switch to CMakePackage and minor cleanup

---

var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/everytrace-example/package.py
var/spack/repos/builtin/packages/everytrace/package.py
var/spack/repos/builtin/packages/trilinos/package.py

After discussion on #2239 (thanks @davydden ) I thought it would be useful to check on the packages that are subclassing `CMakePackage`. 
Probably should be glanced at by the owners of the packages, which seem to be @davydden and @citibeth .

tweaks to packages using CMakePackage

---

var/spack/repos/builtin/packages/opencoarrays/package.py

- update to use more `CMakePackage` goodness
- add version 1.7.4

opencoarrays package fixes and new version

---

var/spack/repos/builtin/packages/matio/package.py

- update to a AutoTools package
- add variants for hdf5 and zlib
- add latest version

updates to matio package

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/build_systems/autotools.py
var/spack/repos/builtin/packages/cairo/package.py
var/spack/repos/builtin/packages/dyninst/package.py
var/spack/repos/builtin/packages/fontconfig/package.py
var/spack/repos/builtin/packages/graphviz/package.py
var/spack/repos/builtin/packages/libelf/package.py
var/spack/repos/builtin/packages/libiconv/package.py
var/spack/repos/builtin/packages/libtiff/package.py
var/spack/repos/builtin/packages/lzma/package.py
var/spack/repos/builtin/packages/py-pygobject/package.py
var/spack/repos/builtin/packages/py-pygtk/package.py

For issue #2063.
@becker33 @tgamblin

patch older config.guess for newer architectures

---

lib/spack/spack/cmd/flake8.py
var/spack/repos/builtin/packages/libsplash/package.py

Add the latest release of libSplash, version 1.6.0.

libSplash: Add 1.6.0 Release

---

var/spack/repos/builtin/packages/python/package.py

I am not sure that this is how it should be fixed. But it seems to work.

Updated python package reflecting the changes in 9347f86

---

var/spack/repos/builtin/packages/environment-modules/package.py

There is a chance that tclConfig.sh that comes with the tcl package is saved not in the 'lib' directory but in the 'lib64' directory. The environment-modules package takes that into account now.

Update for environment-modules.

---

lib/spack/docs/Makefile
lib/spack/docs/basic_usage_tutorial.rst
lib/spack/docs/index.rst
share/spack/qa/run-doc-tests

Adding @becker33's tutorial script.

Basic usage step-by-step tutorial

---

var/spack/repos/builtin/packages/py-pathspec/package.py

Related to Python unit testing.

py-pathspec: New package

---

var/spack/repos/builtin/packages/yaml-cpp/package.py

A new package for building yaml-cpp (https://github.com/jbeder/yaml-cpp).

New package yaml-cpp

---

var/spack/repos/builtin/packages/r-bitops/package.py
var/spack/repos/builtin/packages/r-c50/package.py

R library: C5.0 decision trees and rule-based models for pattern recognition

New package - r-c50

---

var/spack/repos/builtin/packages/r-deoptim/package.py

Implements the differential evolution algorithm for global optimization of a real-valued function of a real-valued parameter vector.

New package - r-deoptim

---

var/spack/repos/builtin/packages/r-formula/package.py

Infrastructure for extended formulas with multiple parts on the right-hand side and/or multiple responses on the left-hand side. Dependency of r-partykit.

New package - r-formula

---

var/spack/repos/builtin/packages/r-partykit/package.py

A toolkit with infrastructure for representing, summarizing, and visualizing tree-structured regression and classification models.

New package - r-partykit

---

var/spack/repos/builtin/packages/r-catools/package.py

Contains several basic utility functions

New package - r-catools

---

var/spack/repos/builtin/packages/r-bitops/package.py

R Library with functions for bitwise operations on integer vectors.

New package r-bitops

---

var/spack/repos/builtin/packages/superlu/package.py

Updating SuperLU package file with ability to build version 4.3. (before they added cmake) with external blas or internal blas, and added capability to build the latest version 5.2.1 (with cmake) with internal blas.

Updating SuperLU package file with ability to build version 4.3.

---

var/spack/repos/builtin/packages/py-pyqt/package.py
var/spack/repos/builtin/packages/qt/package.py

phonon and dbus support in qt are required for pyqt.

added qt variants for pyqt to build

---

var/spack/repos/builtin/packages/r-evaluate/package.py

Parsing and evaluation tools that make it easy to recreate the command line behaviour of R

New package - r-evaluate

---

var/spack/repos/builtin/packages/r-formatr/package.py

Provides a function tidy_source() to format R source code.

New package - r-formatr

---

var/spack/repos/builtin/packages/r-knitr/package.py

Provides a general-purpose tool for dynamic report generation in R using Literate Programming techniques. Dependency of r-gistr.

New package - r-knitr

---

var/spack/repos/builtin/packages/r-hexbin/package.py

Binning and plotting functions for hexagonal bins.

New package - r-hexbin

---

var/spack/repos/builtin/packages/r-irdisplay/package.py

An interface to the rich display capabilities of Jupyter front-ends

New package - r-irdisplay

---

var/spack/repos/builtin/packages/r-rzmq/package.py

Interface to the ZeroMQ lightweight messaging kernel.

New package - r-rzmq

---

var/spack/repos/builtin/packages/r-rinside/package.py

C++ classes to embed R in C++ applications

New package - r-rinside

---

var/spack/repos/builtin/packages/scotch/package.py

i have not tested the installed package as I needed it for something else, but at least it compiles now under macOS. 
FYI, [homebrew](https://github.com/Homebrew/homebrew-science/blob/master/scotch.rb) do things a bit differently
```
make_args << "AR=libtool"
arflags = ldflags.join(" ") + " -dynamic -install_name #{lib}/$(notdir $@) -undefined dynamic_lookup -o"
make_args << "ARFLAGS=#{arflags}"
```
with default flags
```
cflags   = %w[-O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER
-DCOMMON_PTHREAD
-DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED
-DCOMMON_TIMING_OLD -DSCOTCH_RENAME
-DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ]
```

scotch: fix compilation on macOS

---

var/spack/repos/builtin/packages/r-uuid/package.py

Tools for generating and handling of UUIDs.

New package - r-uuid

---

var/spack/repos/builtin/packages/r-pryr/package.py

Useful tools to pry back the covers of R and understand the language at a deeper level.

New package - r-pryr

---

var/spack/repos/builtin/packages/r-rzmq/package.py

@JavierCVilla - not sure how it built for you w/o. Did you have a local installation?

add missing zeromq dependency to r-rzmq

---

lib/spack/spack/cmd/install.py

to be able to upload to cdash some more information is needed in the junit output. Added:
- hostname
- full spec as buildname
Not sure whether a one-command publish command is a good idea

[WIP] adapt junit output for cdash

---

var/spack/repos/builtin/packages/petsc/package.py
var/spack/repos/builtin/packages/sowing/package.py

Funded-by:  IDEAS
Project:  IDEAS/xSDK
Time:   .3 hours
x

add support for installing the development (master) version of PETSc

---

var/spack/repos/builtin/packages/jemalloc/package.py

This corrects a severe problem (segfault) on macos Sierra.

jemalloc: Update to 4.3.1

---

var/spack/repos/builtin/packages/r-rbokeh/package.py

R interface for creating plots in Bokeh.

New package - r-rbokeh

---

var/spack/repos/builtin/packages/r-irkernel/package.py
var/spack/repos/builtin/packages/r-pbdzmq/package.py

New package - r-irkernel

---

var/spack/repos/builtin/packages/py-argcomplete/package.py
var/spack/repos/builtin/packages/py-scientificpython/package.py

py-scientificpython had a missing dependency on py-numpy
py-argcomplete had a missing setuptools build dependency

Fix py-scientificpython and py-argcomplete dependencies

---

var/spack/repos/builtin/packages/yaml-cpp/package.py

Updating yaml-cpp from Package to CMakePackage.

Updating yaml-cpp from Package to CMakePackage

---

var/spack/repos/builtin/packages/py-pypar/package.py

Another py-* package failure less

Fix download URL and dependencies for py-pypar

---

var/spack/repos/builtin/packages/git/package.py

Builds, seems to work (ate its own dogfood on this commit!).

Update git package to include 2.11.0

---

var/spack/repos/builtin/packages/openmpi/package.py

I also updated OpenMPI to the new AutotoolsPackage while I was at it.

Add Java support to OpenMPI

---

var/spack/repos/builtin/packages/texlive/package.py

While the discussion in #2494 progresses, this changes fixes the digest
values so that builds succeeed.

Update texlive digest value

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/find.py

Quick fix of a seemingly innocent typo (and if it is not, it needs another name).

Fixed typo

---

var/spack/repos/builtin/packages/cmor/package.py
var/spack/repos/builtin/packages/uuid/package.py

More tools for the climate modelling community.

Added packages: cmor and uuid.

---

lib/spack/spack/util/spack_json.py

We need something like this (at least for now) because now we get unicode objects when we load from the json database. This leads to the problem of hash evaluation of already installed packages.
For example, when we do 'spack activate <python_extension>' we get the following error:
_Error: Can only (de)activate extensions for installed packages._
This happens because when spack evaluates hash code, it gives yaml unicode strings and the latter, instead of returning:
`{python: {version: 2.7.12, arch:...`
gives this:
`{!!python/unicode 'python': {version: 2.7.12, arch:`
The solution is based on this: http://stackoverflow.com/a/33571117

Json loader now returns str objects instead of unicode.

---

var/spack/repos/builtin/packages/petsc/package.py
var/spack/repos/builtin/packages/pflotran/package.py

First implementation of spack file for Pflotran

---

var/spack/repos/builtin/packages/eigen/package.py

Main page states [3.3.1 is latest stable](http://eigen.tuxfamily.org/index.php?title=Main_Page).

Eigen 3.3.1 is latest stable version.

---

var/spack/repos/builtin/packages/likwid/package.py

only add a TODO, which I don't know how to fix.
see https://groups.google.com/forum/#!topic/likwid-users/cczaPvi1H3g

likwid: add todo

---

var/spack/repos/builtin/packages/r-xgboost/package.py

Extreme Gradient Boosting, which is an efficient implementation of gradient boosting framework. 
**Using R with uppercase until #2475 is merged**

New package - r-xgboost

---

var/spack/repos/builtin/packages/doxygen/package.py

As in subject line; adds version 1.8.12

Doxygen: Add new version

---

lib/spack/spack/cmd/graph.py
lib/spack/spack/cmd/setup.py
lib/spack/spack/directory_layout.py

Update `spack setup` and `spack graph` to be consistent with recent refactoring

---

lib/spack/spack/build_environment.py

Change attribute to match ArchSpec refactor

---

var/spack/repos/builtin/packages/py-cdo/package.py

Hello,
this is my first attemp to collaborate with spack. I've created the package py-cdo, which is the python interface for the Climate Data Operators.
https://pypi.python.org/pypi/cdo/1.3.2

New package py-cdo

---

var/spack/repos/builtin/packages/texlive/package.py

Texlive is *live*, they update the contents of their tarball on a whim.
Here's the current one.
Sigh.

Update texlive digest

---

lib/spack/spack/cmd/create.py
lib/spack/spack/util/compression.py

Make unzip quiet

---

var/spack/repos/builtin/packages/flex/package.py

Blacklist flex 2.6.2 by commenting out package version

---

var/spack/repos/builtin/packages/trilinos/package.py

Updating Trilinos with superlu variant and fixing git branch options.

Updating Trilinos with superlu variant and fixing git branch options

---

var/spack/repos/builtin/packages/dealii/package.py

fixes https://github.com/LLNL/spack/issues/2615
tested on macOS Sierra.
@cpraveen please check on your system where the problem occurred.

dealii: fix config for Netcdf with lib64

---

var/spack/repos/builtin/packages/gawk/package.py

Add gawk (GNU awk)

---

var/spack/repos/builtin/packages/h5hut/package.py

Various improvements to H5hut

---

var/spack/repos/builtin/packages/libspatialindex/package.py

Small fix for the homepage of the package libspatialindex.

Fix homepage for the package libspatialindex

---

var/spack/repos/builtin/packages/go-bootstrap/package.py
var/spack/repos/builtin/packages/go/package.py

After a bit of thinking I believe this is the right way to fix the problem (instead of #2588)

go: fixed GOROOT_BOOTSTRAP handling

---

lib/spack/docs/basic_usage.rst
lib/spack/docs/getting_started.rst
lib/spack/docs/mirrors.rst
lib/spack/docs/module_file_support.rst
lib/spack/docs/packaging_guide.rst
lib/spack/docs/repositories.rst
lib/spack/docs/tutorial_sc16_modules.rst
lib/spack/docs/tutorial_sc16_spack_basics.rst
lib/spack/docs/workflows.rst

Remove usernames from paths in docs

---

var/spack/repos/builtin/packages/texlive/package.py

Update the texlive distro digest.

---

var/spack/repos/builtin/packages/gcc/package.py

Built a few packages and everything seems to be working fine.

Update gcc to 6.3.0

---

var/spack/repos/builtin/packages/yorick/package.py

Init new package for LLNL's Yorick [http://dhmunro.github.io/yorick-doc/](url).

init yorick package

---

.travis.yml

Adds OSX to the platforms tested by Travis.
@davydden @alalazo

Add OSX build to .travis.yml.  Clean up .travis.yml

---

share/spack/qa/run-unit-tests

See the comment in #2709  by @adamjstewart

tests: `coverage combine` run only if tests succeeded

---

lib/spack/spack/cmd/info.py
lib/spack/spack/directives.py
lib/spack/spack/provider_index.py
lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py
var/spack/repos/builtin.mock/packages/multi-provider-mpi/package.py

Fixes #1623.
@citibeth: can you please verify?
- provides() now adds to a set of provided vdeps instead of a single one.

Fix issues when a package provides the same vdep twice.

---

var/spack/repos/builtin/packages/zlib/package.py

Update to latest zlib version, server no longer provides older version

---

lib/spack/spack/test/conftest.py

@tgamblin There was a line more than due in a fixture. This should solve the problem in #2320

test: fixed 'refresh_builtin_mock' fixture

---

var/spack/repos/builtin/packages/intel-mkl/package.py

Renaming mkl to intel-mkl

---

var/spack/repos/builtin/packages/petsc/package.py

Unset PETSC_DIR during installation

---

var/spack/repos/builtin/packages/octopus/package.py

I added support for Octopus 6.0 as well as several variants.

Features/octopus 6.0

---

lib/spack/spack/build_environment.py
lib/spack/spack/test/build_systems.py
var/spack/repos/builtin.mock/packages/cmake-client/package.py

Avoid code duplication for "get_std_cmake_args"

---

var/spack/repos/builtin/packages/pgi/package.py

Someone discovered a bug that affects PGI 15.9 and above, so I was asked to install 15.7.

Add old version of PGI

---

var/spack/repos/builtin/packages/cuda/package.py

Adds the latest CUDA toolkit release, 8.0.44.

Packages: Add CUDA8

---

lib/spack/spack/cmd/__init__.py

Fixed find -lp command (coloring was broken)

---

lib/spack/spack/test/concretize_preferences.py

Add a test for behavior in #1622.

Add a test to exercise non-buildable external packages.

---

var/spack/repos/builtin/packages/cmake/package.py

```
$ spack versions cmake
==> Safe versions (already checksummed):
3.7.1  3.6.1  3.6.0  3.5.2  3.5.1  3.5.0  3.4.3  3.4.0  3.3.1  3.1.0  3.0.2  2.8.10.2
==> Remote versions (not yet checksummed):
3.4.2  3.4.1
```
```
$ spack checksum cmake
==> Found 4 versions of cmake:
3.4.3  https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
3.4.2  https://cmake.org/files/v3.4/cmake-3.4.2.tar.gz
3.4.1  https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz
3.4.0  https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz
How many would you like to checksum? (default is 1, q to abort)
```
```
$ spack versions cmake
==> Safe versions (already checksummed):
3.7.1  3.6.1  3.6.0  3.5.2  3.5.1  3.5.0  3.4.3  3.4.0  3.3.1  3.1.0  3.0.2  2.8.10.2
==> Remote versions (not yet checksummed):
3.7.0  3.4.1  3.2.2  3.1.2  2.8.12.2 …
```

Add list_url to cmake

---

lib/spack/docs/basic_usage.rst
lib/spack/docs/features.rst
lib/spack/docs/getting_started.rst
lib/spack/docs/tutorial_sc16_spack_basics.rst
lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/install.py
lib/spack/spack/parse.py
lib/spack/spack/spec.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/spec_syntax.py

Eliminates the need for escape quotes.
TODO: Fix multiple specs. Ideally add (more) unit tests.

Parser fix

---

lib/spack/spack/test/url_parse.py
lib/spack/spack/url.py

Support scionlib version detection

---

lib/spack/spack/spec.py

Address issue #2162
Maybe there's something deeper that's wrong, but this is working for me.

check if node is already deleted

---

var/spack/repos/builtin/packages/oce/package.py
var/spack/repos/builtin/packages/oce/sierra.patch

~~i will most likely update the patch soon...~~

oce: add 0.18 and fix patching

---

lib/spack/spack/cmd/create.py

Currently, when you run `spack create` with a URL for a tarball that uses the Autotools build system, it only detects `AutotoolsPackage` if a `configure` script is present. If the tarball does not contain a `configure` script, it cannot decide what build system it uses.
This PR adds detection for files like `configure.ac`, `configure.in`, and `Makefile.am`. If one of these files is present but `configure` is not, `spack create` now automatically adds the automake/autoconf/libtool/m4 dependencies and adds a default `autoreconf` method.

Allow spack create to detect packages that need to run autoreconf

---

var/spack/repos/builtin/packages/pflotran/package.py

let pflotran depend on hdf 1.8.12 and above

---

var/spack/repos/builtin/packages/parallel-netcdf/package.py

I decided to split this out of #2831 because that PR doesn't seem to be moving forward any time soon.

Add latest version of PnetCDF

---

var/spack/repos/builtin/packages/xerces-c/package.py

I decided to split this out of #2831 because that PR doesn't seem to be moving forward any time soon.

Convert xerces-c to AutotoolsPackage

---

var/spack/repos/builtin/packages/symengine/package.py

Take advantage of new configuration options in the @develop branch
Closes symengine/symengine#1186

Update SymEngine package

---

var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/matio/package.py
var/spack/repos/builtin/packages/metis/package.py
var/spack/repos/builtin/packages/parmetis/package.py
var/spack/repos/builtin/packages/zlib/package.py

add shared variant for following packages to allow static-only builds:
metis
parmetis
matio
zlib
bzip2

add static options for some libraries

---

var/spack/repos/builtin/packages/flex/package.py

The last version of flex had a slew of compatibility issues. Hopefully this version fixes those. Can someone test it out for me?

Add latest version of flex

---

lib/spack/spack/spec.py

Add single quotes to message for readability and engineering fixes.

Fix ambiguous hash message generation.

---

lib/spack/spack/build_systems/python.py

PythonPackage: removed call syntax from property

---

var/spack/repos/builtin/packages/perl/package.py

Adds the latest stable release of Perl. Note that there are several newer development releases, but that they recommend the latest stable release for all users.

Add latest stable Perl release

---

var/spack/repos/builtin/packages/tcl/package.py
var/spack/repos/builtin/packages/tk/package.py

Update Tcl/Tk to 8.6.6

---

var/spack/repos/builtin/packages/flex/package.py
var/spack/repos/builtin/packages/glib/package.py

Add m4 dependency to Flex and Glib builds

---

var/spack/repos/builtin/packages/intel-mkl/package.py
var/spack/repos/builtin/packages/intel-parallel-studio/package.py

This PR turns intel-mkl and intel-parallel-studio into scalapack providers...for most MPIs, anyway.
A couple of things are iffy:
- scalapack should be provided when ^mpi (is this valid?). There's a test for that later that raises an exception if there are no known MPI implementations in the spec, though.
- It doesn't support Intel MPI because afaik there's no way to distinguish between ^intel-parallel-studio being pulled for Intel MPI or the rest of the stuff in the package. (including scalapack itself)

MKL: Provide scalapack

---

var/spack/repos/builtin/packages/spark/package.py

Changed spark URL, Added version 2.0.2, 2.1.0

---

.codecov.yml

codecov: added commit status, made green a reachable state

---

lib/spack/spack/fetch_strategy.py

fixes https://github.com/LLNL/spack/issues/3065

make svn fetch quiet

---

var/spack/repos/builtin/packages/adlbx/package.py
var/spack/repos/builtin/packages/exmcutils/package.py
var/spack/repos/builtin/packages/parallel/package.py
var/spack/repos/builtin/packages/turbine/package.py

This is a pure C library that is a dependency for Swift/T.

New package.py for ExM C-Utils: An initial package dependency for Swift/T

---

var/spack/repos/builtin/packages/numdiff/package.py

numdiff: update dependencies and fix

---

lib/spack/spack/modules.py
lib/spack/spack/package.py
lib/spack/spack/test/modules.py
var/spack/repos/builtin.mock/packages/callpath/package.py
var/spack/repos/builtin.mock/packages/mpileaks/package.py

fix: don't call setup_environment when not needed 

---

var/spack/repos/builtin/packages/dealii/package.py

Add tag for version develop to allow caching of git repos.

Add tag master for version develop of dealii.

---

var/spack/repos/builtin/packages/octave/package.py

not sure about all of those, but `java` was turned on by default.

octave: fix missing --without statements

---

var/spack/repos/builtin/packages/py-nose/package.py
var/spack/repos/builtin/packages/py-numpy/package.py
var/spack/repos/builtin/packages/py-pip/package.py
var/spack/repos/builtin/packages/py-pytest-flake8/package.py
var/spack/repos/builtin/packages/py-scikit-learn/package.py
var/spack/repos/builtin/packages/py-setuptools/package.py

Many of these come from #2869. I figured it would be easier to review #2869 with unrelated changes in a separate PR.

Add new versions of several Python packages

---

var/spack/repos/builtin/packages/binutils/package.py
var/spack/repos/builtin/packages/extrae/package.py
var/spack/repos/builtin/packages/paraver/package.py

Recently we changed bsc website so links were no longer valid.
I add to add a flag in binutils to avoid an error when using binutils in extrae.
KiM

Updating homepages and sources from two BSC packages

---

var/spack/repos/builtin/packages/swig/package.py

Fixes #3000. This is an alternate solution to #3248.
Ping @eschnett @davydden @alalazo @jppelteret

Fix infinite recursion in swig build

---

var/spack/repos/builtin/packages/nfft/package.py

debian jessie: package does not build without patch

nfft: distclean before configure

---

var/spack/repos/builtin/packages/hypre/ibm-ppc64le.patch
var/spack/repos/builtin/packages/hypre/package.py

This is a temporary patch for ppc64le. 
This patch will be removed after hypre group modified config.guess
Pull request was made for hypre (https://github.com/LLNL/hypre/pull/10)

ibm-support for hypre

---

var/spack/repos/builtin/packages/intel-parallel-studio/package.py

From #3182, I have added URLs for the supported Parallel Studio versions.

added urls for Intel Parallel Studio

---

var/spack/repos/builtin/packages/mumps/package.py
var/spack/repos/builtin/packages/mumps/spectrum-mpi-xl.patch

Add xl and spectrum mpi support for mumps

---

var/spack/repos/builtin/packages/samrai/package.py

Updating SAMRAI package with new urls and new versions. Also updating to use Spack's built in MPI compilers.

Updating SAMRAI package with new urls and new versions

---

var/spack/repos/builtin/packages/py-doxypypy/package.py

This is not a duplicate, but rather to nearly identical python packages...

add package py-doxypypy

---

var/spack/repos/builtin/packages/icu4c/package.py

Also adds the latest version.
Fixes #3304.

Convert icu4c to AutotoolsPackage

---

var/spack/repos/builtin/packages/notmuch/package.py
var/spack/repos/builtin/packages/talloc/package.py
var/spack/repos/builtin/packages/xapian-core/package.py

add package notmuch and dependencies

---

var/spack/repos/builtin/packages/py-qtawesome/package.py

requires py-qtpy
and again no working ```pypi.io``` URL found...

add package py-qtawesome

---

var/spack/repos/builtin/packages/py-spyder/package.py

requires:
- ~~py-rope~~
- ~~py-qtconsole~~
- ~~py-qtawesome~~
- ~~py-qtpy~~
- ~~py-pyzmq~~
- ~~py-chardet~~
- ~~py-numpydoc~~

add package py-spyder

---

var/spack/repos/builtin/packages/py-elephant/package.py

Commented out requirements to document the need if documentation and tests are wanted. I'm unsure how I could incorporate this directly.

add package py-elephant

---

var/spack/repos/builtin/packages/openblas/package.py
var/spack/repos/builtin/packages/py-lmfit/package.py

* needed to deactivate testing in openblas due to spec.cppflags being undefined
Should I open an issue? I could also directly fix the openblas error, if someone can tell me how to do it.

add package py-lmfit

---

var/spack/repos/builtin/packages/opencoarrays/package.py

The download url changed and needs to be corrected.

opencoarrays: Correct download url, update version

---

var/spack/repos/builtin/packages/py-scipy/package.py

See https://github.com/scipy/scipy/issues/7112 for details.

scipy build fails when built in parallel

---

var/spack/repos/builtin/packages/openblas/package.py

fixes https://github.com/LLNL/spack/issues/3343

openblas: fix flags

---

var/spack/repos/builtin/packages/gcc/package.py

Revert "Make libgcc_s relocatable on Macos by adding @rpath to installname"

---

var/spack/repos/builtin/packages/magma/ibm-xl.patch
var/spack/repos/builtin/packages/magma/package.py

Added magma package

---

var/spack/repos/builtin/packages/gl2ps/package.py

Fixes #3159.
Also adds dozens of missing X11 dependencies.

Convert gl2ps to CMakePackage

---

var/spack/repos/builtin/packages/elemental/package.py
var/spack/repos/builtin/packages/lammps/package.py
var/spack/repos/builtin/packages/magma/package.py

p.s. plus some whitespace.
fixes https://github.com/LLNL/spack/issues/3364
in reference to https://github.com/LLNL/spack/pull/1875

fix blas/lapack usage after PR 1875

---

var/spack/repos/builtin/packages/veclibfort/package.py

Fixes veclibfort which was broken by PR1875

---

var/spack/repos/builtin/packages/farmhash/CMakeLists.txt
var/spack/repos/builtin/packages/farmhash/package.py

We are trying to build TensorFlow natively as Spack for HackIllinois. This is one of the dependencies for TensorFlow

Adding farmhash package from google

---

lib/spack/spack/package.py

package.py: packages dump build dependencies in prefix

---

var/spack/repos/builtin/packages/elemental/package.py
var/spack/repos/builtin/packages/lbann/package.py

introduced by PR https://github.com/LLNL/spack/pull/1875

Fixes the Elemental and LBANN packages to conform to the new syntax

---

var/spack/repos/builtin/packages/patch/package.py

patch: configure and build out of source 

---

var/spack/repos/builtin/packages/py-coverage/package.py

Fixing wrong checksum added after moving to pypi.io in #3088

Fixing checkum of py-coverage v4.3.4

---

var/spack/repos/builtin/packages/spectrum-mpi/package.py

Updated the spectrum-mpi package to get the right compiler names when

---

var/spack/repos/builtin/packages/py-4suite-xml/package.py

Just some questions before creating several PR's, I have around 30 python packages to add:
- Do I make a single PR per standalone package better than a PR with 30 packages?
- After looking into the open/closed issues, I see that we want to follow the pypi.io approach for python packages, but this url is redirecting to pypi.org. Does anyone know the reason of the readdressing? 
- Do we maintain the pypi.io url's?

Adding new package: py-4suite-xml

---

var/spack/repos/builtin/packages/vc/package.py

Adding new package: vc

---

var/spack/repos/builtin/packages/vdt/package.py

Vectorised math. A collection of fast and inline implementations of mathematical functions.

Adding new package: vdt

---

var/spack/repos/builtin/packages/py-joblib/package.py

Python function as pipeline jobs.

Adding new package: py-joblib

---

var/spack/repos/builtin/packages/py-keras/package.py
var/spack/repos/builtin/packages/py-pydot/package.py
var/spack/repos/builtin/packages/py-theano/package.py

Deep Learning library for Python. Convnets, recurrent neural networks, and more. Runs on Theano or TensorFlow.
This PR includes;
- py-keras
- py-theano
- py-pydot

Adding new package: py-keras

---

var/spack/repos/builtin/packages/py-elasticsearch/package.py
var/spack/repos/builtin/packages/py-nosexcover/package.py
var/spack/repos/builtin/packages/py-urllib3/package.py

Python client for Elasticsearch

Adding new package: py-elasticsearch

---

var/spack/repos/builtin/packages/py-lxml/package.py

Library for processing XML and HTML in the Python language

Adding new package: py-lxml

---

var/spack/repos/builtin/packages/binutils/package.py

binutils: Add gettext dependency

---

var/spack/repos/builtin/packages/autoconf/package.py

autoconf: Correct m4 dependency declaration

---

var/spack/repos/builtin/packages/ncurses/package.py

This should be a better solution for #3361.

ncurses: Use gawk as awk

---

var/spack/repos/builtin/packages/zlib/package.py

Fix zlib %pgi build

---

var/spack/repos/builtin/packages/pcre/package.py

Add latest version of pcre

---

var/spack/repos/builtin/packages/py-jpype/package.py

JPype is an effort to allow python programs full access to java class libraries

Adding new package: py-jpype

---

var/spack/repos/builtin/packages/hwloc/package.py

- add several missing dependencies
- add variants for various features
- add new version 1.11.6

hwloc: Add missing dependencies

---

var/spack/repos/builtin/packages/qt/package.py

Fixes #2903.
@davydden: this worked for me on 10.11.  Can you verify for Sierra?
I am not sure whether this is a minimal set of changes (particularly the `dbus` pieces) but it builds.

Fix Qt4 build on Yosemite (10.11)

---

var/spack/repos/builtin/packages/libgpuarray/package.py
var/spack/repos/builtin/packages/py-ipython/package.py

Added support for GPUs in Theano and added the py-pexpect package for ipython.

Py keras extension

---

var/spack/repos/builtin/packages/nco/package.py

@citibeth You might be interested in this. Just released yesterday.

Add latest version of NCO

---

var/spack/repos/builtin/packages/vtk/package.py

Fixes #2802.
Also adds the latest version and converts the package to the `CMakePackage` base class.
@KineticTheory, would you mind testing this out?

Add version constraints to VTK patch

---

var/spack/repos/builtin/packages/py-future/package.py

Clean single-source support for Python 3 and 2

Adding new package: py-future

---

var/spack/repos/builtin/packages/julia/package.py

julia: Create cacert directory manually to ensure correct permissions

---

var/spack/repos/builtin/packages/py-virtualenv/package.py

Fixes #3484. Also adds the latest version of virtualenv.

setuptools is a runtime dependency of virtualenv

---

var/spack/repos/builtin/packages/hdf5/package.py

hdf5: Clean up building self-tests

---

var/spack/repos/builtin/packages/leveldb/package.py

I also added a pkg-config file because that makes it much more convenient to use the library.

Update leveldb to 1.20

---

var/spack/repos/builtin/packages/binutils/package.py

Add latest version of binutils

---

var/spack/repos/builtin/packages/py-pudb/package.py

UPDATE:
Was supposed to help with #3501 but doesn't solve the real problem.

Fix: setuptools is a runtime dependency for pudb

---

var/spack/repos/builtin/packages/mpfr/package.py
var/spack/repos/builtin/packages/mpfr/strtofr.patch
var/spack/repos/builtin/packages/mpfr/vasprintf.patch

These patches are unmodified and come directly from http://mpfr.loria.fr/mpfr-current/#bugs

Add recommended patches to mpfr package

---

var/spack/repos/builtin/packages/isl/package.py

I wanted to build with `--run-tests` to make sure the tests pass [Spoiler Alert: they did].

Convert isl to AutotoolsPackage

---

var/spack/repos/builtin/packages/lammps/package.py

Fixes #3524.
@weijianwen Can you see if this solves your issue?

Only configure requested lammps features

---

lib/spack/spack/cmd/flake8.py
var/spack/repos/builtin/packages/expect/expect_detect_tcl_private_header_os_x_mountain_lion.patch
var/spack/repos/builtin/packages/expect/package.py
var/spack/repos/builtin/packages/tcl/package.py
var/spack/repos/builtin/packages/tk/package.py

Add Expect package

---

var/spack/repos/builtin/packages/dejagnu/package.py

Depends on #3517 to be merged first.

Add DejaGnu package

---

var/spack/repos/builtin/packages/intel-parallel-studio/package.py
var/spack/repos/builtin/packages/intel/package.py

Add env vars for Intel VTune Amplifier

---

var/spack/repos/builtin/py-dev/__init__.py.patch
var/spack/repos/builtin/py-dev/package.py

This package is needed for tensorflow

Initial add of dev package

---

var/spack/repos/builtin/packages/dejagnu/package.py
var/spack/repos/builtin/packages/gcc/package.py

Various changes to make the GCC package simpler.

Clean up the gcc package

---

var/spack/repos/builtin/packages/libunistring/package.py

`make check` passes with flying colors in the latest release, yay!

Add latest version of libunistring

---

var/spack/repos/builtin/packages/bdw-gc/package.py

Add latest version of bdw-gc

---

var/spack/repos/builtin/packages/mozjs/package.py
var/spack/repos/builtin/packages/mozjs/perl-bug.patch

Add mozjs package

---

var/spack/repos/builtin/packages/util-linux/package.py

Add latest version of util-linux

---

lib/spack/spack/fetch_strategy.py

fixes https://github.com/LLNL/spack/issues/3179
with this PR
```
$ spack install dealii@develop
==> Installing dealii
==> zlib is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.10-oh65pcwikiqep74vtfaitp6ojgzivaag
...
==> gsl is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gsl-2.3-zpffzwkqlu2zkpp6f4gv6xppiqsxz63m
==> Trying to clone git repository:
https://github.com/dealii/dealii.git
==> No checksum needed when fetching with git
==> Already staged dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm in /Users/davydden/spack/var/spack/stage/dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm
==> No patches needed for dealii
==> Building dealii [CMakePackage]
==> Executing phase : 'cmake'
...
```

make git fetching quiet

---

var/spack/repos/builtin/packages/scotch/nonthreaded-6.0.4.patch
var/spack/repos/builtin/packages/scotch/package.py

ENH: add int64 variant to scotch

---

var/spack/repos/builtin/packages/cvs/package.py

Sometimes you need to connect to a traditional vcs.

this builds cvs CentOS Linux release 7.2.1511

---

var/spack/repos/builtin/packages/datamash/package.py

Direct spack to build datamash in a subdirectory

fix for #3588

---

var/spack/repos/builtin/packages/nextflow/package.py

Add support for nextflow versions 0.24.1 and 0.23.3.

nextflow: add info for versions 0.24.1 and 0.23.3

---

var/spack/repos/builtin/packages/mummer/package.py

Feedback on making the install bit prettier is welcome.
It works as is, but....

New package: mummer

---

var/spack/repos/builtin/packages/bats/package.py

Add package for the BASH Automated Testing System.

Add package for BATS

---

var/spack/repos/builtin/packages/py-abipy/package.py
var/spack/repos/builtin/packages/py-apscheduler/package.py
var/spack/repos/builtin/packages/py-html2text/package.py
var/spack/repos/builtin/packages/py-monty/package.py
var/spack/repos/builtin/packages/py-netcdf4/package.py
var/spack/repos/builtin/packages/py-palettable/package.py
var/spack/repos/builtin/packages/py-pydispatcher/package.py
var/spack/repos/builtin/packages/py-pymatgen/package.py
var/spack/repos/builtin/packages/py-pytz/package.py
var/spack/repos/builtin/packages/py-seaborn/package.py
var/spack/repos/builtin/packages/py-spglib/package.py
var/spack/repos/builtin/packages/py-tzlocal/package.py

@gmatteo I noticed that you wrote our `abinit` package. Thank you! A lot of our users at ANL use abinit, and have requested abipy as well. Can you take a look at this package and see if everything looks good, since you're the developer?

Add abipy package and dependencies

---

var/spack/repos/builtin/packages/gnutls/package.py

Fix url fetching for GnuTLS

---

var/spack/repos/builtin/packages/perl-xml-parser/package.py

Issue #1817 mentioned the need for a perl XML::Parser module. This is it.

perl-xml-parser: add perl XML::Parser package

---

var/spack/repos/builtin/packages/bison/package.py

- for programs that don't yet work with bison 3.x

CONFIG: add older bison version 2.7

---

var/spack/repos/builtin/packages/perl-dbi/package.py
var/spack/repos/builtin/packages/perl/package.py
var/spack/repos/builtin/packages/qbank/package.py

An ancient allocations management system that we still regrettably use. I really only needed to build it to get the documentation.
Technically depends on #3640 for an older version of Perl. I couldn't get the documentation to build with any newer version of Perl.

Add QBank package

---

var/spack/repos/builtin/packages/llvm-openmp-ompt/package.py
var/spack/repos/builtin/packages/pruners-ninja/package.py
var/spack/repos/builtin/packages/rempi/package.py

tools for PRUNERS (Providing Reproducibility for Uncovering Non-deterministic Errors in Runs on Supercomputers). More info at https://github.com/PRUNERS.

new and updated PRUNERS tools

---

var/spack/repos/builtin/packages/libzip/package.py

libzip is a C library for reading, creating, and modifying zip archives.

Add a package: libzip.

---

var/spack/repos/builtin/packages/py-easybuild-easyblocks/package.py
var/spack/repos/builtin/packages/py-easybuild-easyconfigs/package.py
var/spack/repos/builtin/packages/py-easybuild-framework/package.py

follow-up for #3658 which was merged a bit prematurely by @tgamblin 
cc @adamjstewart

fix version specs for EasyBuild packages

---

lib/spack/spack/package.py
lib/spack/spack/test/data/web/1.html
lib/spack/spack/test/data/web/2.html
lib/spack/spack/test/data/web/3.html
lib/spack/spack/test/data/web/4.html
lib/spack/spack/test/data/web/index.html
lib/spack/spack/test/web.py
lib/spack/spack/url.py
lib/spack/spack/util/web.py
var/spack/repos/builtin/packages/autogen/package.py
var/spack/repos/builtin/packages/boost/package.py
var/spack/repos/builtin/packages/cmake/package.py
var/spack/repos/builtin/packages/elfutils/package.py
var/spack/repos/builtin/packages/gcc/package.py
var/spack/repos/builtin/packages/gdal/package.py
var/spack/repos/builtin/packages/hwloc/package.py
var/spack/repos/builtin/packages/hydra/package.py
var/spack/repos/builtin/packages/mpich/package.py
var/spack/repos/builtin/packages/openmpi/package.py
var/spack/repos/builtin/packages/openssl/package.py
var/spack/repos/builtin/packages/pango/package.py
var/spack/repos/builtin/packages/patchelf/package.py
var/spack/repos/builtin/packages/py-nose/package.py
var/spack/repos/builtin/packages/py-scikit-learn/package.py
var/spack/repos/builtin/packages/python/package.py
var/spack/repos/builtin/packages/qt-creator/package.py
var/spack/repos/builtin/packages/qt/package.py
var/spack/repos/builtin/packages/util-linux/package.py

Fix spack versions

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/directives.py
lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py
var/spack/repos/builtin.mock/packages/conflict-parent/package.py
var/spack/repos/builtin.mock/packages/conflict/package.py
var/spack/repos/builtin/packages/openblas/package.py

new directive: conflicts

---

var/spack/repos/builtin/packages/jq/package.py

I was picking this up free until I tried it on yet another system.

Add depends_on() new-ish bison

---

lib/spack/spack/spec.py

In case anybody wonders: sometimes you just need to ask @tgamblin where to put an underscore in the code...

Fixes #3675 ( Abinit: invalid spec on concretization)

---

var/spack/repos/builtin/packages/gcc/package.py
var/spack/repos/builtin/packages/zip/package.py

Add zip package

---

var/spack/repos/builtin/packages/pngwriter/package.py

Adds the latest release of PNGwriter.

PNGwriter: 0.6.0

---

var/spack/repos/builtin/packages/libsplash/package.py
var/spack/repos/builtin/packages/pngwriter/package.py

Use new CMakePackage base class

libSplash & PNGwriter: CMakePackage

---

lib/spack/docs/tutorial_sc16_spack_basics.rst

-d was changed to -R as of PR #1917

Correct uninstall -d to uninstall -R in tutorial

---

var/spack/repos/builtin/packages/openssh/package.py

Add package for OpenSSH

---

lib/spack/spack/spec.py
var/spack/repos/builtin/packages/abinit/package.py
var/spack/repos/builtin/packages/hdf5/package.py
var/spack/repos/builtin/packages/libxc/package.py
var/spack/repos/builtin/packages/netcdf-fortran/package.py

I plan to modify `fftw` in another PR. 
@gmatteo I can't request you as a reviewer from the interface to the right, so I'll ping you here.

Abinit: a few modernizations for the package and its dependencies 

---

var/spack/repos/builtin/packages/libedit/package.py

Tell libedit to link to -lncursesw

---

var/spack/repos/builtin/packages/py-yt/package.py
var/spack/repos/builtin/packages/rockstar/adjust_buildscript.patch
var/spack/repos/builtin/packages/rockstar/package.py

Adds the rockstar halo finder package along with variants to yt.

Add the rockstar package

---

var/spack/repos/builtin/packages/go/package.py

Update for go@1.8.1.
Built on CentOS 7.

Add info for go@1.8.1

---

var/spack/repos/builtin/packages/pkg-config/package.py

Fixes #3670. @eschnett can you see if this solves your problem?

Append system PKG_CONFIG_PATH on Cray instead of prepend

---

var/spack/repos/builtin/packages/cudnn/package.py

In #3235, @muffgaga hasn't replied on the refinement proposals for about 3 days. It is quite urgent for me to use cudnn thus I resubmit a PR with slight modification. 
**LIMITATION**: As the file name `cudnn-8.0-linux-x64-v5.1.tgz` indicates, this package works for `cudnn@5.1` against `cuda@8.0` on x86_64 Linux platform only. Future work can be done to adapt it to more platforms.

A new package: cudnn.

---

var/spack/repos/builtin/packages/py-backports-shutil-get-terminal-size/package.py
var/spack/repos/builtin/packages/py-backports-ssl-match-hostname/package.py

Those two are probably not the only ones...

Fix namespaced python packages

---

lib/spack/docs/index.rst
lib/spack/docs/known_issues.rst

i got tired answering the same known issues like https://github.com/LLNL/spack/issues/3720 and https://github.com/LLNL/spack/issues/3001 , so let's help users with a short lists of know issues and workarounds.

doc: start with known issues section

---

var/spack/repos/builtin/packages/git/package.py

Install the `git-completion.{bash,tcsh,zsh}` and `git-prompt.sh`into `$(spack location -i git)/share` (aka `prefix.share`).
Closes #3778

Install the shell completion scripts

---

var/spack/repos/builtin/packages/cscope/package.py

@sknigh Can you see if this fixes #3783?

Help cscope find ncursesw library

---

lib/spack/docs/known_issues.rst

I sure do miss `spack extensions`... 😢

Document commands that no longer work

---

var/spack/repos/builtin/packages/bowtie/package.py

TODO: Merge with the package `bowtie2`.

A new package: bowtie.

---

lib/spack/spack/package.py

Add documentation on explicit param for do_install

---

var/spack/repos/builtin/packages/mvapich2/package.py

This could really use @alalazo's #2386... Ping @tgamblin

Add variant to mvapich2 to control thread level

---

var/spack/repos/builtin/packages/pegtl/package.py

New package: PEGTL

---

var/spack/repos/builtin/packages/py-pkgconfig/package.py

Fixes #1285.
@eschnett Can you see if this lets you build `py-h5py`?

Add a py-pkgconfig package

---

var/spack/repos/builtin/packages/flash/package.py

Add a package for FLASh (bioinformatics)

---

var/spack/repos/builtin/packages/tut/package.py

New package: tut

---

var/spack/repos/builtin/packages/boostmplcartesianproduct/package.py

New package: boost-mpl-cartesian_product

---

var/spack/repos/builtin/packages/flecsi/package.py

New package: flecsi

---

var/spack/repos/builtin/packages/random123/package.py

random123: install uniform.hpp as well

---

var/spack/repos/builtin/packages/trilinos/package.py

trilinos: allow to compile exodus

---

var/spack/repos/builtin/packages/charm/package.py

charm: add support for shared linking

---

var/spack/repos/builtin/packages/cppad/package.py
var/spack/repos/builtin/packages/elemental/package.py
var/spack/repos/builtin/packages/libsplash/package.py
var/spack/repos/builtin/packages/pngwriter/package.py
var/spack/repos/builtin/packages/symengine/package.py

Remove redundant cmake dependencies

---

var/spack/repos/builtin/packages/openblas/openblas0.2.19.diff
var/spack/repos/builtin/packages/openblas/package.py

note that this patch is merge upstream

opneblas: fix compilation with clang

---

var/spack/repos/builtin/packages/py-fiscalyear/package.py
var/spack/repos/builtin/packages/py-hypothesis/package.py
var/spack/repos/builtin/packages/py-pytest-runner/package.py
var/spack/repos/builtin/packages/py-pytest/package.py

Shameless plug for a really cool Python module I wrote! Ok, it's not actually that cool... But it was really useful for managing our quarterly allocation requests here at ANL! Check it out:
https://github.com/adamjstewart/fiscalyear

Add a py-fiscalyear package

---

var/spack/repos/builtin/packages/apr-util/package.py

Fixes #3826, but contingent on #3772

Added expat dependency to apr-util

---

var/spack/repos/builtin/packages/charm/package.py

@citibeth 
see https://github.com/LLNL/spack/pull/3852#pullrequestreview-32996651 for details

charm: set sane default

---

var/spack/repos/builtin/packages/adios/package.py

This is silly, and unfortunate, but these lines seem to have gone missing somewhere (sorry).

add lines missed in rebase (adios +bzip2)

---

share/spack/setup-env.sh

Is there a reason we weren't already doing this...?

Add lmod files to MODULEPATH

---

lib/spack/spack/build_systems/perl.py
lib/spack/spack/build_systems/python.py
lib/spack/spack/build_systems/r.py

Small change, but would definitely need some testing. @scheibelp I'm not incredibly familiar with our deptypes and these build systems, but does this seem like the right thing to do? @lee218llnl 
I'm wondering if this would fix things like #3772

Set proper deptypes for certain build systems

---

share/spack/setup-env.sh

Revert "Add lmod files to MODULEPATH"

---

var/spack/repos/builtin/packages/emacs/package.py

Add version info for emacs@25.2

---

var/spack/repos/builtin/packages/eccodes/package.py

Recommended dependency for libemos

eccodes: new package for encoding and decoding meteorological data

---

var/spack/repos/builtin/packages/cntk/build.patch
var/spack/repos/builtin/packages/cntk/kaldireader-openblas.patch
var/spack/repos/builtin/packages/cntk/package.py
var/spack/repos/builtin/packages/cntk1bitsgd/package.py
var/spack/repos/builtin/packages/multiverso/cmake-143187.patch
var/spack/repos/builtin/packages/multiverso/package.py

[The Microsoft Cognitive Toolkit](https://github.com/Microsoft/CNTK) (https://www.microsoft.com/en-us/research/product/cognitive-toolkit/), is a unified deep-learning toolkit that describes neural networks as a series of computational steps via a directed graph.

A new package: CNTK.

---

var/spack/repos/builtin/packages/ipopt/package.py

fixes https://github.com/LLNL/spack/issues/3983

ipopt: fix build with Linux clang

---

var/spack/repos/builtin/packages/perl/package.py

perl: identify dependency on gdbm

---

var/spack/repos/builtin/packages/xsdk/package.py

Commit-type: bug-fix
Project: xSDK
Reported-by: "Klinvex, Alicia Marie" <amklinv@sandia.gov>
@tgamblin @amklinv

Update checksum for dummy xsdk package

---

var/spack/repos/builtin/packages/sqlite/package.py

Add missing readline dependency to sqlite

---

lib/spack/llnl/util/filesystem.py
lib/spack/spack/build_environment.py
lib/spack/spack/build_systems/python.py
lib/spack/spack/cmd/checksum.py
lib/spack/spack/cmd/create.py
lib/spack/spack/cmd/edit.py
lib/spack/spack/cmd/url.py
lib/spack/spack/directives.py
lib/spack/spack/environment.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/mirror.py
lib/spack/spack/package.py
lib/spack/spack/spec.py
lib/spack/spack/test/modules.py
lib/spack/spack/test/python_version.py
lib/spack/spack/url.py
lib/spack/spack/util/naming.py
lib/spack/spack/util/pattern.py

Follow on to #3920.
- Sometimes you need something mindless to do.
- Sometimes it can be helpful and satisfy your OCD, as well.

Convert rest docstrings to Google docstrings.

---

var/spack/repos/builtin/packages/root/package.py

Also converts to `CMakePackage` and adds several missing dependencies.
@gartung It looks like you wrote the original package in #1830. Can you test my changes out and make sure they didn't break anything for you?

Add latest versions of root

---

var/spack/repos/builtin/packages/flecsi/package.py
var/spack/repos/builtin/packages/legion/package.py

flecsi: add mpi interoperability

---

var/spack/repos/builtin/packages/relion/package.py

package for relion version 2.0.3

 add relion package

---

var/spack/repos/builtin/packages/portage/package.py

New package: portage

---

var/spack/repos/builtin/packages/dealii/package.py

@MathiasMen : could you please copy-paste the content of `package.py` (File Changes->View->Raw) and check if this still fixes your problem?

dealii: fix missing -march=native in flags

---

var/spack/repos/builtin/packages/pgi/package.py

Also updated comment. The tarball no longer needs to be renamed.

Add latest version of PGI compilers

---

var/spack/repos/builtin/packages/dash/package.py
var/spack/repos/builtin/packages/ncurses/package.py

@tgamblin This might help with #4048.

Add a new package for dash

---

var/spack/repos/builtin/packages/flecsale/package.py

flecsale: works with python3

---

var/spack/repos/builtin/packages/ghostscript/package.py

Fixes #4057.
@KineticTheory Wanna take this for a spin?

Allow ghostscript to build with Spack dependencies

---

var/spack/repos/builtin/packages/findutils/package.py

Add findutils package

---

var/spack/repos/builtin/packages/py-lxml/package.py

Update the py-lxml package

---

var/spack/repos/builtin/packages/wget/package.py

Building wget depends on a perl option present only after 5.12.0

building wget depends on perl > 5.12.0

---

lib/spack/spack/build_environment.py

fixes https://github.com/LLNL/spack/issues/4064

only add direct build-only dependencies to PATH

---

lib/spack/spack/build_environment.py

Closes #3772.
implement https://github.com/LLNL/spack/pull/4069#issuecomment-299079865

add transitive run dependencies of direct build dependencies

---

var/spack/repos/builtin/packages/charm/package.py
var/spack/repos/builtin/packages/matlab/package.py
var/spack/repos/builtin/packages/npb/package.py
var/spack/repos/builtin/packages/plumed/package.py
var/spack/repos/builtin/packages/texlive/package.py

variants: fixed packages reported by @adamjstewart in #4098

Updated variants in a few packages

---

var/spack/repos/builtin/packages/jdk/package.py

My users have an irresistible need....

Add info for jdk@8u73

---

var/spack/repos/builtin/packages/boost/package.py
var/spack/repos/builtin/packages/openfoam-com/package.py
var/spack/repos/builtin/packages/openfoam-org/package.py

Python 3 doesn't have iteritems, use items

---

var/spack/repos/builtin/packages/perl/package.py

What the user wants, the user gets....

Add info for perl@5.22.1

---

README.md

Would people be interested in this? It looks and functions like this one:
https://github.com/adamjstewart/fiscalyear

Add Read the Docs badge to README

---

var/spack/repos/builtin/packages/scala/package.py

Port from epfl-scitas#67. Is there a way to merge this that preserves the original author @nvarini ?

scala: added package

---

var/spack/repos/builtin/packages/py-asn1crypto/package.py
var/spack/repos/builtin/packages/py-cryptography/package.py
var/spack/repos/builtin/packages/py-idna/package.py
var/spack/repos/builtin/packages/py-ipaddress/package.py
var/spack/repos/builtin/packages/py-paramiko/package.py
var/spack/repos/builtin/packages/py-pyasn1/package.py
var/spack/repos/builtin/packages/py-pycrypto/package.py

I need Paramiko and these other extensions. added extension needed in my use case.
unsure is dependency have been specified correctly

Paramiko python extensions + his deps and other related extensions

---

lib/spack/spack/compilers/pgi.py

@serbanmaerean Can you try this out and see if it allows Spack to pick up your PGI compilers?
See #4047 for discussion.

Fix PGI compiler detection on PowerPC

---

lib/spack/spack/test/spec_syntax.py

It seems that parse_anonymous_spec may fail if more than one part (variant, version range, etc.) is given to the function. Added tests to code against to fix the problem in #4144.

spec_syntax: added xfailing tests for cases in #4144

---

var/spack/repos/builtin/packages/funhpc/package.py

Also use a Spack-provided GoogleTest.

funhpc: Update to version 1.3

---

var/spack/repos/builtin/packages/gcc/package.py

@hartzell Can you see if this fixes #4175? At this point I don't even understand Python anymore. If someone can explain raw strings to me I would be eternally grateful.

Fix newline character in GCC package

---

var/spack/repos/builtin/packages/openmpi/package.py

Open MPI: add 2.1.1 to the list

---

var/spack/repos/builtin/packages/py-cdat-lite/package.py

Added new package for managing and analysing climate science data

Python cdat-lite package

---

lib/spack/spack/mirror.py

Can I get a _hip, hip, hooray!_ for actually useful error messages?
```
$ spack fetch ont-albacore
==> Error: 'NoneType' object has no attribute 'lstrip'
```
```
$ spack fetch ont-albacore
==> Error: Unable to parse extension from https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-1.1.0-cp35-cp35m-manylinux1_x86_64.whl.
If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:
version('1.2.3', 'hash', extension='tar.gz')
If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:
version('1.2.3', 'hash', expand=False)
```
Closes #4202. Hopefully things will be more …

Add helpful error message for uncompressed downloads

---

var/spack/repos/builtin/packages/ont-albacore/package.py
var/spack/repos/builtin/packages/py-cutadapt/package.py
var/spack/repos/builtin/packages/py-ont-fast5-api/package.py
var/spack/repos/builtin/packages/py-xopen/package.py

changes made per rejected #4217 
thanks again @adamjstewart

albacore and cutadapt again

---

var/spack/repos/builtin/packages/ont-albacore/package.py

Fixes #4239, closes #4241.
@JusticeForMikeBrown

albacore requires setuptools as build and run requirement

---

var/spack/repos/builtin/packages/py-matplotlib/package.py

@alalazo Curious to see if I can get this to pass the unit tests. I branched it directly off of the commit from #4266.

Add latest version of matplotlib

---

var/spack/repos/builtin/packages/miniconda2/package.py
var/spack/repos/builtin/packages/miniconda3/package.py

These releases survived simplisitic testing on CentOS 7.

Add info for miniconda[23]@4.3.14

---

var/spack/repos/builtin/packages/armadillo/package.py

added new version 7.900.1

---

var/spack/repos/builtin/packages/mpifileutils/package.py

This is using some old style spack.  I realize this needs some updating, so I'm happy for any help with that.  Thanks!

Mpifileutils

---

var/spack/repos/builtin/packages/cpprestsdk/package.py

Handy for communicating with external webservices from C++ apps.

Add Microsoft's C++ Rest SDK

---

var/spack/repos/builtin/packages/plumed/package.py

Tested with `mvapich2@2.2` and `gcc@5.4.0`

plumed: fixed compilation on rhel6

---

var/spack/repos/builtin/packages/libpciaccess/package.py

Builds fine for me with Intel 17.

Add latest version of libpciaccess

---

var/spack/repos/builtin/packages/r-rgl/package.py

added new R package - r-rgl

---

var/spack/repos/builtin/packages/trilinos/package.py

Fix #4285.
First version. One question I have is: if my external package (resource) has version numbering different from the original package, is it possible to request a specific version of the resource?

Trilinos: add DTK external package

---

var/spack/repos/builtin/packages/py-configparser/package.py
var/spack/repos/builtin/packages/py-entrypoints/package.py
var/spack/repos/builtin/packages/py-ordereddict/package.py

@healther Can you see if this fixes #4327?

Add missing dependency to py-entrypoints

---

var/spack/repos/builtin/packages/ant/package.py

Users want @1.9.6, users get @1.9.6.

Add ant@1.9.6 info

---

var/spack/repos/builtin/packages/mfem/package.py

Updating mfem version to 3.3 to get newest examples in release tarball.

updating mfem version

---

var/spack/repos/builtin/packages/bwa/package.py

Work around varying github URLs.
See #4365 for details.

Fix bwa url's

---

var/spack/repos/builtin/packages/xmlto/package.py

Fix #3851 xmlto migrated to https://pagure.io/xmlto

Fix #3851 xmlto fetch

---

var/spack/repos/builtin/packages/libharu/package.py
var/spack/repos/builtin/packages/wt/package.py

Adds `wt` "witty", a Qt-like C++ web framework for GUIs.
**Homepage:** http://www.webtoolkit.eu/wt
**GitHub Repo:** https://github.com/emweb/wt
@jkelling can you please report if the commands
succeed for you?
Both work for me, the second requires #4392, #4394

Package: Wt

---

var/spack/repos/builtin/packages/trimmomatic/package.py
var/spack/repos/builtin/packages/trimmomatic/trimmomatic.sh

See the discussion about installing jar files in #4386.
Also installs a wrapper script that has explicit references to the prerequisite java exe and to the jar file in it's final resting place.

Add a package for Trimmomatic

---

var/spack/repos/builtin/packages/postgresql/package.py

postgresql: Fix build with threadsafe and add variant.

---

var/spack/repos/builtin/packages/folly/package.py

Also modified double-conversion to use 'pic'.

folly: added new package.

---

var/spack/repos/builtin/packages/nalu/package.py
var/spack/repos/builtin/packages/superlu/package.py
var/spack/repos/builtin/packages/trilinos/package.py
var/spack/repos/builtin/packages/yaml-cpp/package.py

Ok, this is fairly involved courtesy of Trilinos. This adds the Nalu application from the Wind ECP. I have tried to not entirely change the way the Trilinos package works by default, but inevitably it must evolve, and I think this is the next step. This is just the beginning of numerous modifications I will likely need to make to this pull request, but this builds Nalu for me.
I don't see any way to select reviewers here, so @davydden please let me know if this will break deal ii.

Adding Nalu package.

---

var/spack/repos/builtin/packages/bml/package.py
var/spack/repos/builtin/packages/lanl-bml/package.py

Added LANL's BML library as Spack Package as dependency for future
packages

New Package: bml

---

lib/spack/spack/build_systems/makefile.py
var/spack/repos/builtin/packages/esmf/package.py

Also converts ESMF to `MakefilePackage`.

Add an installcheck phase to MakefilePackage

---

var/spack/repos/builtin/packages/czmq/package.py

Also bump to latest stable version.

czmq: Fix invocation when building with clang.

---

var/spack/repos/builtin/packages/py-binwalk/package.py
var/spack/repos/builtin/packages/rose/package.py
var/spack/repos/builtin/packages/spot/package.py
var/spack/repos/builtin/packages/z3/package.py

This pull request updates the definition for Rose, adding several options and making the definition more idiomatic by changing it to be an AutotoolsPackage.

Updates rose definition

---

bin/sbang
var/spack/repos/builtin/packages/intltool/package.py

Had to modify bin/sbang to support intltool scripts that are like
#!/bin/perl -w

fix intltool_sbang issue #4191

---

var/spack/repos/builtin/packages/h5utils/package.py
var/spack/repos/builtin/packages/libmatheval/package.py

Couldn't get `libmatheval` to build, but `h5utils` builds just fine.

Add h5utils package

---

var/spack/repos/builtin/packages/nalu/package.py
var/spack/repos/builtin/packages/trilinos/package.py

Nalu requires Trilinos with Exodus support

---

var/spack/repos/builtin/packages/fenics/package.py

Fixes #4472.
@mpilosov Can you test this out? The problem was that one of the optional dependencies (sphinx) depended on whether or not the `+doc` variant was on, but there was no `+doc` variant! As far as I can tell, it looks like this variant was always missing. I'm not sure why it didn't raise an error message before. Possibly related to @alalazo's recent work on multi-valued variants. I agree the error message could be more helpful though. I don't know how to fix that one but @alalazo might.
While I was at it I made a few unrelated changes. Converted `fenics` to `CMakePackage`. Also fixed a couple deptypes. I can't imagine that `eigen` is only a build dependency or `cmake` is a run-time dependency, but correct me if I'm wrong. Also separated the Python component installation into 2 …

Add missing doc variant to fenics package

---

lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py

issue 4492: DependencyMap.concrete checks for unconditional dependencies

---

var/spack/repos/builtin/packages/votca-csg/package.py

votca-csg: fixing develop url

---

var/spack/repos/builtin/packages/fontconfig/package.py

Nicely, this fixes build failure on aarch64 with clang :)

fontconfig: Update to latest stable release

---

var/spack/repos/builtin/packages/gnutls/package.py
var/spack/repos/builtin/packages/libpsl/package.py
var/spack/repos/builtin/packages/wget/package.py

Currently blocked by #4113 and #4112. Marking this as a WIP.

Various updates to wget and dependencies

---

var/spack/repos/builtin/packages/andi/package.py
var/spack/repos/builtin/packages/libdivsufsort/package.py

Adding andi and its dependency libdivsufsort

Andi and libdivsufsort

---

lib/spack/spack/util/executable.py

Fixes #4577 
Supercedes #4578 
@adamjstewart @alalazo @tgamblin

fix issue #4577

---

var/spack/repos/builtin/packages/gmap-gsnap/package.py

gmap-gsnap: adding gmap-gsnap package

New package gmap-gsnap

---

var/spack/repos/builtin/packages/albert/package.py

New package albert

---

var/spack/repos/builtin/packages/augustus/package.py

New package augustus

---

var/spack/repos/builtin/packages/flex/package.py

Fixes #4583
Not the most elegant, but I'll leave it to @mjwoods to cleanup.

BUG: flex+lex fails with lib64/ installation (issue #4583)

---

var/spack/repos/builtin/packages/suite-sparse/package.py

suite-sparse: add openmp variant

---

var/spack/repos/builtin/packages/cntk/build.patch
var/spack/repos/builtin/packages/cntk/package.py

…on on the head of the git repo

Minor fixes to CNTK package

---

var/spack/repos/builtin/packages/votca-xtp/package.py

votca-xtp: new package

---

lib/spack/spack/__init__.py

Fixes #4526 
Closes #4527 
@tgamblin @ax3l Can you test this?

Don't immediately raise an error when an editor is not found

---

var/spack/repos/builtin/packages/vpic/package.py

vpic: new package
