var/spack/repos/builtin/packages/zoltan/package.py
This PR adds logic for zoltan to detect metis with 64b ints and append the necessary configure flag for compatibility.
=> zoltan: detect metis int64 variant

var/spack/repos/builtin/packages/redundans/package.py
couldn't find an actual release tarball for 0.14a but several commits which seem to indicate it,
cleaned up the install process if new files are added in the future.
older release marked as preferred over the alpha release.
=> redundans: add 0.14a, cleanup install

var/spack/repos/builtin/packages/libsodium/package.py
The source URL for versions 1.0.15 and older is updated to reflect where
those archives are now hosted by the upstream libsodium developers.
While two new releases of libsodium are available,
```
version('1.0.17', sha256='0cc3dae33e642cc187b5ceb467e0ad0e1b51dcba577de1190e9ffa17766ac2b1')
version('1.0.16', sha256='eeadc7e1e1bcef09680fb4837d448fbdf57224978f865ac1c16745868fbd0533')
```
This commit does not attempt to add them to the spack package since the
author has not tested them nor checked for other packages that might be
affected. This simply updates the location of the source archives during
the "fetch" stage of installation.
=> libsodium: Updates source URL.

var/spack/repos/builtin/packages/mercury/package.py
The Mercury package previously depended on libfabric@develop on Cray platforms in order to pick up a fix for the GNI provider that was only available in git.  This is no longer needed now that the libfabric package is at 1.7.0.  
This PR removes the special case dependency on Cray platforms.
=> change Mercury's libfabric dependency on Cray platforms

var/spack/repos/builtin/packages/fftw/package.py
Fixed issue #7372 with building fftw@2
Added patch method which renames config.h in the fftw subdir of the source tree.  fftw 2.1.5 appears to ship with a copy of this file with all defines commented out.  This gets read by the #include directives instead of the version in the build directory with the correct defines.  As a result, many C preprocessor macros left undefined, including F77_FUNC_ which causes the bulk of fttwf77.c to be skipped due to an #ifdef, so fftw_reverse_int_array et al not included in library.
Also fixed some inconsistencies with the handling of quad and long_double in specs between the configure method and the build, check, and install methods.
=> fftw: fix issue #7372/rename config.h in source tree

var/spack/repos/builtin/packages/openjdk/package.py
closes #2622
I got annoyed trying to install jdk about 20 min ago.
Anyway, it seems it's much easier to get a binary distribution of openjdk with version 11. 
This is basically entirely copied from the jdk package to hopefully provide similar functionality. There are binaries for windows and macos as well, but I'm not sure how to denote different downloads for different os versions.
=> openjdk: adding new package openjdk

var/spack/repos/builtin/packages/py-pybigwig/package.py, var/spack/repos/builtin/packages/py-pybigwig/python3_curl.patch
* added patch to correctly pick up non-system curl when building with python 3
* added numpy variant
* updated version and checksums
=> py-pybigwig: fix build with python3 and numpy variant

var/spack/repos/builtin/packages/gatk/package.py
Fixes gatk so it works with gatk4+.
Closes #10168.
It seems like "jdk" package is broken currently.  The only way I was able to get this to work was to first apply #10446.  Then set $SPACK_ROOT/etc/spack/packages.yaml from "java: [jdk]" to "java: [openjdk]".
=> Fixing gatk4

var/spack/repos/builtin/packages/dyninst/package.py, var/spack/repos/builtin/packages/dyninst/tribool.patch
Add tribool.patch to add explicit casts from tribool to bool in two
places.  Boost, starting with version 1.69, turned on explicit
conversions for tribool, which breaks the build for dyninst.
----------
The purpose of this PR is to allow dyninst 9.3.x and 10.0.0 to work
with the latest boost >= 1.69.
Also, probably within a week, I expect dyninst 10.1.0 to be released.
10.1 will include the patch.
My plan is to wait for 10.1 to be tagged and released and fold that
into this PR.  It's a 1-line change to add version 10.1.0 and I could
add that line now.  (I know what the tag will be.)  We just have wait
until the tag exists before merging the PR.
I'm leaning in favor of waiting, but we could do two commits if the
release is delayed.  Either way.
ping @hainest from dyninst
=> dyninst: add patch to work with new boost

var/spack/repos/builtin/packages/mercury/package.py
- optional mode that is faster and/or more robust in some cases on Cray
platforms
=> add 'udreg' variant to mercury package

var/spack/repos/builtin/packages/r-wgcna/package.py
depends on r-dynamictreecut (#10388), r-robust (#10391)
due to R version constraints, also depends on patches in #10390 and #10389
=> r-wgcna: new package at 1.64-1

var/spack/repos/builtin/packages/xsdk/package.py
should be merged after https://github.com/spack/spack/pull/10217
=> xsdk: enable slepc in deal.ii (used to be a concretization error)

var/spack/repos/builtin/packages/python/package.py
Also add versions 3.7.1, 3.6.8, 3.6.7, 3.6.6. Does NOT alter preferred version (2.7.15).
Supplants PR "Add Python 3.7.2" (https://github.com/spack/spack/pull/10491).
Verification builds on LANL Darwin:
**Intel Xeon**
```
[+] /scratch/users/dantopa/new-spack/pr.new.python-3.7.2/general/opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-3.7.2-d3p7vg6w2r563cpmwsmbgjbsiqc4j4fq
[+] /scratch/users/dantopa/new-spack/pr.new.python-3.7.2/general/opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-3.7.1-ibom6qj2z64egyaqz5htkwp5tr362il6
[+] /scratch/users/dantopa/new-spack/pr.new.python-3.7.2/general/opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-3.6.8-rkifc3c7mjgdglw27upiap767ut4wpkz
[+] /scratch/users/dantopa/new-spack/pr.new.python-3.7.2/general/opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-3.6.7-meue …
```
=> Add Python 3.7.2 updated

var/spack/repos/builtin/packages/paraview/package.py
I just realized the `vtkmodules` directory was missing from `PYTHONPATH` here. I need this to be able to use the Trilinos Catalyst adapter. @sbna @DarylGrunau
=> WIP: Adding missing paths to PYTHONPATH for Paraview > 5.4

var/spack/repos/builtin/packages/mafft/package.py
* updated mafft to v7.407 (release date 2018-07-23).
* previous version v7.221 was very old (2015-04-16)
Build was tested with gcc-8.2.0 on Centos 7, kernel 3.10.0-957.1.3.el7.x86_64
=> mafft: update to latest version

lib/spack/spack/platforms/cray.py
x86_64 as the frontend target does not get set in the cray platform.
This makes sure to add the target as named target x86_64 as well as the
aliased target front_end.  This fixes the issue where specifying
arch=cray-fe-x86_64 gives the error:
==> Error: ValueError: Can't recreate arch for spec cray-sles12-x86_64
on current arch cray-cnl6-mic_knl; spec architecture is too different
@scheibelp can you check whether this is a viable solution for @mwkrentel problem?
=> Add x86_64 as target to cray platform

var/spack/repos/builtin/packages/orthofiller/package.py
depends on packages introduced in #10360, as well as augustus which may require #10362 to build
=> orthofiller: new package at 1.1.4

lib/spack/spack/util/log_parse.py
Output before this PR:
```console
$ spack log-parse $(spack location -i hdf5@1.10.4)/.spack/build.out
0 errors
==> Error: max() arg is an empty sequence
```
and after this PR:
```console
$ spack log-parse $(spack location -i hdf5@1.10.4)/.spack/build.out
0 errors
```
=> Fixed an issue occurring when no error lines are found

var/spack/repos/builtin/packages/mirdeep2/package.py
many of the perl scripts installed to bin had incorrect permissions; explicitly performs chmod before installing
=> mirdeep2: make sure bins are executable

var/spack/repos/builtin/packages/netlib-scalapack/cmake_fortran_mangle.patch, var/spack/repos/builtin/packages/netlib-scalapack/package.py
This is a fix for builds with GCC 6/7/8 and CMake 2/3
I added it as an issues to upstream and future ScaLAPACK releases should be OK
https://github.com/Reference-ScaLAPACK/scalapack/issues/9
=> Add patch to fix Fortran mangling CMake test

.github/ISSUE_TEMPLATE/bug_report.md
See: https://github.com/spack/spack/issues/10544
https://github.com/spack/spack/commit/1137b183e32aae467b08be36d7223172d5d01337 removed the `-s` option from `spack` such that to see a stack trace you must pass the `--stacktrace` option. The bug report templates were not updated accordingly.
=> bug report template: suggest --stacktrace instead of -s

var/spack/repos/builtin/packages/meson/package.py, var/spack/repos/builtin/packages/meson/rpath.patch
rpath stripping breaks (at least) the gtkplus build because at-spi2-atk's dependencies can not be found.
=> meson: add 0.49.1 and disable rpath stripping

var/spack/repos/builtin/packages/cardioid/package.py
Using a non-standard build directory so the package can work with the existing testing code and scripts.  
Designed for use with spack diy for build development.
=> Adding a package for cardioid.

var/spack/repos/builtin/packages/libarchive/package.py
lzma was last updated in 2008 and has compilation
issues on some platforms. The format has been superceded
by xz (see e.g. https://tukaani.org/xz/).
=> libarchive: remove lzma dependency

share/spack/qa/run-docker-tests
Checking the latest build log, it looks like everything docker-related is working, except for what seems to be an issue with docker/dockerhub
See the end of this build log -- docker reports successful log in, but then fails to authenticate at push time:
https://api.travis-ci.org/v3/job/490096345/log.txt
Here are two (among many) github issues describing the problem:
https://github.com/docker/cli/issues/1180
https://github.com/docker/hub-feedback/issues/1222
This PR implements a fix suggested in a comment:
https://github.com/docker/hub-feedback/issues/1222#issuecomment-459390746
=> try to workaround an issue with docker/dockerhub

var/spack/repos/builtin/packages/man-db/package.py, var/spack/repos/builtin/packages/pxz/package.py
lzma has been superseded by xz. Followup of #10517.
=> remove remaining lzma dependencies

var/spack/repos/builtin/packages/xerces-c/package.py
Add variant to support compiling against main C++ standards if needed for ABI compatibility. Use 'default' value as Xerces-C autoconf system does not enforce a minimum, or set a default, C++ standard.
=> xerces-c: Add cxxstd variant

lib/spack/spack/build_systems/cmake.py, lib/spack/spack/test/build_systems.py
CMake supports the notion of secondary generators which provide extra information to (e.g.) IDEs over and above that normally provided by the primary generator.
The list of primary generators ('Unix Makefiles' and 'Ninja') supported by Spack has not changed.
Since the secondary generator is irrelevant to a Spack build, it is passed on to CMake without further validation.
=> Allow secondary generators when building with CMake.

lib/spack/docs/module_file_support.rst
Add some helpful hints about autload:
- default is `none`
- setting to `direct` for all can be useful when building external software that uses artifacts from within the spack tree.
See #10307.
=> Enhancement to module autoload documentation

lib/spack/llnl/util/lang.py, lib/spack/spack/test/llnl/util/lang.py
Spack allows to specify precise relative dates/times:
```bash
spack find --start-date "23 seconds ago"
```
but has only a very coarse precision when using absolute dates:
```bash
spack find --start-date 2018-12-25
```
I would like to add `HH:MM(:SS)?` to this for feature parity and allow:
```bash
spack find --start-date 2018-12-25\ 23:59
```
=> enh: allow time like HH:MM in date strings.

lib/spack/spack/hooks/permissions_setters.py
When installing openssl with write permission for group, the installation failed in post-install hook due to an attempt to change permission on a system file. It turns out that it is simply due to a small typo in the permission-setter.
=> Bug Fix in permission setter

var/spack/repos/builtin/packages/eigen/package.py
Considering how few mandatory dependencies Eigen has, it is a shame that Spack's Eigen package pulls in so many barely relevant dependencies by default, and requires users who care about their Docker image sizes and package build times to disable all of them one by one.
I would therefore propose to change the default to a more bare-bones Eigen install, and let those who are interested in Eigen's integration with various optional dependencies ask for them using the relevant variants.
=> Disable unnecessary default dependencies of Eigen

var/spack/repos/builtin/packages/pixman/package.py
0.34.0 fails to build with clang@7.0.1 with
```shell
630    1 warning generated.
>> 631    utils-prng.c:207:27: error: use of unknown builtin '__builtin_shuffle' [-Wimplicit-function-declarati
on]
632                randdata.vb = __builtin_shuffle (randdata.vb, bswap_shufflemask);
633                              ^
>> 634    utils-prng.c:207:25: error: assigning to 'uint8x16' (vector of 16 'uint8_t' values) from incompatible
type 'int'
635                randdata.vb = __builtin_shuffle (randdata.vb, bswap_shufflemask);
636                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
0.38.0 is fine.
=> add latest version of pixman

share/spack/setup-env.sh
See discussions in #7475 and #8443.  This patch attempts to make setup-env's shell detection work correctly when it is sourced within a shell script environment.  The target use cases are continuous integration environments or job scheduler scripts.
Test case:
```
#!/bin/bash
echo step: sourcing setup-env.sh
. /home/pcarns/working/src/spack/share/spack/setup-env.sh
echo step: loading mpich
spack load -r mpich
echo step: listing modules
module list
```
Without this PR, it produces the following output:
```
pcarns@carns-x1:~$ ./foo.sh 
step: sourcing setup-env.sh
step: loading mpich
init.c(379):ERROR:109: Unknown shell type 'foo.sh'
step: listing modules
init.c(379):ERROR:109: Unknown shell type 'foo.sh'
```
With this PR applied, it produces the following output:
```
pcarns@carns-x1:~$ …
```
=> make SPACK_SHELL detection more robust

var/spack/repos/builtin/packages/root/package.py
ROOT 6.16.00 is now out, so after checking that it still builds I updated the package release list.
While I was at it, I also moved everything else to SHA-256 checksums for consistency.
=> Add new ROOT releases, move to SHA-256 checksums

var/spack/repos/builtin/packages/dd4hep/package.py
This PR introduces a package for the DD4hep detector description toolkit, an attempt at standardizing HEP detector description tools which is currently being evaluated by numerous HEP experiments.
=> DD4hep package

var/spack/repos/builtin/packages/gaudi/package.py, var/spack/repos/builtin/packages/gaudi/use-xenv-master.diff, var/spack/repos/builtin/packages/relax/package.py
This MR introduces a package for the Gaudi HEP data processing framework, used by the LHCb and ATLAS experiments among other projects.
Gaudi also depends on RELAX, a set of ROOT dictionaries for typical HEP libraries. Since I know of no other package that depend on RELAX, I decided to bundle the two in this MR in order to save administrative/review work, but I can separate the two submissions if you think that is useful.
There is a small part of the RELAX package which I'm not very proud of, so I will highlight it in the MR thread and let you decide if there is a better way to do this.
=> Add Gaudi and RELAX packages

var/spack/repos/builtin/packages/icu4c/package.py
For versions supported in Spack, ICU4C defaults to the C++11 Standard. Provide a variant to default to this, plus options for C++14 and 17 if dependees require for ABI compatibility.
A `default` value for the variant is not supplied, as ICU4c's configure script appears to always fall back to C++11 if `CXXFLAGS` does not contain a `-std` flag.
=> icu4c: Add cxxstd variant

var/spack/repos/builtin/packages/xrootd/package.py
Deal with C++ standard as a multi-value variant for XRootD.
Also:
* add checksums for 4.8.4 and 4.8.5
* deactivate the Python support patch for 4.9.0 onward since its acceptance upstream.
=> xrootd: allow specification of C++ standard.

var/spack/repos/builtin/packages/pythia6/package.py
Fix two issues with the pythia6 recipe:
1. The checksum of an ASCII data file downloaded as part of the examples has changed.
1. An upstream change (possibly) has exposed an issue verifying the value of the `NMXHEP` variant parameter.
=> pythia6: fix input verification issue and example data checksum.

var/spack/repos/builtin/packages/cp2k/package.py, var/spack/repos/builtin/packages/libint/package.py, var/spack/repos/builtin/packages/libxc/package.py, var/spack/repos/builtin/packages/plumed/package.py
This PR contains a reworking of `cp2k` with a few improvements:
@baip @dev-zero
=> cp2k is now a MakefilePackage

lib/spack/env/cc, lib/spack/spack/build_environment.py, lib/spack/spack/test/build_environment.py
fixes #10601
fixes #10603 
Due to a bug this attribute is wrong for packages that use directories as namespaces. For instance it will add `<boost-prefix>/include/boost` instead of `<boost-prefix>/include` to the include path.
As a minor addition a few loops in the compiler wrappers have been simplified.
=> Compiler wrappers don't add "pkg.headers.directories" to the include list

var/spack/repos/builtin/packages/pumi/package.py
This PR adds the `simmodsuite`(#8730) variant to the `pumi` package.
=> new variant: simmodsuite for pumi

lib/spack/spack/reporters/cdash.py, lib/spack/spack/test/cmd/install.py
If the -f <specyamlfile> argument to install is used (rather than providing package specs on the command line), CDash throws an exception due to missing the installation command (the packages targeted for install).  This fixes that behavior so CDash reporting succeeds in either case.
=> CDash: Fix broken reporter when installing from spec.yaml

lib/spack/spack/binary_distribution.py
Use `list` rather than `set` when getting specs from YAML file (`spec.yaml`)
**Context**
Currently there seems to be cases where two specs, with different `dag`-hashes, share the same internal hash - returned by `hash(spec)`. This produces some problems when installing from binaries and using the hash to specify the package to be installed, example:
```
spack  buildcache install /123456789
```
Let's say there are two YAML files with the same name, version and compiler but different hashes such as:
```
linux-centos7-x86_64-gcc-6.2.0-packageA-1.0-987654321-spec.yaml
linux-centos7-x86_64-gcc-6.2.0-packageA-1.0-123456789-spec.yaml
```
I don't fully understand how this is even possible, but there are cases where the `specs` produced out of these two YAML files can have the same internal …
=> Fix bug getting specs from build caches

lib/spack/spack/build_environment.py
Fixes https://github.com/spack/spack/issues/10617
Fixes #10624
See also: https://github.com/spack/spack/pull/10621
Closes: https://github.com/spack/spack/pull/10619
@davydden @HadrienG2 
This handles a couple bugs reported on #8136. It universally adds `lib`/`lib64` directories as link/rpath directories. It also filters system paths from link/rpaths/includes.
* remove system paths from link/rpath/include dirs
* remove duplicate paths from collected link/rpath/include dirs
* always add lib and lib64 directories since default .libs only reports libs with a name matching the package name
=> Include lib/lib64 by default

var/spack/repos/builtin/packages/root/package.py
During discussion around https://github.com/spack/spack/pull/10583 , there was general agreement on the fact that the plural "Development versions" wording in ROOT's package.py was confusing, but the PR was merged too quickly for me to fix it. So here's my smallest Spack PR diff ever. :wink:
=> Fix plural typo in ROOT package

var/spack/repos/builtin/packages/qmcpack/package.py
This PR updates the CUDA support in QMCPACK:
- Removes the explicit CUDA variant in QMCPACK, since its now built into every package.
- Add support for passing CUDA_ARCH value into the QMCPACK's  CMake
=> Update CUDA support in QMCPACK

var/spack/repos/builtin/packages/openpmd-api/package.py
Refactor dependencies, increase new min versions, add mpi4py variant.
Depends on:
=> openPMD-api: mpi4py support

var/spack/repos/builtin/packages/openssl/package.py
1. Point out that OpenSSL uses a fake Autotools, and therefore should NOT subclass AutotoolsPackage.
2. Separate generations of versions by a blank line
3. Add a version
=> openssl: Add comments and version

var/spack/repos/builtin/packages/xxhash/package.py
On macOS, the build of libxxhash is performed by a bare `make` launched by `MakePackage`s default `build` phase. As `prefix` is not set in `xxhash`'s `Makefile` at this point, the library gets compiled with a hard-coded install name of `/usr/local/libxxhash.dylib`. Downstream clients, in the tested case Root, will then fail to build as the install name is incorrect.
Move setting of `prefix` from `install` to `edit` so that it propagates to subsequent `build` and `install` phases.
=> xxhash: edit prefix in Makefile for macOS

var/spack/repos/builtin/packages/diffutils/package.py, var/spack/repos/builtin/packages/gcc/package.py, var/spack/repos/builtin/packages/mpc/package.py, var/spack/repos/builtin/packages/time/package.py
This is a continuation of #8992.
I wasn't able to download `diffutils` from the previous URL. Switching to a mirror resolved the problem.
Successfully downloaded all 4 packages, and the checksums still match.
=> Download GNU packages from mirrors (Part 2)

bin/rebuild-index.sh, bin/rebuild-package.sh, etc/spack/defaults/release.yaml, lib/spack/docs/example_files/spec_set.yaml, lib/spack/docs/index.rst, lib/spack/spack/binary_distribution.py, lib/spack/spack/cmd/buildcache.py, lib/spack/spack/cmd/release_jobs.py, lib/spack/spack/cmd/upload_s3.py, lib/spack/spack/schema/os_container_mapping.py, lib/spack/spack/schema/spec_set.py, lib/spack/spack/schema/specs_deps.py, lib/spack/spack/spec.py, lib/spack/spack/spec_set.py, lib/spack/spack/test/cmd/release_jobs.py, lib/spack/spack/test/spec_set.py, lib/spack/spack/test/spec_yaml.py, lib/spack/spack/util/web.py, share/spack/docker/os-container-mapping.yaml, share/spack/docker/spack_builder/Dockerfile-spack_builder_centos_7, share/spack/docker/spack_builder/Dockerfile-spack_builder_ubuntu_18.04, share/spack/docker/spack_builder/update_rpaths.py, share/spack/templates/misc/buildcache_index.html
This topic implements several pieces needed to support a release workflow for Spack.  Some of the pieces included:
1. A new Spack command to create a description of packages for Gitlab-CI to build. It defines a gitlab-ci.yml file that would be placed in a repository, such that when Gitlab-CI detects a commit to the branch, it will build the packages mentioned in the description.  More details on this new command are provided further down in this PR description ("Details of `release-jobs` command).
2. A build job shell script to be run by Gitlab-CI.  The responsibility of this script is to be assigned a spec, determine if the package corresponding to that spec exists and is up-to-date on a configured binary mirror, and if it is not, build the package, create a buildcache for it, and push …
=> Release workflow

var/spack/repos/builtin/packages/gcc/package.py
Looks like commit 040b65876bea73c761aaaf32cf7886fb790f496c broke the gcc~nvptx build (i.e. the default).  This PR inserts the proper logic into nvptx_install to select (or not) the nvptx offload capability
=> Fix gcc~nvptx build

lib/spack/spack/build_environment.py
Spack warns users when a dependency package updates CPATH. This warning message is generating bug reports and alarm in cases where there is no problem. For now this downgrades the warning message to the debug level, so it only shows up if something goes wrong for the user.
Also note that https://github.com/spack/spack/pull/10644 may be merged soon which would avoid this issue entirely.
=> downgrade warning message to debug message

var/spack/repos/builtin/packages/ucx/package.py
https://github.com/openucx/ucx/releases/tag/v1.5.0
Released 2019-02-14
Verification builds on LANL Darwin:
**Intel Xeon**
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               1198.779
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              5193.70
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K …
=> Add UCX v1.5.0

var/spack/repos/builtin/packages/mono/package.py
Allow users to build recent version of mono.
Recipe is unchanged except for new urls.
=> Update mono package

var/spack/repos/builtin/packages/adios2/package.py
Adding ADIOS v2.3.1 to the check-summed versions.
cc @chuckatkins: you probably want to co-maintain ADIOS2's package and be pinged on updates?
First question: is it fine to use the git tag version on GitHub or should we take from 2.3.1 onward the newly uploaded release files?
=> ADIOS v2.3.1

var/spack/repos/builtin/packages/automake/package.py
This pull request:
* Adds automake version 1.13.4
* Replaces MD5 hashes for all versions of automake with SHA256 hashes
=> automake@1.13.4: add new version

var/spack/repos/builtin/packages/beast-tracer/package.py, var/spack/repos/builtin/packages/beast-tracer/tracer
Source includes a flaky launch script, replaced with one that just executes the compiled jar in the same manner.
=> beast-tracer: new package at 1.7.1

var/spack/repos/builtin/packages/acts-core/package.py
This is a build recipe for the ACTS HEP tracking toolkit.
=> Add an ACTS package

var/spack/repos/builtin/packages/slurm/package.py
- Add support for pmix
- Add support for installing pmi2 header and library
pmi2 support is currently a variant; maybe we should just do it by default?
=> slurm: Add PMI support

lib/spack/spack/util/module_cmd.py, var/spack/repos/builtin/packages/libhio/package.py
- Switch all libhio tarball listings to sha256 checksums
- Correct typo in alert message in /lib/spack/spack/util/module_cmd.py: fucntion -> function
https://github.com/hpc/libhio/releases
Released 2019-02-01
Verification builds on LANL Darwin:
**Intel Xeon**
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               1198.779
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000 …
=> Add libhio v1.4.1.3, 1.4.1.1

lib/spack/env/cc, lib/spack/llnl/util/filesystem.py, lib/spack/spack/build_environment.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/llnl/util/filesystem.py, var/spack/repos/builtin/packages/libxml2/package.py
This PR restores the computation of the include directories that was remove as part of the hotfix in #10604 It also adds the following modifications:
=> Restore computation of include directories

var/spack/repos/builtin/packages/eospac/package.py
This PR simply bumps the version of eospac to reflect new code availability.
=> Bump eospac version

var/spack/repos/builtin/packages/openblas/package.py
Piledriver is a codename for an AMD x86-64 processor, it can't
possibly make sense to compile for that if the architecture is
aarch64.
=> Don't try to build TARGET=PILEDRIVER on aarch64

var/spack/repos/builtin/packages/libbeagle/package.py
libbeagle compiles against CUDA by default but no there is no mention of it in the package recipe.
This PR adds explicit cuda paths and variants, and fixes the target architecture as well (for those who don't have compute_13)
=> libbeagle: add cuda flags, patches

lib/spack/spack/package.py
Fixes #10487.
@weidendo can you test this?
We need to be careful here, as `config.yaml` provides a `build_language` setting that we don't want to overwrite.
=> Fix 'make test' detection when LANG is not in English

var/spack/repos/builtin/packages/ior/package.py
The current sha256 sum seems wrong. Can check it by:
```
$ wget https://github.com/hpc/ior/archive/3.2.0.tar.gz
$ sha256sum 3.2.0.tar.gz
91a766fb9c34b5780705d0997b71b236a1120da46652763ba11d9a8c44251852
```
=> Fix sha256 sum for IOR

var/spack/repos/builtin/packages/blast-legacy/package.py
provides legacy `blastall` binary required by some older packages
=> blast-legacy: new package at 2.2.26

var/spack/repos/builtin/packages/bedops/package.py
by default bedops will try and statically link with stdc++; this patches the package to dynamically link instead
=> bedops: avoid static linking with glibc

var/spack/repos/builtin/packages/eigen/package.py, var/spack/repos/builtin/packages/python/package.py
Fixes https://github.com/spack/spack/issues/10769
~Closes https://github.com/spack/spack/pull/10751~ (EDIT: see https://github.com/spack/spack/pull/10773#issuecomment-469355115)
@HadrienG2 @davydden @jslee02 @alalazo 
https://github.com/spack/spack/pull/10623 updated the default behavior of `.headers.directories` to exclude subdirectories (since this can cause clashes with system headers). This broke some packages which depended on the old behavior of `.headers.directories`: for example if you had `<package-prefix>/include/subdir/ex1.h`, `.headers.directories` would include `<package-prefix>/include/subdir`.
This updates the `.headers` property to include subdirectories for Python and Eigen (as is recommended by these packages).
In hindsight, it was a mistake not to request documentation …
=> Update packages which need include subdirectories

var/spack/repos/builtin/packages/seacas/package.py
Modified NetCDF requirement to allow NetCDF-4.6.2 and subsequent versions.
=> seacas: Update NetCDF version requirement

var/spack/repos/builtin/packages/regcm/package.py
'any_combination_of' expects a sequence of objects, but was getting a single
iterable object (PR #9481).
This should fix and improve #9934, which was messed up by a fetch from `develop`.
There are some new versions of RegCM available:
```python
version('4.7.0-SVN6916',
sha256='cad66b760464b513afd318eb28a6820a0d4c8c55d3b23a34d06cb9c1b57aa0bc',
url='http://clima-dods.ictp.it/Users/ggiulian/RegCM-SVN6916.tar.gz')
version('4.7.0-SVN6884',
sha256='fd4eb0fbe911c6c4dacbaaf2a952a45ac8c1fa54a5d905972ffe592e47818c00',
url='http://clima-dods.ictp.it/Users/ggiulian/RegCM-SVN6884.tar.gz')
```
A new "official" version has not been released yet.
The latest version provides a partial support to `pnetcdf` (direct support, without using `netcdf`, would cost more developing time).
=> RegCM: intel FC 'hint', 4.7.0 intel warning, fcflags, fix extensions.

var/spack/repos/builtin/packages/openspeedshop/package.py
@jgalarowicz, my attempts to build openspeedshop in spack failed b/c it was specifying the PYTHON_INCLUDE_DIR only up to the python "include" path. The actual Python.h file is in the versioned sub directory pythonX.Y, i.e. "include/python2.7" for Python 2.7. CMake should be smart enough to figure this out, so in this PR, I remove the specification of the include directory. One could also specify it, but include the versioned sub directory if you feel that's a better solution.
=> do not specify python include path for oss package

var/spack/repos/builtin/packages/netcdf/package.py
NetCDF-4.6.3 has been released and follows the naming scheme introduced in NetCDF-4.6.2 which is the addition of "-c" prior to the version number.  Added a `url_for_version()` function to compose this URL.  Also updated the `url` to point to a version using the new naming convention so future versions will be discoverable using `spack checksum netcdf`.  Removed explicit url from the 4.6.2 version statement and added version statement for 4.6.3 with checksum.
=> NETCDF: Update for new version and naming

var/spack/repos/builtin/packages/erfa/package.py
This commit adds a new package: erfa (Essential Routines for Fundamental Astronomy) which has been built succesffully against gcc@5.4.0 on CentOS 7.
=> erfa: a new package.

var/spack/repos/builtin/packages/util-linux/package.py
Adding pkgconfig as a dependence fixes #7632. This also removes the need to manually specify python via PKG_CONFIG_PATH
=> build fixes for util-linux

var/spack/repos/builtin/packages/libelf/package.py
Libelf is no longer maintained and the original mr511.de web site no
longer exists.  The final release, 0.8.13 from Nov 2009 is still
archived at fossies.org.
Fixes #10757.
----------
The libelf homepage (www.mr511.de) no longer exists, but I was unable
to find a satisfactory replacement.
=> libelf: move url to fossies.org

lib/spack/docs/getting_started.rst
Closes #10346 
Still trying to think of a way to get a better error message when the `make` executable is not found. Perhaps we can add a `required=True` flag to `Executable`? Should `Executable` always call `which`?
@grahamlopez
=> Make is a required dependency of Spack

var/spack/repos/builtin/packages/omega-h/package.py
=> omega-h: update gcc conflict - as the issue is fixed in gcc-8.3.1

var/spack/repos/builtin/packages/netcdf/package.py
Without the change in this PR, NetCDF will always depend on a `+mpi` variant of hdf5.  The best I can determine is that the simple specification of `depends_on('hdf5@1.8.9:+hl')` will always select the `+mpi` hdf5 variant whether `+mpi` or `~mpi` were specified for NetCDF:
```
ews00321:spack(develop)> spack spec netcdf+mpi
Input spec
netcdf+mpi
Concretized
netcdf@4.6.3%gcc@7.2.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-rhel7-x86_64 
^hdf5@1.10.5%gcc@7.2.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-rhel7-x86_64 
^openmpi@3.1.3%gcc@7.2.0~cuda+cxx_exceptions fabrics=auto ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt …
```
=> netcdf: Eliminate spurious dependence on hdf5+mpi

var/spack/repos/builtin/packages/dysco/package.py
This PR adds a new package: dysco. It has been built succesfully against gcc@5.4.0 on Cent OS 7.
=> Dysco: a new package.

var/spack/repos/builtin/packages/vtkm/package.py
Since there is no real mpi based functionality currently in VTK-m,
mpi is off by default. Otherwise building the spack package inside of
a TravisCI ubuntu docker container fails with compile errors in DIY.
=> vtk-m: Turn of mpi by default

var/spack/repos/builtin/packages/eigen/package.py
Eigen installs its headers in [`<install_prefix>/include/eigen3`](https://bitbucket.org/eigen/eigen/src/4f9e93b66572c3a52c23d5f463aa3aa28bca6d58/CMakeLists.txt?at=default&fileviewer=file-view-default#CMakeLists.txt-422), and the users are encouraged to include them as:
```cpp
#include <Eigen/Core>
#include <Eigen/Dense>
```
However, the current `package.py` doesn't reflect the custom path so the users have to include the headers as:
```cpp
#include <eigen3/Eigen/Core>
#include <eigen3/Eigen/Dense>
```
Otherwise, it fails to find the header.
This PR fixes it following [this guide](https://spack.readthedocs.io/en/latest/module_file_support.html#override-api-calls-in-package-py).
=> Fix Eigen include path

var/spack/repos/builtin/packages/thrust/package.py
Hi,
These added versions should be the ones that have been released with CUDA these past few years, and have recently been added to the official thrust [repository](https://github.com/thrust/thrust/releases).
=> thrust: add versions 1.9.0-1.9.4

var/spack/repos/builtin/packages/py-entrypoints/package.py, var/spack/repos/builtin/packages/py-flake8/package.py, var/spack/repos/builtin/packages/py-pycodestyle/package.py
Without these dependencies, py-flake8 does not work at all for me.
=> py-flake8: Add missing dependencies for @3.7.7

var/spack/repos/builtin/packages/trimmomatic/package.py
Trimmomatic fails with newer versions of Java.
=> trimmomatic: restrict java dependency to version 8

var/spack/repos/builtin/packages/autofact/package.py
current ncbi-blast does not contain blastall which this program requires. User has confirmed the program is working now.
=> autofact: fix dependency

.travis.yml, etc/spack/defaults/config.yaml, lib/spack/spack/compilers/__init__.py, lib/spack/spack/concretize.py, lib/spack/spack/package.py, lib/spack/spack/package_prefs.py, lib/spack/spack/schema/config.py, lib/spack/spack/test/concretize.py
This PR adds a config option that allows concretization to match to compilers that are not already available, and changes the install logic to build the compiler and add it to the configuration at install time of the package building against that compiler.
The option is controlled by the `install_missing_compilers` boolean flag in the `config.yaml` configuration file.
Currently, if no compiler `gcc@7.3.0` is available on the system, `spack install zlib%gcc@7.3.0` will raise a concretization error. With this PR and when the option is turned on, `spack install zlib%gcc@7.3.0` will build gcc and all its dependencies (with a default compiler) before building zlib against that gcc install.
=> Create option to build compilers as needed

lib/spack/llnl/util/filesystem.py
This is likely caused by #10623. Currently, only C headers are considered, causing build failures for packages depending on, e.g., netcdf-fortran and xerces-c. Additionally, the regex used to look for the include path component did not consider word boundaries, causing false matches.
=> Fix find_headers to also look for C++ headers and Fortran modules

var/spack/repos/builtin/packages/boost/package.py, var/spack/repos/builtin/packages/boost/system-non-virtual-dtor-include.patch, var/spack/repos/builtin/packages/boost/system-non-virtual-dtor-test.patch
Boost 1.69.0 has issues in a relatively low level header that cause compile warnings when a particular non-bundled warning (`-Wnon-virtual-dtor`) is activated. This can cause problems for downstream code that uses `-Werror`. This PR applies a pair of patches comprising the fixes for this issue that have already been applied to the `develop` branch of the relevant Boost package (`system`) and will be released with 1.70.0.
=> boost: patch for problem with warnings for 1.69.0.

var/spack/repos/builtin/packages/intel-tbb/gcc_generic-pedantic-2019.patch, var/spack/repos/builtin/packages/intel-tbb/gcc_generic-pedantic-4.4.patch, var/spack/repos/builtin/packages/intel-tbb/package.py
In addition to adding checksums for recent versions of Intel Threading Building Blocks, we also add a pair of patches to resolve pedantic warnings in versions `2017:2019`. The patch against version `2019` has been submitted upstream as https://github.com/01org/tbb/pull/129.
=> intel-tbb: add 2019.{3,4} and patches for pedantic warnings.

var/spack/repos/builtin/packages/flex/package.py
It seems that this is actually a glibc problem and while 2.6.4 builds without the patch on newer versions of gcc (@8:), it still sometimes segfaults (as observed during the doxygen build).
Looks like I missed this in #10754 (sorry!).
=> flex: Apply 2.6.4 patch regardless of gcc version

var/spack/repos/builtin/packages/hdf5/package.py, var/spack/repos/builtin/packages/netcdf/package.py
NetCDF 4.6.3 announcement:
https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2019/msg00020.html
HDF5 1.10.5 announcement:
https://www.hdfgroup.org/2019/02/hdf5-1-10-5-release-newsletter-168/
=> Update hdf5 to 1.10.5, netcdf to 4.6.3

var/spack/repos/builtin/packages/cgns/package.py
Added the newly released cgns-3.4.0 version which adds some performance and bug fixes.
Updated the checksums to use `sha256` as that seems to be the current default chosen by spack.  Verfied that the previous checksums are still the same as shown in the pre-patched package.
Updated the `hdf5` dependency to explicitly ask for `hdf5~mpi` if the `~mpi` variant is selected and `hdf5+mpi` if `+mpi` variant is selected.  Without this change, the `~mpi` variant would select the `hdf5` dependency which would incorrectly add `+mpi` to hdf5 and we would get a dependency on mpi when it should not exist.  The `spack spec cgns~mpi` output is shown below for prior to the patch showing the dependency on mpi and following the patch showing the correct dependencies.
```
ews00321:spack(develop)> spack spec …
```
=> cgns: new version and updated hdf5 dependency

var/spack/repos/builtin/packages/openmpi/package.py
`shmemrun` and `oshrun` do not exist in OpenMPI v4.0.0
(ref: https://www.open-mpi.org/doc/v4.0/)
Simply calling `os.remove` on them will cause Spack install error:
```
$ spack install openmpi@4.0.0+pmi schedulers=slurm
...
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: OSError: [Errno 2] No such file or directory: '/shared/spack/opt/spack/linux-centos7-x86_64/intel-19.0.1.144/openmpi-4.0.0-mbndkoanvn5tknggr35g7omsrgkajnj5/bin/shmemrun'
/shared/spack/var/spack/repos/builtin/packages/openmpi/package.py:483, in delete_mpirun_mpiexec:
480        if '@1.6: ~legacylaunchers schedulers=slurm' in self.spec:
481            os.remove(self.prefix.bin.mpirun)
482            os.remove(self.prefix.bin.mpiexec)
>> …
```
=> Fix OpenMPI v4.0.0 + Slurm installation error

var/spack/repos/builtin/packages/elfutils/package.py
Presumably this was missed because a system m4 is usually findable.
=> Elfutils requires m4 to build.

etc/spack/defaults/packages.yaml, var/spack/repos/builtin/packages/ibm-java/package.py, var/spack/repos/builtin/packages/jdk/package.py, var/spack/repos/builtin/packages/openjdk/package.py
This is a binary package of the IBM Java SDK for big and little-endian
powerpc (power7, 8 and 9).  The jdk and openjdk packages only install
on x86_64.
=> ibm-java: new package

var/spack/repos/builtin/packages/parallel/package.py
added checksum for 20190222 release of gnu parallel
Tested build & install on CentOS7 with gcc8.2
=> parallel: new version

var/spack/repos/builtin/packages/regcm/package.py
The configure of RegCM treats --disable-FEATURE as --enable-FEATURE,
so we cannot use enable_or_disable.
I'd also like to fix issue #10163; I tried specifying: `depends_on('mpi', type=('build', 'link', 'run'))`
but the openmpi bin wasn't added to the PATH in the module created; the following is the line with PATH from the module:
`prepend-path PATH /.../intel/18.0.3/regcm/4.7.1-SVN6916-cosiybixa6r2korik6vaajsq4xfxhjmv/bin`.
Shouldn't `'run'` include the dependency in the PATH? Is it a bug?
https://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=run#dependency-types
=> Revert to manual flag enabling, due to RegCM bug in configure.

var/spack/repos/builtin/packages/openpmd-api/package.py
Add a variant to control shared/static builds (one at a time) and make shared the default.
=> openPMD-api: shared variant

var/spack/repos/builtin/packages/pcre/package.py, var/spack/repos/builtin/packages/pcre2/package.py, var/spack/repos/builtin/packages/qt/package.py
qt currently falls back to bundled versions of sqlite, harfbuzz, pcre, double-conversion and xcb. This adds the appropriate dependencies and configure arguments. A new variant adds multibyte support to pcre and pcre2, which is required by qt.
Additionally, newer versions of gcc (starting with @8.3.0) cause build failures. This adds a patch to fix the problem.
The changes have been tested with all versions of qt currently available in Spack. 5.2 and 5.3 do not build for reasons that seem to be unrelated to these changes, though.
=> qt: Use more system dependencies and fix build with new gcc versions

var/spack/repos/builtin/packages/rapidjson/0001-turn-off-Werror.patch, var/spack/repos/builtin/packages/rapidjson/package.py
rapidjson gives warnings with gcc-7.3 and branch fall through
I admire the developers commitment to warning-free code, but spack cannot build this package in its present state with gcc7.
rapidjson addressed this in its git repository through gcc-specific pragmas.  For the sake of spack, however, I thought it was sufficient to just not use Werror.
=> rapidjson: "Werror" too strict for recent compilers

lib/spack/spack/util/web.py
When executing `spack create` with an archive URL spack will sometimes miss versions passed on the command line:
```
$ spack create -n r-abn 'https://cran.r-project.org/src/contrib/abn_1.3.tar.gz'
==> Using specified package name: 'r-abn'
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Found 11 versions of r-abn:
1.2    https://cran.r-project.org/src/contrib/Archive/abn/abn_1.2.tar.gz
1.0.2  https://cran.r-project.org/src/contrib/Archive/abn/abn_1.0.2.tar.gz
1.0    https://cran.r-project.org/src/contrib/Archive/abn/abn_1.0.tar.gz
0.86   https://cran.r-project.org/src/contrib/Archive/abn/abn_0.86.tar …
```
=> Expand link search in find_versions_of_archive

var/spack/repos/builtin/packages/py-pytables/package.py
Also fixes setuptools import error at software runtime.
=> py-pytables: Add hdf5 1.10.x support for versions above 3.4.0

lib/spack/spack/cmd/setup.py
`string.find` is not part of Python 3 anymore.
This pull-request allows one to use `spack setup ...` also with Python 3.
=> Do not use `string` module to be compatible with python 3 (#248)

var/spack/repos/builtin/packages/mpich/package.py
mpich@3.3 introduced a new regex-based function for node list parsing that does not recognize hostnames without a dash properly.
=> mpich: Add patch to fix node list parsing

var/spack/repos/builtin/packages/qmcpack/package.py
Two bug fixes:
- Throw InstallError if more than one value of cuda_arch is specified
- Fix detection of default ('none') cuda_arch value provided.
=> QMCPACK More CUDA Fixes

lib/spack/spack/util/editor.py
If the user has set the environment variable `VISUAL`, it will be used in preference to `EDITOR` for all Spack editing activities. If `VISUAL` is not set or fails (perhaps due to a lack of graphical editing capabilities),`EDITOR` will be used instead. We fall back to one of several common editors if neither bears fruit.
This feature has been tailored to:
* Provide identical behavior to the previous implementation in the case that `VISUAL` is not set.
* Not require any change to code utilizing the editor feature.
* Follow usual UNIX behavior concerning `VISUAL` and `EDITOR`.
=> Support VISUAL environment variable per usual UNIX idiom

var/spack/repos/builtin/packages/mysql/package.py
Builds and passes all unit tests on macOS 10.14.3 with Clang 10.0.0.
I still need to test this on Cray.
=> Add latest version and missing dependencies of MySQL

var/spack/repos/builtin/packages/hpcviewer/package.py, var/spack/repos/builtin/packages/ibm-java/package.py
Add binary package for hpcviewer and hpctraceviewer for the Rice
hpctoolkit on Linux x86_64, ppc64 and ppc64le.
----------
I may be pushing the boundaries of flake with the long sha256 strings.
But folding them to the next line is ugly.  So, we'll see how the
judge rules.
Also, hpcviewer depends on java, but the tcl module that spack
created for hpcviewer doesn't depend on java.  I was expecting that
`module load hpcviewer` would also load jdk as a dependency, but it
didn't.
The module file sets `PATH` and `CMAKE_PREFIX_PATH` and prints a help
string.  Nothing else, no mention of java.
Did I miss something, or do tcl modules just not support dependencies?
=> hpcviewer: new package

var/spack/repos/builtin/packages/redis/package.py
Added versions from 4.0.11 to 5.0.3
closes #9180 
As I was not sure I could modify myself the license in #9180 here's a new PR for redis
=> redis: new package

var/spack/repos/builtin/packages/bowtie2/package.py
`spack install` tested on CentOS 7 with gcc 8.2.0
=> bowtie2: new release checksum

var/spack/repos/builtin/packages/abinit/package.py, var/spack/repos/builtin/packages/gromacs/package.py
If for some reason there's a cuda toolkit installed by other means,
(i.e. not by spack) cmake will still try to build with cuda support,
even though 'cuda=False' is the default of the spec.
=> gromacs: make sure cuda support is disabled when cuda=False

var/spack/repos/builtin/packages/gmsh/package.py
This updates gmsh to its latest version.
I also added a variant to enable OpenMP support.
Metis seems to build fine and is required for compiling the Hxt internal lib, so the choice is left to the user.
=> Update GMSH to 4.2.2 with OpenMP variant

lib/spack/spack/util/environment.py
Patch extracted from #7536 courtesy of @mgsternberg
CC: @alalazo 
This was preventing an Intel 2019 battle (lmod), but the `continue` statement fixed my issues :slightly_smiling_face:
I can't tell what the status of the other PR is, but I think it would be a good idea to get this in since it seems to affect all module systems (?)
=> prevent UnboundLocalError when sourcing files

var/spack/repos/builtin/packages/openfoam-com/package.py
openfoam-com needs flex's FlexLexer.h, which can only be found if flex is also a link dependency.
Should also fix #7439.
=> openfoam-com: Fix flex dependency

var/spack/repos/builtin/packages/ninja/package.py
Locally when I remove `preferred=True` (instead of moving it to 1.9.0) it will default to 1.9.0.  Is this behavior we can rely on or should I add `preferred=True` to the 1.9.0 version?
=> add ninja v1.9.0

var/spack/repos/builtin/packages/conduit/package.py
Added a variant to allow conduit to build with newer versions of
HDF5.  Set the default for the variant to prefer compatibility mode
with HDF5 v1.8 per Cyrus Harrison's request.
=> Add variant to Conduit package

var/spack/repos/builtin/packages/llvm/package.py
Adds a new variant to llvm: `cuda`, which if disabled (default), will set additional CMake variables so as to explicitly disable CUDA features from the llvm build.
These changes address an issue where a local cuda install outside of spack can leak into and break the build.  The variant doesn't add any dependencies on the `cuda` package, but perhaps it should?  Open to suggestions.
=> disable CUDA in llvm

var/spack/repos/builtin/packages/elmer-fem/package.py
This new package contains instructions on building [Elmer FEM solver](https://www.csc.fi/web/elmer).
It builds Elmer, ElmerICE and contributed solvers with MPI support.
Variants include:
- `+hypre` - For Hypre support (default: off).
- `+lua` - For Lua support  (default: off).
- `+mumps` - For MUMPS support  (default: off).
- `+openmp` - For OpenMP support  (default: on).
- `+trilinos` - For Trilinos support  (default: off).
- `+zoltan` - For Zoltan support  (default: off).
=> elmer-fem: New package for Elmer finite element method solver.

var/spack/repos/builtin/packages/postgresql/package.py
We add new variants to handle readline vs libedit, a client-only build and install, and bindings to TCL, Python and Perl. We also add new versions and the ability to detect remote versions not otherwise dealt with.
closes #7728
=> postgresql: new variants and versions.

var/spack/repos/builtin/packages/py-netcdf4/package.py
When installing py-netcdf4, I end up having the library linked against the system installed versions, not those Spack specifically installed as dependencies. These environment variables are set as described in http://unidata.github.io/netcdf4-python.
=> Explicitly set py-netcdf4 dependency locations

var/spack/repos/builtin/packages/ninja-fortran/package.py
Adding newer versions updates the base url and invalidates the previous
versions' urls
=> add newer versions of ninja-fortran

etc/spack/defaults/packages.yaml, var/spack/repos/builtin/packages/mysql/fix-no-server-5.5.patch, var/spack/repos/builtin/packages/mysql/package.py
Support client-only builds where feasible.
Support many more versions.
Add cxxstd variant and handle combinatorics in Boost dependency.
Integrate with virtual package mysql-client provided by PR #7729.
=> mysql: Support client-only, cxxstd and more versions.

var/spack/repos/builtin/packages/nix/package.py
Manual page https://github.com/NixOS/nix/blob/ffeabf8390f69d6bb002c2a4e17eef186ecaa32d/doc/manual/installation/prerequisites-source.xml and [previous versions](https://github.com/NixOS/nix/commits/ffeabf8390f69d6bb002c2a4e17eef186ecaa32d/doc/manual/installation/prerequisites-source.xml) thereof.
Requires PR #10910.
=> nix: improve dependencies based on prerequisites from manual.

lib/spack/spack/util/executable.py
This allows shell commands for `spack edit` to be executed correctly if
they have quoted arguments. Example:
```sh
mvim -f -c "au VimLeave \* !open -a iTerm"
```
would fail because the quoted argument is being incorrectly split:
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 13 2018 14:30:39)
Unknown option argument: "-a"
More info with: "vim -h"
==> Error: Command exited with status 1:
'mvim' '-f' '-c' '"au' 'VimLeave' '\*' '!open' '-a' 'iTerm"' '/rnsdhpc/code/spack/var/spack/repos/builtin/packages/qt/package.py'
```
=> Use 'shlex' to split Executable arguments

lib/spack/spack/platforms/cray.py
Prevents infinite recursion caused by sourcing setup-env.sh in bashrc on Cray machines. Works fine on my system. Let me know if it works well on yours.
=> Replace previous bash command to new one

var/spack/repos/builtin/packages/random123/ibmxl.patch, var/spack/repos/builtin/packages/random123/package.py
* Newer versions of IBM XL no longer define `__xlC__`, but define `__ibmxl__` instead.  This one-line patch fixes this problem in Random123.
* This patch was also provided to the Random123 maintiners (Random123@DEShawResearch.com). I don't expect a new release from them for a while, so I believe that this patch is the correct path forward (for now).
* I have chosen to always patch the source code, even when the spack compiler is not _xlc_.  This choice was made because Random123 is a header-only package that is frequently installed using a _Core_ or system default compiler (e.g. `/usr/bin/gcc`) even when the files will be consumed through include directives when other compilers are used (like _xlc_)
=> Random123 - provide a patch to fix compiles with IBM XL

lib/spack/llnl/util/lang.py, lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/test.py, lib/spack/spack/extensions.py, lib/spack/spack/schema/config.py, lib/spack/spack/tengine.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/llnl/util/lang.py
fixes #7967 
This PR gives Spack the ability to hook external commands. This is done adding a new keyword (`extensions`) to `config.yaml`, which contains a list of paths pointing to valid extensions.
A valid extension is any path in your filesystem which respect a certain naming and layout for files:
```console
$ tree spack-scripting/
spack-scripting/ # The top level directory must match the format 'spack-{extension_name}'
├── pytest.ini # Optional file if the extension ships its own tests
├── scripting # Folder that may contain modules that are needed for the extension commands
│   └── cmd # Folder containing extension commands
│       └── filter.py # A new command that will be available 
└── tests # Tests for this extension
├── conftest.py 
└── test_filter.py
└── templates # Templates …
```
=> Spack can be extended with external commands

var/spack/repos/builtin/packages/qmcpack/package.py
Now you are able to use the Intel compiler with other BLAS and LAPACK providers, no longer forced to use MKL.
=> QMCPACK Minor MKL buglet. 

var/spack/repos/builtin/packages/squashfs/package.py
This is my first contribution (thanks in advance for helping me learn the codebase so I can contribute more!) to add installation of the squashfs tools package in order to prepare for the Singularity upgrade.
- I chose 4.3 as the default, the latest version
- I didn't go earlier than 4.0 because it was like, back in 2009! :O 
- the library only requires a make and make install, so I chose `MakefilePackage` as the base class (I found the package.py file in the main source folder) and then set the prefix to the prefix variable, which I figured out was provided in the function, and the makefile expected INSTALL_DIR to be set to the prefix.
- to change directory, I found other examples `with working_dir` and that seemed to do the trick!
Let me know what needs to be changed / improved, etc., …
=> adding package to install squashfs for singularity

lib/spack/spack/compiler.py, lib/spack/spack/compilers/arm.py, lib/spack/spack/compilers/cce.py, lib/spack/spack/compilers/clang.py, lib/spack/spack/compilers/gcc.py, lib/spack/spack/compilers/intel.py, lib/spack/spack/compilers/nag.py, lib/spack/spack/compilers/pgi.py, lib/spack/spack/compilers/xl.py, lib/spack/spack/compilers/xl_r.py, lib/spack/spack/test/cmd/test_compiler_cmd.py, lib/spack/spack/test/compilers.py
There were samples of output from different compilers in the docstrings of the various `default_version` methods. This PR:
=> Added tests on compiler's version detection

var/spack/repos/builtin/packages/nalu-wind/package.py
It looks like Hypre was updated with a `superlu-dist` variant that defaults to `on` and this appears to break Nalu-Wind unless we require `hypre~superlu-dist`.
=> Setting nalu-wind to require hypre without superlu-dist

var/spack/repos/builtin/packages/netcdf-cxx/package.py
On my system netcdf-cxx will link to the system hdf5 and netcdf4 libraries, which causes issues. This change ensures the spack installed libraries are used.
=> netcdf-cxx: set ldflags for hdf5 and netcdf

lib/spack/spack/repo.py
To reproduce the issue:
```
$ cd $SPACK_ROOT/var/spack/repos
$ mkdir acme
$ <builtin/repo.yaml sed s/builting/acme/ > acme/repo.yaml
$ spack repo add acme
==> Error: No directory 'repo.yaml' found in '/tmp/spack/var/spack/repos/acme'
```
Should be _packages_ instead of _repo.yaml_
=> spack repo add: fix error message when `packages' directory is missing

var/spack/repos/builtin/packages/r-pkgload/package.py
depends on `r-pkgbuild` in #11046 and `r-desc` in #11048
=> r-pkgload: new package at 1.0.2

var/spack/repos/builtin/packages/r-hoardr/package.py
depends on newer version of `r-roxygen2` in #11045
=> r-hoardr: new package at 0.5.2

var/spack/repos/builtin/packages/openmpi/nolegacylaunchers.sh, var/spack/repos/builtin/packages/openmpi/package.py
This adds a stub script for `mpirun` and other standard executables when installing OpenMPI with slurm. The purpose is to make the removal less of a surprise to administrators/users: it explains why they were removed and how to restore them.
See discussion on https://github.com/spack/spack/pull/10340 @alalazo
=> Add stub mpirun script for openmpi~legacylaunchers+slurm

var/spack/repos/builtin/packages/trilinos/package.py
This is a new instantiation option that appears to be required for STK to give 64 bit integers to Zoltan which goes through Tpetra.
=> Adding Tpetra_INST_INT_LONG_LONG to Trilinos explicit_instantiation variant

lib/spack/spack/spec.py, lib/spack/spack/test/directory_layout.py
Fixed bug in `lib/spack/spack/spec.py` when `${NAMESPACE}` is included in directory layout.  Added test to prevent regression.
=> Bug fix in lib/spack/spack/spec.py

var/spack/repos/builtin/packages/fio/package.py
This variant will add libaio (which is already present in spack) as a dependency to fio so that fio is built with the libaio engine.
=> add libaio variant to fio

var/spack/repos/builtin/packages/xcb-util-wm/package.py
This fixes the following error at configure phase on systems where m4 is not available:
`checking for m4 that supports -I option... configure: error: could not find m4 that supports -I option`
According to [build-system-dependencies](https://spack.readthedocs.io/en/latest/build_systems/autotoolspackage.html?highlight=autotools#build-system-dependencies), build systems dependecies were added to the package.
=> xcb-util-wm: add m4 build system dependency

lib/spack/spack/test/module_parsing.py
The module_parsing test checks whether the module function is available by looking for the string 'not found'. If the user has set a different locale, the test can assume that the module function is available when it actually is not.
=> Fix module_parsing test

var/spack/repos/builtin/packages/py-basemap/package.py
The basemap package was failing to import. This is because basemap installed an __init__.py in its mpl_toolkits namespace directory. Per https://packaging.python.org/guides/packaging-namespace-packages/:
> It is extremely important that every distribution that uses the namespace package omits the __init__.py or uses a pkgutil-style __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable.
This has been reported to the basemap project as https://github.com/matplotlib/basemap/issues/456.
This PR should supercede #10590.
=> fixes py-basemap package

lib/spack/spack/database.py, lib/spack/spack/spec.py, lib/spack/spack/test/database.py, lib/spack/spack/test/spec_semantics.py
Old Spack databases have the string "None" as the path for external entries.
Change the logic in `Spec.prefix` to catch this and replace it with the `Spec.external_path` entry.
Includes regression test.
=> Fix reading externals from old database

lib/spack/spack/cmd/install.py, lib/spack/spack/reporters/cdash.py, lib/spack/spack/test/cmd/install.py
When providing a track, the cdash reporter will format the stamp
itself, as it has always done, and register the build during the
package installation process.  When providing a stamp, it should
first be formatted as cdash expects, and then cdash will be sure
to report results to same build id which was registered manually
elsewhere.
=> Allow spack install to take either cdash stamp or track

var/spack/repos/builtin/packages/netlib-scalapack/mpi2-compatibility.patch, var/spack/repos/builtin/packages/netlib-scalapack/package.py
ref: https://github.com/spack/spack/pull/11096
ref: https://github.com/Reference-ScaLAPACK/scalapack/pull/10
=> netlib-scalapack: fix compatibility with mpi2 i.e openmpi-4

var/spack/repos/builtin/packages/root/package.py
The assumption is that cmake will set the correct include flags.
=> root: unset SPACK_INCLUDE_DIRS so the compiler wrapper does not prepend any -I flags. 

var/spack/repos/builtin/packages/mumps/gfortran8.patch, var/spack/repos/builtin/packages/mumps/package.py
Add patch for gfortran-8 runtime errors
Ref: https://listes.ens-lyon.fr/sympa/arc/mumps-users/2018-11/msg00003.html
=> mumps: add version 5.1.2

lib/spack/spack/build_systems/intel.py, var/spack/repos/builtin/packages/intel-mkl/package.py, var/spack/repos/builtin/packages/intel-parallel-studio/package.py
follow up to https://github.com/spack/spack/pull/10993 , in that PR I did not notice that the base class already has `libs()`, we should have put everything there from the beginning.
=> intel: consolidate libs() in the base class

var/spack/repos/builtin/packages/perl/package.py
If system perl is being used through packages.yaml there cannot be dependent modules.
The  setup_dependent_packages function should not do anything in that case.
Addresses bug in https://github.com/spack/spack/issues/11033
=> Fix bug when system perl is used.

lib/spack/spack/platforms/cray.py
Altd and darshan were found to be causing slowdowns for builds. This makes sure to unload these modules before building.
=> Unload altd and darshan

lib/spack/llnl/util/filesystem.py, lib/spack/spack/cmd/env.py, lib/spack/spack/cmd/install.py, lib/spack/spack/environment.py, lib/spack/spack/filesystem_view.py, lib/spack/spack/schema/env.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/util/environment.py
This PR updates environments so that by default they are created with views. Currently my goal is to show how it works and get agreement on it. There are still tests etc. which are needed to complete it.
```
spack env create e1 #by default this will maintain a view in the directory Spack maintains for the env
spack env create e1 --with-view=/abs/path/to/anywhere
spack env create e1 --without-view
```
The `manifest.yaml` file now looks like:
```
spack:
specs:
- python
view: true #or false, or a string
```
Existing environments will not automatically maintain views. I propose adding the following command to manipulate whether an env maintains a view (these commands aren't yet available):
~`spack env view --enable #by default create the view`~
~`spack env view --enable …
=> Maintain a view for an environment

var/spack/repos/builtin/packages/ecp-io-sdk/package.py, var/spack/repos/builtin/packages/ecp-vis-sdk/package.py, var/spack/repos/builtin/packages/ecp-viz-sdk/package.py
This is an initial set of meta-package for the Data & Viz SDK.  Each dependency is described as a variant and should work in isolation.  As interoperability issues are addressed then numerous variants will be enabled by default.  For now though, this puts the meta-package infrastructure in place.
TODO:
- Dependencies are currently only using default variants.  Adjust to use ecp-desired variants.
- Many interoperability issues between packages, some having to do with current limitations in the concretizer
=> New Packages: ecp-io-sdk and ecp-viz-sdk

.readthedocs.yml, .travis.yml, lib/spack/docs/requirements.txt
@zzotta reported chain docs not present in our online documentation even though they were merged yesterday. I tried to have a look at our builds on readthedocs and the most recent one was from 2 months 
and 3 weeks ago. Manually triggering a build is failing:
Looking at the failed build, there's a message from the readthedocs guys that suggests to update our configuration by using a yaml file (like Travis):
This PR is an attempt to write a valid YAML file for readthedocs and update the dependencies and environment for Sphinx builds.
=> Updated Sphinx configuration

var/spack/repos/builtin/packages/py-deeptools/package.py
Tested on CentOS 7 w/ gcc 8.2.0
=> py-deeptools: adding new release 3.2.1

var/spack/repos/builtin/packages/verilator/package.py
Similar to #10956 flex needs to be a link-dependency for verilator in
order for `FlexLexer.h` to be found during install.
=> verilator: Fix FlexLexer.h not found

lib/spack/spack/package.py
This fixes the recursion so dependencies and packages with dependencies install properly using `install_missing_compilers`.
=> Bugfix: Install missing compilers doesn't work for packages with dependencies

var/spack/repos/builtin/packages/qmcpack/package.py
A Spack hack for MKL usage was needed in QMCPACK prior to version 3.5 when non-Intel compilers were used. This Spack hack could have undesirable side-effects and led to ugly code that was extra work to maintain. For older version of QMCPACK, we through a conflict if you want to use Intel MKL with the other compilers commonly found on x86.
Note that there is no impact to version of QMCPACK since 3.5.
=> Remove Spack MKL hack for older version of QMCPACK.

var/spack/repos/builtin/packages/cln/package.py
Add package for [CLN library](https://www.ginac.de/CLN/). The CLN source code is obtained from the CLN git repository. Some versions are provided in the package definition, each specified by the commit's SHA1 that corresponds to tagged releases.
Some of our applications (and maybe others as well) use this library. Having it available in `spack` eases management of external libraries, as everything can be managed via `spack`.
- `spack install cln` works on my machine.
- `spack flake8` passes on my machine.
=> New package: CLN library for arbitrary precision numerics

lib/spack/spack/environment.py
The default (implied) behavior for all environments, as of https://github.com/spack/spack/pull/10017, is that an environment will maintain a view in a location of its choosing. #10017 explicitly recorded all three possible states of maintaining a view:
1. Maintain a view, and let the environment decide where to put it (default)
2. Maintain a view, and let the user decide
3. Don't maintain a view
This PR updates the config writer so that for case [1], nothing will be written to the `config.yaml`. This will not change any existing behavior, it just serves to keep the config more compact (which ideally makes it more readable).
=> don't record 'view: True' in environment config

var/spack/repos/builtin/packages/ruby/package.py
If specifying `~openssl`, the post-install step will still try to install
the non-existent certificate, leading to an `IOError`.
=> ruby: Install certificate for +openssl only

var/spack/repos/builtin/packages/dbus/package.py, var/spack/repos/builtin/packages/harfbuzz/package.py, var/spack/repos/builtin/packages/kitty/package.py, var/spack/repos/builtin/packages/libx11/package.py, var/spack/repos/builtin/packages/libxkbcommon/package.py, var/spack/repos/builtin/packages/util-macros/package.py, var/spack/repos/builtin/packages/xkeyboard-config/package.py
Adds a package for the kitty terminal.
A few of the dependencies needed `setup_dependent_environment` implemented in order to be detected/used. For example, the `util-macros` package provides several m4 macros, which aren't discovered unless `ACLOCAL_PATH` is properly set.
One of kitty's dependencies, `libxkbcommon`, needed a few dependencies of its own added in order to compile.
=> new package: kitty terminal

var/spack/repos/builtin/packages/llvm/package.py
While trying to build the latest `llvm@8.0.0`, `cmake` dies with the following error msg:
```
>> 19    CMake Error at cmake/modules/CheckCompilerVersion.cmake:40 (message):
20      Host GCC version should be at least 5.1 because LLVM will soon use new C++                                                                              
21      features which your toolchain version doesn't support.
```
This PR adds a proper `conflict` according to the message above.
=> llvm: prevent building llvm@8: with an incompatilble gcc

lib/spack/spack/reporters/cdash.py, lib/spack/spack/test/cmd/install.py
* Make a separate CDash report for each package installed
* Don't report errors to CDash for successful packages
* Report a maximum of 50 errors/warnings to CDash
=> improvements to our CDash reporter

var/spack/repos/builtin/packages/openmpi/package.py
tarball posted 2019-04-15
https://www.open-mpi.org/software/ompi/v3.0/
```
dantopa@cn209:openmpi-3.0.4-5ienfvwpcxky3nz5jt3rygxzxzltkwm4 $ cd lib/
dantopa@cn209:lib $ ls -alh
total 27M
...
lrwxrwxrwx 1 dantopa dantopa   16 Apr 17 10:01 libmpi.so -> libmpi.so.40.0.5
```
```
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
5ienfvw    openmpi@3.0.4%gcc
bkkhvej        ^hwloc@1.11.11%gcc
5chyfxo            ^libpciaccess@0.13.5%gcc
bcnjbc3            ^libxml2@2.9.8%gcc
tt2hkol            ^numactl@2.0.12%gcc
64vg6e4        ^zlib@1.2.11%gcc
```
-- linux-rhel7-aarch64 / gcc@4.8.5 ------------------------------
```
cq2y6b3    openmpi@3.0.4%gcc
7gqvelc        ^hwloc@1.11.11%gcc
6a4he35            ^libpciaccess@0.13.5%gcc
6a5uzd6            ^libxml2@2.9.8%gcc
m5neuus …
```
=> Add Open MPI v3.0.4

var/spack/repos/builtin/packages/qmcpack/package.py
There are two separate CMake related fixes in the PR:
- cflags and cxxflags are not getting passed into CMake automatically. This causes problems when they are added either in packages.yaml or at the command line interface. A long term solution would be to add this kind of functionality into the CMake base package. However, it appears that many CMake Spack packages are already passing these flags explicitly into their own CMake.
- We need to add Intel's `ifcore` library into the link line. It is needed when linking a Fortran library, compiled by the Intel compiler, into the QMCPACK binary. This does not happen with GCC. Not sure if the responsibility should rest with the Intel compiler or QMCPACK's CMake.
=> QMCPACK CMake fix

lib/spack/spack/repo.py
fixes #11159 
This PR forbids the assignment of custom super-namespaces for `Repo` and `RepoPath`, as the only super-namespace supported by package directives is `spack.pkg`. 
It also adds a few minor maintenance changes:
=> Forbid the assignment of Repo and RepoPath super-namespace

lib/spack/docs/chain.rst
https://github.com/spack/spack/pull/11152 added documentation for https://github.com/spack/spack/pull/8772 but some details were based on an earlier implementation that had changed by the time #8772 was merged. In particular, #11152 mentioned that upstream Spack instances were configured in `config.yaml`, when in fact they should be placed in a separate `upstreams.yaml` config file; this PR updates the documentation accordingly.
=> Spack chain docs: config goes in upstreams.yaml

var/spack/repos/builtin/packages/hpx/package.py
=> hpx: overhaul of the package recipe

var/spack/repos/builtin/packages/petsc/package.py
- spec[ss_spec].libs.ld_flags results in:
--with-suitesparse-lib="-L/raid/home/sajid/packages/spack/opt/spack/linux-rhel7-x86_64/gcc-8.3.0/suite-sparse-5.3.0-vteg2xpr3uz2ppisgdrjtacwpavzydm7/lib -L/lib64 -lumfpack
-lklu -lcholmod -lbtf -lccolamd -lcolamd -lcamd -lamd -lsuitesparseconfig -lrt"
-L/lib64 from above results in system libraries getting picked-up instead of spack installed packages [in this case hdf5]
Fixed-by: "Smith, Barry F." <bsmith@mcs.anl.gov>
Reported-by: "Syed, Sajid Ali" <sajidsyed2021@u.northwestern.edu>
cc: @BarrySmith @s-sajid-ali
=> petsc: fix suitesparse configure options.

lib/spack/spack/modules/common.py
#10556 changed the format strings but maintained backwards compatibility in all cases except one.
The list of valid tokens for the module naming schemes was not updated properly to contain both the new and old styles for compilers and package names.
This PR re-adds the old tokens into the list of valid tokens.
=> Make module naming schemes backwards compatible

var/spack/repos/builtin/packages/jdk/package.py
With current `HEAD`:
```
$ spack fetch jdk
==> Fetching http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_linux-x64_bin.tar.gz
==> Warning: The contents of the archive look like HTML. Either the URL you are trying to use does not exist or you have an internet gateway issue. You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: sha256 checksum failed for ${SPACKFOLDER}/spack/var/spack/stage/jdk-11.0.2_9-eew5mfdv2z343v2z5nvb5hmcmwyi2o4j/jdk-11.0.2_linux-x64_bin.tar.gz
Expected 7b4fd8ffcf53e9ff699d964a80e4abf9706b5bdb5644a765c2b96f99e3a2cdc8 but got 80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd
```
With this PR, fetching `jdk` works as expected again.
~~This fixes …
=> jdk: Fix fetching with curl 7.64.0+

var/spack/repos/builtin/packages/mysql/package.py
MySQL 5.7.X and Boost 1.59.0 have a closer relationship than MySQL >= 8.0 and their corresponding Boost versions.
=> mysql: fix #11226.

lib/spack/spack/util/web.py
PR #10758 made a slight change to find_versions_of_archive() which included
archive_url in the search process. While this fixed `spack create` and
`spack checksum` missing command-line arguments, it caused `spack
install` to prefer those URLs over those it found in the scrape process.
As a result, the package url was treated as a list_url causing all R
packages to stop fetching once the package was updated on CRAN.
This patch is more selective about including the archive_url in the
remote versions, explicitly overriding it with matching versions found
by the scraper.
=> Fix outdated R packages failing to fetch

lib/spack/spack/compilers/pgi.py, lib/spack/spack/test/compilers.py
Fixes #10599 
@anderbubble Can you test this? I want to make sure:
1. It does detect the LLVM-enabled compilers
2. It doesn't add 2 copies of the compiler, one with and one without `-llvm`
Also, can you confirm that all of the flags are the same as for PGI, not LLVM?
=> Fix detection of LLVM-enabled PGI compilers

var/spack/repos/builtin/packages/openblas/package.py
Allow specifying whether AVX2 or AVX512 should be enabled or disabled
on x86 targets.
As AVX2 hardware and toolchain support is quite ubiquitous by now,
AVX2 is enabled by default.  Also AVX2 support is not disabled when
building the +virtual_machine variant.
AVX512 is not supported in older but still supported toolchains,
hardware is still expensive, and OpenBLAS AVX512 kernels still have
bugs. Thus AVX512 is disabled by default.
=> OpenBLAS: Allow enabling/disabling AVX2/512 support

lib/spack/spack/test/util/editor.py, lib/spack/spack/util/editor.py, lib/spack/spack/util/executable.py
TL; DR: `spack edit` could be weird because it relied on `Popen` (via `Executable`), not `execv`
The problem:
- `spack edit` previously used `spack.util.executable` `Executable` objects, and didn't `exec` the editor.
- This meant that Spack was still running while your editor was, and it could lead to weird behavior
- e.g. on Mac OS the builtin `emacs` will quit with "Keyboard interrupt" when you type `Ctrl-g` -- this is obviously not what we want
The fix:
This slightly changes the behavior from #10898 (@chissg -- take a look).
Before, if you launched the editor and it exited 1, you'd try the next editor.  Now we'll only do that if there is a problem with `execv`.  I think that is fine, because you could launch `$VISUAL`, do edits, and `exit 1` for perfectly normal reasons, and then you …
=> spack edit: use execv instead of Executable

lib/spack/spack/environment.py
We want to do a point release of `v0.12` that includes views in environments, so that we can add an example of this feature to the environments tutorial.
=> Backport Environment managed views onto v0.12

lib/spack/docs/tutorial.rst
- Add link to container image, as well as a description of VMs
- Update slide link to point to latest RIKEN tutorial
=> Update tutorial page with RIKEN tutorial slides.

var/spack/repos/builtin/packages/squashfs/package.py
The squashfs Makefile's `INSTALL_DIR` args is the path to the `bin` directory, not the top of the install tree.
Adjust accordingly.
FYI: @vsoch
=> Install squashfs exe's into prefix.bin, not prefix

var/spack/repos/builtin/packages/ftgl/ftgl-2.1.3-rc5-ldflags.patch, var/spack/repos/builtin/packages/ftgl/package.py
This updates to the last release (from 2008) with patches required to work with Spack and Root.
These changes were implemented by @gartung on https://github.com/FNALssi/spack and abstracted for upstream by @chissg.
=> ftgl: update to 2.1.3-rc5.

var/spack/repos/builtin/packages/squashfs/package.py
On my CentOS system it was getting linked in (from Spack, no less)
fortuitously.
On a minimal Ubuntu system it failed until it was added as an explicit
dependency.
=> squashfs should depend_on('zlib')

var/spack/repos/builtin/packages/root/find-mysql.patch, var/spack/repos/builtin/packages/root/format-stringbuf-size.patch, var/spack/repos/builtin/packages/root/honor-unuran-switch.patch, var/spack/repos/builtin/packages/root/package.py, var/spack/repos/builtin/packages/root/root7-webgui.patch
This assorted improvement brings upstream `root` recipe into line with FNAL's use.
* Support MySQL.
* Patches:
* Bigger stringbuf.
* Find MySQL even when it's called `mariadb-c-client`.
* Honor external provision of `unuran`.
* Properly handle the ROOT7 web GUI for 6.16/00.
* `memstat` variant is now default-OFF due to version-related constraints.
* Add missing dependencies.
* Propagate `python` to `libxml2`.
* Handle external FTGL dependency with X / OpenGL: depends on #11214.
* Add `force=True` to `SPACK_INCLUDE_DIRS` to avoid Spack warning.
* New `gminimal` variant default ON per discussion with HSF Packaging Group.
=> root: new versions, variants and patches

var/spack/repos/builtin/packages/precice/package.py
This PR adds hotfix 1.4.1 of the preCICE library.
=> precice: add version 1.4.1

var/spack/repos/builtin/packages/environment-modules/package.py
New bugfix version in the v4.2 series.
Release notes: https://modules.readthedocs.io/en/latest/NEWS.html#modules-4-2-4-2019-04-26
=> environment-modules: add version 4.2.4

var/spack/repos/builtin/packages/vtk/package.py
VTK requires a patched libharu that is not maintained upstream
See https://github.com/libharu/libharu/pull/157
=> vtk: Use the vendored libharu

.travis.yml, lib/spack/spack/cmd/flake8.py
- We were previously hardcoding the branch that `spack flake8` bases its changes on to `develop`
- Now it will use `$TRAVIS_BRANCH` as the base instead of `develop`
- This is needed for cases where `develop` is not the PR target.
=> Fix spack flake8 to use Travis's target as base when needed

var/spack/repos/builtin/packages/openfoam-com/package.py
Kahip does not build with clang (`conflicts('%clang')` in kahip package.
Because of this, openfoam-com %clang fails concretization.
In light of this, consider changing default openfoam-com variant for kahip to False.
=> Change openfoam-com kahip variant to default False

var/spack/repos/builtin/packages/lua/package.py
The current lua package.py does not link with libdl.so, so you get unresolved symbols while linking with lua. This PR fixes this issue
=> Lua: Fix unresolved symbols in shared library by linking with libdl.so

var/spack/repos/builtin/packages/argobots/package.py, var/spack/repos/builtin/packages/margo/package.py
margo package is a required dependency for unifycr but the package
was not available in spack. margo requires a recent version of argobots
that has the ABT_SCHED_BASIC_WAIT scheduler (rc1 does while previously
available versions of this package in spack did not have it).
=> Add margo package and add rc1 tag for argobots package

var/spack/repos/builtin/packages/libxsmm/package.py
Added LIBXSMM v1.11, updated package description, removed incorrect/hacky edit phase. For the latter, spack_cc, spack_cxx, and spack_fc were never passed correctly (neither as build key nor per environment).
=> LIBXSMM 1.11

lib/spack/spack/environment.py
When trying to use a spack environment in a singularity container, I came across the following:
```
+ spack -e canu add canu@1.8
File "/opt/spack/bin/spack", line 48, in <module>
File "/opt/spack/lib/spack/spack/main.py", line 633, in main
ev.activate(env, args.use_env_repo)
File "/opt/spack/lib/spack/spack/environment.py", line 128, in activate
if 'color' in os.environ['TERM'] and prompt:
File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
raise KeyError(key)
KeyError: 'TERM'
ABORT: Aborting with RETVAL=255
```
This patch corrects the issue
=> fix error when adding package to env in container

share/spack/docker/Dockerfile
Also adds hooks to environment setup scripts.  Instead of symlinking `handle-xyz.sh` to `$SPACK_ROOT`, it is sourced.  If the file is not found (e.g.: due to a different version of spack being mounted to `$SPACK_ROOT`), then a static version of the setup files are evaluated inline.
Also adds a `spack spec` command near the end so that prebuilt caches are included in the resulting images.
=> install spack under /opt/spack in docker images

lib/spack/docs/packaging_guide.rst, lib/spack/spack/test/concretize_preferences.py, lib/spack/spack/test/versions.py, lib/spack/spack/version.py, var/spack/repos/builtin.mock/packages/develop-test2/package.py, var/spack/repos/builtin.mock/packages/preferred-test/package.py
as per @adamjstewart request, an alternative to https://github.com/LLNL/spack/pull/1979 which defines a list of infinity-like versions.
@adamjstewart : how do I use that `__gt__` operator in places like
```
for a, b in zip(self.version, other.version)
return a < b
```
?
Closes #1975, Closes #8421
=> extend Version class so that 2.0 > 1.develop > 1.1 and develop > master > head > trunk > 9999

var/spack/repos/builtin/packages/llvm/package.py
Based on the LLVM documentation [1], Python is used to run the automated
test suite. Therefore is it always a dependency for LLVM. However, if
build without Python (~python), we limit it to a build time dependency.
Note that py-lit is not added as a spack dependency even though it is
available as a spack package. This is because it is already included
in llvm and llvm is difficult to configure using an external py-lit
(several CMake variables to set correctly). Additionally, having
py-lit as a spack dependency adds Python as a runtime dependency
for llvm even though it is not required at runtime.
[1] https://llvm.org/docs/GettingStarted.html#requirements
Replaces accidentally closed and deleted #10986
=> llvm: depend on python only when +python

var/spack/repos/builtin/packages/bmi/package.py, var/spack/repos/builtin/packages/mercury/package.py
- also enable optional dependency in Mercury
BMI is helpful as an alternative to libfabric for debugging and TCP oriented deployments.
=> add BMI package

lib/spack/spack/concretize.py, lib/spack/spack/repo.py, lib/spack/spack/test/concretize.py, share/spack/templates/misc/coconcretization.pyt
Refers to #9902
Refers to #11095
This PR adds a function that concretizes specs together or fails trying to do so.
In many contexts (e.g. when using Spack environments to develop software or sometimes when deploying applications in a container) there could be the need to concretize specs together - meaning there will be a single configuration for each package in the DAG. This PR adds a function that permits to do just that:
```python
import spack.concretize
concrete_specs = spack.concretize.concretize_specs_together('hdf5+mpi', 'zlib@1.2.8', 'mpich')
```
The function comes with unit tests and can be used later to solve issues like #9902
The implementation of this functionality relies on the current state of the concretizer and repository modules in Spack. This involves:
1. Creating a …
=> Added a function that concretizes specs together

var/spack/repos/builtin/packages/libunistring/package.py, var/spack/repos/builtin/packages/libunistring/removed_libio.patch
glibc 2.28+ removed libio.h where `_IO_ftrylockfile` was defined, thus causing the build to fail in `./lib/fseterr.c`. I added a patch to check for `IO_EOF_SEEN` as well like libunistring does since version 0.9.10.
=> libunistring: added newer versions and fixed older ones

var/spack/repos/builtin/packages/blast-plus/package.py
Updating blast-plus checksum to include 2.9.0 and 2.8.1.
Builds tested on CentOS 7 w/ gcc 8.2.0
=> blast-plus: new versions

var/spack/repos/builtin/packages/gmtsar/package.py
GMTSAR is an open source (GNU General Public License) InSAR processing system designed for users familiar with Generic Mapping Tools (GMT).
=> newpackage: GMTSAR

var/spack/repos/builtin/packages/curl/package.py
This option allows curl and its dependents (git, ...) to work with proxy using Kerberos authentification.
=> Add gssapi option for curl.

var/spack/repos/builtin/packages/py-yt/package.py
- Update yt versions to `3.5.1`.
- Add the `develop-4.0` version which is the next major release in development. Although still in development, it's already used by many people in production including me for its major improvements in supporting SPH datasets.
=> py-yt: update versions

var/spack/repos/builtin/packages/omega-h/package.py
An omega-h hello world driver builds and runs successfully on our RHEL7 systems using the v9.27.0 spack build of omega-h.
=> omega-h: add version 9.27.0

var/spack/repos/builtin/packages/faodel/array.patch, var/spack/repos/builtin/packages/faodel/faodel_mpi.patch, var/spack/repos/builtin/packages/faodel/faodel_sbl.patch, var/spack/repos/builtin/packages/faodel/package.py
FAODEL (Flexible, Asynchronous, Object Data-Exchange Libraries) is a collection
of software libraries that are used to implement different data management
services on high-performance computing (HPC) platforms. This project is part of
the Advanced Technology Development and Mitigation (ATDM) effort for NNSA's ASC
program at Sandia National Laboratories.
This PR replaces spack#11268.
@chuckatkins @fbudin69500 @craigulmer Please review.
=> FAODEL: Add FAODEL package to spack

var/spack/repos/builtin/packages/slate/package.py
The package was referencing a missing variant that had not been implemented.  These references were removed.
=> Fixed slate package errors

var/spack/repos/builtin/packages/mesa/glproto-mr806.patch, var/spack/repos/builtin/packages/mesa/package.py
This should be ready to go, see conversation for details.
---
ToDo:
---
The mesa package refers to `GL/glproto.h`.  On systems that don't have the OS packages installed, this leads to failures during the build [e.g. this comment in 01482](https://github.com/spack/spack/pull/10482#issuecomment-488786745).
This fixes it.  Tested on a minimally provisioned CentOS 7.
@opadron, can you check it on your systems (I'm using the same base system that @odoublewen is, but I'm sure he'll test it too...).
=> Mesa should depend_on('glproto')

var/spack/repos/builtin/packages/ccfits/package.py
This PR include the CCfits package (Version 2.5 and 2.4).
=> Added CCfits package

lib/spack/spack/test/environment_modifications.py, lib/spack/spack/test/util/environment.py, lib/spack/spack/util/environment.py
New functions `deprioritize_system_paths()` and `prune_duplicate_paths()` have been added to `util/environment.py` with tests, and functionality to use them from `EnvironmentModifications` has been added, along with tests. In addition, all functions in `util/environment.py` have tests in `test/util/environment.py` and one now-redundant test in `test/environment.py` has been removed in favor of an equivalent test in the more appropriate `test/util/environment.py`.
The new functions are particularly useful in recipes using `PATH`-like variables where entries in `packages.yaml` might cause issues by putting (_e.g._) `/usr/include` ahead of paths from specific spack-installed packages.
`deprioritize_system_paths(name)` will move identified system paths to the end of the `name` `PATH`-like …
=> New environment manipulation functions for system path deprioritization and duplicate removal.

var/spack/repos/builtin/packages/llvm/package.py
The default install for llvm should just be the common typical case, i.e.
support for local host and cpu architectures.  Enabling support for the wide
array of auxiliary architectures should be explicit rather than implicit.
Note that this is merely a bandaid.  I have the intention later to make the targets a multi-valued variant, but there's no particular timeline on that.
=> llvm: Adjust default supported targets

lib/spack/spack/util/environment.py
- Escape environment values that contain unusual characters (newlines
in functions or quotes in other variables would cause failures)
- Comment out environment variables that would cause undesirable changes
(don't arbitrarily reset PWD and OLD_PWD when sourcing, as well as other
session-specific IDs)
=> Allow spack-build.env file to be safely `source`d

var/spack/repos/builtin/packages/random123/arm-gcc.patch, var/spack/repos/builtin/packages/random123/package.py
+ The additional patch enables a non-optimized random123 code path that will work on ARM architectures. This solution is provided only for version 1.09 to allow the most current version of Random123 to function.
+ A more complete, long term solution will be the addition of a native ARM intrinsics-based implementation of random123.  This solution is being worked on but it is several weeks or months away.  Once the full implementation is available it will be provided to the author/maintainer of Random123.
=> Random123: Provide a patch to allow preliminary support for ARM platforms

CODE_OF_CONDUCT.md
- Code of conduct was still copy-pasted from the Contributor Covenant.
- Updated to use more specific language to the Spack community
=> Make CODE_OF_CONDUCT.md more Spack-specific

var/spack/repos/builtin/packages/papi/package.py
This also fixes the GCC patch to be applied for versions 8 and up.
=> papi: Add 5.7.0

var/spack/repos/builtin/packages/netcdf/package.py
For 4.7.0, configure fails if curl is not installed.
=> netcdf: Fix build if curl is not installed

var/spack/repos/builtin/packages/nco/package.py
Earlier versions do not compile with gcc@9.
=> nco: Add 4.7.9

var/spack/repos/builtin/packages/dyninst/package.py
Starting with the upcoming 10.1 release, Dyninst changed the names of
some cmake args to camel case: LIBELF_* to LibElf_* and LIBDWARF_* to
LibDwarf_*.  This change is needed now for @develop and will be used
for 10.1 when it is released.
Also, Dyninst now requires cmake version 3.4.0 or later.
Fold in the change from PR #11222 for Boost version 1.69.  It's a
1-line change and is needed to build Dyninst now (all versions).
----------
ping @hainest to check the arg names and if there will be anything
else for 10.1.
ping @sknigh for the boost version.
=> dyninst: update cmake args for develop and upcoming 10.1 release

lib/spack/spack/cmd/license.py, lib/spack/spack/test/cmd/license.py, var/spack/repos/builtin/packages/aom/package.py, var/spack/repos/builtin/packages/simgrid/package.py
Previous license checks have allowed for significant deviation in the license header as long as a few parts of the license matched the general format.
This updates the license check to require almost an exact match, ignoring leading/trailing whitespace, or leading `#`/`.` characters (to account for python/bash and rst files).
The check is updated to print a debug message if a date mismatch is detected (e.g. if the copyright ends in 2018 vs. 2019 at this point). A mismatch on the upper end of the date range is not considered an error (so long as it falls within `[2017, 2029]`).
As an example of how much stricter this is, `Copyright 2018 Lawrence...` from the `simgrid` package was considered a mismatch, and had to be updated to `Copyright 2013-2019 Lawrence`. This could be relaxed to allow …
=> Force exact license match

.travis.yml, lib/spack/spack/operating_systems/cnl.py, lib/spack/spack/operating_systems/cray_frontend.py, lib/spack/spack/platforms/cray.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/flag_handlers.py, lib/spack/spack/test/module_parsing.py, lib/spack/spack/util/module_cmd.py
Fixes #6451.
Fixes #7884.
Fixes #8193.
Update Spack core to use new `module` function instead of `get_module_cmd`
Previously, Spack relied on either examining the bash `module()` function or using the `which` command to find the underlying executable for modules.
As @mgsternberg commented in detail on #6451, more complicated module systems do not allow for the sort of simple analysis we were doing.
This PR uses the `module` function directly and copies environment changes from the resulting subprocess back into Spack. This should provide a future-proof implementation for changes to the logic underlying the module system on various HPC systems.
=> Change from modulecmd interface to module interface

lib/spack/spack/build_systems/intel.py
- Only return scalapack libraries if `+mpi` is in the spec.
Fixes #11314
Fixes #11289
- set HOME when the intel silent installer is run. This prevents the
installer from using the ~/intel directory
Fixes #9713
=> Some fixes for Intel build system packages.

lib/spack/spack/hooks/permissions_setters.py, lib/spack/spack/test/cmd/spec.py, lib/spack/spack/test/permissions.py
Previously, the post-install hook to set file-permissions obliterated the suid, sgit, and sticky bits.
This PR changes it to keep those bits. The logic is that the build system knows better than we do what they should be.
It also adds logic to throw an error if you try to install an suid binary with world write permissions.
=> Bugfix/permissions Don't blow away suid and sgid bits

.travis.yml, share/spack/qa/setup.sh
- Codecov cannot handle as many coverage reports as we are generating
- As a result, our PR coverage pages have been broken for a while, and it's hard to tell people where to enhance their testing in PR reviews.
- Scale back to only running coverage for 3.7 and 2.7
- Make coverage depend on `COVERAGE=true` being in the environment, so we can control it from `.travis.yml`
- This is *probably* better.  We run the build tests for good measure, but we do not need to evaluate them for coverage.  The coverage reports are about unit tests.
=> coverage: only run coverage for subset of unit tests

var/spack/repos/builtin/packages/sqlite/package.py, var/spack/repos/builtin/packages/sqlite/remove_overflow_builtins.patch, var/spack/repos/builtin/packages/sqlite/sqlite_b0.patch
* New versions 3.27.{0,1,2}, 3.28.0.
* Restore ability to download and compile older versions (no checksums, therefore not preferred) with the addition of a variant (`+fts`) which conflicts with versions <3.26.0, thereby resolving issues with Magellan vulnerability.
* Automatic URL calculations.
=> sqlite: New versions; restore old versions; variant to resolve security issues

var/spack/repos/builtin/packages/py-pycares/package.py
Pycares includes a patched cares that is incompatible with system cares and is statically linked.
=> Add package py-pycares at 3.0.0

.travis.yml, share/spack/qa/run-unit-tests
See discussion at #11411.
Seeing just how much coverage 2.6 adds.
Also seeing whether we can get the 2.6 build working again -- it's been broken due to Travis's flaky containers for a while.
=> coverage: include Python 2.6 again

.travis.yml
We were allowing these to fail, but now that they pass, we'll require them again.
=> tests: require Python 2.6 tests to pass

.travis.yml
Python 3.4 was released in 2014, and it's [end-of-life](https://www.python.org/downloads/release/python-340/).  AFAIK it is not used as the default Python on any operating systems, so I do not believe we need to support it anymore.
=> tests: stop testing Python 3.4

var/spack/repos/builtin/packages/m4/package.py
Fixed logic that was checking for `arch.platform_os`, which,
does not appear to be a member of the ArchSpec class
anymore.
=> bugfix: fix m4 on osx high sierra

lib/spack/spack/util/module_cmd.py
Removes a vestigial print statement introduced in #8570
=> Module load should not print environment

var/spack/repos/builtin/packages/ntpoly/package.py
I would like to contribute a new package for SPACK called NTPoly.
NTPoly is a massively parallel library for computing the functions of sparse, hermitian matrices based on polynomial expansions. For sufficiently sparse matrices, most of the matrix functions in NTPoly can be computed in linear time.
I would like to thank the SPACK developers for giving a tutorial a few weeks ago at RIKEN, and I hope that this PR lines up with what they taught us!
=> New Package: NTPoly

var/spack/repos/builtin/packages/cuda/package.py
CUDA 10.0 provides Compatability libraries for running newer versions of CUDA with older drivers. These do not work with newer drivers.
=> CUDA package: exclude compat libs

var/spack/repos/builtin/packages/parallel-netcdf/package.py
Required for new versions of netcdf to succeed during configure.
Here is the error using NetCDF 4.6.3:
```
289    checking for ncmpi_create in -lpnetcdf... yes
290    checking Is libpnetcdf version 1.6.0 or later?... yes
291    checking for full path of header file pnetcdf.h... sed: couldn't flush stdout: Broken pipe
292    /spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/parallel-netcdf-1.8.1-hlhhe3ef
ocvp53itqj3ebqijkmp552u3/include/pnetcdf.h
293    checking if erange-fill is enabled in PnetCDF... yes
294    checking if relax-coord-bound is enabled in PnetCDF... no
>> 295    configure: error: PNetCDF must be built with relax-coord-bound
```
Here is the website that shows this option was added in 1.8.0 …
=> Add enable-relax-coord-bound to parallel-netcdf if version 1.8 or greater

var/spack/repos/builtin/packages/repeatmasker/package.py
repeatmasker 4.0.9 made some changes to the interactive configure script,
which required some refactoring in the package recipe.
The generation of spack-config.in was modified to be clearer about how lines were written,
and perl is now pulled from `which` instead of `inspect.getmodule(self)` which seemed to stop working for some reason.
Changes were tested to be backwards compatible with the existing 4.0.7 version.
=> repeatmasker: add 4.0.9

var/spack/repos/builtin/packages/r-rstan/package.py
depends on `r-loo` introduced in #11448 
also depends on new versions of `r-stanheaders` and `r-withr` introduced in #11446 and #11445
=> r-rstan: add 2.18.2

var/spack/repos/builtin/packages/r-construct/package.py
depends on `r-caroline` introduced in #11450 ,
depends on `r-rstantools` introduced in #11451 ,
and also needs the newer version of `r-rstan` introduced in #11447
=> r-construct: new package at 1.0.3

var/spack/repos/builtin/packages/py-tblib/package.py
tblib: Traceback serialization library. a dependency of spatialist package.
=> new python package: py-tblib

var/spack/repos/builtin/packages/kitty/package.py
pkgconfig is the correct virtual dependency while pkg-config is a specific implementation.
=> kitty: Fix pkgconfig dependency

lib/spack/spack/fetch_strategy.py, lib/spack/spack/test/conftest.py
- `svn info` prints different results depending on the system locale
- In particular, Japanese output doesn't contain "Revision:" -- it contains「レビジョン：」
- Change Spack code to use XML output instead of using the human-readable output
=> svn: use `svn info --xml` instead of `svn info` to get revisions

var/spack/repos/builtin/packages/r-urltools/package.py
depends on `r-triebeard` in #11457
=> r-urltools: new package at 1.7.3

var/spack/repos/builtin/packages/r-crul/package.py
depends on `r-httpcode` in #11454, `r-urltools` in #11458, new version of `r-curl` in #11456
=> r-crul: new package at 0.7.4

var/spack/repos/builtin/packages/r-rmysql/package.py
depends on `mariadb-connector-c` in #11043
=> r-rmysql: add 0.10.17, mariadb-connector-c dependency

var/spack/repos/builtin/packages/repeatscout/package.py
depends on `nseg` introduced in #11410
=> repeatscout: new package at 1.0.5

.flake8, .flake8_packages
…naming
Rules N813 and N814 prevented import statements like this:
xml.etree.ElementTree as et
xml.etree.ElementTree as ET
But both of those seem pretty reasonable.  We see no reason to require
any camelcase import to be imported "as" a camelcase word.
=> flake8: exceptions for pedantic camelcase rules from pep8-naming

var/spack/repos/builtin/packages/paraview/package.py
* Use externally provided mpi4py
* Make mpi4py and numpy both build deps instead of only run deps
* libxt is only on ~osmesa platform=linux
=> paraview: fix several dependency issues

var/spack/repos/builtin/packages/py-numpy/package.py
* New version: 1.16.3.
* Historical versions: 1.16.1, 1.16.0, 1.15.4, 1.15.3, 1.15.3, 1.15.0, 1.14.6, 1.14.5, 1.14.4, 1.11.3, 1.9.3.
=> numpy: new version 1.16.3; update historical versions.

lib/spack/spack/cmd/build_env.py, lib/spack/spack/test/cmd/build_env.py
New options `--dump <file>` and `--pickle <file>` dump the text and a pickle, respectively, of a source-able environment to the specified file.
The print-to-screen behavior when no command is given is ignored if `--dump` or `--pickle` is specified.
=> Allow command access to dump/pickle_environment from #8476

lib/spack/docs/extensions.rst, lib/spack/docs/index.rst, lib/spack/spack/extensions.py, lib/spack/spack/test/cmd_extensions.py, lib/spack/spack/test/extensions.py
This PR is a follow up of #8612 and an alternative implementation of the improved import capabilities in #11145.
The problem with #8612 was basically that for complex commands one couldn't split source code into python modules that were residing:
1. In the extension root folder 
2. In a subfolder of the `cmd` directory
This PR solves that issue by ensuring that, for each extension found, the python packages associated with the root folder and the `cmd` folder are in `sys.modules` with an appropriate `__path__` set.
List of modifications:
=> Spack extensions can import code from modules in root or cmd folder

var/spack/repos/builtin/packages/cdo/gcc9-openmp-1.9.7rc2.patch, var/spack/repos/builtin/packages/cdo/package.py
This makes several changes to make cdo work with cdo@9:
- Add version 1.9.7rc2
- Add a patch to make version 1.9.7rc2 build with gcc@9:
- Add a conflict for earlier versions
It also adds a pkgconfig build dependency as configure checks for it.
=> cdo: Fix build with gcc@9

var/spack/repos/builtin/packages/cmake/package.py
We've gotten a lot of complaints about CMake taking a long time to build, and I'd like to change the default to `+ownlibs` to reduce that overhead. 
- CMake is built *very* frequently, and the number of dependencies it has accumulated can take a very long time on some systems.
- Use +ownlibs by default to avoid the build overhead. This won't interfere with other packages by introducing conflicting libraries, as CMake is nearly always a build dependency.
=> cmake: default to +ownlibs to improve build times

var/spack/repos/builtin/packages/repeatmodeler/package.py
depends on `repeatscout` in #11409, `recon` in #11408
=> repeatmodeler: new package at 1.0.11

var/spack/repos/builtin/packages/py-metasv/package.py
depends on `py-pybedtools` in #11475
=> py-metasv: new package at 0.5.4

var/spack/repos/builtin/packages/r-popvar/package.py
depends on `r-bglr` in #11489, `r-rrblup` in #11488, `r-qtl` in #11487
=> r-popvar: new package at 1.2.1

lib/spack/spack/util/module_cmd.py
Adds executable=/bin/bash into Popen. We discovered this bug while
working in a csh/tsch environment. By executing with /bin/bash we ensure
that the module command works.
=> Execute modulecmd in bash shell

var/spack/repos/builtin/packages/qmcpack/package.py
This is a minor update:
- Add QMCPACK 3.7.0
- Add QMCPACK converter based on QE 6.4
- Change SOA default to True
=> QMCPACK Update May 2019

var/spack/repos/builtin/packages/dealii/package.py, var/spack/repos/builtin/packages/trilinos/package.py
keep it OFF by default due to the presence of the global symbol "divide"
that can lead to symbol clash with other libraries, for example see
https://github.com/dealii/dealii/issues/8170#issuecomment-492700787
=> trilinos: add variant to disable chaco from seacas

var/spack/repos/builtin/packages/py-kmodes/package.py
sklearn provides a k-means implementation, but no k-modes implementation for clustering categorical data. This package addresses that need.
=> Add py-kmodes package

var/spack/repos/builtin/packages/optional-lite/package.py, var/spack/repos/builtin/packages/span-lite/package.py, var/spack/repos/builtin/packages/string-view-lite/package.py
These packages only have CMake installs on their most recent versions.
Therefore, we overload all of the CMake stages to fallback to the old
versions (no-op for most, copytree for install), and use CMakePackage on
the new versions.
=> Update optional-lite and span-lite to use CMakePackage

lib/spack/spack/operating_systems/cnl.py
At NERSC, we added our own custom module PrgEnv-llnl which was
incorrectly reporting the os version as cnl9 instead of cnl6. Rather
than just grep all PrgEnv modules just grep the Cray.
=> Grep the cray PrgEnv directly

lib/spack/spack/cmd/flake8.py
I recently made a change to the `spack` executable, but `spack flake8` did not detect the change. This PR fixes that.
Are there any other Python files in Spack that don't end in `.py`? We could check for `python` in the shebang, but that's probably more costly than it needs to be. For what it's worth, `flake8` also only looks at `*.py` files [by default](https://github.com/PyCQA/flake8/blob/master/src/flake8/main/options.py#L88,L96). We could also use the `file` command on UNIX:
```console
$ file spack
spack: Python script text executable, ASCII text
$ file spack-python 
spack-python: POSIX shell script text executable, ASCII text
```
=> Make flake8 check python files without .py extension

var/spack/repos/builtin/packages/openmpi/package.py
This PR makes 2 changes to the openmpi package.
1. Adds a conflict for scheduler=loadleveler for openmpi >=3 as that is no longer a valid configure option.
1. Makes the behavior of the value of 'auto' for fabrics and schedulers defer to the openmpi configure script.
The default for the fabrics variant is 'auto' if verbs is not detected.
The default for the schedulers variant is 'auto'. In both cases, if/when
the default is 'auto' the effect is to actually set the variants to
'none'. This is because all of the possible values in the respective
lists pass the `--without-...` option to configure.
I believe the intent was to have those variants defer to the openmpi
configure and let it determine and use what it finds available on the
system. This is useful given that the required …
=> Openmpi default for fabrics/schedulers=auto behavior

var/spack/repos/builtin/packages/mesa/meson-expose-glapi-through-osmesa.patch, var/spack/repos/builtin/packages/mesa/package.py
Add upstream patch to fix missing gl symbols in OSMesa
Combined with #11485, Fixes #11398
=> mesa: Patch missing gl symbols in OSMesa

var/spack/repos/builtin/packages/dealii/package.py
unfortunately https://github.com/spack/spack/pull/11499 is not working as expected (at least for me).
```
$ spack spec -I dealii@develop+symengine
Input spec
-   dealii@develop+symengine
Concretized
...
dealii requires symengine variant build_type=Debug,Release, but spec asked for build_type=Release
```
This looks like a bug in Spack (at least code in deal.II package does not require both variants).
In this PR I am trying to re-phrase the same constraints but make sure that `depends_on()` are self excluding. The first commit works both for `spack spec -I dealii@develop+symengine` and `spack spec -I dealii@develop+symengine^trilinos+debug`, but the …
=> dealii: fix symengine constraints

lib/spack/docs/basic_usage.rst
`spack list` output is very long and takes up a lot of space in the docs.  Truncate it to just 10 lines and link to the package list page.
=> docs: truncate `spack list` output in basic usage

var/spack/repos/builtin/packages/lmod/package.py, var/spack/repos/builtin/packages/lua-luafilesystem/package.py, var/spack/repos/builtin/packages/lua/package.py
New versions added:
- Lmod version 8.1.5
- Lua version 5.3.5
- Lua Filesystem 1.7.0.2
Turned tcl to a link dependency so that Lmod's configure can find it.
=> Updated lmod (to version 8.1.5) and associated dependencies

lib/spack/spack/build_environment.py, lib/spack/spack/cmd/bootstrap.py, lib/spack/spack/cmd/common/arguments.py, lib/spack/spack/cmd/diy.py, lib/spack/spack/cmd/install.py, lib/spack/spack/package.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/cmd/common/arguments.py, lib/spack/spack/test/conftest.py, var/spack/repos/builtin.mock/packages/a/package.py, var/spack/repos/builtin/packages/bazel/package.py
This PR implements the refactoring requests in https://github.com/spack/spack/pull/11373#discussion_r281064828, in particular:
=> Simplified handling of parallel jobs during builds

var/spack/repos/builtin/packages/mbedtls/package.py
Add variant 'pic' for including in shared libraries.
Add build dependency on perl.  Compiling mbedtls runs several perl
scripts.
Add versions 2.7.10 and 2.16.1, the heads of the two main stable
branches.
=> mbedtls: add pic variant

var/spack/repos/builtin/packages/xsdk/package.py
wrt xsdk@develop - ginkgo requires openmp - so disable until we can add openmp dependencies consistantly
=> xsdk@0.4.0: update dealii defaults wrt changes in a973ab475

var/spack/repos/builtin/packages/gnupg/package.py, var/spack/repos/builtin/packages/libassuan/package.py, var/spack/repos/builtin/packages/libgcrypt/package.py, var/spack/repos/builtin/packages/libgpg-error/package.py
Update GnuPG to the latest version. Note that while some of the updates are only housekeeping, libassuan must be updated to at least version 2.5.0 for GnuPG version 2.2.15.
=> Update GnuPG and associated packages

var/spack/repos/builtin/packages/intel-mkl-dnn/package.py
intel-mkl-dnn@1.0-pc2 has been built successfully against gcc@8.3.0.
=> Add new versions for intel-mkl-dnn.

lib/spack/spack/cmd/mirror.py
`mirror create` should return a non-zero return code if errors occurred. In such a case, a user could retry, e.g. with
```bash
while [ $? -ne 0 ]
do
spack mirror create -d spack-mirror -D mpileaks
done
```
=> mirror create: non-zero return code

lib/spack/docs/conf.py, lib/spack/docs/requirements.txt
- `gettext_uuid=True` makes every commit update every .pot file in [spack/localized-docs](/spack/localized-docs) , and speeds up the internationalized doc build slightly.
- Optimize for less repository churn, and use `python-levenshtein` to accelerate the build instead.
=> docs: set gettext_uuid to False to reduce churn

share/spack/spack-completion.bash
Accidentally left this out of #11521 -- I had worked it in with the other commits but the push failed and I didn't notice.
This adds completion for the new `--header` and `--update` options in `spack commands` and `spack list --format=rst`.
=> commands: completion for new --update and --header options

etc/spack/defaults/config.yaml, lib/spack/docs/config_yaml.rst, lib/spack/docs/packaging_guide.rst, lib/spack/spack/cmd/common/arguments.py, lib/spack/spack/config.py, lib/spack/spack/test/cmd/common/arguments.py
fixes #11072
`config:build_jobs` is capped by the number of cores available
`config:build_jobs` controls the number of parallel jobs to spawn during builds, but cannot ever exceed the number of cores on the machine. The default is set to 16 or the number of available cores, whatever is lowest.
=> Cap the maximum number of build jobs

var/spack/repos/builtin/packages/gnutls/package.py
GnuTLS by default depends on Guile, added a guile variant. Updated GnuTLS to 3.6.8
=> guile variant + update to GnuTLS 3.6.8

var/spack/repos/builtin/packages/root/package.py
After cmake v3.12 FindPythonInterp used by llvm subsystem is deprecated. 
When building with python3 the cmake error below happens. 
FindPythonInterp sets PYTHON_EXECUTABLE=/usr/bin/python2.7 and calls
execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
"import sys; sys.stdout.write(';'.join([str(x) for x in sys.version_info[:3]]))"
OUTPUT_VARIABLE _VERSION
RESULT_VARIABLE _PYTHON_VERSION_RESULT
ERROR_QUIET)
Since PYTHONPATH is set to the python3 install this results in an error importing site and the _VERSION variable is not set.
Setting -DPYTHON_EXECUTABLE=path_to_python fixes this error:
118    -- Doxygen disabled.
119    -- Go bindings disabled.
120    -- LLVM host triple: x86_64-unknown-linux-gnu
121    -- LLVM default target triple: x86_64-unknown-linux-gnu …
=> ROOT: Set PYTHON_EXECUTABLE with +python variant

var/spack/repos/builtin/packages/lsf/package.py, var/spack/repos/builtin/packages/openmpi/package.py
Related: #8503
Hello!
:tipping_hand_woman: This PR adds a new external package for [IBM Platform LSF](https://www.ibm.com/marketplace/hpc-workload-management) (`lsf`) and adds it as a dependency for `openmpi` when `schedulers=lsf`.
LSF (Load Sharing Facility) is a batch scheduler for HPC environments; similar to Slurm, Torque, etc. The current Open MPI package supports `lsf` as a scheduler variant and will add the `--with-lsf` configure flag when compiling `openmpi`. However, the path for LSF is not necessarily standardized. It is also closed-source software that you retrieve from the IBM website and unpack onto a cluster as part of the initial setup, so it cannot be naturally-managed by Spack. Because the path is not standardized, passing `--with-lsf` instead of …
=> Add external package for IBM Platform LSF and have OpenMPI depend on it when LSF is specified in the schedulers variant.

var/spack/repos/builtin/packages/acts-core/package.py
This PR enables building the new ACTS 0.9.x releases.
It also marks the package as incompatible with Boost 1.70.0 (as it breaks our CMake configuration) and fixes the C++ standard selection logic by incorporating #11054.
=> New versions and bugfixes for the ACTS package

var/spack/repos/builtin/packages/root/package.py
Per @adamjstewart  use spec['python'].command.path
=> ROOT: set PYTHON_EXECUTABLE

var/spack/repos/builtin/packages/xrootd/package.py
When building with python3 PYTHON_EXECUTABLE needs to be set for deprecated FindPythonInterp to work as expected.
=> Xrootd: set PYTHON_EXECUTABLE with +python variant

var/spack/repos/builtin/packages/git/package.py, var/spack/repos/builtin/packages/git/patch/relocatable.patch
Apply patch to git to make it search for config files from its current install directory instead of the hard coded at install directory.
=> Git: patch to make git relocatable with buildcache.

lib/spack/spack/relocate.py, var/spack/repos/builtin/packages/libxpm/package.py, var/spack/repos/builtin/packages/root/package.py
Addresses  this error
> spack buildcache create -raf flecsi
---Lots of operations complete---
==> creating binary cache file for package cmake@3.14.2%gcc@7.4.0~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 
==> Error: need more than 1 value to unpack
=> Buildcache relocate.py error fix

lib/spack/spack/hooks/permissions_setters.py, lib/spack/spack/modules/common.py, lib/spack/spack/test/modules/common.py, lib/spack/spack/test/permissions.py, lib/spack/spack/util/file_permissions.py
Previously, modulefiles were not set with the same permissions as the package installation.
For world-readable packages, this would not cause a problem.
For group readable packages, it does
```
packages:
mypackage:
permissions:
group: mygroup
read: group
write: group
```
In this case, the modulefile is unreadable by members of the group other than the one who installed it.
This PR adds logic to the modulefile writers to set the permissions based on the configuration in `packages.yaml`
=> set modulefile permissions based on package configuration

lib/spack/spack/compiler.py, lib/spack/spack/compilers/arm.py, lib/spack/spack/compilers/cce.py, lib/spack/spack/compilers/clang.py, lib/spack/spack/compilers/gcc.py, lib/spack/spack/compilers/intel.py, lib/spack/spack/compilers/xl.py
This adds the `c99_flag` and `c11_flag` virtual methods to the compiler class, and implements it for most of the existing compilers.
This is a cleaner solution to the problem seen in #11611
=> add C standard flags to compiler classes

lib/spack/spack/cmd/common/arguments.py, lib/spack/spack/cmd/dependencies.py, lib/spack/spack/cmd/graph.py, lib/spack/spack/database.py, lib/spack/spack/dependency.py, lib/spack/spack/directives.py, lib/spack/spack/graph.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/dependencies.py, lib/spack/spack/test/cmd/graph.py, lib/spack/spack/test/graph.py, lib/spack/spack/test/package_class.py
There's a fair amount of cruft in the Spack core, and this the first of what will be ongoing attempts to clean a bunch of it up in advance of adding a new concretizer.  
The main user-facing changes here are:
There are also a number of changes to `PackageBase` to make all this cleaner.  In particular:
More details are in the commits; probably best to read those while reviewing this.
=> Dependencies: various improvements to handling of static dependencies

var/spack/repos/builtin/packages/gnutls/package.py
The gnutls configure script was picking up /usr/bin/guile2 instead of the spack-built guile executable. Setting GUILE in the environment forces the gnutls configure script to use the spack-built build executable.
fixes #11601
=> set GUILE env var when building gnutls

lib/spack/spack/compilers/clang.py
A small follow up fix for #11618, cleaning up error messages caught [here](https://github.com/spack/spack/pull/11618#discussion_r290839260)
=> clang: fix some error messages for C/C++ flags

var/spack/repos/builtin/packages/nettle/package.py
nettle's source uses some C99-specific language features which can break building on some systems.
This forces the compiler to build against the C99 standard.
=> nettle: fix broken build

lib/spack/llnl/util/tty/__init__.py, lib/spack/spack/binary_distribution.py, lib/spack/spack/build_systems/autotools.py, lib/spack/spack/cmd/install.py, lib/spack/spack/cmd/location.py, lib/spack/spack/cmd/mirror.py, lib/spack/spack/cmd/modules/__init__.py, lib/spack/spack/cmd/upload_s3.py, lib/spack/spack/database.py, lib/spack/spack/fetch_strategy.py, lib/spack/spack/main.py, lib/spack/spack/mirror.py, lib/spack/spack/package.py, lib/spack/spack/repo.py, lib/spack/spack/spec.py, lib/spack/spack/stage.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/git_fetch.py, lib/spack/spack/test/hg_fetch.py, lib/spack/spack/test/mirror.py, lib/spack/spack/test/patch.py, lib/spack/spack/test/stage.py, lib/spack/spack/test/svn_fetch.py, lib/spack/spack/test/url_fetch.py, share/spack/qa/run-unit-tests
The goal of this work is to make stage.source_path available before it exists.  The approach (per @tgamblin) is to use a well-known stage source path name that is available when Stage is instantiated but does not exist until "expanded".  
Well-behaved tarballs will be expanded such that the stage.source_path is the root directory (so hidden Mac OS X files are in the parent of stage.source_path).  Exploding tarballs will be expanded in their respective subdirectories of stage.source_path.  Un-expanded archives and other files (e.g., patches) will be moved to within stage.source_path.
This PR includes assorted documentation updates.
=> stage: make `source_path` available before stage is built

lib/spack/spack/test/package_sanity.py
=> Package sanity tests need to be able to find packages in repos other

var/spack/repos/builtin/packages/lua-luafilesystem/package.py
Fixes #11645.
@odoublewen 
After #11528, we use `$stage_dir/src` as the path for all expanded tarballs, so that the expanded path is *known* in advance. This helps client code that needs to know the checked out source path before fetching and expanding the source.
Some builds seem to assume they know `stage.source_path` and construct it themselves.  e.g, `lua-luafilesystem` was doing this:
```python
fmt = os.path.join(
self.stage.path,
'luafilesystem-{version.underscored}',
'rockspecs',
'luafilesystem-{semver.dotted}-{tweak_level}.rockspec'
)
```
It assumes the name of the directory under stage is `'luafilesystem-{version.underscored}'`.  Code like this should use `stage.source_path` instead of joining `stage.path` with an assumed name.
Here is the fix:
```python
fmt = os.path.join( …
```
=> bugfix: lua-luafilesystem package should use stage.source_path

lib/spack/spack/stage.py
After #11528, `spack cd` would fail like this in `spack location` because the `StageComposite` object didn't have all the necessary properties:
```console
(spackbook):~$ spack cd lua-luafilesystem
==> Error: 'StageComposite' object has no attribute 'expanded'
```
Added the new `expanded` property to it.
=> bugfix: StageComposite must include the `expanded` property`

var/spack/repos/builtin/packages/python/package.py, var/spack/repos/builtin/packages/tcl/package.py, var/spack/repos/builtin/packages/tix/package.py, var/spack/repos/builtin/packages/tk/package.py
Tix appears to be old, but a user at LLNL has requested it be supported in Python. It looks like Tix uses structures in tcl that were removed from tcl 8.6, hence the dependence on older versions. Because of this, I thought it would be best to make tix a variant in python that is not enabled by default, rather than forcing all python builds to use the older tcl/tk versions.
=> added tix package and python variant for tix

lib/spack/spack/cmd/list.py, lib/spack/spack/test/cmd/list.py
We use `spack list --foramt=html` now, as it is much faster and doesn't make the docs build take forever.
=> commands: remove unused `spack list --format=rst`

var/spack/repos/builtin/packages/lammps/package.py
This allows openmp support to be explicitly specified, rather than relying on the cmake auto-detection.
=> add openmp variant to lammps

lib/spack/llnl/util/filesystem.py, lib/spack/llnl/util/multiproc.py, lib/spack/llnl/util/tty/__init__.py, lib/spack/llnl/util/tty/colify.py, lib/spack/llnl/util/tty/color.py, lib/spack/llnl/util/tty/log.py, lib/spack/spack/architecture.py, lib/spack/spack/cmd/compiler.py, lib/spack/spack/compiler.py, lib/spack/spack/compilers/__init__.py, lib/spack/spack/operating_systems/cnl.py, lib/spack/spack/operating_systems/cray_frontend.py, lib/spack/spack/package.py, lib/spack/spack/test/architecture.py, lib/spack/spack/test/cmd/release_jobs.py, lib/spack/spack/test/cmd/test_compiler_cmd.py, lib/spack/spack/test/compilers.py
closes #10127
Following the request in https://github.com/spack/spack/pull/10127#pullrequestreview-186647721 I started refactoring the logic underneath:
```console
$ spack compiler add
```
The version in this PR shows much better performance than the version in `develop`. The main modifications are:
1. `spack.compilers.find_compilers` employs a `multiprocess.pool.ThreadPool` to execute system commands for the detection of compiler versions.
2. A few memoized functions have been introduced to avoid poking the filesystem multiple times for the same results.
Timing tests will be posted in the discussion below.
=> Compiler search uses a pool of workers

lib/spack/spack/cmd/list.py, lib/spack/spack/test/cmd/list.py, lib/spack/spack/test/versions.py, lib/spack/spack/version.py
List the latest version of each package in JSON encoding.
Preparation for consumption for a "spack badge" service.
```command
spack list --format version_json
```
```json
[
{"...": "..."},
{"name": "adios2",
"latest_version": "2.3.1",
"versions": ["develop", "2.3.1", "2.2.0", "2.1.0", "2.0.0"],
"homepage": "https://www.olcf.ornl.gov/center-projects/adios/",
"file": "https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/adios2/package.py",
"maintainers": ["ax3l", "chuckatkins"],
"dependencies": {"build": ["cmake", "pkgconfig", "mpi", "zeromq", "hdf5", "adios", "bzip2", "zfp", "python", "py-numpy", "py-mpi4py"], "link": ["mpi", "zeromq", "hdf5", "adios", "bzip2", "zfp", "python"], "run": ["python", "py-numpy", "py-mpi4py"], "test": []}},
{"...": "..."},
{"name": …
```
=> spack list: format version_json

var/spack/repos/builtin/packages/trilinos/package.py
ADIOS2 is the latest implementation of the ADaptable Input Output System,
ADIOS. This brand new architecture was designed to continue supporting the
performance legacy of ADIOS, and extend its current capabilities to address
current and future input/output (IO) challenges in the scientific data
lifecycle through effective research and development (R&D) activities.
ADIOS2 was recently added as a Third Party Library of Trilinos when it
was integrated to IOSS, a library inside the SEACAS package.
=> Add ADIOS2 option to Trilinos

lib/spack/spack/spec.py, lib/spack/spack/test/directory_layout.py, lib/spack/spack/test/spec_dag.py
See: https://github.com/spack/spack/issues/11542
The intent of this PR is that for a spec DAG like:
```
X->Y->Z (all link dependencies)
X->W->Z (W has a build dependency on Z)
```
that you can do something like
```
$ spack install w
$ spack install X ^/hash-of-installed-w
```
In this case, if Y and W have differing constraints on Z, this allows Y to build Z without using constraints from W (since W only needed Z to build).
=> Don't apply build-dependency constraints for installed packages

share/spack/qa/run-unit-tests
Let's see if Travis hangs on `spack spec mpileaks` now that #10190 is in.
=> tests: restore `spack spec mpileaks` for Python 2

var/spack/repos/builtin/packages/m4/package.py
I  will add LDFLAGS  to configure options when building with fujitsu compiler.
This is a necessary change to build m4 with Fujitsu compiler.
=> m4: Define flags when using fujitsu compiler

var/spack/repos/builtin/packages/cmake/package.py
Drop the `gnutls` dependency as CMake has no direct dependency on it.  This also explicitly disables `openssl` from the `+ownlibs` curl when `~openssl`.
=> CMake ssl fixes

share/spack/packages/Dockerfile, share/spack/packages/build-image.sh, share/spack/packages/push-image.sh, share/spack/packages/split.sh, share/spack/qa/run-docker-tests
Build the docker image for the new package index REST API on each merge/push to develop and master.
Follow-up to: #11652
=> CD: Package Index

etc/spack/defaults/packages.yaml, var/spack/repos/builtin/packages/ninja-fortran/package.py, var/spack/repos/builtin/packages/ninja/package.py
Temporary fix to #11628.
I think a more permanent fix would be something along the lines of:
- write at least one virtual package, call the 1st one `ninja-build`
- if it's possible, give `ninja-build` a `+fortran` variant, if not, have a 2nd virtual package called `ninja-build-fortran`
- have `ninja` and `ninja-fortran` provide the appropriate virtual packages
=> ninja{-fortran}: make pkgs nonvirtual (fix #11628)

var/spack/repos/builtin/packages/pfunit/package.py
[spack-fail-pfunit-4.0.0.txt](https://github.com/spack/spack/files/3259874/spack-fail-pfunit-4.0.0.txt)
- 3.2.10, 3.3.0, 3.3.1, 3.3.2, 3.3.3
- 3.2.9 now with sha256
- 4.0.0 is added, but commented out (build fails, see errors)
Verification builds
Darwin x86_64:
dantopa@cn100:pr-pfunit-darwin-general.spack $ spack find pfunit
==> 5 installed packages
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
pfunit@3.2.9  pfunit@3.2.10  pfunit@3.3.0  pfunit@3.3.1  pfunit@3.3.2  pfunit@3.3.3
Darwin Power9:
-- linux-rhel7-ppc64le / gcc@4.8.5 ------------------------------
pfunit@3.2.9  pfunit@3.2.10  pfunit@3.3.0  pfunit@3.3.1  pfunit@3.3.2  pfunit@3.3.3
Darwin ARM:
dantopa@cn805:pr-pfunit-darwin-arm.spack $ spack find pfunit
==> 5 installed packages
-- linux-rhel7-aarch64 / gcc@4.8.5 …
=> Add latest releases for pFUnit

lib/spack/spack/cmd/modules/__init__.py, lib/spack/spack/modules/common.py, lib/spack/spack/store.py, lib/spack/spack/test/modules/common.py, lib/spack/spack/test/modules/tcl.py
`spack module tcl find -r <spec>` (and equivalents for other module systems) was failing when a dependency was installed in an upstream Spack instance. This updates the logic to appropriately handle that case and adds a test for it.
=> Fix recursive module find for upstream dependencies

var/spack/repos/builtin/packages/paraview/package.py, var/spack/repos/builtin/packages/vtk/package.py
Paraview@5.6.0 fails to build with intel compilers on certain platforms.
Error messages have been traced to the optional MotionFX lib.
(see https://discourse.paraview.org/t/error-build-5-6-0-rc1/572)
Adding the motionfx variant allows for succesful builds on these platforms.
=> Paraview:  Add motionfx variant

lib/spack/llnl/util/filesystem.py
See #11588 (@downloadico)
This is a continuation of #10798 (@michaelkuhn)
Can anyone think of any other common header file extensions?
=> Add additional common C++ and Fortran header file extensions

var/spack/repos/builtin/packages/warpx/package.py
These changes are needed so that WarpX will build without needing any extra specifications.
=> warpx: only allow master branch, and fix build on darwin

lib/spack/spack/stage.py, lib/spack/spack/test/stage.py, var/spack/repos/builtin/packages/aspera-cli/package.py, var/spack/repos/builtin/packages/bcl2fastq2/package.py, var/spack/repos/builtin/packages/catalyst/package.py, var/spack/repos/builtin/packages/charmpp/package.py, var/spack/repos/builtin/packages/clhep/package.py, var/spack/repos/builtin/packages/cuda/package.py, var/spack/repos/builtin/packages/lmod/package.py, var/spack/repos/builtin/packages/nseg/package.py, var/spack/repos/builtin/packages/singularity/package.py
Fixes #11528 
See also #11648 for why this is necessary
Note that installing `catalyst` fails in the same place it does for the commit prior to merging changes for #11528.
=> Corrected `source_path` for built-in packages

var/spack/repos/builtin/packages/hpcviewer/package.py, var/spack/repos/builtin/packages/intel-xed/package.py
Change 'destination' to 'placement' in the use of resource() for
intel-xed and hpcviewer.  Recent commits (1842873f and eb584d89)
changed the directory path for a resource and thus broke the build
for these packages.
=> intel-xed and hpcviewer: adapt to new resource placement

lib/spack/spack/cmd/location.py, lib/spack/spack/test/cmd/location.py, lib/spack/spack/test/stage.py
Add test per discussion in #11647
=> Added check of `expanded` StageComposite property

var/spack/repos/builtin/packages/trilinos/package.py
DataTransferKit now requires ArborX submodule for its work. The 12.14 Trilinos's version has frozen dtk version, so we don't update that.
=> trilinos: update dtk@develop resourcedtk to require 'submodules=True' flag

lib/spack/docs/tutorial_configuration.rst
This fixes a few typos, adds a hint to `spack config blame` and brings the variant specification in line with other docs sections.
=> docs: fix config tutorial

var/spack/repos/builtin/packages/hpl/package.py
The 2.3 version of HPL needs LDFLAGS set for use of MKL libraries.
=> Fix latest HPL for MKL use

lib/spack/docs/tutorial.rst
This adds a link to the ISC19 tutorial slides.
=> docs: update tutorial page for ISC19 tutorial

var/spack/repos/builtin/packages/openpmd-api/package.py
Update the dependency on pybind11 to the latest version (`constexpr` signature support for all C++11 compilers + fixes).
=> openPMD-api: pybind11>=2.3.0

lib/spack/spack/stage.py, lib/spack/spack/test/stage.py
Some tests introduced in #11528 temporarily set the user's `config:build_stage`, which affected (or created) a config.yaml file in the user's `$HOME/.spack` directory that could leave entries behind if the tests fail.
This change ensures only temporary configuration files are used/affected by these tests.
=> tests/bugfix: Use config fixture for stage tests

var/spack/repos/builtin/packages/go/package.py
Added the newest stable versions from: https://golang.org/dl/
=> Add Go@1.12.[5,6] and 1.11.[10,11]

var/spack/repos/builtin/packages/py-pyproj/package.py
@citibeth Can you take a look at this? I tried building without the `proj` dependency but it crashed saying the system installation was too old. When I added a dependency on `proj`, everything built fine.
=> Add py-pyproj 2.2.0

var/spack/repos/builtin/packages/grass/package.py
PROJ requirements taken from https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status
=> GRASS GIS does not yet support PROJ.6

var/spack/repos/builtin/packages/magics/package.py
Version requirement comes from https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status
=> Restrict magics to proj@:5

var/spack/repos/builtin/packages/mapserver/package.py
See https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status and https://github.com/mapserver/mapserver/issues/5766. It sounds like the latest release supports PROJ.6, though I didn't test it.
=> Specify which versions of PROJ work with MapServer

var/spack/repos/builtin/packages/py-cartopy/package.py
See 
https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status
https://github.com/SciTools/cartopy/issues/1140
https://github.com/SciTools/cartopy/pull/1252
=> py-cartopy does not yet support PROJ.6

var/spack/repos/builtin/packages/proj/package.py
@citibeth @neilflood I decided to add PROJ.6 to Spack. As you probably know, the PROJ.6 API is not backwards compatible with PROJ.5 and PROJ.4. I updated several packages that depend on `proj` to account for this (in followup PRs), but if you could test other packages for me that would be great.
Packages that depend on `proj` that may need to be updated due to PROJ.6:
=> Add PROJ.6

lib/spack/spack/directory_layout.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/install.py
A common annoyance on the Spack mailing list has been this scenario:
1. Alice reports a problem building
2. Bob asks them to share their `spack-build.out` file.
3. Alice does so, attaching it to an email message or GitHub Issue comment.
4. Bob cannot just click on the resulting file in email to view it, because desktop applications (and GMail too) don't know what application to launch of `.out` files.
Now, Bob has to spend more time downloading the file and opening it in an editor, than how long it might take them to spot the problem.
This PR solves that problem by simply calling the file `spack-build.txt` instead.  That will make everybody's lives a little easier; and I can see no downside to it.
=> Rename build.out to build.txt

var/spack/repos/builtin/packages/rclone/package.py
Fixes #11745
Setting the GOPATH environment variable to the stage path precludes creation of a $HOME/go directory.
=> Ensure proper gopath set for rclone.

var/spack/repos/builtin/packages/acts-core/package.py
Here are a couple extra ACTS releases that I forgot during my last round of updates.
Along the way, I...
- Add a leading zero to old version numbers, to please old-school sorting algorithms (the hash is unchanged, as you can check)
- Remove the mention of the acts-framework package, which isn't in Spack upstream yet, and will likely depend on a different ACTS release when it will land.
=> A few more ACTS releases that I forgot in my last update

var/spack/repos/builtin/packages/repeatmasker/package.py
`repeatmasker` depended on `hmmer` but was never actually configured to use it.
The package also had many shebangs pointing to random perl locations, now patched to use Spack's perl installation.
=> repeatmasker: various fixes

var/spack/repos/builtin/packages/cdo/package.py
Successfully built and passes all tests with Clang 10.0.1 on macOS 10.14.5.
I tried building with PROJ.6 and everything built just fine and all of the tests passed. However, according to https://code.mpimet.mpg.de/boards/1/topics/7600, PROJ.6 is still not supported in CDO. I'm going to err on the side of caution and restrict the dependency to `proj@:5`.
@skosukhin
=> Add CDO 1.9.7.1

var/spack/repos/builtin/packages/gplates/package.py
Couldn't find any mention of what versions of PROJ are supported, but since the latest release is old and requires GDAL 1, I highly doubt it supports PROJ 6.
=> Restrict gplates to proj@:5

.travis.yml
Currently, all macos tests are failing because brew cannot install ccache without updating brew.
This PR: ensure `brew update` is run before using brew in test environment
=> Testing bugfix: Spurious MacOS failures

lib/spack/spack/test/cmd/compiler_command.py
regression test for 11678 on darwin fails because darwin /usr/bin/gccis secretly clang. This PR updates the test to expect this.
=> bugfix for regression test for 11678 on Darwin

lib/spack/spack/spec.py
This addresses #11686. When resolving a dependence, the current string was being over written by the specified package's spec.
=> fixed spec dependence attribute writing for #11686

var/spack/repos/builtin/packages/eospac/package.py
v 6.3.1, 6.4.0beta.1, 6.4.0beta.2, 6.4.0beta.3, 6.4.0beta.4, 6.4.0
Mon Jun 17 13:48:43 MDT 2019
Verification builds of all versions on LANL Darwin: ARM, Power9, x86_64
[spack-find-ldf.txt](https://github.com/spack/spack/files/3298645/spack-find-ldf.txt)
Sha256sums
[ss-sha256sum.txt](https://github.com/spack/spack/files/3298649/ss-sha256sum.txt)
=> eospac: create sha256 sums

var/spack/repos/builtin/packages/xfd/package.py
Fixes #11526.  The xfd configure script tests for libintl but
incorrectly concludes that no additional library is needed because
gettext is provided in libc.  So we add '-lintl' to ldlibs.
Add latest version 1.1.3.
=> xfd: fix autoconf test for libintl

var/spack/repos/builtin/packages/osu-micro-benchmarks/package.py
package update for 5.6.1 and additions to paths to easily access all the benchmarks.
=> osu-micro-benchmarks: update to 5.6.1 

var/spack/repos/builtin/packages/py-matplotlib/package.py
Starting with 2.1.0, `backports.functools_lru_cache` replaces `functools32`
when using python 2.7.x until python2 support is dropped in 3.0.0.
=> py-matplotlib: Fix dependencies in [2.1.0:3.0.0)

var/spack/repos/builtin/packages/py-python-dateutil/package.py
setup.py secretly downloads it anyway, but this fails on air-gapped machines.
=> py-python-dateutil: Version 2.7.0 acquired dependency on setuptools-scm

var/spack/repos/builtin/packages/gdl/package.py
This package has way too many dependencies for me to test PROJ.6 support, so I'm going to explicitly require `proj@:5` until someone has the time to make sure it works with PROJ.6.
=> Add GDL 0.9.9

lib/spack/llnl/util/filesystem.py, lib/spack/spack/fetch_strategy.py, lib/spack/spack/stage.py, lib/spack/spack/test/stage.py, var/spack/repos/builtin/packages/intel-xed/package.py, var/spack/repos/builtin/packages/warpx/package.py
For resources, it is desirable to use the expanded archive name of the resource as the name of the directory when adding it to the root staging area.
#11528 established 'spack-src' as the universal directory where source files are placed, which also affected the behavior of resources managed with Stages.
This adds a new property to Stage to remember the name of the expanded source directory, and uses this as the default name when placing a resource directory in the root staging area.
This also:
* Ensures that downloaded sources are archived using the expanded archive name
* Updates working_dir context manager to guarantee restoration of original working directory when an exception occurs
* Adds a "temp_cwd" context manager which creates a temporary directory and sets it as the working …
=> ResourceStage: use expanded archive name by default

var/spack/repos/builtin/packages/boost/package.py
Starting with 1.69.0, boost added a bjam option for the default symbol
visibility.  Up to 1.68.0, the value was always 'global'.  1.69.0
changed the default to 'hidden' but added an option.
Most packages will work with hidden and won't notice.  But some
packages may discover that an interface that they rely on is now
hidden and inaccessible.
https://boostorg.github.io/build/manual/develop/index.html#bbv2.builtin.features.visibility
----------
In my case (hpctoolkit), we needed `parse_graphviz_from_string()` from
graph which went dark in 1.69.
Btw, with `--keep-stage` or building boost outside of spack, you can
see that boost has added an extra directory level for visibililty in
the build stage.
In 1.68.0, compiling date_time has:
```
gcc.compile.c++ …
```
=> boost: add variant for symbol visibility

lib/spack/spack/compilers/pgi.py
Follow-up to #10704, see #10599.
From @anderbubble:
> On current develop, it's picking up the `-llvm` variants by default in all circumstances now.
> My understanding is that the llvm variant doesn't support all the same features as the traditional variant of the pgi code generator; so defaulting to the llvm variant is probably the wrong thing.
> In my opinion, `spack compiler find` shouldn't be looking for the `-llvm` binaries by name; it should just be willing to accept when the standard binary names return LLVM in their version string. That way, you can specify which compiler you want by pointing it at `linux86-64` or `linux86-64-llvm`.
This change reverts to the previous behavior of only looking for `pgcc` and friends, not `pgcc-llvm` and friends.
=> Ignore pgcc-llvm and friends, default to pgcc

var/spack/repos/builtin/packages/libnrm/package.py, var/spack/repos/builtin/packages/nrm/package.py, var/spack/repos/builtin/packages/py-jsonpatch/package.py, var/spack/repos/builtin/packages/py-jsonpointer/package.py, var/spack/repos/builtin/packages/py-warlock/package.py
Adds packages for two software pieces from Argonne National Laboratory.
NRM, a node-local resource manager: https://xgitlab.cels.anl.gov/argo/nrm
libnrm, its application interfacing library: https://xgitlab.cels.anl.gov/argo/libnrm
Also adds three json schema related python dependencies for NRM.
=> libnrm,nrm,py-jsonpatch,py-jsonpointer,py-warlock: New packages.

var/spack/repos/builtin/packages/mpe2/package.py
The packages of mep use original configure.
Because these scripts is very old, new architecture host is faild to configure.
This patch use autotools for mpe to update config.guess.
Also add libx11 dependency.
=> mpe2: use autotools and add libx11 dependency.

var/spack/repos/builtin/packages/mpileaks/package.py
The packages of mpileaks use original configure.
Because these scripts is very old, new architecture host is faild to configure.
This patch usempileaks to update config.guess.
=> mpileaks: use autotools.

var/spack/repos/builtin/packages/exonerate/package.py
The packages of exonerate use original configure.
Because these scripts is very old, new architecture host is faild to configure.
This patch use autotools for exonerate to update config.guess.
=> exonerate: use autotools  for new architecture host

var/spack/repos/builtin/packages/precice/package.py
This fixes a compatibility with Boost 1.70.0 issue.
=> precice: add version 1.5.1

lib/spack/spack/stage.py, lib/spack/spack/test/stage.py
Fixes https://github.com/spack/spack/issues/11816
@paulbry
Allow packages to refer to non-expanded downloads (e.g. a single script) using Stage.archive_file. This addresses a regression from https://github.com/spack/spack/pull/11688 and adds a unit test for it.
=> Reference non-expanding resources by "Stage.archive_file"

var/spack/repos/builtin/packages/r-sf/package.py
Might be supported in the latest release according to https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status, but I can't access the CRAN site to confirm.
=> r-sf may not support PROJ.6

var/spack/repos/builtin/packages/py-astor/package.py, var/spack/repos/builtin/packages/py-astunparse/package.py
Are the license headers no longer a requirement? `spack create https://pypi.io/packages/source/a/astunparse/astunparse-1.6.2.tar.gz` did not automatically create it
=> New package py-astor (and test dependency py-astunparse)

var/spack/repos/builtin/packages/hypre/package.py
=> hypre: superlu-dist-link-2.15.0.patch is now in hypre@develop

var/spack/repos/builtin/packages/py-pytables/package.py
This PR adds the hdf5-blosc dependency to the py-pytables package.
=> The py-pytables package depends on hdf5-blosc

var/spack/repos/builtin/packages/libepoxy/package.py
On PPC64LE systems, libepoxy failed at configure with this error:
configure: error: libX11 headers (libx11-dev) required to build with GLX support
This is because --enable-glx is set to auto by default and was being implicitly turned on. This PR makes sure that glx support is explicitly enabled/disabled, and when enabled, that libx11 is brought in as a dependence.
=> add glx variant to libepoxy

var/spack/repos/builtin/packages/rodinia/package.py
Rodinia makes unconditonal use of CUDA, but CudaPackage provides an optional '+cuda' variant.
I used `conflicts('~cuda')` to enforce the usage of the variant, maybe there is a better way to do this @alalazo?
=> rodinia: new package at 3.1

var/spack/repos/builtin/packages/fmt/fmt-attributes-cpp11_4.1.0.patch, var/spack/repos/builtin/packages/fmt/fmt-no-export-cpp11flag_3.0.0.patch, var/spack/repos/builtin/packages/fmt/fmt-use-cmake-cxx-standard_3.0.0.patch, var/spack/repos/builtin/packages/fmt/package.py
This revives and rebases #10569 
Spack supported versions of fmt default to C++11 for versions less than 5, C++14 greater than 5, with fmt implementing fallbacks to whatever compiler supports.
To give better ABI compatibility and use of newer standards, provide a cxxstd variant defaulting to 11 with 98-17 options. Use cmake_args to set CMAKE_CXX_STANDARD as appropriate, plus use of FMT_USE_CPP11 option for C++98 builds. Use conflicts to disable use of certain standards in versions that don't support, or fail the build, with those standards. Use CMAKE_CXX_STANDARD_REQUIRED to fail, at configure step only, use of compiler/cmake combination that do not support/know the requested standard.
Add patches to unify use of CMAKE_CXX_STANDARD in 3.0 versions, remove hard-coding of compiler flags in …
=> fmt: Add version 5.3.0 with cxxstd variant support

var/spack/repos/builtin/packages/partitionfinder/package.py, var/spack/repos/builtin/packages/py-sfepy/package.py, var/spack/repos/builtin/packages/py-tables/package.py
The developers refer to their software as `PyTables`, but the package name on PyPI is just `tables`. The package name in Conda is `Pytables`, but the module that you import is called `tables`. I usually like to default to the PyPI package name, as that is what you will see in the `setup.py` whenever a package lists its dependencies.
=> Rename py-pytables -> py-tables

lib/spack/spack/cmd/arch.py, lib/spack/spack/test/cmd/arch.py
spack has frontend and backend in platform.
For example, we install zlib to frontend, we can use as follows:
`spack install zlib arch=frontend`
But `spack arch` output only default (currently same as backend) architecture, and we can't known frontend archtecture.
This patch add --frontend and --backend options on `spack arch` to print frontned and backend architecture.
=> Add --frontend and --backend option to spack arch.

var/spack/repos/builtin/packages/relion/package.py
Beta version removed.
URL now back at Github since that now contains latest releases.
=> added relion 3.0.6

var/spack/repos/builtin/packages/gdal/package.py, var/spack/repos/builtin/packages/ncl/package.py
ncl does not build with newer versions of gdal (or rather proj). This also needs a small change to gdal, otherwise we end up with both proj@5 and proj@6 in the spec.
=> ncl: Fix build

var/spack/repos/builtin/packages/cbtf-krell/arm.patch, var/spack/repos/builtin/packages/cbtf-krell/package.py
cbtl-krell use some linux system call directory.
But aarch64 linux kernel is deprecated some system call (For example, open).
This patch replace deprecated system call to existed system call.
=> cbtf-krell: fixed to build on ARM.

var/spack/repos/builtin/packages/font-util/package.py
Some of the fonts now included in font-util need mkfontdir to build.
=> font-util: Add missing mkfontdir build dependency

var/spack/repos/builtin/packages/tcsh/package.py
The download url of the tcsh package was invalid because the following error occurred.
So, I changed the download url and added the latest version (version 6.21.00).
=> tcsh: change the download url, add version 6.21.00

var/spack/repos/builtin/packages/f90cache/package.py
The download url of the f90cache package was invalid because the following error occurred.
So, I changed the download url.
The version of the f90cache package provided by the vendor has changed from "0.99" to "0.99c".
"https://perso.univ-rennes1.fr/edouard.canot/f90cache/"
=> f90cache: change the download url

var/spack/repos/builtin/packages/gotcha/arm.patch, var/spack/repos/builtin/packages/gotcha/package.py
gotcha install fail the following message:
>> 56    /usr/local/spack/var/spack/stage/gotcha-1.0.2-chlsywpzmeffiqynie65b4
fxd3x5wkca/src/src/libc_wrappers.c:361:21: error: 'SYS_open' undecla
red (first use in this function)
57        result = syscall(SYS_open, pathname, flags, mode)
This error is fixed by pull request of gotcha (https://github.com/LLNL/GOTCHA/pull/79), but this is not merged:
This patch is aplly this patch in current version.
=> gotcha: fixed to build on ARM.

var/spack/repos/builtin/packages/fenics/package.py, var/spack/repos/builtin/packages/llvm/package.py
Setting name within the package class allows overriding the package name, which both packages do using several for loops.
Fixes #11789
=> fenics, llvm: Fix package names being overriden

var/spack/repos/builtin/packages/likwid/package.py
It seems #11479 broke building likwid. @TomTheBear @alalazo
=> likwid: Fix build with version 4.3.4

var/spack/repos/builtin/packages/blast-plus/package.py
blast-plus package pass --with-64 flag to configure, 
and configure is checked compiler to -m64 flag is correct.
This patch remove --with-64 flag if target is aarch64.
=> blast-plus: remove --with-64 on ARM.

var/spack/repos/builtin/packages/otf/package.py
The packages of otf use original configure.
Because these scripts is very old, new architecture host is failed to configure.
This patch otf to update config.guess.
=> otf: use autotools.

var/spack/repos/builtin/packages/pmdk/package.py
Apparently PMDK 1.6 cannot be built without ncurses. This PR fixes the dependency.
=> fixing PMDK dependency: ncurses missing

var/spack/repos/builtin/packages/bib2xhtml/package.py
The download url of the bib2xhtml package was invalid because the following error occurred.
So, I changed the download url.
The version of the bib2xhtml package provided by the vendor has changed from "v3.0-15-gf506" to "v3.0-79-ge935".
"https://www.spinellis.gr/sw/textproc/bib2xhtml/"
=> bib2xhtml: change the download url

lib/spack/docs/build_settings.rst
Add an example of a 'modules:' entry for an external package in
packages.yaml.  The 'External Packages' section of 'Build
Customization' mentions 'paths:' and 'modules:' and gives an
example of paths, but not modules.
----------
I was showing someone how to set up a `packages.yaml` file for an
external (not spack built) module and I told him, "Look, it's right
here in the docs."  Except it wasn't, so ....
Also, when I first tried this, I was confused about the correct
directory for paths.  Cmake was in `/usr/bin/cmake`, so my first try
was `/usr/bin`, which is not correct.  So, I added one sentence for
that.
=> docs: add example for an external module in packages.yaml

lib/spack/spack/directory_layout.py, lib/spack/spack/test/install.py
Fixes https://github.com/spack/spack/issues/11870
Remove package access from directory_layout; add regression test to ensure that specs can be uninstalled without a package being known
=> Allow uninstalling missing packages

share/spack/setup-env.sh
@billbarth
- We've seen this a few times now where users have set up `cd` to echo the new directory, and it screws up `setup-env.sh`
- In the past we've said this is user error.
- This just fixes it -- adding command to two `cd` invocations is not difficult, and it'll prevent users from hitting this.
- We should use `command cd` inside `$()` from now on.
=> setup-env.sh: send cd output to /dev/null when it affects Spack

lib/spack/spack/test/spec_semantics.py
This removes some unnecessary noqa's from the Spack code.  Specifically:
```python
'\{name}',  # NOQA: ignore=W605
```
This one is actually borderline erroneous, as it relies on `'\{'` not being a valid escape sequence. If at some point it _became_ a valid escape, the code would be wrong.
Lines like the above one should either be written:
```python
'\\{name}',
```
or (probably preferable):
```python
r'\{name}',
```
I've found that `W605` is nearly always raised correctly -- we should pay attention to it.
cc: @becker33 @scheibelp
=> style: remove unnecessary NOQA exception

var/spack/repos/builtin/packages/llvm/package.py
When compiling llvm@flang-20180921 build fails because it tries to compile the `CppBackend` backend to LLVM which no longer exists in LLVM.  This is because for some reason the version check incorrectly decides that this is an older version of LLVM than 3.9.0.  This change extends this check to disable `CppBackend` for `spec.version`s that start with `fl`.
=> llvm: Extend version check for CppBackend to exclude flang versions of llvm

var/spack/repos/builtin/packages/py-netcdf4/package.py
`spack spec py-netcdf4` produces the following error message:
```
netcdf requires hdf5 variant +hl, but spec asked for ~hl
```
py-netcdf4 depends on netcdf, which depends on `hdf5+hl`. py-netcdf4 also depends on `hdf5`, which uses variant `hdf5~hl` by default, causing a conflict. We can resolve the conflict by depending on `hdf5+hl` in py-netcdf4.
=> py-netcdf4: depend on hdf5+hl

var/spack/repos/builtin/packages/camellia/package.py
As camellia needs hdf5 version:1.8.x, we changed the way to specify version of hdf5.
comments from https://github.com/spack/spack/pull/8337
"HDF5 1.10.x is incompatible with Camellia, at least right now, so adding dependency to versions up to 1.8.x."
=> camellia: fix hdf5 dependency

var/spack/repos/builtin/packages/tk/package.py
The `configure` script in the tk package searches for X11 libraries and header files in standard directories. This PR ensures that X11 packages provided by spack are used instead.
=> tk: avoid search for X headers and libraries

var/spack/repos/builtin/packages/planck-likelihood/arm.patch, var/spack/repos/builtin/packages/planck-likelihood/package.py
planck-likelihood package is useed -m64 flag to compile.
This patch remove -m64 flag if target is aarch64.
=> planck-likelihood: remove -m64 on ARM

var/spack/repos/builtin/packages/mpich/package.py
Supersedes #11907.  @sameershende.
Added a wrapperrpath variant to mpich that defaults to `True`.
Users can set this to `False` (e.g., spack install mpich~wrapperrpath) to
disable the wrapper RPATHs.  This makes it easier to replacing an MPICH
installation in a container with an MPICH for the host system,
e.g., Cray MPICH with Shifter on Cori, Intel MPI, MVAPICH2, etc.
=> mpich: wrapperrpath variant allows disablement of RPATH usage in mpicc

var/spack/repos/builtin/packages/py-markdown/package.py
The last depends_on has a comma rather than a semicolon separating
python2 versions.
=> Typo in py-markdown

var/spack/repos/builtin/packages/py-nc-time-axis/package.py
Required by py-scitools-iris (coming soon).
=> py-nc-time-axis: cftime support for matplotlib axis

var/spack/repos/builtin/packages/r-gwmodel/package.py
depends on `r-spacetime` in #11885, `r-spatialreg` in #11886
=> r-gwmodel: new package at 2.0-9

var/spack/repos/builtin/packages/libmo-unpack/package.py, var/spack/repos/builtin/packages/py-mo-pack/package.py
The Unified Model is an atmospheric model developed by the UK Met Office in partnership with researchers and weather services around the world. Outputs from the model are usually stored in a custom binary format (although netcdf can also be used in some applications). This package provides a library and a python interface to encode and decode fields from the binary files.
The package is required by py-scitools-iris, which is coming soon in a separate PR.
=> Encode and decode fields from Unified Model

lib/spack/spack/operating_systems/cnl.py, lib/spack/spack/test/operating_system.py
The CNL OS previously used the *Cray PE* version to determine the OS version.  Cray does not synchronize PE and CLE releases; you can run CLE7 with PrgEnv 6 (and NERSC currently does).
=> cray: use the cle-release file to determine CNL version

lib/spack/spack/directives.py, lib/spack/spack/spec.py, lib/spack/spack/test/directives.py, lib/spack/spack/test/patch.py, lib/spack/spack/test/spec_semantics.py, lib/spack/spack/test/spec_syntax.py, var/spack/repos/builtin.mock/packages/when-directives-false/package.py, var/spack/repos/builtin.mock/packages/when-directives-true/package.py
This builds on #10192 and should be merged after it.
`parse_anonymous_spec()` is a vestige of the days when Spack didn't support nameless specs well.  We don't need it anymore because now we can write `Spec()` for a spec that will match anything, and `satisfies()` semantics work properly for anonymous specs.
=> refactor: remove parse_anonymous_spec() method

var/spack/repos/builtin/packages/opa-psm2/opa-psm2-install-prefix.patch, var/spack/repos/builtin/packages/opa-psm2/package.py
This PR corrects a problem with the opa-psm2 package.  It was installing headers into `<prefix>/usr/include` and libraries into `<prefix>/usr/lib` instead of `<prefix>/include` and `<prefix>/lib`.  The extra level of `usr/` subdirectories causes dependent packages like libfabric to fail to build. 
To reproduce, run the following on any x86 system (it does not need to have Omni-Path hardware present):
`spack install libfabric fabrics=psm2`
The above command will fail due to lack of psm2 headers (or else mistakenly pick up system psm2 headers if present) unless the PR is applied.
=> patch opa-psm2 to correct installation prefixes

var/spack/repos/builtin/packages/portcullis/package.py
portcullis package is useed -m64 flag to compile.
This patch remove -m64 flag if target is aarch64.
=> portcullis: remove -m64 on aarch64.

var/spack/repos/builtin/packages/py-pyugrid/package.py
UGRID is a convention for storing unstructured grids in netcdf files (https://github.com/ugrid-conventions/ugrid-conventions). This package provides a python implementation of the UGRID data model.
Required by py-scitools-iris (coming soon).
=> py-pyugrid: unstructured grids in netcdf files

var/spack/repos/builtin/packages/py-pyke/package.py
Python Knowledge Engine (PyKE). According to the homepage:
> Pyke introduces a form of Logic Programming (inspired by Prolog) to the Python community by providing a knowledge-based inference engine (expert system) written in 100% Python.
This package is required to install py-scitools-iris, which is coming soon in a separate PR.
=> py-pyke: new package

var/spack/repos/builtin/packages/openmpi/package.py
Hi!
I'd like to add support to PBS/TM to OpenMPI, as it's already done with the mellanox mxm drivers.
=> OpenMPI: add support for pbs/tm at configure.

.codecov.yml
There's too much information on our PRs, and the Travis test results (which are arguably more important than coverage) get buried in coverage information.
cc: @alalazo
=> coverage: remove sub-reports; only show project/patch on PRs

var/spack/repos/builtin/packages/libfabric/package.py
libfabric version 1.8.0 just came out. This PR just updates the package for libfabric to additionally specify this version.
=> add version 1.8.0 for libfabric package

var/spack/repos/builtin/packages/libtool/package.py
The packages of libtool ver.2.4.2 use original configure.
these scripts is very old, new architecture host is faild to configure.
Currently, it is executed autoreconf method only when building develop version.
So,  I modified the source to execute autoreconf when building version 2.4.2 too.
=> libtool: execute autoreconf at ver.2.4.2

var/spack/repos/builtin/packages/py-reportlab/package.py
The py-reportlab package includes binaries for easy_install and pip.
That blocks activation if py-setuptools and/or py-pip are installed.
This PR block the binaries from py-reportlab as easy_install and pip
should be installed with their respective packages.
=> Set ignore files for py-reportlab

var/spack/repos/builtin/packages/py-antlr4-python3-runtime/package.py
This package provides runtime libraries required to use parsers generated by ANTLR4 for the Python3 language.
The package is needed by the py-cf-units package (#11891).
=> py-antlr4-python3-runtime: new package

var/spack/repos/builtin/packages/jdk/package.py
The previous versions except for 1.8.0_141-b15 and 1.8.0_131-b11 are no longer available for download at that URL, because the download for only the previous versions came to require login.
=> jdk: Add JDK 12.0.1

var/spack/repos/builtin/packages/py-stratify/package.py
The purpose of this package is explained in https://github.com/SciTools-incubator/python-stratify/blob/master/index.ipynb:
> Whilst this is not the only use for the stratify package, NWP vertical interpolation was the motivating usecase for the package's creation.
> In its simplest form, vertical interpolation amounts to a 1d interpolation at each grid-point. Whilst some more sophistication exists for a number of interpolators, stratify can be seen as an optimisation to vectorize these interpolations beyond naïve nested for-loops.
Requirement for py-scitools-iris (coming soon).
=> py-stratify: vertical interpolation/stratification of atmos/ocean data

.codecov.yml, .travis.yml, share/spack/qa/run-unit-tests, share/spack/qa/setup-env-test.sh, share/spack/qa/setup.sh, share/spack/setup-env.sh
On the latest Ubuntu and Debian, and on Arch, the default system shell is `dash`, and there are systems out there that don't have `bash`.  See [Arch](https://wiki.archlinux.org/index.php/Dash) and [Ubuntu](https://wiki.ubuntu.com/DashAsBinSh)'s docs on this.
If you run as Spack in those environments, you get this:
```shell
+ export SPACK_ROOT=/spack
+ . /spack/share/spack/setup-env.sh
+ function spack {
/bin/sh: 59: /spack/share/spack/setup-env.sh: function: not found
ERROR: Aborting with RETVAL=255
```
This PR makes `setup-env.sh` `dash`-compatible 😄 .  And less readable 😞 .  I think it is worthwhile to be `sh`-compatible so that we can be used easily in these more and more popular minimal environments.
=> Make setup-env.sh compatible with dash

var/spack/repos/builtin/packages/tau/package.py
Resolves #11846.
Declare a conflict for TAU versions older than 2.28.1, that they
can't depend on libelf or libdwarf.  The user can still install it
by specifying `tau@2.24~libelf~libdwarf`.
=> tau: add conflicts for libelf/libdwarf variants

lib/spack/spack/main.py
Fixes #7841.
We weren't previously printing stack traces on SystemExit or KeyboardInterrupts.
=> bugfix: always generate a stack trace when spack is run with --debug

.travis.yml
__sudo: required__ no longer is.  In Travis CI __sudo__ is _always_ available and there is no way to turn it off.
=> travis: the sudo tag is now deprecated

lib/spack/spack/spec.py
This fix a bug introdcued by removing parse_anonymous_spec() in #10206.  See [this comment](https://github.com/spack/spack/pull/10206#issuecomment-508979049) by @balay.
Conflicts' when specs are now *actually* anonymous, and the name of the package is implicit, so we need to remember to add it back to error messages.
@balay: does this work for you?
=> bugfix: conflicts should print out the spec that has the conflict

var/spack/repos/builtin/packages/r-graph/package.py
The current version constraint matches the appropriate Bioconductor release (R@3.4:3.9) but the DESCRIPTION in this package allows it to build with R >= 2.10.
=> r-graph: update R constraint to reflect DESCRIPTION

var/spack/repos/builtin/packages/environment-modules/package.py
New bugfix version in the v4.2 series.
Release notes: https://modules.readthedocs.io/en/stable/NEWS.html#modules-4-2-5-2019-07-08
=> environment-modules: add version 4.2.5

var/spack/repos/builtin/packages/motif/package.py
The download URL of the motif package was invalid because the following error occurred.
```
curl: (22) The requested URL returned error: 406 Not Acceptable
==> Fetching from http://cfhcable.dl.sourceforge.net/project/motif/Motif 2.3.8 Source Code/motif-2.3.8.tar.gz failed.
```
The above cause is `Motif 2.3.8 Source Code` of the URL can't be read with blanks.
Therefore, I changed blanks to `%20` and checked the checksum of tarball using the changed URL.
Please see below for the motif checksum:
```
$ curl -O http://cfhcable.dl.sourceforge.net/project/motif/Motif%202.3.8%20Source%20Code/motif-2.3.8.tar.gz
[ogura@langtx202 work]$ md5sum motif-2.3.8.tar.gz
7572140bb52ba21ec2f0c85b2605e2b1  motif-2.3.8.tar.gz
```
The above checksum is the same as the original checksum.
=> motif: fix the download url

var/spack/repos/builtin/packages/zoltan/package.py
The packages of zol use original configure.
Because these scripts is vtanery old, new architecture host is faild to configure.
This patch use autotools for zoltan to update config.guess.
=> zoltan: use autotools for new architecture host.

var/spack/repos/builtin/packages/diffsplice/package.py
diffsplice package is useed -m64 flag to compile.
This patch remove -m64 flag if target is aarch64.
=> diffsplice: remove -m64 on ARM.

var/spack/repos/builtin/packages/ferret/package.py
The ferret package has not been changed since 2016, and newer versions of the ferret software are now available. This PR provides the current version (7.2).
Ferret can use hdf5 and netcdf with or without mpi, so the variant `~mpi` is unnecessary (and causes extra package installations when `+mpi` packages already exist). However, the `+hl` variant of hdf5 is required to avoid a spec conflict, because the default for hdf5 is `~hl` but netcdf requires `hdf5+hl`.
Ferret searches for X11, and it tries to use system libraries if they exist. We prefer to use libx11 provided by spack, to avoid problems with the ancient X libraries in some HPC operating systems (e.g. RHEL6).
The previous package created symlinks to netcdf, hdf5 and zlib libraries, assuming that static libraries existed. This …
=> Ferret: add version 7.2 and adjust dependencies

var/spack/repos/builtin/packages/py-astropy/package.py
- correctly installs under python@3.5:3.7.3
- (partially) fixes https://github.com/spack/spack/issues/11966
=> py-astropy: added latest version 3.2.1

var/spack/repos/builtin/packages/luit/package.py
The packages of luit use original configure.
Because these scripts is very old, new architecture host is failed to configure.
This patch luit to update config.guess.
=> luit: use autotools.

var/spack/repos/builtin/packages/libfabric/package.py
Adds optional ability to specify "tcp" provider for libfabric package.  The tcp provider (in conjunction with rxm) is an alternative to the sockets provider for emulating libfabrics communication over TCP/IP.  It will likely  perform better than the sockets provider in some scenarios, though.
=> add support for tcp provider in libfabric

lib/spack/spack/test/package_class.py
This check increases `PackageBase.possible_dependencies` coverage and was originally part of PR #11797.
=> test: Extra possible-dependencies coverage check

var/spack/repos/builtin/packages/megahit/amd.patch, var/spack/repos/builtin/packages/megahit/package.py
megahit was not compile on arm.
This patch is enabled megahit to build on arm.
=> megahit: fixed to build on ARM.

var/spack/repos/builtin/packages/boost/package.py
Compile with toolset=clang (but still bootstrap with toolset=gcc)
Brings package in to line with https://developer.arm.com/tools-and-software/server-and-hpc/arm-architecture-tools/resources/porting-and-tuning/building-boost-with-arm-compiler/procedure
=> Boost: Compile with toolset=clang for Arm compiler

var/spack/repos/builtin/packages/velvet/package.py
velvet package is useed -m64 flag to compile.
This patch remove -m64 flag if target is aarch64.
=> velvet: remove -m64 on aarch64.

var/spack/repos/builtin/packages/bowtie2/package.py
* Add version 2.5.3.1.
* Add simde for ARM.
To compile on ARM, Makefile add `-Ithird_party/simde`, but bowtie2 dose not include simde.
So simde is downloaded when target is ARM.
* Remove -fopenmp-simd when gcc 4.8.X or before for ARM.
`-fopenmp-simmd` is addes gcc 4.9.0 (https://gcc.gnu.org/gcc-4.9/changes.html#languages).
So if gcc 4.8.X or before, -fopenmp-simd is removed.
* Add Makefile option POPCNT_CAPABILITY=0 for ARM.
=> bowtie2: Add version 2.5.3.1 and fix to build on ARM

var/spack/repos/builtin/packages/tk/package.py
TK can be built with support for libXft and X Screensaver. Both of these
are turned on in the Tk configure script. That means the system
libraries will get picked up if they are on the system and nothing is
specified in the package. Since the default for both of them is 'True' I
set the default value for the variants to 'True'.
=> Add variants for tk package

var/spack/repos/builtin/packages/r/package.py
This PR has several modifications for the r package.
- The tk package is always depended on but this pulls in X11, making the
'X' variant non-functional. This PR sets a dependency of tk on '+X'.
- There is a missing dependency on libxmu when '+X' is set.
- The libraries for R wind up in a non-standard location and are thus
left out of the RPATH settings. This PR adds that directory to RPATH.
- The MKL integer interface for gfortran is not in the BLAS libs. This
PR replaces the intel interface with the gfortran interface if needed.
- Use the `LibraryList` `ld_flags` method for blas as that is more in
line with th R Installation and Administration manual.
Note that this PR depends on PR #11956. This PR closes #8642.
=> Modifications to r package

lib/spack/spack/cmd/__init__.py, lib/spack/spack/test/cmd/find.py
- Namepsaces were shown without dots after the new format strings were added.
@becker33: this one should be easy.
=> bugfix: show dot after namespaces in `spack find -N`

share/spack/setup-env.sh
`setup-env.sh` was not properly detecting a bash shell when bash was run as `/bin/sh`.
This fixes the detection routine to always report `bash` when `bash` is run as `sh`.  We no longer parse the path to the executable indicated in `$BASH`.
@wspear -- this should fix your issue.
=> bugfix: setup-env.sh detects bash even when bash is run as sh

lib/spack/spack/compilers/fj.py, lib/spack/spack/test/compilers.py
・Fix `pic_flag` to `-KPIC` from `-fPIC`.
・Correct method of `test_fj_flags`：correct mistake of specifying version.
=> Fix pic_flag and test contents about Fujitsu compiler.

var/spack/repos/builtin/packages/jdk/package.py
Add the following `provides` call in the jdk package, because added JDK 12.0.1 in #11903
```
provides('java@12', when='@12.0:12.999')
```
=> jdk: Add the 'provides' call

lib/spack/spack/cmd/create.py, lib/spack/spack/test/cmd/create.py, share/spack/spack-completion.bash
This is a variant of the tests originally added as part of PR #11797.
NOTES:
- Patch coverage cannot be increased with automated testing
- This PR "blocks" the addition of the `BundlePackage` template creation test mentioned in #11981 
TODO:
=> tests: Add template creation test

lib/spack/spack/cmd/bootstrap.py, share/spack/spack-completion.bash
Straight forward copy-paste to ensure `spack bootstrap` accepts the same `--{use,no}-cache` arguments as `spack install`.
=> Copy --{use,no}-cache from install to bootstrap

var/spack/repos/builtin/packages/r/package.py
This adds a '+rmath' variant to R enabling the build of the standalone Rmath library as described [here](https://cran.r-project.org/doc/manuals/R-admin.html#The-standalone-Rmath-library).
=> r: add rmath variant for standalone rmath library

lib/spack/llnl/util/filesystem.py, lib/spack/spack/spec.py, var/spack/repos/builtin/packages/cuda/package.py, var/spack/repos/builtin/packages/hypre/package.py, var/spack/repos/builtin/packages/netlib-lapack/package.py, var/spack/repos/builtin/packages/sundials/package.py
Avoids excessive search times when, eg, lapack-blas is an external package installed in large system directories.
Closes: #11929
=> Preferentially look for blas and lapack libs in prefix.lib, prefix.lib64

var/spack/repos/builtin/packages/cfitsio/package.py
- currently cfitsio uses system curl, potentially pulling in unwanted system dependencies and lib-paths
=> make cfitsio explicitly depend on curl

var/spack/repos/builtin/packages/py-basemap/package.py
According to the basemap tutorial (https://basemaptutorial.readthedocs.io/en/latest/first_map.html), the way to import Basemap is as follows:
```
from mpl_toolkits.basemap import Basemap
```
However, this failed when I tried it with py-basemap from spack. The py-basemap package was installing into an egg, but the above command assumes that basemap is installed into an existing mpl_toolkits package (part of py-matplotlib).
By adding py-setuptools as a dependency at build time, py-basemap installs into a normal directory tree. When py-basemap and py-matplotlib are both activated, the basemap directory is linked into mpl_toolkits, so that the above import statement works correctly.
=> py-basemap: install without egg

var/spack/repos/builtin/packages/amg/package.py, var/spack/repos/builtin/packages/amg2013/package.py, var/spack/repos/builtin/packages/hypre/package.py, var/spack/repos/builtin/packages/kripke/package.py, var/spack/repos/builtin/packages/laghos/package.py, var/spack/repos/builtin/packages/lcals/package.py, var/spack/repos/builtin/packages/lulesh/package.py, var/spack/repos/builtin/packages/macsio/package.py, var/spack/repos/builtin/packages/samrai/package.py, var/spack/repos/builtin/packages/scr/package.py, var/spack/repos/builtin/packages/spindle/package.py, var/spack/repos/builtin/packages/sundials/package.py, var/spack/repos/builtin/packages/xbraid/package.py, var/spack/repos/builtin/packages/zfp/package.py
LLNL's "Computation" directorate is now the "Computing" directorate, and they're rebranding the website.
Unfortunately, changing the URL still does not fix things, as all of the downloads seem to have permissions set incorrectly after the change.  But I expect these URLs to be right eventually, and the old ones do not work, either.
=> fetching: computation.llnl.gov is now computing.llnl.gov

var/spack/repos/builtin/packages/binutils/package.py
I fixed the download URL because the previous URL are no longer available.
In addition, installing binutils with Fujitsu compiler will cause the following errors:
`x86_64.cc:1592:10: error: case value evaluates to 3221225474, which cannot be narrowed to type 'int' [-Wc++11-narrowing]`
The above cause is narrowing conversions are not allowed by {} initialization, since C++11. 
http://www.stroustrup.com/C++11FAQ.html#narrowing
Therefore, I used `-Wno-narrowing` to ignore the above errors and continue with the previous semantics of silently converting values.
https://gcc.gnu.org/wiki/FAQ#Wnarrowing
=> binutils: added '-Wno-narrowing' to CXXFLAGS when using fj compiler via flag_handler

lib/spack/spack/cmd/uninstall.py, lib/spack/spack/test/cmd/uninstall.py
fixes #3690
fixes #5637 
Uninstalling dependents of a spec was relying on a traversal of the parents done by inspecting `spec._dependents`. This is in turn a `DependencyMap` that maps a package name to a single `DependencySpec` object (an edge in the DAG) and cannot thus model the case where a spec has multiple configurations of the same parent package installed.
This commit works around this issue by constructing the list of specs to be uninstalled in an alternative way, and adds tests to verify the behavior. The core issue with `DependencyMap` is not resolved here.
=> spack uninstall can uninstall specs with multiple roots

lib/spack/spack/build_systems/intel.py, var/spack/repos/builtin/packages/intel-parallel-studio/package.py, var/spack/repos/builtin/packages/intel/package.py
This PR adds the ability to specify the auto-dispatch targets that can
be used by the Intel compilers. The `-ax` flag will be written to the
respective compiler configuration files. This ability is very handy when
wanting to build optimized builds for various architectures. This PR
does not set any optimization flags, however.
=> Add auto-dispatch specification to Intel packages

lib/spack/spack/build_environment.py
All documentation mentions that `build_jobs` is limited by the number of cores available in the system. This is also enforced when setting it via `--jobs`. However, when setting it via `config.yaml`, it can exceed the number of cores available, making builds run out of memory.
=> Fix build_jobs exceeding number of cores

var/spack/repos/builtin/packages/boost/package.py
We will use clang toolset when building with Fujitsu compiler.
=> boost: use clang toolset when building with Fujitsu compiler.

var/spack/repos/builtin/packages/binutils/package.py
Clang also shows an error for the narrowing conversion in binutils
=> binutils: Adding Clang to narrowing conversion error workaround

var/spack/repos/builtin/packages/qt/package.py
It seems that GitHub's output changed slightly for this patch (one more letter for both short hashes on the index line), probably due to the number of objects in the repository.
=> qt: fix patch checksum

share/spack/setup-env.sh
Fixes #12027 
@ajw1980: does this work for you?
=> bugfix: fix module() function in setup-env.sh

.codecov.yml
Codecov is not updating PRs with status anymore.
=> coverage: restore status updates on PRs

lib/spack/spack/test/data/sourceme_unset.sh, lib/spack/spack/test/environment_modifications.py, lib/spack/spack/util/environment.py
fixes #11522 
closes #7536
Credits for this change goes also to @mgsternberg (original author of #7536)
Modifications done in this PR:
=> Ignore Modules v4 environment variables in `from_sourcing_file`

var/spack/repos/builtin/packages/r/package.py
The configure of the `r` package with the fujitsu compiler was failed because the following error occurred:
```
300    configure: WARNING: I could not determine FPICFLAGS.
>> 301    configure: error: See the file doc/html/R-admin.html for more information.
```
According to the following URL, the build with compilers except `gcc` needs to set `FPICFLAGS`:
http://www.hep.by/gnu/r-patched/r-admin/R-admin_79.html
Therefore, I set `FPICFLAGS` for compilers except `gcc`.
=> r: set FPICFLAGS for compilers except 'gcc'

var/spack/repos/builtin/packages/python/package.py
Simple fixup to allow arbitrary versions to be installed without checksum validation by splitting the version against any alpha characters and using the first element (which is what python maintainers appear to be doing).
=> Added url_for_version to python/package.py

lib/spack/spack/cmd/diy.py, share/spack/spack-completion.bash
Developers use the `spack diy` command to build from local source (rather than fetching from the internet).
Previously, the `spack diy` command would run all the way through the install. This PR allows the `-u/--until` argument to the `spack diy` command, which gives the user the ability to specify the *last* install phase for Spack to run.
Use case:
```
spack diy -u configure my-package
make
<testing>
make
<testing>
etc
```
=> Allow developers to use Spack for partial builds

lib/spack/spack/test/install.py, lib/spack/spack/test/packages.py
These tests were originally included in PR #11797.
These test cases are intended to increase Spack code coverage.
=> tests: uninstall_by_spec error and rpath_args tests

var/spack/repos/builtin/packages/libjpeg-turbo/package.py
Cmake executed try_compile when installing libjpeg-turbo, but it was failed with Fujitsu compiler.
Because cmake didn't use compiler flags and Fujitsu compiler needs flags for each environment.
So, we will add spack cflags to cmake options only when using Fujitsu compiler.
※ Libjpeg-turbo doesn't need CXXFLAGS or FFLAGS.
=> libjpeg-turbo: Use spack flags for cmake building with Fujitsu compiler.

var/spack/repos/builtin/packages/bmi/package.py
The git server that previously hosted the BMI repository is being retired and will no longer be publicly accessible after July 22, 2019.  We migrated the repo to a new (long term) server.
=> update web site and git url for BMI package

lib/spack/docs/environments.rst, lib/spack/docs/index.rst, lib/spack/spack/cmd/add.py, lib/spack/spack/cmd/env.py, lib/spack/spack/cmd/find.py, lib/spack/spack/cmd/release_jobs.py, lib/spack/spack/cmd/remove.py, lib/spack/spack/concretize.py, lib/spack/spack/environment.py, lib/spack/spack/filesystem_view.py, lib/spack/spack/schema/env.py, lib/spack/spack/spec.py, lib/spack/spack/spec_list.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/test/concretize.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/spec_list.py, lib/spack/spack/test/spec_semantics.py, var/spack/repos/builtin.mock/packages/mpich/package.py, var/spack/repos/builtin.mock/packages/mpileaks/package.py
Resolves #8835
This PR requires an update after #10017 is merged. I've marked WIP for now.
Allow users to specify combinatorial sets of packages for Environments.
This feature is aimed at facilities deployment people, to enable Spack usage at the facility level.
From the documentation (with only slight formatting changes):
"
Entries in the ``specs`` list can be individual abstract specs or a
spec matrix.
A spec matrix is a yaml object containing multiple lists of specs, and
evaluates to the cross-product of those specs. Spec matrices also
contain an ``excludes`` directive, which eliminates certain
combinations from the evaluated result.
The following two Environment manifests are identical:
```yaml
spack:
specs:
- zlib %gcc@7.1.0
- zlib %gcc@4.9.3
- libelf %gcc@7.1.0
- libelf %gcc@4.9.3
- …
```
=> Spack stacks: Allow combinatorial Environment specifications.

var/spack/repos/builtin/packages/libxpm/package.py
If gettext is installed in the system it won't be in the spec tree.
=> libxpm: cope with system gettext if configured.

lib/spack/llnl/util/filesystem.py, lib/spack/spack/directory_layout.py
Specialised wrapper for `mkdirp`
It sets permissions to all folders that it creates and not just the deepest one.
It is used to create install_dir hierarchy for packages with right permissions.
Proposed fix for #11240
=> Fix #11240

var/spack/repos/builtin/packages/font-util/package.py
Fixes https://github.com/spack/spack/issues/12026
Required on some systems
=> add autoconf/automake build deps to font-util

lib/spack/spack/patch.py, lib/spack/spack/test/packages.py, lib/spack/spack/test/patch.py, var/spack/repos/builtin.mock/packages/patch-inheritance/package.py
Fixes #11844
Fixes #8908 
Previously, a new repo with the following package extending the behavior or the `gcc` package would fail:
```
from spack.pkg.builtin.gcc import Gcc as BuiltinGcc
class Gcc(BuiltinGcc):
def install(self, spec, prefix):
...
BuiltinGcc.install(self, spec, prefix)
```
See #11844 for the error message. The reason for the bug is that the patches are stored in the same directory as the `package.py` file for which they are defined. If we inherit from `builtin.gcc`, we need to still find the patches associated with `builtin.gcc`. 
The above package code will now work. We use python's method resolution order to find the first module which lives in a directory that also contains a patch file of the appropriate name.
=> Package inheritance: Find patch files defined in parent classes using MRO

lib/spack/spack/environment.py, lib/spack/spack/test/cmd/env.py, share/spack/qa/setup-env-test.sh
After #4048 I tried running `spack env activate` and `despacktivate` and noticed some problems.  Turned out they were with my environment, but I added shell tests for this stuff anyway.  This actually ended up catching a bug in the code output by `spack env deactivate --sh` -- it now works properly with `set -u`.
=> environments: activate/deactivate tests, support `set -u`

lib/spack/spack/compilers/__init__.py, lib/spack/spack/test/compilers.py
Fixes #11910.
If the same compiler is defined twice, Spack currently throws an error.
This PR changes that behavior to choose the earliest (highest priority and earliest within a given scope) definition of that compiler.
There is a debug message printed if there are duplicate compilers, available using `spack -d`.
=> allow multiple compiler definitions

lib/spack/spack/environment.py
1. There exists ugly code that round trips specs to yaml to remove their build-only dependencies, because those are not stored in views.
2. There exists a nice function that copies a spec, optionally only copying link and run deptypes
This PR uses 2 to replace 1.
=> environment views: refactor build-only dependency removal

var/spack/repos/builtin/packages/hpcviewer/package.py, var/spack/repos/builtin/packages/ibm-java/package.py
ibm-java: fix the URL to only use a machine type that ibm-java
supports so that 'spack info' doesn't report a non-existent URL on
platforms that it doesn't support.
=> hpcviewer: add version 2019.07

lib/spack/spack/test/cmd/buildcache.py, lib/spack/spack/test/cmd/debug.py, lib/spack/spack/test/cmd/module.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/database.py, lib/spack/spack/test/spec_syntax.py
The `database` and `mutable_database` fixtures were installing and uninstalling the same specs multiple times to maintain the test database in a consistent state. This PR optimizes the procedure by:
- Installing specs only the first time the fixtures are requested
- Caching the installation path into a persistent folder
- Erasing the installation path and copying the cache back into it when needed
The results on my laptop:
```console
$ uname -a
Linux nuvolari 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
are the following. On `develop` (with 2 tests not marked):
```console
$ python3.7 bin/spack test -m db
============================================================== test session starts …
```
=>  Speed-up tests that rely on the database fixture

lib/spack/spack/compilers/clang.py, lib/spack/spack/test/compilers.py
According to https://iscinumpy.gitlab.io/post/omp-on-high-sierra/, Apple Clang can actually build with OpenMP, you just need to install separate OpenMP libraries. This was used in #11496, but split into a separate PR to allow more time for review.
=> Add OpenMP flag for Apple Clang

var/spack/repos/builtin/packages/libsharp/1.0.0-arm.patch, var/spack/repos/builtin/packages/libsharp/arm.patch, var/spack/repos/builtin/packages/libsharp/package.py
libsharp add -march=native for gcc 4.x.
This patch avoid -march=native on aarch64.
=> libsharp: Don't add -march=native on ARM

var/spack/repos/builtin/packages/hpctoolkit/package.py
Add version for 'gpu' and variant for 'cuda'.  These are currently
available from the 'master-gpu' branch.
Add conflicts for old versions of gcc.
=> hpctoolkit: add version gpu and variant cuda

var/spack/repos/builtin/packages/jdk/package.py
`JDK 12.0.1_12` is no longer available for download, so I add `JDK 12.0.2_10`.
=> jdk: Add JDK 12.0.2_10

var/spack/repos/builtin/packages/tealeaf/package.py
tealeaf add -march=native for gcc.
This patch avoid -march=native and -mmtune=native on aarch64 and gcc 5 or before.
=> tealeaf: Don't add -march=native on ARM and gcc 5.x or before.

lib/spack/spack/cmd/buildcache.py, lib/spack/spack/environment.py, lib/spack/spack/hash_types.py, lib/spack/spack/spec.py, lib/spack/spack/spec_list.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/test/cmd/install.py, lib/spack/spack/test/spec_dag.py, lib/spack/spack/test/spec_yaml.py
@tgamblin 
Environments currently stores the full spec dag (including build dependencies) but indexes by dag hash, which excludes build dependencies. This can lead to reference errors for example given:
```
X-[L]->Y
X-[B]->Z1
Y-[B]->Z2
```
This PR
* Updates specs to track dag hashes both with and without build dependencies
* Updates the lockfile format to index based on the full dag hash (including build deps)
* Automatically updates older lockfiles to newer ones (where the indices are hashes based on the full dag)
=> Allow different instances of build deps in environment

var/spack/repos/builtin/packages/cmake/package.py
This is a follow-up to #11839, which I merged prematurely.
See https://github.com/spack/spack/pull/11839#issuecomment-512863141
=> cmake: Move cxx11 flags for fujitsu into the flag_handler method

var/spack/repos/builtin/packages/ucx/package.py
https://github.com/openucx/ucx/releases/tag/v1.6.0
Released 2019-07-17
```
dantopa@cn2037:pr-update-ucx.spack $ date
Mon Jul 22 17:04:14 MDT 2019
```
```
dantopa@cn2037:pr-update-ucx.spack $ pwd
/scratch/users/dantopa/repos/spack/pr-update-ucx.spack
```
```
dantopa@cn2037:pr-update-ucx.spack $ spack find -ldf ucx
==> 2 installed packages
```
```
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
w7fp4n6    ucx@1.6.0%gcc
tt2hkol        ^numactl@2.0.12%gcc
srhy7ry        ^rdma-core@20%gcc
kvgvhpv            ^libnl@3.3.0%gcc
```
```
-- linux-rhel7-ppc64le / gcc@4.8.5 ------------------------------
cji3ce7    ucx@1.6.0%gcc
pmgndwh        ^numactl@2.0.12%gcc
qymrwx6        ^rdma-core@20%gcc
2263pm5            ^libnl@3.3.0%gcc
```
=> Add UCX 1.6.0

var/spack/repos/builtin/packages/font-util/package.py
This fixes the following post install error on systems where autoreconf and aclocal are not available:
> 0dpi-1.0.3.tar.gz
==> Created stage in /home/marlin/tmp/spack-font-util/spack/var/spack/stage/resource-font-bh-lucidatypewriter-100dpi-q3hfsdfvovwl5i6757tgiesw5z4tfrhn
==> Moving resource stage
source : /home/marlin/tmp/spack-font-util/spack/var/spack/stage/resource-font-bh-lucidatypewriter-100dpi-q3hfsdfvovwl5i6757tgiesw5z4tfrhn/spack-src/
destination : /home/marlin/tmp/spack-font-util/spack/var/spack/stage/font-util-1.3.1-q3hfsdfvovwl5i6757tgiesw5z4tfrhn/spack-src/font-bh-lucidatypewriter-100dpi/font-bh-lucidatypewriter-100dpi-1.0.3
==> No patches needed for font-util
==> Building font-util [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> …
=> font-util: add missing autoconf automake dependencies

var/spack/repos/builtin/packages/ncurses/package.py
Fixes #11369
ncurses build system respects the $TERMINFO environment variable for the location of terminfo database. We need to unset this variable to keep the database inside the Spack install tree.
=> ncurses: remove TERMINFO from build env

lib/spack/spack/hash_types.py, lib/spack/spack/spec.py
Fixes #12091 
We were failing to cache hashes internally in the `Spec.to_node_dict` method, causing performance issues.
On develop, before this PR:
```
$ time spack stage r-rminer
…
real    3m35.715s
user    3m29.394s
sys    0m1.393s
```
With this PR:
```
$ time spack stage r-rminer
...
real    0m8.735s
user    0m8.166s
sys    0m0.473s
```
Both timings are with the code already staged.
=> hashing: fix caching of dependency hashes in to_node_dict

var/spack/repos/builtin/packages/ioapi/package.py
New package for IOAPI.
So far only works on GNU/Linux.  
I've posted on the [mailing list](https://groups.google.com/forum/#!topic/spack/R6orWxLCtfg) about adding logic for other architectures supported by upstream, but I don't have exotic hardware to test anyway besides `linux x86_64`, so I figured I would send the working version with my architecture.
=> ioapi: add version 3.2

lib/spack/spack/concretize.py
Provide better error message when matching externals are found for package marked not buildable
Now, the entire spec is in the message.
=>  error messages: include whole spec for "no externals found" message

var/spack/repos/builtin/packages/libfabric/package.py
`libfabric` 1.8 (https://github.com/spack/spack/pull/11918) has integrated Amazon-developed Elastic Fabric Adapter (EFA) (https://aws.amazon.com/about-aws/whats-new/2019/07/elastic-fabric-adapter-officially-integrated-into-libfabric-library/). 
This pull request adds `efa` fabric to the spack package description allowing EFA-enabled `libfabric` to be installed via spack:
```
spack install libfabric fabrics=efa
```
=> libfabric: add EFA fabric

var/spack/repos/builtin/packages/nanoflann/package.py
nanoflann add -mtune=native for gcc.
This patch avoid -march=native and -mmtune=native on aarch64 and gcc 5 or before.
=> nanoflann: Don't add -mtune=native on ARM and gcc 5.x

var/spack/repos/builtin/packages/isaac-server/arm.patch, var/spack/repos/builtin/packages/isaac-server/package.py
isaac-server add -march=native for gcc.
This patch avoid -march=native and -mmtune=native on aarch64 and gcc 5 or before.
=> isaac-server: Don't add -march=native on ARM and gcc 5.x or before.

var/spack/repos/builtin/packages/rocksdb/package.py
rocksdb add -march=native for gcc.
This patch avoid -march=native on aarch64 and gcc 5 or before.
=> rocksdb: Don't add -march=native on ARM and gcc 5.x or before.

lib/spack/spack/test/environment_modifications.py, lib/spack/spack/util/environment.py
fixes #12085
The bug reported in #12085 stemmed from a name clash among variables, introduced during the refactor in #10753 and not caught by unit tests and reviews. This PR fixes the clash and adds a unit test to avoid regressions.
=> Fixed a name clash in the 'from_environment_diff' function

var/spack/repos/builtin/packages/cmake/package.py
I noticed that there is mistake of flag's name on following pullreq. So, I fixed cxx98flag's name, and succeeded installing cmake.
Referenced: cmake: Move cxx11 flags for fujitsu into the flag_handler method #12056
=> cmake: fix cxx98flag's name

var/spack/repos/builtin/packages/c-blosc/package.py
While the c-blosc library compiles with icc some of the c-blosc tests do
not. Disable the tests so that the spack build can continue.
=> Do not build c-blosc test if intel in spec

var/spack/repos/builtin/packages/rapidjson/arm.patch, var/spack/repos/builtin/packages/rapidjson/package.py
rapidjson add -march=native for gcc.
But gcc on aarch64 is supported -march=native on gcc version 6:
This patch avoid -march=native on aarch64 and gcc 5 or before.
=> rapidjson: Don't add -march=native on ARM and gcc 5.x or before.

var/spack/repos/builtin/packages/nnvm/cmake2.patch, var/spack/repos/builtin/packages/nnvm/package.py
nnvm tests -std=c++0x and -msse2 flags.
But ignore the test and always add these flags.
In the PR, These flags is  added only if the test succeeds.
=> nnvm: cmake bug is fixed.

var/spack/repos/builtin/packages/perl/package.py
・`PerlPackage` uses setting information in `config_heavy.pl` for generating `Makefile` from `Makefile.PL`.
・`spack_cflags` specified when installing`PerlPackage` doesn't take in `Makefile`.
So, I fixed the `perl` package file so that `spack_cflags` are taken in `config_heavy.pl` when installing `perl`.
=> Perl take in flags

var/spack/repos/builtin/packages/freetype/package.py
Freetype-2.8 and above use __builtin_shuffle which is not supported by
icc.
=> Add conflicts statement to freetype for icc

var/spack/repos/builtin/packages/py-absl-py/package.py
I needed to add py-setuptools to get py-absl-py to build.
=> Add py-setuptools as a build dependency for py-absl-py

lib/spack/spack/test/install.py
Quick additions to increase test coverage of build-related exceptions based on lack of coverage revealed in #11981 .
=> tests: Test install of unconcretized spec

lib/spack/spack/cmd/maintainers.py, lib/spack/spack/test/cmd/maintainers.py, share/spack/spack-completion.bash, var/spack/repos/builtin.mock/packages/maintainers-1/package.py, var/spack/repos/builtin.mock/packages/maintainers-2/package.py
We don't currently make enough use of the maintainers field on packages, though we could use it to assign reviews.
Here are some examples:
```console
$ spack maintainers --by-user ax3l
adios         isaac-server   mpark-variant  py-adios              xtensor
adios2        jansson        mpilander      py-openpmd-validator  xtensor-python
cuda-memtest  libsplash      nlohmann-json  py-pybind11           xtl
gearshifft    libwebsockets  openpmd-api    rmlab
isaac         mallocmc       pngwriter      xsimd
$ spack maintainers adios
ax3l
$ spack maintainers dealii
davydden  jppelteret
$ spack maintainers --by-user jppelteret
dealii
$ spack maintainers --all | head -10
adios: ax3l
adios2: ax3l, chuckatkins
albany: gahansen
alquimia: balay, smolins
amrex: asalmgren, mic84
ascent: cyrush …
```
=> new command: `spack maintainers` queries package maintainers

var/spack/repos/builtin/packages/gdal/package.py
add v2.4.2 which is confirmed to compile successfully for default variant options.
=> gdal: added versions 2.4.2 and 3.0.1

var/spack/repos/builtin/packages/cmake/cmake-revert-findmpi-link-flag-list.patch, var/spack/repos/builtin/packages/cmake/package.py
See https://gitlab.kitware.com/cmake/cmake/issues/19516
Replaces #12121 
Fixes #12120
=> cmake: Add a patch to revert a findmpi regression

etc/spack/defaults/packages.yaml
Makes OpenJDK the default over JDK because JDK is now a licensed product that is not freely available.  Having JDK as default broke builds of people who didn't even care about Java (eg: R).
=> Make OpenJDK the default

lib/spack/spack/hooks/licensing.py
It looks like https://github.com/spack/spack/commit/0aed3bcea676a9df4a5c1c26a9a5ca7151d85215 causes the editor process to become defunct on exit when updating the license file. This was reported in #11691. This reverts to using Spack's Executable instead of execv when updating a license file.
=> fix defunct editor exit in #11691

var/spack/repos/builtin/packages/xsdk/package.py
so add a variant to disable it on older compiler builds
This is triggered by #11677
cc: @jthies
=> xsdk: phist has a conflict with gcc version <= gcc-4.9.1

var/spack/repos/builtin/packages/graphviz/package.py
- patch to build with qt5, enabling gvedit to build
- two patches to compile graphviz with icc
=> Patches for graphviz

var/spack/repos/builtin/packages/googletest/package.py
If +pthreads is specified, googletest actually gets build without
pthreads support and vice versa.
If pthreads is not available, googletest should detect it itself which
is why "enabling" pthreads in case of ~pthreads does not seem to cause
any error.
=> googletest: Fix reversed +pthreads option

var/spack/repos/builtin/packages/python/package.py
Builds for me on macOS 10.14.5 with Clang 10.0.1.
Also added myself as a maintainer.
=> Add Python 3.7.4

var/spack/repos/builtin/packages/font-util/package.py
Hi,
Just some small fixes for the font-util package:
1. Remove duplicated dependencies: cosmetic change.
2. Fix path handling for font resources: avoid doing nonsensical `join_path` like `join_path('encodings', '/tmp/.../spack-stage/spack-stage-1g54sz/spack-src/encodings/encodings-1.0.4')`.
Rémi
=> Small fixes for font-util package

var/spack/repos/builtin/packages/libxc/configure_add_fj.patch, var/spack/repos/builtin/packages/libxc/package.py
- Fujitsu compiler doesn't recognized by configure, so linker flags were not set.
So, I added a branch for setting of the Fujitsu compiler to `configure`.
=> libxc: Make configure recognize Fujitsu compiler

var/spack/repos/builtin/packages/adios2/cmake-update-findmpi.patch, var/spack/repos/builtin/packages/adios2/package.py
This patch fixes some integration issues with downstream cmake-based projects depending on adios2 getting broken MPI configurations.
See https://github.com/ornladios/ADIOS2/pull/1632
=> adios2: Patch findmpi for downstream issues.

var/spack/repos/builtin/packages/libuuid/package.py, var/spack/repos/builtin/packages/python/package.py
Building Python with `+uuid` currently requires the Spack-built `libuuid` package. However, the vanilla `libuuid` is incompatible with Apple's frameworks. This results in build failures in Python 2.7 (since that version of Python uses Carbon, which also includes libuuid), as well as in code that's downstream of Python (such as py-matplotlib, which includes an `osx` backend).
The commit message documents the error messages for system/compiler versions:
```
MacOS version 10.14.5
Xcode 10.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
```
but the final error message is always:
```
/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
```
because `uuid_string_t` is defined *only* in Apple's `uuid.h` and not in Spack's.
=> Prevent conflicts between libuuid and Apple Cocoa Framework on Mac

var/spack/repos/builtin/packages/fmt/package.py
Installing fmt 5.3.0 is failing due to the out-dated checksum:
```
==> Fetching https://github.com/fmtlib/fmt/releases/download/5.3.0/fmt-5.3.0.zip
[91m==> Error: ChecksumError: sha256 checksum failed for /usr/local/var/spack/stage/fmt-5.3.0-2gwik4qnlccthrcaqjoa6mrvq3u54vnh/fmt-5.3.0.zip
Expected 2ba1469c1f7677e70cb32bcd7dd0907e6952e16a161f07e05c7ffa388643b607 but got 4c0741e10183f75d7d6f730b8708a99b329b2f942dad5a9da3385ab92bb4a15c
```
=> Update checksum of fmt 5.3.0

var/spack/repos/builtin/packages/draco/package.py
Also:
* Update the recipe to track dependency requirements a bit more closely.
* Alphabetically sort the `depends_on` and `variant` lists.
* Only build the tests if requested.
=> Add a new version (7.2) of draco.

var/spack/repos/builtin/packages/lammps/package.py, var/spack/repos/builtin/packages/ncbi-toolkit/package.py, var/spack/repos/builtin/packages/r-tiff/package.py, var/spack/repos/builtin/packages/vigra/package.py, var/spack/repos/builtin/packages/virtualgl/package.py, var/spack/repos/builtin/packages/vtk/package.py
This prevents conflicts between descendents that depend on an unintentional
arbitrary jpeg implementation.
=> Use *virtual* jpeg package for package dependencies

var/spack/repos/builtin/packages/py-torch/package.py
Successfully builds for me on macOS 10.14.5 with Clang 10.0.1.
I renamed the package to `py-torch` to be consistent with the PyPI name.
=> Add PyTorch 1.1.0

var/spack/repos/builtin/packages/py-scipy/package.py
Successfully builds on macOS 10.14.5 with Clang 10.0.1.
This version of scipy drops Python 2 support.
=> Add scipy 1.3.0

lib/spack/spack/build_systems/intel.py
Packages that require the MPI compiler wrappers to be in the PATH previously failed with `intel-mpi` due to Intel's arcane directory structure.
The `intel` build system now fixes this by explicitly adding the `bin` path for the MPI compiler wrappers to its MPI-dependents environment.
=> intel: Add mpicc wrapper bindir to dependent env

var/spack/repos/builtin/packages/opengl/package.py
macOS comes with OpenGL 2.1. With this PR, I can add OpenGL as an external package and Spack will use it as long as there are no version requirements.
=> OpenGL always provides gl

var/spack/repos/builtin/packages/cmake/package.py
* related to #12151 
* fixes #12181
Not sure why the checksum changed.  Does this PR require checking in with the upstream project to see if there is an explanation?
@chuckatkins
=> update cmake 3.15.1 checksum

var/spack/repos/builtin/packages/llvm/package.py
By default the LLVM thread sanitizer does not handle OpenMP threading very well. This option enables capability in the thread sanitizer to help find data races much easier in OpenMP applications.
=> Add variant to LLVM to enable libomp thread sanitizer capability

var/spack/repos/builtin/packages/py-pytest-isort/package.py
Installs fine for me on macOS 10.14.5 with Clang 10.0.1.
=> Add py-pytest-isort package

var/spack/repos/builtin/packages/python/package.py
Python-3.6.7 and up do not build with the Intel compiler
- https://bugs.python.org/issue35473
- https://bugs.python.org/issue37415
=> Add conflicts statement for Python-3.6.7+ and Intel compiler

var/spack/repos/builtin/packages/py-ipython/package.py, var/spack/repos/builtin/packages/py-numpy/package.py, var/spack/repos/builtin/packages/qt/package.py
Previously, we were doing string to int comparison like `(1, 3) > ('1', '2')`. This is incredibly buggy:
```python
$ python2
>>> '10' > 9
True
>>> 10 > '9'
False
>>> '9' < 10
False
>>> 9 < '10'
True
```
Also, this does not work at all in Python 3. You get the following error message when trying to install `qt@4 platform=darwin`:
```
==> Error: TypeError: '>=' not supported between instances of 'str' and 'int'
```
This PR makes use of the `Version` class for version comparison.
=> Use Version object for version comparison

lib/spack/docs/tutorial_environments.rst
Also renames the section to "Environments Tutorial"
=> Typo fixes in Environments Tutorial

var/spack/repos/builtin/packages/catalyst/package.py
Bug introduced by  #11662
Fixes #12065
=> catalyst: Fix paths used for intermediate code generateion

var/spack/repos/builtin/packages/simulationio/package.py
Looks like we finally have Python 3 support: https://github.com/eschnett/SimulationIO/pull/115
@eschnett can you test this?
=> Add SimulationIO 9.0.1

var/spack/repos/builtin/packages/cmor/package.py
It's unclear when CMOR added Python 3 support, but their [circleci config file](https://github.com/PCMDI/cmor/blob/master/.circleci/config.yml) tests Python 3, and [conda](https://anaconda.org/PCMDI/cmor/files) has binaries for Python 3.
=> Add CMOR 3.4.0

var/spack/repos/builtin/packages/hpgmg/package.py
hpgmp add -mcpu=native for gcc.
This patch avoid -march=native on aarch64 and gcc 5 or before.
=> hpgmp: Don't add -mcpu=native on ARM and gcc 5.x or before.

var/spack/repos/builtin/packages/libxsmm/package.py
Introduced shared variant, which builds shared library in addition to the static library. Build header-only variant in addition to library (header-only is just about installing an additional folder). Perform only an additional install-step if generator is requested (and additional make-call as generator is built by default). Streamlined help-line of each variant.
=> LIBXSMM: v1.13, build shared library, and avoid fractured variants

var/spack/repos/builtin/packages/gromacs/package.py
This PR adds gromacs@4.5.5 which will benifit users who are stick to outdated version. It has been built successfully against GCC@5.4.0 on CascadeLake platform with
``$ spack install gromacs@4.5.5+mpi %gcc@5.4.0 ^openmpi ^fftw+mpi simd=avx512``
=> Add gromacs@4.5.5 .

var/spack/repos/builtin/packages/bsseeker2/package.py
I see no evidence that bsseeker2 does not support Python 3. The [system requirements](https://github.com/BSSeeker/BSseeker2#3-system-requirements) say Python 2.6+, and the [bioconda package](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bs-seeker2/meta.yaml) does not restrict things to Python 2.
=> Allow bsseeker2 to build with Python 3

var/spack/repos/builtin/packages/eccodes/package.py
Looks like Python 3 support was finally added for eccodes: https://confluence.ecmwf.int/display/ECC/Python+3+interface+for+ecCodes
@skosukhin can you test this?
=> Add eccodes 2.13.0

var/spack/repos/builtin/packages/magics/package.py
Unclear when Python 3 support was added, but the [installation guide](https://confluence.ecmwf.int/display/MAGP/Installation+Guide) says Python 2.7 and 3.X are both supported. Also, as of Magics 4.0.0, the Python library is now a separate package: https://confluence.ecmwf.int//display/MAGP/Magics
This PR has not been tested in any way.
=> Add Magics 4.1.0

var/spack/repos/builtin/packages/py-cairocffi/package.py
Installs fine, although the unit tests don't pass.
Depends on #12160
=> Add py-cairocffi package

var/spack/repos/builtin/packages/py-matplotlib/package.py
This PR overhauls the `py-matplotlib` package.
Depends on #12157, #12161, #12163
=> Overhaul matplotlib backend support

var/spack/repos/builtin/packages/py-pandas/package.py
Haven't been able to test this yet as the `numexpr` build is broken.
This version of pandas drops Python 2 support.
=> Add pandas 0.25.0

var/spack/repos/builtin/packages/genomefinisher/package.py
Currently `openjdk` is Prioritized than `jdk` as `java` dependency. So I fixed to use a `java` virtual dependency name when specifying package by `spec`.
=> genomefinisher: change package name to java from jdk.

lib/spack/docs/conf.py
When I try to build the docs with the latest version of Sphinx, I see the following deprecation warning:
```
/Users/Adam/spack/lib/spack/docs/conf.py:94: RemovedInSphinx30Warning: app.override_domain() is deprecated. Use app.add_domain() with override option instead.
sphinx.override_domain(PatchedPythonDomain)
```
This PR fixes that. It also sets the minimum required version of Sphinx to 1.8, which is the version where the `override` option was added to `add_domain()`: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_domain
=> Fix Sphinx deprecation warning when building docs

lib/spack/spack/cmd/env.py
Add the environment name to the error message shown when trying to remove an activated environment.
=> Print environment name when removing active env

var/spack/repos/builtin/packages/igvtools/package.py
Currently `openjdk` is Prioritized than `jdk` as `java` dependency. So I fixed to use a `java` virtual dependency name when specifying package  by `spec`.
=> igvtools: change package name to java from jdk.

var/spack/repos/builtin/packages/jsoncpp/package.py
By default, jsoncpp will build and execute tests during its build process. This fails on some platforms that use cross-compiling (i.e. compilers used by spack are actually wrappers for cross-compiling to the target hardware). This PR adds `-DJSONCPP_WITH_TESTS=OFF` so that jsoncpp doesn't build its tests.
=> Preventing jsoncpp from building tests

var/spack/repos/builtin/packages/launchmon/launchmon-char-conv.patch, var/spack/repos/builtin/packages/launchmon/package.py
There are build errors in the launchmon package with newer gcc compilers:
>      272    lmon_coloc_spawner.cxx: In member function 'bool spawner_coloc_t::d
>             o_frontend()':
>   >> 273    lmon_coloc_spawner.cxx:125:12: error: invalid conversion from 'char
>             ' to 'char*' [-fpermissive]
>      274       lmonpl = '\0'; /* ending null */
The upstream launchmon has been fixed, but a new version has not been released. This patch applies the fix to allow launchmon 1.0.2 to build OK in Spack.
=> patch launchmon to fix char * conversion error

var/spack/repos/builtin/packages/mount-point-attributes/mpa_type_conversion.patch, var/spack/repos/builtin/packages/mount-point-attributes/package.py
This patch resolves this build error:
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I.. -I.. -g -O2 -MT libmpattr_la-MountPointAttr.lo -MD -MP -MF .deps/libmpattr_la-MountPointAttr.Tpo -c MountPointAttr.C -fPIC -DPIC -o .libs/libmpattr_la-MountPointAttr.o
MountPointAttr.C:133:1: error: narrowing conversion of '-1' from 'int' to 'short unsigned int' inside { } [-Wnarrowing]
};
^
MountPointAttr.C:133:1: error: narrowing conversion of '-1' from 'int' to 'short unsigned int' inside { } [-Wnarrowing]
The upstream MPA source will be updated with this PR https://github.com/LLNL/MountPointAttributes/pull/4.
=> mpa: fix package build error with a patch

var/spack/repos/builtin/packages/unzip/package.py
Fixes #12007.
The Cray cc wrappers don't handle the -s flag (strip) cleanly, It's
not essential to strip the binary, so just remove the flag on Cray.
Note: the default build on Cray is for the back end and the unzip
binary won't run on the front end.  To build for FE, use something
like arch=cray-fe-x86_64.
----------
As I mentioned in #12199, the way I wrote this, this removes the `-s`
flag on Cray.  If you really wanted to strip the binary, there is
another one-line `filter_file` to put `-s` on `LFLAGS1` which works.
But I'd just as soon not strip the binary.  The zip package uses the
same Makefile except without -s, and I'd rather follow their example.
All five binaries combined are less than 1 meg.
ping @mamelara @jrood-nrel  @chuckatkins
=> unzip: fix build for cray back-end

var/spack/repos/builtin/packages/py-matplotlib/package.py
Defines a missing variable needed to build py-matplotlib.
=> Fix py-matplotlib build (#12230)

var/spack/repos/builtin/packages/mysql/package.py
* New versions:
* 8.0.16
* 5.7.26
* 5.6.44
* Perl is also a build-time dependency for <8.0.
* Special measures to allow use of dtrace to be successful when Python is in the dependency tree.
=> mysql: New versions, add conflicts, cope with use of dtrace.

var/spack/repos/builtin/packages/g4abla/package.py, var/spack/repos/builtin/packages/g4emlow/package.py, var/spack/repos/builtin/packages/g4ensdfstate/package.py, var/spack/repos/builtin/packages/g4ndl/package.py, var/spack/repos/builtin/packages/g4neutronxs/package.py, var/spack/repos/builtin/packages/g4photonevaporation/package.py, var/spack/repos/builtin/packages/g4pii/package.py, var/spack/repos/builtin/packages/g4radioactivedecay/package.py, var/spack/repos/builtin/packages/g4realsurface/package.py, var/spack/repos/builtin/packages/g4saiddata/package.py, var/spack/repos/builtin/packages/g4tendl/package.py
Previously I had relied on the using the extracted directory name. This was changed with https://github.com/spack/spack/commit/16530f84be04b8466769b9b74fe920d67006b988
Now the install directory paths are explicitly names.
=> Geant4 data packages: Set the install path name explicitly.

var/spack/repos/builtin/packages/bolt/package.py
Fixes #12060 (per wspear).
This change is needed for minimal container environments.
=> packages: Add autotools dependencies to bolt

var/spack/repos/builtin/packages/adios2/cmake-update-findmpi.patch
This addresses a specific issue with 3.11.x compatibility
https://github.com/ornladios/ADIOS2/pull/1654
=> adios2: Fix backwards compatibility version logic for FindMPI

var/spack/repos/builtin/packages/glib/package.py, var/spack/repos/builtin/packages/py-pygobject/package.py, var/spack/repos/builtin/packages/py-pygobject/pygobject-3.28.3-setup-py.patch
Packages that link to glib were also picking up -lintl from glib's glib-2.0.pc file. However, packages such as py-pygobject were  bypassing spack's compiler wrapper for linking and thus not finding the gettext library directory. The patch below explitly adds the appropriate -L path.
This fixes #9992.
=> fix glib dependency build fixes #9992

var/spack/repos/builtin/packages/liggghts/package.py
This package produces a single executable, `liggghts`.  I'm not a domain expert in finite particle analysis and the only runtime verification was running `liggghts -help` on that executable.  
I don't know whether the CI tests all variant combinations.  The `profile` flag has always been disabled.  I've tested combinations of:
|`mpi` | `debug` | `jpeg` | `gzip`|
|---|---|---|---|
|-|-|-|-|
|+|-|-|-|
|-|+|-|-|
|+|+|-|-|
|+|+|+|+|
|+|-|+|+|
Some functionality in the `Makefile.user_default` template could not be included because that is part of upstream's premium service.
=> liggghts: added version 3.8.0

var/spack/repos/builtin/packages/ginkgo/package.py
This fixes error with multiple builds - when they use the cached tarball.
cc: @tcojean
=> ginkgo: fix branch -> commit for @1.0.0. Also add variant: develtools

var/spack/repos/builtin/packages/hpcviewer/package.py
We (Rice HPCToolkit) issued a re-release of hpcviewer 2019.07 due to
some serious bugs.
----------
I'd like to say, "Sorry, this won't happen again," but what are the
odds.  :-)
=> hpcviewer: update sha sums for version 2019.07

var/spack/repos/builtin/packages/dialign-tx/package.py
dialign-x use SSE related compile options.
But these options is not support ARM.
This PR remove these options when target is ARM.
=> dialign-tx: build on ARM.

var/spack/repos/builtin/packages/raxml/nox86.patch, var/spack/repos/builtin/packages/raxml/package.py
* xmmintrrin.h is included x86 only.
* Add makefiles for non-x86 hosts.
* mpicc in Makefiles is replaced spacks mpi compile command.
* variant check is rewite with satisfies.
=> raxml: compile on non-x86 hosts.

var/spack/repos/builtin/packages/c-blosc/package.py, var/spack/repos/builtin/packages/c-blosc/test_forksafe.patch
- Update c-blosc to 1.17.0
- Add patch to build test_forksafe for versions 1.15.0 through 1.17.0
when compiled with the Intel compiler.
- Remove code that turned off building the test with the Intel compiler
=> Update c-blosc and fix building tests with icc

var/spack/repos/builtin/packages/parsimonator/nox86.patch, var/spack/repos/builtin/packages/parsimonator/package.py
To build parsomonnator on non x86_64 host, I changed as follows:
* axml.c was include xmmintrin.h when host is not powerPC. I changed include only host is x86_64.
* Add Makefile.nosse for non-x86 hosts.
* sse variant change to False.
* Add check sse and avx variant dose not set non-x86 hosts.
=> parsimonator: Enable build on non x86_64 hosts.

var/spack/repos/builtin/packages/py-mpi4py/package.py
py-mpi4py fails to build on NERSC Cori when using Cray-MPICH with the error:
```
>> 140    /global/gscratch1/sd/tconnors/spack-stage/spack-stage-zJSOhu/src/_configtest.c:6: undefined refere
nce to `MPI_Init'
>> 141    /usr/bin/ld: /global/gscratch1/sd/tconnors/spack-stage/spack-stage-zJSOhu/src/_configtest.c:7: und
efined reference to `MPI_Finalize'
>> 142    collect2: error: ld returned 1 exit status
143    failure.
144    removing: _configtest.c _configtest.o
>> 145    error: Cannot link MPI programs. Check your configuration!!
```
However, it is able to build fine if using Spack built OpenMPI.
After checking the mpi4py documentation, it appears there is a build argument that needs to be added:
> If mpicc is not in your search path or the compiler wrapper has a different name, you can …
=> py-mpi4py: Added build argument for mpicc path

var/spack/repos/builtin/packages/vdt/package.py
* add simd variant and check target.
** default value is None, (current default is sse, but dose not build on other x86_64.)
* build on source directory before 0.3.8.
** https://github.com/dpiparo/vdt/releases/tag/v0.3.9
=> vdt: add simd variant

var/spack/repos/builtin/packages/py-flye/package.py
py-flye is included minimap2.
We need to set makefile variable to build minimap2 on ARM.
This PR set makefile variable to environment variable when build for ARM.
=> py-flye: change to build ARM.

var/spack/repos/builtin/packages/range-v3/fix-is_trivial.patch, var/spack/repos/builtin/packages/range-v3/gcc-compile-opt-check.patch, var/spack/repos/builtin/packages/range-v3/package.py
Resolves #11481.
* Incorporate as a patch upstream commit https://github.com/ericniebler/range-v3/commit/0c20dbf05973368339aeae0c4e106560e2dcf76b#diff-acb9169b4ccbac494ced5140d285a015 resolving problems with `-Wno-...` options not being understood by GCC.
* Incorporate as a patch upstream PR https://github.com/ericniebler/range-v3/pull/1202 fixing upstream issue https://github.com/ericniebler/range-v3/issues/1196.
* Compile tests only if we actually want to run them.
* Optionally compile documentation with a `+doc` variant.
* Add `+examples` and `+perf` variants to avoid unnecessary compilation of components usually not required for install.
* Add conditional build-only dependency on Boost when appropriate.
* Install docs, examples and performance tests if built (not part of upstream …
=> range-v3: Resolve installation issues with 0.5.0

var/spack/repos/builtin/packages/jube/package.py
This sets the default resource_manager to `none`. The previous default `slurm` was arbitrary and not setting the template directory if the user does not explicitly requests it is the better choice.
=> jube: set default resource manager to 'none'

lib/spack/spack/cmd/concretize.py, lib/spack/spack/cmd/install.py, lib/spack/spack/environment.py, lib/spack/spack/test/cmd/env.py
While rebasing #11372 I noticed that the `Environment.concretize` method changed signature in 0715b512a19d5d966f596559274ca7b8a3406701:
https://github.com/spack/spack/blob/0715b512a19d5d966f596559274ca7b8a3406701/lib/spack/spack/environment.py#L823
as a new argument `_display` got added. This argument seems to be used only in unit tests to switch off part of the code. To avoid: 
1. Using an argument to a function that starts with a leading underscore
2. Having code that is needed only for tests mixed with business logic
this PR extracts the logic to display specs into its own function. Client code is then responsible to make an additional call if it needs to display the result of concretization - and unit tests can simply skip that call.
=> Removed an argument to concretize that was there only for unit tests

var/spack/repos/builtin/packages/py-pyasn1/package.py
=> Add py-pyasn1 0.4.6

var/spack/repos/tutorial/packages/py-cachetools/package.py
=> Add py-cachetools package

var/spack/repos/tutorial/packages/py-pyasn1-modules/package.py
=> Add py-pyasn1-modules package

var/spack/repos/tutorial/packages/py-httplib2/package.py
=> Add py-httplib2 package

var/spack/repos/tutorial/packages/py-google-auth/package.py
=> Add py-google-auth package

var/spack/repos/tutorial/packages/py-google-auth-httplib2/package.py
=> Add py-google-auth-httplib2 package

var/spack/repos/tutorial/packages/py-google-api-python-client/package.py
=> Add py-google-api-python-client package

var/spack/repos/tutorial/packages/py-earthengine-api/package.py
=> Add py-earthengine-api package

var/spack/repos/tutorial/packages/py-uritemplate/package.py
=> Add py-uritemplate package

lib/spack/spack/operating_systems/cnl.py, lib/spack/spack/test/operating_system.py
Fixes #12187 
With this PR, Spack successfully detects the Cray OS version on Blue Waters:
```console
$ spack arch
cray-cnl5-interlagos
```
=> Fix CNL version detection

lib/spack/docs/environments.rst
Using `compilers:` with the "s" is an invalid config section and throws an error.
```python-traceback
File "spack/bin/spack", line 48, in <module>
File "/home/omsai/src/libkmap/spack/lib/spack/spack/main.py", line 633, in main
env = ev.find_environment(args)
File "/home/omsai/src/libkmap/spack/lib/spack/spack/environment.py", line 263, in find_environment
return Environment(env)
File "/home/omsai/src/libkmap/spack/lib/spack/spack/environment.py", line 534, in __init__
self._read_manifest(f)
File "/home/omsai/src/libkmap/spack/lib/spack/spack/environment.py", line 561, in _read_manifest
self.yaml = _read_yaml(f)
File "/home/omsai/src/libkmap/spack/lib/spack/spack/environment.py", line 402, in _read_yaml
validate(data, filename) …
```
=> Fix typo in config

.github/actions/add-maintainers-as-reviewers/Dockerfile, .github/actions/add-maintainers-as-reviewers/entrypoint.py
This adds a GitHub action that uses `spack pkg changed` and `spack maintainers` to figure out which packages changed and who their maintainers are in a PR.
Then it adds any maintainers to the PR as reviewers.
=>  actions: add maintainers as PR reviewers for their packages

var/spack/repos/builtin/packages/openpmd-api/package.py
When loading `openpmd-api` as a lib to build outside of spack or to build depending spack packages, the "CMake-PUBLIC" header-only library MPark.Variant must be available. Also, the `*Config.cmake` package must be able to find dependent libs if used.
More details in #2378. Avoids to always require `spack load -r openpmd-api`.
=> openPMD-api: pre-load depend libs

.travis.yml
Before this commit we were sending reports also for unit tests that were not collecting coverage data.
=> Avoid sending empty reports to codecov

var/spack/repos/builtin/packages/fltk/fix_compare_val.patch, var/spack/repos/builtin/packages/fltk/package.py, var/spack/repos/builtin/packages/fltk/type_cast.patch
Modifications to eliminate errors caused by variable type differences.
Referenced:
https://github.com/fltk/fltk/commits/master/src/Fl_Tree_Item.cxx
　-Fix return value test, as pointed out by Albrecht.
https://github.com/fltk/fltk/commits/master/test/menubar.cxx
　-Allow compilation with -std=c++11
　-Add missing cast (part of patch for STR #2813).
=> fltk: fix about variable types

lib/spack/spack/stage.py, lib/spack/spack/util/path.py
Previously, it was not possible to use environment variables or spack config variables in mirror paths. With this PR you can.
E.g. `mirrors.yaml`
```
mirrors:
my_mirror: $spack/../mirror
```
=> Make mirrors use spack environment expansions

var/spack/repos/builtin/packages/atlas/package.py, var/spack/repos/builtin/packages/libflame/package.py, var/spack/repos/builtin/packages/py-meep/package.py, var/spack/repos/builtin/packages/py-numpy/blas-lapack-order.patch, var/spack/repos/builtin/packages/py-numpy/package.py, var/spack/repos/builtin/packages/veclibfort/package.py
Fixes #3204
Fixes #5327
Fixes #6634
Fixes #7687
Fixes #8616
Closes #8817
Fixes #10361
Fixes #12237 
This PR makes the following changes:
Obviously, any big change to the numpy package, which has already gone through a lot of turmoil, will require extensive testing. Here are the platforms and configurations I would like to test before merging this:
```console
$ cat ./lib/python3.7/site-packages/numpy/distutils/site.cfg
[mkl]
libraries = mkl_rt
library_dirs = /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/lib:/usr/lib
rpath = /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/lib:/usr/lib
include_dirs = /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/include
$ otool -l $(find . -name '*.so') | sort | uniq
...
name /usr/lib/libSystem.B.dylib (offset 24)
name …
```
=> Overhaul numpy package

var/spack/repos/builtin/packages/graphviz/fix-quartz-darwin.patch, var/spack/repos/builtin/packages/graphviz/package.py
- Add quartz variant for macOS and necessary patches to get it working on newer systems
- Disable language bindings that simply emit spack errors
- Restrict Qt support to Qt4 (newer versions of Qt are silently ignored)
- The X11 error mentioned in the package (and not documented anywhere) no longer happens, and `/opt/X11` isn't guaranteed to exist
=> graphviz: Simplify package and add quartz support

var/spack/repos/builtin/packages/ncurses/package.py
Resolves #11932.
Move the PIC flags from CFLAGS on the configure line to the spack
compiler wrapper for ncurses.  The problem with the configure line for
autotools is that specifying CFLAGS sets the entire flags, thus
deleting the flags that configure would add itself.
By default, if CFLAGS is unspecified, then configure picks a sensible
default of `-g -O2`.  But adding `-fPIC` erases these and it ends up
building unoptimized.
----------
This patch is a simple and safe way of fixing the problem of building
ncurses unoptimized.  But this brings up two larger issues that affect
autotools in general.
(1) Autotools was designed to pass compiler flags via CFLAGS and
CXXFLAGS on the configure line.  You can either set these yourself, or
else leave them unspecified and then configure selects …
=> ncurses: fix pic and opt flags

var/spack/repos/builtin/packages/trilinos/package.py
Changes have been made to the STK package in Trilinos and I am now able to generalize STK for more than just Nalu. I removed the comments about Nalu. I also removed the explicit disabling of Seacas when `~exodus`.
=> Generalize STK package settings in Trilinos

lib/spack/spack/package.py
@becker33 
@scottwittenburg does this resolve the issue for you?
Fixes https://github.com/spack/spack/issues/12298
https://github.com/spack/spack/pull/11175 enabled installing compilers for dependencies but not for the root package (and in particular not for DAGs which consist of one package); this enables bootstrapping compilers for both types of DAGs
=> Enable compiler bootstrapping for single packages

lib/spack/spack/environment.py
Spack stacks drop invalid dependencies applied to packages by a spec_list matrix operation
Without this fix, Spack would raise an error if orthogonal dependency constraints and non-dependency constraints were applied to the same package by a matrix and the dependency constraint was invalid for that package. This is an error, fixed by this PR.
```
spack:
definitions:
- packages: [libelf, hdf5+mpi]
- compilers: ['%gcc']
- mpis: [^openmpi]
specs:
- matrix:
- $packages
- $compilers
- $mpis
```
=> stacks: fix conditional dependencies

lib/spack/docs/build_settings.rst
Whenever a compiler or package spec contains a version range, the `:` messes up our YAML parsing with an error message like:
```
==> Error: Error parsing yaml  in "/u/sciteam/stewart1/.spack/packages.yaml", line 4, column 20: found unexpected ':'
```
The solution is to wrap that spec in quotes.
=> Fix typo in yaml config docs

lib/spack/docs/getting_started.rst
It's no longer possible to parent compiler flags under paths:
```python-traceback
$ spack concretize -f
File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/bin/spack", line 48, in <module>
File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/main.py", line 633, in main
env = ev.find_environment(args)
File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 263, in find_environment
return Environment(env)
File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 534, in __init__
self._read_manifest(f)
File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 561, in _read_manifest
self.yaml = …
```
=> docs: fix compiler config

var/spack/repos/builtin/packages/openssl/package.py
Question: should we remove the 1.0.1 versions now that they are no longer supported? I don't want Spack responsible for security issues because we allowed people to use ancient openssl versions.
=> Add latest versions of openssl

lib/spack/spack/filesystem_view.py
Fixes #11980 
This is the simplest possible fix to the issue I raised in #11980. Currently, if you have an external package like `jdk` which happens to be extendable, and you install an extension for that package, it becomes impossible to install that package or its extensions if you don't have write access to that directory. For example, on macOS, JDK is installed to the system `/Library` directory. It looks like Spack is trying to create a file to keep track of which extensions are activated, but crashes because that is not possible.
Tested on Python 2 and 3.
=> Allow Spack to uninstall external extensions without permissions

var/spack/repos/builtin/packages/py-tables/package.py
I accidentally broke the `py-tables` package when I removed the `py-cython` dependency in #12172. The documentation says Cython isn't needed if you're installing from a tarball, but apparently it is needed.
=> Re-add py-cython dependency to py-tables

var/spack/repos/builtin/packages/guile/package.py
This pull request adds GNU Guile versions 2.2.1 through 2.2.6, inclusive.
`spack install guile +threads` fails on my machine, even for `guile@2.2.0`, so I have only tested `spack install guile ~threads`.
=> guile: add versions 2.2.1 through 2.2.6

var/spack/repos/builtin/packages/netcdf-cxx4/package.py
Installing version 4.3.0 required calling `autoreconf` to create the `configure` script.  Without the `m4` dependency the following error is hit:
https://github.com/spack/spack/blob/b4862be875dee58187a670e08c4d79f2b49f8cb9/lib/spack/spack/build_systems/autotools.py#L184-L186
This PR adds the `m4` dependency.
=> netcdf-cxx4: add m4 dep for call to autoreconf

var/spack/repos/builtin/packages/cube/package.py, var/spack/repos/builtin/packages/cubelib/package.py, var/spack/repos/builtin/packages/cubew/package.py, var/spack/repos/builtin/packages/opari2/package.py, var/spack/repos/builtin/packages/otf2/package.py, var/spack/repos/builtin/packages/scorep/package.py
Adding the new releases of Cube Tools, OPARI2, OTF2 and Score-P, which were released on August 1 and July 31 respectively.
=> Add new releases of Cube Tools, Opari2, OTF2, and Score-P

var/spack/repos/builtin/packages/hisea/package.py
hisea use -mpopcnt  compile options.
But these options is not support ARM.
This PR remove these options when target is ARM.
=> hisea: build on ARM.

lib/spack/spack/environment.py, lib/spack/spack/spec.py, lib/spack/spack/spec_list.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/test/spec_list.py, lib/spack/spack/variant.py
@mpbelhorn and @Paul-Ferrell reported a bug with Spack stacks for nested matrices.
The resulting error reads `dict object has no attribute 'startswith'`.
This PR resolves the error. There was no associated issue on github.
Also fixes a minor error in matrix concretization for variants with multi-word names (with dashes in the names) because that came up in the reproducer given to me by @Paul-Ferrell
=> Bugfix: nested matrices in spec lists

var/spack/repos/builtin/packages/hunspell/package.py
Hunspell depends on `gettext` (specifically, it requires the `autopoint` binary, which is in `gettext`), but this dependency is missing from the Spack `hunspell` package. This pull request adds this missing dependency, and also includes a triage fix for #12343 while waiting for PR #12344 to be merged.
=> bugfix: hunspell: add missing gettext dependency

var/spack/repos/builtin/packages/sdl2/package.py
* add dependency for libxext2.
* SSEMATH is off when target is aarch64.
* reformat comment for flake8.
=> sdl2: fix dependency for libxext and build on ARM

var/spack/repos/builtin/packages/libfive/package.py
This pull request adds the libfive solid modeling package. It depends weakly on #12333; some OSes package GNU Guile 2.2.1 or later, so this dependency could be installed in Spack via `packages.yaml` instead. However, for users that do not configure `packages.yaml` to register an installation of GNU Guile 2.2.1 or later, merging #12333 will be required.
=> Add new package: libfive@master

var/spack/repos/builtin/packages/py-numexpr/package.py
See https://github.com/pydata/numexpr/issues/340
I've been dealing with build errors with numexpr + MKL all week and I finally tracked down the problem. The PyPI tarball contains a `site.cfg` that overrides numpy's `site.cfg` and specifies MKL installation directories on Windows systems. The GitHub tarball does not contain this `site.cfg` and builds correctly.
=> py-numexpr: switch from PyPI to GitHub download

var/spack/repos/builtin/packages/moab/package.py, var/spack/repos/builtin/packages/moab/tools-492.patch
Our code currently relies on an older version of Moab which has errors that cause it to fail compilation on GCC 8. This patches MOAB to allow it to compile.
```
5 errors found in build log:
609      CXX      mbpart.o
610      CXX      quality.o
611      CXX      umr.o
612      CXX      merge.o
613      CXX      parread.o
614    mbpart.cpp: In function 'int main(int, char**)':
>> 615    mbpart.cpp:494:19: error: no match for 'operator<<' (operand types
are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'std::ostri
ngstream' {aka 'std::__cxx11::basic_ostringstream<char>'})
616             std::cerr << tmp_output_file << " : failed to write file."
<< std::endl;
617             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
618    mbpart.cpp:494:19: note: candidate: 'operator<<(int, int)' <built-i
n>
619 …
```
=> Fix build for moab 4.9.2 on gcc8

var/spack/repos/builtin/packages/py-retrying/package.py
=> Add py-retrying package

var/spack/repos/builtin/packages/py-pysmartdl/package.py
=> Add py-pysmartdl package

var/spack/repos/builtin/packages/py-pyperclip/package.py
=> Add py-pyperclip package

var/spack/repos/builtin/packages/py-pathlib/package.py
=> Add py-pathlib package

var/spack/repos/builtin/packages/py-oauth2client/package.py
=> Add py-oauth2client package

var/spack/repos/builtin/packages/py-googleapis-common-protos/package.py
=> Add py-googleapis-common-protos package

var/spack/repos/builtin/packages/py-google-resumable-media/package.py
=> Add py-google-resumable-media package

var/spack/repos/builtin/packages/py-google-cloud-storage/package.py
=> Add py-google-cloud-storage package

var/spack/repos/builtin/packages/py-google-cloud-core/package.py
=> Add py-google-cloud-core package

var/spack/repos/builtin/packages/py-google-api-core/package.py
=> Add py-google-api-core package

var/spack/repos/builtin/packages/py-gee-asset-manager/package.py
=> Add py-gee-asset-manager package

var/spack/repos/builtin/packages/py-clipboard/package.py
=> Add py-clipboard package

var/spack/repos/builtin/packages/nccl/package.py
Doesn't build for me, but neither did the previous version. 
See https://github.com/NVIDIA/nccl/issues/244 for the bug report.
=> Add NCCL 2.4.8-1

var/spack/repos/builtin/packages/precice/package.py
This PR
* adds support for the build system changes introduced by the adaptation of the xSDK installation policies,
* fixes some python related bugs discovered during the migration, and
* fixes unprecice cmake and eigen dependencies.
=> Add preCICE xSDK support
