spack/spack

var/spack/repos/builtin/packages/darshan-runtime/package.py
var/spack/repos/builtin/packages/darshan-util/package.py

* Add version 3.1.7
* Add develop branch (git master)

Darshan 3.1.7 and develop versions

---

var/spack/repos/builtin/packages/veloc/package.py

* Add veloc 1.1 version
* Add pdsh as a dependency for `master`

Update veloc preferred version to 1.1 and update dependency on master

---

var/spack/repos/builtin/packages/aom/package.py
var/spack/repos/builtin/packages/ffmpeg/package.py

Build of ffmpeg with aom library support.

ffmpeg with aom support

---

var/spack/repos/builtin/packages/trilinos/package.py

We needed this additional Trilinos component.  Added as an optional variant.

Add a trilinos variant for +shylu.

---

var/spack/repos/builtin/packages/python/package.py

(still exploring git workflows for working with other people)

bumped stable python versions

---

var/spack/repos/builtin/packages/py-espresso/package.py

py-espresso: added v4.0.2

---

var/spack/repos/builtin/packages/qmcpack/package.py

This is my second attempt to fix CMake weirdness associated with the compiler and flags. 
After some discussion with folks online and reviewing the documentation, I believe this is the right way to do it.

QMCPACK Compiler Wrapper Fix

---

var/spack/repos/builtin/packages/gdal/package.py

gdal: add new version 2.4.1

---

var/spack/repos/builtin/packages/parallel-netcdf/package.py

Add current release version 1.11.1

PARALLEL-NETCDF: New version 1.11.1

---

var/spack/repos/builtin/packages/netcdf/package.py

Update to latest release version 4.7.0

NETCDF: New version 4.7.0

---

var/spack/repos/builtin/packages/r-rjava/package.py

add new version. Seems to be fixing #9685

rJava new version

---

lib/spack/env/cc
lib/spack/spack/test/cc.py

Cribbed from
https://github.com/handyman5/homebrew/commit/44a38f9bb51ace892ca59104f531494bfdaad9a5

On macOS insert headerpad_max_install_names linker flag

---

var/spack/repos/builtin/packages/openblas/package.py

Signed-off-by: Janne Blomqvist <janne.blomqvist@aalto.fi>

openblas: Add version 0.3.6

---

var/spack/repos/builtin/packages/nut/package.py

Changes due to recent source update!

nut: fix nut build

---

var/spack/repos/builtin/packages/mesa/package.py

mesa: Add missing dependencies

---

var/spack/repos/builtin/packages/mercury/package.py

Clean up mercury package and add boostsys, shared variants
Use tarballs instead of git tags
Fix openpa dependency on gcc < 4.9
Fix boost dependency

Fix mercury package dependencies and use tarballs

---

var/spack/repos/builtin/packages/leveldb/package.py

Fixes #11267 
@fbudin69500 can you test this?

Add master branch of leveldb

---

var/spack/repos/builtin/packages/conduit/package.py
var/spack/repos/builtin/packages/cudnn/package.py
var/spack/repos/builtin/packages/hydrogen/package.py
var/spack/repos/builtin/packages/lbann/package.py
var/spack/repos/builtin/packages/nccl/package.py
var/spack/repos/builtin/packages/protobuf/package.py
var/spack/repos/builtin/packages/py-graphviz/package.py
var/spack/repos/builtin/packages/py-onnx/package.py
var/spack/repos/builtin/packages/py-protobuf/package.py
var/spack/repos/builtin/packages/py-texttable/package.py
var/spack/repos/builtin/packages/py-typing-extensions/package.py
var/spack/repos/builtin/packages/py-typing/package.py

Created new packages for necessary python packages.

Added support for new python front end to LBANN. 

---

var/spack/repos/builtin/packages/nut/package.py

From https://github.com/lanl/NuT/issues/2

nut: add v0.1.1

---

var/spack/repos/builtin/packages/py-python-utils/package.py

new python package. a dependency of pyroSAR

new python package: py-python-utils

---

var/spack/repos/builtin/packages/py-progressbar2/package.py

create new python package: a dependency of pyrosar

new python package progressbar2

---

var/spack/repos/builtin/packages/py-scoop/package.py

new python package: a dependency of pyroSAR

new package: py-scoop

---

var/spack/repos/builtin/packages/py-spatialist/package.py

new python package: py-spatialist 
"A Python module for spatial data handling"
a dependency of pyroSAR

new python package: py-spatialist

---

var/spack/repos/builtin/packages/py-pyrosar/package.py

new python package py-pyrosar: framework for large-scale SAR satellite data processing
depends on PRs #11427 #11421

new python package py-pyrosar

---

var/spack/repos/builtin/packages/r-rnoaa/package.py

depends on `r-crul` in #11459, `r-isdparser` in #11460

r-rnoaa: new package at 0.8.4

---

var/spack/repos/builtin/packages/r-taxizedb/package.py

depends on new version of `r-rmysql` in #11044

r-taxizedb: new package at 0.1.4

---

var/spack/repos/builtin/packages/r-phylostratr/package.py

depends on `r-rhmmer` in #11050, `r-taxizedb` in #11052, and `r-hoardr` in #11051 (and by extension the previous 10 PRs)
Sorry for the PR spam, getting this package in spack was quite a task.

r-phylostratr: new package

---

var/spack/repos/builtin/packages/likwid/package.py

Add latest two LIKWID releases

---

var/spack/repos/builtin/packages/kokkos/package.py

Add debug variant to kokkos

---

var/spack/repos/builtin/packages/cbtf-argonavis-gui/package.py
var/spack/repos/builtin/packages/cbtf-argonavis/package.py
var/spack/repos/builtin/packages/cbtf-krell/package.py
var/spack/repos/builtin/packages/cbtf-lanl/package.py
var/spack/repos/builtin/packages/cbtf/package.py
var/spack/repos/builtin/packages/openspeedshop-utils/package.py
var/spack/repos/builtin/packages/openspeedshop/package.py
var/spack/repos/builtin/packages/qtgraph/package.py

Update versions of openspeedshop and cbtf packages. Also, limit boost versions and fix a module environment variable setting problem (#11443)

Update versions of openspeedshop and cbtf packages.   Also, limit boost versions used.

---

var/spack/repos/builtin/packages/magma/package.py

New MAGMA was released and I tested it on x86 and IBM POWER

Add version 2.5.1-alpha1 of MAGMA

---

var/spack/repos/builtin/packages/gasnet/package.py

gasnet: 2019.3.0

---

var/spack/repos/builtin/packages/parsplice/package.py

Adds the ability to install the multisplice branch for parsplice.

added branch multisplice to the parsplice package

---

var/spack/repos/builtin/packages/py-joblib/package.py

Add latest version of joblib

---

var/spack/repos/builtin/packages/openmpi/package.py

Fix typo in MPI so name comment.

---

var/spack/repos/builtin/packages/vtk/package.py

Improves VTK package so that it better handles its GL dependencies.  In particular, it makes use of the recently added `gl` virtual dependency.

package vtk - improve gl handling

---

var/spack/repos/builtin/packages/py-cython/package.py

Add latest version of py-cython

---

var/spack/repos/builtin/packages/sl/package.py

New Package: sl

---

var/spack/repos/builtin/packages/catch/package.py

Add the latest Catch2 release.

Catch: 2.8.0

---

var/spack/repos/builtin/packages/precice/package.py

precice: add version 1.5.0

---

var/spack/repos/builtin/packages/aml/package.py

AML is a collection of building blocks for explicit memory management on
complex architectures.
https://xgitlab.cels.anl.gov/argo/aml
https://argo-aml.readthedocs.io/en/latest/

aml: new package - the aml memory management library.

---

var/spack/repos/builtin/packages/benchmark/package.py

Add Google Benchmark version 1.5.0

---

var/spack/repos/builtin/packages/lammps/package.py

For https://github.com/lammps/lammps/issues/1495

lammps: added v20190605

---

lib/spack/spack/compilers/cce.py
lib/spack/spack/compilers/pgi.py
lib/spack/spack/compilers/xl.py

Add extra logic for C std flags on PGI, XL, and Cray

---

var/spack/repos/builtin/packages/py-typesentry/package.py

New python package.
A dependency of #11604

new python package/py-typesentry

---

var/spack/repos/builtin/packages/flecsi/package.py

Fixed logic behind flecsi backends to not require legion for an mpi build and to better support required combinations.
Also made graphviz support and tutorial building optional

Fixed Flecsi Backend Dependencies

---

lib/spack/spack/test/conftest.py

Remove temporary mock configuration directory on session end.

tests: Remove mock configuration directory at session end

---

var/spack/repos/builtin/packages/py-pybind11/package.py

Add the latest 2.3.0 release and me as package maintainer.

pybind11: v2.3.0

---

var/spack/repos/builtin/packages/pdf2svg/package.py
var/spack/repos/builtin/packages/poppler/package.py

Fixes #11674. @23skdu can you test this?

Updates to poppler to get pdf2svg working

---

var/spack/repos/builtin/packages/intel-mpi/package.py
var/spack/repos/builtin/packages/intel-parallel-studio/package.py
var/spack/repos/builtin/packages/intel/package.py

This fully follows the template from @lee218llnl using #10835.

Add intel 19.0.4

---

var/spack/repos/builtin/packages/hdf/package.py

One of the unit tests failed for unknown reasons. I contacted the developers.

Add HDF 4.2.14

---

var/spack/repos/builtin/packages/jackcess/package.py

Update URL for older version of jackcess

---

var/spack/repos/builtin/packages/cowsay/package.py

- A program that generates ASCII pictures of a cow with a message.
- Spack is missing this important package.
- This is used by @ArangoGutierrez the ISC19 Singularity tutorial, so we clearly need it in Spack.
```
$ cowsay spack needs more moo
______________________ 
< spack needs more moo >
---------------------- 
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```

cowsay: new package

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/fetch_strategy.py
lib/spack/spack/stage.py

Basic source and packaging documentation updates.

docs: updates for `stage.source_path`

---

var/spack/repos/builtin/packages/claw/package.py

@ax3l or @alalazo Can you have a quick look at this PR?

claw: Add version 1.2.2 and 1.2.3 to the package

---

var/spack/repos/builtin/packages/ibmisc/package.py

Restrict ibmisc to proj@:4

---

var/spack/repos/builtin/packages/pism/package.py

Restrict pism to proj@:4

---

var/spack/repos/builtin/packages/saga-gis/package.py

See https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status and https://sourceforge.net/p/saga-gis/bugs/271/

PROJ.6 not yet supported in SAGA-GIS

---

var/spack/repos/builtin/packages/r-rgdal/package.py

See https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status

r-rgdal does not yet support PROJ.6

---

var/spack/repos/builtin/packages/libspatialite/package.py

See https://github.com/spack/spack/pull/11730#issuecomment-502546361
@neilflood

Restrict libspatialite to proj@:5'

---

var/spack/repos/builtin/packages/cinch/package.py
var/spack/repos/builtin/packages/flecsi/package.py

Added spackage for Cinch build system and updated flecsi spackage to use the externally provided Cinch

Added Cinch Spackage

---

var/spack/repos/builtin/packages/xsimd/package.py
var/spack/repos/builtin/packages/xtensor-python/package.py
var/spack/repos/builtin/packages/xtensor/package.py
var/spack/repos/builtin/packages/xtl/package.py

New versions for the xtensor packages.

xtensor: 0.20.7

---

var/spack/repos/builtin/packages/prrte/package.py

This PR adds PRRTE, PMIx's Reference RunTime Evironment.

PRRTE package

---

var/spack/repos/builtin/packages/amber/package.py

This one requires two different tarballs to be smashed together to build, done via resource

amber: new package at v16

---

var/spack/repos/builtin/packages/netcdf-fortran/package.py

Add support for netcdf-fortran@4.4.5.

netcdf-fortran: add checksummed version 4.4.5

---

var/spack/repos/builtin/packages/py-blessed/package.py

New python package. 
A dependency of #11604

new package/py-blessed

---

var/spack/repos/builtin/packages/awscli/package.py

@adamjstewart  As discussed, this is now on top of the dependencies you added the other day. I named this one without the py- prefix, as it is just a cli on top of the existing python interface.

awscli: new package

---

var/spack/repos/builtin/packages/ucx/package.py

Added sha256 checksum for UCX version 1.5.1 and 1.5.2.

Add UCX version 1.5.1/1.5.2

---

lib/spack/spack/package.py

Fix for #10063 : install from source if buildcache with different DAG exist

---

var/spack/repos/builtin/packages/gnutls/package.py

gnutls: workaround guile build error on macos

---

var/spack/repos/builtin/packages/yaml-cpp/package.py

When built with tests, yaml-cpp vendors gtest. gtest (at least how it is built within yaml-cpp) does not properly understand clang's libc++, and includes `cxxabi.h` headers that are only for use with libstdc++.
This PR does not fix the issue of yaml-cpp vendoring a test dependency. It merely presents a `tests` variant for yaml-cpp and expresses the conflict between that variant and `cxxflags=-stdlib=libc++`.
Because `cxxflags=-stdlib=libc++` is not satisfied by `cxxflags=-stdlib=libc++ -O3` or any other spec that includes the problem flag along with others, I've added handling in the flag handler to catch those situations and throw an error. It's not as good as a conflict, but it's a workaround until we think of something better.
This will allow users to build yaml-cpp with libc++, as …

Make yaml-cpp build with libc++

---

var/spack/repos/builtin/packages/clamav/package.py
var/spack/repos/builtin/packages/launchmon/package.py

pkgconfig is the correct virtual dependency.

Fix pkgconfig dependencies

---

var/spack/repos/builtin/packages/libtomlc99/package.py

The PR for shared libraries has been merged upstream -> add new version.

libtomlc99: Update version

---

var/spack/repos/builtin/packages/r-spacetime/package.py

depends on `r-intervals` in #11884

r-spacetime: new package at 1.2-2

---

var/spack/repos/builtin/packages/adios2/package.py

Add the latest release of ADIOS2.

ADIOS2: v2.4.0

---

var/spack/repos/builtin/packages/r-spatialreg/package.py

depends on `r-spdata` in #11883

r-spatialreg: new package at 1.1-3

---

var/spack/repos/builtin/packages/py-cf-units/package.py

Wrapper class to support Unidata/UCAR udunits2 and cftime calendar functionality.
Depends on #11890 .

py-cf-units: new package

---

var/spack/repos/builtin/packages/py-lark-parser/package.py

Update existing py-lark-parser package to the latest available version.

py-lark-parser: Added latest version, 0.7.1

---

var/spack/repos/builtin/packages/r-grbase/package.py

depends on updates in #11936, #11935, #11934 to build with R@3.6.0+

r-grbase: new package at 1.8-3.4

---

var/spack/repos/builtin/packages/precice/package.py

This PR adds the preCICE Hotfix version 1.5.2

Add preCICE version 1.5.2

---

var/spack/repos/builtin/packages/openfoam/package.py

- sourceforge download location is migrating

CONFIG: update openfoam download url

---

var/spack/repos/builtin/packages/dimemas/package.py

Add recipe for the dimemas parallel performance simulator:
https://tools.bsc.es/dimemas

add dimemas recipe

---

var/spack/repos/builtin/packages/scalasca/package.py

also adds list_url for use with spack checksum

update scalasca to version 2.5

---

var/spack/repos/builtin/packages/py-jsonschema/package.py

Add py-jsonschema 2.6.0

---

var/spack/repos/builtin/packages/bzip2/package.py

bzip2: Add 1.0.8

---

var/spack/repos/builtin/packages/hpx/package.py

Version bump to latest HPX version 1.3.0.

Added HPX version 1.3.0.

---

var/spack/repos/builtin/packages/jube/package.py

Add package definition for the Jülich Benchmarking Environment (JUBE).

Add JUBE package definition

---

var/spack/repos/builtin/packages/kim-api/package.py

Update kim-api package to latest 2.1.0 release.

kim-api 2.1.0

---

lib/spack/spack/test/url_parse.py
lib/spack/spack/url.py
lib/spack/spack/util/compression.py
var/spack/repos/builtin/packages/kim-api/package.py
var/spack/repos/builtin/packages/openkim-models/package.py

```console
$ spack url parse https://s3.openkim.org/archives/collection/openkim-models-2019-03-29.txz
==> Parsing URL: https://s3.openkim.org/archives/collection/openkim-models-2019-03-29.txz
==> Matched version regex  6: r'^[a-zA-Z\\d+-]+-v?(\\d[\\da-zA-Z.]*)$'
==> Matched  name   regex  8: r'^([A-Za-z\\d+\\._-]+)$'
==> Detected:
https://s3.openkim.org/archives/collection/openkim-models-2019-03-29.txz
---------------------- ~~~~~~
name:    openkim-models-2019-03
version: 29.txz
==> Substituting version 9.9.9b:
https://s3.openkim.org/archives/collection/openkim-models-2019-03-9.9.9b
---------------------- ~~~~~~
$ spack url summary
==> Generating a summary of URL parsing in Spack...
Total URLs found:          3176
Names correctly parsed:    2754/3176 (86.71%)
Versions correctly parsed: …
```

Add support for .txz and .tbz2 file extensions

---

var/spack/repos/builtin/packages/py-numpy/package.py

This is a temporary workaround for the problem described in #9149. A similar workaround is employed in #10881.

Workaround for #9149

---

var/spack/repos/builtin/packages/pmix/package.py

added version 3.1.3 of PMIx

---

var/spack/repos/builtin/packages/prrte/package.py

pkg PRRTE: added version 1.0.0

---

var/spack/repos/builtin/packages/py-scikit-learn/package.py

Also allows users to disable OpenMP support, but only on the master branch. See https://github.com/scikit-learn/scikit-learn/issues/14332

Add master version to sklearn

---

lib/spack/spack/url.py
lib/spack/spack/util/web.py

Fixes #12020 
```console
$ spack versions r-broom
==> Safe versions (already checksummed):
0.4.2
==> Remote versions (not yet checksummed):
0.5.1  0.5.0  0.4.5  0.4.4  0.4.3  0.4.1  0.4.0  0.3.7  0.3.6  0.3.5  0.3.4
$ spack checksum r-broom
==> Found 12 versions of r-broom:
0.5.1  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.5.1.tar.gz
0.5.0  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.5.0.tar.gz
0.4.5  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.4.5.tar.gz
0.4.4  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.4.4.tar.gz
0.4.3  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.4.3.tar.gz
0.4.2  https://cran.r-project.org/src/contrib/Archive/broom/broom_0.4.2.tar.gz
0.4.1 …
```

Fix version scraping for CRAN packages

---

lib/spack/spack/operating_systems/mac_os.py
var/spack/repos/builtin/packages/gcc/package.py

a variation of https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb#L76-L84

gcc: support installation without command line tools

---

lib/spack/spack/cmd/pkg.py
lib/spack/spack/repo.py
lib/spack/spack/test/cmd/pkg.py

This provides some updates to the `spack pkg` command.  This command has been around for a while, though it is [only documented here](https://spack.readthedocs.io/en/latest/command_index.html#spack-pkg).  It'll tell you what packages were present in particular revisions of Spack, e.g.:
```console
$ spack pkg list v0.10.0 | wc -l
1114
$ spack pkg list v0.11.0 | wc -l
2177
$ spack pkg list v0.12.1 | wc -l
2907
```
It can diff two revisions, e.g.:
```console
$ spack pkg diff HEAD~150 
HEAD~150:
openfoam-com
HEAD:
dimemas       llvm-openmp  powerapi                   py-mlxtend       py-pyke      r-grbase     r-spatialreg
jube          nim          py-antlr4-python3-runtime  py-mo-pack       py-pyugrid   r-gwmodel    r-spdata
libmo-unpack  openfoam     py-cf-units …
```

Add `spack pkg changed` command

---

var/spack/repos/builtin/packages/quantum-espresso/package.py

Adding support for QE 6.4.1. This is a really minor PR.
@adamjstewart @scheibelp

Quantum Espresso Update 2019

---

var/spack/repos/builtin/packages/relion/package.py

Previous versions have bugs and inferior performance so they're no longer installation options

added relion 3.0.7 - removed deprecated versions

---

var/spack/repos/builtin/packages/qmcpack/package.py

Incremental Update to QMCPACK Spack package, includes:
- Support for QE 6.4.1 converter
- Support for QMCPACK 3.8.0
@adamjstewart @scheibelp

QMCPACK Update July 2019

---

var/spack/repos/builtin/packages/geant4/CLHEP-10.03.03.patch
var/spack/repos/builtin/packages/geant4/package.py

Improve the way Geant4 is built against CLHEP, especially 10.03.p03, which requires a patch.

geant4: improvements with respect to building against CLHEP.

---

var/spack/repos/builtin/packages/lame/package.py
var/spack/repos/builtin/packages/libmad/libmad-0.15.1b.patch
var/spack/repos/builtin/packages/libmad/package.py
var/spack/repos/builtin/packages/sox/package.py

Added a new package for [LAME encoder](http://lame.sourceforge.net) and added a variant in sox-package for it.

lame & libmad: Added two new packages for sox mp3 support.

---

var/spack/repos/builtin/packages/py-flake8/package.py

I'm hoping that this method of specifying dependencies for each minor release works better than the old technique.

Add flake8 3.7.8

---

var/spack/repos/builtin/packages/kealib/package.py

fix incorrect md5sum for version 1.4.11

kealib: fix incorrect md5sum for v1.4.11

---

var/spack/repos/builtin/packages/environment-modules/package.py

New feature release in the v4 series.
Release announcement: https://timeline.noticeable.io/cbzeG7wTvAIqj21zbUmx/posts/modules-4-3-0-released?cache=false

environment-modules package: add version 4.3.0

---

var/spack/repos/builtin/packages/blis/package.py

modified:   var/spack/repos/builtin/packages/blis/package.py

Bump version for BLIS

---

var/spack/repos/builtin/packages/py-torchvision/package.py

Successfully builds for me on macOS 10.14.5 with Clang 10.0.1.
Depends on #12174

Add torchvision package

---

var/spack/repos/builtin/packages/pism/package.py

See https://github.com/pism/pism/issues/359
@citibeth can you test this?

Add PISM 1.1.4

---

var/spack/repos/builtin/packages/py-pipits/package.py
var/spack/repos/builtin/packages/py-pispino/package.py
var/spack/repos/builtin/packages/rdptools/package.py
var/spack/repos/builtin/packages/seqkit/package.py

This hasn't been tested in any way. I just added the latest versions and dependencies to support Python 3.
@akthoma

Add py-pipits 2.4

---

var/spack/repos/builtin/packages/py-tables/package.py

Haven't gotten a chance to test this yet as the `numexpr` build is broken for me.

Add tables 3.5.2

---

var/spack/repos/builtin/packages/magma/package.py

Magma: fix prefix

---

var/spack/repos/builtin/packages/bdw-gc/package.py

bdw-gc: add variant for Multithreading

---

var/spack/repos/builtin/packages/py-pyqt5/package.py

py-pyqt5: add missing py-enum34 dependency

---

var/spack/repos/builtin/packages/blis/package.py

Now that #1983 is merged, change the convention from develop to master.

Minor edit to blis

---

var/spack/repos/builtin/packages/tau/package.py

Fixes #11193 
This should resolve https://github.com/spack/spack/issues/11193

Fixed arch setting variants. Activate cray arch automatically.

---

var/spack/repos/builtin/packages/butterflypack/package.py

I have added the package script for the mathematical software ButterflyPACK. Please review the changes.

added a package butterflypack

---

var/spack/repos/builtin/packages/ermod/package.py

This PR adds (new) support to build and install the `ermod` package.

ermod: new package

---

var/spack/repos/builtin/packages/faodel/package.py

Update the FAODEL package with version 1.1906.1.

FAODEL: Add version 1.1906.1

---

var/spack/repos/builtin/packages/slepc/package.py

slepc: update python dependencies to be in sync with petsc

---

var/spack/repos/builtin/packages/py-requests-futures/package.py

a dependency of py-usgs #12263

new package: py-requests-futures

---

var/spack/repos/builtin/packages/py-usgs/package.py

new package: py-usgs

---

var/spack/repos/builtin/packages/py-backports-weakref/package.py

add new python package
a dependency of py-backports-tempfile

new package: py-backports-weakref

---

var/spack/repos/builtin/packages/py-apipkg/package.py

add new version, add sha256 sums

package/py-apipkg add new version, add sha256 sums

---

var/spack/repos/builtin/packages/py-backports-tempfile/package.py

add new package
depends on py-backports-weekref to be pushed soon

new package: py-backports-tempfile

---

var/spack/repos/builtin/packages/ginkgo/package.py

ginkgo: add maintainers

---

var/spack/repos/builtin/packages/amrex/package.py

Balay/amrex 19.08

---

var/spack/repos/builtin/packages/pumi/package.py

This PR adds a new PUMI version.
https://github.com/SCOREC/core/issues/219

pumi: new version 2.2.1

---

var/spack/repos/builtin/packages/plasma/package.py

Version 19.8.1 of PLASMA 

---

.github/main.workflow

@becker33
This reverts commit 54e3bc31f991200688044431f57ad8b3a25c12e8.
It has been causing problems and merits investigation. In the meantime we will remove it.

Revert "add maintainer review action to main.workflow"

---

var/spack/repos/builtin/packages/aria2/package.py

new package: aria2

---

var/spack/repos/builtin/packages/binutils/package.py

Added checksum for binutils, version 2.32

Added checksum for binutils@2.32

---

var/spack/repos/builtin/packages/flatcc/package.py

This updates the flatcc package to have the latest version.

flatcc: add version 0.5.3

---

var/spack/repos/builtin/packages/gromacs/gmxDetectCpu-cmake-3.14.patch
var/spack/repos/builtin/packages/gromacs/package.py

* https://redmine.gromacs.org/issues/2927
* tested with cmake 3.14.4 and 3.15.1

gromacs: fix CPU optimizations detection (simd=auto)

---

var/spack/repos/builtin/packages/libconfig/package.py

Adds version 1.7.1 to libconfig.

libconfig: add version 1.7.1

---

var/spack/repos/builtin/packages/py-selenium/package.py

Add py-selenium package

---

var/spack/repos/builtin/packages/py-geeup/package.py

Add py-geeup package

---

var/spack/repos/builtin/packages/py-geeadd/package.py

Add py-geeadd package

---

var/spack/repos/builtin/packages/py-poster/package.py
var/spack/repos/builtin/packages/py-poster/python3.patch

Needed to build something that depends on this but it doesn't support Python 3. I haven't heavily tested this, but I successfully installed things that depended on it.

Port py-poster to Python 3

---

var/spack/repos/builtin/packages/qwtpolar/package.py

"The QwtPolar library contains classes for displaying values on a polar coordinate system."
A dependency of QGIS.

new package: qwtpolar

---

var/spack/repos/builtin/packages/grass/package.py

Package/grass: fix iconv linking issue

---

var/spack/repos/builtin/packages/py-keras-applications/package.py

package/py-keras-applications: add new version

---

var/spack/repos/builtin/packages/charliecloud/package.py

This PR (a) adds the charliecloud master branch, and (b) adds charliecloud package dependencies, e.g., python and modules needed to build HTML documentation.

add charliecloud master branch; add dependencies

---

var/spack/repos/builtin/packages/py-python-magic/package.py

add new package: A python wrapper for libmagic

add new package: py-python-magic

---

var/spack/repos/builtin/packages/masurca/arm.patch
var/spack/repos/builtin/packages/masurca/package.py

* remove -minline-all-stringops when target is arm.
* change int3 to raise(SIGTRAP) when target is arm.

masurca: build on arm.

---

var/spack/repos/builtin/packages/nccl/package.py
var/spack/repos/builtin/packages/nccl/so_reuseport.patch

Also removed a version for which there is no evidence that it ever existed on the GitHub repo.

NCCL: fix build on older Linux systems

---

var/spack/repos/builtin/packages/laszip/package.py

lossless lidar compression. A dependency of pktools

new package: laszip

---

var/spack/repos/builtin/packages/py-pyfaidx/package.py

py-pyfaidx: tweak dependencies; fixes #12445

---

var/spack/repos/builtin/packages/kokkos/package.py

Add Kokkos 2.9.0

---

lib/spack/spack/cmd/pkg.py

The pkg command uses a working directory for git invocations rather than -C.
Closes #12448.

Make pkg command behave properly with older git (<1.8.5)

---

var/spack/repos/builtin/packages/mercury/fix-cmake-3.15-check_symbol_exists.patch
var/spack/repos/builtin/packages/mercury/package.py

Fixes https://github.com/mercury-hpc/mercury/issues/301

mercury: Fix CMake 3.15 configure error

---

lib/spack/spack/stage.py

See https://github.com/spack/spack/issues/12485
Properly format message with all paths that could not be used. also report canonicalized paths vs. Spack config variables like 'tempdir'
(Note that this will possibly have to change based on pending PRs related to the code this touches)

[WIP] fix error message when Spack can't find a staging directory

---

var/spack/repos/builtin/packages/qtkeychain/package.py

Platform-independent Qt API for storing passwords securely.
A dependency of QGIS #12388

new package: QtKeychain

---

var/spack/repos/builtin/packages/exiv2/package.py

"Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata."

new package: Exiv2

---

var/spack/repos/builtin/packages/py-fallocate/package.py

py-fallocate "Module to expose posix_fallocate(3), posix_fadvise(3) and fallocate(2) "

new Package/py fallocate

---

var/spack/repos/builtin/packages/py-empy/package.py

new package: py-empy
A templating system for Python.

new package: py-empy

---

var/spack/repos/builtin/packages/c-blosc2/package.py

Add new packages for c-blosc2 compression.
- support external lizard build (missing header(s) in install) https://github.com/inikep/lizard/issues/21

Add: c-blosc2

---

lib/spack/spack/cmd/spec.py

Fixes https://github.com/spack/spack/issues/12306

'spack spec --yaml' command now writes build deps to yaml

---

var/spack/repos/builtin/packages/claw/package.py

Add version 2.0 of the CLAW Compiler

claw: add version 2.0

---

var/spack/repos/builtin/packages/py-blinker/package.py

a dependency of py-nose2 #12528

new package: py-blinker

---

lib/spack/spack/cmd/create.py

bugfix: template create constructor args

---

var/spack/repos/builtin/packages/ecp-io-sdk/package.py

ecp-io-sdk: add UnifyFS and VeloC

---

var/spack/repos/builtin/packages/tau/package.py

Added sha256sum for tau-2.28.2.

---

var/spack/repos/builtin/packages/parallel-netcdf/package.py

Update to latest release version of parallel-netcdf PnetCDF-1.11.2

PARALLEL-NETCDF: New version 1.11.2

---

var/spack/repos/builtin/packages/py-filemagic/package.py

"A Python API for libmagic, the library behind the Unix file command"

add new package: py-filemagic

---

var/spack/repos/builtin/packages/py-fastcache/package.py

C implementation of Python 3 functools.lru_cache

new package: py-fastcache

---

var/spack/repos/builtin/packages/py-cov-core/package.py

A dependency of 'py-nose2@0.6.0' #12522

new package: py-cov-core

---

lib/spack/docs/build_systems/rpackage.rst

Also added some links to useful docs I found, and details about the new "Enhances" section (not sure if new or if I've just never seen it before).
@glennpj

RPackage docs: use cloud.r-project.org

---

var/spack/repos/builtin/packages/qjson/package.py

Package/qjson: add option to build with qt4

---

var/spack/repos/builtin/packages/abinit/package.py

Abinit 8.10.3

---

var/spack/repos/builtin/packages/py-oauthlib/package.py

missing dependencies (blinker, pyjwt) will be pushed soon:

new package: py-oauthlib

---

var/spack/repos/builtin/packages/athena/missing-separator.patch
var/spack/repos/builtin/packages/athena/package.py

I'm taking a Computational Astrophysics course this semester, so I'll be adding a lot of astrophysics codes in the near future.
Successfully builds on CentOS 7 with Intel 18.0.1.
@mlawsonca

Add athena package

---

var/spack/repos/builtin/packages/sqlite/package.py

Build with Rtree support:
https://sqlite.org/rtree.html

package/sqlite: add variant for building RTREE module

---

var/spack/repos/builtin/packages/fann/package.py

new package: FANN

---

var/spack/repos/builtin/packages/pktools/package.py
var/spack/repos/builtin/packages/pktools/package.py.pktools

disabled liblas: 
- package is not available in spack, 
- build fails with system liblas on Centos7

new package: pktools

---

var/spack/repos/builtin/packages/julia/package.py

This PR provides an option to build Julia with Intel MKL.

Add MKL variant to Julia

---

var/spack/repos/builtin/packages/ccs-qcd/package.py

This PR adds (new) support to build and install the `ccs-qcd` package.

ccs-qcd: new package

---

var/spack/repos/builtin/packages/pmlib/fix_compiler_options.patch
var/spack/repos/builtin/packages/pmlib/package.py

This PR adds (new) support to build and install the `pmlib` package.

pmlib: new package

---

var/spack/repos/builtin/packages/protobuf-c/package.py

new package: protobuf-c

---

var/spack/repos/builtin/packages/liblas/package.py

libLAS is a C/C++ library for reading and writing the very common LAS LiDAR format. 
An optional dependency of pktools #12611

new package: liblas

---

var/spack/repos/builtin/packages/textparser/fix_compiler_options.patch
var/spack/repos/builtin/packages/textparser/package.py

This PR adds (new) support to build and install the `textparser` package.

textparser: new package

---

var/spack/repos/builtin/packages/shadow/package.py

This will add shadow-uidmap, hoping to address #12297 @odoublewen I didn't hit the issue with semanage.h - does this mean I have it on my host (and still need to install here?)
I'm not sure that I did the configure and install steps correctly - please review! 
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

new package: shadow

---

lib/spack/docs/module_file_support.rst

Fixes #2757
@hartzell @alalazo

Update docs on module loads command

---

var/spack/repos/builtin/packages/tau/package.py

and making Fortran an option that can be disabled.  Also added
support for the POSIX I/O wrapper and OMPT for OpenMP.

Updating TAU package.  Fixing compiler specification for OSX

---

var/spack/repos/builtin/packages/py-xopen/package.py

Tested on Centos6, gcc 8.2
This update is needed for #12741

py-xopen: update release 0.8.2 checksum

---

var/spack/repos/builtin/packages/py-bz2file/package.py
var/spack/repos/builtin/packages/py-xopen/package.py

Should be merged before #12742 and thus also before #12741

new package: py-bz2file

---

lib/spack/docs/build_systems/sippackage.rst
lib/spack/spack/build_systems/sip.py
var/spack/repos/builtin/packages/py-pyqt4/package.py
var/spack/repos/builtin/packages/py-pyqt5/package.py
var/spack/repos/builtin/packages/py-sip/package.py
var/spack/repos/builtin/packages/qt/package.py

Closes #12353 
@Bidibulke @Sinan81 can you test this? It fixes both `py-pyqt4` and `py-pyqt5` and should be generic enough that it can be extended to new SIP packages. I also added additional import tests that should catch the bug before it happens again.

Fix PyQt installation

---

share/spack/qa/run-docker-tests

Fix docker build for packages.spack.io
Follow-up to #12764

packages build: fix path to spack

---

share/spack/packages/build-image.sh

The build instructions I cloned from did not work ;)
Follow-up to #12772

packages service: fix docker build

---

share/spack/qa/run-docker-tests

CD is hard.
Follow-up to #12773

packages service: fix docker build cont

---

var/spack/repos/builtin/packages/py-atropos/package.py

Tested build and execution with real data on Centos6, gcc 8.2

py-atropos: new package

---

var/spack/repos/builtin/packages/openmx/package.py

This PR adds (new) support to build and install the `openmx` package.

openmx: new package

---

lib/spack/spack/test/module_parsing.py
lib/spack/spack/util/module_cmd.py

A couple of issues have come up recently with module parsing heuristics. This PR makes the heuristics more robust, and adds testing for the portions that failed.
Fixes #12650
Fixes #12662
Fixes #12684
Closes #12687
Fixes #9710
Fixes #9126 
Fixes #5273

module parsing: make heuristic to get paths from modules more robust

---

var/spack/repos/builtin/packages/py-pykwalify/package.py

missing a dependency to be created soon.

new package: py-pykwalify

---

var/spack/repos/builtin/packages/genemark-et/package.py

- add version 4.46
- add missing perl dependencies
- new version has different source layout
- filter shebang to use spack perl

Update genemark-et package

---

var/spack/repos/builtin/packages/augustus/package.py

- add missing perl dependency
- only filter Makefile if referred to dependency is in the spec
- rewrite the shebang line of scripts to use spack perl
- remove tabix dependency as tabix and bgzip are part of htslib

Fixes for augustus package

---

var/spack/repos/builtin/packages/braker/package.py

- add version 2.1.4
- change url to github
- add perl dependencies
- new version has a new source layout
- filter shebang to use spack perl

Update braker package

---

lib/spack/spack/compiler.py

Fixes #12732
Fixes #12767
This is a continuation of #7153 
@becker33 @mathstuf @tgamblin

Add exception for failed implicit RPATH detection

---

var/spack/repos/builtin/packages/libkml/package.py

Successfully installs on macOS 10.14.6 with Clang 10.0.1.
Seeing the same weird unit test errors as #12834

Add libkml package

---

.gitignore

Update/improvement to .gitignore file

Ignore git *.orig files and emacs backup files

---

var/spack/repos/builtin/packages/claw/package.py

@alalazo or @ax3l Can you merge this? Probably the last version pushed from Switzerland :-)

Add version 2.0.1 for CLAW Compiler

---

lib/spack/spack/test/util/util_gpg.py
lib/spack/spack/util/gpg.py

Fix how 'gpg --list-secret-keys ...' output is parsed

---

var/spack/repos/builtin/packages/environment-modules/package.py

New bugfix release in the v4.3 serie.
Release announcement: https://timeline.noticeable.io/cbzeG7wTvAIqj21zbUmx/posts/modules-4-3-1-released?cache=false

environment-modules: add version 4.3.1

---

var/spack/repos/builtin/packages/libceed/package.py

This adds support for the freshly released libCEED 0.5.

Jed/libceed 0.5

---

lib/spack/spack/compilers/fj.py

Add new method 'verbose_flag' to source of Fujitsu compiler.

Add 'verbose_flag' method

---

var/spack/repos/builtin/packages/blast-plus/package.py
var/spack/repos/builtin/packages/catalyst/package.py
var/spack/repos/builtin/packages/hpctoolkit/package.py
var/spack/repos/builtin/packages/openfoam/package.py
var/spack/repos/builtin/packages/ross/package.py
var/spack/repos/builtin/packages/templight/package.py

In #3206 we forgot to search and update for a particular query pattern to the spec's target. This PR fixes that.

Fixed query to target for a few packages

---

var/spack/repos/builtin/packages/neovim/package.py

Reverts spack/spack#12965
@pat-s No rush to get 0.4.2 working, let me know if you need any help.

Revert "Update neovim to v0.4.2"

---

var/spack/repos/builtin/packages/hypre/package.py

hypre: add version 2.18.0

---

var/spack/repos/builtin/packages/mercurial/package.py

versions 4.9.1 and 5.1.1 added

new mercurial versions

---

var/spack/repos/builtin/packages/fio/package.py
var/spack/repos/builtin/packages/libaio/package.py
var/spack/repos/builtin/packages/lvm2/package.py
var/spack/repos/builtin/packages/mariadb/package.py

@odoublewen 
refers #12975
closes #12986

libaio: fixed a condition that checks whether we are running on OS X

---

var/spack/repos/builtin/packages/singularity/package.py

Some love... learning how to contrib to Spack 
Signed-off-by: ArangoGutierrez <eduardo@sylabs.io>

add singularity 3.4.1

---

var/spack/repos/builtin/packages/direnv/package.py

direnv: add info for version 2.20.0

---

lib/spack/spack/compilers/fj.py

Add list of required libraries.

fujitsu compiler: Add 'required_libs'.

---

var/spack/repos/builtin/packages/cdhit/package.py

cdhit use zlib but dependency description is not found.
This PR add zlib dependency on cdhit.

cdhit: add zlib dependency.

---

var/spack/repos/builtin/packages/tasmanian/addons70.patch
var/spack/repos/builtin/packages/tasmanian/package.py
var/spack/repos/builtin/packages/tasmanian/packageconf70.patch

* added Tasmanian version 7.0 to spack
* mpi requires couple of patches due to cmake quirks

added tasmanian version 7.0 to spack

---

lib/spack/llnl/util/cpu/microarchitectures.json
lib/spack/spack/test/llnl/util/cpu.py

Generic x86_64 code compiled with GCC uses non deprecated mtune flags

---

lib/spack/docs/getting_started.rst

Update compilers.yaml location in Getting Started docs

---

var/spack/repos/builtin/packages/py-flye/package.py

`py-flye` finally has Python 3 support.

Add py-flye 2.6

---

var/spack/repos/builtin/packages/manta/package.py

Tested on CentOS 7 w/ gcc 8.2.0

manta: new release checksum

---

var/spack/repos/builtin/packages/cctools/package.py

- add version/checksum info for v7.0.18
- update checksum for v6.1.1 to use sha256, while I have the editor
open...

Update cctools to v7.0.18

---

var/spack/repos/builtin/packages/llvm/package.py

LLVM 9.0.0

---

var/spack/repos/builtin/packages/superlu-dist/package.py

superlu-dist: add openmp variant

---

var/spack/repos/builtin/packages/cxxopts/package.py

A popular lightweight C++ command line option parser

New package: cxxopts

---

lib/spack/docs/features.rst

Applying accepted fix from spack/spack.io#4

doc: fix #12245 non-functional libdwarf dependency

---

var/spack/repos/builtin/packages/gnuplot/package.py
var/spack/repos/builtin/packages/qt/package.py

... otherwise we get back to https://github.com/spack/spack/issues/9721
p.s. I switched `framework` on by default as otherwise there was concretizer error.

gnuplot: add 5.2.7 and fix qt dep

---

var/spack/repos/builtin/packages/pmdk/package.py

Update builtin repo with latest version of PMDK.

bump PMDK to v 1.7

---

var/spack/repos/builtin/packages/cryptsetup/package.py

Since I may not be paying attention when the next release happens, leave a clue for whomever steps up.

Add headsup note re cryptsetup patch for v2.2.2

---

var/spack/repos/builtin/packages/libsigsegv/package.py

Add libsigsegv 2.12

---

var/spack/repos/builtin/packages/libiconv/package.py

Add libiconv 1.16

---

var/spack/repos/builtin/packages/tar/package.py

Add tar 1.32

---

var/spack/repos/builtin/packages/mpfr/package.py

Add mpfr 4.0.2

---

var/spack/repos/builtin/packages/f18/package.py

Resolve https://github.com/spack/spack/issues/13118
@alalazo @certik

Fix f18 install method

---

var/spack/repos/builtin/packages/abinit/package.py
var/spack/repos/builtin/packages/accfft/package.py
var/spack/repos/builtin/packages/libemos/package.py
var/spack/repos/builtin/packages/relion/package.py

See https://github.com/spack/spack/pull/12889#issuecomment-540713844

Fixed constraints in recipes for packages that depends on fftw

---

var/spack/repos/builtin/packages/cmake/package.py

Add cmake 3.15.4

---

var/spack/repos/builtin/packages/libjpeg-turbo/package.py

Add libjpeg-turbo 2.0.3

---

var/spack/repos/builtin/packages/llvm-openmp/package.py

Add LLVM OpenMP 9.0.0

---

var/spack/repos/builtin/packages/py-pandas/package.py

Add py-pandas 0.25.1

---

var/spack/repos/builtin/packages/py-pluggy/package.py

Add py-pluggy 0.13.0

---

var/spack/repos/builtin/packages/py-pytest/package.py

Add py-pytest 5.2.1

---

var/spack/repos/builtin/packages/py-numpy/package.py

See https://github.com/spack/spack/issues/13190#issuecomment-541211722
@balay can you confirm that this fixes your problem? I confirmed that it still works as expected when building the package, but don't have an external installation to test on.

Fix external numpy package support

---

var/spack/repos/builtin/packages/gmp/package.py

Successfully installs and passes all tests on macOS 10.15 with Clang 11.0.0.
Stolen from https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmp.rb#L21

gmp: fix make check on catalina

---

var/spack/repos/builtin/packages/py-pyflakes/package.py

Add py-pyflakes 2.1.1

---

var/spack/repos/builtin/packages/py-docutils/package.py

Add py-docutils 0.15.2

---

var/spack/repos/builtin/packages/py-cython/package.py

Add py-cython 0.29.13

---

var/spack/repos/builtin/packages/subversion/package.py

Haven't gotten a chance to test `subversion+perl`. Is anyone willing to test it?

Add subversion 1.12.2

---

var/spack/repos/builtin/packages/mercurial/package.py

Add mercurial 5.1.2

---

var/spack/repos/builtin/packages/lz4/package.py

Add lz4 1.9.2

---

var/spack/repos/builtin/packages/apr/package.py

Add apr 1.7.0

---

var/spack/repos/builtin/packages/omega-h/package.py

omega-h: add version 9.29.0

---

var/spack/repos/builtin/packages/slepc/package.py

slepc: use spack specified python in configure

---

var/spack/repos/builtin/packages/amrex/package.py

amrex: add version 19.10

---

var/spack/repos/builtin/packages/py-kiwisolver/package.py

Add py-kiwisolver 1.1.0

---

var/spack/repos/builtin/packages/dialign/package.py

see https://bibiserv.cebitec.uni-bielefeld.de/dialign
useful in biopython environment

add dialign package

---

var/spack/repos/builtin/packages/acts-core/package.py

Routine maintenance update adding new ACTS releases and updating the ACTS dependency requirements.

New ACTS versions

---

var/spack/repos/builtin/packages/py-petsc4py/package.py

py-petsc4py: add version 3.12.0

---

var/spack/repos/builtin/packages/arborx/package.py

- Require Kokkos with c++14
- Update the case of CMake options

arborx: update

---

var/spack/repos/builtin/packages/hypre/package.py

hypre: add version 2.18.1

---

lib/spack/spack/cmd/create.py

This has been bothering me for the longest time.

spack create: http -> https

---

var/spack/repos/builtin/packages/py-flask/package.py

Add latest version of py-flask

---

var/spack/repos/builtin/packages/proj/package.py

Add latest version of proj

---

var/spack/repos/builtin/packages/tut/package.py

Tut cannot be built with Python 3.7+

---

var/spack/repos/builtin/packages/py-torch/package.py

Add latest version of py-torch

---

var/spack/repos/builtin/packages/libksba/package.py

Fix configure arg to libksba

---

var/spack/repos/builtin/packages/libassuan/package.py

Fix configure arg to libassuan

---

lib/spack/llnl/util/cpu/microarchitectures.json
lib/spack/spack/test/llnl/util/cpu.py

Added optimization flags for Intel compilers

---

var/spack/repos/builtin/packages/gmsh/package.py

Adds the latest version of GMSH

gmsh: add version 4.4.1

---

var/spack/repos/builtin/packages/sundials/package.py

plus some cleanup
cc: @gardner48, @balay

sundials: add version 5.0.0 and new variant

---

var/spack/repos/builtin/packages/blast-legacy/package.py

Fixes issues related to PR #11662.

blast-legacy: fix build issues

---

var/spack/repos/builtin/packages/py-cdsapi/package.py

Package allows to access Climate Data Store for downloading climate and weather reanalysis data, e.g. ERA5 interim or ERA5-land

New package: py-cdsapi

---

var/spack/repos/builtin/packages/netcdf-cxx4/package.py
var/spack/repos/builtin/packages/netcdf-fortran/package.py
var/spack/repos/builtin/packages/netcdf/package.py

Fixes #13414 
@yellowhat can you test this?

Add latest version of NetCDF libraries

---

lib/spack/spack/database.py

#13410 upgraded the database version, which is something we should've done after #12933.  However, Spack reindexes the whole database on read.  It can seem like Spack is taking a *really* long time to do this (10-20 seconds on my mac, and I'm sure much longer on a cluster with NFS and more installs).
Reindexing takes a significant amount of time, and there's no reason to do it from DB version `0.9.3` to version `5`. The only difference is that v5 can contain "deprecated_for" fields, which doesn't actually require a reindex -- just that we indicate when we've written a DB that could contain `deprecated_for` fields.
Another issue is that we print nothing when we do the reindex.  So for me, it just seemed like Spack was cranking away and taking a really long time and I hit ctrl-c.  When I …

bugfix: reindexing is not necessary for DB v0.9.3 to v5 upgrade

---

var/spack/repos/builtin/packages/py-defusedxml/package.py

new package: py-defusedxml

---

var/spack/repos/builtin/packages/gpu-burn/Makefile.patch
var/spack/repos/builtin/packages/gpu-burn/package.py

The gpu-burn package installs the gpu_burn utility for stress testing
Nvidia GPUs.

New package: gpu-burn

---

var/spack/repos/builtin/packages/ecos/package.py

A lightweight conic solver for second-order cone programming.
A dependency of cvxpy

new package: ecos

---

var/spack/repos/builtin/packages/py-pandocfilters/package.py

new package: py-pandocfilters

---

lib/spack/spack/build_systems/intel.py

Intended to debug #12752.
@mgsternberg

Output directory Spack is looking in for MKL libs

---

var/spack/repos/builtin/packages/cudnn/package.py
var/spack/repos/builtin/packages/lbann/package.py

Updated LBANN to include pytest.  Added support for new versions of cudnn.

Updated LBANN to include pytest

---

var/spack/repos/builtin/packages/cbtf-argonavis-gui/package.py
var/spack/repos/builtin/packages/cbtf-argonavis/package.py
var/spack/repos/builtin/packages/cbtf-krell/package.py
var/spack/repos/builtin/packages/openspeedshop-utils/package.py
var/spack/repos/builtin/packages/openspeedshop/package.py

Update the module files for cbtf-krell and openspeedshop adding man paths and needed papi and libmonitor paths.

Update the module files for cbtf-krell and openspeedshop

---

var/spack/repos/builtin/packages/py-osqp/package.py

python package for OSQP optimization code.

new package: py-osqp

---

var/spack/repos/builtin/packages/py-ecos/package.py

Python package for ECOS: Embedded Cone Solver.

new package: py-ecos

---

var/spack/repos/builtin/packages/py-cvxpy/package.py

new package: py-cvxpy: "Convex optimization for everyone"

new package: py-cvxpy

---

var/spack/repos/builtin/packages/spfft/package.py

https://github.com/eth-cscs/SpFFT (dependency for SIRIUS)

Add SpFFT: sparse 3D FFT library

---

var/spack/repos/builtin/packages/r-fields/package.py

depends on `r-spam` added in #13494

r-fields: new package at 9.9

---

var/spack/repos/builtin/packages/kokkos/package.py

so we can use it from other spackages

kokkos: turn host_values into a property

---

var/spack/repos/builtin/packages/grass/package.py

The latest release of GRASS finally supports Python 3.

Add GRASS 7.8.0

---

var/spack/repos/builtin/packages/protobuf/package.py

Successfully installs on Cray CNL5 with GCC 5.3.0.

Add latest version of protobuf

---

var/spack/repos/builtin/packages/saga-gis/package.py

Several improvements of saga-gis package:
1. New version
2. New variants to enable more Saga-GIS tools
3. Enabled python interface
4. Set Saga-GIS env variables to load tools at runtime

Update package saga gis

---

var/spack/repos/builtin/packages/perl-term-readline-gnu/package.py
var/spack/repos/builtin/packages/perl-xml-libxslt/package.py
var/spack/repos/builtin/packages/polymake/package.py
var/spack/repos/builtin/packages/ppl/package.py

* new 3.5 polymake version
* new 1.2 ppl version
* new packages: perl-term-readline-gnu, perl-xml-libxslt
* added some missing polymake dependencies

Polymake: new version and more dependencies

---

var/spack/repos/builtin/packages/py-voluptuous/package.py

https://github.com/alecthomas/voluptuous (dependency for SIRIUS)

Add py-voluptuous

---

var/spack/repos/builtin/packages/py-testpath/package.py

new package py-testpath

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/relocate.py
var/spack/repos/builtin/packages/perl/package.py

@tgamblin I think we need this for tomorrow.

binary distribution: relocate text files properly in relative binaries

---

var/spack/repos/builtin/packages/charliecloud/package.py

Add Charliecloud version 0.12.

add charliecloud 0.12

---

var/spack/repos/builtin/packages/py-ics/package.py

new package: py-ics

---

var/spack/repos/builtin/packages/netcdf-fortran/package.py

netcdf-fortran@4.5: will error if netcdf-c has been built with MPI support:
```
configure: error:
-----------------------------------------------------------------------
The NetCDF C library is built with parallel I/O feature enabled, but
the Fortran compiler '.../lib/spack/env/gcc/gfortran' supplied in this configure command
does not support MPI-IO. Please use one that does. If parallel I/O
feature is not desired, please use a NetCDF C library with parallel
I/O feature disabled. Abort.
-----------------------------------------------------------------------
```
Copy logic from netcdf-c to add an `mpi` variant.
Fixes #13498

netcdf-fortran: Fix parallel builds

---

var/spack/repos/builtin/packages/ncview/package.py

netcdf has been renamed to netcdf-c.

ncview: Fix dependency check

---

var/spack/repos/builtin/packages/py-torch/package.py

Successfully builds on macOS 10.15.1 with Clang 11.0.0 and Python 3.7.4.
Successfully builds on Cray CNL5 with GCC 5.3.0 and Python 3.7.4.
Build times on macOS are down slightly to 1 hour.
Build times on Cray are way down from ~35 hours to 7 hours.

Speed up PyTorch build

---

var/spack/repos/builtin/packages/py-convertdate/package.py

new package: py-convertdate

---

var/spack/repos/builtin/packages/ginkgo/package.py

Balay/ginkgo 1.1.0

---

var/spack/repos/builtin/packages/acts-core/package.py
var/spack/repos/builtin/packages/py-tempora/package.py

python time utilities, dependency for cherrypy web framework.

new package: py-tempora

---

var/spack/repos/builtin/packages/openfoam/common/spack-Allwmake
var/spack/repos/builtin/packages/openfoam/package.py

- build:
no special treatment - already addressed in the spack-Allwmake script
- run:
use environment from the OpenFOAM etc/bashrc

Update openfoam to use new environment api (ref: #11115, 9ddc98e46a73)

---

var/spack/repos/builtin/packages/openpmd-api/package.py

JSON is not a compile-time variant anymore and a mandatory dependency from now on.

openPMD-api: JSON Always On

---

var/spack/repos/builtin/packages/acts-core/package.py
var/spack/repos/builtin/packages/py-cherrypy/package.py

cherrypy web framework.
Depends on #13582, #13583, #13584, #13585, #13586

New Package: py-cherrypy

---

var/spack/repos/builtin/packages/acts-core/package.py
var/spack/repos/builtin/packages/py-portend/package.py

tcp port monitoring and discovery package, dependency of cherrypy framework

New Package py-portend

---

var/spack/repos/builtin/packages/grpc/package.py

also fix pkg-config issue: grpc/grpc#20211

grpc: add version 1.24.3

---

var/spack/repos/builtin/packages/visit/package.py
var/spack/repos/builtin/packages/visit/parallel-hdf5.patch
var/spack/repos/builtin/packages/vtk/package.py

Should fix @rajeeja's HDF5 build issue in #13555 ; I had the same error as him but now can build successfully.
(The installed VisIt isn't working on my Mac -- somehow qwt when installed as a framework isn't being correctly set with an rpath.)

Fix visit+

---

var/spack/repos/builtin/packages/py-scipy/package.py

Add py-scipy 1.3.2

---

var/spack/repos/builtin/packages/nlohmann-json/package.py

Add the latest bugfix release of Nils Lohmann's JSON library.

nlohmann-json 3.7.2

---

lib/spack/spack/environment.py

Fixes #13529 
Fixes #13509
@becker33 @alalazo feel free to push additional commits to this if you want to add unit tests or modify the behavior. I've been using this for a few days now without any unintended side-effects.

Don't read Python env unless it is installed

---

var/spack/repos/builtin/packages/lcov/package.py

added lcov package

---

var/spack/repos/builtin/packages/trilinos/package.py

cc: @jwillenbring 
cc: @Rombur

trilinos: add version 12.18.1 with dtk-3.1

---

var/spack/repos/builtin/packages/athena/package.py
var/spack/repos/builtin/packages/mvapich2/package.py
var/spack/repos/builtin/packages/spectrum-mpi/package.py

refers to #13557 see https://github.com/spack/spack/pull/13557#discussion_r342394784

athena, mvapich2, spectrum-mpi: use new API to setup environment

---

var/spack/repos/builtin/packages/superlu-dist/package.py
var/spack/repos/builtin/packages/superlu-dist/xl-611.patch

superlu_dist: fix build with xl compilers

---

var/spack/repos/builtin/packages/mvapich2/package.py

closes #13691
Update MVAPICH2 package for 2.3.2 release
Update default build from psm to mrail

Update MVAPICH2 package for 2.3.2 release

---

var/spack/repos/builtin/packages/caliper/package.py

Also adds optional adiak dependency for v2.2+.

Add Caliper v2.2.0 and v2.1.1

---

var/spack/repos/builtin/packages/hwloc/package.py

Needed for https://github.com/spack/spack-tutorial/pull/24

hwloc: added 'master' version pointing at the HEAD of the master branch

---

lib/spack/spack/relocate.py

See: https://github.com/spack/spack/pull/13710
This duplicates a fix to develop over to the 0.13 release
@becker33

Binary packaging: correct relative symlinks

---

var/spack/repos/builtin/packages/trimgalore/package.py

Update to V0.6.4 for new functions

update to v0.6.4

---

var/spack/repos/builtin/packages/alquimia/package.py
var/spack/repos/builtin/packages/pflotran/package.py
var/spack/repos/builtin/packages/xsdk/package.py

~~This PR is for early review/comments, and is not yet ready for merge~~
~~Its has commits from other PRs [and workarounds] that won't be in the final set of changes.~~
~~https://github.com/spack/spack/pull/13661~~
~~[trilinos changes]~~
~~[metis changes]~~
~~i.e the PR is likely to only have changes for the following - and I would appreciate feedback/suggestions on these changes.~~
~~var/spack/repos/builtin/packages/alquimia/package.py~~
~~var/spack/repos/builtin/packages/pflotran/package.py~~
~~var/spack/repos/builtin/packages/xsdk/package.py~~
we are hoping to get this done by nov 15th
cc: @ulrikeyang
cc: @jwillenbring

xsdk 0.5.0

---

etc/spack/defaults/config.yaml
lib/spack/spack/binary_distribution.py
lib/spack/spack/schema/config.py
lib/spack/spack/util/gpg.py

This is a backport PR for the PR to develop of the same name.

Config option to allow gpg warning suppression

---

lib/spack/spack/relocate.py

Fix for issue #13754

---

var/spack/repos/builtin/packages/scalpel/package.py

Update scalpel package.py

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/cmd/create.py

Document use of the maintainers field

---

var/spack/repos/builtin/packages/py-xattr/package.py

py-xattr: fix a package that was pointing to a fork

---

var/spack/repos/builtin/packages/environment-modules/package.py

New feature release in the v4 series.
Release announcement: https://timeline.noticeable.io/cbzeG7wTvAIqj21zbUmx/posts/modules-4-4-0-released

environment-modules: add version 4.4.0

---

var/spack/repos/builtin/packages/clara/package.py

Add a package for the header only library Clara.

Added package for Clara command line parser

---

var/spack/repos/builtin/packages/jdk/package.py

Add old version of jdk

---

var/spack/repos/builtin/packages/py-gast/package.py

Add old version of py-gast

---

var/spack/repos/builtin/packages/tensorflow-serving-client/package.py

a standalone client library for tensorflow serving

tensorflow-serving-client: add new package

---

var/spack/repos/builtin/packages/ampliconnoise/Fix-return-type.patch
var/spack/repos/builtin/packages/ampliconnoise/package.py

Error:
```
error: non-void function 'outputCluster' should return a value [-Wreturn-type]
```
I fixed return type of function that error occured. 
Reference: https://code.google.com/archive/p/ampliconnoise/issues/20

ampliconnoise: Change return type of function.

---

var/spack/repos/builtin/packages/hmmer/package.py

hello
added latest version which compiled successfully

added hmmer v 3.3

---

var/spack/repos/builtin/packages/argobots/package.py
var/spack/repos/builtin/packages/bolt/package.py

This PR updates Argobots and BOLT.
- Argobots: 1.0rc2
- BOLT: 1.0rc3

update Argobots and BOLT

---

lib/spack/llnl/util/cpu/microarchitectures.json
lib/spack/spack/test/data/targets/linux-centos7-cascadelake
lib/spack/spack/test/llnl/util/cpu.py

Fixed detection for cascadelake microarchitecture

---

var/spack/repos/builtin/packages/likwid/package.py

Bump likwid version

---

var/spack/repos/builtin/packages/py-snowballstemmer/package.py

Fixes https://github.com/spack/spack/pull/13294#issuecomment-557585952
@obreitwi

Fix setuptools dependency in py-snowballstemmer

---

var/spack/repos/builtin/packages/py-scipy/package.py

Release notes: https://github.com/scipy/scipy/releases/tag/v1.3.3

Add py-scipy 1.3.3

---

var/spack/repos/builtin/packages/ncurses/package.py

Found here: https://api.travis-ci.org/v3/job/614871616/log.txt

ncurses: don't run strip internally

---

var/spack/repos/builtin/packages/lammps/package.py

Re-do of PR #13110
@adamjstewart : I didn't think I'd mess with spack/develop this much, but now I see the wisdom of branching to make new PRs.

Updated LAMMPS package to use gpu and kokkos options.

---

lib/spack/spack/build_systems/cuda.py
var/spack/repos/builtin/packages/cuda/package.py

add CUDA 10.2 support
CUDA 10.2 can be downloaded from https://developer.nvidia.com/cuda-downloads

add package cuda@10.2.89

---

var/spack/repos/builtin/packages/cmake/package.py

See https://gitlab.kitware.com/cmake/cmake/merge_requests/4066

cmake: add support for xlf and ninja

---

var/spack/repos/builtin/packages/sollve/package.py

I'm creating a pull request for a Spack package for the SOLLVE project, which will be built based on the Spack package for the LLVM project. The Spack package for the SOLLVE project would be used by application programmers of OpenMP applications, especially ECP OpenMP applications, to experiment with the latest features in SOLLVE project's software technologies.

Updating package for SOLLVE

---

var/spack/repos/builtin/packages/mstk/package.py

Added variant for enabling tests
Added option to retrieve variants
Split 'parallel=some_partitioner' variant into 'parallel=true/false' and 'partitioner=some_partitioner'
Added conflicts
General cleanup

Variant for enabling tests, versions, cleanup

---

lib/spack/spack/cmd/buildcache.py
lib/spack/spack/test/cmd/buildcache.py

buildcache list: do not display duplicate specs

---

lib/spack/spack/build_systems/intel.py
var/spack/repos/builtin/packages/intel-mpi/package.py
var/spack/repos/builtin/packages/intel-parallel-studio/package.py

Any PR that touches any Intel package will need this change in order to pass the unit tests.

IntelPackage: setup_env -> setup_build_env

---

var/spack/repos/builtin/packages/votca-csg/package.py
var/spack/repos/builtin/packages/votca-ctp/package.py
var/spack/repos/builtin/packages/votca-xtp/package.py

votca: help concretizer

---

var/spack/repos/builtin/packages/py-arrow/package.py

Fix py-pyarrow recipe

---

var/spack/repos/builtin/packages/py-setuptools-scm-git-archive/package.py

Build dependency for py-cheroot/py-cherrypy

scm-git-archive python package

---

var/spack/repos/builtin/packages/qmcpack/package.py

Mostly a minor update:
- Fix conflicts
- Fix variants
- Update QMCPACK testing option

QMCPACK Update Nov2019

---

var/spack/repos/builtin/packages/py-cartopy/package.py

Cartopy 0.17.0 works fine with proj 6

Update cartopy version and fix recipe

---

var/spack/repos/builtin/packages/aspect/package.py

This adds the latest release to the 'aspect' package.
@tjhei: We should add updating the spack package to our release-tasklist. Will do so in a follow-up.

Add version 2.1.0 to 'aspect' package

---

var/spack/repos/builtin/packages/opencascade/package.py

Adds the Open Cascade package from the official project git repository.

Add package opencascade

---

var/spack/repos/builtin/packages/portcullis/package.py
var/spack/repos/builtin/packages/sensei/package.py

This is a PR request for a recipe for SENSEI. There is only one new file.
I tested the recipe and wanted to make it available for all the users of Spack.
Thanks,
Sergei

Package/sensei: PR request for SENSEI (in situ analysis tool) recipe 

---

var/spack/repos/builtin/packages/kaldi/fujitsu_fix_version_analysis.patch
var/spack/repos/builtin/packages/kaldi/package.py

Change process of version analysis when using Fujitsu compiler.

kaldi: Change process of version analysis when using Fujitsu compiler.

---

var/spack/repos/builtin/packages/eospac/package.py

eospac: fix url

---

var/spack/repos/builtin/packages/hpcviewer/package.py

Add version 2019.09.  Adjust the iteration through versions to
eliminate the need for version_list.

hpcviewer: add version 2019.09

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Add the latest release of openPMD-api.

openPMD-api: 0.10.1

---

var/spack/repos/builtin/packages/flann/package.py

flann: fix missing dependencies

---

var/spack/repos/builtin/packages/polymake/package.py

polymake: fix dependency name

---

var/spack/repos/builtin/packages/elpa/package.py

Fix for https://github.com/spack/spack/pull/13530

elpa: port to microarch

---

var/spack/repos/builtin/packages/cbtf-krell/package.py

cbtf-krell: fix missing dependencies

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

Successfully installs and passes import tests on macOS 10.15.1 with Python 3.7.4 and Clang 11.0.0.
@Sinan81 @healther

TensorFlow: don't override HOME env var

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/s3_handler.py
lib/spack/spack/test/build_distribution.py
lib/spack/spack/test/cmd/mirror.py
lib/spack/spack/test/fetch_strategy.py
lib/spack/spack/test/s3_fetch.py
lib/spack/spack/test/web.py
lib/spack/spack/util/url.py
lib/spack/spack/util/web.py

Follows up on #11117.
- incorporate additional feedback from #11117 that was not merged.
- fix an issue preventing prefix queries on AWS-hosted S3 buckets
- adds more tests

Follow up/11117 fixes and testing

---

var/spack/repos/builtin/packages/tmux/package.py

This just adds newer versions of tmux to the existing package.

Update tmux to 3.0a

---

var/spack/repos/builtin/packages/llvm/package.py

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

llvm: fix for building llvm using Cray PE

---

var/spack/repos/builtin/packages/grass/package.py

Includes some fixes for Python 3 compatibility.

Add grass 7.8.2

---

var/spack/repos/builtin/packages/jdk/package.py

Fix JDK 8 download URLs

---

var/spack/repos/builtin/packages/sollve/package.py

This PR adds a stable version 1.0a2 to the SOLLVE package. (cc @vlkale)

sollve: add a version 1.0a2

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

https://docs.bazel.build/versions/master/user-manual.html#flag--verbose_failures
@adamjstewart

tf verbosity to better enable debugging

---

var/spack/repos/builtin/packages/clara/package.py
var/spack/repos/builtin/packages/half/package.py
var/spack/repos/builtin/packages/hydrogen/package.py
var/spack/repos/builtin/packages/lbann/package.py

Fixed an checksum for Hydrogen 1.3.2.  Cleaned up the Clara package to
not create an empty bin directory.

Added package for Half C++ header-only library.

---

var/spack/repos/builtin/packages/rose/package.py

- Added newest version of ROSE
- Modified to use new method of getting EDG
- Updated dependencies
- Removed older versions as they depend on resources that are no longer available or will be removed soon.
Closes #12983

Update and Fix ROSE Package

---

var/spack/repos/builtin/packages/dd4hep/package.py

Add new DD4hep release and some forgotten build requirements

---

var/spack/repos/builtin/packages/abseil-cpp/package.py

Initial add of abseil-cpp library

Add abseil-cpp package

---

var/spack/repos/builtin/packages/filebench/package.py

@adamjstewart 
Add a filebench package. however, it's a little complex in autoreconf() function, I'm not sure this style is OK or not.

add new package : filebench

---

var/spack/repos/builtin/packages/py-scikit-optimize/package.py

py-scikit-optimize: fix test dependency

---

var/spack/repos/builtin/packages/wireshark/package.py

wireshark: remove non-existing dependencies

---

var/spack/repos/builtin/packages/seacas/package.py

Added checksum and tag name for last two SEACAS releases.

SEACAS: Update to include new versions

---

var/spack/repos/builtin/packages/dmd/package.py

@weijianwen can you see if this fixes #14191?

dmd: setup dependent build environment

---

var/spack/repos/builtin/packages/py-scipy/package.py

Just a version bump to raise the required version of pybind11

Add py-scipy 1.4.1

---

var/spack/repos/builtin/packages/py-cinema-lib/package.py

This is a python package for cinema lib.

New package: cinema_lib

---

var/spack/repos/builtin/packages/acts-core/package.py

Just a couple of small ACTS releases to end the year.

Add new ACTS releases

---

var/spack/repos/builtin/packages/pgmath/libpgmath_symbols.patch
var/spack/repos/builtin/packages/pgmath/package.py

Temporary patch until a more permanent fix is implemented.

PGMATH library symbols patch

---

lib/spack/llnl/util/cpu/microarchitectures.json
lib/spack/spack/test/llnl/util/cpu.py

Fixed ppc optimization flags for clang

---

var/spack/repos/builtin/packages/bazel/package.py

As discussed in https://github.com/spack/spack/issues/14234#issuecomment-568017052

build bazel with jdk

---

var/spack/repos/builtin/packages/beagle/beagle.sh
var/spack/repos/builtin/packages/beagle/package.py

new module beagle

---

var/spack/repos/builtin/packages/openpmd-api/package.py

openPMD-api: 0.10.3

---

var/spack/repos/builtin/packages/awscli/package.py

Successfully installs on macOS 10.15.2 with Python 3.7.4 and Clang 11.0.0.

Add awscli 1.16.308

---

var/spack/repos/builtin/packages/libpaper/package.py

This PR adds the paper library to spack.

New package - libpaper

---

share/spack/qa/setup-env-test.sh

Someone forgot a `&`... no worries though!

Fix pipe redirect in `setup-env-test.sh`

---

var/spack/repos/builtin/packages/graphite2/package.py

This PR adds the Graphite2 package to Spack.

New package - graphite2

---

var/spack/repos/builtin/packages/teckit/package.py

This PR adds the teckit package to spack.

New package - TECkit

---

var/spack/repos/builtin/packages/py-asciitree/package.py

new package: py-asciitree

---

var/spack/repos/builtin/packages/zziplib/package.py
var/spack/repos/builtin/packages/zziplib/python2to3.patch

This PR adds the zziplib package.

New package - zziplib

---

var/spack/repos/builtin/packages/timemory/package.py

- Added 'develop' and '3.0.0' versions
- Added 'tau', 'upcxx', 'gotcha', and 'likwid'

Updated versions and more variants

---

var/spack/repos/builtin/packages/py-msgpack/package.py

new package: py-msgpack

---

var/spack/repos/builtin/packages/osu-micro-benchmarks/package.py

Added version 5.6.2 of osu-micro-benchmarks.

osu-micro-benchmarks: added version 5.6.2

---

lib/spack/spack/util/module_cmd.py

Similar to https://github.com/spack/spack/pull/14252

RHEL8 bugfix for module_cmd

---

var/spack/repos/builtin/packages/cloverleaf/package.py
var/spack/repos/builtin/packages/cloverleaf3d/package.py
var/spack/repos/builtin/packages/hpccg/package.py
var/spack/repos/builtin/packages/minighost/package.py
var/spack/repos/builtin/packages/minimd/package.py
var/spack/repos/builtin/packages/minismac2d/package.py
var/spack/repos/builtin/packages/minixyce/package.py
var/spack/repos/builtin/packages/pathfinder/package.py
var/spack/repos/builtin/packages/tealeaf/package.py

fix url for mantevo packages

---

var/spack/repos/builtin/packages/timemory/package.py

- this patch has a rather critical MT fix

Updated version to include v3.0.1

---

var/spack/repos/builtin/packages/py-numpy/package.py

Beginning with numpy > 1.16 when using older versions of gcc the
`std=c99` flag must be used. The Intel compiler depends on gcc for its
language extensions so the version of gcc is important. If the version
of gcc used by the Intel compiler is one that requires the `-std=c99`
flag then that flag will have to be used for a build with the Intel
compiler as well.
This PR tests the version of gcc used by the Intel compiler and will
abort the build if the gcc version is < 4.8 and inject the `-std=c99`
flag if >= 4.8 and < 5.1. This will cover the system gcc compiler and
any gcc environment module loaded at build time.

Get py-numpy > 1.16 to build with Intel compiler

---

var/spack/repos/builtin/packages/nsimd/package.py

NSIMD is a vectorization library that abstracts SIMD programming. It was designed to exploit the maximum power of processors at a low development cost.

Nsimd: New package

---

var/spack/repos/builtin/packages/qt/package.py

Fixes #13650. Should be extensible to future 'platform' arguments as needed.

Fix QT on Linux+clang

---

share/spack/spack-completion.bash

@tgamblin I'm not sure how much longer I can keep doing this. How much work would it be to make a bot that pops up on a PR and says "don't forget to update the tab completion script!" every time someone edits a file in `lib/spack/spack/cmd`?
@JBlaschke please use this version when you start working on your fish tab completion script.

Fix outdated bash tab completion

---

var/spack/repos/builtin/packages/opencv/package.py

Add a new variant: cudacodec and fix a related build error.
Fixes #14367

Package/opencv: cudacodec fix

---

var/spack/repos/builtin/packages/r-ldheatmap/package.py

depends on `r-genetics` in #14403, `r-snpstats` in #14404

r-ldheatmap: new package at 0.99-7

---

var/spack/repos/builtin/packages/py-python-rapidjson/package.py
var/spack/repos/builtin/packages/py-rapidjson/package.py

depends on new packages `py-yajl` in #14278 and `py-ujson` in #14279

py-rapidjson: new package at 0.9.1

---

var/spack/repos/builtin/packages/cmake/package.py

cmake: Create an optimized release build

---

var/spack/repos/builtin/packages/lrslib/fix-return-value.patch
var/spack/repos/builtin/packages/lrslib/package.py

I fixed return value because following error occured.
`error: non-void function 'lrs_solve_nash' should return a value [-Wreturn-type]`
Ref: https://github.com/mkoeppe/lrslib/commit/2e8c5bd6c06430151faea5910f44aa032c4178a9

lrslib: Fix return value

---

var/spack/repos/builtin/packages/qt/package.py
var/spack/repos/builtin/packages/qt/qt5_11-intel-overflow.patch
var/spack/repos/builtin/packages/qt/qt5_12-intel-overflow.patch

fix build for qt5 and the Intel compiler

---

var/spack/repos/builtin/packages/fairlogger/package.py

FairLogger: new package

---

var/spack/repos/builtin/packages/py-syned/package.py

add py-syned

---

var/spack/repos/builtin/packages/librsb/package.py

Related to issue #14454 (new package: librsb)

new package: librsb

---

var/spack/repos/builtin/packages/libfabric/package.py

Add support for (just about) every provider libfabric knows about

Support for more libfabric providers

---

var/spack/repos/builtin/packages/verrou/package.py

...and add myself as a maintainer.

verrou: Add support for verrou v2.2.0

---

var/spack/repos/builtin/packages/flang/package.py

Support for OpenMP 4.5 in Flang

Flang OpenMP target support for NVidia GPUs.

---

var/spack/repos/builtin/packages/codar-cheetah/package.py

Update to the ECP codar-cheetah software to include new release.
- Kshitij Mehta
ORNL
https://csmd.ornl.gov/profile/kshitij-mehta

codar-cheetah: Added version 0.5

---

var/spack/repos/builtin/packages/mstk/package.py

MSTK was patched to fix a flaw in unittest++ discovery. Updating spackage to use this patched version

Update MSTK to 3.3.1

---

var/spack/repos/builtin/packages/variorum/package.py

Update var/spack/repos/builtin/packages/variorum/package.py
Initial release v0.1.0 for SC19

new package: variorum

---

var/spack/repos/builtin/packages/hpctoolkit/package.py

Add version 2019.12.28 and update the prereqs for the latest master.

hpctoolkit: add version 2019.12.28

---

var/spack/repos/builtin/packages/perl/package.py

This also fixes actually building the development releases.

perl: Add 5.30.1 (and 5.31.7)

---

var/spack/repos/builtin/packages/octave/package.py

Add version Octave 5.1.0 including sha256.

octave: add 5.1.0

---

var/spack/repos/builtin/packages/python/package.py

Add include/pythonX.Y to CPATH

---

var/spack/repos/builtin/packages/jdk/package.py

Add a new version of JDK8 that fetches with no issues.

jdk8 new version

---

var/spack/repos/builtin/packages/casacore/package.py

My first Spack PR. I tried to meet the guidelines, but it is unclear whether you'd prefer this broken into multiple PRs, one per commit. Happy to resubmit, if needed.
Note that I have contributed to the upstream casacore package in the past, and I'm currently working on fixes to issues in the casacore build for which I've put in place workarounds in this PR. I hope to be able to follow up with another PR for the casacore package once the upstream is fixed.

Updates to casacore package

---

lib/spack/spack/package.py
var/spack/repos/builtin/packages/py-spdlog/package.py

This PR adds the py-spdlog package.

Added py-spdlog package

---

var/spack/repos/builtin/packages/capnproto/package.py

capnproto: New package.

---

var/spack/repos/builtin/packages/conduit/package.py

and allow conduit to build against statically linked python

add conduit 0.5.1 release 

---

var/spack/repos/builtin/packages/aws-parallelcluster/package.py

Signed-off-by: Sean Smith <seaam@amazon.com>

Update AWS ParallelCluster to 2.5.1

---

var/spack/repos/builtin/packages/cmake/fix-xlf-ninja-mr-4075.patch
var/spack/repos/builtin/packages/cmake/package.py

Looks like the checksum changed again (see #14125).
@chuckatkins

cmake: Fix patch checksum

---

var/spack/repos/builtin/packages/py-scipy/package.py

New release in there LTS Python 2 version of scipy.

Add py-scipy 1.2.3

---

var/spack/repos/builtin/packages/m4/package.py
var/spack/repos/builtin/packages/m4/test/hello.m4
var/spack/repos/builtin/packages/m4/test/hello.out

Preliminary m4 smoke tests:
- Check executable
- Check version
- Check transformation gets expected output

tests: Preliminary m4 smoke tests

---

var/spack/repos/builtin/packages/perl/package.py

This is the third case/example of a simple smoke test.

tests: Added preliminary smoke test for perl

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

Fixes multiple security vulnerabilities: https://github.com/tensorflow/tensorflow/releases/tag/v1.15.1

Add TensorFlow 1.15.1

---

var/spack/repos/builtin/packages/p3dfft3/package.py

Rework p3dfft3 package based on contribution by @SheraLee at https://github.com/spack/spack/issues/14458
Partially fixes some issues.

Rework p3dfft3

---

var/spack/repos/builtin/packages/llvm/package.py

With #14389 the `flang` package uses `llvm-flang` for it's llvm fork dependency.  This PR removes the flang support that is in the main `llvm` package.

Removing flang variant from llvm package

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

Fixes some security vulnerabilities: https://github.com/tensorflow/tensorflow/releases/tag/v2.0.1

Add TensorFlow 2.0.1

---

lib/spack/spack/test/data/config/config.yaml

Set module_roots in test/config/config.yaml to defaults.

---

var/spack/repos/builtin/packages/mpifileutils/package.py

Signed-off-by: Adam Moody <moody20@llnl.gov>

mpifileutils: add v0.10

---

lib/spack/spack/cmd/load.py

before, a 'time spack load singularity'
4.129u 0.346s 0:04.47 99.7%	0+0k 0+8io 0pf+0w
after, a 'time spack load singularity'
0.844u 0.319s 0:01.16 99.1%	0+0k 0+16io 0pf+0w

make the new 'spack load' faster

---

var/spack/repos/builtin/packages/py-theano/package.py
var/spack/repos/builtin/packages/qt/package.py

Only change the flags for libpng, zlib, libjpeg. Not sure if a similar change is necessary for other libraries (openssl, harfbuzz, etc).

Fix for #14148

---

var/spack/repos/builtin/packages/xsbench/package.py

Added version 19 to xsbench spackage
Part of https://github.com/spack/spack/issues/14669

Added xsbench@19 to Version List

---

var/spack/repos/builtin/packages/miniamr/package.py

Added version 1.4.4 to MiniAMR spackage
Part of https://github.com/spack/spack/issues/14669

Added MiniAMR@1.4.4

---

var/spack/repos/builtin/packages/gdal/package.py

https://github.com/OSGeo/gdal/blob/v3.0.4/gdal/NEWS

Add GDAL 3.0.4

---

lib/spack/docs/workflows.rst

Decided to finally drop Homebrew and Conda in favor of Spack for all of my software installation needs. This PR documents the process.
@svenevs @tgamblin

Document how to use Spack to replace Homebrew/Conda

---

var/spack/repos/builtin/packages/octave/package.py

This gives us someone to ping when octave-related issues/PRs come up.
Thanks to @mtmiller for volunteering!

octave: add maintainer

---

var/spack/repos/builtin/packages/clingo/package.py

clingo: new versions

---

var/spack/repos/builtin/packages/qt/package.py

Update the correct qmake.conf files and use the correct `-platform` flag when using intel compilers.

Update QT to build on Intel

---

var/spack/repos/builtin/packages/llvm/package.py

This PR adds a new version of llvm and fixes the dependency specs.
- This package depends on libtinfo in all cases so change the ncurses
dependency to reflect that
- if +lldb is in the spec but +python is not then do not build the lldb
python support
- build lldb python support only if +python is in the spec with +lldb
- install the llvm python bindings if +python is in the spec
- install the clang python bindings if +clang and +python are in the spec
- Fixes for conflicts with ~clang
- Fix typo in conflict of compiler-rt and flang

Update llvm, adjust dependency specs and conflicts

---

var/spack/repos/builtin/packages/grpc/package.py

add new versions: 1.25.0, 1.26.0 and 1.27.0

grpc: add new versions

---

var/spack/repos/builtin/packages/subread/package.py

Update subread package.py

---

var/spack/repos/builtin/packages/python/package.py

Fixes https://github.com/spack/spack/issues/14792
(Added) Fixes https://github.com/spack/spack/issues/13637
~Fixes (edit: no longer) https://github.com/spack/spack/issues/14793~
~(Added) Fixes (pending resolution of https://github.com/spack/spack/issues/14827#issuecomment-583638144) #14827~
(Added) Closes https://github.com/spack/spack/pull/14844
~(Added) Closes (edit: no longer) https://github.com/spack/spack/pull/14845~

Fix ParaView build.

---

var/spack/repos/builtin/packages/r-dbi/package.py
var/spack/repos/builtin/packages/r-rmariadb/package.py

This PR creates the r-rmariadb package. It also includes an update to
the r-dbi package as a newer version of that is needed.

New package - r-rmariadb

---

var/spack/repos/builtin/packages/octave/package.py

Add version Octave 5.2.0 including sha256.

octave: add 5.2.0

---

var/spack/repos/builtin/packages/openblas/package.py

Add version OpenBLAS 3.8.0 including sha256.

openblas: add 3.8.0

---

var/spack/repos/builtin/packages/r-adgoftest/package.py
var/spack/repos/builtin/packages/r-copula/package.py
var/spack/repos/builtin/packages/r-gsl/package.py
var/spack/repos/builtin/packages/r-pspline/package.py
var/spack/repos/builtin/packages/r-stabledist/package.py

This PR adds the r-copula package and dependencies.
- new package: r-adgoftest
- new package: r-gsl
- new package: r-pspline
- new package: r-stabledist

New package: r-copula

---

var/spack/repos/builtin/packages/r-aroma-light/package.py
var/spack/repos/builtin/packages/r-pscbs/package.py
var/spack/repos/builtin/packages/r-r-cache/package.py
var/spack/repos/builtin/packages/r-r-oo/package.py

This PR adds the r-pscbs package along with new dependencies and updates.
- new package: r-aroma-light
- new package: r-r-cache
- updated package: r-r-oo

New package: r-pscbs

---

var/spack/repos/builtin/packages/r-bmp/package.py
var/spack/repos/builtin/packages/r-imager/package.py
var/spack/repos/builtin/packages/r-readbitmap/package.py

This PR adds the r-imager package and dependencies.
- new package: r-bmp
- new package: r-readbitmap

New package: r-imager

---

var/spack/repos/builtin/packages/acts-core/package.py

Yet another ACTS release ;) With a couple of build system adjustments this time.

[acts-core] Support ACTS v0.16.0

---

var/spack/repos/builtin/packages/r-biomartr/package.py
var/spack/repos/builtin/packages/r-curl/package.py
var/spack/repos/builtin/packages/r-philentropy/package.py

This PR creates the r-biomartr package as well as needed new packages
and updates.
- new dependency: r-philentropy
- update: r-curl

New package - r-biomartr

---

lib/spack/spack/database.py
lib/spack/spack/test/cmd/find.py
lib/spack/spack/test/database.py
var/spack/repos/builtin.mock/packages/hdf5/package.py

Fix over-relaxed database query

---

var/spack/repos/builtin/packages/intel-llvm/package.py

Currently I have only included functionality to install this compiler with SyCL support using their directions here https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#build-sycl-toolchain

Adding Intel LLVM compiler

---

var/spack/repos/builtin/packages/avizo/package.py

Trying to install Avizo, i get "Error: NameError: name 'run_env' is not defined". Correcting it to be just "env"

Fix run environment

---

var/spack/repos/builtin/packages/git/package.py

As discussed in:
https://spackpm.slack.com/archives/C5VL7V81G/p1581394270058800

Add missing dep to git.

---

var/spack/repos/builtin/packages/r-aod/package.py
var/spack/repos/builtin/packages/r-exomedepth/package.py

This PR adds the r-exomedepth package and r-aod as a dependency.

New package: r-exomedepth

---

var/spack/repos/builtin/packages/r-bsgenome-hsapiens-ucsc-hg19/package.py
var/spack/repos/builtin/packages/r-codex/package.py

This PR adds the r-codex package.
- new package: r-bsgenome-hsapiens-ucsc-hg19

New package: r-codex

---

var/spack/repos/builtin/packages/cub/package.py
var/spack/repos/builtin/packages/nccl/package.py

Updated both cub and nccl versions.  Fixed a bug in the cub download

---

lib/spack/spack/cmd/compiler.py

spack compiler info: quick fix for failing command

---

var/spack/repos/builtin/packages/metall/package.py

Add a new package: Metall

---

var/spack/repos/builtin/packages/gdb/package.py

gdb: fix installation

---

var/spack/repos/builtin/packages/powerapi/package.py

This is a pull request to add support for a newer version of PowerAPI. PowerAPI does not use a consistent versioning scheme and it does not have regular releases so the date of the commit is being used as the version.

package: Add newer version of PowerAPI package

---

var/spack/repos/builtin/packages/mercurial/package.py

Thanks to @eugeneswalker for noticing that this is completely broken. I'm not sure how long it's been broken for, but adding `output=str` fixes the issue.
Also added the latest version while I was at it. Successfully builds on macOS 10.15.3 with Clang 11.0.0 and Python 3.7.6.
```console
$ /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/mercurial-5.3-mpjblgfmwfpdktq4codfopllzktyabzz/bin/hg debuginstall
checking encoding (UTF-8)...
checking Python executable (/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-3gaqcongtvfw2l553jlr5lz3pug2z27w/bin/python3.7)
checking Python version (3.7.6)
checking Python lib (/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-3gaqcongtvfw2l553jlr5lz3pug2z27w/lib/python3.7).. …
```

Fix mercurial certificate finding, add latest version

---

var/spack/repos/builtin/packages/openblas/openblas-0.3.8-darwin.patch
var/spack/repos/builtin/packages/openblas/package.py

See https://github.com/xianyi/OpenBLAS/issues/2431, patched in
https://github.com/xianyi/OpenBLAS/issues/2424 .

Fix OpenBLAS 0.3.8 build on darwin

---

var/spack/repos/builtin/packages/hepmc/package.py

- Update CMake requirement per latest master
- Account for Python variant, add python dependency if used
- Account for ROOT I/O variant, add ROOT dependency if used

[hepmc] Finish the HepMC3 spackage update

---

var/spack/repos/builtin/packages/qmcpack/package.py

Include latest 3.9.x releases of QMCPACK

QMCPACK Update - February 2020

---

lib/spack/docs/packaging_guide.rst

Docs: configure_args -> cmake_args

---

var/spack/repos/builtin/packages/libfabric/package.py

Depends: #15058
libfabric used to install fabtests only when installed using --test. fabtests has tools that are useful on a running system, so they should be installed always.
* Rewrote the build/install part to always install fabtests alongside libfabric.
* Updated a few fabtests resources.
* Updated the test related stuff. Works for most versions now.
* Include tcp and udp fabrics so that the test suite works.

libfabric: Always install fabtests

---

var/spack/repos/builtin/packages/py-irpf90/package.py

IRPF90 is a python program which can be installed with
```
pip install irpf90
```

Package for IRPF90

---

var/spack/repos/builtin/packages/igv/package.py

Noticed that this was removed some time ago during the license shenanigans. A previous version of this we had installed is broken so I thought I'd make a new package with the current version of igv.

adding package igv

---

var/spack/repos/builtin/packages/decentralized-internet/package.py

Hi, we have added our package to the Spack repository. Please let us know if you need anything else.

Add decentralized-internet package

---

var/spack/repos/builtin/packages/qt/package.py

Fixes https://github.com/spack/spack/issues/15140 .

Disable qt3d when opengl is disabled

---

var/spack/repos/builtin/packages/lbann/package.py

A new dependency on clara was added, and the Conduit CMake flags were changed.
Tagging @bvanessen for review.

Changes necessary to build lbann@develop

---

var/spack/repos/builtin/packages/sundials/package.py

sundials: add version 5.1.0 and trilinos variant

---

var/spack/repos/builtin/packages/py-rseqc/package.py

This PR depends on #15175
- add updated version
- set depedencies

Update py-rseqc package

---

var/spack/repos/builtin/packages/py-bx-python/package.py
var/spack/repos/builtin/packages/py-python-lzo/package.py

- add update to py-bx-python
- switch to pypi downloads
- set dependencies

Update py-bx-python package

---

var/spack/repos/builtin/packages/suite-sparse/package.py

Release notes: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v5.7.1
Version 5.7.0 was an incomplete release.

suite-sparse: add version 5.7.1

---

var/spack/repos/builtin/packages/qrupdate/package.py

- When compiling qrupdate with `FFLAGS=-fdefault-integer-8` it can be perfectly used for larger problem dimensions.
- Improved the readability of the file with the added rules.

qrupdate: ILP64 support

---

lib/spack/spack/ci.py
lib/spack/spack/cmd/buildcache.py
share/spack/spack-completion.bash

replaces the --no-deps option
```
$ spack install m4
...
$ spack buildcache create -d ./only-deps --only dependencies -a --unsigned m4
...
$ spack buildcache create -d ./only-pkg --only package -a --unsigned m4
...
$ spack buildcache create -d ./both -a --unsigned m4
...
```
```
$ find only-deps/ only-pkg/ both/
only-deps/
only-deps/build_cache
only-deps/build_cache/linux-centos7-haswell
only-deps/build_cache/linux-centos7-haswell/gcc-4.8.5
only-deps/build_cache/linux-centos7-haswell/gcc-4.8.5/libsigsegv-2.12
only-deps/build_cache/linux-centos7-haswell/gcc-4.8.5/libsigsegv-2.12/linux-centos7-haswell-gcc-4.8.5-libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3.spack
only-deps/build_cache/linux-centos7-haswell-gcc-4.8.5-libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3.spec.yaml …
```

add --only option to buildcache create cmd

---

lib/spack/docs/basic_usage.rst

This PR corrects a few minor things and adds a note about colorized
output.

A few edits for the Basic Usage Doc page

---

var/spack/repos/builtin/packages/py-arviz/package.py
var/spack/repos/builtin/packages/py-pymc3/package.py

This PR adds py-pymc3 and py-arviz as a dependency.

New packages: py-pymc3 and py-arviz

---

var/spack/repos/builtin/packages/py-cnvkit/package.py
var/spack/repos/builtin/packages/py-pomegranate/package.py

The py-pomegranate package is a dependency of py-cnvkit

new package: py-cnvkit and py-pomegranate

---

var/spack/repos/builtin/packages/sz/package.py

added a few more functions and fixed a tiny printf issue.

release sz 2.1.8.3

---

var/spack/repos/builtin/packages/libsndfile/package.py
var/spack/repos/builtin/packages/py-audioread/package.py
var/spack/repos/builtin/packages/py-librosa/package.py
var/spack/repos/builtin/packages/py-llvmlite/package.py
var/spack/repos/builtin/packages/py-numba/package.py
var/spack/repos/builtin/packages/py-resampy/package.py
var/spack/repos/builtin/packages/py-soundfile/package.py

This PR adds the py-librosa package, along with new dependency packages
and some updates of existing dependency packages.
- new package: py-audioread
- new package: py-resampy
- new package: py-soundfile
- update package: py-numba
- update package: py-llvmlite
py-numba:
- add updated version
- adjust constraints
py-llvmlite:
- add updated version
- adjust constraints
- fix version specifications for llvm
- add environment function to set PIC

New package: py-librosa

---

var/spack/repos/builtin/packages/gsl/gsl-2.3-cblas.patch
var/spack/repos/builtin/packages/gsl/package.py

@mgorny is the original author of the patch, but it has been used in gentoo for a while.

gsl: build against external cblas

---

var/spack/repos/builtin/packages/clhep/package.py
var/spack/repos/builtin/packages/g4abla/package.py
var/spack/repos/builtin/packages/g4emlow/package.py
var/spack/repos/builtin/packages/g4ensdfstate/package.py
var/spack/repos/builtin/packages/g4ndl/package.py
var/spack/repos/builtin/packages/g4neutronxs/package.py
var/spack/repos/builtin/packages/g4photonevaporation/package.py
var/spack/repos/builtin/packages/g4pii/package.py
var/spack/repos/builtin/packages/g4radioactivedecay/package.py
var/spack/repos/builtin/packages/g4realsurface/package.py
var/spack/repos/builtin/packages/g4saiddata/package.py
var/spack/repos/builtin/packages/g4tendl/package.py
var/spack/repos/builtin/packages/geant4-data/package.py
var/spack/repos/builtin/packages/geant4/package.py
var/spack/repos/builtin/packages/root/package.py

Volunteering myself as maintainer for the main Geant4 packages, plus ROOT!

Add @drbenmorgan as maintainer for core HEP packages

---

var/spack/repos/builtin/packages/ucx/package.py

UCX: add 1.7.0

---

var/spack/repos/builtin/packages/mrcpp/package.py

Recipe for the [MRCPP](http://mrcpp.readthedocs.io) MultiResolution Computation Program Package. MRCPP is a general purpose numerical mathematics library based on multiresolution analysis and the multiwavelet basis which provide low-scaling algorithms as well as rigorous error control in numerical computations.
@stigrj, @ilfreddy do you agree to be co-maintainers?

MRCPP: New package.

---

var/spack/repos/builtin/packages/hpctoolkit/package.py

Add version 2020.03.01, deprecate Blue Gene to 2019.12.28 and earlier,
tighten a few dependencies.

hpctoolkit: add version 2020.03.01

---

var/spack/repos/builtin/packages/qgis/package.py

fix typos in the newly created package #12388 
@adamjstewart

QGIS: fix typos

---

var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/trilinos/package.py

cherry-picking global ordinal type variant selector from [this pull request](https://github.com/spack/spack/pull/14215) and setting dealii to GO int, to make it compile again

Fix compiling dealii with trilinos@master

---

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py

Fix https://github.com/spack/spack/issues/14669

ecp-proxy-apps: version bump

---

var/spack/repos/builtin/packages/fd-find/package.py

Add package for fd-find:
A simple, fast and user-friendly alternative to 'find'.

New package: fd-find

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Add the latest release of openPMD-api.

openPMD-api: 0.11.0

---

var/spack/repos/builtin/packages/bat/package.py

Add package for bat:
A cat(1) clone with wings.

New package: bat

---

lib/spack/spack/modules/common.py
lib/spack/spack/test/install.py
lib/spack/spack/test/modules/common.py

Fix for being able to 'spack load' packages that have been renamed.

---

var/spack/repos/builtin/packages/sirius/package.py

- new versions `6.4.4`, `6.5.0`
- `@develop`, `@master`  dependency on SpFFT added

Update SIRIUS package

---

lib/spack/spack/spec.py
lib/spack/spack/test/architecture.py

Fix ArchSpec.satisfies when not concrete and strict is true

---

var/spack/repos/builtin/packages/gunrock/package.py

High-Performance Graph Primitives on GPUs

new package: GunRock

---

var/spack/repos/builtin/packages/gromacs/package.py

Gromacs: new version 2020.1

---

var/spack/repos/builtin/packages/openmpi/package.py

openmpi: add version 4.0.3

---

var/spack/repos/builtin/packages/libfabric/package.py

See https://github.com/spack/spack/pull/15337 and https://github.com/spack/spack/issues/15244
@ax3l @carns

Update libfabric to 1.9.1

---

var/spack/repos/builtin/packages/axl/package.py
var/spack/repos/builtin/packages/er/package.py
var/spack/repos/builtin/packages/filo/package.py
var/spack/repos/builtin/packages/kvtree/package.py
var/spack/repos/builtin/packages/rankstr/package.py
var/spack/repos/builtin/packages/redset/package.py
var/spack/repos/builtin/packages/scr/package.py
var/spack/repos/builtin/packages/shuffile/package.py
var/spack/repos/builtin/packages/spath/package.py

SCR switched over to building on top of components. See https://ecp-veloc.github.io/component-user-docs/.

SCR: build with components

---

.github/workflows/linux_build_tests.yaml
.github/workflows/minimum_python_versions.yaml

Minor updates to CI configuration

---

var/spack/repos/builtin/packages/acts-core/package.py

Yet another uneventful ACTS release as far as build systems go.

[acts-core] Add version 0.17

---

var/spack/repos/builtin/packages/unqlite/package.py

added unqlite package

---

var/spack/repos/builtin/packages/silo/package.py

Silo does not build with HDF5 1.12.

silo: depends on hdf5@:1.10.999

---

var/spack/repos/builtin/packages/veccore/package.py

Pending merge of https://github.com/spack/spack/pull/14376 . Prerequisite to https://github.com/spack/spack/pull/14520

Add package VecCore

---

var/spack/repos/builtin/packages/seacas/package.py

Add two latest releases of SEACAS

SEACAS: New versions

---

var/spack/repos/builtin/packages/qmcpack/package.py

QMCPACK Update March 2020 

---

var/spack/repos/builtin/packages/cctools/package.py

Updates to CCTools version 7.1.0.

Cctools 7.1.0

---

lib/spack/docs/build_systems/sippackage.rst
lib/spack/spack/build_systems/sip.py
var/spack/repos/builtin/packages/py-pyqt4/package.py
var/spack/repos/builtin/packages/py-pyqt5/package.py
var/spack/repos/builtin/packages/py-sip/package.py

Use python extend_path as pyqt sip fix

---

var/spack/repos/builtin/packages/mxnet/package.py
var/spack/repos/builtin/packages/py-horovod/package.py
var/spack/repos/builtin/packages/py-torch/package.py

Fixes #15545 
@rblake-llnl @rvinaybharadwaj can you test this? 
P.S. if anyone else would like to be added as a maintainer, let me know.

py-horovod: set appropriate build env vars

---

var/spack/repos/builtin/packages/cosma/package.py

Distributed Communication-Optimal Matrix-Matrix Multiplication Library
https://github.com/eth-cscs/COSMA

cosma: added package at v2.0.2

---

var/spack/repos/builtin/packages/mvapich2/package.py

* Update MVAPICH2 package for 2.3.3 release by editing the url and adding the sha256sum hash
@harisubramoni

Update MVAPICH2 package for 2.3.3 release

---

var/spack/repos/builtin/packages/spdlog/package.py

Added two new versions of spdlog (1.4.2 and 1.5.0).

Added two new versions of spdlog

---

var/spack/repos/builtin/packages/root/package.py

* Add version 6.20, don't yet mark it preferred
* It needs zstd
* It needs numpy
* Reorder python dependencies a bit
maintainer ping: @chissg @HadrienG2 @drbenmorgan

root: Add version 6.20.0

---

var/spack/repos/builtin/packages/py-dgl/package.py

Successfully installs on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.0.

py-dgl: add new package

---

var/spack/repos/builtin/packages/freeipmi/package.py

Added freeipmi package. Configure and build work fine, install only as root,
thus added warning and added reference to issue #4432 .

freeipmi: Initial commit

---

var/spack/repos/builtin/packages/py-dgl/package.py

Successfully installs (AND PASSES ALL TESTS) on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.0.

Fix bug in py-dgl installation, add unit tests

---

lib/spack/spack/test/conftest.py

Currently only the `mutable_config` fixture clears out the cached compiler configuration file in `spack.compilers`, but really *any* new configuration should do this.
This becomes an issue when running tests within an environment, because compiler configuration ends up being queried earlier, and the user's real config "leaks" into the cache.  Outside an environment, the cache is never set until tests touch it, so we weren't seeing this issue.

bugfix: mock configs should also mock compiler cache

---

var/spack/repos/builtin/packages/lmod/package.py

Add lmod version 7.8.1 and corresponding checksum.

package: add lmod version 7.8.1

---

lib/spack/spack/cmd/repo.py
lib/spack/spack/repo.py
lib/spack/spack/test/cmd/repo.py

Separating out minor refactoring commits while working towards #15443

spack.repo: remove "import from" statements

---

var/spack/repos/builtin/packages/singularity/package.py

Add version 3.5.3 and checksum to singularity package.

Add version 3.5.3 to singularity package

---

var/spack/repos/builtin/packages/pmix/package.py

Add checksum for pmix version 2.2.3.

package: add pmix version 2.2.3

---

var/spack/repos/builtin/packages/acts-core/package.py

Boost requirement change was already submitted in a previous PR.

[acts-core] Add version 0.19

---

var/spack/repos/builtin/packages/mothur/package.py

specify version of vsearch

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Add the latest release with HDF5-1.12 compatibility.

openPMD-api: 0.11.1

---

var/spack/repos/builtin/packages/darshan-runtime/package.py
var/spack/repos/builtin/packages/darshan-util/package.py

Add dashan-util version 3.1.8 and checksum.

package: add dashan-util version 3.1.8 and checksum

---

var/spack/repos/builtin/packages/med/package.py

med: update package with version 4.0.0

Update med package with version 4.0.0

---

var/spack/repos/builtin/packages/iwyu/iwyu-013-cmake.patch
var/spack/repos/builtin/packages/iwyu/package.py

Add the iwyu package. The patch file necessary to build has been submitted upstream at https://github.com/include-what-you-use/include-what-you-use/pull/781 .

Add include-what-you-use

---

var/spack/repos/builtin/packages/python/package.py

fix gdb installation

---

var/spack/repos/builtin/packages/py-tensorflow/0001-Remove-contrib-cloud-bigtable-and-storage-ops-kernel.patch
var/spack/repos/builtin/packages/py-tensorflow/package.py

Clean up/simplify the installation, make sure the headers are installed so that horovod can find them successfully. Fix the 2.0.* builds.

TensorFlow: Make horovod compilation work

---

var/spack/repos/builtin/packages/qmcpack/package.py
var/spack/repos/builtin/packages/quantum-espresso/package.py

- Add support for ppconvert
- Fix broken install method
- Fix broken setup_run_environment method so that nexus will work
- General clean-up, e.g. intel-mkl conditional statement

QMCPACK Update March 2020 - Part 2

---

var/spack/repos/builtin/packages/lesstif/package.py

This PR provides the lesstif package

New package lesstif

---

var/spack/repos/builtin/packages/mesa-glu/package.py

Adding mesa-glu 9.0.1 (2019)

---

var/spack/repos/builtin/packages/magma/package.py

magma now extends CudaPackage class, taking care of the gcc conflicts

---

var/spack/repos/builtin/packages/qgis/package.py

- add new  versions
- also order main dependencies alphabetically

Package/qgis add versions 3.10.4 3.12.1

---

var/spack/repos/builtin/packages/xsbench/package.py

xsbench: fix build of v19

---

var/spack/repos/builtin/packages/ddd/package.py

This PR adds new package ddd.  It is dependent on the merge of PR #15703

new package ddd

---

var/spack/repos/builtin/packages/py-python-swiftclient/package.py
var/spack/repos/builtin/packages/py-swiftclient/package.py

Python Swift-client package for Swift API client.

Add package swiftclient

---

var/spack/repos/builtin/packages/gdrcopy/package.py

provides the userspace libraries for gdrcopy.

New package: gdrcopy

---

var/spack/repos/builtin/packages/git/package.py

Update git version to 2.26.0

---

var/spack/repos/builtin/packages/py-horovod/fma.patch
var/spack/repos/builtin/packages/py-horovod/package.py

Closes https://github.com/horovod/horovod/issues/1832
@tgaddair let me know if you see anything else wrong with our build recipe. Also, if you or any other Horovod developers would like to be listed as "maintainers" of this package, let me know.

py-horovod: fix compilation of ~cuda

---

var/spack/repos/builtin/packages/helics/package.py

A library/framework for synchronizing time and data between different simulators.

helics: add new package

---

var/spack/repos/builtin/packages/superlu-dist/package.py

superlu-dist: add new version 6.3.0

---

var/spack/repos/builtin/packages/gmt/package.py

Successfully installs on Scientific Linux 6 with GCC 6.1.0.
The build still picks up a lot of system libraries, but I haven't yet found a way to avoid that.

GMT: add 6.0.0

---

var/spack/repos/builtin/packages/py-pybind11/package.py

Add pybind 2.5.0.
Adjust for improved include helpers for pybind11.
Ref.: https://github.com/pybind/pybind11/pull/1995

pybind11 2.5.0: Include Change

---

.flake8_packages
CHANGELOG.md
lib/spack/docs/basic_usage.rst
lib/spack/docs/build_systems/intelpackage.rst
lib/spack/docs/containers.rst
lib/spack/docs/getting_started.rst
lib/spack/docs/packaging_guide.rst
lib/spack/docs/pipelines.rst
lib/spack/docs/workflows.rst

Fix some spelling errors in docs

Spelling fixes

---

var/spack/repos/builtin/packages/lua/package.py

Fixed removal of remaining references and symlinks to so files when building lua with static libraries

Fixed Missed Shared Object Logic in Lua Spackage

---

var/spack/repos/builtin/packages/opendx/package.py

Currently seeing build issues on macOS, hoping I can at least get it installed on Linux...

[WIP] OpenDX: add new package

---

var/spack/repos/builtin/packages/laghos/package.py

Added v3 of Laghos as per
https://github.com/CEED/Laghos/blob/v3.0/README.md

Added v3 of Laghos

---

var/spack/repos/builtin/packages/openssl/package.py

openssl: add v1.1.1f

---

var/spack/repos/builtin/packages/dhpmm-f/package.py

New package:dhpmm-f

---

var/spack/repos/builtin/packages/argobots/package.py

Adds a new Argobots version 1.0

argobots: new version 1.0

---

var/spack/repos/builtin/packages/py-gluoncv/no-unicode-readme.patch
var/spack/repos/builtin/packages/py-gluoncv/package.py

Depends on #15854.  
Replaces #15855

New package: py-gluoncv

---

var/spack/repos/builtin/packages/fl/package.py

Check if CPU family is x86_64.

---

var/spack/repos/builtin/packages/sirius/package.py

SIRIUS: add version 6.5.1 and 6.5.2

---

var/spack/repos/builtin/packages/py-tensorboard-plugin-wit/package.py

dependency for py-tensorboard >= 2.2.0

new package: py-tensorboard-plugin-wit

---

var/spack/repos/builtin/packages/slepc/package.py

Update version information and a few more additions.
@balay this includes your commit

slepc 3.13 develop updates

---

var/spack/repos/builtin/packages/ucx/package.py

This PR adds the following variants for the UCX package:
- assertions
- debugging
- logging
- optimizations
- parameter checking
- pic support

ucx: add additional variants

---

var/spack/repos/builtin/packages/acts-core/package.py

[acts-core] Add version 0.21

---

var/spack/repos/builtin/packages/py-petsc4py/package.py
var/spack/repos/builtin/packages/py-slepc4py/package.py

update versions: petsc4py@3.13.0 and slepc4py@3.13.0

---

var/spack/repos/builtin/packages/draco/package.py

Updated version hashes for draco spackage to specify 7.5 and 7.6

Addded Draco@7.5.0:7.6.0

---

var/spack/repos/builtin/packages/py-awesome-slugify/package.py

depends on `py-unidecode` in #15906

py-awesome-slugify: new package at 1.6.5

---

var/spack/repos/builtin/packages/kripke/package.py

- Fixes build issues.
- Updates Kripke URL to its Github repository.
- Adds previous Kripke versions.
- Adds 'caliper' variant.

Updates to Kripke package. 

---

var/spack/repos/builtin/packages/papi/package.py

papi: check existence of a fortran compiler

---

var/spack/repos/builtin/packages/doxygen/package.py

* Add new version releases 1.8.16 and 1.8.17.
* Add mscgen as an optional dependency.

Update doxygen package

---

var/spack/repos/builtin/packages/py-setuptools-rust/package.py

I'm unable to test this because I can't get rust to build at the moment.

py-setuptools-rust: add new package

---

var/spack/repos/builtin/packages/suite-sparse/package.py

Release notes: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v5.7.2

suite-sparse: add version 5.7.2

---

var/spack/repos/builtin/packages/libtree/package.py

Adds https://github.com/haampie/libtree

libtree: new package at 1.0.3

---

var/spack/repos/builtin/packages/py-sonlib/package.py

py-sonlib package

---

var/spack/repos/builtin/packages/openfoam-org/package.py

openfoam: set run environment by sourcing bashrc

---

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py

Also fixed upper bound for 2.1 apps

Added Laghos@3 to ECP Proxy Apps@3

---

var/spack/repos/builtin/packages/memsurfer/package.py

Change the package to work with python3 and a couple other minor ones.

update: memsurfer with python3

---

var/spack/repos/builtin/packages/openmpi/package.py

Closes #15465 
@hppritcha @azukaitis @wortiz

OpenMPI: add +cxx variant

---

var/spack/repos/builtin/packages/hwloc/package.py

hwloc: Add netloc variant

---

var/spack/repos/builtin/packages/axom/package.py
var/spack/repos/builtin/packages/conduit/package.py
var/spack/repos/builtin/packages/py-shroud/package.py
var/spack/repos/builtin/packages/raja/package.py
var/spack/repos/builtin/packages/umpire/package.py

This adds an Axom spack package that runs on all the Axom supported LLNL systems.  I have run flake8 on all the files.
I am currently re-running our battery of tests which should pass because these files should have no changes other than style in them from what was already in Axom.  This takes a couple hours.

Add Axom spack package

---

etc/spack/defaults/config.yaml
lib/spack/spack/package_prefs.py
lib/spack/spack/schema/config.py

Config option to disable setting S_ISGID bit when creating installation directory

---

var/spack/repos/builtin/packages/arrayfire/package.py

ArrayFire is a general-purpose library that simplifies the process of developing software that targets parallel and massively-parallel architectures including CPUs, GPUs, and other hardware acceleration devices.

new package: arrayfire

---

var/spack/repos/builtin/packages/pango/package.py

pango: add libffi so that configure detects glib

---

lib/spack/spack/cmd/setup.py

First fix for SPACK_DEPENDENCIES problem when doing setup

---

var/spack/repos/builtin/packages/dftbplus/package.py
var/spack/repos/builtin/packages/dftd3-lib/package.py

Recipe for the [DTFB+](https://www.dftbplus.org) quantum mechanics simulation software.

dtfbplus: New package.

---

var/spack/repos/builtin/packages/vasp/package.py

Recipe for the popular ab initio simulation software [VASP](https://vasp.at)

vasp: New package.

---

lib/spack/spack/abi.py
lib/spack/spack/test/abi.py

Resolves #15970
If this is an acceptable change, I will add unit test coverage.

Relax architecture compatibility check

---

var/spack/repos/builtin/packages/gnutls/package.py

Add gnutls-specific headers property.

gnutls: add headers property

---

var/spack/repos/builtin/packages/nalu-wind/package.py

Allow nalu-wind to execute tests through ctest via spack

Add testing to nalu-wind
