spack/spack

var/spack/repos/builtin/packages/llvm/package.py
This fixes #12380 by configuring Clang to include the correct GCC version in its search paths if building with GCC.
See [this thread](http://clang-developers.42468.n3.nabble.com/Control-selected-GCC-installation-selected-libstdc-version-td4050363.html) for the relevant configure option.
---
Before this change, the search directories for Clang seem to be using the system GCC instead of the 8.2 that it was compiled with:
```console
$ clang -print-search-dirs
programs: =/projects/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/llvm-7.0.1-avafczo6dbasez3obndejep4rwbmwnrl/bin:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/bin
libraries: =/projects/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/llvm-7.0.1-avafczo6dbasez3obndejep4rwbmwnrl/lib/clang/7.0.1:/usr/lib/gcc/x86_64-red …
```
=> Use correct GCC installation when installing clang with GCC

var/spack/repos/builtin/packages/py-matplotlib/package.py
Not sure what happened between #5321 and now but the CC=CXX fix now
prevents py-matplotlib from building with the Intel compiler. I verified
with versions of py-matplotlib from 2.0.2 to 3.0.2 and intel-17.0.4 and
19.0.4 that py-matplotlib successfully builds with the Intel compiler
without that code.
=> Fix py-matplotlib build with Intel compiler

var/spack/repos/builtin/packages/swig/package.py
- SWIG versions use commit hashes from tags at https://github.com/swig/swig/releases
- Since git repo doesn't include configure.sh, call autoreconf script
- For information on the Fortran fork: see https://arxiv.org/abs/1904.02546
=> Update SWIG versions and add Fortran fork

lib/spack/spack/parse.py, lib/spack/spack/test/cmd/release_jobs.py, lib/spack/spack/test/spec_syntax.py, lib/spack/spack/util/editor.py, lib/spack/spack/util/executable.py
fixes #12268 
Apparently `shlex.split` can't deal with unicode encoded characters in Python 2.6. The solution is to convert to `str` before calling the function.
=> Fixed a Python 2.6 parsing error

var/spack/repos/builtin/packages/netlib-lapack/package.py
New Cray CCE compilers (version 9+) trip over the same bug that XL has issues with (i.e.: a typo in `CBLAS/CMakeLists.txt`).  This PR simply applies the existing patch to the source to fix builds with `%cce@9.0.1.80`.  IMHO, this patch should probably be applied universally as it shouldn't negatively impact builds with other compilers.
I also opened an issue on the netlib-lapack github page to point out this deficiency: [CMake error CBLAS/CMakeLists.txt wrt FortranCInterface](https://github.com/Reference-LAPACK/lapack/issues/349).
=> Apply xl patch for cce@9: to fix cmake.

var/spack/repos/builtin/packages/openblas/package.py
This adds OpenBLAS 0.3.7 (released 2019-08-11).
=> openblas@0.3.7: New version

var/spack/repos/builtin/packages/openblas/package.py
In a review of a previous pull request (
https://github.com/spack/spack/pull/10713 ) it was mentioned that the
proper way to figure out the target architecture is via
spec.architecture.target.  This patch fixes this for the openblas
package.
Signed-off-by: Janne Blomqvist <janne.blomqvist@aalto.fi>
=> openblas: fix target detection for cross-compiling

var/spack/repos/builtin/packages/blaze/package.py
The previous version does not properly install the required cmake
configuration files for blaze-lib, so find_package does not work
correctly.
This patch converts the blaze-lib package to use CMakePackage,
adds the required cmake dependency, and removes the install()
member function, which is not working correctly and is no longer
needed.
=> blaze: converted to CMakePackage

var/spack/repos/builtin/packages/poppler/package.py, var/spack/repos/builtin/packages/poppler/poppler_page_splash.patch, var/spack/repos/builtin/packages/texstudio/package.py
I also refactored the `Poppler` package to build with QT4. `TexStudio` expects `libpoppler-qt<version>` to be available when building against `poppler` (required for internal viewing of PDFs), so `^poppler+qt` is necessary. However, I couldn't get it to build with QT5, so trying QT4 seemed appropriate. I'll open an issue for the QT5 problem later.
=> New package: TexStudio

var/spack/repos/builtin/packages/singularity/package.py
Tested successfully on linux-centos7-x86_64 / gcc@4.8.5
I added what I hope is a slightly more helpful note, referring folks to the build log (where the fully instantiated post-install instructions wind up) rather than just the package definition.
URL for security implications updated per admonition banner at https://singularity.lbl.gov/docs-security
=> singularity: update version to 3.3.0

lib/spack/spack/cmd/modules/__init__.py
@albestro 
Fixes #12062
Closes #12063
#11304 addressed `spack module load` for upstream modules but not the `spack loads` command. This applies the same fixes from #11304 to `loads`.
=> Fix reference error for loads when retrieving upstream modules

var/spack/repos/builtin/packages/opa-psm2/opa-psm2-compiler.patch, var/spack/repos/builtin/packages/opa-psm2/package.py
patch to get the Makefile to use the spack compiler wrappers. Also sets a CCARCH=icc variable when using the Intel compilers to ensure the appropriate compiler flags are specified.
=> patch opa-psm2 to build with spack wrappers

var/spack/repos/builtin/packages/gromacs/gmxDetectCpu-cmake-3.14.patch, var/spack/repos/builtin/packages/gromacs/gmxDetectSimd-cmake-3.14.patch, var/spack/repos/builtin/packages/gromacs/package.py
* pre 2018 the cmake file was named differently
* fixed up post 2018 patch file which was not pretty
=> package/gromacs: simd optimizations autodetection for more versions

var/spack/repos/builtin/packages/subread/package.py
subread use -mtune=core2 to compile ooption.
But this option is not suppoeted on ARM.
This PR remove -mtune=core2 option when target is ARM.
=> subread: build on ARM.

var/spack/repos/builtin/packages/strace/package.py
* souce URL change to github.
* Add version 5.1 and 5.2
* enable build on ARM.
* strace try to use -m32, but gcc on aarch64 dose not support -m32, so -m32 is off on aarch64.
=> starce: new version and build on ARM.

var/spack/repos/builtin/packages/zstd/package.py
Also adds latest version of zstd.
```console
$ otool -L libzstd.dylib 
libzstd.dylib:
/usr/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.4.2)
```
There is no zstd library in `/usr/local/lib`.
```console
$ otool -L libzstd.dylib 
libzstd.dylib:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/zstd-1.4.2-mhzqhmg5hhpc7j6rhcs2yndwyvb5ow7p/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.4.2)
```
Correctly links to the Spack library.
=> zstd: fix build linking error

var/spack/repos/builtin/packages/unifycr/package.py
This adds some specifics about dependencies and conflicts and adds additional build options and variants.
UnifyCR now also has limited fortran support.
ECP project.
=> UnifyCR: update dependencies and build options

var/spack/repos/builtin/packages/bolt/package.py
This PR adds two new versions (`1.0rc1` and `develop`) and missing dependencies (CMake and Argobots) to the BOLT package.
Note that this BOLT package previously uses a built-in Argobots, but it complicates the version control. The Argobots/BOLT team would like to separate it from the BOLT package.
=> Update BOLT package

var/spack/repos/builtin/packages/icu4c/package.py
icu4c is a dependency of `qt@4.8.7`. Version 60.1 fails to build on linux with clang@7.0.1 and clang@8.0.0:
```
digitlst.cpp:508:9: error: use of undeclared identifier 'freelocale'
freelocale(gCLocale);
^
clang++     ...  coll.cpp
digitlst.cpp:520:26: error: use of undeclared identifier 'LC_ALL_MASK'
gCLocale = newlocale(LC_ALL_MASK, "C", (locale_t)0);
^
clang++     ...  sortkey.cpp
clang++     ...  bocsu.cpp
clang++     ...  ucoleitr.cpp
clang++     ...  ucol.cpp
clang++     ...  ucol_res.cpp
2 errors generated.
clang++     ...  ucol_sit.cpp
clang++     ...  collation.cpp
*** Failed compilation command follows:
----------------------------------------------------------
/projects/spack/lib/spack/env/clang/clang++ -D_REENTRANT
-DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -DU_HAVE_STRTOD_L=1 …
```
=> Update icu4c to version 64.1

var/spack/repos/builtin/packages/adios2/package.py
Version 2.4.0 of ADIOS2 (#11904) added new dependencies that are not yet listed as `depends_on` and/or disabled otherwise. Add them now to avoid picking them up from system paths, e.g. `libpng`.
=> ADIOS 2.4.0: Add new Deps

var/spack/repos/builtin/packages/qwt/no-designer.patch, var/spack/repos/builtin/packages/qwt/package.py, var/spack/repos/builtin/packages/visit/nonframework-qwt.patch, var/spack/repos/builtin/packages/visit/package.py, var/spack/repos/builtin/packages/visit/spack-changes.patch, var/spack/repos/builtin/packages/vtk/package.py
With these changes I was successfully able to install the latest VisIt on my mac using the spack toolchain. I needed to make changes to the VisIt package and to two upstream packages (QWT and VTK) for my configuration, so please let me know if those should be separate pull requests.
Changes to QWT are to allow building with `qt~tools`.
Changes to VTK:
- Fix compile error due to `""` in mac-specific configure flags
- Enable `VTK_ALL_NEW_OBJECT_FACTORY` (needed for visit, I don't think it would be harmful in any other case) option
- Merge `+python` and `+python3` variants
Changes to VisIt:
- Add new version and checksums
- Add support for building with a QWT that was compiled as a library rather than framework on mac
- Add more explicit version dependencies based on VisIt build_script …
=> Update VisIt to version 3.0.1 and fix on mac

var/spack/repos/builtin/packages/go/package.py
Both address security issues:
https://groups.google.com/forum/#!topic/golang-nuts/fCQWxqxP8aA
=> go: Add 1.12.8 and 1.11.13

var/spack/repos/builtin/packages/hpctoolkit/package.py
Add version 2019.08.14 and rename 'develop' to 'master' to match the
git branch name (now that master is also a special name).
=> hpctoolkit: add version 2019.08.14

var/spack/repos/builtin/packages/py-torch/package.py
Made the following changes:
I was able to successfully build PyTorch 1.2.0 on macOS 10.14.6 with Clang 10.0.1 with no optional variants enabled. Build worked with OpenBLAS but not with MKL. Still needs a bit of testing, but is probably safe to merge.
=> Overhaul PyTorch package

var/spack/repos/builtin/packages/camx/package.py
New CAMx package.
Notes:
1. Only tested with Intel compiler and Intel MPI and OpenMP; environment file below.
2. The built `camx` executable needs to be run with 2 or more MPI tasks (even if your single MPI task has multiple CPUs per task) or you'll get a cryptic MPI crash.
3. For some reason upstream compiles in their parameter limits into their `camx.prm.*` file.  This seems to be somewhat common practice in the atmospheric research Fortran community, but I still have to wonder why those parameter limits are not it a separate `/etc` configuration file?  It might be because upstream expects you to work inside of their source directory for all your computation, and expects you to edit source files; they have no "install" make rule.  I `patch()` that file to fix runtime errors my user …
=> camx: add version 6.50

lib/spack/spack/cmd/mirror.py, lib/spack/spack/mirror.py, lib/spack/spack/test/cmd/mirror.py
Resolves #12337 
Allow `spack mirror` with no spec arguments to create a mirror for the active environment.
=> mirrors: make `spack mirror` environment aware

var/spack/repos/builtin/packages/precice/package.py
This PR fixes the Eigen include directory used in the precice package.
=> preCICE: Fix Eigen include directory

lib/spack/spack/package.py, lib/spack/spack/report.py, lib/spack/spack/reporters/cdash.py
Skip generating reports for any packages that were found in the binary cache.
=> Do not report on packages installed from the cache

lib/spack/spack/stage.py
Removed print statements from #12072
=> cleanup: remove extraneous prints

var/spack/repos/builtin/packages/r/package.py
Add r 3.6.1 which has been built successfully via `spack install r %gcc@8.3.0 r+external-lapack+X ^openblas threads=openmp ^cairo+X+pdf`.
=> Add r 3.6.1.

var/spack/repos/builtin/packages/unifyfs/package.py
UnifyCR has been renamed to UnifyFS. Renaming the Spack package is the last step in this process.
This renames the package and changes any UnifyCRs to UnifyFS within the package.
The only side effect this should have is to the [EcpIoSdk package](https://github.com/spack/spack/blob/f1bdaa11d46b7d7c7014509143fd68d895cbfe37/var/spack/repos/builtin/packages/ecp-io-sdk/package.py) (@chuckatkins).
=> UnifyFS: new package - rename from UnifyCR

var/spack/repos/builtin/packages/musl/package.py
This PR fixes a bug in the musl spec which arises when the modulefile is built:
`==> Warning:   --> global name 'prefix' is not defined <--
`
=> musl: prefix -> self.prefix

var/spack/repos/builtin/packages/mvapich2/package.py
inspired by @becker33 presentation at the MVAPICH2 user group :-)
=> mvapich2 depends on slurm when built with process_managers=slurm

lib/spack/llnl/util/filesystem.py, lib/spack/spack/directory_layout.py
Fixes #12102 
Set file permissions for intermediate directories in install tree to the permissions of the parent directory.
=> permissions: fix file permissions on intermediate install directories

var/spack/repos/builtin/packages/py-deeptools/package.py, var/spack/repos/builtin/packages/py-deeptoolsintervals/package.py
Getting several import and other runtime errors from `py-deeptools@3.2.1` executables due to missing dependencies lagging behind upstream:
https://github.com/deeptools/deepTools/blob/master/requirements.txt
To run unit tests via spack, I patch in upstream's nose test suite so that we can now run:
```bash
spack install --test root --verbose py-deeptools ^python@3:
```
1.  The trade off for running unit tests is switching the URL from the small pypi tarball [188K] to the larger GitHub release tarball [60M] which includes the test data files.  But I expect it will save us maintainers multiple hours of packaging and troubleshooting.
2. Of the 108 tests, only 5 fail, all of which are related to the heatmapper plotting functions.  Those failures look harmless to me; they are image size …
=> py-deeptools: add version 3.3.0

lib/spack/spack/cmd/help.py, lib/spack/spack/main.py
Fix to help option text, factored out of a drive-by fix in #11145.
=> Fix to option text for help command.

lib/spack/docs/packaging_guide.rst, lib/spack/spack/fetch_strategy.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/git_fetch.py
Fetch strategies: new global option `no_cache`, new git option `get_full_repo`.
* All fetch strategies now accept the Boolean version keyword option `no_cache` in order to allow per-version control of cache-ability.
* New git-specific version keyword option `get_full_repo` (Boolean). When true, disables the default `--depth 1` and `--single-branch` optimizations that are applied if supported by the git version and (in the former case) transport protocol.
* The try / catch blog attempting `--depth 1` and retrying on failure has been removed in favor of more accurately ascertaining when the `--depth` option should work based on git version and protocol choice. Any failure is now treated as a real problem, and the clone is only attempted once.
* Test improvements:
* …
=> Fetch strategies: new global option no_cache, new git options full_depth and all_branches.

lib/spack/spack/concretize.py
Resolves a bug I found while working with Spack stacks.
=> compiler install: fix bug in construction of compiler spec

var/spack/repos/builtin/packages/nlohmann-json/package.py
Add the latest release of this library, fixing compile issues with GCC 9.0 [among others](https://github.com/nlohmann/json/releases).
Also refactor the test handling to proper control via `spack install --test root|all ...` instead of a variant.
=> nlohmann-json: v3.7.0

var/spack/repos/builtin/packages/esmf/gcc_darwin.patch, var/spack/repos/builtin/packages/esmf/package.py
This updates the ESMF package to version 7.1.0r and changes the url to the public-facing versions.
The previous version of ESMF wouldn't build with newer Intel compilers due to the openMP flag changing from "-openmp" to "-qopenmp". The new version (7.1.0r) now contains new build scripts to account for this change. When testing on my local mac, I also found that a new gcc patch for mac's needs to be added as well which I've included.
=> Adding a new version of ESMF.

var/spack/repos/builtin/packages/libfabric/package.py
This variant (off by default) adds support for the kdreg option in the GNI provider.  It is disabled by default in order to avoid potential runtime conflicts with the cray-mpich library.  Only one library at a time can use this feature.
This patch allows the libfabric package to work correctly out of the box on systems like Cori at NERSC (since it's CLE7 update).  Otherwise the spack build may autodetect kdreg headers on the system and enable this problematic feature.
=> add kdreg variant to libfabric package

lib/spack/spack/repo.py, lib/spack/spack/test/repo.py
Having a non-directory invisible file in the `packages` dir causes `spack find` to die. This
fixes the logic to ignore invalid module names but only warn if they're
visible.
```
NotADirectoryError: [Errno 20] Not a directory: '/spack/var/spack/repos/builtin/packages/.DS_Store/package.py'
```
=> Skip invisible non-packages in package directory.

var/spack/repos/builtin/packages/openstf/package.py
This PR adds (new) support to build and install the `openstf` package.
This `openstf` is confirmed to compile successfully with gcc and Fujitsu compiler.
=> openstf: new package

var/spack/repos/builtin/packages/go/package.py
Updating minor version: https://golang.org/doc/devel/release.html#go1.12.minor
=> Add Go 1.12.9

var/spack/repos/builtin/packages/seacas/package.py
SEACAS is now using versions instead of just relying on always installing `master`.  There are now tagged versions.
The most recent version is the first that can be used with a non-patched `develop` version of the CGNS package; previously, seacas required that the CGNS library have some internally-developed patch applied, but this is no longer needed.
Also, added support for `adios2` package with the `adios2` variant.  This currently defaults to off.
=> SEACAS: New version and added adios2 variant

var/spack/repos/builtin/packages/julia/armgcc.patch, var/spack/repos/builtin/packages/julia/package.py
* add version 1.0 and 1.1
*  startup file and codes is changed. (#9278)
* change to work on arm
*  remove fp16 code when gcc is old. (https://www.gnu.org/software/gcc/gcc-6/changes.html#aarch64)
* to assemble crc32, add -marc=armv8-a+crc
=> julia: new version and work on arm

var/spack/repos/builtin/packages/esmf/intel.patch, var/spack/repos/builtin/packages/esmf/package.py, var/spack/repos/builtin/packages/ncl/package.py, var/spack/repos/builtin/packages/ncl/ymake.patch
This PR targets NCL, but ESMF needs to be fixed as NCL has it as a dependent.
Bug fixes are targeting my testing with Intel 19.0.3 compilers.  However, some other fixes are not Intel compiler based.
1. Support Intel 17+ `-qopenmp` where appropriate, this has to be done in a patch because `build_rules.mk` sets the options in the source files.
2. Allow compiler flags to be injected from the compiler spec.
1. Remove single quote specification in configure script, this keeps some subprograms from linking to libraries properly. 
2. Add in the deps:
```
depends_on('pixman')
depends_on('bzip2')
depends_on('freetype') # should have been there initially
```
Comment: `pixman` and `bzip2` need to be in there because the final `ncl` would not link without the presence of `-lbz2` and `-lpixman-1`.  I …
=> ESMF,NCL: Bug fixes for Intel Compilers

var/spack/repos/builtin/packages/openpmd-api/package.py
Update minimal required version of the `nlohmann-json` dependency.
Follow-up to #12517
=> openPMD-api: newer nlohmann-json

var/spack/repos/builtin/packages/hypre/package.py
This commit adds `hypre@2.17.0`.
I have not attempted to add variants for Caliper, RAJA, Kokkos, etc.
=> hypre@2.17.0: new version

var/spack/repos/builtin/packages/gobject-introspection/package.py
When building other GNOME packages, configure scripts for those packages will search for the GIR files installed by gobject-introspection. In order for these scripts to detect those files successfully, the prefix path for those files must be prepended to `XDG_DATA_DIRS`. This commit adds this operation to the `setup_dependent_environment` method in the `gobject-introspection` Spack package.
=> gobject-introspection: add GIR file search path

var/spack/repos/builtin/packages/gtksourceview/package.py
This pull request prepends the gtksourceview GIR search path to `XDG_DATA_DIRS` so that other GNOME project package build systems can find these files when needed.
=> gtksourceview: add GIR file search path

var/spack/repos/builtin/packages/raja/package.py
Before this commit, CMake would still attempt to detect OpenMP, even
if RAJA were being installed with `spack install raja~openmp`, because
the option `ENABLE_OPENMP` is set to "On" by default. This commit
explicitly disables OpenMP when the Spack install spec contains
'~openmp`, ensuring that CMake does not attempt to detect and link
with OpenMP.
Fixes https://github.com/spack/spack/issues/12571.
=> raja~openmp: explicitly disable OpenMP in CMake

var/spack/repos/builtin/packages/bowtie/package.py
This commit add bowtie 1.2.3 which has resolved the GCC 8 compiling issue thus conflicting statements and patching actions are removed for bowtie@1.2.3 %gcc@8: . `spack install bowtie@1.2.3 %gcc@8.3.0` has been built successfully.
=> Add bowtie 1.2.3.

lib/spack/docs/packaging_guide.rst
Update variant table to deprecate `static` variant and explain semantics of `shared` variant.
=> Docs: update variant table in packaging guide

var/spack/repos/builtin/packages/qt/package.py
disable phonon backend gstreamer until it is setup.
=> Qt@4.8.7: fix build issue due to +phonon variant, disable phonon backend

var/spack/repos/builtin/packages/atk/package.py
This pull request adds `libffi` as a dependency to the `atk` package, because its `configure` script checks for `libffi` as part of detecting `glib`. A similar fix for `pango` can be found in PR #12384 due to a similar issue in `pango` reported in issue #12383.
=> bugfix: atk build requires libffi to detect glib

var/spack/repos/builtin/packages/paraview/package.py
It turns out that the embedded libpng in paraview doesn't build correctly
using more recent GNU compilers on aarch64 systems.  It ends up partially
configuring the embedded libpng for neon but the build fails with confusion
about whether to use neon instructions or not.
Specifying that the available system libpng be used instead resolves this problem.
=> Use system libpng by default

var/spack/repos/builtin/packages/elpa/package.py
Add elpa 2018.11.001. This is not the latest version 2019.05.001, as
that one doesn't build cleanly due to module dependencies being
incomplete. Also 2019.05.001 by default removes some deprecated
functionality.
=> elpa@2018.11.001: New version

var/spack/repos/builtin/packages/hpctoolkit/package.py
Change the depends_on type from default (build + link) to just 'link'
for binutils and a few other packages.  We don't use the binutils
utilities (only libs).  On cori at NERSC (Cray), this was breaking the
build by covering up the system ld.
=> hpctoolkit: tighten some dependencies

lib/spack/spack/repo.py
Fixes https://github.com/spack/spack/issues/12612
@glennpj can you confirm this fix?
When Spack installs a package it writes the `package.py` file and patches to a separate repository (which reflects the state of the package at the time it was installed). Previously, Spack only wrote patches that were used at installation time. This updates the archiving step to include all patch files that are relevant to the package (in case that repository is used in another context).
=> Archive all patches in a package after install

var/spack/repos/builtin/packages/py-zipp/package.py
=> Add py-zipp package

var/spack/repos/builtin/packages/py-importlib-metadata/package.py
=> Add py-importlib-metadata package

var/spack/repos/builtin/packages/py-pluggy/package.py
=> Add py-pluggy 0.12.0

var/spack/repos/builtin/packages/py-packaging/package.py
No idea why six and pyparsing weren't build dependencies, but they definitely are now.
=> Add py-packaging 19.1

var/spack/repos/builtin/packages/py-pytest/package.py
Note that PyTest 5 drops Python 2 support.
=> Add py-pytest 5.1.1

var/spack/repos/builtin/packages/gtkplus/package.py
[wow, lost a big hunk of my commit message, recreated here...]
[edit: change -> changed]
#12568 ~~change~~ changed the cairo package so that its --enable-gobject flag 
is either explicitly true or false.  Previously, the feature defaulted to `auto`
and configure would *auto*magically run a test to figure whether to
include gobject support.   I'm betting that (on our systems, at
least), it decided to include it.
Now that we're defaulting it to off, that functionality is not being
included.
The gtk configure script blithely assumes that cairo *has* gobject
support, by searching for the `cairo-gobject.pc` pkg-config file and
crash/burning when it's not there.
Making the cairo dependency include gobject support fixes it (as in,
Works For Me(tm) and Works For Owen(patent-pending)).
I've tested …
=> gtkplus' cairo dependency must be +gobject

var/spack/repos/builtin/packages/kaldi/package.py
@adamjstewart Currently the install_tree() call tries to copy the symlinks but not the
libraries themselves, they are instead pointed to somewhere in the build
stage directories. This breaks some of the binaries that are installed
This change looks at all the .so's in the lib directory, then installs
the real library files instead of just copying the symlink.
=> Change how the libraries are installed for kaldi

var/spack/repos/builtin/packages/extrae/package.py
Version bump to latest extrae version.
Dyninst and PAPI are both optional deps hence addition of variants.  Dyninst in particular is problematic for our uses on various machines, hence disabled as a default.
Dyninst also limited in version to <10 as recommended by extrae devs. (https://github.com/bsc-performance-tools/extrae/issues/30)
=> bump extrae to 3.7.1, optionalise dyninst, papi

var/spack/repos/builtin/packages/gtkplus/package.py
this PR adds: depends_on('cups')
however alternatively one could get rid of it by adding a configure argument:
args.append('--disable-cups')
=> fix: gtkplus depends on cups

var/spack/repos/builtin/packages/mariadb/package.py
The mariadb-5.5 series can not be compiled with gcc-9.1.0 and above. Add
a conflicts statement to refect that.
The errors are due to -Werror=address-of-packed-member, a warning that is new in gcc-9.
=> Add conflicts statement to mariadb

var/spack/repos/builtin/packages/pumi/package.py, var/spack/repos/builtin/packages/zoltan/package.py
Adds variant to pumi and zoltan that enables 64bit indices.
=> Add int64 variant to pumi and zoltan

var/spack/repos/builtin/packages/idba/package.py
The IDBA package can be built with Intel 19 compilers.  There is no need to block building against other compilers, though it appears it's been sometime since the package has been updated by the primary developer.  No evidence that only GCC compiler can be supported: https://github.com/loneknightpy/idba
=> IDBA: package does not need conflicts with other compilers

var/spack/repos/builtin/packages/ncbi-rmblastn/isb-2.9.0+-rmblast-p1.patch, var/spack/repos/builtin/packages/ncbi-rmblastn/package.py
Ncbi-rmblastn 2.2.28 configuration fails for Gcc compiler on Ubuntu 16.04 due to some compatibility issues that requires manual intervention to keep the installation going. However you still stumble upon other issues while compiling it.
Using Intel compiler passes the configuration step but fails for the compilation process as well.
Here I'm using the latest version and patch, and the recommended configuration option as mention in http://www.repeatmasker.org/RMBlast.html
=> Install the newest version of ncbi-rmblastn

lib/spack/docs/basic_usage.rst, lib/spack/docs/config_yaml.rst, lib/spack/docs/module_file_support.rst, lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/extensions.py, lib/spack/spack/cmd/find.py, lib/spack/spack/environment.py, lib/spack/spack/spec.py, lib/spack/spack/test/cmd/extensions.py, lib/spack/spack/test/cmd/find.py, lib/spack/spack/test/spec_yaml.py, lib/spack/spack/test/test_activations.py, share/spack/spack-completion.bash, var/spack/repos/builtin.mock/packages/perl-extension/package.py, var/spack/repos/builtin.mock/packages/py-extension1/package.py, var/spack/repos/builtin.mock/packages/py-extension2/package.py
Fixes #2638.
We've had some nice spec format string syntax since #10556 ([documented here](https://spack.readthedocs.io/en/latest/spack.html#spack.spec.Spec.format)), and people have asked for easier ways to parse `spack find` output.
I've added two options to `spack find` to address this:
You can provide a format string to `spack find`, as in #10556, and you can print out exactly those parts of the spec you want, one per line, with no frills:
```console
$ spack find --format "{name}-{version}-{hash}"
autoconf-2.69-icynozk7ti6h4ezzgonqe6jgw5f3ulx4
automake-1.16.1-o5v3tc77kesgonxjbmeqlwfmb5qzj7zy
bzip2-1.0.6-syohzw57v2jfag5du2x4bowziw3m5p67
bzip2-1.0.8-zjny4jwfyvzbx6vii3uuekoxmtu6eyuj
cmake-3.15.1-7cf6onn52gywnddbmgp7qkil4hdoxpcb
```
See the docs for more details.
You can get JSON records …
=> Add machine-readable options to `spack find`

lib/spack/spack/cmd/__init__.py
`spec.prefix` reads from Spack's database, and if you do this with
multiple consecutive read transactions, it can take a long time.  Or, at
least, you can see the paths get written out one by one.
This uses an outer read transaction to ensure that actual disk locks are
acquired only once for the whole `spack find` operation, and that each
transaction inside `spec.prefix` is an in-memory operation. This speeds
up `spack find -p` a lot.
=> perf: spack find -p now does only one DB transaction

var/spack/repos/builtin/packages/py-chardet/package.py
Fixes #12560 (where it was discovered `py-pytest-runner` is a necessary dependency)
=> py-chardet package: add py-pytest-runner as build dependency

lib/spack/spack/database.py, lib/spack/spack/spec.py, lib/spack/spack/test/cmd/uninstall.py
Previously spec parsing didn't allow you to look up missing (but still known) specs by hash.
For example:
```console
$ spack uninstall -f /7lpqufu  # force uninstall a still-needed package
```
Notice that xz is uninstalled (`[-]`) below:
```console
$ spack spec -Il /tddqgvd
Concretized
[+]  tddqgvd  hdf5@1.10.2%clang@8.1.0-apple~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=darwin-highsierra-x86_64 
[+]  j55gl56      ^openmpi@3.1.1%clang@8.1.0-apple~cuda+cxx_exceptions fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=darwin-highsierra-x86_64 
[+]  4qjjdvh          ^hwloc@1.11.9%clang@8.1.0-apple~cairo~cuda+libxml2~pci+shared arch=darwin-highsierra-x86_64 
[+]  cmhpqwp              ^libxml2@2.9.8%clang@8.1.0-apple~python …
```
=> specs: better lookup by hash; allow references to missing dependency hashes

var/spack/repos/builtin/packages/boost/package.py
Without this fix, when requesting `boost~signals` for a boost version greater than or equal to 1.69, spack throws an exception on line 391 saying that 'signals' is not in `with_libs`.
With this fix, spack will simply ignore the ~signals since the signals variant does not exist after 1.69.
=> Boost: fixed problem when requesting ~signals for boost >= 1.69

var/spack/repos/builtin/packages/tmux/package.py
While debugging this package on our Cray machine, tmux was throwing an
error involving the ncurses headers. Tmux would look for headers in
system locations rather than where spack installed ncurses. Tested only
on a Cray.
=> tmux: cppflags point to ncurses headers

var/spack/repos/builtin/packages/boost/clang-linux_add_option.patch, var/spack/repos/builtin/packages/boost/clang-linux_add_option2.patch, var/spack/repos/builtin/packages/boost/package.py
Versions up to 1.63.0 lack the `-c` option for C/C++ compiler commands in clang-linux.jam.
I fixed it.
※ The directory structure is different between the versions before 1.55.0 and the versions after 1.56.0.
Referenced:
http://boost.2283326.n4.nabble.com/Boost-Math-Weird-compiler-error-with-Clang-3-8-td4691122.html
=> boost: add -c option to C/C++ compile commands for clang.

lib/spack/spack/test/conftest.py, lib/spack/spack/test/url_fetch.py, lib/spack/spack/util/compression.py
`mock_archive` can now take multiple extension / tar option pairs (default matches old behavior).
`url_fetch.test_fetch` tests more archive types.
`compression.EXTS` split into `EXTS` and `NOTAR_EXTS` to avoid unwanted, non-meaningful combinatoric extensions such as `.tar.tbz2`.
=> Improve mock_archive versatility; Remove unwanted ALLOWED_ARCHIVE_TYPES.

var/spack/repos/builtin/packages/go/package.py
Update to latest release: https://blog.golang.org/go1.13
=> Add Go 1.13

var/spack/repos/builtin/packages/cctools/arm.patch, var/spack/repos/builtin/packages/cctools/package.py
cctols use some linux system call directory.
But aarch64 linux kernel is deprecated some system call (For example, open).
This patch replace deprecated system call to existed system call.
=> cctools: fixed to build on ARM.

var/spack/repos/builtin/packages/py-ase/package.py
Add ASE version 3.18. ASE 3.18 has dropped support for python 2.x,
hence add a dependency on python@3.5: for it.
=> py-ase: New version 3.18

var/spack/repos/builtin/packages/mariadb/package.py
Found while building mariadb in a minimal build environment.
=> mariadb: Add missing dependencies

var/spack/repos/builtin/packages/catalyst/package.py
This PR adds the `-DPNG_ARM_NEON_OPT=0` definition to CMAKE_CXX_FLAGS and CMAKE_C_FLAGS if the target is `aarch64`. Without these flags, Catalyst fails to compile on this architecture, with undefined references to `png_init_filter_functions_neon`.
=> FIX Catalyst: corrected catalyst package for aarch64 targets

var/spack/repos/builtin/packages/fftw/package.py
Currently, default value of simd variant is dependent to x86_64 architecture.
And if we execute `spack install fftw` on other than x86_64, the command is failed.
This patch change defaul value to 'default', and the value is determined to configure().
=> fftw: change default value of simd variant for other than x86_64

lib/spack/spack/environment.py
Currently, environments only load existing paths on activation. This means that new packages in the environment do not load properly. For example
```
$ unset LD_LIBRARY_PATH
$ spack env create myenv
$ spack env activate myenv
$ spack install zlib
$ echo $LD_LIBRARY_PATH
```
results in nothing in `LD_LIBRARY_PATH`. Under this PR, it now results in `$spack/var/spack/environments/myenv/.spack-env/view/lib:$spack/var/spack/environments/myenv/.spack-env/view/lib64`.
=> Environment views: add all paths on activation

var/spack/repos/builtin/packages/openspeedshop-utils/arm.patch, var/spack/repos/builtin/packages/openspeedshop-utils/package.py, var/spack/repos/builtin/packages/openspeedshop/arm.patch, var/spack/repos/builtin/packages/openspeedshop/package.py
openspeedshop and openspeedshop-utils  use some linux system call number.
But aarch64 linux kernel is deprecated some system call (For example, open).
This patch replace deprecated system call to existed system call.
=> openspeedshop: fixed build on arm.

var/spack/repos/builtin/packages/upcxx/package.py
Adding a UPC++ spack package pointing to the default 2019.3.2 UPC++
version, and allowing to build UPC++ with the experimental CUDA variant.
Supersedes #12585 -- sorry for the confusion 😄 
@mjacquel @bonachea
=> UPC++: new package

var/spack/repos/builtin/packages/font-util/package.py
A [new version](https://cgit.freedesktop.org/xorg/font/util) of `xorg/font/util` was released recently, for the first time in several years.
Tested on CentOS  6, gcc 8.2
(@mamelara @tgamblin -- This may or may not help with #12547 -- but seems worth trying.)
=> font-util: new release 1.3.2

var/spack/repos/builtin/packages/plasma/fix_cmake_include.patch, var/spack/repos/builtin/packages/plasma/package.py, var/spack/repos/builtin/packages/plasma/protect_cmake_version.patch
- Use of symbol testing macro requires explicit include()
- CMake policies are not version-portable and the support has to queried
based on CMake version
=> Add PLASMA patches to work around CMake versions

var/spack/repos/builtin/packages/py-numpy/package.py
Successfully builds and passes all unit tests on macOS 10.14.6 with Clang 10.0.1, Intel MKL 2019.4, and Python 3.7.4.
=> Add py-numpy 1.17.2

var/spack/repos/builtin/packages/lua-luafilesystem/package.py, var/spack/repos/builtin/packages/lua-luaposix/package.py
This way luarocks does not attempt to pull stuff from the internet.
Fix #3909
Fix #7848
Ref: https://stackoverflow.com/a/43321646/1334711
=> luarocks: Use `make` command instead of `install`

var/spack/repos/builtin/packages/ncurses/package.py
Apply configure options to skip manpage generation and test builds for both wide and non-wide builds.
=> ncurses: improve build time

var/spack/repos/builtin/packages/p4est/package.py
The default is to have MPI enabled, as before. But now the user has the option to turn off MPI if desired.
=> add mpi variant to p4est package to allow turning off MPI

var/spack/repos/builtin/packages/mesa/package.py
There are problems with libunwind for arm and trying to use it with mesa.
See for example:
https://github.com/grate-driver/mesa/issues/6
disabling use of libunwind for arm, allows the package to be built
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
=> mesa: disable use of libunwind for arm arch

var/spack/repos/builtin/packages/boost/package.py
I need to build boost 1.54 with gcc 8.20 and it currently fails with _exactly_ the same error as reported by #2821
I propose to extend the patch introduced in #2822 to apply to any gcc after 5.0, and not just 5.0-5.9.
I have tested this with gcc 8.2 on Centos 7 machine and it works nicely.  Perhaps I should conservatively bookend the patch to `%gcc@5.0:8.2`?
@hartzell
=> patch boost version 1.54-1.55 with ANY gcc >= 5.0

lib/spack/spack/cmd/flake8.py
E501 (line too long) exemptions are probably our most common ones -- we add them for directives, URLs, hashes, etc. in packages.  But we currently add them even when a line *doesn't* need them, which can mask trailing whitespace errors.
This changes `spack flake8` so that it will only add E501 exemptions if the line is *actually* too long.
=> flake8: only add E501 exemptions when absolutely necessary

var/spack/repos/builtin/packages/py-dnaio/package.py
Tested on Centos6, gcc 8.2
This is needed by #12741
=> py-dnaio: new package need by py-cutadapt

var/spack/repos/builtin/packages/py-cutadapt/package.py
Tested (build and execute with real data) on CentOS 6, gcc 8.2
This PR will be followed by two more in dependent packages, which are necessary for this updated version of py-cutadapt:
* py-xopen (update)
* py-dnaio (new package)
=> py-cutadapt: Updated version checksum

var/spack/repos/builtin/packages/singularity/package.py
WIP.  @vsoch @hartzell 
* v3.3 now depends on the new package `shadow` (#12750) and appears to build successfully.  --fakeroot option still needs testing.
* v3.4 does not yet build.  The build error message is:
```
checking: libseccomp+headers... no
checking: cryptsetup... no
unable to find the cryptsetup program, is the package cryptsetup-bin installed?
```
=> for fakeroot support, add "shadow" dependency

var/spack/repos/builtin/packages/cgns/package.py
This should go in the CGNS CMakeLists.txt, but it isn't there yet and won't be in previous versions, so best to handle it here.  
If building on darwin/MacOSX, need to set the RPATH so applications can find shared library correctly.
=> CGNS: Add setting of RPATH on Darwin

share/spack/packages/Dockerfile, share/spack/packages/cors-header.conf
Add the HTTP header `Access-Control-Allow-Origin: *` for our NGINX service that is serving static JSON content on https://spack.packages.io .
Fix #12760 .
=> Add CORS for spack.packages.io

var/spack/repos/builtin/packages/binutils/package.py
This fixes undefined symbol `libintl_dgettext` on `libbfd.so` when building `bintuils+nls`, which depends on `gettext`.
```
ldd -r `./spack/bin/spack location -i binutils+nls`/lib/libbfd.so
linux-vdso.so.1 (0x00007ffcf4551000)
libz.so.1 => /tmp/spack/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/zlib-1.2.11-svvxgn7pln5jyvtfaexp4s6kkfwefraf/lib/libz.so.1 (0x00007f07ed9a6000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f07ed97b000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f07ed790000)
/lib64/ld-linux-x86-64.so.2 (0x00007f07ee082000)
undefined symbol: libintl_dngettext	(/tmp/spack/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/binutils-2.32-wedlillsmksloz46hpuf6uywypwb3fvw/lib/libbfd.so)
undefined symbol: libintl_dgettext …
```
=> binutils: fix undefined symbol libintl_dgettext

lib/spack/spack/compilers/clang.py, lib/spack/spack/test/compilers.py
This is similar to #10191. The Ubuntu package for clang 8.0.0 displays a very unusual version string, and we need this new regex to detect it as just 8.0.0
Unit test have been complemented by the output that was failing detection.
=> clang: add another regex for version detection

share/spack/qa/run-docker-tests
Build the packages.spack.io service images first, so they are guaranteed to be pushed even if further images fail to build.
Fix the query to the `spack` script executed in later builds.
Update: remove Spack image builds which are now performed on Dockerhub.
=> Fix CD: Packages Service First

var/spack/repos/builtin/packages/ccs-qcd/package.py
I created this package in #12681 .
I have used explicit target `CONFIG_GEN` because of the dependency problem of "makefile" when running `make` in parallel,
but instead adding `parallel = False` have solved the problem.
Sorry for the lack of confirmation of the spack manual.
=> ccs-qcd: disable parallel builds

var/spack/repos/builtin/packages/cuda/package.py
Adds CUDA 10.1.243. The installer command-line arguments have slightly
changed, hence in the install method the version needs to be inspected
in order to give the correct arguments for the new installer.
=> cuda: New version 10.1.243

var/spack/repos/builtin/packages/popt/package.py
Tested on CentOS 7 with gcc 8.2 and 4.8.
Motivation is to support new package cryptsetup (#12762)
=> create package popt

var/spack/repos/builtin/packages/precice/package.py
This PR adds the versions `1.6.0` and `1.6.1` of preCICE.
This is relevant to the xSDK project.
=> preCICE 1.6

var/spack/repos/builtin/packages/wcslib/package.py
Version 5.18 is no longer available for download.
Successfully builds on macOS 10.14.6 with Clang 10.0.1.
=> Add wcslib 6.4

var/spack/repos/builtin/packages/py-emcee/package.py
=> Add py-emcee 2.2.1

var/spack/repos/builtin/packages/py-cython/package.py
This seems to be a Python 3-specific bug. When run with Python 3,
```console
$ spack install --test=root py-cython
...
==> Error: TypeError: expected string or bytes-like object
/Users/Adam/spack/var/spack/repos/builtin/packages/py-cython/package.py:46, in test:
44    def test(self):
45        # Warning: full suite of unit tests takes a very long time
>>     46        python('runtests.py', '-j', make_jobs)
```
This PR explicitly casts the object to a string.
=> Fix bug in string conversion of py-cython

var/spack/repos/builtin/packages/py-bleach/package.py
=> Add py-bleach 3.1.0

var/spack/repos/builtin/packages/flang/package.py
When I install  flang on arm,  the build is  failed because spec ['llvm'] is not set.
This PR fixed to build on arm.
I check only version 20180921. so the pr is only add 20180921.
=> flang: build on arm.

var/spack/repos/builtin/packages/py-html5lib/package.py
The Python version constraints for this package were too strict. There are actually several more packages in Spack that exhibit this, but I haven't gotten around to updating them yet.
=> Relax Python version constraints on py-html5lib

var/spack/repos/builtin/packages/py-soupsieve/package.py
=> Add py-soupsieve package

var/spack/repos/builtin/packages/py-sortedcontainers/package.py
=> Add py-sortedcontainers package

var/spack/repos/builtin/packages/py-semantic-version/package.py
=> Add py-semantic-version package

var/spack/repos/builtin/packages/py-pyopenssl/package.py
=> Add py-pyopenssl package

var/spack/repos/builtin/packages/py-ligo-segments/package.py
=> Add py-ligo-segments package

var/spack/repos/builtin/packages/py-jplephem/package.py
=> Add py-jplephem package

var/spack/repos/builtin/packages/py-lscsoft-glue/package.py
=> Add py-lscsoft-glue package

var/spack/repos/builtin/packages/py-bintrees/package.py
=> Add py-bintrees package

var/spack/repos/builtin/packages/py-asdf/package.py
=> Add py-asdf package

var/spack/repos/builtin/packages/py-mpld3/package.py
=> Add py-mpld3 package

var/spack/repos/builtin/packages/py-beautifulsoup4/package.py
=> Add py-beautifulsoup4 4.8.0

var/spack/repos/builtin/packages/py-astropy/package.py
This PR includes the following changes:
=> Add py-astropy 2.0.14

var/spack/repos/builtin/packages/py-pycbc/package.py
Needed to do some gravitational wave simulations for a Computational Astrophysics course, so decided to package this.
=> Add py-pycbc package

lib/spack/spack/util/environment.py
Fixes #12730 
Not sure what other bugs this may have influenced, or if there are other places in Spack where we should be escaping spaces in paths and we're not currently.
@tgamblin @alalazo
=> Fix Spack Environments bug with space in PATH

lib/spack/spack/cmd/create.py
On develop, if you create a new package, it will always contain the body:
```python
def install(self, spec, prefix):                                            
make()                                                                  
make('install')
```
regardless of whether or not the build system was correctly detected. This bug was introduced by #11981 when the variable name was changed from `body` to `body_def` but the existing package base classes were not updated. I changed the name back to `body`, but let me know if there is a good reason to keep it as `body_def`.
=> Fix generic body during package creation

var/spack/repos/builtin/packages/cryptsetup/package.py, var/spack/repos/builtin/packages/util-linux/package.py
This adds a variant to the util-linux package that controls whether it
builds its own libuuid.  Variant defaults to True.  It enables other
packages to choose to get libuuid from the libuuid package instead.
This also changes the cryptsetup package to use the ~libuuid variant.
Fixes #12829
=> util-linux variant for libuuid, cryptsetup use it

var/spack/repos/builtin/packages/boost/package.py
`spec['boost'].libs` currently causes error, from the default libs handler
This PR adds a libs property to the boost package.
=> Boost: add libs property

lib/spack/spack/parse.py, lib/spack/spack/repo.py, lib/spack/spack/spec.py, lib/spack/spack/test/spec_syntax.py
This is maybe a cleaner approach to do the same thing as described in #11103.  It gets around some of the ambiguities there and allows any combination of clispecs and yaml paths, including depending on other specs by yaml path.
Paths to spec yaml files (files containing concreted specs) can come in three flavors:
1. file in current directory (no relative path specifiers included e.g. `pkgconf.yaml`)
2. relative path (e.g. `./pkgconf.yaml`, `../../Documents/pkgconf.yaml`, etc.)
3. absolute path (`/home/me/pkgconf.yaml`, `/home/me/../me/pkgconf.yaml`, etc.)
This case collides with existing handling of namespaced specs.  Current examples like `builtin.yaml-cpp`, which need to keep working, provided some of the constraints we needed to handle.  To handle this case, we let the normal …
=> Support yaml paths anywhere specs are handled on CLI

lib/spack/spack/binary_distribution.py, lib/spack/spack/relocate.py, lib/spack/spack/test/packaging.py, var/spack/repos/builtin/packages/py-altgraph/package.py, var/spack/repos/builtin/packages/py-macholib/package.py
Update py-machotools dependencies and versions.
=> Update buildcache creation and installation to allow mach-o binary relocation using py-machotools on linux or macos.

var/spack/repos/builtin/packages/uriparser/package.py
Successfully installs on macOS 10.14.6 with Clang 10.0.1.
Seeing some weird problems with the unit tests. Reported it [upstream](https://github.com/uriparser/uriparser/issues/83).
=> Add uriparser package

var/spack/repos/builtin/packages/minizip/package.py
Successfully builds on macOS 10.14.6 with Clang 10.0.1.
This is a contributed packages that comes with the zlib tarball.
=> Add minizip package

var/spack/repos/builtin/packages/libunistring/package.py
Successfully installs and passes all unit tests on macOS 10.14.6 with Clang 10.0.1.
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libunistring-0.9.10-ivxnfbyjb3jd5tebppqoj6cdqsi3dpvm/lib/libunistring.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libunistring-0.9.10-ivxnfbyjb3jd5tebppqoj6cdqsi3dpvm/lib/libunistring.dylib:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libunistring-0.9.10-ivxnfbyjb3jd5tebppqoj6cdqsi3dpvm/lib/libunistring.2.dylib (compatibility version 4.0.0, current version 4.0.0)
/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version …
```
=> libunistring: add missing dependency on libiconv

var/spack/repos/builtin/packages/gdal/package.py
Successfully installs on macOS 10.14.6 with Clang 10.0.1.
The import unit tests fail, and `libkml` doesn't seem to be RPATHed correctly. Opened up an issue [upstream](https://github.com/OSGeo/gdal/issues/1840) but if anyone knows why RPATH isn't working let me know. For now, `DYLD_LIBRARY_PATH` needs to be set to import `osgeo`.
Tested by converting an MKL file to a Shapefile.
=> GDAL: Add support for MKL driver

var/spack/repos/builtin/packages/sqlite/package.py
Also adds missing dependency on zlib.
Successfully installs on macOS 10.14.6 with Clang 10.0.1.
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/sqlite-3.28.0-bnexuocixdforrf4cz6unyimqighnvpa/lib/libsqlite3.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/sqlite-3.28.0-bnexuocixdforrf4cz6unyimqighnvpa/lib/libsqlite3.dylib:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/sqlite-3.28.0-bnexuocixdforrf4cz6unyimqighnvpa/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
```
```console
$ otool -L …
```
=> Add SQLite 3.29.0

var/spack/repos/builtin/packages/diffutils/package.py
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-jvgimm7dfdzbuwjxhmrmrzfangw3r3ry/bin/diff
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-jvgimm7dfdzbuwjxhmrmrzfangw3r3ry/bin/diff:
/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-yxlkgmwyhdbocjsbrswrdiiz65s6duje/bin/diff
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-yxlkgmwyhdbocjsbrswrdiiz65s6duje/bin/diff:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libiconv-1.15-6y7tjlqe …
```
=> diffutils: add missing libiconv dependency

var/spack/repos/builtin/packages/wcslib/package.py
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/wcslib-6.4-rxqn53e3azxkvkxoe7qxy7nb2aga273g/lib/libwcs.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/wcslib-6.4-rxqn53e3azxkvkxoe7qxy7nb2aga273g/lib/libwcs.dylib:
libwcs.6.4.dylib (compatibility version 6.0.0, current version 6.4.0)
```
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/wcslib-6.4-rxqn53e3azxkvkxoe7qxy7nb2aga273g/lib/libwcs.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/wcslib-6.4-rxqn53e3azxkvkxoe7qxy7nb2aga273g/lib/libwcs.dylib:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/wcslib-6. …
```
=> wcslib: fix darwin install name

var/spack/repos/builtin/packages/libkml/package.py
Fixes https://github.com/OSGeo/gdal/issues/1840
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libkml-1.3.0-htdjxbbipmrmh35vhtf3slinfvttbpsy/lib/*.dylib
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libkml-1.3.0-htdjxbbipmrmh35vhtf3slinfvttbpsy/lib/libkmlbase.1.3.0.dylib:
libkmlbase.1.dylib (compatibility version 1.0.0, current version 1.3.0)
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/expat-2.2.5-ivx3l77irr7xnft6v2xduzqier7zlct3/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.7.0)
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/zlib-1.2.11-nqnlnxddpa4qfz5cnf4grnct57ds25ks/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11) …
```
=> libkml: fix darwin install name

var/spack/repos/builtin/packages/googletest/package.py
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/googletest-1.8.1-sdcowbfxteo6x2mnlzbuh3yobr6znwzf/lib/libgtest_main.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/googletest-1.8.1-sdcowbfxteo6x2mnlzbuh3yobr6znwzf/lib/libgtest_main.dylib:
libgtest_main.dylib (compatibility version 0.0.0, current version 0.0.0)
libgtest.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/googletest-1.8.1-sdcowbfxteo6x2mnlzbuh3yobr6znwzf/lib/libgtest_main.dylib …
```
=> googletest: fix darwin install name

var/spack/repos/builtin/packages/blis/package.py
Fixes https://github.com/numpy/numpy/issues/14180
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/blis-0.6.0-rufmzbffyfzqafiolixs4ztwdwz73adj/lib/libblis.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/blis-0.6.0-rufmzbffyfzqafiolixs4ztwdwz73adj/lib/libblis.dylib:
libblis.2.dylib (compatibility version 0.0.0, current version 0.0.0)
```
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/blis-0.6.0-v7dirtoptoe5d3vaxjb223mr6to6y3sb/lib/libblis.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/blis-0.6.0-v7dirtoptoe5d3vaxjb223mr6to6y3sb/lib/libblis.dylib: …
```
=> blis: fix darwin install name

lib/spack/spack/binary_distribution.py, lib/spack/spack/cmd/buildcache.py, lib/spack/spack/relocate.py, lib/spack/spack/test/packaging.py
=> Buildcache: put back the use of otool and install_name_tool when running on macOS.  Only use machotools on linux.

share/spack/spack-completion.bash
This PR adds the new --known-targets flag to the `spack arch` command.
=> Add --known-targets to bash completion for arch command

var/spack/repos/builtin/packages/py-protobuf/package.py
for python2.7 an empty `__init__.py` needed for  `import` to work for otherwise empty directories with a module folder
A similar fix was implemented for #12543
=> package/py-protobuf fix bug for python@2.7: google.protobuf not found

var/spack/repos/builtin/packages/intel-tbb/package.py
This process needs to judge if start of sentence is `CONLY=`.
=> intel-tbb: fix typo.

var/spack/repos/builtin/packages/charliecloud/package.py
Adds charliecloud/0.11. Also adds the test suite dependency `bats` (needed by all versions of charliecloud).
=> add charliecloud/0.11

var/spack/repos/builtin/packages/czmq/package.py
I’m may have been missing something obvious but I’m running into the following when installing `czmq` with the latest version of Spack.
```
$ spack install czmq
...
==> Executing phase: 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
'/ecp/sw/opt/xeon-x86_64/linux-centos7-x86_64/gcc-4.8.5/autoconf-2.69-dzuvqtysoqchxxlnfcfdvflwlvnwl542/bin/autoreconf' '-ivf' '-I' '/ecp/sw/opt/xeon-x86_64/linux-centos7-x86_64/gcc-4.8.5/pkgconf-1.6.1-zyia6fm5vvznsxxla43wto6vezv3jciz/share/aclocal'
5     ==> [2019-09-17-08:03:53.989870] Warning: *        a custom AUTORECO
NF phase in the package       *
6     ==> [2019-09-17-08:03:53.989947] Warning: **************************
*******************************
7     ==> [2019-09-17-08:03:53.999625] …
```
=> Added autoreconf stage for czmq

lib/spack/external/jsonschema/validators.py
Spack doesn't need `requests`, and neither does `jsonschema`, but `jsonschema` tries to import it, and it'll succeed if `requests` is on your machine (which is likely, given how popular it is).  This commit removes the import in our vendored `jsonschema` to improve Spack's startup time a bit.  (see https://github.com/psf/requests/issues/3213).
On my mac, the import of requests is ~28% of Spack's startup time when run as `spack --print-shell-vars sh,modules` (.069 / .25 seconds), which is what `setup-env.sh` runs.
On a Linux cluster where Python is mounted from NFS, this reduces `setup-env.sh` source time from ~1s to .75s.
Note: This issue will be eliminated if we upgrade to a newer `jsonschema` (we'd need to drop Python 2.6 for that).  See https://github.com/Julian/jsonschema/pull/388.
=> externals: avoid importing requests in jsonschema

lib/spack/external/__init__.py
Adding a note to the vendored `jsonschema` package to indicated how it has been modified not to import `requests`.
See  #12894.
=> externals: add note to jsonschema about modifications

var/spack/repos/builtin/packages/qt/package.py
The 'fontconfig' option is only valid when freetype is enabled (QT
qt-5.11.3):
```
ERROR: Feature 'fontconfig' was enabled, but the pre-condition
'!config.win32 && features.system-freetype && libs.fontconfig' failed.
```
=> Fix configure when disabling fontconfig on non-macOS systems

lib/spack/spack/test/cmd/create.py
This PR adds the creation of the remaining (16) templates to ensure we can create them with expected content.  The goal is to facilitate catching problems such as #12804 during testing.
=> tests: add more template creation tests

lib/spack/spack/compilers/clang.py, lib/spack/spack/test/compilers.py
Also add unit tests to prevent a regression.
```console
$ spack compiler find
==> Added 1 new compiler to /Users/Adam/.spack/darwin/compilers.yaml
clang@11.0.0
==> Compilers are defined in the following files:
/Users/Adam/.spack/darwin/compilers.yaml
```
```console
$ spack compiler find
==> Added 1 new compiler to /Users/Adam/.spack/darwin/compilers.yaml
clang@11.0.0-apple
==> Compilers are defined in the following files:
/Users/Adam/.spack/darwin/compilers.yaml
```
XCode 11 was released on September 20, 2019.
=> Fix detection of Apple Clang 11.0.0

var/spack/repos/builtin/packages/blis/Makefile_0.6.0.patch, var/spack/repos/builtin/packages/blis/package.py, var/spack/repos/builtin/packages/libflame/Makefile_5.2.0.patch, var/spack/repos/builtin/packages/libflame/package.py
With this, I can finally build `py-numpy+blas+lapack ^blis ^libflame` on Linux. There are still build problems on macOS, and `libflame` still has undefined symbols, but it's a step in the right direction.
@s-sajid-ali
=> Fix installation permissions on BLIS and libflame libs

lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/test/data/targets/linux-rhel6-piledriver, lib/spack/spack/test/llnl/util/cpu.py
fixes #12896 
Changes in the AMD models:
- `zen` (17h family) derives directly from `x86_64` and is not compatible with any of the 15h family
- Added more features that are peculiar of the 15h family
Added a unit test for `piledriver` using a `/proc/cpuinfo` from [here](https://www.redhat.com/archives/vfio-users/2015-August/msg00111.html)
=> AMD: fix architecture hierarchy (zen)

lib/spack/docs/basic_usage.rst, lib/spack/docs/build_settings.rst, lib/spack/spack/concretize.py, lib/spack/spack/test/concretize_preferences.py
Preferred targets (#3206) were failing because we were looking them up by `Microarchitecture` object, not by string.
You can now set up `packages.yaml` (or an environment) like this to prefer a particular target across your stack:
```yaml
packages:
all:
target: [sandybridge]
```
@carns: this should allow you to set your default target.
=> bugfix: use string keys to set preferred targets

var/spack/repos/builtin/packages/spdlog/package.py
Add newest release with ability to pre-build as shared or static library.
Intentionally skip 1.4.0 to avoid some regressions.
=> spdlog: v1.4.1

var/spack/repos/builtin/packages/perl-http-daemon/package.py
Added the following dependencies:
+    depends_on('perl-http-date', type=('build', 'run'))
+    depends_on('perl-module-build-tiny', type='build')
=> Add missing dependencies to perl-http-daemon

var/spack/repos/builtin/packages/perl-libwww-perl/package.py
The following dependencies are needed for perl-libwww-perl according to
https://metacpan.org:
+    depends_on('perl-encode-locale', type=('build', 'run'))
+    depends_on('perl-file-listing', type=('build', 'run'))
+    depends_on('perl-html-parser', type=('build', 'run'))
+    depends_on('perl-http-cookies', type=('build', 'run'))
+    depends_on('perl-http-daemon', type=('build', 'run'))
+    depends_on('perl-http-date', type=('build', 'run'))
+    depends_on('perl-http-message', type=('build', 'run'))
+    depends_on('perl-http-negotiate', type=('build', 'run'))
+    depends_on('perl-lwp-mediatypes', type=('build', 'run'))
+    depends_on('perl-net-http', type=('build', 'run'))
+    depends_on('perl-try-tiny', type=('build', 'run'))
+    depends_on('perl-uri', type=('build', 'run'))
+ …
=> Added depencies to perl-libwww-perl

var/spack/repos/builtin/packages/perl-list-moreutils/package.py
The following dependencies were added:
+    depends_on('perl-exporter-tiny', type=('build', 'run'))
+    depends_on('perl-list-moreutils-xs', type=('build', 'run'))
=> Added missing dependencies for perl-list-moreutils

var/spack/repos/builtin/packages/perl-xml-parser/package.py
This PR adds the following dependency:
+    depends_on('perl-libwww-perl', type=('build', 'run'))
=> Add missing dependency to perl-xml-parser

lib/spack/llnl/util/cpu/detect.py
Fixes #12905 
The output of `subprocess.check_output` is a byte string in Python 3. This causes dictionary lookup to fail later on.
A try-except around this function prevented this error from being noticed. Removed this so that more errors can propagate out.
@alalazo @tgamblin @becker33
=> Fix "specific target" detection in Python 3

var/spack/repos/builtin/packages/openblas/package.py
Currently the Openblas package shows the following error:
```
==> Error: AttributeError: 'Target' object has no attribute 'lower'
/projects/spack/var/spack/repos/builtin/packages/openblas/package.py:204, in make_defs:
201        if '+ilp64' in self.spec:
202            make_defs += ['INTERFACE64=1']
203
>>    204        if 'x86' in self.spec.architecture.target.lower():
205            if '~avx2' in self.spec:
206                make_defs += ['NO_AVX2=1']
207            if '~avx512' in self.spec:
```
This PR fixes this by converting the Target object into a string so that `lower()` can be called on it.
=> Fixing bug in openblas package

var/spack/repos/builtin/packages/libflame/Makefile_5.2.0_darwin.patch, var/spack/repos/builtin/packages/libflame/package.py
With this PR, I'm finally able to build NumPy 1.17.2 with libflame 5.2.0, BLIS 0.6.0, Python 3.7.4, and Clang 11.0.0 on macOS 10.14.6. All unit tests pass.
@s-sajid-ali
=> libflame: fix macOS build

var/spack/repos/builtin/packages/llvm/package.py, var/spack/repos/builtin/packages/mesa/package.py
Fixes #12931.
I suppose the recent introduction of a Target object broke a number of packages that assumed `spec.architecture.target` to be a string. Here is a fix for the llvm and mesa packages.
=> fixing target conversion to string

var/spack/repos/builtin/packages/libspatialite/package.py
- grep'ped the source code to confirm it has rtree dependency as mentioned in other places on the internet (also see https://docs.djangoproject.com/en/2.2/ref/contrib/gis/install/spatialite/)
- A careful look at config log reveals it has iconv and libxml2 dependency
=> package/libspatialite: improve dependencies

var/spack/repos/builtin/packages/interproscan/large-gid.patch, var/spack/repos/builtin/packages/interproscan/non-interactive.patch, var/spack/repos/builtin/packages/interproscan/package.py
This PR adds interproscan-4.8, which has a completely different build
system than version 5. Note that this builds for running on a host as
opposed to a queue system. I am fairly certain that a queue system can
be configured later.
This PR also adds a patch for intrproscan-5 to build when the user
building the packages has a large GID by setting posix mode for tar.
=> Add version 4 of interproscan

var/spack/repos/builtin/packages/flibcpp/package.py
Add a new spack package for [flibcpp](https://github.com/swig-fortran/flibcpp), Fortran bindings to the C++ standard library.
=> New package: flibcpp (Fortran bindings to C++ standard library)

var/spack/repos/builtin/packages/parsimonator/package.py
Now the support for SSE3 or AVX is tested on the selected target
=> parsimonator: simplified recipe by removing SIMD variants

var/spack/repos/builtin/packages/cp2k/package.py, var/spack/repos/builtin/packages/dealii/package.py, var/spack/repos/builtin/packages/elpa/package.py, var/spack/repos/builtin/packages/hpgmg/package.py, var/spack/repos/builtin/packages/krims/package.py, var/spack/repos/builtin/packages/lazyten/package.py, var/spack/repos/builtin/packages/libceed/package.py, var/spack/repos/builtin/packages/nanoflann/package.py, var/spack/repos/builtin/packages/rocksdb/package.py, var/spack/repos/builtin/packages/tealeaf/package.py, var/spack/repos/tutorial/packages/elpa/package.py
Now that Spack injects microarchitecture specific optimizations for the selected target, packages should avoid adding flags that could step over those flags.
=> Removed references to '(-march|-mtune|-mcpu)=native' in packages

lib/spack/spack/binary_distribution.py, lib/spack/spack/relocate.py
Changes deps and rpaths for bins and libs, changes id for libs using only macholib on Linux.
=> Relocate mach-o binaries using macholib on linux.

var/spack/repos/builtin/packages/qt/package.py
Since #3206, 'spec.architecture.target' returned the microarchitecture
target rather than the architecture family. This causes QT 4 to fail to
build because it's expecting something like 'x86_64' rather than
'broadwell'.
See #12914
Erorr message:
```
==> [2019-09-26-09:37:33.834286] './configure' '-prefix' '/rnsdhpc/code/spack/opt/spack/clang/qt/aguusfi' '-v' '-opensource' '-no-opengl' '-release' '-confirm-license' '-optimized-qmake' '-no-pch' '-no-freetype' '-no-openssl' '-no-sql-db2' '-no-sql-ibase' '-no-sql-oci' '-no-sql-tds' '-no-sql-mysql' '-no-sql-odbc' '-no-sql-psql' '-no-sql-sqlite' '-no-sql-sqlite2' '-shared' '-no-openvg' '-no-nis' '-nomake' 'examples' '-nomake' 'tools' '-no-dbus' '-no-framework' '-fast' '-no-declarative-debug' '-no-gtkstyle' '-no-webkit' '-no-phonon' '-arch' …
```
=> Fix 'arch' string in QT4 due to microarchitecture change

lib/spack/spack/build_systems/perl.py
This fixes #12852 where perl builds that use Build.PL will fail when the
shebang of the Build script produced from the configure step is too
long.
=> Fix perl build when using Build.PL

var/spack/repos/builtin/packages/libibumad/package.py
This package provides libibumad library and header files derived from the rdma-core distribution.
=> Added new package for libibumad.

var/spack/repos/builtin/packages/tau/package.py
The TAU defaults aren't very friendly on OSX/Darwin.  For that platform, instead of forcing the user to disable 5 defaults, just make them default 'False' for the Darwin architecture.
=> Changing variant defaults based on architecture (Darwin)

var/spack/repos/builtin/packages/eospac/package.py
This PR simply reflects the change of hostname that this project is housed by.
=> eospac: laws.lanl.gov -> laws-green.lanl.gov

var/spack/repos/builtin/packages/bolt/package.py
New BOLT release (1.0rc2). https://bolt-omp.org/downloads/
=> BOLT: update a version (1.0rc2)

var/spack/repos/builtin/packages/petsc/package.py
use list of library files for --with-zlib-lib=  to get rpath included correctly
Fixes #10585
=> correct with-xxx-lib= options

var/spack/repos/builtin/packages/vdt/package.py
Now the support for SSE3 or AVX is tested on the selected target
@tkameyama @t-karatsu
=> vdt: simplified recipe by removing SIMD variants

var/spack/repos/builtin/packages/bowtie/fix_narrowing_err.patch, var/spack/repos/builtin/packages/bowtie/for_aarch64.patch, var/spack/repos/builtin/packages/bowtie/package.py
* Correspond to `aarch64` architecture based on the following URL information.
URL: https://github.com/BenLangmead/bowtie/pull/13
* Fix bug about 'narrowing error'.
```error: constant expression evaluates to -1 which cannot be narrowed to type 'char' [-Wc++11-narrowing]```
=> bowtie: fix for aarch64, and bugfix about c++11-narrowing.

var/spack/repos/builtin/packages/raxml/package.py
Now the support for SSE3 or AVX is tested on the selected target.
@tkameyama @akthoma
=> raxml: simplified recipe by removing SIMD variants

lib/spack/llnl/util/cpu/microarchitectures.json
LLVM, mesa and other packages check for these generic microarchitectures. One solution is to let Spack know they exist.
@odoublewen
=> Add all the 'generic' architectures that are mentioned in recipes

bin/spack, lib/spack/spack/cmd/license.py
Closes #11783.
@michaelkuhn: I think this accomplishes what #11783 set out to do, but in a much simpler way.
The Python landscape is going to be changing in 2020, and Python 2 will be end of life. Spack should *prefer* Python 3 to Python 2 by default, but we still need to run on systems that only have Python2 available.
This is trickier than it sounds, as on some systems, the `python` command is `python2`; on others it's `python3`, and [RHEL8 doesn't even have the `python` command](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/).  Instead, it makes you choose `python3` or `python2`. You can thus no longer make a simple shebang to handle all the cases.
This commit makes the `spack` script bilingual.  It is still valid Python, but its shebang is `#!/bin/sh`, and it has a …
=> prefer python3 to python2 for running Spack

var/spack/repos/builtin/packages/gcc/package.py
Unlike the compiler binary name search logic, the `setup_environment` in GCC's package assumes the compiler names are *exactly* `gcc`, `g++`, etc. In many external installations (Homebrew, Macports) the installation includes only *suffixed* versions such as `gcc-9`.
This patch uses the GCC compiler search suffixes to actually locate the correct filenames for the installed compilers, allowing the Spack-generated module file to have useful definitions of CC, CXX, etc.
It also allows for the possibility that the user's external installation of GCC is compiled without Fortran support, in which case the `FC` environment variables are not defined.
@tmdelellis
=> Fix GCC environment variables for external installations

var/spack/repos/builtin/packages/libcerf/package.py
An error of unused functions occurs when building with Fujitsu compiler. Therefore, I added the same processing as Clang.
=> libcerf:add CFLAGS for fujitsu compiler

var/spack/repos/builtin/packages/adios2/package.py
Add the latest ADIOS2 release, [v2.5.0](https://github.com/ornladios/ADIOS2/releases/tag/v2.5.0) .
@chuckatkins any changes in dependencies? `zfp` seams not to be found yet during configuration stage.
=> ADIOS2: 2.5.0

var/spack/repos/builtin/packages/chapel/package.py
This change updates the Chapel language from 1.19 to version 1.20 which was released on Sept 19 2019. The changes can be found at https://github.com/chapel-lang/chapel/blob/release/1.20/CHANGES.md
=> Update chapel to current (1.19 -> 1.20)

lib/spack/spack/filesystem_view.py
Sometimes when `remove_file` is called on a link, that link is missing (perhaps ctrl-C happened halfway through a previous action, a `make clean` went rogue, ...). As removing a non-existent file is no problem, this patch changes the behaviour so Spack continues rather than erroring. 
Currently you would see
```ValueError: /path/to/my/env/.spack-env/view/share/info/dir is not a link tree!```
and now it continues silently.
=> when removing a file from a view, don't fail if it doesn't exist

lib/spack/spack/platforms/cray.py
The code doing detection employs two different strategies:
- Check the currently modules available
- Check the directory where module files are stored
The list of strategies can be extended easily in the future, if need be. If nothing is found the default is set to `platform.machine()`.
=> Improve robustness of target detection

var/spack/repos/builtin/packages/gcc/package.py
https://github.com/spack/spack/pull/12454 (7bcb306) updated `setup_environment` in the GCC package to examine the bin/ directory to find alternatively-named instances of CC but this failed to account for when GCC was being installed and failed when it attempted to list the not-yet-existing installation prefix.
This problem would also be addressed by https://github.com/spack/spack/pull/11115
=> Gcc package: setup environment bug when installing

var/spack/repos/builtin/packages/dataspaces/package.py, var/spack/repos/builtin/packages/savanna/package.py
Fix new URL for dataspaces.
Savanna has some other issues in dependencies besides its broken spec, which I am not addressing.
=> Dataspaces: Fix Fetch URL, Savanna Spec

lib/spack/spack/binary_distribution.py
Since #3206 build caches are too specific in which packages they show as available. On a broadwell machine, build caches should consider all packages built for x86_64 architectures broadwell or earlier.
Fixes #12935
=> binary cache: show all packages for compatible differing targets

var/spack/repos/builtin/packages/go-md2man/package.py
This PR explicitly disables module-mode that only came to being for go >= 1.11.  The intent of this spack recipe is to explicitly download go-md2man's dependency and put it into place for the final build.  This PR fixes #12787.
=> go-md2man: disable module-mode

lib/spack/spack/architecture.py, lib/spack/spack/main.py, share/spack/setup-env.csh, share/spack/setup-env.sh
fixes #12915
closes #12916
Since Spack has support for specific targets it might happen that software is built for targets that are not exactly the host because it was either an explicit user request or the compiler being used is too old to support the host.
Modules for different targets are written into different directories and by default Spack was adding to MODULEPATH only the directory corresponding to the current host. This PR modifies this behavior to add all the directories that are **compatible** with the current host.
@smjenness @pat-s @oehlrich9 @marcmengel
=> Add all compatible system types directory to module paths

var/spack/repos/builtin/packages/adios/package.py, var/spack/repos/builtin/packages/adios/zfp051.patch, var/spack/repos/builtin/packages/adios2/package.py, var/spack/repos/builtin/packages/zfp/package.py
ZFP is primarily build via CMake, which will have all install logic and configuration files generated.
The 0.5.0 release did not support this yet, so we toss it.
Fix #12998
cc @markcmiller86 @michaelkuhn
=> ZFP: CMake Package

var/spack/repos/builtin/packages/py-jupyter-notebook/package.py
As discussed in #10319 and discovered by @adamjstewart py-jupyter-notebook only depends on `node-js` and `npm` for mimification, which they do as part of their release process. Unfortunately the github releases are not releases in that sense, but from their point of view these constitute a from-source install. 
I dropped the dependencies and switched to pypi, unfortunately not all github-releases have a counterpart on pypi, so I dropped the missing ones and replaced the checksums by the output of `spack checksum`, the latter is required as all tar-balls differ (obviously), but in the default change from md5 to sha256 we had the discussion whether we should accept mass hash changes from "untrusted" sources, so I'm unsure on how to proceed here.
After this change `py-jupyter-notebook` no …
=> update py-jupyter-notebook to use the real releases

var/spack/repos/builtin/packages/breseq/package.py
* zlib dependency is fixed from build to link
* conflict unsupported gcc and clang version
=> breseq: fix dependency and limit compiler version.

var/spack/repos/builtin/packages/breakdancer/package.py
breakdancer use curses, but dependency is missing.
This PR add ncureses dependency on breakdancer
=> breakdancer: missing ncurses dependency.

var/spack/repos/builtin/packages/ants/package.py
* ants use zlib but ependency is missing.
* install() asummes package stage directory is current directory, but the current directory is source directory in current spack version, so I specify working directory to use self.build_directory.
=> ants: missing zlib dependency and fix working directory in install.

var/spack/repos/builtin/packages/singularity/package.py
#12995 broke the singularity build, at least for non-root users:
```
[+] /home/ghartzell/tmp/spack-direnv-update/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.2.0/squashfs-4.3-3bq655rauqfz4uvlcqdm7axs3szla7ir
==> Installing singularity
==> Searching for binary cache of singularity
==> Warning: No Spack mirrors are currently configured
==> No binary for singularity found: installing from source
==> Fetching https://github.com/sylabs/singularity/releases/download/v3.4.1/singularity-3.4.1.tar.gz
###################################################################################################################################################################################### 100.0%
==> Staging archive: /tmp/ghartzell/spack-stage/singularity-3.4.1-pzr4a77jsakpga6yl3oiwj2ndjplmbcz/singular …
```
=> Singularity 3.4.1 still needs the makefile patch

var/spack/repos/builtin/packages/cnpy/package.py
cnpy use zlib, but dependency is missin.
This PR add zlib dependency on cnpy.
=> cnpy: add zlib dependency.

var/spack/repos/builtin/packages/denovogear/package.py, var/spack/repos/builtin/packages/denovogear/stream-open.patch
* denovogear use zlib, but zlib dependency is missing
* Fix code to file open is failed.
=> denovogear: Add missing zlib depenbdency and fix open handling error.

var/spack/repos/builtin/packages/cp2k/package.py, var/spack/repos/builtin/packages/libint/package.py
This is basically the alternative to #12403: instead of using the libint package prepared by the CP2K project we can configure it directly. To make it easy I'd suggest an enumerated `tune` variant to switch sets of `./configure` parameters.
=> libint: 2-stage build with 'tune' and 'fortran' variants

var/spack/repos/builtin/packages/easybuild/package.py, var/spack/repos/builtin/packages/py-easybuild-easyblocks/package.py, var/spack/repos/builtin/packages/py-easybuild-easyconfigs/package.py, var/spack/repos/builtin/packages/py-easybuild-framework/package.py
Congratulations to EasyBuild for their big 4.0 release!
Among other things, EasyBuild 4.0 adds Python 3 support. As EasyBuild was one of the few remaining Spack packages that required Python 2, I took the liberty of updating to the latest version.
@boegel can you review this?
=> Add EasyBuild 4.0.0

var/spack/repos/builtin/packages/ngmlr/package.py
ngmlr use zlib but missing dependency.
This PR add zlib dependency to ngmlr.
=> ngmlr: add zlib dependency.

var/spack/repos/builtin/packages/muse/package.py
muse use zlib, bad zlib dependency is missiong.
This PR add zlib dependency on muse.
=> muse: add zlib dependency.

var/spack/repos/builtin/packages/metabat/package.py
metabat use curses and zlib, but missing dependency.
This PR add ncurses and  zlib dependency on metabat.
=> metabat: Add zlib and ncurses dependency.

var/spack/repos/builtin/packages/liblbxutil/package.py
liblbxutil use zlib but dependency is missing.
This PR add zlib dependency on liblbxutil.
=> liblbxutil: Add zlib dependency.

var/spack/repos/builtin/packages/hapcut2/package.py
hapcut2 use zlib but dependency is missing, This PR add zlib dependency to hapcut2.
=> hapcut2: add zlib dependency.

var/spack/repos/builtin/packages/fastqvalidator/chromosome.patch, var/spack/repos/builtin/packages/fastqvalidator/package.py
* fastqvalidator use zlib, but dependency is missing. This PR add zlib dependency.
* fastqvalidaor cannot build to erroneous deletes in Chromosome constructor.  This PR backport to upstream commit https://github.com/statgen/libStatGen/commit/3a10afe08c209dbacc3eca7794a5a8c0a42ee566
=> fastqvalidator: add zlib dependency and  Removes erroneous deletes in Chromosome

var/spack/repos/builtin/packages/graphmap/package.py
graphmap use zlib, but missing dependency.
This PR add zlib dependency.
=> graphmap: add zlib dependency.

var/spack/repos/builtin/packages/boost/package.py
Bootstraps with gcc, but compiles with clang.
=> boost: Use gcc toolset for bootstrap with Fujitsu compiler.

var/spack/repos/builtin/packages/fftw/package.py
This PR simplifies the FFTW recipe making use of the features introduced in #3206 and #9481:
- The variants to specify floating point precision have been collapsed in a single multi-valued variant
- The variants to specify SIMD support and FMA have been removed. Now the flags are activated when a feature is detected in the spec target
=> fftw: simplify the recipe and make use of specific targets

var/spack/repos/builtin/packages/migrate/package.py
migrate use zlib.
If zlib is not found, migrate is compiled zlib.
Currentry zlib dependency is missing.
TRhis PR add zlib dependency, and use the library.
=> migrate: add zlib dependency.

var/spack/repos/builtin/packages/llvm/package.py
The old link is dead. This one works, but I'm not sure if this is an official repo of llvm or someone's private fork. Either way, this works the old one doesn't, so I think it's an improvement
=> llvm: update link to the document explaining codesign

lib/spack/spack/main.py, lib/spack/spack/test/config.py
fixes #13045
When removing support for dotkit in #11986 the code trying to set the paths of the various module files was not updated to skip it. This results in a failure because of a key error after the deprecation
warning is displayed to user.
This commit fixes the issue and adds a unit test for regression. Note that code for Spack chains has been updated accordingly but no unit test has been added for that case.
=> Fixed issue caused by a custom dotkit root present in config.yaml

var/spack/repos/builtin/packages/expect/package.py
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib:
libexpect5.45.dylib (compatibility version 5.45.0, current version 5.45.0)
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect:
libexpect5.45.dylib (compatibility version 5.45.0, current version …
```
=> expect: fix darwin install name

etc/spack/defaults/modules.yaml, lib/spack/docs/environments.rst, lib/spack/spack/environment.py, lib/spack/spack/test/config.py, lib/spack/spack/test/data/config/modules.yaml, lib/spack/spack/test/environment_modifications.py
While the build environment already takes share/pkgconfig into account, the generated module files etc. only consider lib/pkgconfig and lib64/pkgconfig.
=> Consistently support pkg-config files in share subdirectory

var/spack/repos/builtin/packages/pcre2/package.py, var/spack/repos/builtin/packages/qt/package.py
follow up to https://github.com/spack/spack/pull/10817
strangely enough `qt` could not pick up dependencies, i.e. 
```
Checking for DoubleConversion... 
Trying source 0 (type inline) of library doubleconversion ...
None of [libdouble-conversion.dylib libdouble-conversion.tbd libdouble-conversion.a] found in [] and global paths.
=> source produced no result.
test config.qtbase_corelib.libraries.doubleconversion FAILED
```
and as a result
```
ERROR: Feature 'system-doubleconversion' was enabled, but the pre-condition 'features.doubleconversion && libs.doubleconversion' failed.
```
Similarly 
```
ERROR: Feature 'system-pcre2' was enabled, but the pre-condition 'libs.pcre2' failed.
ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' …
```
=> qt: help pick up dependencies

var/spack/repos/builtin/packages/py-contextlib2/package.py
PR #12657 adds `py-contextlib2` as fallback package for old python versions but does not add the corresponding package, which leads to concretization errors.
=> Add missing py-contextlib2

var/spack/repos/builtin/packages/go/package.py
Added latest version of Go that address security issues (https://groups.google.com/forum/#!topic/golang-announce/cszieYyuL9Q)
=> Added go 1.13.1 and 1.12.10

var/spack/repos/builtin/packages/watch/package.py
Adds a new package for the Linux `watch` command. Unfortunately the full procps package is Linux-only, so I had to make a separate package for this single command to build on macOS. This package is based off of https://github.com/Homebrew/homebrew-core/blob/master/Formula/watch.rb
Successfully installs on macOS 10.14.6 with Clang 11.0.0.
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/watch-3.3.15-kiz3awhf7mwvjm2fj2dzyfymwiv6rwz3/bin/watch 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/watch-3.3.15-kiz3awhf7mwvjm2fj2dzyfymwiv6rwz3/bin/watch:
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/ncurses-6.1-ugyc74k76z7yu52ik3epobty2dscu53z/lib/libncurses.6.dylib (compatibility version 6.0.0, current …
```
=> Add watch package

lib/spack/docs/environments.rst, lib/spack/spack/environment.py, lib/spack/spack/schema/env.py, lib/spack/spack/test/cmd/env.py
depends on #12213 
fixes #9902
fixes #11095
This PR adds a boolean entry in `spack.yaml`:
```yaml
spack:
concretize_together: true
```
If set to `true` all the specs in the environment are concretized to be self-consistent, meaning there will be a single configuration for each package and a single provider for each virtual dependency. The default value is `false` to maintain backward compatibility with the behavior before this PR.
=> Spack environments can concretize specs together

var/spack/repos/builtin/packages/py-apipkg/package.py
The checksums for version `1.4` and `1.5` of `py-apipkg` are mixed up.
Compare:
https://pypi.org/project/apipkg/1.4/#copy-hash-modal-57804a89-dc76-417d-8c39-33b05b7f789a
https://pypi.org/project/apipkg/1.5/#copy-hash-modal-241f1f7c-fa7f-49f1-af44-338103d5ad4b
=> py-apipkg: Fix mix up of checksums

lib/spack/spack/operating_systems/mac_os.py
```console
$ spack arch
darwin-macos-ivybridge
```
```console
$ spack arch
darwin-catalina-ivybridge
```
Also added older macOS releases because why not?
=> Add macOS Catalina support

var/spack/repos/builtin/packages/qmcpack/package.py
Two small fixes:
- Get CMake build types working again
- LIBXML2 flags only needed for older releases.
@adamjstewart
=> QMCPACK Oct2019 fix buglets

var/spack/repos/builtin/packages/tabix/package.py
tabix use zlib.  but zlib dependency is missing.
This pr add zlib dependency to tabix.
=> tabix: add zlib dependency.

var/spack/repos/builtin/packages/seqprep/package.py
seqprep use zlib. but dependency is missing.
This PR add zlib dependency on seqprep.
=> seqprep: add zlib dependency.

var/spack/repos/builtin/packages/psmc/package.py
psmc use zlib. but zlib dependency is missing.
This pr add zlib dependency to psmc.
=> psmc: add zlib dependency.

var/spack/repos/builtin/packages/perl-perlio-gzip/package.py
perl-perlio-gzip use zlib, but dependency is missing.
This PR add zlib ependency on perl-perlio-gzip.
=> perl-perlio-gzip: add zlib dependency.

lib/spack/spack/binary_distribution.py
=> "No Spack mirror configured": demoted the warning to a debug message

var/spack/repos/builtin/packages/mysql/package.py
This also changes the default for cxxstd from 98 to 14 because (at least) newer versions of mysql do not compile with 98 (tested with gcc@9).
=> mysql: Add missing dependencies

lib/spack/spack/relocate.py
This should fix a Python3 error from concatenating strings and bytes.
=> Buildcache: pass string.encode('utf-8') for old_dir and new_dir to replace_prefix_bin

var/spack/repos/builtin/packages/py-maestrowf/package.py
Addition of 1.1.3 and 1.1.4 of Maestro to Spack. Also fixed a small bug where `enum-34` was always installed regardless of Python version.
=> Add new versions of py-maestrowf

var/spack/repos/builtin/packages/py-line-profiler/package.py
See rkern/line_profiler#166. Closes #13059.
=> py-line-profiler: add 2.1.2, re-run cython if needed

var/spack/repos/builtin/packages/sqlite/package.py
=> Add sqlite 3.30.0

var/spack/repos/builtin/packages/ncurses/package.py
#3896 added a gdbm dependency to perl, meaning curl -> openssl -> perl -> gdbm -> readline -> ncurses -> pkgconf
=> ncurses: https -> http

var/spack/repos/builtin/packages/gdbm/package.py
#3896 added a gdbm dependency to perl, meaning curl -> openssl -> perl -> gdbm -> readline -> ncurses -> pkgconf
=> gdbm: https -> http

var/spack/repos/builtin/packages/readline/package.py
#3896 added a gdbm dependency to perl, meaning curl -> openssl -> perl -> gdbm -> readline -> ncurses -> pkgconf
=> Add readline 8.0

var/spack/repos/builtin/packages/pkgconf/package.py
#3896 added a `gdbm` dependency to `perl`, meaning curl -> openssl -> perl -> gdbm -> readline -> ncurses -> pkgconf
=> Add pkgconf 1.6.3

var/spack/repos/builtin/packages/perl/package.py
=> Add latest Perl releases

var/spack/repos/builtin/packages/openssl/package.py
=> Add latest openssl releases

var/spack/repos/builtin/packages/isl/package.py
=> Add isl 0.21

var/spack/repos/builtin/packages/gettext/package.py
=> Add gettext 0.20.1

var/spack/repos/builtin/packages/expat/package.py
=> Add expat 2.2.9

var/spack/repos/builtin/packages/sublime-text/package.py
* added new version 3.2.2.3211
* symlink to the binary into a new subdirectory `bin` to keep $PATH clean
* sublime_text may also be called from the terminal with optional flags, on the web often referred to as `subl`
=> sublime-text: New version, adapt install process

var/spack/repos/builtin/packages/bash/package.py
=> Add patches and missing dependency to bash

lib/spack/spack/spec.py, lib/spack/spack/test/spec_semantics.py
fixes #13111
Due to a missing case we were treating a single target that was not equal to the one we were comparing to as a range open on the right.
=> ArchSpec: fix constraint satisfaction for targets

lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/test/llnl/util/cpu.py
Both floating-point and NEON are required in all standard ARMv8 implementations. Theoretically 
though specialized markets can support no NEON or floating-point at all. Source for this info [here](https://developer.arm.com/docs/den0024/latest/aarch64-floating-point-and-neon).
On the other hand the base procedure call standard for Aarch64:
> assumes the availability of the vector registers for passing floating-point and SIMD arguments. 
Further:
> the Arm 64-bit architecture defines two mandatory register banks: a general-purpose register bank which can be used for scalar integer processing and pointer arithmetic; and a SIMD and Floating-Point register bank".
Source for this info [here](https://developer.arm.com/docs/ihi0055/latest/procedure-call-standard-for-the-arm-64-bit-architecture). …
=> Added NEON to the list of features required for the aarch64 family

lib/spack/spack/config.py, lib/spack/spack/stage.py, lib/spack/spack/test/config.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/stage.py
Fixes #12651
Fixes #12798
Fixes #13009 
This PR restructures tests needing to temporarily change the`config:build_stage` path such that the tests no longer create or overwrite the setting in `$HOME/.spack/config.yaml`.  The change also appears to resolve stage path related issues when filtering tests on staging.
This PR consists of **two distinct commits**.  The first provides support for nested `overrides` scopes, which are created via the `spack.config.override` context manager.  The second commit changes how the `autouse`'d `mock_stage` and assorted test fixtures and tests establish their temporary stage directories. 
TODO :
=> Tests/bugfix: clean up build stage handling

lib/spack/spack/build_systems/autotools.py
fixes #13196
The fix reverts the semantic meaning of this check to what was before #3206
=> Autotools build system to patch config.guess based on a range check

var/spack/repos/builtin/packages/adiak/package.py
Adds a new package, adiak.  Adiak works with tools like caliper to collect metadata about HPC application runs.
=> Add adiak package, version 0.1.1

var/spack/repos/builtin/packages/f18/package.py
Minor updates and enhancements to the F18 package:
- Support CMake build types
- Update LLVM dependency
- Add conflict to only include compilers that support C++17
@certik @adamjstewart
=> F18 Oct2019 Minor Update

lib/spack/spack/cmd/bootstrap.py, lib/spack/spack/cmd/install.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/install.py
Creates the option to install only from binary cache, ignoring Spack's ability to build from source.
=> install command: add cache-only option

var/spack/repos/builtin/packages/utf8proc/package.py
=> Add utf8proc package

var/spack/repos/builtin/packages/graphviz/package.py
=> Add graphviz 2.42.2

var/spack/repos/builtin/packages/help2man/package.py
=> Add help2man 1.47.11

var/spack/repos/builtin/packages/scons/package.py
=> Add SCons 3.1.1

var/spack/repos/builtin/packages/valgrind/package.py
The conflict immediately below the variant prevents building the package on macOS.
=> Fix valgrind concretization on macOS

var/spack/repos/builtin/packages/watch/package.py
=> Add missing gettext dependency to watch

var/spack/repos/builtin/packages/wget/package.py
=> Add missing libiconv dependency to wget

var/spack/repos/builtin/packages/py-atomicwrites/package.py
=> Add py-atomicwrites 1.3.0

var/spack/repos/builtin/packages/py-bottleneck/package.py
=> Add missing test dependency to py-bottleneck

var/spack/repos/builtin/packages/py-certifi/package.py
=> Add py-certifi 2019.9.11

var/spack/repos/builtin/packages/py-importlib-metadata/package.py
=> Add py-importlib-metadata 0.23

var/spack/repos/builtin/packages/py-packaging/package.py
=> Add py-packaging 19.2

var/spack/repos/builtin/packages/py-setuptools/package.py
=> Add py-setuptools 41.4.0

var/spack/repos/builtin/packages/mpfr/package.py
Successfully installs and passes all tests on macOS 10.15 with Clang 11.0.0.
Stolen from https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpfr.rb#L21
=> mpfr: fix make check on catalina

var/spack/repos/builtin/packages/py-setuptools-scm/package.py
=> Add py-setuptools-scm 3.3.3

var/spack/repos/builtin/packages/py-pytz/package.py
=> Add py-pytz 2019.3

var/spack/repos/builtin/packages/py-py/package.py
=> Add py-py 1.8.0

var/spack/repos/builtin/packages/py-pillow/package.py
=> Add py-pillow 6.2.0

var/spack/repos/builtin/packages/py-more-itertools/package.py
=> Add py-more-itertools 7.2.0

var/spack/repos/builtin/packages/py-joblib/package.py
=> Add py-joblib 0.14.0

var/spack/repos/builtin/packages/py-attrs/package.py
=> Add py-attrs 19.2.0

var/spack/repos/builtin/packages/libpng/package.py
The last time there was a security vulnerability found in libpng, we removed all older versions. Is this still the recommended approach?
=> Add libpng 1.6.37

var/spack/repos/builtin/packages/freetype/package.py
=> Add freetype 2.10.1

var/spack/repos/builtin/packages/bison/package.py
=> Add bison 3.4.2

var/spack/repos/builtin/packages/apr-util/package.py
=> Add apr-util 1.6.1

lib/spack/spack/test/mirror.py, lib/spack/spack/test/svn_fetch.py
The SVN mock fixture requires both `svn` and `svnadmin`, but we only check for `svn`. macOS Catalina comes with `svn` but not `svnadmin`. This change causes the SVN tests to correctly be skipped.
=> Fix svn tests, skip if svnadmin not found

lib/spack/spack/cmd/url.py, lib/spack/spack/test/cmd/url.py
`spack url stats` now also looks at packages' resources when calculating statistics.
Example:
```
$ spack url stats
==> URL stats for 3531 packages:
--------------------------------------------------------------
stat                    versions        %   resources        %
--------------------------------------------------------------
url                         8335    89.3%         339    89.0%
schemes
https               6489    69.5%          93    24.4%
ftp                   32     0.3%           8     2.1%
http                1763    18.9%         237    62.2%
file                  51     0.5%           1     0.3%
checksums
md5                   26     0.3%           0     0.0%
sha256              8306    89.0%         336    88.2%
no checksum            3     0.0%           3 …
```
=> commands: add resource stats to `spack url stats`

var/spack/repos/builtin/packages/adios2/package.py
Provide up to date specs for build options
Remove non-production versions
Remove Python 2 support
Format using autopep8
@ax3l @chuckatkins @olesenm please review
=> adios2 package configuration cleanup

lib/spack/spack/cmd/install.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/install.py, var/spack/repos/builtin.mock/packages/dependent-install/package.py
Fixes #12002 
Allows `spack install --only dependencies foo` or `spack install --only dependencies` in an environment to work. The former will install all dependencies of foo in the environment, and the latter will install all dependencies of all root specs in the environment.
=> bugfix: install --only dependencies works in env

var/spack/repos/builtin/packages/ntpoly/package.py
I added definition of `CMAKE_Fortran_MODDIR_FLAG` to detect fortran modules when using Fujitsu compiler.
=> ntpoly: Define module directry when compiling with Fujitsu compiler.

lib/spack/spack/modules/lmod.py, lib/spack/spack/test/modules/lmod.py, share/spack/templates/modules/modulefile.lua
fixes #13005
This commit fixes an issue with the name of the root directory for module file hierarchies. 
Since #3206 the root folder was named after the microarchitecture used for the spec, which is too specific and not backward compatible for lmod hierarchies. Here we compute the root folder name using the target family instead of the target name itself and we add target information in the "whatis" portion of the module file.
=> lmod: module files are written in a root folder named by target family

var/spack/repos/builtin/packages/adios2/package.py
There are few conventions for variant defaults in Spack, but `shared` (true), `mpi` (true) and `python` (false) are defined.
https://spack.readthedocs.io/en/latest/packaging_guide.html#variant-names
This can still be requested explicitly by users (`spack install adios2 +python`) and reduces the complexity of the default install a bit. Fortran bindings should potentially also be requested explicitly, but Spack (due to MPI packages) defaults them in anyway.
cc @williamfgc @chuckatkins
=> ADIOS2: Default no Python

var/spack/repos/builtin/packages/python/package.py
Add the newly-released 3.8.0. There doesn't appear to be any build changes on https://docs.python.org/3/whatsnew/3.8.html so I think just adding the new version is sufficient.
=> add python version 3.8.0

lib/spack/llnl/util/filesystem.py, lib/spack/spack/test/llnl/util/filesystem.py
Since the backup file is only created on the first invocation, it will contain the original file without any modifications. Further invocations will then read the backup file, effectively reverting prior invocations.
This can be reproduced easily by trying to install likwid, which will try to install into /usr/local. Work around this by creating a temporary file to read from.
@alalazo @tgamblin @tkameyama
=> Fix filter_file

lib/spack/spack/util/imp/importlib_importer.py
Our importer was always parsing from source (which is considerably slower) because the source size recorded in the `.pyc` file differed from the size of the input file.
This speeds up importing all of Spack's packages by about 25% for me (13 seconds vs. 10 seconds).  In conjunction with #13238, this brings `import` time for all 3500 packages down to about 7 seconds (from 13).
=> importing: make importlib_importer recognize .pyc cache files

lib/spack/spack/multimethod.py, lib/spack/spack/package.py
Python 3 metaclasses have a `__prepare__` method that lets us save the class's dictionary before it is constructed.  In Python 2 we had to walk up the stack using our `caller_locals()` method to get at this.  Using `__prepare__` is much faster as it doesn't require us to use `inspect`.
This PR makes multimethods use the faster `__prepare__` method in Python3, while still using `caller_locals()` in Python 2.  We try to reduce the use of caller locals using caching to speed up Python 2 a little bit.
This makes loading all packages in Python 3 ~25% faster for me (7.4 seconds vs. 10 seconds).
=> multimethods: avoid calling caller_locals() in Python 3

lib/spack/spack/spec.py
Satisfaction checks on dependencies should be strict when the parent check is strict
This is intended for constraints like 
```
depends_on('py-backports-functools-lru-cache', when='^python@:2')
```
currently, Spack will add the `py-backports-functools-lru-cache` dependency at a point in the concretization when the dependency is just `^python` (without a version) because strict constraint checking does not propagate to dependency constraint checking.
Note that because the concretizer is greedy, the constraints applied by the `py-backports-functools-lru-cache` dependency will be applied later and may generate concretizer conflicts (which requires the user to specify certain constraints on the command line), but this avoids the concretizer incorrectly adding the …
=> Strict dependency constraint checking

var/spack/repos/builtin/packages/adios2/package.py, var/spack/repos/builtin/packages/dataspaces/package.py
Add missing dependencies to ADIOS2. Without explicit control, those dependencies might get picked up from the system environment and will cause unstable builds.
Add a newer release of DataSpaces (1.8.0) for ADIOS2. Also add missing `-fPIC` flags since this is a static library.
Mentioned in https://github.com/spack/spack/pull/13220#issuecomment-542380335
cc @williamfgc @chuckatkins @philip-davis
=> ADIOS2: Dataspaces, libffi, libfabric

var/spack/repos/builtin/packages/brotli/package.py
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/clang-11.0.0-apple/brotli-1.0.7-vqhkxyd6fyuiettn3c5mel7e5givipwg/lib/libbrotli*.dylib | sort | uniq
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
libbrotlicommon.1.dylib (compatibility version 1.0.0, current version 1.0.7)
libbrotlidec.1.dylib (compatibility version 1.0.0, current version 1.0.7)
libbrotlienc.1.dylib (compatibility version 1.0.0, current version 1.0.7)
```
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/clang-11.0.0-apple/brotli-1.0.7-vqhkxyd6fyuiettn3c5mel7e5givipwg/lib/libbrotli*.dylib | sort | uniq
/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/clang-11.0.0-apple/brotli-1. …
```
=> brotli: fix darwin install name

var/spack/repos/builtin/packages/gcc/package.py
Fixes #13232
See https://gcc.gnu.org/install/build.html:
> For a native build, the default configuration is to perform a 3-stage bootstrap of the compiler when ‘make’ is invoked. This will build the entire GCC system and ensure that it compiles itself correctly. It can be disabled with the --disable-bootstrap parameter to ‘configure’, but bootstrapping is suggested because the compiler will be tested more completely and could also have better performance.
Although bootstrapping is _suggested_, I found that disabling it changed the build time from 2 hrs to 30 min.
=> GCC: fix build on macOS Catalina

lib/spack/llnl/util/cpu/microarchitecture.py, lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/architecture.py, lib/spack/spack/compilers/__init__.py, lib/spack/spack/test/architecture.py, lib/spack/spack/test/compilers.py, lib/spack/spack/test/concretize.py, lib/spack/spack/test/data/compilers.yaml, lib/spack/spack/test/llnl/util/cpu.py
fixes #13104
This PR adds microarchitecture specific optimization flags to Clang / LLVM starting from version 3.9:
```console
$ spack -d install zlib %clang
[...]
==> [2019-10-17-20:21:19.885939] Successfully installed zlib
Fetch: 0.00s.  Build: 4.10s.  Total: 4.10s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-8.0.0/zlib-1.2.11-5i54k54rkpieapytrliahvgb52vcr2km
==> [2019-10-17-20:21:19.888574] WRITE LOCK: /home/culpo/PycharmProjects/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-17-20:21:19.888965] WRITE LOCK: /home/culpo/PycharmProjects/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-17-20:21:19.903866] WRITE LOCK: /home/culpo/PycharmProjects/spack/opt/spack/.spack-db/lock[0:0] [Released]
$ head -n 4 …
```
=> Microarchitecture specific optimizations for LLVM

lib/spack/spack/hooks/sbang.py
We've been doing this for quite a while now, and it does not seem to cause issues.
=> shebangs: don't warn when patching long shebangs

var/spack/repos/builtin/packages/py-brotlipy/package.py
=> Add py-brotlipy package

var/spack/repos/builtin/packages/py-docutils-stubs/package.py
=> Add py-docutils-stubs package

var/spack/repos/builtin/packages/py-typed-ast/package.py
=> Add py-typed-ast package

var/spack/repos/builtin/packages/py-sphinxcontrib-serializinghtml/package.py
=> Add py-sphinxcontrib-serializinghtml package

var/spack/repos/builtin/packages/py-sphinxcontrib-qthelp/package.py
=> Add py-sphinxcontrib-qthelp package

var/spack/repos/builtin/packages/py-sphinxcontrib-jsmath/package.py
=> Add py-sphinxcontrib-jsmath package

var/spack/repos/builtin/packages/py-sphinxcontrib-htmlhelp/package.py
=> Add py-sphinxcontrib-htmlhelp package

var/spack/repos/builtin/packages/py-sphinxcontrib-applehelp/package.py
=> Add py-sphinxcontrib-applehelp package

var/spack/repos/builtin/packages/py-sphinxcontrib-devhelp/package.py
=> Add py-sphinxcontrib-devhelp package

var/spack/repos/builtin/packages/py-flake8-import-order/package.py
=> Add py-flake8-import-order package

var/spack/repos/builtin/packages/py-raven/package.py
=> Add py-raven package

var/spack/repos/builtin/packages/py-pytest-forked/package.py
=> Add py-pytest-forked package

var/spack/repos/builtin/packages/py-mypy/package.py
=> Add py-mypy package

var/spack/repos/builtin/packages/py-mypy-extensions/package.py
=> Add py-mypy-extensions package

var/spack/repos/builtin/packages/py-werkzeug/package.py
=> Add latest version of py-werkzeug

var/spack/repos/builtin/packages/py-virtualenv/package.py
=> Add latest version of py-virtualenv

var/spack/repos/builtin/packages/py-urllib3/package.py
=> Add latest version of py-urllib3

var/spack/repos/builtin/packages/py-typing-extensions/package.py
=> Add latest version of py-typing-extensions

var/spack/repos/builtin/packages/py-torchvision/package.py
=> Add latest version of py-torchvision

var/spack/repos/builtin/packages/py-httpbin/package.py
=> Add latest version of py-httpbin

var/spack/repos/builtin/packages/py-hypothesis/package.py
=> Add latest version of py-hypothesis

var/spack/repos/builtin/packages/py-idna/package.py
=> Add latest version of py-idna

var/spack/repos/builtin/packages/py-itsdangerous/package.py
=> Add latest version of py-itsdangerous

var/spack/repos/builtin/packages/py-jinja2/package.py
=> Add latest version of py-jinja2

var/spack/repos/builtin/packages/py-lxml/package.py
=> Add latest version of py-lxml

var/spack/repos/builtin/packages/py-markupsafe/package.py
=> Add latest version of py-markupsafe

var/spack/repos/builtin/packages/py-mock/package.py
=> Add latest version of py-mock

var/spack/repos/builtin/packages/py-pip/package.py
=> Add latest version of py-pip

var/spack/repos/builtin/packages/py-psutil/package.py
=> Add latest version of py-psutil

var/spack/repos/builtin/packages/py-pycparser/package.py
=> Add latest version of py-pycparser

var/spack/repos/builtin/packages/py-pysocks/package.py
=> Add latest version of py-pysocks

var/spack/repos/builtin/packages/py-pytest-cov/package.py
=> Add latest version of py-pytest-cov

var/spack/repos/builtin/packages/py-pytest-httpbin/package.py
=> Add latest version of py-pytest-httpbin

var/spack/repos/builtin/packages/py-pytest-mock/package.py
=> Add latest version of py-pytest-mock

var/spack/repos/builtin/packages/py-pytest-xdist/package.py
=> Add latest version of py-pytest-xdist

var/spack/repos/builtin/packages/py-pyyaml/package.py
The libyaml dependency is optional. Without it, it falls back on a pure-Python implementation, which is much slower.
=> Add latest version of py-pyyaml

var/spack/repos/builtin/packages/py-requests/package.py
=> Add latest version of py-requests

var/spack/repos/builtin/packages/py-snowballstemmer/package.py
=> Add latest version of py-snowballstemmer

var/spack/repos/builtin/packages/py-sphinx/package.py
=> Add latest version of py-sphinx

var/spack/repos/builtin/packages/py-sphinxcontrib-websupport/package.py
=> Add latest version of py-sphinxcontrib-websupport

var/spack/repos/builtin/packages/py-coverage/package.py
=> Add latest version of py-coverage

var/spack/repos/builtin/packages/py-decorator/package.py
=> Add latest version of py-decorator

var/spack/repos/builtin/packages/py-execnet/package.py
=> Add latest version of py-execnet

var/spack/repos/builtin/packages/py-click/package.py
=> Add latest version of py-click

var/spack/repos/builtin/packages/py-chardet/package.py
=> Add latest version of py-chardet

var/spack/repos/builtin/packages/py-babel/package.py
=> Add latest version of py-babel

var/spack/repos/builtin/packages/py-apipkg/package.py
=> Add missing dependencies to py-apipkg

var/spack/repos/builtin/packages/py-typing/package.py
=> Add latest version of py-typing

var/spack/repos/builtin/packages/py-alabaster/package.py
=> Add missing test dependency to py-alabaster

var/spack/repos/builtin/packages/googletest/package.py
=> Add latest version of googletest

var/spack/repos/builtin/packages/libgcrypt/package.py
=> Add latest version of libgcrypt

var/spack/repos/builtin/packages/libyaml/package.py
By switching to the official download tarballs, we no longer need Autotools except for the master branch.
=> Add latest version of libyaml

var/spack/repos/builtin/packages/libgeotiff/package.py
=> libgeotiff: http -> https

var/spack/repos/builtin/packages/libtiff/package.py
=> libtiff: http -> https

var/spack/repos/builtin/packages/openblas/package.py
=> openblas: http -> https

var/spack/repos/builtin/packages/openjpeg/package.py
=> Add missing zlib dependency to openjpeg

var/spack/repos/builtin/packages/uriparser/package.py
Doesn't seem to build with googletest 1.10.0, and there are no newer releases than 1.8.1 to test against. Locking the version for now.
=> Use specific version of googletest for uriparser

var/spack/repos/builtin/packages/py-tables/package.py
=> Add latest version of py-tables

var/spack/repos/builtin/packages/py-numpy/package.py
=> Add latest version of py-numpy

var/spack/repos/builtin/packages/py-cffi/package.py
=> Add latest version of py-cffi

var/spack/repos/builtin/packages/python/package.py
Tested with Python 2.7.16, 3.7.3, 3.7.4, and 3.8.0.
Python 3.8.0 is still horribly broken (see #13256), so I wouldn't recommend anyone actually use it until a more stable point release comes out, but this PR lets it build successfully.
=> Fix Python 3.8 build on macOS

lib/spack/llnl/util/cpu/__init__.py, lib/spack/llnl/util/cpu/microarchitecture.py, lib/spack/spack/architecture.py, lib/spack/spack/test/architecture.py, lib/spack/spack/test/data/compilers.yaml, lib/spack/spack/test/llnl/util/cpu.py
closes #13194 
Custom string versions for compilers were raising a ValueError on conversion to int. This commit fixes the behavior by trying to detect the underlying compiler version when in presence of a custom string version.
=> Fix custom compiler versions with microarchitectures

.travis.yml, lib/spack/spack/cmd/bootstrap.py, lib/spack/spack/main.py, share/spack/qa/run-bootstrap-tests
fixes #13073
Since #3206 was merged bootstrapping environment-modules was using the architecture of the current host or the best match supported by the default compiler. The former case is an issue since shell integration was looking for a spec targeted at the host microarchitecture.
This commit fixes the problem by:
1. Bootstrapping an en modules targeted at generic architectures
2. Looking for generic targets in shell integration scripts
=> Bootstrap environment modules optimizing for generic architectures

var/spack/repos/builtin/packages/qt/package.py
For some reason, newer versions of qt fail to build because they cannot find certain system libraries such as libatomic and libdl.
Leaving the qmake compiler set to gcc seems to fix the problem.
Fixes #13221
=> qt: Fix build for newer versions

var/spack/repos/builtin/packages/bpp-core/clarify_isnan.patch, var/spack/repos/builtin/packages/bpp-core/package.py
Clarify isnan's namespace, because Fujitsu compiler can't resolve ambiguous of 'isnan' function.
- Error 
2441 /path_to_bpp-core/spack-src/src/Bpp/Numeric/Function/ThreePointsNumericalDerivative.cpp:56:51: error: c     
all to 'isnan' is ambiguous
=> bpp-core: Clarify 'isnan' function's namespace.

var/spack/repos/builtin/packages/arpack-ng/incompatible_isnan_fix.patch, var/spack/repos/builtin/packages/arpack-ng/package.py
Fujitsu compiler does not support `isnan` function.
- isnan: function that determines whether it is `NaN`.
So, I Modified to judge `NaN` without using `isnan` function.
=> arpack-ng: Fixed error that is not compatible with 'isnan'.

var/spack/repos/builtin/packages/elsi/package.py
An error occurs indicating that the specified module cannot be used when building with Fujitsu compiler.Therefore, a process to specify a module is added.
=> elsi:add CMAKE Fortran MODDIR FLAG for Fujitsu compiler

var/spack/repos/builtin/packages/zstd/package.py
=> Add latest version of zstd

var/spack/repos/builtin/packages/patchelf/package.py
=> Add latest version of patchelf

var/spack/repos/builtin/packages/gnupg/package.py
Also adds several missing dependencies, dependency version constraints, and fixes configure arg spellings.
=> Add latest version of gnupg

var/spack/repos/builtin/packages/libgcrypt/package.py
=> Add dependency version constraint to libgcrypt

var/spack/repos/builtin/packages/py-astropy/package.py
Fixes #13119 
@Sinan81 can you test this? Some of the other build flags may also be specific to the latest release.
I'm not sure exactly which version of Python/setuptools is required for parallel builds, but this seems like a good default for now.
=> Restrict parallel build of py-astropy to Python 3

var/spack/repos/builtin/packages/py-sphinxcontrib-programoutput/package.py
=> Add latest version of py-sphinxcontrib-programoutput

var/spack/repos/builtin/packages/py-macs2/package.py
py-macs2 now supports Python 3!
=> Add latest version of py-macs2

var/spack/repos/builtin/packages/npth/package.py
=> Add latest version of npth

var/spack/repos/builtin/packages/py-scikit-learn/package.py
=> Add latest version of py-scikit-learn

var/spack/repos/builtin/packages/adios2/package.py
Update the documentation of the `endian_reverse` variant in ADIOS2. The short description caused [some confusion](https://github.com/ornladios/ADIOS2/issues/1822) (for me) :-)
cc @williamfgc @chuckatkins
=> ADIOS2: Document endian_reverse variant

var/spack/repos/builtin/packages/boost/package.py
Boost iostream autodetects the compression libraries libzstd and liblzma outside of the Spack environment.
This PR disables mentioned libraries. [Boost docs](https://www.boost.org/doc/libs/develop/libs/iostreams/doc/installation.html)
=> Boost: Fix iostream autodetect libraries outside Spack

.travis.yml
Travis macOS builds are taking too long to run, so we'll only run them on `develop` until they get faster.
=> Disable macOS builds on PRs while we wait for Travis to catch up.

lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/test/architecture.py, lib/spack/spack/test/concretize.py, lib/spack/spack/test/modules/lmod.py
fixes #13361
fixes #13248
Based on manuals found [here](https://gcc.gnu.org/onlinedocs/) and assuming that new arch are not added during patch releases.
=> Fixed optimization flags support for old GCC versions

lib/spack/llnl/util/cpu/detect.py, lib/spack/spack/test/cmd/compiler_command.py, lib/spack/spack/test/llnl/util/cpu.py
fixes #13138
closes #13354
This PR ensures that on Darwin we always append `/sbin` and `/usr/sbin` to `PATH`, if they are not already present, when looking for `sysctl`.
=> Make sure we look into /sbin and /usr/sbin for sysctl

lib/spack/spack/environment.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/test/package_sanity.py, lib/spack/spack/test/util/environment.py, lib/spack/spack/util/environment.py, var/spack/repos/builtin.mock/packages/cmake-client/package.py
Fixes #12731 
This PR ensures that environment activation sets all environment variables set by the equivalent `module load` operations, except that the spec prefixes are "rebased" to the view associated with the environment.
Currently, Spack blindly adds paths relative to the environment view root to the user environment on activation. Issue #12731 points out ways in which this behavior is insufficient.
This PR changes that behavior to use the `setup_run_environment` logic for each package to augment the prefix inspections (as in Spack's modulefile generation logic) to ensure that all necessary variables are set to make use of the packages in the environment.
See #12731 for details on the previous problems in behavior.
This PR also updates the `ViewDescriptor` object in …
=> env activation: use package defined env setup methods

lib/spack/spack/binary_distribution.py, lib/spack/spack/cmd/release_jobs.py, lib/spack/spack/config.py, lib/spack/spack/environment.py, lib/spack/spack/filesystem_view.py, lib/spack/spack/hooks/yaml_version_check.py, lib/spack/spack/modules/common.py, lib/spack/spack/spec.py, lib/spack/spack/test/cmd/release_jobs.py, lib/spack/spack/test/concretize_preferences.py, lib/spack/spack/test/config.py, lib/spack/spack/test/spack_yaml.py, lib/spack/spack/util/spack_yaml.py
Closes https://github.com/spack/spack/pull/10651 (This is an alternative to #10651 but attempts to confer the comment-preserving behavior of ruamel to the objects returned by spack_yaml when parsing yaml)
This updates the configuration loading/dumping logic (now called load_config/dump_config) in spack_yaml to preserve comments (by using ruamel.yaml's RoundTripLoader). This has two effects:
* environment spack.yaml files expect to retain comments, which load_config now supports. By using load_config, users can now use the ':' override syntax that was previously unavailable for environment configs (but was available for other config files).
* config files now retain user comments by default (although in cases where Spack updates/overwrites config, the comments can still be removed). …
=> Preserve comments for Spack yaml objects

var/spack/repos/builtin/packages/glib/package.py
python~pythoncmd does not provide a python symlink for python3, so make sure we pick the right command.
Fixes #12418
=> glib: Use correct python command

var/spack/repos/builtin/packages/bracken/package.py
python~pythoncmd does not provide a python symlink for python3, so make sure we pick the right command.
=> bracken: Use correct python command

var/spack/repos/builtin/packages/magics/package.py
Another python command fix (untested).
python~pythoncmd does not provide a python symlink for python3, so make sure we pick the right command.
=> magics: Use correct python path

var/spack/repos/builtin/packages/py-codecov/package.py
=> Add py-codecov package

var/spack/repos/builtin/packages/bison/package.py
It seems that 3.4.2 includes a change that is supposed to fix parallel builds (https://lists.gnu.org/archive/html/bug-bison/2019-08/msg00000.html). Instead, it actually breaks it for me (with -j48) with errors such as:
```
mv: cannot stat 'examples/c/reccalc/scan.stamp.tmp': No such file or directory
Makefile:9323: recipe for target 'examples/c/reccalc/scan.stamp' failed
```
=> bison: Fix build

var/spack/repos/builtin/packages/py-traceback2/package.py
=> py-traceback2: fix dependencies

var/spack/repos/builtin/packages/py-argparse/package.py
This dependency version requirement should not be explicit.
=> py-argparse: remove Python dependency version

lib/spack/spack/cmd/url.py
Previously this command only showed total counts for each regular expression.  This doesn't give you a sense of which regexes are working well and which ones are not.  We now display the number of right, wrong, and total URL parses per regex.
It's easier to see where we might improve the URL parsing with this change.
Let's see how triggered @adamjstewart is by these results -- there are some pretty unproductive regexes in here.
```
(spackbook):spack$ spack url summary
==> Generating a summary of URL parsing in Spack...
Total URLs found:          3477
Names correctly parsed:    3045/3477 (87.58%)
Versions correctly parsed: 3159/3477 (90.85%)
==> Statistics on name regular expressions:
Index   Right   Wrong   Total   Regular Expression
0     664     112     776 …
```
=> url summary: show right and wrong parse counts for each regex

var/spack/repos/builtin/packages/mysql/package.py
Found this due to #12418. It is the same change as in #13392 but I have not tested it.
python~pythoncmd does not provide a python symlink for python3, so make sure we pick the right command.
=> mysql: Use correct python command

etc/spack/defaults/config.yaml, lib/spack/docs/config_yaml.rst, lib/spack/env/cc, lib/spack/spack/build_environment.py, lib/spack/spack/compiler.py, lib/spack/spack/compilers/nag.py, lib/spack/spack/schema/config.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/cc.py
fixes #9160 
fixes #909 
fixes #639
This PR adds a new entry in `config.yaml`:
```yaml
config:
shared_linking: 'rpath'
```
If this variable is set to `rpath` (the default) Spack will set RPATH in ELF binaries. If set to `runpath` it will set RUNPATH.
=> Users can decide whether to set RPATH or RUNPATH

lib/spack/spack/util/spack_yaml.py
Properties read from configuration and applied to specs may not be represented after af65146. This registers the special configuration types as represent-able in `syaml.dump`, thereby enabling core functions like `dag_hash` to proceed as normal for properties read from configuration.
At a lower level: syaml.dump now allows representing all syaml_ objects (in af65146 this was only available for syaml.dump_config).
=> Fix Spec.dag_hash for properties read from config

var/spack/repos/builtin/packages/bison/package.py, var/spack/repos/builtin/packages/bison/parallel.patch
Turns out a patch for #13231 has been available in the bison mailing list archives. I did a few test builds and the patch seems to fix the problem for me. I am not sure whether the added dependencies make it worth it, though (most of them are already required by bison anyway). @adamjstewart
I will send feedback to the developers to make sure it gets included in the next release.
=> bison: Fix parallel build

lib/spack/spack/util/web.py
Fixes #13404
fd58c98 formats the `Stage`'s `archive_path` in `Stage.archive` (as part of `web.push_to_url`). This is not needed and if the formatted differs from the original path (for example if the archive file name contains a URL query suffix), then the copy fails.
This removes the formatting that occurs in `web.push_to_url`. Admittedly the archive path chosen by the stage should strip off strings like `?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Flibuuid%2F&ts=1433881396&use_mirror=iweb` from `libuuid-1.0.3.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Flibuuid%2F&ts=1433881396&use_mirror=iweb`, but that should be handled when the archive names are chosen (i.e. in `Stage.expected_archive_files`).
See also: https://github.com/spack/spack/pull/11117#discussion_r338301058
=> Don't format local path when caching a local archive

lib/spack/spack/cmd/build.py, lib/spack/spack/cmd/configure.py, lib/spack/spack/cmd/dev_build.py, lib/spack/spack/cmd/diy.py, lib/spack/spack/cmd/install.py, lib/spack/spack/test/cmd/dev_build.py, var/spack/repos/builtin.mock/packages/dev-build-test-install/package.py
Fixes #3642.
We've decided to rename the `spack diy` command to `spack dev-build` to make the use case clearer.
The `spack diy` command has some useful functionality for developers using Spack to build their dependencies and configure/build/install the code they are developing. We've realized that as this becomes a developer tool, the name `spack diy` is less useful. Hence the rename.
The `spack dev-build` command has a `-u/--until PHASE` option to stop after a given phase of the build. This can be used to configure your project, run cmake on your project, or similarly stop after any stage of the build the user wants. These options are analogous to the existing `spack configure` and `spack build` commands, but for developer builds. To unify the syntax, we have deprecated the `spack …
=> deprecate spack diy in favor of spack dev-build

lib/spack/spack/build_systems/autotools.py
If libtool does not have values for linker/pic flags, patch them in.
Caused by older versions of config.guess.
Akin to `sed` commands seen here: https://developer.arm.com/tools-and-software/server-and-hpc/arm-architecture-tools/resources/porting-and-tuning/building-hdf5-with-arm-compiler
=> Patch libtool when using the Arm compiler

lib/spack/spack/database.py
I forgot to bump the database format version when I added the `spack deprecate` command, which included a change to the database format.
After discussion with @scheibelp and @tgamblin we also changed to an integer database format version (instead of tracking the Spack version).
=> database: update database format version

var/spack/repos/builtin/packages/hpx/package.py
* Add version to build master branch
* Add option to disable examples
* Add MPI option
* Remove `cxxstd=98` option (not supported)
Question: is it possible to specify already in the `variant('mpi', ...)` call that this option requires `networking` to be on? Is the way I check for both `+networking` and `+mpi` when appending CMake options the most idiomatic way to do this?
=> Extend HPX package

var/spack/repos/builtin/packages/python/package.py
Currently, the python `add_files_to_view` method attempts to get the real path from the prefix to a file using `os.path.realpath`. However, that only works if the prefix itself is not under a symlink. If the prefix itself is under a symlink, the entire `merge_map` is created relative to that link.
By computing `os.path.realpath` of both the file and the python prefix, we can use `os.path.relpath` to compute the real relative path from the python prefix to the file, and prepend that with the python prefix to get the value we should expect in our `merge_map`.
Tested with `python@3.7` in a stack with a managed view. Spack could not link Python into the view without this change, and now can.
=> Views: fix python in views when python prefix is under a symlink

lib/spack/spack/cmd/spec.py, lib/spack/spack/test/cmd/spec.py
We've had `spack spec --yaml` for a while, and we've had methods for JSON for a while as well.  We just haven't has a `--json` argument for `spack spec`.
=> commands: Add `--json` argument to `spack spec`

lib/spack/spack/fetch_strategy.py, lib/spack/spack/package.py, lib/spack/spack/test/install.py
Fixes #13148 
Previously, spack would error out if we tried to fetch something with no code, but that would prevent fetching dependencies. In particular, this would fail:
spack fetch --dependencies xsdk
to be fetched for packages like xsdk that do not have code.
=> bugfix: allow fetching no-code packages

var/spack/repos/builtin/packages/py-gensim/package.py
depends on `py-smart-open` in #13135
=> py-gensim: new package at 3.8.0

lib/spack/spack/database.py, lib/spack/spack/test/database.py
Supersedes #13364 
A merge created a semantic error for managing upstream DB locks: upstream DBs are not supposed to be locked at all but the `ForbiddenLock` object used to manage this was overwritten.
Additionally, an upstream db test was calling methods on upstream DBs that should only be called on the local DB (which knows how when to lock and when not to). This updates the test to avoid that, and also adds a regression test to make sure that writing to upstream DBs leads to an exception.
=> Restore upstream lock safety, avoid calling methods directly on upstream DB in test

var/spack/repos/builtin/packages/py-readme-renderer/package.py
=> Add latest version of py-readme-renderer

var/spack/repos/builtin/packages/py-requests-toolbelt/package.py
=> Add latest version of py-requests-toolbelt

var/spack/repos/builtin/packages/py-tqdm/package.py
=> Add latest version of py-tqdm

var/spack/repos/builtin/packages/py-pkginfo/package.py
=> Add py-pkginfo package

var/spack/repos/builtin/packages/py-twine/package.py
=> Add py-twine package

var/spack/repos/builtin/packages/py-fiscalyear/package.py
Successfully installs on macOS 10.15 with Clang 11.0.0 and Python 3.7.4.
Shameless plug for some cool software I wrote!
=> Add latest version of py-fiscalyear

var/spack/repos/builtin/packages/mpich/package.py
Set include and library path to slurm explicitly.
Reported in https://github.com/spack/spack/pull/13259#issuecomment-543805366 by @jrood-nrel 
- ~~Does this need an upstream bug report in https://github.com/pmodels/mpich or is this just the way it works?~~ Looks legit to me.
=> MPICH: Fix Slurm Find Issue

var/spack/repos/builtin/packages/py-torch/package.py
When building PyTorch 1.3.0, it emits the following warning message:
```
WARNING: USE_GLOO_IBVERBS is deprecated. Use USE_IBVERBS instead.
```
=> Update PyTorch variable name

var/spack/repos/builtin/packages/llvm/package.py
Follow-up to #13047 @kljohann pointed out that my previous improvement was due to an old version being the head of someone's private fork and provided a link to the official documentation. Using that link here rather than the old one.
=> LLVM code-signing on OSX: link to the offical documentation

var/spack/repos/builtin/packages/beast1/package.py, var/spack/repos/builtin/packages/libbeagle/package.py
This PR fixes a couple of issues with the libbeagle package.
- Use args.append('--with-cuda=%s' % self.spec['cuda'].prefix)
- Disable the default of compiling with -march=native as Spack now
inserts architecture specific flags
- Set BEAST_LIB in the beast1 package not in libbeagle.
=> Libbeagle fixes

var/spack/repos/builtin/packages/c-blosc2/package.py, var/spack/repos/builtin/packages/lizard/fix-install-decompress.patch, var/spack/repos/builtin/packages/lizard/package.py
Add a new package for Lizard, formerly LZ5, a very fast compressor and decompressor library.
https://github.com/inikep/lizard
With the new package, use an external Lizard (LZ5) dependency and add missing "when="s for other compressor dependants.
=> Add Lizard (LZ5)

var/spack/repos/builtin/packages/quantum-espresso/package.py
@adamjstewart 
Excising convoluted brittle code that was frequently breaking.
The filter_file HDF5 hack was unfortunately going off the rails even though it previously seemed to work. HDF5 detection is working robustly in QE 6.4.1, but only with MPI enabled. HDF5 detection is still having problems with the serial QE. I am working with the QE developers to get it fixed in the native configure, so we don't have to run these filter_files. Less headache for the people who maintain this package.
=> QE Update Oct 2019

var/spack/repos/builtin/packages/perl-dbfile/package.py
Resolve two issues for the building of `perl-dbfile`:
1) add package dependence on `berkeley-db`
2) fix the building using a patch, which locates the position of `berkeley-db` and modify the configuration file for the building
=> Add dependency and patch for perl-dbfile

var/spack/repos/builtin/packages/py-torch/package.py
With this patch, PyTorch 1.3.0 successfully locates the Intel MKL libraries.
=> Fix PyTorch build with Intel MKL

var/spack/repos/builtin/packages/go/package.py
Added Go versions 1.13.2 and 1.12.11, release today (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/golang-announce/lVEm7llp0w0)
=> Added go 1.13.2 and 1.12.11

var/spack/repos/builtin/packages/gcc/package.py
+ It appears that macOS related changes to the gcc recipe (PR #13202) broke gcc on RHEL7.  This bug manifests as `libstdc++.so: undefined reference to libiconv` when gcc is used.
+ Fixes #13452 by moving `--with-libiconv-prefix={0}'.format(spec['libiconv'].prefix)` into the darwin OS section of the configuration.
+ Also fixes #13391
+ Needs to be tested on macOS and other Linux flavors.
=> Fix gcc recipe for RHEL7.

lib/spack/spack/cmd/flake8.py, lib/spack/spack/test/cmd/flake8.py
A developer should be able to use the `-d` option when running spack tests but the `test_changed_files` test has been failing with `spack: error: unrecognized arguments: -d` (for me) if it is used.  
You can quickly reproduce the issue by entering `spack -d test -k test_changed_files`.
This PR changes the offending test case so it uses only the flake8 defaults (rather than picking up arguments from the spack command line).
=> bugfix/tests: ensure `test_changed_files` uses only flake8 defaults

var/spack/repos/builtin/packages/cp2k/package.py
The json-support is now completely internal to the sirius dependency and the sirius support was only in the git-version of CP2K.
=> CP2K: drop json-fortran dependency and add support for the Nvidia V100

var/spack/repos/builtin/packages/mumps/package.py
Fujitsu Fortran compiler requires using `MAIN__()`  instead of `main()` in C program. C programs in `MUMPS` use `MAIN__` when `MAIN_COMP` is defined, so I added Fujitsu compiler to the judgment conditions.
=> mumps: Add '-DMAIN_COMP' when using Fujitsu compiler.

var/spack/repos/builtin/packages/r-spam/package.py
depends on `r-dotcall64` added in #13493
=> r-spam: new package at 2.3-0.2

var/spack/repos/builtin/packages/mumps/package.py
The original commands may not be executed depending on the environment, so it was modified to use the compile command names that Spack has.
=> mumps: Fix compile commands.

var/spack/repos/builtin/packages/openmpi/package.py
The wrappers fail to automatically link libfabric. This will cause undefined references unless we add the appropriate flags. This is the error prior to this fix:
```console
$ /usr/WS2/lee218/delete/spack-ulna-openmpi/opt/spack/linux-rhel7-aarch64/gcc-8.3.1/openmpi-3.1.4-6tvlgmme5jbfubi3bkoet3cbnujx6ckw/bin/mpicc hello.c 
/usr/WS2/lee218/delete/spack-ulna-openmpi/opt/spack/linux-rhel7-aarch64/gcc-8.3.1/openmpi-3.1.4-6tvlgmme5jbfubi3bkoet3cbnujx6ckw/lib/libmpi.so: undefined reference to `fi_dupinfo@FABRIC_1.2'
/usr/WS2/lee218/delete/spack-ulna-openmpi/opt/spack/linux-rhel7-aarch64/gcc-8.3.1/openmpi-3.1.4-6tvlgmme5jbfubi3bkoet3cbnujx6ckw/lib/libmpi.so: undefined reference to `fi_getinfo@FABRIC_1.2'
/usr/WS2/lee218/delete/spack-ulna-openmpi/opt/spack/linux-rhel7-aarch64/gcc-8.3.1/openmpi-3.1.4 …
```
=> fix openmpi wrappers with libfabric

lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/test/architecture.py
The `x86_64` target for clang currently provides architecture flags `-march=x86_64 -mcpu=generic`. The `-mcpu=generic` flag is ignored by clang (and seems to be a mistaken copy/paste from GCC.
This PR removes that flag.
=> cpu: fix clang flags for generic x86_64

lib/spack/spack/database.py
Currently, query arguments in the Spack core are documented on the `Database._query` method, where the functionality is defined.
For users of the `spack python` command, this makes the python builtin method `help` less than ideally useful, as `help(spack.store.db.query)` and `help(spack.store.db.query_local)` do not show relevant information.
This PR updates the __doc__ attributes for the `Database.query` and `Database.query_local` arguments to mirror everything after the first line of the `Database._query` docstring.
=> Database.query methods share docstrings

var/spack/repos/builtin/packages/ipopt/ipopt_aarch64_build.patch, var/spack/repos/builtin/packages/ipopt/package.py
`Ipopt/config.guess` does not recognize `aarch64` architecture, so I added condition to recognize  'aarch64' to `Ipopt/config.guess`.
=> ipopt: Add condition for 'aarch64' to Ipopt/config.guess

var/spack/repos/builtin/packages/pgmath/package.py
@alalazo @gklimowicz
Bump PGMathLibrary up to latest version. More transparent naming, version name equals branch name.
=> PGMathLibrary Oct 2019 Update

.travis.yml, lib/spack/docs/getting_started.rst, lib/spack/spack/cmd/flake8.py, lib/spack/spack/cmd/list.py
This PR adds Python 3.8 to our list of tested versions on Travis CI. It also fixes several bugs with our Python 3.8 support
=> Travis CI: Test Python 3.8

lib/spack/docs/requirements.txt
@alalazo @tgamblin thoughts on this PR? I just successfully built the docs with the latest version of all of these dependencies. I don't recall why we locked the versions in the first place (maybe because they started dropping Python 2.6 support), but now that we build with Python 3, we should make sure the latest version of these packages still works.
Alternatively, I can update the versions to the current releases I've tested if we want things to be more stable.
=> Docs: unlock requirement versions

lib/spack/spack/fetch_strategy.py
4af4487 added a `mirror_id` function to most `FetchStrategy` implementations that is used to calculate resource locations in mirrors. It left out `BundleFetchStrategy` which broke all packages making use of `BundlePackage` (e.g. `xsdk`). This adds a noop implementation of `mirror_id` to `BundleFetchStrategy` so that the download/installation of `BundlePackage`s can proceed as normal.
=> Bugfix: BundlePackages failing to download/install on account of missing API

var/spack/repos/builtin/packages/openmpi/package.py
```
dantopa@cn733:pr-openmpi-4.0.2.spack $ spack arch
linux-centos7-skylake_avx512
$ spack install openmpi @ 4.0.2 % gcc @ 4.8.5
...
==> Installing openmpi
...
==> Successfully installed openmpi
Fetch: 2m 15.65s.  Build: 6m 13.17s.  Total: 8m 28.82s.
[+] /scratch/users/dantopa/new-spack/pr-openmpi-4.0.2.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.0.2-jrypg7vfnk6nl5if2rnzt65wdrjelxsq
```
```
$ spack arch
linux-centos7-nehalem
$ spack install openmpi @ 4.0.2 % gcc @ 4.8.5
...
==> Installing openmpi
...
==> Successfully installed openmpi
Fetch: 50.48s.  Build: 9m 11.45s.  Total: 10m 1.93s.
[+] /scratch/users/dantopa/new-spack/pr-openmpi-4.0.2.spack/opt/spack/linux-centos7-nehalem/gcc-4.8.5/openmpi-4.0.2-4jz3bcwjci44taizt4jqzxqh4y75uswc
```
```
$ spack arch
linux-rhel7-aarch64
$ …
```
=> Add Open MPI v. 4.0.2

var/spack/repos/builtin/packages/trilinos/package.py
Trilinos install fails when trying to build against the latest version of netcdf (@4.7.2) -- it appears unable to find certain netcdf header files in the expected locations. This PR would temporarily constrain trilinos to use netcdf@:4.7.1 until the issue can be resolved. @becker33
=> trilinos: temporarily pin to ^netcdf@:4.7.1 until build issues resolved with newer versions

lib/spack/spack/concretize.py, lib/spack/spack/test/concretize.py
fixes #13482 
Whenever the default compiler is too old to build for the current host, Spack prints a warning message to make the user aware of the downgrading.
=> Spack prints a warning message before downgrading targets

lib/spack/spack/cmd/__init__.py, lib/spack/spack/test/cmd/common/arguments.py
=> Specs with quoted flags containing spaces are parsed correctly

lib/spack/spack/test/util/util_url.py, lib/spack/spack/util/url.py, lib/spack/spack/util/web.py
Needed to resolve #13474.
Other fixes might be necessary.
=> fix issue where spack.util.url.join() failed to correctly handle absolute path components

lib/spack/spack/relocate.py, lib/spack/spack/test/relocate.py
Currently, even if you have patchelf in your binary cache, you cannot use it, because we try to install it to relocate the patchelf binary.
This patch notices if we're trying to use patchelf on patchelf itself, and lets us use it to relocate it 
(Note, you have to make a copy of the binary to actually  patch it to avoid a busy file error).
This lets you 
spack buildcache install patchelf
before buildcache installing anything else, and do all buildcache installs from the bottom up.
=> allow bootstrap buildcache install of patchelf

var/spack/repos/builtin/packages/py-tables/package.py
3.6.0 is no longer available for download on PyPI. Apparently the `setup.py` was missing `python_requires`, causing it to be pulled in by Python 2 users: https://github.com/PyTables/PyTables/issues/772
Successfully installs on Cray CNL5 with GCC 5.3.0 and Python 3.7.4.
=> Add py-tables 3.6.1

lib/spack/spack/environment.py, lib/spack/spack/test/cmd/env.py
I inadvertently reverted my changes from #12719 in #13249. This reinstates the functionality from #12719.
=> environments: make shell modifications partially unconditional

lib/spack/spack/mirror.py
Fixes: https://github.com/spack/spack/issues/13541
Construct MirrorCollection with OrderedDict to preserve order from config
@opadron 
(EDIT: added explanation) it turns out this wasn't a configuration loading issue: after the config is loaded, the MirrorCollection object constructs a `dict` with the entries (and Python's `dict` doesn't guarantee ordering).
=> Bugfix: preserve mirror order

var/spack/repos/builtin/packages/py-torch/package.py, var/spack/repos/builtin/packages/qnnpack/package.py
Successfully installs on macOS 10.15.1 with Clang 11.0.0.
Still haven't found a way to use dependencies instead of resources: https://github.com/pytorch/QNNPACK/issues/68
Is there an easier way to find the directory containing a resource? Then I won't have to mess with destination/placement.
=> Add QNNPACK package

var/spack/repos/builtin/packages/llvm/package.py
This PR applies constexpr_longdouble.patch to LLVM versions 6.x as well.  I've demonstrated successful patching and building with 6.0.0 and 6.0.1.
=> constexpr_longdouble.patch should be applied to v6 too

var/spack/repos/builtin/packages/vtk/package.py
Fixes two issues:
1. OpenGL2 dependency needs libxt, since CMake searches for X11_Xt_LIB
2. Same issue like #7145, same solution like #7404
=> Added dependencies

var/spack/repos/builtin/packages/py-deprecation/package.py, var/spack/repos/builtin/packages/py-semver/package.py, var/spack/repos/builtin/packages/py-wradlib/package.py, var/spack/repos/builtin/packages/py-xarray/package.py, var/spack/repos/builtin/packages/py-xmltodict/package.py
wradlib is an open source library for weather radar data processing (e.g. RADOLAN). Changes include new versions for xarray as well as new packages, on which py-wradlib depends:
- py-deprecation (provides a deprecated decorator and a fail_if_not_removed decorator)
- py-semver (semantic versioning, simplifies comparing versions)
- py-xmltodict (working with XML feel like you are working with JSON)
=> New package py-wradlib with new dependencies

lib/spack/spack/cmd/release_jobs.py, lib/spack/spack/environment.py, lib/spack/spack/schema/env.py, lib/spack/spack/test/cmd/env.py
Fixes #12313
This fixes a known bug that Spack adds keys to the environment yaml for everything left empty, filling in the default values.
Will edit with issue # of the issue this fixes once I find it.
=> environments: only write when necessary

lib/spack/spack/fetch_strategy.py, lib/spack/spack/stage.py, lib/spack/spack/util/web.py
Also updates the S3FetchStrategy so that it throws a SpackError if the fetch fails.  Before, it was throwing URLError, which was not being caught in stage.py. (This uncaught exception is what had originally confused me and led to my erroneous changes in `stage.py`.)
Fixes #13537
=> Fix issue where fetch failed to prefer local mirrors over public remote resources

var/spack/repos/builtin/packages/py-pybind11/package.py
Successfully builds on Cray CNL5 with GCC 5.3.0.
@ax3l
=> Add latest version of py-pybind11

var/spack/repos/builtin/packages/flux-core/package.py, var/spack/repos/builtin/packages/flux-sched/package.py
Support flux-core versions v0.11.1 to v0.11.3 (and associated flux-sched versions).  
Encode the C4 repo model in the `url_for_version` function to support future patch release (and minor versions once it passes v1.0).
=> Flux v0.11.1 - v0.11.3

var/spack/repos/builtin/packages/py-astor/package.py
=> py-astor: specify py-setuptools versions as build fail with latest version

var/spack/repos/builtin/packages/acts-core/package.py
Just a new [uneventful release](https://gitlab.cern.ch/acts/acts-core/-/tags/v0.10.05) of the ACTS package.
=> Add ACTS v0.10.5

lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/find.py, lib/spack/spack/test/cmd/env.py
If you do this in a spack environment:
spack add hdf5+hl
hdf5+hl will be the root added to the `spack.yaml` file, and you should really expect `hdf5+hl` to display as a root in the environment.
Before:
```console
$ spack add hdf5+hl
$ spack find
==> In environment myproject2
==> Root specs
hdf5
==> 0 installed packages
```
After:
```console
$ spack add hdf5+hl
$ spack find
==> In environment myproject2
==> Root specs
hdf5 +hl
==> 0 installed packages
```
=> `spack find` now displays variants and other spec constraints

lib/spack/spack/environment.py
This fixes a regression introduced in #10792.  `spack uninstall` in an
environment would not match concrete query specs properly after the index
hash of enviroments changed.
=> bugfix: uninstall should find concrete specs by DAG hash

var/spack/repos/builtin/packages/relion/package.py
Note, 3.0.7 removed as it contains bugs.  3.0.8 latest stable version in 3.0 branch.  I added 3.1_beta which isn't yet stable so we are still preferring 3.0.
3.0.8 will compile with latest cmake / gcc so remove that constraint.
=> added relion 3.0.8 [latest stable version in 3.0 branch] as well as 3.1_beta

lib/spack/spack/cmd/create.py
During the last round of package adding, @adamjstewart repeatedly reminded me to also track the python version compatibilities, so I ended up making spack show me that in the stub rather than adding it manually each time
=> add depends_on(python) to PythonPackage stub

var/spack/repos/builtin/packages/py-torch/package.py
Successfully builds on Cray CNL5 with GCC 5.3.0 and CUDA 9.
Without these changes, PyTorch tried to use vendored third party dependencies for all of these packages. There are still several other vendored deps I would like to remove in the future, but this is a step in the right direction.
I also needed the following patch to build on Blue Waters:
```diff
diff --git a/c10/util/Half.h b/c10/util/Half.h
index 338f271627..1e4a2e7be1 100644
--- a/c10/util/Half.h
+++ b/c10/util/Half.h
@@ -31,6 +31,7 @@
#include <limits>
#include <sstream>
#include <stdexcept>
+#include <stdint-gcc.h>
#include <string>
#include <utility>
diff --git a/c10/util/llvmMathExtras.h b/c10/util/llvmMathExtras.h
index 76ae3b26a2..a1422faf5d 100644
--- a/c10/util/llvmMathExtras.h
+++ b/c10/util/llvmMathExtras.h
@@ -19,6 …
```
=> PyTorch: avoid use of third party vendored deps

var/spack/repos/builtin/packages/py-mpi4py/package.py
mpi4py 3.0.3 adds support for Python 3.8 with new Cython files.
https://bitbucket.org/mpi4py/mpi4py/src/3.0.3/CHANGES.rst
I tried to build 3.0.0 with Python 3.8 and this builds as well, therefor I added no conflict.
=> mpi4py 3.0.3

var/spack/repos/builtin/packages/py-pybind11/package.py
Helper for non-CMake downstream projects to find the pybind11 header location.
Patch the right location of our install prefix in.
Fix #13559
=> pybind11: correct get_include path

var/spack/repos/builtin/packages/cdo/package.py
netcdf has been renamed to netcdf-c and udunits2 has been renamed to udunits.
=> cdo: Fix with_or_without calls

var/spack/repos/builtin/packages/m4/package.py
Patch was not being applied in recent versions of macOS. Homebrew is still applying patch to any version after High Sierra.
=> m4: fixed macOS version identification on patch

var/spack/repos/builtin/packages/arrow/package.py, var/spack/repos/builtin/packages/py-pyarrow/package.py
~~This doesn't currently work, as the `build_directory` setting is required for the apache downloads but doesn't work for the github ones~~
edit: ended up adding only 0.15.1 to py-pyarrow as pypi has sources for this only
=> (py)arrow: new versions

var/spack/repos/builtin/packages/py-pyside/package.py
This fix already exists in the development branch of _pyside_. See https://github.com/pyside/pyside-setup/pull/55.
=> py-pyside: fix setup files to support python 3.5.

lib/spack/spack/mirror.py, lib/spack/spack/test/mirror.py
Fixes a second error mentioned by @zzotta in https://github.com/spack/spack/issues/13474#issuecomment-550281560.
`mirror_archive_path` was failing to acccount for the case where the fetched versions isn't known to Spack.
=> bugfix: mirror path works for nonexisting versions

var/spack/repos/builtin/packages/acts-core/package.py, var/spack/repos/builtin/packages/py-jaraco-functools/package.py
second order dependency for cherrypy web framework/tempora
=> New package:  py-jaraco-functools

var/spack/repos/builtin/packages/llvm/llvm_py37.patch, var/spack/repos/builtin/packages/llvm/package.py
This PR applies a patch to llvm versions 4.x - 6.x that got applied in the master at version 7.  This fixes issues when the underlying python support is the same or newer than 3.7 to reflect the return value change in PyUnicode_AsUTF8AndSize.
=> llvm: fix PythonString::GetString for >=python-3.7

var/spack/repos/builtin/packages/precice/package.py
This PR adds conflicting compilers versions (pre C++11, no N2071/N2072) as explicit conflicts to the package.
This change is related to xSDK.
=> precice: add compiler conflicts

var/spack/repos/builtin/packages/fluxbox/fix_zero_comparison.patch, var/spack/repos/builtin/packages/fluxbox/package.py
Modifications to eliminate errors caused by zero comparision.
Reference: https://sourceforge.net/p/fluxbox/bugs/1171/
=> fluxbox: fix the comparison method with zero.

var/spack/repos/builtin/packages/acts-core/package.py, var/spack/repos/builtin/packages/py-zc-buildout/package.py
System for managing development buildouts -- dependency of cherrypy framework
=> new package: py-zc-buildout

var/spack/repos/builtin/packages/openfoam/package.py
- patched versions are located in the same directory as the
original release. For example, 1906_191103 is located in
the 'v1906/' directory, not in 'v1906_191103/'.
- add master branch as a known version
=> update openfoam versions, sha256 values and download directory

var/spack/repos/builtin/packages/py-pyside2/package.py
https://wiki.qt.io/Qt_for_Python
The Qt for Python project aims to provide a complete port of the PySide module to Qt 5. The development started on GitHub in May 2015. The project managed to port Pyside to Qt 5.3, 5.4 & 5.5. During April 2016 The Qt Company decided to properly support the port.
=> New Package: py-pyside2

lib/spack/spack/cmd/checksum.py, lib/spack/spack/stage.py
Very minor change.
```console
$ spack checksum mpich
==> Found 35 versions of mpich:
3.3.1   http://www.mpich.org/static/downloads/3.3.1/mpich-3.3.1.tar.gz
3.3rc1  http://www.mpich.org/static/downloads/3.3rc1/mpich-3.3rc1.tar.gz
3.3b3   http://www.mpich.org/static/downloads/3.3b3/mpich-3.3b3.tar.gz
3.3b2   http://www.mpich.org/static/downloads/3.3b2/mpich-3.3b2.tar.gz
3.3b1   http://www.mpich.org/static/downloads/3.3b1/mpich-3.3b1.tar.gz
3.3a3   http://www.mpich.org/static/downloads/3.3a3/mpich-3.3a3.tar.gz
3.3a2   http://www.mpich.org/static/downloads/3.3a2/mpich-3.3a2.tar.gz
3.3a1   http://www.mpich.org/static/downloads/3.3a1/mpich-3.3a1.tar.gz
3.3     http://www.mpich.org/static/downloads/3.3/mpich-3.3.tar.gz
...
3.0     http://www.mpich.org/static/downloads/3.0/mpich-3.0.tar.gz
==> …
```
=> Improve spack checksum formatting

var/spack/repos/builtin/packages/cmake/package.py
Successfully builds on macOS 10.15.1 with Clang 11.0.0.
@chuckatkins
=> Add CMake 3.13.5

var/spack/repos/builtin/packages/pmdk/package.py
Update logic that checks for x86_64 architectures in the pmdk package.
=> fix x86_64 arch check in pmdk package

var/spack/repos/builtin/packages/py-scikit-learn/package.py
Switching to `self.compiler.openmp_flag` now that #12049 has been merged.
=> py-scikit-learn: update OpenMP flag

var/spack/repos/builtin/packages/intel-mkl-dnn/package.py, var/spack/repos/builtin/packages/py-torch/package.py
Successfully installs and passes all unit tests on macOS 10.15.1 with Clang 11.0.0.
Ran into a few bugs I'm still trying to resolve:
* https://github.com/intel/mkl-dnn/issues/591
* https://github.com/spack/spack/pull/13656#issuecomment-552273278
=> Add new version of Intel MKL-DNN

var/spack/repos/builtin/packages/cudnn/package.py
Also changes version names to more easily choose corresponding CUDA version.
Also adds macOS versions.
=> cuDNN: add new versions

var/spack/repos/builtin/packages/sirius/package.py
- depends on spfft starting from 6.4.0
- add magma variant
- avoid setting cuda_arch to none
- add python dependencies
- use release as default build type
=> SIRIUS: add new version, etc.

lib/spack/spack/verify.py
This PR adds exception handling around the `os.stat()` call during manifest creation so that installation of packages can run to completion should the package itself insert bogus files (e.g. a dangling symlink) into its install directory.  Without this patch, if any package so misbehaves, the `post_install()` section fails like this (even if the package itself successfully builds!):
```
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/usr/projects/packages/user_contrib/spack/opt/spack/linux-centos7-sandybridge/gcc-9.2.0/trilinos-12.12.1-wi5tyjl6gogocxjy4nvbv6nme7drcpzs/lib/cmake/tribits/doc/developers_guide/TribitsBuildReference.html'
/usr/projects/packages/user_contrib/spack/lib/spack/spack/package.py:1718, in build_process:
1715                    echo = logger.echo …
```
=> verify.py: os.path.exists exception handling

var/spack/repos/builtin/packages/precice/package.py
This PR changes preCICE to enable PETSc by default.
This has been extensively tested by @balay.
=> preCICE: Enable PETSc by default

var/spack/repos/builtin/packages/nlopt/package.py
Prepend PYTHONPATH with NLopt's Python directory when built with +python option. This allows nlopt to be imported in Python.
=> Update nlopt package to add Python bindings to PYTHONPATH

var/spack/repos/builtin/packages/damselfly/package.py
I got the following error when installing `damselfly`.
```
35    mpicxx   -I/tmp/~/spack-stage-da
mselfly-1.0-2ag34mthvthcixrhtvt3djsp6o64jj2p/spack-build  -O2 -g -DN
DEBUG   -o CMakeFiles/damselfly.dir/src/ariesModeling.C.o -c /tmp/~
~/spack-stage-damselfly-1.0-2ag34mthvthcixrhtvt3djsp6o64jj2p/
spack-src/src/ariesModeling.C
36    make[2]: mpicxx: Command not found 
```
It means that `damselfly` needs mpi library, so I added `mpi` dependency.
=> damselfly: Add mpi dependency.

var/spack/repos/builtin/packages/flex/package.py
Flex would not build in `registry.access.redhat.com/ubi8/ubi-minimal` b/c the image did not come with `diff` and `find` in system paths.
=> Add missing dependencies to flex.

lib/spack/docs/conf.py
See also https://github.com/spack/spack-tutorial/pull/10.
=> docs: use nicer looking code blocks in docs

var/spack/repos/builtin/packages/strumpack/package.py
[i.e behavior before this variant was added] as +shared fails on multiple builds
cc: @pghysels
=> strumpack: revert default to ~shared

var/spack/repos/builtin/packages/root/package.py
`depends_on('libxml2~python', when='~python')` -> `depends_on('libxml2', when='~python')` per https://github.com/spack/spack/issues/13637#issuecomment-552026561.
=> root: relax libxml2 requirements when ~python.

lib/spack/docs/packaging_guide.rst
=> Docs update for deprecated `spack sha256`

lib/spack/spack/binary_distribution.py, lib/spack/spack/relocate.py
Binaries with relative RPATHS currently do not relocate strings hard-coded in binaries
This PR extends the best-effort relocation of strings hard-coded in binaries to those whose RPATHs have been relativized.
A separate PR will be made to the develop branch
=> Allow binary relocation of strings in relative binaries

var/spack/repos/builtin/packages/file/package.py, var/spack/repos/builtin/packages/gmake/package.py, var/spack/repos/builtin/packages/grep/package.py, var/spack/repos/builtin/packages/gzip/package.py, var/spack/repos/builtin/packages/vim/package.py, var/spack/repos/builtin/packages/which/package.py
Installing `vim` in `registry.access.redhat.com/ubi8/ubi-minimal` container had configure error because the image did not have `file`.
**Edit: Added GNU `which` and `grep`
=> Added "file" package and added missing depenency to VIM

lib/spack/spack/relocate.py
@becker33 
Something I missed when reviewing https://github.com/spack/spack/pull/10073
`relocate.make_link_relative` was resolving a path relative to a complete file path when in fact `os.path.relpath` expects a directory. The result was that the relative path was always "off" by one directory in the sense that it always added an extra initial `../` to the path.
This determines the link target relative path relative to the link directory rather than relative to the full link path (which includes the file name).
=> Binary packaging: correct relative symlinks

var/spack/repos/builtin/packages/libbsd/local-elf.h.patch, var/spack/repos/builtin/packages/libbsd/package.py
Libbsd assumes GCC-defined compiler macros:
```
In file included from nlist.c(44):
local-elf.h(238): catastrophic error: #error directive: Unknown ELF machine type
#error Unknown ELF machine type
^
```
The `__amd64__` and `__x86_64__` macros should be equivalent, but the latter is defined by intel.
=> Fix libbsd build on Intel compilers

var/spack/repos/builtin/packages/geopm/package.py
Added changes for 1.1.0 and 1.0.0 in this patch.
Patch for 1.0.0 was previously not merged.
Variant for hwloc removed since that is not a dependency since 0.5.1 and
variant('hwloc', when="@:0.5.1"... is not supported afaik.
Made depends_on versions more explicit.
New pull request as recommended in #11230
=> package/geopm: Added versions 1.0.0 and 1.1.0

var/spack/repos/builtin/packages/dmtcp/package.py
Updated DMTCP package to v2.6.0, released August 2019.
=> Update DMTCP package to v2.6.0

var/spack/repos/builtin/packages/py-enum34/package.py, var/spack/repos/builtin/packages/py-matplotlib/package.py, var/spack/repos/builtin/packages/py-multiqc/package.py
This implements @scheibelp's suggestion in #13711.
py-matplotlib should only depends_on py-backports-functools-lru-cache
when it's using a python that actually *needs* it.
See #13711 for details.
Fixes #13711
=> py-matplotlib only needs backports when ^python@:2

var/spack/repos/builtin/packages/bison/package.py, var/spack/repos/builtin/packages/cmake/package.py, var/spack/repos/builtin/packages/icu4c/package.py, var/spack/repos/builtin/packages/nasm/package.py
I recently had to build out a compiler toolchain using Intel 14.0.4, which supports *most* but *not all* of C++11 and C11 features. I found the oldest Spack-defined versions of each package that failed Intel 14 and marked as conflicts the newer versions with Intel 14 and before.
For posterity, here is what I successfully installed:
```
-- linux-rhel6-x86_64 / intel@14.0.4 ----------------------------
autoconf@2.69
automake@1.16.1
bison@3.0.5
bzip2@1.0.8+shared
cmake@3.12.4~doc+ncurses+openssl+ownlibs patches=93488edf3f89cef6f3c77e821007c022e88e9f1f566ae9bf824a87ecbac97ebb,dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt
diffutils@3.7
expat@2.2.9+libbsd
freetype@2.7.1
gdbm@1.18.1
gettext@0.20.1+bzip2+curses+git~libunistring+libxml2+tar+xz
glib@2.56.3~libmount …
```
=> Mark conflicts between newer packages and Intel 14 compilers

etc/spack/defaults/config.yaml, lib/spack/spack/binary_distribution.py, lib/spack/spack/schema/config.py, lib/spack/spack/util/gpg.py
We currently print quite verbose gpg output when installing binary packages
This gives users an option (default remains the same) to suppress that output.
=> Config option to allow gpg warning suppression

var/spack/repos/builtin/packages/hwloc/package.py
Backport of #13731 to the release branch
=> hwloc: added 'master' version pointing at the HEAD of the master branch

var/spack/repos/builtin/packages/revbayes/package.py
The GCC version conflict has been resolved in newer versions as the build process specifies the C++ it needs rather than relying on the compiler default.
The MPI build is done in a different folder on development, and the executable name produced was different in 1.0.12 and 1.0.13 than before and in the current development branch.
=> revbayes: add new versions

var/spack/repos/builtin/packages/guile/package.py
Currently, guile by default tries to compile its thread variant.
However, the threaded version can only be compiled if bdw-gc is
compiled with some threads support. Currently, the default
compilation of the bdw garbage collector is compiled without any
thread support resulting in a compilation error.
I have changed the default guile compilation to the non-threaded
version. I have also added the appropriated options for the bdw-gc
compilation in case the user prefers the threaded variant.
Without the changes this is the error message you get when installing guile:
```
'make' '-j36'
9 errors found in build log:
1602      SNARF  socket.doc
1603      SNARF  regex-posix.doc
1604      CCLD     libguile-2.2.la
1605 …
```
=> guile package: Handling the threads option.

var/spack/repos/builtin/packages/openpmd-api/package.py
Add latest release and first to be tagged by number in Spack, version 0.10.0.
=> openPMD-api: 0.10.0

var/spack/repos/builtin/packages/ascent/package.py, var/spack/repos/builtin/packages/conduit/package.py, var/spack/repos/builtin/packages/metis/package.py, var/spack/repos/builtin/packages/mfem/package.py, var/spack/repos/builtin/packages/vtk-h/package.py, var/spack/repos/builtin/packages/vtk-m/package.py
update ascent, vtk-h, and vtkm to new releases. 
changes zfp variant default for conduit to false
Also includes fixes to metis download and flags passed to the mfem for conduit
=> update to add ascent 0.5.0 release

var/spack/repos/builtin/packages/libxml2/package.py
libxml2 installation was failing with `curl: (52) Empty reply from server`
It seems that the HTTP server does not redirect (so -L option for curl cannot do anything) and the resource is only available at HTTPS url.
=> Fix libxml2 package download problem

var/spack/repos/builtin/packages/zlib/package.py
zlib was using the deprecated setup_environment call.  Now it's using
the current setup_build_environment.
(noticed this in some `spack -d` output)
=> zlib: use setup_build_environment for build env

var/spack/repos/builtin/packages/hpx/package.py
Expose HPX build option which is fundamental to fully exploit all resources available on platforms with more than 64 cores.
@msimberg can you check if it is ok for you or something is missing, please?
=> add MAX_CPU_COUNT variant to HPX package

var/spack/repos/builtin/packages/py-protobuf/package.py
=> Add old versions and missing dependencies to py-protobuf

var/spack/repos/builtin/packages/c-ares/package.py
This version fixes a bug on macOS where the library wasn't correctly RPATHed.
Successfully installs on macOS 10.15.1 with Clang 11.0.0.
=> Add c-ares 1.15.0

var/spack/repos/builtin/packages/py-grpcio/package.py
=> Add new py-grpcio package

var/spack/repos/builtin/packages/py-google-pasta/package.py
Split off of #13112 
Successfully installs and passes all unit tests on macOS 10.15.1 with Clang 11.0.0 and Python 3.7.4.
=> Add py-google-pasta package

var/spack/repos/builtin/packages/py-numexpr3/package.py
I corrected the version referring to the following.
https://pypi.org/project/numexpr3/
=> py-numexpr3: Fixed version

var/spack/repos/builtin/packages/valgrind/package.py
Fix for some overlong shebangs in valgrind. Borrowed from verrou/package.py
=> Fix for overlong shebang in valgrind

var/spack/repos/builtin/packages/bpp-suite/clarify_isinf.patch, var/spack/repos/builtin/packages/bpp-suite/package.py
Clarify `isinf`'s namespace, because Fujitsu compiler can't resolve ambiguous of `isinf` function.
Reference: https://github.com/BioPP/bppsuite/commit/7ef3885dc6b5d6fb18a76bbe775a884ef0e070b2#diff-3df4628f9113630d27f006a70615fd41
=> bpp-suite: Clarify 'isinf' function's namespace.

var/spack/repos/builtin/packages/texinfo/fix_unescaped_braces.patch, var/spack/repos/builtin/packages/texinfo/fix_unescaped_braces_2.patch, var/spack/repos/builtin/packages/texinfo/fix_unescaped_braces_3.patch, var/spack/repos/builtin/packages/texinfo/package.py, var/spack/repos/builtin/packages/texinfo/update_locale_handling.patch
* Fix unescaped braces in regexps.
Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898994
* Apply this fix to perform thread-safe processing in code that uses the global locale.
Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902771
=> texinfo: fix unescaped braces, and update locale handling

var/spack/repos/builtin/packages/cbtf-krell/package.py
The PR add dependency to rpcsvc-proto (for rpcgen command) and libtirpc (for rpc functions).
=> cbtf-krell: add rpcsvc-proto and libtirpc dependency.

var/spack/repos/builtin/packages/mg/package.py
TODO:
**Switched to using Package**.
---
Adds a package for the portable OpenBSD version of mg.  mg is a gnu-emacs-ified version of the micro-emacs editor.
Small, fast, quick-starting editor with gnu-emacs compat. key bindings.
=> Add mg, a gnu-emacs like fork of microemacs

.travis.yml
It's a couple of days that a lot of jobs are failing on Travis due to corrupted caches for source mirrors. This PR removes the source mirror from caches to work around this issue.
=> Remove mirrors from Travis cache

lib/spack/spack/cmd/install.py, share/spack/spack-completion.bash
Pretty straightforward. The option isn't actually hooked up to any functionality, and I'm not sure how it got into the `install` command.
Motivated by the error report on slack that confused it with the similarly named option for the `spack spec` command.
=> cmd/install: remove unused install_status option

var/spack/repos/builtin/packages/py-matplotlib/package.py
Just noticed that matplotlib's backend dependencies weren't being added during runtime.
=> py-matplotlib backend dependencies needed at runtime

var/spack/repos/builtin/packages/ack/package.py
This makes several installs from the same download cache impossible once
the hash of the used perl-install changes.
Fixes: #13824
=> ack: Fix install modifying download cache

var/spack/repos/builtin/packages/acts-core/package.py
Yet another [largely uneventful ACTS release](https://gitlab.cern.ch/acts/acts-core/-/tags/v0.11.00), at least from a build system point of view.
I also figured out how to add myself as a maintainer, as was suggested during a previous last round of updates.
=> ACTS v0.11.0 + adding myself as maintainer

var/spack/repos/builtin/packages/py-qtpy/package.py
This change allows one to use qtpy with pyqt5, pyside and pyside2 by enabling the appropriate variant.
=> Update py-qtpy recipe

var/spack/repos/builtin/packages/cctools/cctools_6.1.1.python.patch, var/spack/repos/builtin/packages/cctools/cctools_7.0.18.python.patch, var/spack/repos/builtin/packages/cctools/package.py
cctools configure option is separated python2 and python3.
But package.py allows python3 and specfies as python2.
Also cctools use pydoc but pydoc version is mismatch to specify spack.
(If pydoc2 is existed in PATH, cctools is used pydoc2, but spack installed python2 is installed pydoc.)
* python option of configure is corrrect.
* In version 7.0.18, pydoc is used as dependent python.
* In version 6.1.1, use pydoc insted of pydoc2.
=> cctools: fix python related error.

var/spack/repos/builtin/packages/mapnik/package.py, var/spack/repos/builtin/packages/py-python-mapnik/package.py
without py-pycairo and cairo+pdf, `import mapnik.printing` yields runtime errors.
=> Mapnik: fix runtime error involving py-pycairo and PDF

var/spack/repos/builtin/packages/lm-sensors/package.py, var/spack/repos/builtin/packages/papi/package.py
This change provides a custom libs() in lm-sensors and implements use of this property in the papi package when configuring with the lmsensors variant.
=> Improved library access for lm-sensors and implemented use in papi.

lib/spack/docs/extensions.rst
Extensions have been available for a while and the overall design seems solid enough to be extended without losing backward compatibility.
=> Remove warning from the "Custom Extensions" section of the docs

var/spack/repos/builtin/packages/lsof/package.py
I got following error when installing `lsof`.
I changed the download url and I fixed the checksum because the checksum of version 4.89 has changed.
=> lsof: fix url and checksum

var/spack/repos/builtin/packages/vtk-m/package.py
During normal operation, vtkm is sending warnings to the terminal which are false positives and this is effecting the performance of dependent applications. This happens on every rank. Until this is resolved inside vtkm, suppress the logging output.
=> silence vtkm logging until it does not report false positives

var/spack/repos/builtin/packages/openmpi/fix-ucx-1.7.0-api-instability.patch, var/spack/repos/builtin/packages/openmpi/package.py
No tagged release of OpenMPI 4.0.x supports UCX 1.7. [OpenMPI devs blame UCX's unstable API](https://github.com/open-mpi/ompi/issues/7128). Unfortunately some software installs UCX 1.7, such as Mellanox OFED drivers. Why a major network driver distribution wasn't regression tested for compatibility with a flagship communication library remains a mystery.
=> Patch for OpenMPI 4.0.x + UCX 1.7

var/spack/repos/builtin/packages/ocaml/package.py
The download url of the ocaml package was invalid because the following error occurred.
The purpose is to convert the version `4.06.0` to `4.06` 
But, when using up_to, `4.06` was converted to `4.6`.
http://caml.inria.fr/pub/distrib/ocaml-4.6/ocaml-4.06.0.tar.gz
http://caml.inria.fr/pub/distrib/ocaml-4.06/ocaml-4.06.0.tar.gz
So I converted the string of version in the recipe without using up_to.
=> ocaml: Fix version conversion process

var/spack/repos/builtin/packages/mathematica/package.py
This pull request addresses the following issues.
- Licensing is currently missing from the recipe. Assuming that majority of the installations will be on clusters, information about the licence manager server would be required
- Replace url with url_for_version in case subsequent versions are added
- Create .spack dir during installation. This directory may not be created automatically causing installation failure when spack is trying to copy the log file there.
- Symlink wolframscript. Most people running mathematica in the cluster environment would be using wolframscript binary. However, the installer does not symlink it, so full path is required to run it.
- Generate spec.yaml. This file may not be created automatically causing package registration failure.
=> Update Mathematica recipe

var/spack/repos/builtin/packages/mpark-variant/nvcc.patch, var/spack/repos/builtin/packages/mpark-variant/package.py
Fix a (downstream) issue with NVCC when building with C++14.
Patch works with both tagged versions.
Ref.: https://github.com/mpark/variant/pull/71
=> MPark.Variant: Patch NVCC C++14 Build

lib/spack/spack/util/module_cmd.py
fixes a bug reported on slack.
`python -c` fails with lines delimited by newlines, but succeeds with lines delimited by semicolons.
This PR fixes Spack's `module` function to use semicolons instead of newlines.
=> module_cmd: use semicolons instead of newlines python command

var/spack/repos/builtin/packages/intel-tbb/package.py
Clang builds incorrectly determine GCC version which in turn incorrectly causes a mismatch in C++ features resulting in a link error. This also means that clang builds require a gcc compiler to work correctly (this has always been the case). See https://github.com/intel/tbb/pull/147 for details.
=> Add version check when building intel-tbb with clang

var/spack/repos/builtin/packages/acts-core/package.py
Probably our [simplest bugfix release](https://gitlab.cern.ch/acts/acts-core/-/tags/v0.11.01) ever ;)
=> Package the ACTS v0.11.1 bugfix

var/spack/repos/builtin/packages/py-line-profiler/package.py
Because `@run_after` and `@when` are incompatible (issue #12736), we got
the following error when installing `py-line-profiler` with `python@2.7.16`.
```
/opt/spack/lib/spack/spack/package.py:1718, in build_process:
1715                    echo = logger.echo
1716                    self.log()
1717
>>   1718                # Run post install hooks before build stage is removed.
1719                spack.hooks.post_install(self.spec)
1720
1721            # Stop timer.
NoSuchMethodError: Package PyLineProfiler does not support fix_cython called with py-line-profiler@2.1.2 [...] ^python@2.7.16 [...]
```
=> Fix py-line-profiler incompatible decorators

var/spack/repos/builtin/packages/intel-mkl/package.py, var/spack/repos/builtin/packages/intel-mpi/package.py, var/spack/repos/builtin/packages/intel-parallel-studio/package.py, var/spack/repos/builtin/packages/intel/package.py
Bump intel, intel-mkl, intel-mpi, intel-parallel-studio to the latest version 2019u5 which is released on Sep 2019. All these packages have been installed successfully and `spack install tara %intel@19.0.5` works.
=> Bump intel compiler suite to 2019u5.

var/spack/repos/builtin/packages/accfft/fix_narrowing_error.patch, var/spack/repos/builtin/packages/accfft/package.py
Bugfix about 'narrowing error'.
```
error: non-constant-expression cannot be narrowed from type 'int' to 'size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
```
=> accfft: fix narrowing error.

var/spack/repos/builtin/packages/json-fortran/package.py
Successfully builds and passes all unit tests on macOS 10.15.1 with Clang 11.0.0 and GFortran.
=> json-fortran: get unit tests working

var/spack/repos/builtin/packages/openmpi/package.py
Note to spack people: these are expected to be end of line releases for both the 3.1.x and 3.0.x release streams.
=> openmpi: add 3.1.5 and 3.0.5

var/spack/repos/builtin/packages/cuda/package.py
As discussed in #13827, this PR adds the multi-package version hack to `cuda`.
Closes #13827
=> cuda: add polymorphic package versions

var/spack/repos/builtin/packages/r/package.py
The documentation states that Spack builds R without the recommmened
packages, with Spack handling the build of those packages to satisfy
dependencies. From the docs:
> Spack explicitly adds the --without-recommended-packages flag to
> prevent the installation of these packages. Due to the way Spack
> handles package activation (symlinking packages to the R installation
> directory), pre-existing recommended packages will cause conflicts for
> already-existing files. We could either not include these recommended
> packages in Spack and require them to be installed through
> --with-recommended-packages, or we could not install them with R and
> let users choose the version of the package they want to install. We
> chose the latter.
However, this is not what Spack is actually doing. The …
=> Build R without recommended packages

var/spack/repos/builtin/packages/boost/package.py
* the spack `cxxstd` variant is not sufficient to enforce
`-std=c++11` usage in boost compile lines when `xl_r` compiler
spec is in use; while it would be nice if this were fixed
in a boost config file somewhere, for now this patch
allows boost to build on POWER9 with
an %xl_r compiler spec if the user specifies i.e.,:
`spack install boost@1.70.0+mpi cxxstd=11 %xl_r@16.1.1.5`
Related:
- #11849
- https://lists.boost.org/boost-users/2019/09/89953.php
=> BLD: enforce C++11 std for boost + xl_r

var/spack/repos/builtin/packages/py-backports-shutil-get-terminal-size/package.py
The bug seems to be fixed at least in setuptools 41.0.0
=> Loosen restriction on setuptools version of py-backports-shutil-get-terminal-size

var/spack/repos/builtin/packages/perl/package.py
Fixes https://github.com/spack/spack/issues/13792
Fixes #13930 
https://github.com/spack/spack/commit/99dfff447509a68d672a82812e5abfbc463b6d26 updated `perl` to add `perl`'s `bin/` directory to `PATH` but does not filter it when it is a system path. This removes that logic from the `perl` package because adding `bin` for a given package is already handled in Spack core (and it includes filtering logic for system dirs)
=> Handle external perl

lib/spack/spack/test/util/executable.py
The unicode script written by `test_read_unicode()` can fail the shebang character limit with some development environments. Use `filter_shebangs_in_directory()` to guard against this.
=> Armor test script against shebang character limit if appropriate.

var/spack/repos/builtin/packages/cbtf/package.py
The PR add dependency to rpcsvc-proto (for rpcgen command) and libtirpc  (for rpc functions).
=> cbtf: add rpcsvc-proto and libtirpc dependency.

var/spack/repos/builtin/packages/dealii/package.py
TBB is an optional dependency of deal.II, used by the library to parallelize some operations with threads. If the cmake flag DEAL_II_WITH_THREADS (default: ON) is set to OFF, deal.II does not require TBB anymore. This pull request adds a variant 'threads' to the deal.II package with the same default behavior (+threads), which controls the TBB dependency.
The motivation for this pull request is that there is currently a bug in the Intel compiler (icpc version 19.0.3.199 (gcc version 8.3.0 compatibility)), that makes it impossible to compile deal.II with thread support enabled (a reference to one of the headers in TBB fires a "bad pointer" internal error in icpc). So without this variant, I could not build deal.II.
=> dealii: Added 'threads' variant that controls the TBB dependency

.gitattributes
Add a line to .gitattributes so that `git grep -p` shows function names properly for `*.py` files.  Without this, the class name is shown instead of the function for python files.
This also causes diff output to use proper functions as hunk headers in `diff` output.
Here's an example with `git grep -p`.
```console
$ git grep -p spack_cc var/spack/repos/builtin/packages/athena
var/spack/repos/builtin/packages/athena/package.py=class Athena(AutotoolsPackage):
var/spack/repos/builtin/packages/athena/package.py:            env.set('CC', spack_cc)
var/spack/repos/builtin/packages/athena/package.py:            env.set('LDR', spack_cc)
```
vs.
```console
$ git grep -p spack_cc var/spack/repos/builtin/packages/athena
var/spack/repos/builtin/packages/athena/package.py=    def …
```
=> git: add .gitattributes file

lib/spack/spack/__init__.py
We forgot to bump the version when we released 1.13.1. We need a documented (or automated) process for releasing new versions that includes bumping the version number.
=> Version bump: 1.13.1

var/spack/repos/builtin/packages/qt/package.py
Fix an issue where the latest openssl is desired for multiple packages for the openspeedshop qt3 build, but the qt build wants to use an older version of openssl.  There does not appear to be any side effects for the openspeedshop gui when using the latest openssl, so making the change to resolve the conflict.
=> Fix conflict with respect to openssl and qt3 built for openspeedshop.

var/spack/repos/builtin/packages/amber/package.py, var/spack/repos/builtin/packages/dealii/package.py
- Added amber 18 with ambertools 19
- Added all available patches
- Added +update variant to use the self update
- Added +openmp variant to get openmp optomizations
- Added +x11 variant when possible
- Splitted amber 16 and 18 dependencies
- We now detect the copiler type and compile accordingly
- Added cray variant which is a bit special (untested)
- Improved detection of possible cuda versions
- All compilation optimizations +mpi +openmp +cuda are compatible
- Updated to use setup_build_environment(), setup_run_environment()
=> amber: Improved package.py and added version 18

var/spack/repos/builtin/packages/superlu-dist/package.py
Ran into a problem compiling Superlu-dist because metis and parmetis was built in a different directories.  Adding metis's include directory solved this problem.
=> Add missing metis include to superlu-dist

var/spack/repos/builtin/packages/gawk/package.py, var/spack/repos/builtin/packages/libgpg-error/awk-5.patch, var/spack/repos/builtin/packages/libgpg-error/package.py
- awk is a build depdency for this package
There is an [issue](https://dev.gnupg.org/rE7865041c77f4f7005282f10f9b6666b19072fbdf) with libgpg-error and gawk >= 5.0 which will be fixed in any release version of libgpg-error (it's the third commit on their master branch after the release tag 1.36). Therefore there should be a requirement in the sense of 
depends_on('awk@:4, when='@:1.36', type='build')
depends_on('awk@4:, when='@1.37:', type='build')
But since awk is a virtual dependency this would not work I assume? Shall I leave it as it is or specify this version constraint for each awk provider?
=> Update package libgpg error

var/spack/repos/builtin/packages/mrbayes/package.py
* Updated MrBayes to release version 3.2.7a (latest).
* Fixed incorrect MPI configure argument.
* Added several new configure arguments as variants.
Thanks.
=> Update MrBayes to 3.2.7a and correct MPI variants

var/spack/repos/builtin/packages/cantera/package.py
For a successful cantera installation, googletest has to be installed with gmock on, and sundials has to be of version less than 3.2
=> fix_cantera_installation

var/spack/repos/builtin/packages/argobots/package.py
Commit 71cd91e4 changed "latest from git" to 'master' from former
'develop'.  Build dependencies still pointed to @develop, though
=> argobots: consistently use 'master'

var/spack/repos/builtin/packages/mpich/package.py
To build from git, MPICH will need newer autoconf, automake, and libtool than
typically available on many systems.
=> mpich: update build requirements

var/spack/repos/builtin/packages/sz/package.py
I am releasing v2.1.8.0 for SZ, also modifying package.py by adding maintainer and parallel=False.
I ran 'spack test' but failed. However, it seems that failure has nothing to do with my modification. I just modified sz/package.py. The failures are 'test_url_parse', 'test_url_local_file_path', 'test_url_join_local_paths'.
=> Release a new version v2.1.8.0 for SZ

var/spack/repos/builtin/packages/intel-tbb/package.py
Update to #13893. Use correct range check for the version. This has been tested with gcc for 2019.5-2019.8 and with clang for 2019.7-2019.8. Once #13913 is merged, this will build cleanly.
Ping @mwkrentel
=> intel-tbb: Fix version check for clang builds

lib/spack/llnl/util/cpu/microarchitectures.json, lib/spack/spack/test/architecture.py, lib/spack/spack/test/llnl/util/cpu.py
Before the flags used where the one for llc, the underlying compiler from LLVM IR to machine assembly. It turns out that the semantic of `-march`, `-mtune` and `-mcpu` changes from clang front-end to llc.
I found no definitive reference for the flags submitted in this PR, but I checked the assembly on a vectorizable function using [Godbolt's web-site](https://godbolt.org/z/S9yFwU).
Refers to the discussion in https://github.com/spack/spack/pull/13825#discussion_r351107265 (thanks @t-karatsu !)
=> Fixed x86-64 optimization flags for clang

lib/spack/spack/test/util/util_url.py
Fixes bug in unit tests reported by @disheng222 in #13974.
=> Fix spack test when SPACK_ROOT isn't set

var/spack/repos/builtin/packages/cuda/package.py
Keep CUDA 10.1.243 as the preferred version until the issue of including implementation details of libcu++ is addressed: #13969 #13819
Related: #13991
=> CUDA: Keep 10.1.243 As Preferred

lib/spack/spack/spec.py, lib/spack/spack/test/patch.py, lib/spack/spack/test/versions.py, var/spack/repos/builtin.mock/packages/patch/biz.patch, var/spack/repos/builtin.mock/packages/patch/package.py
Fixes https://github.com/spack/spack/issues/13961
Apply strict constraint checks for patches, otherwise Spack may incorrectly treat a version range constraint as satisfied when mixing x.y and x.y.z versions.
See also: https://github.com/spack/spack/issues/8957#issuecomment-560613454
=> Patching: do strict version range checking

var/spack/repos/builtin/packages/py-cheroot/package.py, var/spack/repos/builtin/packages/swipl/package.py
This pull request contains a new package, that sets up the SWI-Prolog interpreter. Since some dependencies are optional, I added variants that control whether Spack should try installing them.
I am not a member of the SWIPL development team, just a user of the program. The configuration scripts are based on the following two documentation pages:
https://www.swi-prolog.org/build/unix.html
https://github.com/SWI-Prolog/swipl-devel/blob/master/CMAKE.md
I could build and install with GCC and all variants enabled, as well as all variants disabled. Compilation of the interpreter with ICC was also successful, but when building the core database, the interpreter failed with a segmentation fault (so it could not be installed with ICC). I am not sure whether that is a problem of the setup of our …
=> New package: swipl

var/spack/repos/builtin/packages/py-pillow/package.py
Support for python 3.4 wasn't dropped until Pillow 6.x.
Related to #13985
=> py-pillow: allow older versions to build with python 3.4

var/spack/repos/builtin/packages/paraview/package.py
- py-matplotlib: No constraint necessary for py3 but py2 has an upper bound
- py-numpy: No constraint necessary for py3 but py2 has an upper bound
Related to #13985
=> paraview: Adjust python version constraints

lib/spack/spack/reporters/cdash.py
Hopefully fixes this issue I just ran into where installing with cdash reporting arguments resulted in:
```
File "/data/scott/Documents/spack/single_repo_testing/spack/bin/spack", line 64, in <module>
File "/data/scott/Documents/spack/single_repo_testing/spack/lib/spack/spack/main.py", line 713, in main
return _invoke_command(command, parser, args, unknown)
File "/data/scott/Documents/spack/single_repo_testing/spack/lib/spack/spack/main.py", line 456, in _invoke_command
return_val = command(parser, args)
File "/data/scott/Documents/spack/single_repo_testing/spack/lib/spack/spack/cmd/install.py", line 335, in install
install_spec(args, kwargs, abstract, concrete)
File "/data/scott/Documents/spack/single_repo_testing/spack/lib/sp …
```
=> cdash: fix reporting issue with python 3

lib/spack/docs/build_systems.rst, lib/spack/docs/build_systems/bundlepackage.rst
Added a basic ``build_systems`` page for the ``BundlePackage``.
=> docs: Minimal BundlePackage build system doc

var/spack/repos/builtin/packages/py-h5sh/package.py
Adds a command-line tool for interacting with an HDF5 file as though it is a shell. Much more suitable for analysis of large HDF5 files compared to `h5ls`/`h5dump`
=> Add h5sh python package

var/spack/repos/builtin/packages/flang/package.py, var/spack/repos/builtin/packages/llvm/constexpr_longdouble.patch, var/spack/repos/builtin/packages/llvm/llvm_gcc7.patch, var/spack/repos/builtin/packages/llvm/llvm_py37.patch, var/spack/repos/builtin/packages/llvm/package.py
This change updates the llvm Spackage to use the monorepo at https://github.com/llvm/llvm-project.  This will be the primary code repository moving forward for the llvm-project.  In this repo all projects are side by side in a single tarball and projects are enabled with `-DLLVM_ENABLE_PROJECTS`.
To enable flang in this structure, the flang fork of clang and llvm will need to replace the llvm and clang directories.  This is what I am doing below, but it requires a change allowing resources in Spack to overwrite a location.
Someone more familiar with flang could likely make a cleaner mapping from the flang forks to the monorepo releases.
=> Convert llvm Spackage to use the monorepo

var/spack/repos/builtin/packages/lua/package.py
I noticed this when deploying software with the 0.13.2 release:
```
==> Installing lua-luaposix
==> Searching for binary cache of lua-luaposix
==> Warning: No Spack mirrors are currently configured
==> No binary for lua-luaposix found: installing from source
==> Error: NameError: name '_setup_dependent_env_helper' is not defined
/opt/spack/var/spack/repos/builtin/packages/lua/package.py:121, in setup_dependent_build_environment:
120    def setup_dependent_build_environment(self, env, dependent_spec):
>>    121        lua_patterns, lua_cpatterns = _setup_dependent_env_helper(
122            self, env, dependent_spec)
123
124        env.set('LUA_PATH', ';'.join(lua_patterns), separator=';')
```
I've included a fix that worked in my case but it could very well be something I simply …
=> Specify self for lua internal setup method

var/spack/repos/builtin/packages/sz/fix_optimization.patch, var/spack/repos/builtin/packages/sz/package.py
Part of latest sources couldn't execute to optimize `-O3` with Fujitsu compiler.
I'll lower optimize level to `-O2` only for Fujitsu compiler.
References for similar bugs:
https://github.com/HexHive/CFIXX/issues/6
Real error log:
```
libtool: compile:  /～/spack/lib/spack/env/fj/fcc -DHAVE_CONFIG_H -I. -I.. -I./ -I./compress -I./common -I./deprecated -I./dictBuilder -I./legacy -O3 -std=c99 -Wall -MT ./legacy/libzstd_la-zstd_v02.lo -MD -MP -MF ./legacy/.deps/libzstd_la-zstd_v02.Tpo -c ./legacy/zstd_v02.c  -fPIC -DPIC -o ./legacy/.libs/libzstd_la-zstd_v02.o
/～/lib64/libLLVMSupport.so.6(_ZN4ll
vm3sys15PrintStackTraceERNS_11raw_ostreamE+0x28)[0xffff9fd20888]
Stack dump:
0.      Program arguments: ～
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass …
```
=> sz: Change optimization flags for Fujitsu compiler

var/spack/repos/builtin/packages/ceed/package.py
I'm working on "build system" documentation for BundlePackage and noticed I could not build this package because it does not have a version.
This commit adds an initial version entry (the latest per the web site) to allow it to be built.
=> Ceed: Added required version

var/spack/repos/builtin/packages/fastmath/package.py
I'm working on "build system" documentation for ``BundlePackage`` and noticed I could not build this package because it does not have a version.
This commit adds a version placeholder and tweaks the URL (since the redirect caused problems for me) .
=> Fastmath: Added required version

var/spack/repos/builtin/packages/augustus/package.py
* `augustus` always uses only gnu compiler, so I fixed makefiles to use compile commands of specified compiler on Spack.
* Fix to use `boost` installed by Spack.
=> augustus: Set compile commands for each compiler and Fix for using 'boost' on Spack

lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/find.py, lib/spack/spack/test/cmd/find.py
Fixes #13971
Fixes #9875 (thanks @abernede and @nazavode for pointing that out).
Solution: force spack find -p to print abstract specs without prefixes
Spack was trying to print the prefix of an abstract spec, which causes an attribute error (or moral equivalent).
=> Bugfix: spack find -p fails in environment

lib/spack/spack/cmd/create.py
Noticed the docs --and ``spack create -h``-- were showing a format option instead of the template choices so this change fixes (or should) this problem.
UPDATE:  Changed to only alphabetize the options given #14014 fix.
=> docs: Alphabetize create cmd template options

var/spack/repos/builtin/packages/mesquite/package.py
Allows for the mesquite package to be built without mpi.
The --with-mpi option was always passed to the configure, it is now dependent on whether the mpi variant was chosen or not.
=> mesquite: fix build of the no mpi variant.

var/spack/repos/builtin/packages/py-theano/package.py
`py-nose-parameterized` was renamed to `py-parameterized`. Not sure which version of `py-theano` reflects this change, only looked at the latest version.
=> Update py-theano dependencies

var/spack/repos/builtin/packages/py-parameterized/package.py
=> Add py-parameterized package

var/spack/repos/builtin/packages/ibm-java/package.py
Add version 8.0.6.0 and remove 8.0.5.30.  IBM is fairly aggressive
about removing old versions, and 8.0.5.30 is no longer available from
their download site.
----------
I looked around IBM's download site a bit, but I couldn't find an
archive directory for 8.0.5.30 or other old versions.
http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/
If someone can find where old versions are archived, then let me know
and we can set `list_url`.
=> ibm-java: add version 8.0.6.0

lib/spack/llnl/util/filesystem.py, lib/spack/spack/test/build_environment.py, var/spack/repos/builtin/packages/cuda/package.py
Avoid matching recurringly nested include paths that most certainly refer to internally shipped libraries in packages.
Example in CUDA Toolkit #13819 #13983, shipping a libc++ fork internally with libcu++ since 10.2.89: `<prefix>/include/cuda/std/detail/libcxx/include`.
Quick fix #13969 
A more thorough solution is not to recursively search for headers anymore since this is against the idea of C/C++ facade headers: https://github.com/spack/spack/issues/13969#issuecomment-561929481 Unfortunately, it's not that easy for us to find which headers are facade and which ones are detail, but I am not sure we have to know anything besides the include dir locations.
Generally, just searching for *any* `include/` in the overall path (instead of just taking the `<prefix>/include`) is dangerous as …
=> Spec Header Dirs: Only first include/

var/spack/repos/builtin/packages/py-importlib-metadata/package.py
Successfully installs and passes all unit tests on macOS 10.15.1 with Clang 11.0.0 and Python 3.7.4.
=> Add latest version of py-importlib-metadata

var/spack/repos/builtin/packages/py-tox/package.py
=> Add py-tox package

var/spack/repos/builtin/packages/py-extras/package.py
=> Add new py-extras package

var/spack/repos/builtin/packages/py-fixtures/package.py
=> Add new py-fixtures package

var/spack/repos/builtin/packages/py-hacking/package.py
=> Add new py-hacking package

var/spack/repos/builtin/packages/feh/package.py, var/spack/repos/builtin/packages/imlib2/package.py, var/spack/repos/builtin/packages/libexif/package.py, var/spack/repos/builtin/packages/libid3tag/10_utf16.diff, var/spack/repos/builtin/packages/libid3tag/11_unknown_encoding.dif, var/spack/repos/builtin/packages/libid3tag/CVE-2008-2109.patch, var/spack/repos/builtin/packages/libid3tag/libid3tag-gperf.patch, var/spack/repos/builtin/packages/libid3tag/package.py
* **Name**: feh
* **Description**: feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
* **imlib2**: Library that does image file loading and saving as well as rendering, manipulation, arbitrary polygon support
* **libexif**: A library to parse an EXIF file and read the data from those tags
* **libid3tag**: library for id3 tagging
---
If need be I can resubmit this as 4 separate Pull Requests but as the 3 extra packages are just to support the topic of this PR (feh), I decided to submit one request that includes all 4 packages.
=> Add New package feh and supporting packages

var/spack/repos/builtin/packages/py-python-subunit/package.py
=> Add new py-python-subunit package

var/spack/repos/builtin/packages/py-testtools/package.py
=> Add new py-testtools package

var/spack/repos/builtin/packages/py-testscenarios/package.py
=> Add new py-testscenarios package

var/spack/repos/builtin/packages/py-testresources/package.py
=> Add new py-testresources package

var/spack/repos/builtin/packages/py-testrepository/package.py
=> Add new py-testrepository package

var/spack/repos/builtin/packages/py-stestr/package.py
=> Add new py-stestr package

var/spack/repos/builtin/packages/py-jupyter/package.py
=> Add py-jupyter package

var/spack/repos/builtin/packages/py-brian2/package.py
=> py-brian2: py-nosetests -> py-nose

var/spack/repos/builtin/packages/py-asserts/package.py
=> Add new py-asserts package

var/spack/repos/builtin/packages/py-h5glance/package.py, var/spack/repos/builtin/packages/py-htmlgen/package.py
=> py-python-htmlgen -> py-htmlgen

var/spack/repos/builtin/packages/py-sphinxcontrib-issuetracker/package.py
=> Add new py-sphinxcontrib-issuetracker package

var/spack/repos/builtin/packages/py-pytest-mypy/package.py
=> Add new py-pytest-mypy package
