spack/spack

var/spack/repos/builtin/packages/py-requests-mock/package.py

Add new py-requests-mock package

---

var/spack/repos/builtin/packages/r-condop/package.py

@tgamblin This is the package I was talking about that depends on `r-rminer`. To the best of my knowledge, this is now the slowest concretizing package in Spack. On my laptop:
```console
$ time spack spec r-condop
...
real	1m19.250s
user	1m8.797s
sys	0m4.655s
```
In comparison:
```console
$ time spack spec r-rminer
...
real	1m9.245s
user	0m59.829s
sys	0m4.205s
```
I imagine that the new concretizer will be much more efficient with these R packages. The main reason they take so long to concretize is that R itself has a whopping 58 dependencies! Since `r-condop` has another 107 R packages that it depends on, you end up with 6,000+ dependencies in the full DAG, mostly duplicates.

Add new r-condop package

---

lib/spack/docs/contribution_guide.rst

edit: grammar
I have, more than once, tried to install the list of things that ~need~ are needed to build the docs, only to discover that the list doesn't use Spack's package names.  I'm tired of facepalming....  This commit touches up the prose so that it actually includes a command that one can use to install the things.
While I was there I touched up the prose about activating the new Python packages; activating a python package doesn't add anything to your PYTHONPATH, it links things into a directory that's *already* on your PYTHONPATH.  Note that this all presupposes that you're using that same python....
What's the issue label for nitpicky-changes?

Tuneup docs re setting up sphinx for building docs

---

lib/spack/spack/fetch_strategy.py

Dear Spack developers,
this is just a small fix which enables sources with ftp:// urls to be downloaded. I hope that it helps.
Kind regards,
Andras

Apply URLFetchStrategy to ftp:// and ftps:// url schemes

---

var/spack/repos/builtin/packages/vtk-m/package.py

This fixes an incorrect entry in the gpu architecture map that caused code to fail on summit.

fix incorrect gpu arch map for vtk-m package

---

lib/spack/spack/environment.py
lib/spack/spack/test/cmd/env.py

@sethrj requested the ability to add virtual packages to environments using `spack add`.
This PR allows virtual packages to be added to the `specs` list using the `add` command.
Virtual packages are already allowed in named lists in spack environments/stacks.
Virtual packages are already allowed in the `specs` list when added using the yaml directly.

environments: allow 'add' command to add virtuals

---

var/spack/repos/builtin/packages/intel-tbb/package.py

Recent commit e9ee9eaf (#13989) fixed testing version ranges inside
patch when clauses.  Previously, it was necessary to write all revs
individually for packages with multiple length version numbers (2019
and 2019.1).
This fixes the build for the old 2017.* versions.
----------
Thanks to @adamjstewart for issue #8957.
Thanks to @scheibelp for patch #13989.
At this point, it's possible to write the version ranges sensibly,
and all of the old revs should build cleanly.

intel-tbb: fix and cleanup patch version ranges

---

var/spack/repos/builtin/packages/openfoam-org/package.py

This pull request adds openfoam-org versions 6 and 7 and a variant +metis for linking metis.
The version number change from 5.0 to 6 and 7 is due to the change made by OpenFOAM developers on their repository naming convention.
The included patch contains changes made by [this commit](https://github.com/OpenFOAM/OpenFOAM-7/commit/ef33cf38ac9b811072a8970c71fbda35a90f6641). Without it the +int64 variant will not build correctly.

openfoam-org: Adding openfoam-org versions 6 and 7 and a metis variant.

---

lib/spack/spack/spec.py
lib/spack/spack/test/spec_semantics.py
lib/spack/spack/variant.py

fixes #13124
The current error message for `accfft`:
```console
$ spack spec accfft
Input spec
accfft
Concretized
==> Error: trying to set variant "float" in package "fftw", but the package has no such variant [happened during concretization of accfft ^cmake ^fftw+double+float~mpi+openmp]
```

Better error message when setting unknown variants during concretization

---

lib/spack/spack/test/cmd/__init__.py
lib/spack/spack/test/cmd/env.py
lib/spack/spack/test/llnl/util/__init.py
lib/spack/spack/test/modules/__init__.py
lib/spack/spack/test/util/__init__.py

Currently, `cmd/resource.py` in `lib/spack/spack/test` conflicts with a file in `celery`, so users who use spack in a python virtualenv with `celery` installed will not be able to run `spack test`.
This is also just best practices. We had already added a `__init__.py` file for the top level testing directory, this covers all the subdirectories.

pytest: add __init__ files for all test subdirs

---

var/spack/repos/builtin/packages/diamond/fix_narrowing_error.patch
var/spack/repos/builtin/packages/diamond/package.py

・Fix about narrowing error
`error: constant expression evaluates to -3 which cannot be narrowed to type 'char' [-Wc++11-narrowing]`
　Ref:https://github.com/bbuchfink/diamond/commit/155e076d662b0e9268e2b00bef6d33d90aede7ff#diff-27acfe5422eb9cf2b8dd1a4cd11e17c3

 diamond: fix narrowing error.

---

var/spack/repos/builtin/packages/intel-xed/package.py

The xed CLI is handy, and can be gotten by building the examples in the
intel-xed package. This PR builds the examples and installs the xed CLI.
It would also be possible to install more of the example binaries if
someone thinks they are useful.

Build xed CLI for the intel-xed package

---

var/spack/repos/builtin/packages/doxygen/package.py

PR #10589 introduced a libiconv dependency to doxygen. This causes problems on Linux systems, since the iconv symbols are included in libc, which causes CMake to use the external header but not the external library. Work around this by always using the external libiconv.

doxygen: Fix libiconv checks

---

var/spack/repos/builtin/packages/python/package.py

Fixes an issue reported by @gartung on Slack:
> On a side note the python package defines several methods that call python. This breaks installing python packages built for macOS on a linux host because the python executable is a mach-o binary. This line is evaluated on python package install
https://github.com/spack/spack/blob/a288449f0b23acbec128bab943e42b403f4f4df9/var/spack/repos/builtin/packages/python/package.py#L562

Add try-except for Python installation

---

var/spack/repos/builtin/packages/augustus/package.py

PR #13975 added makefile filtering to replace gcc/g++ with the spack
compiler. This conflicts with other filtering that is done in the package to
add paths for dependencies. The text of the dependency paths might
have 'gcc' in the path name, depending on the install_path_scheme, and
that was being replaced by the new compiler filters. That would mangle
the path to the dependecy resulting in a failed build.
This PR moves the compiler filters to be before the other filters to
make sure that the compiler is set before the dependency paths.

Fix replacement of embedded 'gcc' in augustus

---

var/spack/repos/builtin/packages/cmake/package.py

https://github.com/spack/spack/pull/13796
I got ChecksumError when installing `cmake@3.15.5`. Checksum of new patch merged on this pull request seems to be different. I got correct checksum from following URL.
https://gitlab.kitware.com/cmake/cmake/merge_requests/4075

cmake: Fix checksum of 4075.patch

---

var/spack/repos/builtin/packages/python/package.py

It seems loadable extensions are already enabled by default in SQlite. Also enable this feature in python so that one can do
```python
import sqlite3
con = sqlite3.connect(":memory:")
con.enable_load_extension(True)
```
If not compiled with this option, the last line throws errors.
Refs:
- https://docs.python.org/3.8/library/sqlite3.html#f1
- https://www.sqlite.org/loadext.html
Note that footnotes in 1st Ref above doesn't apply here since spack compiles SQLite from scratch

package/Python: compile python with sqlite loadable extensions

---

lib/spack/spack/cmd/install.py
lib/spack/spack/test/cmd/install.py
share/spack/spack-completion.bash

Prevent `spack help install` from getting too cluttered with CDash-specific
documentation.

Split out CDash options to a separate help document

---

share/spack/docker/ubuntu-1604.dockerfile
share/spack/docker/ubuntu-1804.dockerfile

I've noticed that:
1. now spack chooses python3 by default, and 
2. one of the packages installed brings python3, but 
3. the boto3 module is not installed under python3, so that 
4. spack/ubuntu images no longer work for accessing S3 buckets
This change should make sure boto3 is installed under python3 as well as python, so that boto3 is available in either case.

docker: add `file`, adjust locale, and use python3 for ubuntu

---

var/spack/repos/builtin/packages/gmodel/fix_gmodel.cpp.patch
var/spack/repos/builtin/packages/gmodel/package.py

・I changed 0 to nullptr because I got following error when installing gmodel.
`error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]`
・I deleted function template because  I got following error when installing gmodel.
`error: unused function template 'size' [-Werror,-Wunused-template]`
・Ref: https://github.com/ibaned/gmodel/commit/6b81ec190cf2ce9a6554a99cb6d759b023393cdd

gmodel: Fix various errors during build

---

var/spack/repos/builtin/packages/oniguruma/package.py

Also defines `libs` property and adds post-installation tests.
Successfully installs and passes all tests on macOS 10.15.1 with Clang 11.0.0.

Add latest version of oniguruma

---

var/spack/repos/builtin/packages/py-boto3/package.py

Add latest version of py-boto3

---

var/spack/repos/builtin/packages/py-botocore/package.py

Add latest version of py-botocore

---

var/spack/repos/builtin/packages/py-ipaddress/package.py

Add latest version of py-ipaddress

---

var/spack/repos/builtin/packages/py-tabulate/package.py

Add latest version of py-tabulate

---

var/spack/repos/builtin/packages/aws-parallelcluster/package.py

Add new aws-parallelcluster package

---

var/spack/repos/builtin/packages/berkeley-db/package.py

The berkeley-db package normally fetches from the Gentoo repository because the Oracle website requires login. However the archives seem to have been removed from the Gentoo repository.
This PR comments the `url_for_version` function so that it reverts to downloading from Oracle. This will work for version 6.2.32 (the latest in this package) and 6.1.29, but not for older ones.
If anyone knows of another mirror from which more versions of BerkeleyDB can be downloaded, please update the package. At least with this PR the two latest versions are available again.
Fixes #14145

FIX: Making berkeley-db package fetch from correct links

---

var/spack/repos/builtin/packages/motif/add_xbitmaps_dependency.patch
var/spack/repos/builtin/packages/motif/package.py

Installing motif does not work, see the corresponding issue #14127 . The problem is that the upstream package does not expect header files from the `xbitmaps` package to appear in a different prefix than the other X11 libraries. I made a patch to correct for this, and force an autoreconf in the package.py script.
Additionally, I have found that autoreconf complains about missing AUTHORS and NEWS files in the source distribution. The same patch also adds dummy files to satisfy autoreconf.

Patch: explicitly use xbitmaps include dir in the automake package

---

var/spack/repos/builtin/packages/hpctoolkit/package.py

In preparation for an upcoming release, we moved around a few
branches, and eliminated 'master-gpu' and replaced it with 'gpu'.
(sorry)

hpctoolkit: update git branch for version 'gpu'

---

lib/spack/spack/test/packages.py
lib/spack/spack/util/package_hash.py
var/spack/repos/builtin.mock/packages/hash-test3/package.py

Closes #13620
Closes #13265
Fixes #13237
Spack computes a "full hash" of packages as part of identifying them when retrieving binary packages for installation. The full hash includes a content hash that attempts to traverse the AST of a `package.py` file and include only the components that are used for the spec (e.g. if a patch is not applied for a particular spec version, then it is excluded from the content hash).
This AST examination fails in some cases where the "when" condition for a patch/phase is not a string literal. At this time `swig` is such an example. This PR updates the package hash calculation logic to fall back to including content when it cannot evaluate a `when` condition (even though it may not strictly be required by the spec).

Build caching: support package hash for swig

---

lib/spack/spack/package.py

@scottwittenburg noticed that when bootstrapping compilers, we just concretize the compiler spec without trying to match its arch/os to the spec it came from.
This PR ensures that the bootstrapped compiler is built for the same architecture as the spec for which it is being bootstrapped.

match bootstrapped compiler to architecture

---

.travis.yml
share/spack/qa/run-unit-tests

Before this commit we used to run the entire unit test suite in the presence of a failure. Since we currently rely a lot on the state of the filesystem etc. the end report was most of the time showing spurious failures that were a consequence of the first failing test.
This PR makes unit tests exit at the first failing test

Travis exits at the first failing test

---

var/spack/repos/builtin/packages/acts-core/package.py

Release notes: https://gitlab.cern.ch/acts/acts-core/-/tags/v0.12.00 .

New ACTS version: 0.12.0

---

share/spack/setup-env.sh

This change should harden shell detection when `procfs` is available, so that Spack detects the correct shell even when the setup script is sourced indirectly (as part of another script).

Harden shell detection when procfs is available

---

var/spack/repos/builtin/packages/mrnet/package.py

This is part of the cleanup of nonexisting dependencies in #13949.
MRNet had an optional dependency on `cti`, which doesn't exist.  Remove it from the repo, at least until someone adds `cti` back.
FYI @jgalarowicz.

mrnet: remove nonexisting cti dependency

---

lib/spack/llnl/util/cpu/detect.py
lib/spack/llnl/util/cpu/microarchitectures.json
lib/spack/llnl/util/cpu/schema.py
lib/spack/spack/test/llnl/util/cpu.py

Refers to #13780 
Also fixes a couple of typos in GCC flags.

Display human readable text for AArch64 vendors

---

var/spack/repos/builtin/packages/adios2/2.5-fix-clear_cache.patch
var/spack/repos/builtin/packages/adios2/package.py

Fix the argument type of the `__clear_cache` function in the adios2 source code match the argument type of the built-in function `__clear_cache` function for Fujitsu compiler.

adios2: Fix argument type of clear_cache for Fujitsu compiler

---

var/spack/repos/builtin/packages/py-scipy/package.py

SciPy has a new minor release. It looks like they removed a lot of deprecated functions, so things aren't backwards compatible. We'll have to keep an eye out for any packages that don't build with the latest version of SciPy.
Successfully installs and passes all unit tests on macOS 10.15.2 with Clang 11.0.0 and Python 3.7.4.

Add py-scipy 1.4.0

---

lib/spack/llnl/util/argparsewriter.py

Argparse allows you to include parameters of `add_argument` in your help messages. See https://docs.python.org/3/library/argparse.html#help:
> The help strings can include various format specifiers to avoid repetition of things like the program name or the argument default. The available specifiers include the program name, %(prog)s and most keyword arguments to add_argument(), e.g. %(default)s, %(type)s, etc.:
This worked fine for `spack create -h`, but didn't work with our custom rST argparse formatter. This PR fixes that. @tldahlgren 
```console
$ spack commands --format=rst | grep -A 36 'spack create'
spack create
------------
create a new package file
.. code-block:: console
spack create [-hf] [--keep-stage] [-n NAME] [-t TEMPLATE] [-r REPO]
[-N NAMESPACE] [--skip-editor]
[url] …
```

Fix argparse rST parsing of help messages

---

var/spack/repos/builtin/packages/lammps/package.py

The incorrect `reax` package keyword is replaced with the correct `user-reaxc` keyword, according to LAMMPS' [package details](https://lammps.sandia.gov/doc/Packages_details.html#pkg-user-reaxc).
The correction has been validated by running a LAMMPS task that requires the `USER-REAXC` package.
Thank you.

LAMMPS: Fix USER-REAXC package variant

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Add the latest release of openPMD-api, `v0.10.2` .

openPMD-api: 0.10.2

---

var/spack/repos/builtin/packages/root/README.md
var/spack/repos/builtin/packages/root/package.py

* Completely re-vamp CMake option handling for readability and maintainability:
* Three categories of option: control, builtin and feature, alphabetically sorted.
* Each option is described as a list: an option name followed by an optional value which is either Boolean or a string representing the name of a variant. If the value is omitted, it defaults to the option name.
* New functions `_process_opts()` and `_process_opt()` (nested) to turn all supplied option/value specifications into CMake arguments.
* Remove overly-terse per-option comments in favor of (much) more comprehensive notes in README.md.
* Variants and conflicts:
* Remove `test` variant in favor of pegging ROOT `testing` option to the value of `self.run_tests` since the install is unaffected, per ROOT developer.
* Remove …

root: Rationalize and improve version, variant and ROOT option handling.

---

var/spack/repos/builtin/packages/acts-core/package.py
var/spack/repos/builtin/packages/py-zc-lockfile/package.py

interprocess locking in pythyon, dependency of cherrypy framework

New package: py-zc-lockfile

---

lib/spack/spack/architecture.py
lib/spack/spack/compiler.py
lib/spack/spack/compilers/pgi.py

`pgcc -V` was failing on `ppc64` machines because it returns 2 (despite correctly printing version information).  On `x86_64` machines the same command returns 0 and doesn't cause an error.
@becker33 @alalazo FYI

bugfix: `pgcc -V` returns 2 on power machines

---

var/spack/repos/builtin/packages/parallel-netcdf/package.py

Added checksum for recent 1.12.1 release.
This version has fixes required for building with OpenMPI-4.0.2 and later  related to the use of symbols deprecated in MPI-3.0

PNETCDF: Update to include latest release 1.12.1

---

var/spack/repos/builtin/packages/amrex/package.py

I added definition of CMAKE_Fortran_MODDIR_FLAG, because specifying place to output fortran modules when using Fujitsu compiler.

amrex: Define module directry when compiling with Fujitsu compiler.

---

var/spack/repos/builtin/packages/netcdf-c/package.py

Added checksum for recent 1.12.1 release.
This version has fixes required for building with OpenMPI-4.0.2 and later  related to the use of symbols deprecated in MPI-3.0

NETCDF-C: Add latest release 4.7.3

---

lib/spack/spack/architecture.py
lib/spack/spack/cmd/spec.py
lib/spack/spack/environment.py
lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py

Fixes #12779.
This addresses two problems:
1. Checks for deprecated specs (introduced in #12933) were repeatedly taking out read locks on the database, which can be very slow.
2. `get_platform()` is pretty expensive and can be called many times in a spack invocation.
@ajw1980 @matz-e: does this improve things for you?

Improve concretization performance

---

lib/spack/spack/package.py
lib/spack/spack/test/package_class.py
lib/spack/spack/test/package_sanity.py
var/spack/repos/builtin.mock/packages/missing-dependency/package.py

fixes #1735
Currently, there are some packages in the mainline that list dependencies that don't exist.  We should get rid of those or add the missing packages.  To address this, I've added a sanity check that reports non-existing dependencies in `builtin`.
I tracked this down because it was causing issues with dependency solves in the new concretizer -- we can keep this issue open and keep rebasing it until we sanitize `develop`, but it would be nice to get these resolved soon.
Here's the current list:
- @adamjstewart: some of these are python test dependencies -- I think they're yours and we just need to add them.
- @chissg, @gartung: not sure what to do with the ones on `root`.
- @jgalarowicz: A few of these are yours.  For `cbtf-krell` I'm guessing the dependencies should probably be …

Sanity check missing dependencies

---

var/spack/repos/builtin/packages/root/package.py

As it turns out, the check for value bool-ness of https://github.com/spack/spack/pull/14203 was not compatible with python 3. This PR fixes that without breaking python 2 compatibility.

Remove python2-ism in root package

---

var/spack/repos/builtin/packages/gromacs/package.py

GROMACS silently picks up "hwloc" if cmake is not told explicitly what to do with it but is found during compile time (e.g. installed in /usr). This pull request adds a new variant to control this situation and pull in the required dependency on demand.

Explicit hwloc dependency for GROMACS

---

var/spack/repos/builtin/packages/root/package.py

Well, I _do_ have an interest in keeping this package working on my machines, along with an unusual system configuration that's unpleasantly good at catching CentOS- and CERN-isms in the ROOT build recipe...

root: Adding myself as a ROOT maintainer

---

var/spack/repos/builtin/packages/py-pyinstrument-cext/package.py

Successfully builds on macOS 10.15.2 with Clang 11.0.0 and Python 3.7.4.

Add py-pyinstrument-cext package

---

var/spack/repos/builtin/packages/root/package.py

The patch which prevents ROOT from building its own version of unuran is not compatible with the ROOT 6.06 series. The first release on which it was tested to apply cleanly is ROOT 6.08/06.

root: Do not apply the unuran patch to ROOT 6.06/xy, it is not compatible

---

var/spack/repos/builtin/packages/quantum-espresso/package.py

This is a minor update:
- Support for QE 6.5
- Configure patch for QE 6.4.1 and 6.5 so that `hdf5=serial` is final supported in the serial QE case.

QE Update Dec 2019

---

var/spack/repos/builtin/packages/root/package.py

@chissg After further investigation, the latest 6.06/xy releases clearly state that they're not compatible with the GCC 5 ABI, so getting ROOT 6.06 to work on GCC 5+ is probably a lost cause.

root: Record that old versions of ROOT don't support modern GCC

---

var/spack/repos/builtin/packages/dd4hep/package.py

This is basically the same issue which happened to ROOT back in the days of #11579, and the same fix happens to work here.

dd4hep: Latest versions of CMake need a hand for Python detection

---

var/spack/repos/builtin/packages/node-js/package.py

The latest version of node.js seems to support Python 3 now! It looks like there has been experimental support for quite some time, so I'm not sure what version was the first to add support. I tried both 12.14.0 and 13.5.0 and the former had some "ImportError: no module named 'site'" style errors, while 13.5.0 works fine. Now I just have to get `npm` working...
Successfully builds on macOS 10.15.2 with Clang 11.0.0 and Python 3.7.4.

node-js: add Python 3 support

---

var/spack/repos/builtin/packages/py-pyinstrument/package.py

Can't test this yet, as I'm still working on getting `npm` and `node-js` to build with Python 3.
Depends on #14240

Add py-pyinstrument package

---

var/spack/repos/builtin/packages/npm/package.py

Successfully installs on macOS 10.15.2 with Clang 11.0.0, Python 3.7.4, and Node.js 12.14.0.

npm: add Python 3 support

---

lib/spack/spack/util/environment.py

Since there is no `python` on `RHEL/CentOS-8`. Alternatively, one could query the OS version and use that for an `if-else` clause.

RHEL8 bugfix for unavailability of python.

---

var/spack/repos/builtin/packages/py-botocore/package.py

Successfully installs on macOS 10.15.2 with Python 3.7.4 and Clang 11.0.0.

Add py-botocore 1.13.44

---

var/spack/repos/builtin/packages/py-numpy/package.py

Successfully builds and passes all unit tests on macOS 10.15.2 with Python 3.7.4, Intel MKL 2019.4.233, and Clang 11.0.0.
NumPy has always required Cython to build from source, but historically the PyPI tarballs came pre-Cythonized. This caused problems whenever a new version of CPython was released, requiring a newer version of Cython than was used to generate the release. @rgommers made the change requiring Cython even for PyPI tarballs as of https://github.com/numpy/numpy/pull/14453.

Add py-numpy 1.18.0

---

var/spack/repos/builtin/packages/py-boto3/package.py

Successfully installs on macOS 10.15.2 with Python 3.7.4 and Clang 11.0.0.

Add py-boto3 1.10.44

---

lib/spack/llnl/util/filesystem.py
lib/spack/llnl/util/lock.py
lib/spack/spack/cmd/install.py
lib/spack/spack/database.py
lib/spack/spack/environment.py
lib/spack/spack/filesystem_view.py
lib/spack/spack/spec.py
lib/spack/spack/test/llnl/util/lock.py
lib/spack/spack/util/file_cache.py

Fixes #14259.
This fixes a lot of performance issues with the view generation phase of environments.  It also fixes a number of correctness issues with the transaction classes in `llnl.util.lock`.
Performance stuff:
Lock stuff:

Major performance improvements for `spack install` in environments

---

var/spack/repos/builtin/packages/nektar/package.py

`nektar@5.0.0` has been built sucessfully on `gcc@8.3.0`.

Bump nektar to 5.0.0.

---

lib/spack/llnl/util/cpu/microarchitectures.json

microarchitectures-a64fx: fix typo.

---

COPYRIGHT
lib/spack/external/_pytest/pytester.py
lib/spack/external/ruamel/yaml/compat.py

Remove a few remaining mentions of the pyqver package that we removed in #14289.

tests: finish removing pyqver from the repository

---

.github/workflows/build_tests_linux.yaml
.travis.yml
README.md
share/spack/qa/configuration/packages.yaml

refers #13485
closes #5842
This PR moves build smoke tests from TravisCI and migrates them to Github Actions. The result is that build tests are performed in parallel with unit tests and they don't hog additional resources on Travis. The workflow will not run if a PR only changes packages in the built-in repository, but will always run on pushes to develop or master.

Moved build tests from Travis to Github Actions

---

var/spack/repos/builtin/packages/aspa/fix_common_errors.patch
var/spack/repos/builtin/packages/aspa/package.py

* defined new member 'Vec_value_type' in 'self' namespace.
```
460    In file included from ../src/mtl_headers/mtl/matrix_implementation.h:27:
>> 461    ../src/mtl_headers/mtl/linalg_vec.h:135:21: error: no member named 'Vec_value_type
' in 'linalg_vec<RepType, RepPtr, NN>'
462            while (*i == self::Vec_value_type(0)) ++i;
463                         ~~~~~~^
```
I defined `Vec_value_type` as a member of `linalg_vec` namespace with reference to other header file `src/mtl_headers/mtl/dense1D.h`.
* fix narrowing error.
```
>> 915    ../src/utils/toolbox/database/HDFDatabase.cc:689:24: error: non-con
stant-expression cannot be narrowed from type 'int' to 'hsize_t' (a
ka 'unsigned long long') in initializer list [-Wc++11-narrowing]
916          hsize_t dim[] = {nelements};
917 …
```

aspa: Fix common errors.

---

var/spack/repos/builtin/packages/cairo/fontconfig.patch
var/spack/repos/builtin/packages/cairo/package.py

With #14092, cairo is building with fontconfig disabled by default. However, cairo's build system is still looking for fontconfig in one of its files. I found a bug report to cairo with a patch on https://gitlab.freedesktop.org/cairo/cairo/issues/346. This was also report in Spack issue #14112.

patch cairo build files for build without fontconfig fixes #14112

---

var/spack/repos/builtin/packages/pango/package.py

Due to the changes in #14092, pango needs to specify additional requirements.

added build dependences required after cairo package change

---

lib/spack/spack/cmd/info.py

In "spack info" the Variants header currently has two blank lines under it. That's too much. It looks like the actual content belongs to something else.
Instead underline the headers to make things more obvious.

Improve info variant header

---

lib/spack/llnl/util/tty/colify.py

Commands like `spack blame` were printig poorly when redirected to files, as colify reverts to a single column when redirected.  This works for list data but not tables.

bugfix: colify_table should not revert to 1 column for non-tty

---

lib/spack/spack/modules/common.py
lib/spack/spack/tengine.py

Jinja2 costs a tenth to a few tenths of a second to import, so we should avoid importing it on startup.  This seems to speed up spack startup on clusters (especially with NFS).

externals: avoid importing jinja2 on startup

---

var/spack/repos/builtin/packages/harfbuzz/package.py

This PR adds graphite2 support to harfbuzz. This PR depends on PR #14299, which added the graphite2 package to spack.

Add support for graphite2 to harfbuzz

---

lib/spack/llnl/util/lang.py
lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/package_prefs.py
lib/spack/spack/test/cmd/config.py
lib/spack/spack/test/cmd/env.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/cmd/module.py
lib/spack/spack/test/cmd/spec.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/config.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/data/config.yaml
lib/spack/spack/test/git_fetch.py
lib/spack/spack/test/hg_fetch.py
lib/spack/spack/test/install.py
lib/spack/spack/test/mirror.py
lib/spack/spack/test/packages.py
lib/spack/spack/test/repo.py
lib/spack/spack/test/spec_dag.py
lib/spack/spack/test/spec_yaml.py
lib/spack/spack/test/svn_fetch.py
lib/spack/spack/test/url_fetch.py

This was originally just about making `spack.cmd.common.arguments` more lazy to shave some time off Spack startup.  I attempted to refactor that module so that it would not construct so many `Args` objects at module scope.  That is now done lazily instead.
When doing that, a weird issue arose.  This test was failing:
```python
@pytest.mark.parametrize('arguments,expected', [
([], spack.config.get('config:dirty')),  # default from config file
(['--clean'], False),
(['--dirty'], True),
])
def test_install_dirty_flag(parser, arguments, expected):
args = parser.parse_args(arguments)
assert args.dirty == expected
```
It turns out it failed because `Args` are now fetched lazily:
```python
@arg
def dirty():
return Args(
'--dirty',
action='store_true',
default=spack.config.get('config:dirty'), …
```

Refactor how global state is handled in test fixtures

---

lib/spack/spack/cmd/install.py
lib/spack/spack/report.py
lib/spack/spack/reporters/cdash.py
lib/spack/spack/test/cmd/install.py

Also:
* Avoid 'installed_from_binary_cache' KeyError in CDash reporter
* Make it so InstallErrors get described in reports

Add support for authenticated CDash uploads

---

lib/spack/spack/test/cmd/install.py

This test passed in #14200, but the intervening merge of #14309 revealed a missing fixture.  I've added the `install_mockery` fixture here.
@zackgalbreath: FYI

bugfix: add required fixture for CDash authentication test

---

.codecov.yml

Ever since #13389 dropped macOS tests from PRs, GitHub has been a sea of ❌as every single PR fails its codecov tests. This prevents PRs from being merged on mobile devices, and [causes](https://github.com/spack/spack/pull/14322#issuecomment-569898843) [confusion](https://github.com/spack/spack/pull/14147#issuecomment-565453920) [among](https://github.com/spack/spack/pull/13931#issuecomment-560079501) [PR](https://github.com/spack/spack/pull/13707#issuecomment-553587158) [contributors](https://github.com/spack/spack/pull/13658#issuecomment-552118257). 
A more permanent solution would be to:
1. Skip coverage tests on package-only PRs, and
2. Run macOS tests for all core changes
This PR is a workaround until that happens.
@alalazo @tgamblin

Ignore coverage drop due to lack of macOS tests

---

lib/spack/spack/cmd/create.py

R packages can contain configure scripts so R needs to be before
autotools in the clue list.

Modify create clue list so R packages are detected

---

.github/workflows/linux_build_tests.yaml
.github/workflows/minimum_python_versions.yaml
README.md

I usually want to look at the Travis CI output, but I currently have to scroll down to see it. This renames checks to be a bit shorter and more consistent with Travis's naming, and also so that actions appear lower than travis and codecov in the list of checks.

tests: rename checks in github actions

---

lib/spack/docs/contribution_guide.rst
lib/spack/docs/developer_guide.rst
lib/spack/spack/cmd/test.py
lib/spack/spack/test/cmd/test.py
share/spack/spack-completion.bash

Previously, `spack test` automatically passed all of its arguments to `pytest -k` if no options were provided, and to `pytest` if they were. `spack test -l` also provided a list of test filenames, but they didn't really let you completely narrow down which tests you wanted to run.
Instead of trying to do our own weird thing, this passes `spack test` args directly to `pytest`, and omits the implicit `-k`.  This means we can now run, e.g.:
```console
$ spack test spec_syntax.py::TestSpecSyntax::test_ambiguous
```
This wasn't possible before, because we'd pass the fully qualified name to `pytest -k` and get an error.
Because `pytest` doesn't have the greatest ability to list tests, I've tweaked the `-l`/`--list`, `-L`/`--list-long`, and `-N`/`--list-names` options to `spack test` so that …

tests: improved `spack test` command line options

---

lib/spack/spack/test/cmd/install.py

The latest cdash test creates a local cdash_reports directory, but it should do that in a tmpdir.
@zackgalbreath FYI

bugfix: cdash tests shoudln't modify working directory

---

lib/spack/spack/cmd/__init__.py
lib/spack/spack/concretize.py
lib/spack/spack/provider_index.py
lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/install.py
lib/spack/spack/test/spec_semantics.py
lib/spack/spack/test/spec_syntax.py

The imports in `spec.py` are getting to be pretty unwieldy.  This probably means the file needs to be broken up, but for now we can at least clean up the namespace.

refactor: cleanup imports in spec.py

---

lib/spack/spack/build_systems/intel.py
var/spack/repos/builtin/packages/py-torch/package.py

PyTorch has trouble finding the MKL libraries when they are not in default system install locations. On macOS, simply setting `CMAKE_PREFIX_PATH` to the `<prefix>/mkl` directory is sufficient, but on Linux, the libraries are tucked away inside `<prefix>/mkl/intel64/lib`. This PR sets the appropriate CMake environment variables to allow PyTorch to find MKL. I put the changes in the `IntelPackage` base class so that other packages can benefit from this too.
Tested with PyTorch 1.3.1 and master on macOS 10.15.2 and Amazon Linux 2 with Intel MKL 2019.4.233 and 2019.5.281.
Fixes #14232 
Fixes https://github.com/pytorch/pytorch/issues/24334
@coreyjadams can you test this out?

MKL: set appropriate CMake env vars

---

var/spack/repos/builtin/packages/gromacs/package.py

Because of a bug in the current concretizer,
spack install gromacs
fails because gromacs depends on hwloc (default is v2), and Open MPI
(the default MPI library) depends on hwloc v1.
As discussed in https://github.com/spack/spack/issues/14339, this
workaround should be removed once the concretizer is fixed
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

gromacs: depend on hwloc v1

---

var/spack/repos/builtin/packages/mercury/package.py

Added `+verbose` variant to Mercury package. The variant is ON by default, and will make Mercury print errors on stderr.

Mercury package: added verbose variant

---

var/spack/repos/builtin/packages/perl-bioperl/package.py

Due to formatting differences, the older version of perl-bioperl was
getting picked up as the preferred version. This PR explicitly sets the
newer version to be preferred.

Set preferred version of perl-bioperl

---

var/spack/repos/builtin/packages/environment-modules/package.py

Happy new year Spack folks!
New environment-modules bugfix release in the v4.4 serie.
Release announcement: https://timeline.noticeable.io/cbzeG7wTvAIqj21zbUmx/posts/modules-4-4-1-released

environment-modules: add version 4.4.1

---

var/spack/repos/builtin/packages/py-torchvision/package.py

The next release (0.5.0) will fix this, and is expected to be released sometime in the next week.

py-torchvision 0.4.X does not support py-pillow 7.X.Y

---

var/spack/repos/builtin/packages/lcms/package.py

Library is `liblcms2`, not `liblcms`

Add libs property to lcms package

---

var/spack/repos/builtin/packages/openjpeg/package.py

Library is `libopenjp2`, not `libopenjpeg`

Add libs property to openjpeg package

---

var/spack/repos/builtin/packages/gcc/package.py

This PR adjusts the constraints on isl with GCC-5. GCC-5.1 and GCC-5.2
need isl-0.14, not isl-0.15.

Adjust constraints of gcc-5

---

var/spack/repos/builtin/packages/libwebp/package.py

`libwebp` wouldn't install on macOS, so I converted it to `AutotoolsPackage`. The [Homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/webp.rb) also uses Autotools.
Also added some variants to enable/disable libwebpmux support.
Successfully installs on macOS 10.15.2 with Clang 11.0.0 both with and without libwebpmux support enabled.

libwebp: CMakePackage -> AutotoolsPackage

---

var/spack/repos/builtin/packages/py-pillow/package.py

Makes the following changes:
Successfully installs and passes all unit tests on macOS 10.15.2 with Python 3.7.4 and Clang 11.0.0 with all variants enabled and all variants disabled. 
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 7.0.0
platform     darwin 3.7.4 (default, Nov  6 2019, 16:24:25)
[Clang 11.0.0 (clang-1100.0.33.12)]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.3)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support …
```

Overhaul py-pillow package

---

lib/spack/spack/cmd/spec.py

@healther I finally figured out a clean way to do this!
```console
$ spack spec --help
usage: spack spec [-hlLIyjNt] [-c {nodes,edges,paths}] ...
show what would be installed, given a spec
positional arguments:
specs                 specs of packages
optional arguments:
-h, --help            show this help message and exit
-l, --long            show dependency hashes as well as versions
-L, --very-long       show full dependency hashes as well as versions
-I, --install-status  show install status of packages. packages can be: installed [+], missing and needed by an installed package [-], or not installed (no annotation)
-y, --yaml            print concrete spec as YAML
-j, --json            print concrete spec as YAML
-c {nodes,edges,paths}, --cover {nodes,edges,paths}
how extensively to …
```

Reference `spack help --spec` in `spack spec --help`

---

var/spack/repos/builtin/packages/singularity/package.py

Builds for me on CentOS 7.
Tested (after running the setuid helper script) by running a docker container/
```
[hartzell@spacker spack]$ singularity exec docker://ubuntu:latest echo "Hello Dinosaur..."
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 2746a4a261c9 done
Copying blob 4c1d20cdee96 done
Copying blob 0d3160e1d0de done
Copying blob c8e37668deea done
Copying config d2d21cbe92 done
Writing manifest to image destination
Storing signatures
2020/01/06 19:03:01  info unpack layer: sha256:2746a4a261c9e18bfd7ff0429c18fd7522acc14fa4c7ec8ab37ba5ebaadbc584
2020/01/06 19:03:03  info unpack layer: sha256:4c1d20cdee96111c8acf1858b62655a37ce81ae48648993542b7ac363ac5c0e5
2020/01/06 19:03:03  info unpack layer: …
```

Add singularity@3.5.2

---

var/spack/repos/builtin/packages/gdal/package.py

gdal@2.4.3 is missing the libgeotiff dependency.

gdal: Fix libgeotiff dependency

---

var/spack/repos/builtin/packages/ncl/package.py

Moreover, cairo needs to have its freetype variant enabled.

ncl: Add missing fontconfig dependency

---

var/spack/repos/builtin/packages/py-cython/package.py
var/spack/repos/builtin/packages/py-numpy/package.py

I accidentally merged NumPy 1.18.1 without checking to see if its dependencies changed. Apparently it depends on the bleeding edge of Cython. Successfully installs on macOS 10.15.2 with Clang 11.0.0 and Python 3.7.4.

NumPy 1.18.1 requires Cython 0.29.14

---

var/spack/repos/builtin/packages/root/package.py

Found while narrowing down ROOT / python 3 incompatibility as part of https://github.com/spack/spack/pull/14225 .

root: Record a new ROOT/GCC incompatibility

---

var/spack/repos/builtin/packages/hpcviewer/package.py

Add conflicts for aarch64 and darwin.
----------
Is there a way to specify 'platform=windows'?  The hpcviewer spack
recipe also doesn't work on windows, but I couldn't find an example
for that.  I thought spack runs on windows, right?
Also, the conflict for aarch64 doesn't really work.  On ARM, I get:
```
spack install hpcviewer
==> Error: There are no valid versions for hpcviewer that match ':'
```
The problem is that conflicts happen after concretization and there is
no version available for aarch64.  So, concretization fails before
conflicts are checked and the 'helpful' message is never printed.
This is specific to a binary package where we have a different tar
file per platform, and this platform isn't supported, so there are no
valid versions.

hpcviewer: add version 2019.12

---

lib/spack/spack/compilers/clang.py
lib/spack/spack/test/compilers.py

Starting with clang-9, Ubuntu no longer uses the 'svn' prefix in its version information. This was causing the version string
clang version 9.0.1-+201911131414230800840845a1eea-1~exp1~20191113231141.78
to report a version of 
9.0.1-+201911131414230800840845a1eea
which was interpreted as a version of `9.0.1-` and a variant. With this patch, the version is correctly reported as just `9.0.1`, and the compiler subcommands work correctly.
**Before**
$ cat ~/.spack/linux/compilers.yaml
compilers: []
$ spack compiler find
==> Added 10 new compilers to /home/tim/.spack/linux/compilers.yaml
gcc@8.3.0  gcc@6.5.0  gcc@4.9.4  gcc@4.7                                     clang@8.0.1
gcc@7.4.0  gcc@5.5.0  gcc@4.8    clang@9.0.1-+201911131414230800840845a1eea  clang@6.0.1
==> Compilers are defined in the …

spack.compilers.clang: Add new version check

---

var/spack/repos/builtin/packages/py-scikit-build/package.py

Scikit-build is a useful python repository for building python extensions that use CMake.  It is pure python and independent of cmake itself.
Source code: https://github.com/scikit-build/scikit-build
Documentation: https://scikit-build.readthedocs.io/en/latest/index.html
This PR is exclusively the addition of a package for scikit-build.

Adding a new package, scikit-build, which is useful for building Python Extensions

---

var/spack/repos/builtin/packages/rapidjson/package.py
var/spack/repos/builtin/packages/rapidjson/remove_march.patch

Fujitsu compiler does not correspond to define '-march=native'.
So, I Fixed to delete '-march=native' when using Fujitsu compiler.

rapidjson: delete '-march' flags when using Fujitsu compiler.

---

var/spack/repos/builtin/packages/root/package.py

To quote Guilherme Amadio in [ROOT-9033](https://sft.its.cern.ch/jira/browse/ROOT-9033), back in February 2018:
> The `python3` option should be avoided. It has been removed in the master branch, and on the other branches, the recommended way to configure ROOT with Python 3.x is to pass `-Dpython=ON -DPYTHON_EXECUTABLE=<full path to python3 interpreter>` to CMake when configuring ROOT.
(Further, other comments on that issue suggest that the `python3` CMake option was already gone at least as far as in 2017 / the ROOT 6.10 era.)
We're already doing the `-DPYTHON_EXECUTABLE` part, but we don't set `-Dpython` when building for Python 3, which means in practice that we're not building PyROOT...

root: Configure ROOT correctly for python3

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

Successfully installs on macOS 10.15.2 with Clang 11.0.0 and Python 3.7.4.
If anyone else wants to test this for me, please do, as I don't have access to a GPU, aside from AWS, where I've never managed to get this to build.

Add TensorFlow 2.1.0

---

share/spack/spack-completion.bash

The only purpose of this PR is to minimize the diff in #14393 by factoring out formatting differences.
This PR should involve no functionality change.

Reformat Bash tab completion script

---

lib/spack/spack/test/relocate.py

Fixes #14402 
Check if patchelf is executable, not binary, in case a site is wrapping it.

tests/test_patchelf_is_relocatable: patchelf executable, not binary

---

var/spack/repos/builtin/packages/python/package.py

Anaconda still defaults to Python 3.7, so we will too.

Add Python 3.8.1

---

var/spack/repos/builtin/packages/python/package.py

Without this, the build fails if users do not have a C++ compiler installed. It might make more sense to require a C++ compiler, though. Opinions?

python: Fix post-install script without C++ compiler

---

var/spack/repos/builtin/packages/r-mass/package.py

Added new version '7.3-51.5', and fix checksum of '7.3-51.4'.
Package of '7.3-51.4' was moved to archive directory, and was modified following points.
```
[usr@apollo13 r-mass]$ diff -ur MASS MASS_new
diff -ur MASS/DESCRIPTION MASS_new/DESCRIPTION
--- MASS/DESCRIPTION    2019-04-26 22:18:59.000000000 +0900
+++ MASS_new/DESCRIPTION        2019-03-31 16:55:05.000000000 +0900
@@ -33,4 +33,4 @@
David Firth [ctb]
Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
Repository: CRAN
-Date/Publication: 2019-04-26 13:18:59 UTC
+Date/Publication: 2019-03-31 07:55:05 UTC
diff -ur MASS/MD5 MASS_new/MD5
--- MASS/MD5    2019-04-26 22:18:59.000000000 +0900
+++ MASS_new/MD5        2019-03-31 16:55:05.000000000 +0900
@@ -1,4 +1,4 @@
-a2dbb5e4e548578e5d6fce1c6683d531 *DESCRIPTION …
```

r-mass: Add version '7.3-51.5' and fix checksum.

---

var/spack/repos/builtin/packages/libcircle/package.py

Must run the included `autogen.sh` script for auto tools when building from master. Spack's built-in auto-re-conf-whatever doesn't quite work. 
Tagging @adammoody

libcircle: add develop version from git master branch

---

var/spack/repos/builtin/packages/upcxx/package.py

Makes explicit UPCXX's dependency on Python 2 >= 2.7.5

upcxx depends on python 2 >= 2.7.5

---

lib/spack/spack/test/url_parse.py
lib/spack/spack/url.py

@darmac with this you won't need any `url_for_version` in #14442.

Fix parsing of rocketmq URL

---

var/spack/repos/builtin/packages/gapfiller/package.py

The current gapfiller package patches some but not all (bwa) of the necessary perl sources.

gapfiller: traverse subdirectories in patch

---

share/spack/setup-env.sh

The pathadd function was using setopt to configure zsh for word
splitting, which leaks out of the function and breaks default
functionality in a number of external zsh plugins and packages.  This
switches to emulate -L, just as the spack function uses, to keep the
setting local to the function.

(fix zsh) stop word splitting from leaking out of setup-env.sh 

---

var/spack/repos/builtin/packages/htslib/package.py

This PR updates htslib to version 1.10.2 and adds a libcurl variant. The
libcurl variant defaults to True because, while it is optional, it is
highly recommended by the project developers.
Other things done:
- remove unused libzip dependency
- be consistent with quotes

Update htslib and add libcurl variant

---

var/spack/repos/builtin/packages/trnascan-se/package.py

trnascan-se needs an infernal installation to function properly. This adds infernal as a dep and configures the path to the installation in the tRNAscan config.

trnascan-se: add and configure infernal dependency

---

var/spack/repos/builtin/packages/bcftools/fix_mk.patch
var/spack/repos/builtin/packages/bcftools/guess-ploidy.py_2to3.patch
var/spack/repos/builtin/packages/bcftools/makefile_12.patch
var/spack/repos/builtin/packages/bcftools/makefile_13.patch
var/spack/repos/builtin/packages/bcftools/makefile_14.patch
var/spack/repos/builtin/packages/bcftools/package.py

This PR updates bcftools to 1.10.2 and is dependent on PR #14504.
This PR also fixes builds of other versions. Versions 1.2-1.4 did not
use autotools so when the packaeg was converted to use autotools with
version 1.6 those older versions could no longer build. Also, those
versions needed to be patched to use an external htsllib. The method of
finding the external htslib is also different for those older versions.
In addition, this PR adds two variants to bcftools:
- libgsl
- perl-filters
Finally, dependencies for perl and python are added, and an unused
dependency for libzip was removed.

Update and fix bcftools package

---

var/spack/repos/builtin/packages/icu4c/package.py

This PR makes several changes to the icu4c package
1. add updated version to 65.1
2. modify the default url as project has moved to github
3. set UTF-8 locale to support building from source files in UTF-8
format
Note that the older versions are not available on github so explicit urls
were used. This PR will close #14399.

Update the icu4c package

---

var/spack/repos/builtin/packages/interproscan/package.py
var/spack/repos/builtin/packages/interproscan/ps_scan.patch

One of the perl scripts was encoded with ISO-8859-1, which caused the
sbang replacement process to fail when spack uses python3. This PR
converts the ps_scan script to UTF-8 encoding.

Convert encoding of script in interproscan

---

var/spack/repos/builtin/packages/texlive/package.py

This PR reworks the texlive package so that it installs from versioned
source distibution files. This is preferred over installing the binary
package for several reasons. For the binary installation:
1. Each component is downloaded, so can not use a spack mirror.
2. Changes in components over time are not reflected in spack hash.
3. Some of the binaries do not run due to glibc issues, depending on OS.
This PR keeps the binary installation as an option but it should be
considered deprecated, and probably rewmoved at some point.
This PR depends on zziplib from PR #14318.

Rework texlive package to install from source

---

var/spack/repos/builtin/packages/openmpi/package.py
var/spack/repos/builtin/packages/ucx/package.py

Fixes:
1. MPI_THREAD_MULTIPLE problem with OpenMPI and UCX.
Changes:
1. OpenMPI provides two new depends_on options which result in UCX being compiled with multiple threads support. One implicit when OpenMPI 3.x is used, MPI_THREAD_MULTIPLE is enabled by default, and one explicit for OpenMPI <= 2.x, MPI_THREAD_MULTIPLE is disabled by default.
2. Extends UCX package to allow "Enable thread support in UCP and UCT" option.
3. Adds sha256 sums of UCX releases 1.6.1 and 1.2.0.
More details:
Fixes the issue with OpenMPI where programs that use MPI_THREAD_MULTIPLE will fail to execute because UCP worker didn't support it.
During the OpenMPI package installation, it's the +thread_multiple spec was not propagated to UCX nor UCX handled it at all.
Now, the OpenMPI package is capable of handling …

Adds MPI_THREAD_MULTIPLE support for OpenMPI to the variant with UCX fabrics

---

var/spack/repos/builtin/packages/jali/package.py
var/spack/repos/builtin/packages/mstk/package.py

Jali is a parallel unstructured mesh infrastructure library designed for use by multi-physics simulations.

New package Jali - unstructured mesh infrastructure for multiphysics applications

---

var/spack/repos/builtin/packages/graphviz/package.py

This PR restricts the graphviz version that the patches for building
with the Intel compiler apply to. The two patches that were needed for
building graphviz-2.40.1 with the Intel compiler are not needed for
graphviz-2.42.2.

Add version constraint to graphviz patches

---

var/spack/repos/builtin/packages/rocksdb/package.py

This series of commits updates RocksDB to the current version and adds some environment variables to avoid picking up system versions of some libraries if they are not explicitly requested as variants.

Update RocksDB to current version

---

var/spack/repos/builtin/packages/perl/package.py

Looks like I broke something with #14509. :frowning_face: Sorry I did not catch this earlier.
It seems that stable versions of perl also install a `perlX.Y.Z` binary. However, it seems that this binary can hang if used in conjunction with Spack's sbang workaround, as observed during automake's build.
@adamjstewart

perl: Fix binary detection

---

var/spack/repos/builtin/packages/py-torch/package.py

This PR adds CudaPackage in order to pick up the cuda/compiler conflicts
defined in CudaPackage.

Use CudaPackage mixin for py-torch

---

var/spack/repos/builtin/packages/falcon/Py_None.patch
var/spack/repos/builtin/packages/falcon/package.py

error: 
`non-void function 'initext_falcon' should return a value [-Wreturn-type]`
I set Py_None to return value because Python version 3 and later should return a value of PyObject type.

falcon: Set Py_None to return value

---

var/spack/repos/builtin/packages/mesa/package.py

to disable use of libunwind.  Without this mesa fails to build
using recent Cray compilers - cce 9 and higher -  on aarch64 systems.
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

mesa: check aarch64 system type as well

---

var/spack/repos/builtin/packages/unifyfs/package.py

This updates the UnifyFS package to account for the latest 0.9.0 version and removes support for version 0.2.0.

unifyfs: new release version

---

lib/spack/spack/util/environment.py
lib/spack/spack/util/module_cmd.py

@zzotta can you see if this fixes #14491 for you?
I'm not sure whether the quotes are necessary or not. I wanted to be robust in case `python` is installed in a directory containing spaces. Honestly, we should probably rewrite all of this stuff so that it doesn't use `shell=True`, and then it shouldn't be necessary anymore.
@s-sajid-ali @chissg

Fix use of sys.executable for module/env commands

---

var/spack/repos/builtin/packages/py-torch/package.py

Successfully builds on macOS 10.15.2 with Python 3.7.4 and Clang 11.0.0.
Note that this is the last release to support Python 2.

Add py-torch 1.4.0

---

var/spack/repos/builtin/packages/py-torchvision/package.py

Successfully builds on macOS 10.15.2 with PyTorch 1.4.0, Python 3.7.4, and Clang 11.0.0.
Note that this is the last release to support Python 2.

Add py-torchvision 0.5.0

---

var/spack/repos/builtin/packages/hdf5/package.py

Fixes #14537 
Based on https://github.com/spack/spack/issues/12586#issuecomment-532322303, it appears this patch is no longer needed in HDF5 1.10.6.
@hightower8083 @omsai

Don't patch latest version of HDF5

---

var/spack/repos/builtin/packages/suite-sparse/package.py

- The suite-sparse author publishes new versions starting with 5.5.0 on GitHub, see https://github.com/DrTimothyAldenDavis/SuiteSparse/releases and http://faculty.cse.tamu.edu/davis/SuiteSparse/
- change spack to download from there
- updated sha256 checksums from GitHub for all available releases
- For versions 5.4.0, 5.5.0, 5.6.0 there is a slightly different compilation necessary: first `make default` then `make install`.
Summary of the version changes (+ added, -removed [because not available on GitHub]):
```diff
+ 5.6.0
+ 5.5.0
+ 5.4.0
5.3.0
5.2.0
+ 5.1.2
5.1.0
+ 5.0.0
+ 4.5.6
4.5.5
- 4.5.4
4.5.3
- 4.5.1
```

suite-sparse: add 5.4.0, 5.5.0, and 5.6.0, GitHub releases

---

var/spack/repos/builtin/packages/openmpi/package.py

Unfortunately UCX 1.7.0 is appearing in RPMS before it's officially released.
There's a problem with Open MPI 4.0.x where x < 3 and this version of UCX,
namely that the UCT BTL fails to compile.
See https://github.com/open-mpi/ompi/issues/7128
This patch works around the problem by disabling the build of the UCT BTL
for releases 4.0.0 to 4.0.2.

openmpi: swat btl/uct ucx 1.7 bug

---

var/spack/repos/builtin/packages/py-voluptuous/package.py

- download from pypi instead of github, since versions `>0.11.5` are only on pypi
- add new versions `0.11.6`, `0.11.7`

py-voluptuous add new versions

---

var/spack/repos/builtin/packages/kcov/package.py

We use `kcov` for unit testing our shell scripts, but we didn't have a package for it.
Successfully installs on macOS 10.15.2 with Clang 11.0.0.

Add new kcov package

---

var/spack/repos/builtin/packages/py-theano/package.py

This PR adds the CudaPackage mixin class to py-theano. This replaces the
`gpu` variant with the `cuda` variant.

Use CudaPackage mixin for py-theano

---

lib/spack/spack/build_systems/gnu.py

One should not use os.path.join for URLs. This does only work on POSIX systems.
Instead use urljoin from urllib.parse.
Update used prefixes accordingly.

Use util.url.join for URLs in GNU Mirrors / reorder Mirrors

---

var/spack/repos/builtin/packages/samtools/package.py

This PR adds samtools-1.10 and sets the htlib directory so that the
spack built htslib can be used. This PR also arranges the dependencies
so that the htslib sequence is grouped on its own. Finally, the bzip2
dependency is removed and python and perl run dependencies are added.

Update and fix samtools

---

var/spack/repos/builtin/packages/patchelf/package.py

Quick change of the filename variables to avoid confusion with function variables per feedback from #14553

tests: Quick change of filename variables

---

lib/spack/spack/architecture.py
lib/spack/spack/spec.py
lib/spack/spack/test/spec_yaml.py

Fixes #13553.
Despite trying very hard to keep dicts out of our hash algorithm, we seem to still accidentally add them in ways that the tests can't catch. This can cause errors when hashes are not computed deterministically.
This PR fixes an error we saw with Python 3.5, where dictionary iteration order is random.  In this instance, we saw a bug when reading Spack environment lockfiles -- The load would fail like this:
```console
...
File "/sw/spack/lib/spack/spack/environment.py", line 1249, in concretized_specs
yield (s, self.specs_by_hash[h])
KeyError: 'qcttqplkwgxzjlycbs4rfxxladnt423p'
```
This was because the hashes differed depending on whether we wrote `path` or `module` first when recomputing the build hash as part of reading a Spack lockfile.  We can fix it by ensuring a …

bugfix: hashes should use ordered dictionaries everywhere

---

var/spack/repos/builtin/packages/libquo/package.py

Hello,
I'm the maintainer of libquo and just released v1.3.1.
This commit moves the libquo package from 1.3 to 1.3.1.
Thank you.

libquo: Update default version from 1.3 to 1.3.1.

---

var/spack/repos/builtin/packages/mpark-variant/nvcc.patch
var/spack/repos/builtin/packages/mpark-variant/package.py

Update the patch (#13901) to fix builds with NVCC <= 10.2.89 with the accepted PR for upcoming releases of the library.
Ref.: https://github.com/mpark/variant/pull/73

MPark.Variant: Patch NVCC C++14 Build 2

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/test/ci.py
lib/spack/spack/test/cmd/ci.py
lib/spack/spack/test/cmd/gpg.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/packaging.py
lib/spack/spack/util/gpg.py

refers #14594 
Details:
For `has_gnupg2`, since we were not trying to parse the version from the output of:
```console
$ gpg2 --version
```
this is effectively equivalent to check if `spack.util.gpg.GPG.gpg()` was found. If we need to ensure version is `^2.X` it's probably better to do it in `spack.util.gpg.GPG.gpg()` than in a separate function.

Removed code duplication in a few tests

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Enable the ADIOS1 backend by default.
This was only disabled until the build recipes (adios1 and its dependencies, e.g. sz) are mature enough in Spack to not affect/crash the default spec of openpmd-api.

openPMD-api: Default +adios1

---

lib/spack/spack/test/cmd/gpg.py
lib/spack/spack/test/conftest.py
lib/spack/spack/util/gpg.py

The `gpg2` command isn't always around; it's sometimes called `gpg`.  This is the case with the brew-installed version, and it's breaking our tests.
This fixes the currently breaking macOS tests.

bugfix: gpg2 is called 'gpg' on macOS

---

var/spack/repos/builtin/packages/root/package.py

For those unfamiliar with this longstanding issue, here's a quick summary:
- The design of Unices strongly favors putting all headers/libraries/binaries in one place, whereas the design of Spack strongly favors putting each package in its own prefix. As a result, if no further action is taken, file lookup sadness ensues.
- Spack's standard answer to this problem is the moral equivalent of crafting a CPATH which contains the include prefix of all dependencies during a build (using headers as an example, but it's the same idea for libraries & friends). That's `SPACK_INCLUDE_DIRS`.
- Sadly, this technique breaks when a package defines a header whose name clashes with that of a header of a dependency. Which is arguably a failure of C/++'s non-namespaced header file model, but well, we can't …

root: Fix root+x breakage from #11129

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Popular CMake find-scripts for ADIOS1 search for this binary instead of looking up `CMAKE_PREFIX_PATH`. Eases usage for downstream projects that just to `spack load` without `-r`.
Follow-up to #14599 that was caught in nightly deployment testing on OSX: https://dev.azure.com/axelhuebl/openPMD-api/_build/results?buildId=161&view=results

openPMD-api: adios_config to run env

---

lib/spack/spack/util/environment.py
lib/spack/spack/util/module_cmd.py

See issue #14568 
Currently unit tests for Spack don't run cleanly under `venvs`. This aims at fixing the issue while not regressing on #14252 and #14491. Bonus if anybody could suggest a way to test this patch for all these issues.

bugfix: make `_source_single_file` work in venvs

---

var/spack/repos/builtin/packages/charliecloud/package.py

Charliecloud now uses the autotools build system. It isn't clear how to update the package to handle both hand-rolled Makefile and autotool packages depending on the version. Please advise.
FWIIW, upstream (us) does not support older versions of Charliecloud. Must we complicate the spack package to include unsupported versions? Do other packages rely on Charliecloud?

add charliecloud/0.13

---

var/spack/repos/builtin/packages/pdt/package.py

Fixes #14588.  The PDT configuration detected ppc64le, and decided that XL should be the default compiler.  This PR will check whether the Spack compiler is GCC and correctly use the -GNU flag. If one of the supported PDT compilers are not found, the PDT installation will now fail with an error message.

Fixing GCC compiler setting for PDT package

---

bin/sbang

The perl binary can also be called `perlX.Y.Z` if using a development build or simply using the versioned binary.
We were also dropping all sbang arguments, since `exec $interpreter_v` was only using the first element of the `interpreter_v` array.
This fixes the underlying problem of #14536. We should still apply #14536 to be on the safe side, though.

sbang: Fix perl binary detection

---

lib/spack/spack/cmd/config.py
lib/spack/spack/test/cmd/config.py
share/spack/bash/spack-completion.in
share/spack/spack-completion.bash

This command allows you to get a list of all valid configuration sections from the command-line. Its intended use is in Spack's tab completion scripts.

Add spack config list command for tab completion

---

var/spack/repos/builtin/packages/harfbuzz/package.py

This PR sets a conflict on harfbuzz-2.3.1 when using the Intel compiler
as that version of harfbuzz does not compile with the Intel compiler.

Set conflicts harfbuzz-2.3.1 and intel compiler

---

var/spack/repos/builtin/packages/libhio/package.py

The autoreconf is not necessary and can cause errors.

libhio: remove autoreconf method

---

var/spack/repos/builtin/packages/py-torch/package.py

This PR gets the py-torch package to build with caffe2, and closes #14576. If building on a machine with CUDA but no GPU the build
will try to build with all compute capabilities. Older compute
capabilities are not supported so the build will fail. The list of
capabilities can be passed to the build using values set in the
cuda_arch variant. Likewise, conflicts are also set to catch if the
unsupported capabilities are listed in cuda_arch.
This PR also sets version constraints on using an external mkldnn for
newer versions. Currenly, only versions up to 0.4 use an external mkldnn
library. Also, the cuda variant is set to True, which restores
previous behavior.

Get py-torch to build caffe2

---

var/spack/repos/builtin/packages/z3/package.py

Configure z3+python to build the python libraries inside its own prefix and extend python as other packages do
Previously, z3 was installing it's python API into the python install prefix, which breaks Spack's fundamental model of separating installs into separate prefixes.

Package bugfix: z3+python

---

var/spack/repos/builtin/packages/vtk/package.py

This PR adds some extra dependencies needed for vtk-8.2.0. It also
handles the variable name changes to turn off some of the external
libraries.

Get vtk-8.2.0 to build

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/package.py

spack install command calls spack.package.try_install_from_binary_cache() which calls spack.binary_distribution.get_specs().
spack.binary_distribution.get_specs() was modified in
#13002
to allow listing and installing buildcaches for macOS on a linux host.
In the case where a mirror contains buildcaches for multiple OSes the spack install command can spend more time downloading all of the specs from the build_cache directory than it takes to install the buildcache. The is especially true when using pipelines and the buildcache download directory is cleared between steps.
I modified the get_specs() command to accept a filter option and pass the current OS as the filter option when get_specs() is called from spack.package.try_install_from_binary_cache()

When spack install checks for buildcaches only add urls for current arch

---

var/spack/repos/builtin/packages/simulationio/package.py

The HDF5 dependency bound was inverted. (How did this ever compile? There is a cmake check.)

simulationio: Correct HDF5 dependency bounds

---

var/spack/repos/builtin/packages/py-vermin/package.py

Successfully installs and passes all tests on macOS 10.15.2 with Python 3.7.6 and Clang 11.0.0.

Add py-vermin package

---

var/spack/repos/builtin/packages/py-pygdal/package.py

fix dependency version, add more versions. Fixes #14075

pygdal and gdal versions should be in lockstep

---

lib/spack/spack/cmd/list.py
lib/spack/spack/util/web.py

All of a sudden, all of our recent PRs have been failing the "python version check" GitHub action. It looks like a new, smarter version of vermin (0.10.0) was just released today, detecting new incompatible sections of code. Luckily all of these versions are guarded by `sys.version_info` checks or try-except blocks. This PR adds `# novm` to the lines that were causing the tests to fail.

Fix Python version compatibility tests for vermin 0.10.0

---

var/spack/repos/builtin/packages/amrex/package.py

Now using Github releases instead of git commits.

amrex: Update to version 20.01

---

lib/spack/spack/binary_distribution.py

Limit the specs downloaded by get_specs to those that match the os and platform.

Fix for bug introduced in pull request 14639

---

lib/spack/spack/database.py
lib/spack/spack/test/database.py

example of the issue: attempting to do a 'spack find' of a package
in an upstream database results in this cryptic error:
[aweits@skl-a-00 spack]$ spack find -Lv nccl
==> 1 installed package
-- linux-rhel7-x86_64 / gcc@7.4.0 -------------------------------
z63m54h4t53nvcvngbkjfpk2lm36ojea nccl@2.3.7-1
spack:/dev/shm/SPACK/spack
[aweits@skl-a-00 spack]$ spack find /z63m54h4t53nvcvngbkjfpk2lm36ojea
==> Error: Cannot access attribute 'acquire_read' of lock
[aweits@skl-a-00 spack]$ spack find nccl/z63m54h4h
==> Error: Cannot access attribute 'acquire_read' of lock

fix get_by_hash so that we don't attempt to lock an upstream database

---

lib/spack/docs/environments.rst

The example in the docs is incorrect -- spack env expects a subcommand:
```
$ spack env myenv loads -r
usage: spack env [-h] SUBCOMMAND ...
spack env: error: argument SUBCOMMAND: invalid choice: 'myenv' choose from:
activate  create  deactivate  list  loads  ls  remove  rm  st  status  view
```
I also have a question about the resulting `loads` script.  The docs cheerfully state: *This creates a file called loads in the environment directory. Sourcing that file in Bash will make the environment available to the user; and can be included in .bashrc files, etc.*
However, when I try to source the script on a vanilla Ubuntu 18.04 box, I get:
```
$ source path/to/spack/var/spack/environments/myenv/loads
module: command not found
module: command not found
module: command not found
module: …
```

fix spack env loads example

---

lib/spack/llnl/util/filesystem.py

Our exception handler currently raises an exception of its own when handling an error in a `filter_file` operation. Because the temp file is removed in the `finally` block, we should not remove it in the `except` block.
This removes the first call to remove the file, now the code reports the appropriate exception from `filter_file`

Fix handling of filter_file exceptions

---

lib/spack/docs/config_yaml.rst

This PR adds a note about segfaults with the Intel compiler when the
install paths are long and the dependencies many.

Note about Intel compiler segfault with long paths

---

var/spack/repos/builtin/packages/intel-tbb/package.py

Intel-TBB's libraries on Darwin are installed with "@rpath" prefixed to their install names. This was found to cause issues building the `root` package on Darwin due to libtbb not being found when running some of the generated tools linking to it.
Follow example from other packages with the same issue and fixup up install names for intel-tbb post install.

intel-tbb: Fix install names on Darwin

---

var/spack/repos/builtin/packages/med/add_space.patch
var/spack/repos/builtin/packages/med/package.py

error:
`invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]`
I added a space between literal and identifier at spots where error occured.

med: add a space between literal and identifier.

---

var/spack/repos/builtin/packages/powerapi/add_space.patch
var/spack/repos/builtin/packages/powerapi/package.py

error:
`invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]`
I added a space between literal and identifier at spots where error occured.

powerapi: add a space between literal and identifier.

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Replace the deprecated ADIOS1 backend default with ADIOS2 default.
Disable `sz` in ADIOS1 since we do not need it and it conflicts with supported version ranges between ADIOS2 and ADIOS1 if someone enables both.

openPMD-api: With ADIOS2 by Default

---

var/spack/repos/builtin/packages/graphite2/package.py
var/spack/repos/builtin/packages/graphite2/regparm.patch

This PR sets the definition of REGPARM when building with the Intel
compiler.

Build graphite2 with Intel compiler

---

var/spack/repos/builtin/packages/pcma/fix_return_type_err.patch
var/spack/repos/builtin/packages/pcma/package.py

- I set appropriate return value.
```
>> 30     interface.c:205:20: error: non-void function 'check_param' should r
eturn a value [-Wreturn-type]
31             if(args[0]==NULL) return;
32                               ^
```
```
>> 353    alcomp2.c:1741:22: error: non-void function 'read_alignment2int' sh
ould return a value [-Wreturn-type]
354    if (flag_errread==1) return;
355                         ^
```
- I fixed return type of function because there is no other processing to return a value in the function.
```
>> 439    alcomp2.c:3331:94: error: non-void function 'CompareAlnVsReferenceA
ln' should return a value [-Wreturn-type]
440            if (len_common1<=0 || len_common2<=0) {coverage1 = coverage
2 = accuracy1 = accuracy2 = 0.0; return;}
441 …
```

pcma: set return value and change return type of function

---

var/spack/repos/builtin/packages/racon/aarch64.patch
var/spack/repos/builtin/packages/racon/package.py

1. Add a patch for aarch64 platform.
It's confirmed by racon community with the issue:https://github.com/isovic/racon/issues/151
2. And new racon version with this code will make error:
`install_tree('spack-build/bin', prefix.bin)`
`install_tree('spack-build/lib', prefix.lib)`
I've tried all of the stable versions with this patch, they are work well.

racon: support aarch64 and fix install error

---

var/spack/repos/builtin/packages/netcdf-fortran/no_parallel_build.patch
var/spack/repos/builtin/packages/netcdf-fortran/package.py

This PR turns off parallel builds when the Intel compiler is used.
Builds with the Intel compiler will fail otherwise.

Set netcdf-fortran to build serially with Intel compiler

---

lib/spack/spack/cmd/add.py
lib/spack/spack/cmd/concretize.py
lib/spack/spack/cmd/install.py
lib/spack/spack/cmd/remove.py
lib/spack/spack/environment.py

This is a minimal set of edits to get parallel installs as implemented in https://github.com/spack/spack/pull/13100 working with environments.
What it currently does:
* adds a lock file for an environment that is stored in the environment directory
* adds `Environment.write_transaction`
* makes use of `Environment.write_transaction` in `cmd.install`
(UPDATE: now passing) ~One test is currently failing, which I think is an issue with the testing framwork vs. the actual logic (since I cannot manually reproduce the error when manually running through commands executed in the test).~
TODOs

Synchronized env update for install

---

var/spack/repos/builtin/packages/git/package.py

pcre2 became optional in 2.14 and the default in 2.18. I noticed this
as git was compiling against the system pcre2 (spack was
specifying pcre as the dependency).

git: add version 2.25.0 and fixup pcre dependency

---

lib/spack/spack/compilers/fj.py

There is required option when building OSS with Fujitsu compiler. We set it in the `compilers.yaml` until now, but I modified to be defined in the compiler source.

Fujitsu compiler: Defining option that is always added.

---

lib/spack/spack/test/cmd/create.py
lib/spack/spack/test/git_fetch.py
lib/spack/spack/test/install.py
lib/spack/spack/test/llnl/util/cpu.py
lib/spack/spack/test/llnl/util/filesystem.py
lib/spack/spack/test/stage.py

This commit makes two fundamental corrections to affected tests:
1) Changes `matches` to the correct `match` argument for `pytest.raises` (except tests checking for `SystemExit`);
2) Replaces the `match` argument for tests expecting `SystemExit` (since the exit code is retained instead) with `capsys` error message capture.
Both changes are needed to ensure the associated exception message is actually checked.

bugfix/tests:  Correct exception message matching

---

var/spack/repos/builtin/packages/py-pillow/package.py

In #14666, @aweits reported that the `py-pillow` tests are being run regardless of whether `--test=root` was requested. This PR fixes that.

Fix py-pillow tests

---

var/spack/repos/builtin/packages/fastx-toolkit/fix_pragma_pack.patch
var/spack/repos/builtin/packages/fastx-toolkit/package.py

I specified the scope of pragma pack because the following error occurred.
`error: the current #pragma pack aligment value is modified in the included file [-Werror,-Wpragma-pack]`

Fastx-toolkit: Specified the scope of pragma pack

---

var/spack/repos/builtin/packages/pumi/package.py

This PR adds support for ctest and the submodule containing the input files needed to run the tests.  It also adds a flag to control the simmetrix-simmodsuite version check which is useful for testing.

pumi: sim version check, meshes via submodule, ctest

---

lib/spack/spack/cmd/uninstall.py
lib/spack/spack/environment.py

* `Environment.__init__` is now synchronized with all writing operations
* `spack uninstall` now synchronizes its updates to any associated environment
* A side effect of this is that the environment is no longer updated piecemeal as specs are uninstalled - all specs are removed from the environment before they are uninstalled

Synchronize env reading and uninstall

---

lib/spack/spack/repo.py
lib/spack/spack/spec.py

Importing `package.py` files involves a lot of spec parsing, which currently takes the bulk of the time.  This `test.py` script:
```python
#!/usr/bin/env spack-python
import spack.repo
for name in spack.repo.all_package_names():
spack.repo.path.get_pkg_class(name)
```
takes ~8.5s on my machine on current `develop`.  With the changes included here, it takes 7.4s.  It's small but it makes a difference when importing lots of files.  The new concretizer will import a lot of packages, so I'm trying to speed this up.

Faster spec parsing and imports

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/package.py
lib/spack/spack/test/cmd/buildcache.py
share/spack/spack-completion.bash

Further limit the number of spec files downloaded by spack install process when it looks for buildcaches. Use the package name or hash in a regex along with current platform and os to match urls for spec files before they are downloaded.

Limit the number of spec files downloaded to find matches for buildcaches

---

var/spack/repos/builtin/packages/lmod/package.py

The first sentence in the docstring has been separated in its own paragraph since some tools (e.g. module generation) will use that as a short description.

lmod: update version of lmod to v8.3, updated docstring

---

lib/spack/spack/environment.py

locate the environment lock in the hidden environment directory rather than the root of the environment

Bugfix: put environment lock in the right place

---

lib/spack/docs/packaging_guide.rst

Fixes #510
We haven't explicitly mentioned how to add conditional dependencies to a package in the documentation. This adds a section on how to do that.

Document how to add conditional dependencies

---

var/spack/repos/builtin/packages/py-pillow/package.py

Fixes a couple of issues with `py-pillow`:
Fixes #14506

py-pillow fixes

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/package.py

Add binary_distribution::get_spec which takes concretized spec.
Add binary_distribution::try_download_specs for downloading of spec.yaml files to cache.
get_spec is used by package::try_install_from_binary_cache to download only the spec.yaml
for the concretized spec if it exists.
This arose from a discussion with @eugeneswalke. Muliple pipelines write to the same build_cache and the index.html is not updating correctly when two processes content for writing index.html.  Buildcaches that are available are skipped by spack install because they don't have a link in index.html.

Bypass build_cache/index.html read when trying to download spec.yaml for concretized spec.

---

var/spack/repos/builtin/packages/superlu-dist/package.py

The `enable_openmp` is broken in some older version.

superlu-dist: enforce OpenMP=OFF

---

lib/spack/spack/main.py
lib/spack/spack/test/main.py

Closes #8119.
`spack -V` previously always returned the version of spack from `spack.spack_version`.  This gives us a general idea of what version users are on, but if they're on `develop` or on some branch, we have to ask more questions.
This PR makes `spack -V` check whether this instance of Spack is a git repository, and if it is, it appends useful information from `git describe --tags` to the version.  Specifically, it adds:
- number of commits since the last release tag
- abbreviated (but unique) commit hash
So, if you're on `develop` you might get something like this:
```console
$ spack -V
0.13.3-912-3519a1762
```
This means you're on commit 3519a1762, which is 912 commits ahead of the 0.13.3 release.
If you are on a release branch, or if you are using a tarball of Spack,
you'll get …

`spack -V` is more descriptive for dev branches

---

var/spack/repos/builtin/packages/diy/package.py

This PR fixes the DIY package, adding the proper MPI dependency.

Fixed DIY package missing MPI dependency

---

var/spack/repos/builtin/packages/libfabric/package.py

Fix from libfabric's git for 1.9.0.
Compiling C++ software against libfabric@1.9.0 doesn't work
without this patch.
See: https://github.com/ofiwg/libfabric/commit/2e95b0efd85fa8a3d814128e34ec57ffd357460e

[libfabric@1.9.0] Fix C++ header usage

---

var/spack/repos/builtin/packages/draco/d710-python2.patch
var/spack/repos/builtin/packages/draco/d710.patch
var/spack/repos/builtin/packages/draco/d730.patch
var/spack/repos/builtin/packages/draco/d740.patch
var/spack/repos/builtin/packages/draco/package.py

+ Added versions 7.3.0 and 7.4.0.
+ Change several variants to be default TRUE since most consumers need these variants enabled (eospac, lapack, parmetis, superlu-dist). Change variant name for `+superlu_dist` to use hyphen instead of underscore.  This makes the variant name consistent with the spackage name for `superlu-dist`.
+ Clean up `depends_on` instructions and avoid specifying `type` when possible.
+ Provide patch files that are necessary for some machines (mostly Cray machines).

draco: update versions

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/packaging.py

Initializing _cached_specs every time binary_distribution::try_download_specs was called broke the install of cached dependencies because only the first one was placed in the cache. Move the initialization to the module level and only skip checking the mirrors if the spec exists in _cached_specs.

binary_distribution:  Initialize  _cached_specs  at the module level and only search the mirrors in get_spec if spec is not in _cached_specs.

---

var/spack/repos/builtin/packages/dealii/package.py

Without this patch, it looks like deal.II will not be able to be built with the latest versions on Intel TBB.

deal.II: Add patch for TBB version check

---

var/spack/repos/builtin/packages/cmake/package.py
var/spack/repos/builtin/packages/libarchive/package.py

CMake since 3.15.3 requires libarchive 3.3.3 (previously it was 3.1.0).
This PR add the latest libarchive version and fixes the dependency in CMake.
Reference:
- https://github.com/Kitware/CMake/commit/752fa8be9d410907e1ecb80a6a21daacd1a666f9
- https://github.com/Kitware/CMake/blob/v3.15.2/CMakeLists.txt#L514
- https://github.com/Kitware/CMake/blob/v3.15.3/CMakeLists.txt#L514

Fix CMake and update libarchive

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/test/cmd/buildcache.py
share/spack/spack-completion.bash

buildcache list: restore original behavior of allowing constraints on command line

---

var/spack/repos/builtin/packages/octave/helloworld.cc
var/spack/repos/builtin/packages/octave/package.py

fixes #14702 
fixes #4874
This PR patches `mkoctfile.in.cc` so that the real compilers are used instead of Spack compiler wrappers. The result is:
```console
$ mkoctfile -p CC
/usr/bin/gcc-9
$ strings ./mkoctfile | grep spack
/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/octave-5.1.0-udv3gkc3pqwvh3zgvk3dxrxqyw7iiydb/lib:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/octave-5.1.0-udv3gkc3pqwvh3zgvk3dxrxqyw7iiydb/lib64:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/openblas-0.3.7-uokct4hhjbmvuwjhv6f27jyzgnaartl2/lib:/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/pcre-8.42-gbithje7unewjy3vr4xm3nxwy5t623yt/lib:/home/culpo/PycharmProjects/spack/opt/spack/l …
```

octave: mkoctfile doesn't use compiler wrappers

---

var/spack/repos/builtin/packages/pmdk/package.py
var/spack/repos/builtin/packages/pmdk/pmem-1.8-disable-docs.patch

new upstream release
- notable in that it has experimental powerpc-le support (e.g. summit)
- required a new patch to disable documentation

update pmdk to 1.8

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/fetch_strategy.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/git_fetch.py
var/spack/repos/builtin/packages/py-torch/package.py

adds the 'submodules_delete' parameter to git versioning so that a
submodule can be removed from the repo.

py-torch: allow v0.4.1 to build despite missing nervanagpu repo

---

var/spack/repos/builtin/packages/pythia8/package.py

* Add a few old versions (some of which are needed by us).
* Building pythia8 needs rsync.

[pythia8] Old versions, build depend on rsync

---

var/spack/repos/builtin/packages/abinit/package.py

fixes #14578
Abinit's recipe requires double precision FFTW libraries for linking.

abinit: fix dependency on fftw

---

var/spack/repos/builtin/packages/mariadb/package.py

Leaving dtrace enabled causes build errors.

New version for mariadb and disable dtrace

---

var/spack/repos/builtin/packages/python/package.py

An intel-only patch added into spack was merged in to upstream python 3.7 and is fixed in 3.7.6.

Remove python patch for inapplicable versions

---

var/spack/repos/builtin/packages/libmng/package.py

The autoconf-based libmng package fails on intel, but all versions of the library spack include cmakelists, so use that instead.

Use CMake for libmng package

---

var/spack/repos/builtin/packages/openbabel/package.py

Actually installation fails as following (similar to #13637):
```shelsession
$ spack install openbabel
gettext@0.20.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-debian10-skylake
while trying to concretize the partial spec:
python@3.7.6%gcc@8.3.0+bz2+ctypes+dbm~debug~libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-debian10-skylake
^pkgconf@1.6.3%gcc@8.3.0 arch=linux-debian10-skylake
python requires gettext variant ~libxml2, but spec asked for +libxml2
```
But I hope this works.

Bump Open Babel to 3

---

var/spack/repos/builtin/packages/qt/package.py

Bad news @adamjstewart ... that last patch introduced a copy-paste error :( . Sorry about that. The perils of combinatorial build systems. I've tested that this fix works for gcc.

Fix QT@4 on GCC

---

var/spack/repos/builtin/packages/pumi/package.py

This PR adds PUMI version 2.2.2.
https://github.com/SCOREC/core/issues/290 has a description of the changes since 2.2.1 .

pumi: new version 2.2.2

---

var/spack/repos/builtin/packages/acts-core/package.py

Older versions require C++17 and newer ones force C++17 anyway. The build fails if root uses an older C++ standard.
@HadrienG2

acts-core: Fix build

---

var/spack/repos/builtin/packages/amdblis/package.py
var/spack/repos/builtin/packages/blis/package.py

The Blis package has been refactored to be able to reuse the build logic for the fork of the project optimized for AMD.

Added optimized version of Blis for AMD

---

lib/spack/llnl/util/cpu/microarchitectures.json

VSX alitvec extensions are supported by PowerISA from v2.06 (Power7+), but might
not be listed in features.
FMA has been supported by PowerISA since Power1, but might not be listed in
features.
This commit adds these features to all the power ISA family sets.

Adds fma and vsx features to entire power arch family.

---

lib/spack/spack/cmd/install.py
lib/spack/spack/package.py
share/spack/spack-completion.bash

When running `spack install` with `--with-cache` (which is the default)
and spack will try to verify all packages found in the buildcache.
If the buildcache contains unsigned packages it will fail at
`lib/spack/spack/binary_distribution.py:522`.
```python
NoVerifyException(
"Package spec file failed signature verification.\n"
"Use spack buildcache keys to download "
"and install a key for verification from the mirror.")
```
This commit introduces `--unsigned` for `spack install` so that unsigned
packages can be installed.

spack install --with-cache: Add --no-check-signature

---

var/spack/repos/builtin/packages/aws-parallelcluster/enum34.patch
var/spack/repos/builtin/packages/aws-parallelcluster/package.py
var/spack/repos/builtin/packages/py-enum34/package.py

When I try to run `pcluster configure` with Python 3.7.6, I get the following error:
```
$ pcluster configure
File "/Users/Adam/.spack/darwin/.spack-env/view/bin/pcluster", line 7, in <module>
from pkg_resources import load_entry_point
File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
@_call_aside
File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
f(*args, **kwargs)
File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File …
```

patch aws-parallelcluster so that it doesn't require enum34

---

var/spack/repos/builtin/packages/intel-tbb/makefile-debug.patch
var/spack/repos/builtin/packages/intel-tbb/package.py

Fixes #14850.  Commit 6b1958219 added versions 2020 and 2020.1 for
intel-tbb as part of updating several intel packages but added the
wrong sha256 sums for the github/01org repository.
Also, version 2020 is 2020, not 2020.0.
Add patch makefile-debug to restore the debug targets.
----------
Please double check my sha256 sums.  Just a simple wget for 2020 and
2020.1 to make sure these are the right sha256 sums for the
github/01org repo.
@robert-mijakovic Where did you get the sha256 sums?  Were they from a
professional version of TBB or something?  Anyway, I think these are
correct for github/01org.

intel-tbb: fix sha256 sums for 2020 versions

---

var/spack/repos/builtin/packages/r-fdb-infiniummethylation-hg19/package.py
var/spack/repos/builtin/packages/r-illuminahumanmethylation450kanno-ilmn12-hg19/package.py
var/spack/repos/builtin/packages/r-lumi/package.py
var/spack/repos/builtin/packages/r-matrixstats/package.py
var/spack/repos/builtin/packages/r-methylumi/package.py
var/spack/repos/builtin/packages/r-roc/package.py
var/spack/repos/builtin/packages/r-txdb-hsapiens-ucsc-hg19-knowngene/package.py
var/spack/repos/builtin/packages/r-watermelon/package.py

This PR creates the r-watermelon package, along with dependencies.
- new package: r-fdb-infiniummethylation-hg19
- new package: r-illuminahumanmethylation450kanno-ilmn12-hg19
- new package: r-lumi
- new package: r-methylumi
- new package: r-roc
- new package: r-txdb-hsapiens-ucsc-hg19-knowngene
- updated package: r-matrixstats, new version needed as a dependency

New package: r-watermelon

---

var/spack/repos/builtin/packages/vim/package.py

This PR will set the approriate library if ncurses is built with a
separate tinfo library.

Fix vim build with ^ncurses+termlib

---

var/spack/repos/builtin/packages/libedit/package.py

Fixes https://github.com/spack/spack/issues/14846
This new version of libedit can make use of an ncurses dependency built with `+termlib` (which moves some symbols into a separate `libtinfo`).

libedit package: add version 3.1-20191231

---

var/spack/repos/builtin/packages/precice/package.py

This PR adds
* version 2.0.0 of the xSDK member preCICE
* python3 dependency
* support for new CMake variables.

precice: add version 2.0.0

---

var/spack/repos/builtin/packages/qt/package.py

The previous incantation for QT platform detection worked for QT5 linux clang (see https://github.com/spack/spack/issues/13650) but apparently not for QT4 linux clang. I can now successfully compile QT 4.8.7 with clang 9, gcc 8, or intel 18 on linux.
I've also marked myself as a maintainer of QT since I have to deal with this 💩 package so much.

Fix QT4 platform detection for linux clang

---

var/spack/repos/builtin/packages/cpio/package.py
var/spack/repos/builtin/packages/intel-mkl/package.py

This PR adds a `cpio` package and makes it available during the build of `intel-mkl`.
Fixes #14855

Fix intel-mkl package

---

lib/spack/spack/main.py

- `git -C` doesn't work on git before 1.8.5
- `working_dir` gets us the same effect

bugfix: `spack -V` should use `working_dir()` instead of `git -C`

---

var/spack/repos/builtin/packages/r-truncdist/package.py

r-truncdist: new package at 1.0-2

---

var/spack/repos/builtin/packages/dd4hep/package.py
var/spack/repos/builtin/packages/dd4hep/tbb-workarounds.patch

This will allow current releases of DD4hep to build against current TBB releases provided by Spack, while waiting for [upstream patch integration](https://github.com/AIDASoft/DD4hep/pull/613).

[dd4hep] Make DDDigi work with current TBB releases

---

var/spack/repos/builtin/packages/root/README.md
var/spack/repos/builtin/packages/root/package.py

Since a `pythia8` package was contributed by @michaelkuhn in #14665, we can now expose Pythia 8 support in the ROOT package.

[root] Enable Pythia8 support

---

var/spack/repos/builtin/packages/warpx/package.py

WarpX removed the `dev` branch in favor of a simpler, `master`-centric development model.
`master` is the new development branch and there is no stable branch anymore (we use tags and release branches instead).
We intentionally do not tag other versions than the development branch yet.
Adding @dpgrote @remilehe @maxthevenet and me as package maintainers, too.

WarpX: master is the new develop

---

var/spack/repos/builtin/packages/openpmd-api/package.py

- fix a missing `env.` prefix in the build environment.
- rename development branch to same name as in git

openPMD-api: Build Env Fix & Dev

---

lib/spack/spack/cmd/python.py
lib/spack/spack/test/cmd/python.py
share/spack/spack-completion.bash

It's often useful to run a module with `python -m`, e.g.:
```console
$ python -m pyinstrument script.py
```
Running a python script this way was hard, though, as `spack python` did not have a similar `-m` option.  This PR adds a `-m` option to `spack python` so that we can do things like this:
```console
$ spack python -m pyinstrument ./test.py
```
This makes it easy to write a script that uses a small part of Spack and then profile it.  Previously thee easiest way to do this was to write a custom Spack command, which is often overkill.

spack python: add -m option to run modules as scripts

---

var/spack/repos/builtin/packages/macsio/cast.patch
var/spack/repos/builtin/packages/macsio/package.py

- Fix narrowing error
```
>> 84     /tmp/pytest-of-ogura/pytest-77/mock-stage0/spack-stage-macsio-1.1-b
oj45ykokozxfqahtdfktmn2yvpbmovq/spack-src/plugins/macsio_silo.c:709
:9: error: non-constant-expression cannot be narrowed from type 'in
t' to 'unsigned int' in initializer list [-Wc++11-narrowing]
85             JsonGetInt(main_obj, "clargs/exercise_scr")&0x1};
86             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I did typecast for `JsonGetInt` to 'unsigned int'.
I did the same fix as the reference.
・Ref: https://github.com/LLNL/MACSio/commit/51b8c40cd9813adec5dd4dd6cee948bb9ddb7ee1#diff-211e5531b37ad0c24fea756d482d80f9
I submitted this pull request to upstream.
・upstream: https://github.com/LLNL/MACSio/pull/20

macsio: cast JsonGetInt from int to unsigned int

---

var/spack/repos/builtin/packages/bmi/package.py

Package `bmi` currently has a non-explicit build dependency on `automake`. This PR makes the dependency explicit.
@carns @ax3l @scottwittenburg

bmi depends on automake for build

---

var/spack/repos/builtin/packages/hepmc/package.py

@HadrienG2 
See https://github.com/spack/spack/pull/14805#discussion_r378730176

hepmc: fixed wrong sha256 for latest versions

---

lib/spack/spack/relocate.py

As reported by @eugeneswalker call to relocate::is_file_relocatable throws an exception. In get_existing_elf_rpaths this exception is handled correctly. Replace direct call to patchelf with call to get_existing_elf_rpaths.
[pdt.txt](https://github.com/spack/spack/files/4199429/pdt.txt)

Replace direct call to patchelf with get_existing_elf_rpaths which handles exceptions.

---

var/spack/repos/builtin/packages/libcircle/package.py

Package `libcircle` currently has a non-explicit build dependency on `pkg-config`. This PR makes this build dependency explicit. @scottwittenburg @adammoody

libcircle depends on pkg-config for build

---

var/spack/repos/builtin/packages/unifyfs/package.py

UnifyFS no longer has an option to depend on numa. This removes the numa variant, dependency, and associated conflict.
This commit also
- renames the `pmpi` variant to the more appropriate `auto-mount`
- changes the preferred version to the most recent release

unifyfs: remove numa dependency

---

var/spack/repos/builtin/packages/intel-tbb/package.py

Starting with 2020, the tar files are named v2020.0.tar.gz,
v2020.1.tar.gz, etc, not 2020_U1.tar.gz.
https://github.com/intel/tbb/releases
The previous commit (7a10478708) fixed the checksum mismatch, but
didn't update url_for_version (my bad).
----------
Sorry I didn't notice the name change and fix url_for_version() in the
previous commit.  Intel provides the old names for compatibility, so
it looked like the old names were correct.  :-(
The contents of the two tar files (2020_U1.tar.gz and v2020.1.tar.gz)
are identical except for the top-level directory name.  But that's
enough to change the sha sum.
Better to adapt sooner rather than later I guess.
ping @tgamblin who reviewed the previous commit

intel-tbb: update to new tar file names for 2020 versions

---

var/spack/repos/builtin/packages/silo/package.py

The `<math.h>` implementation in libc++ distributed with clang@9 differs from the one in clang@8: it uses `#include_next` to include the system's `math.h`, which defines macros `DOMAIN` and `RANGE`. There are a few files in Silo that unwittingly use these macro-like names as type names. Since Silo has no public repo I can't submit a patch directly, but it looks like the upstream [fpzip library](https://github.com/LLNL/fpzip) is available and the [peccant source files have been fixed](https://github.com/LLNL/fpzip/blob/master/src/pcmap.h).
```
In file included from read.cpp:3:
In file included from ./pcdecoder.h:5:
./pcmap.h:17:13: error: expected member name or ';' after declaration
specifiers
typedef T DOMAIN;
~~~~~~~~~ ^
/usr/include/math.h:335:18: note: expanded from macro 'DOMAIN'
\# …
```

Fix Silo build on %clang@9

---

var/spack/repos/builtin/packages/r-rhtslib/find_deps-1.12.patch
var/spack/repos/builtin/packages/r-rhtslib/find_deps-1.16.patch
var/spack/repos/builtin/packages/r-rhtslib/package.py
var/spack/repos/builtin/packages/r-rhtslib/use_spack_Makeconf.patch
var/spack/repos/builtin/packages/r-rsamtools/package.py

This PR adds an updated version to the r-rhtslib package as well as fix
the build.
- add patches to use compiler flags from R
- add variables for bzip2 and xz dependencies
- use the spack Makeconf file when building the in-tree htslib
- make patchelf available to allow R to remove reference to temporary
installation directory in htslib shared object
- Add new version of r-rsamtools as the r-rsamtools and r-rhtlib
packages are closely paired.

Update and fix the r-rhtslib package

---

var/spack/repos/builtin/packages/r-fdb-infiniummethylation-hg18/package.py
var/spack/repos/builtin/packages/r-txdb-hsapiens-ucsc-hg18-knowngene/package.py

This PR adds the r-fdb-infiniummethylation-hg18 package and the needed
dependency of r-txdb-hsapiens-ucsc-hg18-knowngene.

New package: r-fdb-infiniummethylation-hg18

---

var/spack/repos/builtin/packages/rsync/package.py

popt and zlib are available as spack packages.
So use them instead of building internal ones.

[rsync] Use popt and zlib

---

var/spack/repos/builtin/packages/openblas/package.py

Add the OpenBLAS variant `+consistentFPCSR`, by default `False`, which adds the compile definition `CONSISTENT_FPCSR=1` as documented in  OpenBLAS `Makefile.rule`.

openblas: add variant +consistentFPCSR

---

share/spack/setup-env.sh

Fixes part of #14560 
The procfs tests were ~unreliable~ too reliable, as it was detecting `zsh5` instead of `zsh` on Travis.

Fix shell detection: zsh5 -> zsh

---

var/spack/repos/builtin/packages/python/package.py

Not clearing `PYTHONPATH` from intel compiler modules loaded by default (which also define a `PYTHONPATH` and `PYTHONHOME`) causes the following error (similar error on linux) : https://bugs.python.org/issue27054
@adamjstewart

Intel compiler: fix env vars before install

---

lib/spack/docs/build_settings.rst

While reading the documentation I stumbled across the following in the `build_settings.rst`:
```yaml
packages:
openmpi:
paths:
openmpi@1.4.3%gcc@4.4.7 arch=linux-x86_64-debian7: /opt/openmpi-1.4.3
```
The existing examples on that page swapped architecture and operating system for the `arch=`. I believe it should appear as `arch=linux-debian7-x86_64`?

Update target arch in build settings documentation examples

---

var/spack/repos/builtin/packages/cuda/package.py

Installing `cuda` in, e.g., a container that does not have `libxml2` installed revealed this issue:
```
[ubuntu] ~: spack install cuda
==> Installing cuda
==> Searching for binary cache of cuda
==> No binary for cuda found: installing from source
==> Fetching http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run
################################################################################################################################################################################################################################## 100.0%
==> Staging unexpanded archive /tmp/root/spack-stage/spack-stage-cuda-10.2.89-3pzuxaqcsscqhzwfnkbpc2oi2xujokut/cuda_10.2.89_440.33.01_linux.run in …
```

cuda: add libxml2 as a dependency

---

lib/spack/spack/config.py
lib/spack/spack/schema/hardware.py
lib/spack/spack/schema/merged.py
lib/spack/spack/test/schema.py

For cross-compilation, we are adding an optional `hardware.yaml` config file, which can be used to describe the types of target environments available on the system.  Currently this includes the microarchitecture target (`target`) and the OS running on each node (`operating_system`).
For example, on Fugaku, we might use the following hardware.yaml to describe the machine's nodes:
```yaml
hardware:
nodes:
- node:
name: backend
operating_system: centos8
target: cascadelake
- node:
name: backend2
operating_system: rhel8
target: a64fx
```
Other properties, e.g., an optional `sysroot`, or a section describing available networks, can come later.  We expect that this file might also contain hints for setting default values of variants (e.g. you could ask what network fabrics are available on …

config: add initial hardware.yaml schema

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/test/packaging.py

* install_tree copies hardlinked files
* tarfile creates hardlinked files on extraction.
* create a temporary tarfile from prefix and extract it to workdir

Buildcache creation/extraction use temp tarfile to preserve hardlinks during copy to/from prefix.

---

var/spack/repos/builtin/packages/r-readbitmap/package.py

This PR corrects the jpeg dependency in r-readbitmap to use the jpeg
virtual dependency.

package r-readbitmap Change jpeg dependency

---

var/spack/repos/builtin/packages/libmng/package.py

Libmng only needs gzip to compress man files for distribution, so it
builds fine without it. The spack
gzip currently fails to compile.
```
config.status: linking /var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/spack-stage/s3j/spack-stage-gzip-1.10-iatwtuk2l5xgwmuh4pwu5bf27yezpydj/spack-src/GNUmakefile to GNUmakefile
config.status: executing depfiles commands
==> Executing phase: 'build'
==> [2020-02-14-09:32:45.502913] 'make' '-j12'
make: GNUmakefile: Too many levels of symbolic links
make: stat: GNUmakefile: Too many levels of symbolic links
make: *** No rule to make target `GNUmakefile'.  Stop.
```

Remove unneeded dependency on gzip for libmng

---

var/spack/repos/builtin/packages/gzip/package.py

At least on mac systems (perhaps because of a case sensitivity issue?)
gzip fails to build inside the source tree:
```
config.status: linking /var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/spack-stage/s3j/spack-stage-gzip-1.10-iatwtuk2l5xgwmuh4pwu5bf27yezpydj/spack-src/GNUmakefile to GNUmakefile
config.status: executing depfiles commands
==> Executing phase: 'build'
==> [2020-02-14-09:32:45.502913] 'make' '-j12'
make: GNUmakefile: Too many levels of symbolic links
make: stat: GNUmakefile: Too many levels of symbolic links
make: *** No rule to make target `GNUmakefile'.  Stop.
```

Use separate build directory for gzip

---

var/spack/repos/builtin/packages/boost/package.py

We should check whether `with_libs` is empty after making version-specific modifications to it. Otherwise, we might get an empty value for the `--with-libraries` argument of `bootstrap.sh`, and compile all the libraries instead of getting a header-only installation.

Fix header-only installation of Boost

---

var/spack/repos/builtin/packages/libnrm/package.py

Package `libnrm` currently has a non-explicit build dependency on `pkgconfig`. This PR makes this build dependency explicit. @freuk @scheibelp @scottwittenburg

libnrm depends on pkg-config for build

---

var/spack/repos/builtin/packages/cmake/package.py

If one runs `spack install cmake` inside ctest, then cmake sometimes fails to install properly.
Fixes:
1. Improve environment cleaning: Remove `$DASHBOARD_TEST_FROM_CTEST`
2. Add `-DCMake_TEST_INSTALL=OFF` to `bootstrap_args()`
Both alone would fix the issue, but it seems more sensible to apply them together: Cleaning the environment is anyway a good idea and passing explicit options seems good too.

cmake: Fix spack install inside ctest

---

var/spack/repos/builtin/packages/libcircle/package.py

Change package `libcircle` so that it depends on a provider of pkgconfig, as opposed to specifically requiring pkg-config. @adammoody @adamjstewart

libcircle depends on a provider of pkgconfig for build

---

lib/spack/spack/cmd/extensions.py
lib/spack/spack/test/cmd/extensions.py
share/spack/bash/spack-completion.in
share/spack/spack-completion.bash

Closes #1356
This behavior is modeled after the `spack providers` command, which prints a list of valid virtual packages if no argument is supplied. Its intended use is for Spack's shell tab completion scripts.
This command is currently slower than I would like for tab completion, so if there are any ways to speed it up let me know.

spack extensions prints list of extendable packages

---

var/spack/repos/builtin/packages/clhep/package.py

It looks like the CLHEP fetch url has changed:
```
==> Fetching http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.4.1.2.tgz
-#O#-  #    #
curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.4.1.2.tgz
URL http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.4.1.2.tgz was not found!
==> Fetching from http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.4.1.2.tgz failed.
==> Cannot find version 2.4.1.2 in url_list
==> Error: FetchError: All fetchers failed for spack-stage-clhep-2.4.1.2-27z42fmkngktzmf6gde6incbg4y5xwx2
```
I'm updating based on the [official clhep download …

Update CLHEP fetch URL and version

---

var/spack/repos/builtin/packages/pegtl/change_to_virtual_destructor.patch
var/spack/repos/builtin/packages/pegtl/package.py

- error
```
>> 1084    /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.
8.5/ext/new_allocator.h:124:29: error: destructor called on non-fi
nal 'examples::string_json' that has virtual functions but non-vir
tual destructor [-Werror,-Wdelete-non-virtual-dtor]
1085            destroy(_Up* __p) { __p->~_Up(); }
1086                                ^
```
I changed destructor to virtual destructor.
Ref: https://github.com/taocpp/PEGTL/commit/340110292b35d367205953a59e7eab28e1f4a0bb#diff-1273613920dbf566d89ea5cf50609053

pegtl: change to virtual destructor

---

var/spack/repos/builtin/packages/hdf5/package.py

The argument 'buf_size' of the C function 'h5fget_file_image_c' is declared as intent(in) in its interface block in 'H5Fff.F90' or 'H5Fff_F03.f90' though it is modified by the invocation. As a result, aggressive compilers such as Fujitsu's may do a wrong optimization to generate a wrong result, and a test during the installation fails. So, 'buf_size' should be declared as intent(out).
Note: This fix should be temporal and the bug should be fixed by the developer. I'll report it to them.

an argument 'buf_size' of 'h5fget_file_image_c' should be intent(out).

---

var/spack/repos/builtin/packages/davix/package.py
var/spack/repos/builtin/packages/root/package.py

Adds latest version of DaviX toolkit and adds a version requirement from ROOT.
```
-- Checking for module 'davix>=0.6.4'
--   Found davix, version 0.6.8
CMake Warning at cmake/modules/SearchInstalledSoftware.cmake:960 (message):
Davix versions 0.6.8 to 0.7.0 have a bug and do not work with ROOT, please
upgrade to 0.7.1 or later.
```

Update davix and ROOT version requirement

---

lib/spack/spack/test/ci.py
lib/spack/spack/test/cmd/ci.py
lib/spack/spack/test/cmd/gpg.py
lib/spack/spack/test/packaging.py

Since #14594 there are tests that fail when no gpg executable is present. This PR skips those tests in that circumstance.

skip gpg tests when no gpg executable

---

var/spack/repos/builtin/packages/ross/package.py

And 'master' and 'develop' versions to properly match branches.

ROSS: v7.2.0

---

lib/spack/spack/binary_distribution.py

In https://github.com/spack/spack/pull/15003 the compression of the tarfile was changed from gzip to bzip2 without accounting for older buildcaches which contain tar.gz files instead of tar.bz2 files. This fixes the problem.

buildcache: Check for tar.bz2 and set tar.gz if not found

---

var/spack/repos/builtin/packages/julia/package.py

The current Spack Julia package potentially installs a few julia
packages, with the installation being controlled by variants. There are
a couple of problems with this.
First, Julia handles packages very differently from systems such as R
and Python. Julia requires write access to the repository directories in
order for user installs of packages to work. If spack installs julia
packages then there will be a repository, DEPOT_PATH, in the
installation directory. If spack is used on an individual basis this
would work but would mean that package data is written to the spack
installation directory after installation. If spack is used to provide
packages for end users then user installs of julia packages will fail
due to lack of write access to the repository in the installation
directory. It …

Update and simplify julia package

---

var/spack/repos/builtin/packages/slate/package.py

Package `slate` needs mercurial.

slate needs mercurial

---

var/spack/repos/builtin/packages/catch2/package.py
var/spack/repos/builtin/packages/openpmd-api/package.py

* add a variant allowing catch2 to be installed
via CMake, which is useful for generating a .cmake
config file for consumption by other projects
This allows me to "just consume" the .cmake config files generated after:
`spack install catch2+use_cmake % gcc@7.4.0`
`spack load catch2`
I'm sure `spack` devs will want to make changes to this draft approach. I'll do what I can or feel free to push to the branch.

ENH: add catch2 CMake install

---

var/spack/repos/builtin/packages/modern-wheel/add_virtual_destructor.patch
var/spack/repos/builtin/packages/modern-wheel/package.py

- error
```
>> 99     /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8
.5/ext/new_allocator.h:124:29: error: destructor called on non-fina
l '(anonymous namespace)::DerivedSum' that has virtual functions bu
t non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
100            destroy(_Up* __p) { __p->~_Up(); }
101                                ^
```
All base classes with a virtual function should define a virtual destructor.
So I added virtual destructor to base class.

modern-wheel: add virtual destructor to BaseMultiParms class

---

var/spack/repos/builtin/packages/octave/package.py

Perform necessary actions [as described in the manual](https://octave.org/doc/v5.2.0/Compiling-Octave-with-64_002dbit-Indexing.html) to build Octave against BLAS implementations supporting 64-bit indices.

octave: enable 64-bit BLAS builds.

---

lib/spack/spack/relocate.py

This reproduces the behavior of spack.relocate.file_is_relocatable(patchelf) expected by test_patchelf_is_relocatable which was broken by
https://github.com/spack/spack/pull/14929

Buildcache: join rpaths returned by get_existing_elf_rpaths with ':'.

---

var/spack/repos/builtin/packages/gcc/package.py

This applies a homebrew patch (https://github.com/Homebrew/homebrew-core/pull/39041) to the spack-installed GCC for version 8.3.
---
Build error before this patch:
```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
from /var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/s3j/spack-stage/spack-stage-gcc-8.3.0-qif3yy4p3yh4vq5upji4bqu6l4w6hjww/spack-src/gcc/config/darwin-driver.c:30:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
_Atomic u_long          cr_ref;  /* reference count */
^~~~~~~
make[3]: *** [darwin-driver.o] Error 1
```

Fix gcc 8.3 build on macOS 10.14

---

lib/spack/spack/relocate.py

If the mimetype returned from `file -h -b --mime-type` contains slashes
in its subtype, the tuple returned from `spack.relocate.mime_type` will
have a size larger than two, which leads to errors.

Fix relocate.mime_type if slashes in subtype

---

var/spack/repos/builtin/packages/py-notebook/package.py

The py-setuptools dependency in py-notebook needs to be a run
dependency. The following message is received if it is not in the run
environment.
Traceback (most recent call last):  File "/opt/ssoft/apps/2020.1/linu
x-centos7-sandybridge/gcc-9.2.0/py-notebook-6.0.1-6usbn4c/bin/jupyter-notebook",
line 6, in <module>
from pkg_resources import load_entry_point
Module NotFoundError: No module named 'pkg_resources'

py-notebook: make py-setuptools a run dependency

---

var/spack/repos/builtin/packages/hpctoolkit/package.py

Change hpctoolkit's dependency on libunwind from 2018.10.12 to 1.4:.
In libunwind, 2018.10.12 is going away in favor of 1.4-rc1 (they're
nearly identical commits).
Remove the 'gpu' version.  This was a temporary branch that is now
folded into master.

hpctoolkit: adjust libunwind dependency

---

lib/spack/llnl/util/filesystem.py

Sometimes one needs to preserve the (relative order) of mtimes on installed files.  So it's better to just copy over all the metadata from the source tree to the install tree. If permissions need fixing, that will be done anyway afterwards.
One major use case are resource()s: They're unpacked in one place and then copied to their final place using install_tree(). If the resource is a source tree using autoconf/automake, resetting mtimes uncorrectly might force unwanted autoconf/etc calls.

Use shutil.copy2 in install_tree

---

var/spack/repos/builtin/packages/binutils/package.py
var/spack/repos/builtin/packages/gcc/package.py
var/spack/repos/builtin/packages/llvm/package.py

When binutils builds on macOS, it omits `ld` and other key components. Additionally, `gcc+binutils %clang` sends invalid arguments to the linker since it assumes it's being built with GCC. This MR:
- marks `binutils+gold` as conflicting with `platform=darwin` since `ld.gold` doesn't actually get built in this case;
- marks `gcc+binutils` on darwin as well, for the same reasons
- marks `gcc+binutils+nvptx` as conflicting since `+binutils` requires bootstrapping and `+nvptx` explicitly disables it.
```
configure: error: C compiler cannot create executables
See `config.log' for more details.
checking for C compiler default output file name... checking for suffix of object files... checking for C compiler default output file name... make[2]: *** [configure-stage1-libdecnumber] Error 77
``` …

Mark binutils-related conflicts

---

lib/spack/spack/concretize.py
lib/spack/spack/test/concretize.py

fixes #14730
fixes #8735
Spack now requires an exact match of the compiler version requested by the user. A loose constraint can be given to Spack by using a version range instead of a concrete version (e.g. `4.5:` instead of `4.5`).

Compilers require an exact match on version during concretization

---

lib/spack/spack/test/packages.py
lib/spack/spack/util/package_hash.py
var/spack/repos/builtin.mock/packages/hash-test4/package.py

Fixes: https://github.com/spack/spack/issues/14735
Fixes: #15079 
When checking if a function call is a directive, add a preliminary check to ensure that the name of the function is available in the AST (this is always true for directives, so we can return `False` if the function call doesn't have a name).
The check for directives was tripping over logic added to `py-pillow`:
```
run_after('install')(PythonPackage.sanity_check_prefix)
```
the hashing logic was checking the names of function calls. But this particular function call (i.e. `...(PythonPackage.sanity_check_prefix)`) doesn't have a name (or at least it doesn't have a name that can be determined by examining the AST); that will always be true for directives.
TODOs:

Package hashing: fix detection of directives

---

lib/spack/spack/installer.py
lib/spack/spack/test/installer.py

Restore `package.py`-related changes lost from #11107 due to moving the associated functions to `installer.py`.
TODO:

Restore package-related unsigned binary changes from PR 11107

---

var/spack/repos/builtin/packages/qmcpack/package.py
var/spack/repos/builtin/packages/quantum-espresso/package.py

In order to support the QMCPACK dependency patching of QE, a new QE variant is needed that suppressed the internal patching of the Spack QE package.

QE+QMCPACK Converter Update February 2020

---

var/spack/repos/builtin/packages/pdt/package.py

Add ability to build with clang compiler. Tested and working on
Power9, Red Hat Enterprise Linux Server release 7.6 (Maipo)
x86, Ubuntu 19.04
aarch64, Ubuntu 19.04
with `clang@8.0.X`.
Pinging @khuck

pdt: Add clang compiler

---

var/spack/repos/builtin/packages/raja/package.py

Updating the raja versions so I can use the newest raja features.
It would be really nice if spack had something like [uscan](https://manpages.debian.org/buster/devscripts/uscan.1.en.html) in debian to automatically add new versions to the package as they become available.

Added additional raja versions

---

lib/spack/spack/compilers/__init__.py
lib/spack/spack/test/compilers.py

fixes #14798
fixes #13733
Compiler specifications require a generic architecture family as their target. This commit improves the error message that is displayed to users if they edit `compilers.yaml` and use an overly specific name.

Emit a sensible error message if compiler's target is overly specific

---

var/spack/repos/builtin/packages/llvm/package.py

Newer versions of LLVM provide a one-line command to set up LLDB code
signing. Now the build will abort only if this command fails.
https://lldb.llvm.org/resources/build.html#code-signing-on-macos
See https://github.com/spack/spack/pull/7012 , closes https://github.com/spack/spack/issues/3215

Automatically run LLDB codesign script on mac

---

var/spack/repos/builtin/packages/silo/package.py

I don't think `silo+silex` has ever compiled correctly before now. With this fix I can successfully build on my mac (and so it's even more likely to build on windows).
- Restrict to QT4
- Specify QT libs so `autoconf` doesn't default to choosing the alphabetical first library (libqt3support)
- Specify x11 lib and includes
- Add another general missing dependency on readline
Fixes https://github.com/spack/spack/issues/5154

Fix silex build 

---

lib/spack/spack/cmd/create.py

A generic python dependency is already added implicitly by the PythonPackage class.

create: Mention that python dependency does not have to be added

---

var/spack/repos/builtin/packages/sz/package.py

The newer versions of SZ now uses CMake to build.  Also support the options included in the cmake build.  I've already talked to @disheng222 about these changes.

sz: update to version 2.1.8.1

---

lib/spack/spack/installer.py
lib/spack/spack/modules/common.py
lib/spack/spack/package.py
lib/spack/spack/test/install.py

This change fixes (at least) two problems:
1. proj uses its stage directory during configure_args. However, configure_options does not set up the stage, leading to OSErrors about the stage directory (see #10649). This change will lead to missing configure_args in such cases but allows regenerating the module file and avoids needlessy setting up fake stages during refresh.
2. libxml2 uses global variables exported by python. Again, configure_options does not set up the environment appropriately, leading to NameErrors (see #10716). In addition to ignoring NameErrors, this change will set up the package environment so global variables can be found during refresh.
Fixes #10649, #10716
closes #14361

module: Fix various errors during refresh

---

lib/spack/spack/cmd/load.py

args.specs is a list, which results in output like this:
```
eval `spack load --sh ['libxml2', 'xz']`
```
We want this instead:
```
eval `spack load --sh libxml2 xz`
```

cmd/load: Fix usage output

---

var/spack/repos/builtin/packages/openfoam/package.py

Cast the target family to string for comparison. Was causing issues with IA64 not being a recognized target.
Discussed with @olesenm

Update of OpenFOAM package.py

---

var/spack/repos/builtin/packages/tau/package.py

2 changes:
1) Adding ADIOS2 and SQLite3 output support to TAU.  Also fixing MPI include and library paths.
2) Setup package to use MPI the way Spack recommends, and remove extra -iowrapper option from configure.

Updates to TAU package

---

lib/spack/spack/cmd/buildcache.py
share/spack/spack-completion.bash

This allows get_specs to download spec for buildcaches from other OS. For example you can install macOS buildaches on linux (with the appropriate fake compiler entry for clang on macOS).

Buildcache cmd:  add install -o/--otherarch option for installing macOS buildcaches on linux

---

lib/spack/spack/cmd/buildcache.py
lib/spack/spack/test/cmd/buildcache.py
lib/spack/spack/util/web.py

Closes #15157 
Issue originally identified in #15090

remove catch-all exception handling in buildcache command

---

lib/spack/spack/modules/common.py
lib/spack/spack/test/data/modules/tcl/suffix.yaml
lib/spack/spack/test/modules/tcl.py

Consider a user that wants to mark CUDA-enabled modules with a `-cuda` suffix. To also account for libraries that use cuda-enabled MPI (perhaps to differentiate them from the same library that uses non-cuda MPI), they set their `modules.yaml` file to:
```yaml
modules:
enable::
- lmod
lmod:
all:
suffixes:
'+cuda': 'cuda'
'^mpi+cuda': 'cuda'
```
Although this creates non-conflicting module names for `foo ^mpi+cuda` and `foo ^mpi~cuda`, it gives `bar+cuda ^mpi+cuda` an suffix of `-cuda-cuda`.
This patch deduplicates module extensions so that the latter suffix will simplify to `-cuda`. It also sorts the suffixes to improve robustness.

Uniquify suffixes added to module names

---

var/spack/repos/builtin/packages/ncurses/package.py

Alternative to https://github.com/spack/spack/pull/14853 removes default conflict for LLVM and other ncurses-based packages. See https://github.com/spack/spack/issues/14793 .

Default to +termlib for ncurses to satisfy LLVM

---

var/spack/repos/builtin/packages/tau/package.py

SQLite shouldn't be enabled by default for TAU package
Also Adding conflict for SQLite and ADIOS2 for older TAU releases
Fixes #15227

Fix for #15227

---

lib/spack/spack/spec.py
lib/spack/spack/test/concretize_preferences.py

Fixes #15219
The new build process, introduced in #13100 , relies on a spec's dependents in addition to their dependencies.  Loading a spec from a `yaml` file was not initializing the dependents.  This PR corrects that oversight.

bugfix:  Add dependents when initialize spec from yaml

---

var/spack/repos/builtin/packages/aws-parallelcluster/package.py

Signed-off-by: Luca Carrogu carrogu@amazon.com

Update AWS ParallelCluster to version 2.6.0

---

var/spack/repos/builtin/packages/arpack-ng/package.py

Details about ILP64 support: `INTERFACE64=1` are described on the [ARPACK-NG GitHub website](https://github.com/opencollab/arpack-ng).

arpack-ng: ILP64 support

---

lib/spack/docs/packaging_guide.rst

Docs: "spack env" is in the meantime called "spack build-env"

---

var/spack/repos/builtin/packages/go/package.py

Adds the 1.14 version recently released: https://gitlab.com/ecp-ci/hpc-executor/container_registry

Added go 1.14

---

lib/spack/spack/build_systems/cuda.py

@eugeneswalker pointed out that many common CUDA architectures, like Tesla K80 (3.7) weren't supported by our CudaPackage base class. This PR adds all possible CUDA architectures and more specific supported versions of CUDA.
I wasn't sure what to do about older versions of CUDA and compiler conflicts. Maybe @ax3l can point me in the right direction? It seems like info for older versions of CUDA is sparse though. I feel like a lot of this compiler conflict stuff should actually be moved to the `cuda` package, not this base class. Thoughts?
P.S. Is anyone interested in being an official maintainer for `CudaPackage`? I think it would be overridden by any package that extends this base class and sets `maintainers`, but it would be nice to have someone official to manage this stuff.
@svenevs …

CudaPackage: add support for Tesla K80 and older CUDA

---

etc/spack/defaults/config.yaml
lib/spack/spack/config.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/schema/config.py
var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/jdk/package.py
var/spack/repos/builtin/packages/libffi/package.py

download_timeout can be used to increase the time Spack waits for the server to answer. This can be used to work around slow servers.
Fixes #14700

config: Add a new option download_timeout

---

var/spack/repos/builtin/packages/xcfun/package.py

Recipe for the [XCFun](https://xcfun.readthedocs.io/en/latest/) library for arbitrary order derivatives of exchange-correlation kernel used in density-functional theory.
Co-maintainer: @bast

XCFun: New package.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build_error.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/linux_build_tests.yaml

This PR makes a few minor improvements to issue templates:

Advice to users are hidden when rendering issue templates

---

var/spack/repos/builtin/packages/umpire/package.py

This is useful if you need to link to a C code and you're using a compiler suite that doesn't support fortran.

Adding an option to build the C api for Umpire.

---

var/spack/repos/builtin/packages/trilinos/fix_clang_errors_12_18_1.patch
var/spack/repos/builtin/packages/trilinos/package.py

Also fix a build error that occurs when using an old compiler.

Update Trilinos: Add Mesquite as optional package

---

var/spack/repos/builtin/packages/py-pyfftw/package.py

Hi all,
This small PR allows **pyfftw** version 0.12.0 to be fetched/pulled in order to fix #15218.
---
1. macOS Catalina - %clang@11.0.0-apple (but with gcc@9.2.0 fortran compilers - see compilers.yaml below)
2. spack installed python (@3.7.6)
3. spack installed py-scipy (@1.4.1)
4. spack installed py-pfftw (@0.11.1)
5. spack commit 
```console
$ git rev-parse HEAD
f7d13b4779dd3caa8046ff92a07342bdbccb2969
```

Added version 0.12.0 to py-pyfftw

---

var/spack/repos/builtin/packages/py-ipython/package.py
var/spack/repos/builtin/packages/py-ipywidgets/package.py
var/spack/repos/builtin/packages/py-jupyter-console/package.py
var/spack/repos/builtin/packages/py-pyqt5/package.py
var/spack/repos/builtin/packages/py-qtconsole/package.py

This PR fixes a few things for some jupyter related packages.
py-ipython:
- make the python depends_on statements reflect needs of different
versions
- remove an unneeded conflicts directive
py-ipywidgets:
- add new version
- set version constraints for py-widgetsnbextension
py-jupyter-console
- add new version
- set python dependencies for versions as needed
- set version constraint for py-ipython
- set version constraints for py-prompt-toolkit
py-pyqt5
- build with py-sip
py-qtconsole
- add dependency on py-pyqt5

Fixups for jupyter

---

var/spack/repos/builtin/packages/unifyfs/package.py

Package `unifyfs` currently has a non-explicit dependency on `openssl`. This PR makes the dependency explicit.
@CamStan @tgamblin

unifyfs depends on openssl

---

var/spack/repos/builtin/packages/libfabric/package.py

See https://github.com/ofiwg/libfabric/issues/5339
Fixes https://github.com/spack/spack/issues/15244
Also reduced copy-paste of URLs with `url_for_version`.

Add new version of libfabric that builds on macOS

---

lib/spack/external/distro.py

@CreRecombinase can you check if this solves #15251 for you?
We need to upstream this to the `distro` project if it doesn't already exist in newer versions of `distro`.

Fix detection of redhat enterprise compute node

---

var/spack/repos/builtin/packages/ssht/float_conversion.patch
var/spack/repos/builtin/packages/ssht/package.py

- Tell make about the source code path
- Install actual header files, not a wrapper with wrong paths
- Add a patch to prevent compiler warnings
- Improve description
The first two of these changes are necessary to make the package build and install.

ssht: Correct recipe

---

var/spack/repos/builtin/packages/tree/package.py

- add version info for v1.8.0
- v1.8.0 adds a new source file, `file.c`, which need to be included
in our hardcoded list of objects to link.
I discovered this while demonstrating "how easy it is to add a new
package to Spack", only to scratch my head when it failed `spack
install` but worked when I ran `make` in the stage dir.  Finally
looked at tree/package.py and it All Became Clear.
Perhaps someone should rewrite this to use MakefilePackage, but the
Makefile starts off with a bunch of twisty turny "uncomment these
lines to run on this platform", so it might not be worth it.

Update tree for v1.8.0

---

var/spack/repos/builtin/packages/bowtie2/package.py
var/spack/repos/builtin/packages/exuberant-ctags/package.py
var/spack/repos/builtin/packages/perl-want/package.py
var/spack/repos/builtin/packages/samtools/package.py

This PR adds 'http://' to the homepage setting of a few packages that do
not have it set. Not having that set can cause problems with some wiki
apps when embedding the homepage value into markdown syntax.
- bowtie2
- exuberant-ctags
- perl-want
- samtools

Set http:// in homepage for a few packages

---

var/spack/repos/builtin/packages/libhio/package.py

libhio has been building it's own json.  With this change, libhio will rely on the json installed by spack.

libhio: specify use of external json

---

var/spack/repos/builtin/packages/caliper/package.py

The package needs to be told where to find it.

Caliper depends on python3.

---

var/spack/repos/builtin/packages/kallisto/package.py

Add version info for kallisto@0.46.2.
Versions of kallisto since 0.44.0 vendor a copy of htslib and kallisto's cmake bits generate a configure script for it using the auto* tools.  The std cmake args include `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`, which causes bits of the cmake verbose output to be embedded in the configure script.  This, in turn, wreaks havoc.
See  https://github.com/spack/spack/issues/15274 and https://github.com/pachterlab/kallisto/issues/253 for additional details.
Closes #15274

Update kallisto (with hackery on std_cmake_args)

---

var/spack/repos/builtin/packages/quantum-espresso/package.py

qe-6.5 fails to detect MKL for FFT if BLAS_LIBS is set due to
an unfortunate upsteam change in their autoconf/configure:
- qe-6.5/install/m4/x_ac_qe_blas.m4 only sets 'have_blas'
but no 'have_mkl' if BLAS_LIBS is set (which seems to be o.k.)
- however, qe-6.5/install/m4/x_ac_qe_fft.m4 in 6.5 unfortunately
relies on x_ac_qe_blas.m4 to detect MKL and set 'have_mkl'
- qe-5.4 up to 6.4.1 had a different logic and worked fine with
BLAS_LIBS being set
However, MKL is correctly picked up by qe-6.5 for BLAS and FFT if
MKLROOT is set (which SPACK does automatically for ^intel-mkl).
Thus, do not set BLAS_LIBS when compiling qe-6.5 with intel-mkl.
@naromero77 / @alalazo:
This PR has been split off from #15242 for separating distinct parts and easier merging.

Quantum-Espresso: qe-6.5 fails to detect MKL for FFT

---

var/spack/repos/builtin/packages/lastz/cast_signed_char.patch
var/spack/repos/builtin/packages/lastz/package.py

- error
```
>> 41    sequences.c:5089:3: error: comparison is always false due to limited
range of data type [-Werror=type-limits]
42       if (ch == EOF) goto failure;
43       ^
```
I did typecast for `ch` to 'signed char'.

lastz: cast from char to signed char

---

var/spack/repos/builtin/packages/tcsh/package.py

This PR adds some fixes for the tcsh package.
- Adds new version
- adds list_url so fetching works for current and old tarballs
- sets ncurses dependency explicitly to `ncurses+termlib`
If `+termlib` is not set then it will link against the system libtinfo.

Update tcsh package

---

var/spack/repos/builtin/packages/lastz/package.py

- `lastz` always uses only gnu compiler, so I fixed makefiles to use compile commands of specified compiler on Spack.

lastz: set compile commands for each compiler

---

var/spack/repos/builtin/packages/openblas/package.py

[OpenBLAS 0.3.9](https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.9) was released.

openblas: Add version 0.3.9.

---

lib/spack/spack/installer.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/installer.py

Fixes #15196 
The recent distributed build PR -- #13100 -- did not check the install status of dependencies when using the `--only package` option so would refuse to install a package with the claim that it had uninstalled dependencies whether that was the case or not.
This PR adds install status checks for the `--only package` case.

bugfix: ensure proper dependency handling for package-only installs

---

var/spack/repos/builtin/packages/tmux/package.py

Tmux tests for `setupterm` functionality in its configure script.
Our ncurses package provides terminfo functionality when built with
+termlib, which is the default.  That functionality is in a separate
library, called `libtinfo`. 
This ensures that ncurses is built to include termlib support and 
removes the override for the library location, trusting our pkg-config
to sniff it out.
All versions of tmux in its package definition built successfully on a CentOS box and ldd shows the binary was linked against spack libtinfo.
Additional details in: https://github.com/spack/spack/issues/15281
Closes #15281

Tmux should look for tinfo in -ltinfo

---

var/spack/repos/builtin/packages/suite-sparse/package.py

Newest suite-sparse versions also need separate make run to compile successfully

Suite sparse compilation fix for 5.7.0 and 5.7.1

---

var/spack/repos/builtin/packages/openmpi/nag_ltmain_1.patch
var/spack/repos/builtin/packages/openmpi/nag_ltmain_2.patch
var/spack/repos/builtin/packages/openmpi/nag_ltmain_3.patch
var/spack/repos/builtin/packages/openmpi/nag_ltmain_4.patch
var/spack/repos/builtin/packages/openmpi/package.py

This fixes the problem with NAG compiler for versions of OpenMPI that are based on Libtool 2.4.6. Versions that use older versions of Libtool need to be patched too but I assume that nobody is interested in them. The problem is reported upstream a year ago: https://github.com/open-mpi/ompi/pull/6378.

OpenMPI: patch for NAG.

---

var/spack/repos/builtin/packages/fairlogger/package.py

* `@develop` needs the full git repo to use `git describe` properly
* If not specifying the `cxxstd` variant, let cmake use its default
* Improve fmt dependencies: fairlogger < 1.6.2 does not work with fmt >= 6
* Small other stuff

fairlogger: add version, other improvements

---

var/spack/repos/builtin/packages/protobuf/package.py

and found when using the RelWithDebInfo build type.  Change protobuf
to only support Release and Debug build types.

Protobuf's cmake environment does not properly handle being exported

---

var/spack/repos/builtin/packages/elfutils/package.py

Increase the connect timeout for elfutils to 60 sec.  Elfutils (and
bzip2) tar files are on sourceware.org which is often slow to respond.
----------
In addition to bzip2, I've also sometimes had trouble with elfutils timing out,
as in #15212.  So the connection timeout is a welcome addition.
@michaelkuhn Is there a way to specify the fetch options once per package?
Or, is it necessary to add this for every version as in bzip2?

elfutils: increase connect timeout

---

var/spack/repos/builtin/packages/intel-xed/package.py

Fix intel-xed build error:
```
'./mfile.py' '--clean'
module 'platform' has no attribute 'linux_distribution'
```
`platform.linux_distribution` was deprecated in python 3.5 and removed in 3.8

intel-xed does not support python>3.7

---

lib/spack/env/cc
lib/spack/spack/build_systems/autotools.py

Spack's `fflags` are meant for both `f77` and `fc`. Therefore, they must to be passed as `FFLAGS` and `FCFLAGS` to the configure scripts of Autotools-based packages.

Set 'fflags' as FCFLAGS when the flags must be passed to Autotools.

---

var/spack/repos/builtin/packages/suite-sparse/package.py

fixes #15184
fixes #14654
fixes #10313

suite-sparse: fix installation for v5.X

---

var/spack/repos/builtin/packages/precice/package.py

This PR adds the version 2.0.1 of the preCICE coupling library (xSDK member).

precice: Add version 2.0.1

---

lib/spack/spack/relocate.py

use os.sep instead of null byte to pad replacement paths in binaries

---

lib/spack/spack/database.py

fixes #13122
Removed the code that was converting the old `index.yaml` format into `index.json`. Since the change happened in #2189 it should be considered safe to drop this (untested) code.

Remove DB conversion from index.yaml

---

var/spack/repos/builtin/packages/libfabric/package.py

Since 1.9.0 is broken for Darwin, which impacts many developers, and the fix is still a RC, let's keep the previous release as default.
This avoids disruption for OSX developers and CI.
(I think things should install with defaults on major platforms and should not require variant or dependency tweaks.)
Follow-up to #15254 #15244

libfabric: default 1.8.1

---

lib/spack/spack/relocate.py

This recovers the old behavior of replace_prefix_bin that was
modified to work with elf binaries by prefixing os.sep to new prefix
until length is the same as old prefix.

Add function replace_prefix_nullterm for use replacing mach-o rpaths on linux. 

---

var/spack/repos/builtin/packages/adios2/package.py

Add the python dependency and CMake hints when build with tests.
`spack install --test=root adios2`
ADIOS2 needs Python when:
- building python bindings and/or
- running tests

ADIOS2: Testing Depends on Python

---

var/spack/repos/builtin/packages/adios2/package.py

Rename branch version to supported, real development branch `master`. The old name is legacy Spack when alternative development branch names were not yet supported.
Use the already defined local variable `spec` to shorten lines.

ADIOS2: Cleanup, Development Branch Name

---

var/spack/repos/builtin/packages/py-matplotlib/package.py

Successfully builds on macOS 10.15.3 with Clang 11.0.0 and Python 3.7.6.

py-matplotlib: add 3.2.0

---

lib/spack/spack/installer.py
lib/spack/spack/test/installer.py

Testing the install `StopIteration` exception resulted in an attribute error:
```AttributeError: 'StopIteration' object has no attribute 'message'```
This PR adds a unit test and resolves that error.
Note that this work was originally part of #15237 but was pulled out to highlight that the change resolves a bug in the code.

bugfix: resolve StopIteration message attribute failure

---

lib/spack/spack/test/database.py
lib/spack/spack/test/installer.py
lib/spack/spack/test/llnl/util/lock.py

`pytest.raises` ignores `matches` arguments so this PR changes them to the proper argument, namely `match`.
Note these corrections were part of #15237 but have been separated since they address a separate issue.

testing:  Correct pytest.raises matches to match

---

var/spack/repos/builtin/packages/ripgrep/package.py

Add package for ripgrep:
ripgrep is a line-oriented search tool that recursively searches
your current directory for a regex pattern.  ripgrep is similar to
other popular search tools like The Silver Searcher, ack and grep.

New package: ripgrep

---

lib/spack/spack/binary_distribution.py

Add *.pub as a key suffix searched for in the links.

Allow buildcaches keys to find public keys on the e4s mirror

---

var/spack/repos/builtin/packages/unifyfs/auto-mount.patch
var/spack/repos/builtin/packages/unifyfs/package.py

UnifyFS had a bug with the `--enable-mpi-mount` config option, which corresponds to the `auto-mount` variant. This bug was fixed in the UnifyFS dev branch, however remains broken for the 0.9.0 version.
This adds a patch to the `unifyfs` package to fix the `auto-mount` variant when installing with version 0.9.0.
**Update:** the following paragraph is no longer valid.
This also removes the `openssl` dependency as `unifyfs` does not directly depend on it. This was said to be a non-explicit dependency in #15258, but I have been unable to duplicate this. However, if it is needed, it is likely a non-explicit dependency of one of unifyfs's dependencies and should be added there.
Fixes: #15292

unifyfs: add patch to fix #15292

---

var/spack/repos/builtin/packages/python/package.py

Closes #13256
It looks like 3.8.2 is significantly less buggy than 3.8.0. I was able to install NumPy with this version and it passed all tests with no issues. I think we should still keep Python 3.7 as preferred until Anaconda and Homebrew update to Python 3.8.
Successfully builds on macOS 10.15.3 with Clang 11.0.0.

Python: add 3.8.2

---

lib/spack/spack/cmd/test.py
lib/spack/spack/test/cmd/test.py
lib/spack/spack/test/llnl/util/log.py
pytest.ini
share/spack/qa/run-unit-tests

Moving `pytest.ini` to Spack's root folder since apparently moving to another folder during tests
causes `coverage` to output coverage files within `lib/spack/spack/test` with no coverage data.
Currently `spack test` can be run from any directory, but coverage will be correctly measured only if run from Spack's root folder.

Recover coverage from subprocesses during unit tests

---

lib/spack/spack/config.py
lib/spack/spack/test/config.py

Fixes #14416.
* Allows `spack.config.InternalConfigScope` and `spack.config.Configuration.set()` to handle keys with trailing ':' to indicate replacement vs merge behavior with respect to lower priority scopes.
* Lists may now be replaced rather than merged (this behavior was previously only available for dictionaries).
* Tests of the new behavior.
* In `spack.config._merge_yaml()`:
* New optional Boolean argument `override` for use in nested contexts.
* Minor logic improvements and simplification.

Allow ':' in key name to denote overrides for set() and override().

---

var/spack/repos/builtin/packages/munge/package.py

* Add version 0.5.14
* Add variant to allow setting the localstatedir: See below
* Add bzip2 dependency
* Add myself to maintainers (I just think, I can care for this package)
About localstatedir:
munge has a server and a client.
They communicate via unix domain sockets.
This socket is in PREFIX/var.
This package provides the client, the server, and development part (headers, libraries).
Let's assume one has the server part installed as a system package.  This generally is a good idea, so that the server gets started during boot. This means, that the socket is in the system's `/var`.
If one now wants to use the client part (library!) via spack, one has a problem: spack's munge looks in SPACK-PACKAGE-PREFIX/var for the socket.
There needs to be a way to let the spack installed package use …

munge: new version, local state path, misc

---

var/spack/repos/builtin/packages/cscope/package.py

I hope this fixes [issue 15355](https://github.com/spack/spack/issues/15355) and updates cscope.

Cscope: fix linking and update to v15.9

---

var/spack/repos/builtin/packages/caliper/package.py
var/spack/repos/builtin/packages/hpctoolkit/package.py
var/spack/repos/builtin/packages/libunwind/package.py

Finish cleaning up the libunwind version numbers.  The 2018.10.12
snapshot number didn't fit well with spack's ordering (my bad), and
1.4-rc1 is a near identical replacement.
Add a version for the 1.4-stable branch.
Add a variant for zlib compressed symbol tables (develop branch only).
Adjust packages caliper and hpctoolkit to adapt to the changes.
Add myself as maintainer.
----------
I grep'ed the package.py files and only caliper and hpctoolkit
mentioned 2018.10.12, so no other package should be affected.
@daboehme This is the (tiny) change to the caliper recipe that I told
you about last week.
For libunwind, 'stable' is at the low end of the spack ordering,
although based on the git repo, it should go 1.4 < stable < develop.
This is mildly inconvenient in some places.  For example, in …

libunwind: remove version 2018.10.12, add stable branch

---

var/spack/repos/builtin/packages/flatbuffers/package.py

Added a shared variant, that switches between shared and static library building, like with most cmake packages.

flatbuffers: Allow building shared libraries

---

lib/spack/spack/caches.py
lib/spack/spack/cmd/mirror.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/mirror.py
lib/spack/spack/package.py
lib/spack/spack/patch.py
lib/spack/spack/stage.py
lib/spack/spack/test/cmd/mirror.py
lib/spack/spack/test/mirror.py
share/spack/spack-completion.bash
var/spack/repos/builtin.mock/packages/trivial-pkg-with-valid-hash/package.py

Add a `--skip-unstable-versions` option to `spack mirror create` which forces the mirror to only add package sources/resources for archives with checksums. Other types of sources (e.g. fetched from a git repository) do not have a well-known checksum and for example would not be suitable for a public mirror.
TODOs:

Only use stable versions for public mirror

---

var/spack/repos/builtin/packages/pinentry/package.py

Successfully builds and passes all tests on macOS 10.15.3 with Clang 11.0.0.

pinentry: add new package

---

var/spack/repos/builtin/packages/libgpg-error/package.py

Successfully builds and passes all tests on macOS 10.15.3 with Clang 11.0.0.

libgpg-error: add 1.37

---

var/spack/repos/builtin/packages/libgcrypt/package.py

Successfully builds and passes all tests on macOS 10.15.3 with Clang 11.0.0.

libgcrypt: fix macOS tests

---

var/spack/repos/builtin/packages/gnupg/package.py

Successfully builds and passes all tests on macOS 10.15.3 with Clang 11.0.0.
Depends on #15387

gnupg: add 2.2.19, add missing pinentry dep

---

var/spack/repos/builtin/packages/libmesh/package.py
var/spack/repos/builtin/packages/opencv/package.py

ref: https://github.com/spack/spack/pull/15357
CC: @alalazo @adamjstewart 
I think I got them all, but maybe it would be good to have a second person fact check.  I was just grepping for `depends_on` piped to `grep -i eigen` and checking that `spack spec <pkg>+eigen` can concretize.  Prior to this you'll get an error.

eigen variants have been removed

---

var/spack/repos/builtin/packages/fast-global-file-status/package.py

fast-file-status is required openssl.
https://github.com/LLNL/FastGlobalFileStatus/blob/master/README line 50
But the dependency is missing.
This PR add openssl dependency.

fast-global-file-status: add openssl dependency.

---

var/spack/repos/builtin/packages/exiv2/package.py

exiv2 use zlib and expat.
https://github.com/Exiv2/exiv2#24-dependencies
But the dependencies are missing.
This PR is added the dependencies.

exiv2: add zlib and expat dependency.

---

var/spack/repos/builtin/packages/bazel/package.py

bazel needs working zip / unzip executables as pointed out in https://docs.bazel.build/versions/master/install.html .

bazel: add missing dependency on zip

---

var/spack/repos/builtin/packages/likwid/package.py

includes in partitular fixes for likwid-mpirun but also better support
for ARM and POWER but also other bugfixes.
For full support of ARM and POWER, #14183 has to be merged, too.
Added TomTheBear as maintainer. He is the current main developer of
LIKWID.

likwid: new version 5.0.1

---

lib/spack/spack/installer.py

Bug: when installing with `install_missing_compilers: true` in the config.yaml, leaf nodes of the package will be pulled from the queue for installation before the underlying compiler is installed.
Fix: Mark bootstrapped compilers as having a dependent of the package they are bootstrapped for. Do not mark the package as having a dependency on the compiler, as that would change the hash. Rather, we separately compute the compiler, if not already installed, as one of the dependents of the BuildTask object when pushing tasks to the queue.
To reproduce, try to install the following environment to a Spack instance in which `gcc@5.5.0` is not already configured as an available compiler.
```
spack:
specs: [zlib%gcc@5.5.0]
config:
install_missing_compilers: true
```

bugfix: fix install_missing_compilers option bug from v0.14.0

---

var/spack/repos/builtin/packages/r/change_optflags_tmp.patch
var/spack/repos/builtin/packages/r/package.py

R cannot be built with '-O2' optimization when using Fujitsu Compiler@4.1.0 now, but we will fix this problem. Until this problem is fixed, we need to temporary fix to lower the optimization level.
This fix will be removed if the problem is resolved in the future.

r: Lower optimization level when using Fujitsu compiler@4.1.0.

---

var/spack/repos/builtin/packages/gcc/glibc-2.31-libsanitizer-1.patch
var/spack/repos/builtin/packages/gcc/glibc-2.31-libsanitizer-2.patch
var/spack/repos/builtin/packages/gcc/package.py

This commit fixes [issue 15351](https://github.com/spack/spack/issues/15351) for me.

gcc: backporting fix for glibc 2.31

---

var/spack/repos/builtin/packages/openblas/lapack-0.3.9-xerbl.patch
var/spack/repos/builtin/packages/openblas/package.py

See https://github.com/spack/spack/issues/15385 . I verified OpenBLAS 0.3.9 now installs on intel%18 and 0.2.20 installs on my mac. I also changed the mixed-case `consistentFPCSR` variant name to `consistent_fpcsr` as per https://github.com/spack/spack/issues/15239 .

Fix OpenBLAS 0.2 build, 0.38+ Intel builds, and variant name

---

lib/spack/spack/fetch_strategy.py

This code is not used anywhere in the project, and the import of xml causes errors on systems for which the default python was built without xml support.

fetch_strategy: remove vestigial code

---

lib/spack/spack/installer.py
lib/spack/spack/test/installer.py

This PR fixes a bug in and adds a test for `dump_packages`.
Note the changes were pulled from #15237 to highlight the bug fix.

bugfix: resolve undefined source_pkg_dir failure

---

var/spack/repos/builtin/packages/libfabric/package.py

The test utils for the new version 1.9.1 are missing.
Add them.

libfabric@1.9.1: Add fabtests

---

var/spack/repos/builtin/packages/cpio/package.py

This PR adds `-no-gcc` to Intel's compile line to be able to compile this package.

cpio: icc -no-gcc

---

var/spack/repos/builtin/packages/revbayes/package.py

The revbayes project renamed their old development repository to revbayes.archive, then started a new development repository with the same name as the old one. 
Consequently, the urls for previous release downloads have changed. The hashes seem to have changed too on account of the tar file using the repository name as a folder name

revbayes: Update URLs and hashes for old archives

---

lib/spack/spack/fetch_strategy.py
lib/spack/spack/package.py
lib/spack/spack/test/url_fetch.py

fixes #15449
Before this PR a call to `pkg.url_for_version` was modifying class attributes determining different results for subsequent calls and an error when the `urls` was empty.

Creating versions from urls doesn't modify class attributes

---

var/spack/repos/builtin/packages/plumed/package.py

Plumed uses cython in its build process. Adding the dependency to Spack prevents getting a random (old) version from the environment and seeing errors like `Error compiling Cython file: Cannot convert 'void *' to Python object` during build.

add cython as dependency of plumed

---

var/spack/repos/builtin/packages/likwid/package.py

LIKWID 5.0.0 has support for ARM and POWER processors. Each architectures uses a different LIKWID-internal compiler name like GCCARMv8.
I wasn't sure how to check the version in the install function to raise an error if trying to build LIKWID < 5.0 with ARM and POWER compiler settings. If you could give me a hint, I'll add that of course.

Add compiler selection for ARM and POWER architecture

---

.gitignore

@alalazo I believe #15354 moved the cache directory that pytest uses to store failed test results.

gitignore: pytest cache directory

---

var/spack/repos/builtin/packages/pgi/package.py

Adjust PATH, MANPATH and LD_LIBRARY_PATH in the run environment.
These are also set in the module-files in the PGI compiler itself:
```
e.g. <pgi-install-path>/modulefiles/pgi/19.10:
...
setenv PGI $pgihome
setenv CC $pgidir/bin/pgcc
setenv FC $pgidir/bin/pgfortran
setenv F90 $pgidir/bin/pgfortran
setenv F77 $pgidir/bin/pgfortran
setenv CPP /bin/cpp
setenv CXX $pgidir/bin/pgc++
prepend-path PATH $pgidir/bin
prepend-path MANPATH $pgidir/man
if { $kern == "Darwin" } {
prepend-path DYLD_LIBRARY_PATH $pgidir/lib
} elseif { $kern == "Linux" } {
prepend-path LD_LIBRARY_PATH $pgidir/lib
}
...
```

pgi: add missing paths in setup_run_environment

---

lib/spack/spack/fetch_strategy.py
lib/spack/spack/package.py
lib/spack/spack/test/packages.py
lib/spack/spack/test/url_fetch.py
var/spack/repos/builtin.mock/packages/fetch-options/package.py
var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/eclipse-gcj-parser/package.py
var/spack/repos/builtin/packages/elfutils/package.py
var/spack/repos/builtin/packages/gcc/package.py
var/spack/repos/builtin/packages/jdk/package.py
var/spack/repos/builtin/packages/libffi/package.py
var/spack/repos/builtin/packages/lvm2/package.py
var/spack/repos/builtin/packages/valgrind/package.py
var/spack/repos/builtin/packages/verrou/package.py

PR #15212 added a new connect_timeout option that can be overriden using fetch_options but had to specified per-version. This adds a new per-package variable that can be used to override fetch_options.

package: Add fetch_options variable

---

var/spack/repos/builtin/packages/py-astpretty/package.py

Successfully installs on macOS 10.15.3 with Clang 11.0.0 and Python 3.7.6.

py-astpretty: add new package

---

var/spack/repos/builtin/packages/hpctoolkit/package.py

HPCToolKit <= 2020.03.01 does not build with binutils 2.34.
@mwkrentel I used a version constraint here since I'm assuming that at some point before the next point release, `master` will be buildable with binutils@2.34. If you would rather wait to add that until after `master` *actually* builds with that, then I can remove it.

hpctoolkit: limit binutils to <= 2.33.1

---

var/spack/repos/builtin/packages/gcc/package.py

The patch neither applies nor is necessary.

gcc: Don't apply macOS 9.2.0 patch for 9.3.0

---

var/spack/repos/builtin/packages/tixi/package.py

Add the TIXI xml interface library.
TIXI is built on top of libxml2 and libxslt and provides a simple interface for different languages (C/C++/Fortran/Python). It is used in scientific codes for aircraft design optimization, e.g. see https://www.cpacs.de/.

tixi: add package.py for the TIXI xml interface library

---

lib/spack/docs/build_systems/cmakepackage.rst
lib/spack/spack/build_systems/cmake.py
lib/spack/spack/test/build_systems.py
var/spack/repos/builtin.mock/packages/cmake-client/package.py

This is a first crack at a convenience function for creating a helper function to simplify CMake package definitions, namely to simplify the common but ugly and potentially error-prone idiom of
```python
args.append('-DFOO=%s' % ('ON' if '+foo' in self.spec else 'OFF'))
```
to
```python
args.append(self.define_from_variant('foo'))
```

Add CMake package equivalent of "with_or_without"

---

lib/spack/spack/relocate.py

@eugeneswalker got this error using buildcache installs on RHEL8.
```
==> Relocating package from
/super/absurdly/ridiculously/obnoxiously/long/path/for/relocation to /opt/spack/opt/spack.
==> Error: Doing a binary string replacement in /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-7.3.0/pkgconf-1.6.3-mrunufrcl6il7w5yqi43dxmeshtdzsi2/lib/libpkgconf.so.3.0.0 failed.
The size of the file changed from 253992 to 254172
when it should have remanined the same.
```
This was tracked to using null byte strings in the search pattern for path text in the binary file. This method works for Mach-o paths but not for path strings in ELF binaries. Removing the null bytes from the string fixes the error.

When replacing path text in ELF binaries do not include null byte padding in search string

---

var/spack/repos/builtin/packages/tau/package.py

Package `tau` doesn't currently build with `binutils@2.34` . This temporarily limits `tau` to use `binutils@:2.33.1` until the issue is resolved.
@wspear @sameershende @khuck

TAU cap binutils to @:2.33.1 due to problems with 2.34

---

etc/spack/defaults/modules.yaml

fixes #11555
Every path in `CPATH` is equivalent to a `-I` path to the compiler, while every path in `*_INCLUDE_PATH` is equivalent to `-isystem`. The latter avoids the noise due to warnings coming from 3rd party libraries that a project depends on.

Module files won't use CPATH by default, but language specific vars

---

var/spack/repos/builtin/packages/vecgeom/package.py

This PR has https://github.com/spack/spack/pull/14376 as a prerequisite; changes to spack core will be merged in that one and then I'll rebase this branch.
---
- Add a new package VecCore as a Spack-based dependency rather than having VecGeom's cmake auto-download and install
- Prevent auto-downloading of unused test data during VecGeom installation
- Use target microarchitecture instead of variant to determine instruction set
- Add shared library and CUDA support to VecGeom
- Add GDML and ROOT support to VecGeom
- Update a ROOT dependency (Davix) because of a version compatibility issue declared by ROOT

Update and exetend VecGeom

---

var/spack/repos/builtin/packages/geant4/package.py

@drbenmorgan
I got error when installing `geant4`.
```
xerces-c@3.2.2%fj@4.1.0 cxxstd=default transcoder=gnuiconv arch=linux-rhel8-thunderx2
while trying to concretize the partial spec:
geant4@10.05.p01%fj@4.1.0 build_type=RelWithDebInfo cxxstd=11 +data~motif~opengl~qt+threads~vecgeom~x11 arch=linux-rhel8-thunderx2
^cmake@3.16.2%fj@4.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel8-thunderx2
^ncurses
^pkgconfig
^openssl
^perl@5.14.0:
^gdbm
^readline
^zlib@1.2.11%fj@4.1.0+optimize+pic+shared arch=linux-rhel8-thunderx2
geant4 requires xerces-c variant cxxstd=11, but spec asked for cxxstd=default
```
Variants of 'cxxstd' can be selected one of [11,14,17], and 3 types of `xerces-c` dependency corresponding to cxxstd …

geant4: Removed unnecessary definition of xerces-c.

---

var/spack/repos/builtin/packages/tau/package.py

Implemented working file filtering to replace Spack compiler wrapper with real compiler. It was possible for TAU to grab the wrapper when configuring off of a spack-provided MPI.

Corrected compiler filtering for TAU makefiles

---

lib/spack/spack/relocate.py

Most documented cases of patchelf generating an error are from running on staticly linked binaries.

Remove PatchelfError and change patchelf error message to a warning.

---

var/spack/repos/builtin/packages/mpich/nag_libtool_2.4.2_0.patch
var/spack/repos/builtin/packages/mpich/nag_libtool_2.4.2_1.patch
var/spack/repos/builtin/packages/mpich/nag_libtool_2.4.2_2.patch
var/spack/repos/builtin/packages/mpich/nag_libtool_2.4.6.patch
var/spack/repos/builtin/packages/mpich/package.py

The dependencies on `libpciaccess` and `libxml2` come from the embedded `hwloc`, which, before MPICH 3.3, was used only for Hydra. Additionally, it is possible to use `hwloc`'s custom implementation of XML parsing instead of `libxml2`, which might be useful. For example, `libxml2.la` contains `-pthread` flag, which might not be recognized by Fortran compiler, e.g. NAG.

MPICH: optionally build without libxml2.

---

var/spack/repos/builtin/packages/intel-tbb/package.py

The current checksum for `intel-tbb@2020.1` doesn't match that of the source package. This PR updates the checksum to reflect the actual source package checksum.

intel-tbb@2020.1 - update checksum

---

var/spack/repos/builtin/packages/openspeedshop/package.py
var/spack/repos/builtin/packages/qt/package.py

This puts back the changes that caused the breakage.
Also add depends_on for libSM for the qt 3 build.  On some platforms the installed libSM is out of sync with libuuid causing build link errors.
Change the broke build:
```
@@ -149,7 +134,7 @@ class Qt(Package):
depends_on("libpng@1.2.57", when='@3')
depends_on("pcre+multibyte", when='@5.0:5.8')
depends_on("inputproto", when='@:5.8')
-    depends_on("openssl@:1.0.999", when='@:5.9+ssl~krellpatch')
+    depends_on("openssl@:1.0.999", when='@:5.9+ssl')
```

Previous qt package file changes broke the openspeedshop gui build.  

---

var/spack/repos/builtin/packages/openpmd-api/hdf5-1.12.0.patch
var/spack/repos/builtin/packages/openpmd-api/package.py

Fix API breakage in HDF5 1.12.0 for released versions.
cc @eugeneswalker: took me a day longer than expected due to the shelter-in-place announcement yesterday. Thank you again for reporting!
Refs.:
- https://github.com/openPMD/openPMD-api/pull/696
- Fix #15502

openPMD-api: HDF5 1.12.0 Support

---

var/spack/repos/builtin/packages/libxml2/package.py
var/spack/repos/builtin/packages/libxml2/test/info.dtd
var/spack/repos/builtin/packages/libxml2/test/info.xml

This is a set of smoke tests that leverage executables generated by the `libxml2` package.
TODO

Preliminary libxml2 tests

---

var/spack/repos/builtin/packages/r-openssl/package.py

r-sys requires C99, but this is not set explicitly. The issue is expressed for compilers using C11 as default.

r-openssl requires C99.

---

var/spack/repos/builtin/packages/r-sys/package.py

r-sys requires C99, but this is not set explicitly. The issue is expressed for compilers using C11 as default.

r-sys requires C99.

---

var/spack/repos/builtin/packages/xsetpointer/package.py

xsetpointer use inputproto's include file.
But dependency type of inputproto is 'build'.
This PR change dependency type to 'link'.

xsetpointer: fix wrong dependency type.

---

var/spack/repos/builtin/packages/triangle/package.py

Triangle is used libX11. but dependency is missing.
This PR add libX11 dependency to triangle.

triangle: add X11 dependency.

---

var/spack/repos/builtin/packages/cgns/package.py

The CGNS library has several new versions.   There was a format-changing change in 3.4.0 which was removed for 3.4.1.  The change was then added again and released with a change to the major version (4.0.0).  Note that 4.0.0 should be close to the functionality of 3.4.0.

CGNS: Version update

---

var/spack/repos/builtin/packages/revbayes/package.py

The development branch requires running a new script before compiling.

revbayes: Update pre-build process

---

var/spack/repos/builtin/packages/adol-c/package.py

Updating source location since ADOL-C has been moved to ​https://github.com/coin-or/ADOL-C
from https://projects.coin-or.org/ADOL-C

adol-c:updating sources location

---

var/spack/repos/builtin/packages/openmpi/package.py

This is a set of smoke tests for the `openmpi` package.  
This PR leverages the `_run_test` function introduced in #15092 to perform version checks, check expected result status, and check expected output.  This PR introduces the notion of running a complete set of checks before terminating (versus terminating on the first failure).
Follow-on work will introduce simple executable programs for the major languages -- C, C++, and Fortran -- that must be compiled and run.  Tests to check the rpath _may_ be introduced.  According to John Gyllenhaal (LLNL), these types of tests -- if they were run on multiple nodes with multiple tasks -- could catch 95% of the problems with an installation.
TODO:
(There are differences e.g., eight of the version tests fail for v2.0.0.)
*These should be designed …

Initial OpenMPI smoke tests

---

var/spack/repos/builtin/packages/trilinos/package.py

+ Provide three new variants to allow building trilinos without netcdf, matio, or glm.
+ No change to defaults.
+ Allows a lighter-weight install of trilinos.

Trilinos: Add more variants (~netcdf ~matio ~glm)

---

lib/spack/spack/database.py

When trying to use an upstream spack repository that is read-only, in particular,
the one on Summit, I got an error because Spack was trying to create the failures/
subdir in the upstream .spack_db.
This adds a little check to prevent slack from trying to mkdir failures/ in an upstream
repo.

don't try to create failures/ directory in upstream repo

---

var/spack/repos/builtin/packages/fabtests/package.py
var/spack/repos/builtin/packages/libfabric/package.py

Fabtests provides runtime analysis tools and examples of libfabric.
As with other projects that are [tightly version-bound](https://github.com/ofiwg/libfabric/blob/33ea19fd66119b8218dc50678f240d44084c2690/.travis.yml#L110-L118), e.g. `py-adios` and `adios`, the fact that releases stem from the same repo does not imply they should be the same package.
Remove resources, which [complicate the libfabric build](https://github.com/spack/spack/issues/15244), and update the fabtests package accordingly.
See https://github.com/spack/spack/pull/15405#issuecomment-600362176
See https://github.com/spack/spack/pull/15405#issuecomment-600501395
Re.: #15244 #15405 #15440
CC: @LDAmorim @sethrj @carns @soumagne @ChristianTackeGSI please confirm this works for you. Be aware that `fabtests` are probably …

Split: Fabtest/libfabric

---

var/spack/repos/builtin/packages/amdblis/package.py
var/spack/repos/builtin/packages/blis/package.py

In `spack info amdblis` , package name is blis.
And amdblis dose not provide blas virtual package.
This PR fixes those problems.
<pre>
$ spack info amdblis
Package:   blis
Description:
AMD Optimized BLIS. BLIS is a portable software framework for
instantiating high-performance BLAS-like dense linear algebra libraries.
The framework was designed to isolate essential kernels of computation
that, when optimized, immediately enable optimized implementations of
most of its commonly used and computationally intensive operations.
Homepage: https://developer.amd.com/amd-aocl/blas-library/
Tags:
None
Preferred version:
2.1    https://github.com/amd/blis/archive/2.1.tar.gz
Safe versions:
2.1    https://github.com/amd/blis/archive/2.1.tar.gz
Variants:
Name [Default]    Allowed values …

amdblis: fix display spack info and virtual package setting.

---

lib/spack/spack/cmd/dependencies.py
lib/spack/spack/package.py
lib/spack/spack/test/cmd/dependencies.py
lib/spack/spack/test/package_class.py

This consolidates some code that was in `cmd/dependencies.py` to `spack.package.possible_dependencies()`, and it adds some tests  Specifically, it's code for dealing with virtuals -- `possible_dependencies()` can just take virtuals now, and does not need special logic in the `spack dependencies` command.  This is an ongoing attempt to get some stuff off `features/solver` and onto the mainline.

refactor: `spack.package.possible_dependencies()` handles virtuals

---

var/spack/repos/builtin/packages/py-deprecated/package.py

This PR adds the ["Deprecated"](https://pypi.org/project/Deprecated) python module.
The dependency information has been extracted from the project's [`setup.py`](https://github.com/tantale/deprecated/blob/master/setup.py).

Add package: py-deprecated

---

var/spack/repos/builtin/packages/petsc/package.py

Fixes #15553 
Besides updating release 3.12.4, this fixes a build error by constraining hdf5 to up 1.10 for existing releases.
`develop` and the next release (3.13) will (hopefully) support HDF5 1.12 directly,
so their behavior is unchanged, but for exisiting releases this one makes them build again by
falling back to HDF5 1.10.

petsc fix hdf5

---

var/spack/repos/builtin/packages/charliecloud/package.py

We've had issues (#14605, [636](https://github.com/hpc/charliecloud/pull/636)) with our spack builder variant. In short, you simply couldn't install Charliecloud with said variant.
To reduce Charliecloud dependencies and simplify packaging we replaced `skopeo` and `umoci` functionality with a native python3 script, [ch-tug](https://github.com/hpc/charliecloud/pull/616).
We'd like to remove the builder variant completely. Charliecloud 0.13 (unsupported) was the last release depending on skopeo and umoci, thus this PR removes it completely.

add charliecloud/0.14; remove umoci/skopeo; remove builder variant

---

lib/spack/spack/platforms/cray.py

Bug: Spack hangs on some Cray machines
Reason: The `TERM` environment variable is necessary to run `bash -lc "echo $CRAY_CPU_TARGET"`, but we run that command within `env -i`, which wipes the environment.
Fix: Manually forward the `TERM` environment variable to `env -i /bin/bash -lc "echo $CRAY_CPU_TARGET"`

Cray bugfix: TERM missing while reading default target

---

.vscode/settings.json
var/spack/repos/builtin/packages/libgit2/package.py
var/spack/repos/builtin/packages/rust/package.py

This change improves on the installation of the rust package in a few key ways. First, it puts everything needed to build the package into Spack's package management, meaning you no longer need network access to build the package (the current Rust package must pull the bootstrapping compiler off the Internet). Second, it builds the vendored LLVM for the package. This is important because Rust is tightly coupled to its own, modified version of LLVM - it shouldn't be built with any arbitrary version of LLVM, even if in practice it sometimes works. Finally, it provides a path to bootstrap Rust from a C++ implementation of the compiler called mrustc.
The current 'rust' package relies on the Rust build system pulling the bootstrapping compiler from the web. This, of course, doesn't work on …

Improvements to Rust's Installation

---

var/spack/repos/builtin/packages/htop/package.py

htop requires a `python` binary on the PATH in order to be build. 
The shebang in [scripts/MakeHeader.py](https://github.com/hishamhm/htop/blob/master/scripts/MakeHeader.py) is `#!/usr/bin/env python` leading to the error below. This affects all versions in spack. I think it doesn't trigger usually, as the host system typically comes with a `python` binary/symlink. Technically the explicit variant is not needed, as we default to True, but it's not PEP compliant so we might want to change it in the future.
Found this while setting up my Ubuntu on Windows which comes with python3.6
```
'make' '-j8'
16 errors found in build log:
93     ./scripts/MakeHeader.py DisplayOptionsPanel.c
94     ./scripts/MakeHeader.py Header.c
95 …
```

add missing python build dependency to htop

---

var/spack/repos/builtin/packages/acts-core/package.py

Yet another minor ACTS release. In addition, the boost version requirement was recently bumped on master, which will most likely affect v0.19+.

[acts-core] v0.18 and boost version bump

---

var/spack/repos/builtin/packages/py-networkx/package.py

Successfully installs on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.0.

py-networkx: add 2.4

---

var/spack/repos/builtin/packages/py-decorator/package.py

Successfully installs on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.0.

py-decorator: add 4.4.2

---

lib/spack/spack/patch.py

When a patches sha256 is missing, also show the packagename, so that analyzing is easier.

Show the packaga name for a missing patch sha256

---

var/spack/repos/builtin/packages/sentencepiece/package.py

Successfully installs on macOS 10.15.3 with Clang 11.0.0.

sentencepiece: add new package

---

var/spack/repos/builtin/packages/tau/package.py

Make `tau`'s dependency on `hwloc` explicit. @wspear

tau depends on hwloc

---

lib/spack/spack/cmd/checksum.py
lib/spack/spack/stage.py

This makes sure that a package's fetch_options are used when fetching new versions to checksum. This allows working around problems with slow servers or those requiring a cookie to be set.
Depends on #15317
cc @scheibelp

checksum: Use package's fetch_options

---

etc/spack/defaults/packages.yaml
lib/spack/llnl/util/tty/log.py
lib/spack/spack/test/cmd/install.py

Spack currently cannot run as a background process uninterrupted because some of the logging functions used in the install method (especially to create the dynamic verbosity toggle with the `v` key) cause the OS to issue a `SIGTTOU` to Spack when it's backgrounded.
This PR puts the necessary gatekeeping in place so that Spack doesn't do anything that will cause a signal to stop the process when operating as a background process.

multiprocessing: allow Spack to run uninterrupted in background

---

var/spack/repos/builtin/packages/py-sentencepiece/package.py

Successfully builds on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.0.

py-sentencepiece: add new package

---

var/spack/repos/builtin/packages/lua-luaposix/package.py

Add version 33.2.1 with checksum to the lua-luaposix package.

Add 33.2.1 version with checksum to lua-luaposix

---

var/spack/repos/builtin/packages/gmsh/package.py

This adds OpenCASCADE as an alternative to the oce package.
A new variant 'privateapi' is added to enable the gmsh private API.

Add gmsh v4.5.4 with new options

---

var/spack/repos/builtin/packages/swig/package.py

Adds version 4.0.1 to the swig package versions (released in August, 2019).

swig: add version 4.0.1

---

lib/spack/spack/test/packaging.py

Also fixes a bug in the test for relative paths.

Buildcache: add unit tests for normalized path functions in relocate.py

---

lib/spack/spack/database.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/database.py

fixes #15030
fixes #15040 
Add a file containing a unique uuid that is regenerated at database
write time. Use this uuid to suppress re-parsing the database
contents if we know a previous uuid and the uuid has not changed.

performance: add a verification file to the database

---

var/spack/repos/builtin/packages/bash/package.py

Successfully builds on macOS 10.15.3 with Clang 11.0.0.

bash: add patches up to 5.0.16

---

var/spack/repos/builtin/packages/davix/package.py

Davix is written in C++, so add a `cxxstd` variant to allow dependents to specify this so a consistent ABI is used. Its only `dependents` is the `root` package, so that may need updating in due course.

davix: add cxxstd variant

---

var/spack/repos/builtin/packages/warpx/package.py

Update WarpX from for recent developments:
- add openPMD I/O (default: ON)
- remove electro-static solver option (now a runtime option)
- enable tiny profiler by default
- depend on new CXX std support in make scripts for C++14
- WarpX only supports 2D and 3D in cartesian dims
CC for review: @dpgrote @MaxThevenet @RemiLehe

WarpX: Update ES and openPMD

---

var/spack/repos/builtin/packages/intel-mkl-dnn/package.py

Successfully installs on macOS 10.15.3 with Clang 11.0.0.
Doesn't pass all its tests, but I don't even have a GPU on my laptop, so I'm not surprised.

NCCL: add 1.2.2

---

lib/spack/spack/installer.py

`spack test` has a spurious '[+] ' in the output:
```
lib/spack/spack/test/install.py .........[+] ......
```
Output is properly suppressed:
```
lib/spack/spack/test/install.py ...............
```

bugfix: spack test should not output [+] for mock installs

---

lib/spack/spack/platforms/cray.py

Fixes first bug in #15620.
Fixes a bug introduced in #15381: `TERM` may not be set at all.

bugfix: TERM may not be in the environment on Cray

---

lib/spack/external/__init__.py
lib/spack/external/_pytest/config.py
lib/spack/external/_pytest/vendored_packages/pluggy.py

Closes #15369.
Closes #9034.
Follow-up of #9261.
Previously, `spack test` would fail within a new spack environment, because it could not import `pkg_resources` (part of `setuptools`) Parts of `pytest` use `setuptools`, but we do not need them for Spack, so it's an unnecessary dependency.
Patching `pytest` is nasty but it's a lot simpler than vendoring yet another mess of packages.  Also, recent versions of `pytest` do not depend on `setuptools` (see pytest-dev/pytest#5063).  We're just stuck with an old version of `pytest` because we still support Python 2.6.
Astute readers may note that `jinja2` also uses `pkg_resources`, but we don't use any parts of it that actually import `pkg_resources`.  So we do not need to remove these imports from `jinja2`.

vendoring: remove dependency on setuptools from vendored pytest

---

lib/spack/spack/relocate.py
lib/spack/spack/test/relocate.py

This PR is a minor refactoring of a couple of functions in `spack.relocate` to be more in line with current practices in other parts Spack (see single commit descriptions for details). It also adds a unit test for the function searching for `patchelf`.

spack.relocate: add unit test

---

var/spack/repos/builtin/packages/py-onnx/package.py
var/spack/repos/builtin/packages/py-onnx/remove_dllexport_decl.patch

I got error following when installing `py-onnx`.
```
91    [  7%] Running C++ protocol buffer compiler on /tmp/n0013/spack-stage/spack-stage-p
y-onnx-1.5.0-bzrosaagawrtjc5zjbefjb2hrncnwfhr/spack-src/.setuptools-cmake-build/onn
x/onnx-ml.proto
92    --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
```
It seems that 'python_out' does not recognize dllexport_decl. So, Apply the following fix patch.
Ref: https://github.com/onnx/onnx/pull/2482
This fix will be included in the upstream package version:1.7.0.

py-onnx: Remove 'dllexport_decl'.

---

var/spack/repos/builtin/packages/r-remotes/package.py

Adding new version `2.1.1` to `r-remotes`.

Update version r-remotes for 2.1.1

---

var/spack/repos/builtin/packages/otf2/package.py

This resolves an erroneous requirement by `otf2`'s python configure script, which requires a `python 2` version when `python 2` is NOT in fact specifically needed for `otf2`. Replacement for PR https://github.com/spack/spack/pull/15499

workaround for otf2's erroneous python2 configure requirement

---

var/spack/repos/builtin/packages/charmpp/package.py

- change URL to http as our server only supports TLSv1.0, which
not all HTTPS clients accept anymore (see also #15186)
- change name of development branch to 'master'

charmpp: add version 6.10.1+cleanups

---

var/spack/repos/builtin/packages/gitconddb/package.py

Git-based conditions database for HEP and other experiments.
Use latest release version and current master to support Linux and macOS. Add core known dependencies and conflicts related to C++17 support. Strictly speaking the conflict on macOS should be "AppleClang less than 11 or OS less than 10.15", but I'm not sure how best to express that yet. 
The `cxxstd` variant is present to help transitive dependencies, and for future support for newer standards in future.

New package: gitconddb

---

lib/spack/spack/provider_index.py
lib/spack/spack/test/spec_dag.py

The refactoring is instrumental to a further subclassing of `_IndexBase` to implement user defined bindings of provider spec for #15443

provider index: removed import from + refactored a few parts

---

var/spack/repos/builtin/packages/warpx/package.py

Expose serial/parallel build (MPI), RZ geometry, CUDA/OpenMP backends, Clang, and Ascent bindings.
Interestingly, `warpx +ascent` (@cyrush) currently leads to an infinite loop in the Spack concretizer (@tgamblin).
CC for review: @dpgrote @MaxThevenet @RemiLehe

WarpX: MPI, Backends, RZ, Ascent

---

var/spack/repos/builtin/packages/upcxx/package.py

This PR updates and improves the Spack package for [UPC++](https://upcxx.lbl.gov).
I'm an LBL employee and developer on the UPC++ team, as well as the maintainer of this Spack package.
* Adding new 2020.3.0 release and support for use of develop/master branches
- Our build infrastructure underwent a major change in this release, switching from a hand-rolled Python2 script to a bash-based autoconf work-alike. 
- The new build system is NOT using autotools (nor does it support some of the more esoteric autoconf options), but the user interface for common builds is similar.
* Add explicit support for an MPI optional dependency
- New `mpi` variant enables use of the MPI-based spawner (most relevant on loosely coupled clusters), and the (unofficial) mpi-conduit backend
- This variant is OFF by …

UPC++ 2020.3.0 update

---

var/spack/repos/builtin/packages/util-linux/package.py

This pull request adds `--disable-makeinstall-chown` flag to the configuration arguments. Without this flag, installation procedure involves changing the ownership on some files to root:root. So, the installation fails if the package is installed as a non-root user.
```
5 errors found in build log:
1290    for I in uname26 linux32 linux64   i386 x86_64     ; do \
1291       cd /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/util-linux-2.35.1-fvfws3jh
pjdhsw3a53taa5yrscxacyy2/bin && ln -sf setarch $I ; \
1292    done
1293    chown root:root /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/util-linux-2.3
5.1-fvfws3jhpjdhsw3a53taa5yrscxacyy2/bin/mount
1294    chown: changing ownership of '/home/ubuntu/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/ …
```

Fix non-root installations; update homepage

---

var/spack/repos/builtin/packages/gtkorvo-dill/2.1-fix-clear_cache.patch
var/spack/repos/builtin/packages/gtkorvo-dill/2.4-fix-clear_cache.patch
var/spack/repos/builtin/packages/gtkorvo-dill/package.py

- error
```
>> 101    /tmp/pytest-of-ogura/pytest-77/mock-stage0/spack-stage-gtkorvo-dill
-2.4-dqt4eofp33rvnb3sv5cbl5hd3lnpbw37/spack-src/arm8_rt.c:127:13: e
rror: conflicting types for '__clear_cache'
102    extern void __clear_cache(char*, char *);
103                ^
```
Only define `__clear_cache` if not defined, and fix for match the argument type of the built-in function `__clear_cache`.
Ref: https://github.com/GTkorvo/dill/commit/dac6dfcc7fdaceeb4c157f9ecdf5ecc28f20477f

gtkorvo-dill: fix argument type of clear_cache

---

var/spack/repos/builtin/packages/meson/package.py

py-setuptools is actually required for running meson.

meson: Add 0.53.2 and fix setuptools dependency

---

var/spack/repos/builtin/packages/intel-tbb/package.py

intel moved the repository around.
github changes the prefix inside the tar according to the repository name.
So all sha256 have changed!
I verified that the tar contents for 2019.4 did not change except for the prefix.
cc: @kresan

intel-tbb: new download url, fix sha256

---

var/spack/repos/builtin/packages/denovogear/newmat6.cpp.patch
var/spack/repos/builtin/packages/denovogear/package.py

- error
```
>> 162    /tmp/pytest-of-ogura/pytest-77/mock-stage0/spack-stage-denovogear-1
.1.1-ukwgywcis5clcaibvlqdn6wdfimw4vue/spack-src/src/contrib/newmat/
newmat6.cpp:431:13: error: ordered comparison between pointer and z
ero ('int *' and 'int')
163       if (indx > 0) { delete [] indx; indx = 0; }
164           ~~~~ ^ ~
```
I changed comparison from `indx > 0` to `indx != NULL`
I submitted this pull request.
https://github.com/ultimatesource/denovogear/pull/309

denovogear: fixed comparison error

---

var/spack/repos/builtin/packages/py-pyqt4/package.py
var/spack/repos/builtin/packages/py-pyqt5/package.py
var/spack/repos/builtin/packages/qgis/package.py
var/spack/repos/builtin/packages/qscintilla/package.py

use `extend_path` trick to install Qscintilla python bindings under qscintilla prefix but still make `from PyQt5 import Qsci` work.

Package/qscintilla: python bindings via extend path

---

var/spack/repos/builtin/packages/py-grpcio/package.py

Successfully installs on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.3, although I run into the following issue on my laptop (for both 1.27.2 and 1.25.0): https://github.com/grpc/grpc/issues/22491

py-grpcio: add new version

---

var/spack/repos/builtin/packages/py-tensorflow/package.py

we don't need to manually install them.

TensorFlow: let install take care of the headers

---

var/spack/repos/builtin/packages/netcdf-c/package.py

I'm not sure of the correct protocol to do this, so decided to make a stab and hopefully it works or I'm told the correct way...
The `maxdims` and `maxvars` variants for the NetCDF package were, to the best of my knowledge, only ever used for the Exodus library in the SEACAS package (which I maintain).  In versions of NetCDF prior to 4.4.0, Exodus required that the `NC_MAX_DIMS` and `NC_MAX_VARS` be increased over the default values.  This requirement was removed in 4.4.0 and later.
I do not know of any way to make a variant depend on the version and since the `maxdims` and `maxvars` variants are integer values and not boolean, then every build of NetCDF will have  these variants.  Typically `maxdims=1024 maxvars=8192` and the build will patch the `netcdf.h` include file for every build …

netcdf-c: remove maxdims and maxvars variant

---

var/spack/repos/builtin/packages/py-diskcache/package.py

Successfully installs on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.3.

py-diskcache: add new package

---

var/spack/repos/builtin/packages/mesa/package.py

The `libs` property was originally introduced in the `mesa` package in #8904 but then it was removed (unintentionally, I assume) in #10482.

Re-introduce the libs property in the mesa package

---

etc/spack/defaults/packages.yaml
var/spack/repos/builtin/packages/apr-util/package.py
var/spack/repos/builtin/packages/bash/package.py
var/spack/repos/builtin/packages/dcmtk/package.py
var/spack/repos/builtin/packages/diffutils/package.py
var/spack/repos/builtin/packages/doxygen/package.py
var/spack/repos/builtin/packages/gcc/package.py
var/spack/repos/builtin/packages/gdal/package.py
var/spack/repos/builtin/packages/git/package.py
var/spack/repos/builtin/packages/glib/package.py
var/spack/repos/builtin/packages/gnupg/package.py
var/spack/repos/builtin/packages/gnuplot/package.py
var/spack/repos/builtin/packages/grass/package.py
var/spack/repos/builtin/packages/gtksourceview/package.py
var/spack/repos/builtin/packages/lftp/package.py
var/spack/repos/builtin/packages/libc/package.py
var/spack/repos/builtin/packages/libgd/package.py
var/spack/repos/builtin/packages/libiconv/package.py
var/spack/repos/builtin/packages/libspatialite/package.py
var/spack/repos/builtin/packages/libunistring/package.py
var/spack/repos/builtin/packages/libxml2/package.py
var/spack/repos/builtin/packages/libxslt/package.py
var/spack/repos/builtin/packages/mono/package.py
var/spack/repos/builtin/packages/ncl/package.py
var/spack/repos/builtin/packages/poppler/package.py
var/spack/repos/builtin/packages/procps/package.py
var/spack/repos/builtin/packages/tar/package.py
var/spack/repos/builtin/packages/unixodbc/package.py
var/spack/repos/builtin/packages/wget/package.py
var/spack/repos/builtin/packages/xerces-c/package.py

We at SFT-SPI would like to use libc's implementation of iconv, as opposed to libiconv one. This PR introduces a new virtual package `iconv` and a dummy package `libc` to provide it. 
lib's and libiconv's implementation of iconv should be compatible on API level, but I'm testing this just in case.
Packages that directly depend on libiconv:
(re-do of #15213 due to changes in gnupg recipe)

Hack to select iconv implementation - libiconv vs. libc iconv

---

var/spack/repos/builtin/packages/gcc/package.py

the gcc package.py includes patches for a sanitizer related bug that look
like they've been fixed in gcc 8.4.0, which caused `spack install` to fail.
This PR excludes patching gcc >= 8.4.0 and < 9.0.0.
Fixes #15711 . It's mostly @adamjstewart's suggested fix, though I didn't touch the other, macos specific patch.

fix gcc@8.4.0 build

---

var/spack/repos/builtin/packages/motif/package.py

Couldn't build without this. Successfully builds on macOS 10.15.4 with Clang 11.0.3.

motif: add pkgconfig dependency

---

var/spack/repos/builtin/packages/citcoms/package.py

Successfully installs on macOS 10.15.4 with Clang 11.0.3.

CitcomS: add maintainer, master version, python dep

---

var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py

Currently, the only way that the Intel MPI benchmarks can be installed through Spack is by installing the entire Intel MPI implementation. This PR adds a new package that is only the Intel MPI benchmarks so that they can be run independently.

new package: intel-mpi-benchmarks

---

bin/spack-python

The current implementation of `spack-python` will leave an extra shell around while it runs.  That shell should really replace itself with spack.

spack-python should exec `spack python`

---

var/spack/repos/builtin/packages/binutils/package.py

Add additional compile time configuration toggles for binutils. Specifically lto, ld, and interwork have been added as package variants with the defaults set to false to not change any pre-exisiting behavior.

package: add additional configuration options for binutils

---

var/spack/repos/builtin/packages/gdb/package.py

Add additional compile time configuration options for the gdb package. Specifically, variants have been added for lto, quad, gold, and ld support, with the default set to false to preserve existing behavior.

package: add additional configuration options for gdb

---

var/spack/repos/builtin/packages/lmod/package.py

Lmod is missing a few configuration options. I've added some as variants. Now auto-swapping of modules and redirects can be enabled or disabled.

package: add additional configuration options to lmod

---

var/spack/repos/builtin/packages/acts-core/package.py

In order to facilitate outside contribution, the Acts project is moving from a CERN-hosted Gitlab instance to Github. During this migration process, a new release was also tagged.

[acts-core] New version + new repository

---

var/spack/repos/builtin/packages/lua/package.py

Added option to disable generation of shared object library for lua to
avoid build issues on static only platforms

Aded Option to Disable Shared Lua library Generation

---

lib/spack/spack/build_systems/cuda.py

Fix the CUDA-ICC conflict check (revert).
Simplify the XL 17 check.
Follow-up to #13819
Fix #15712
Ref.: https://gist.github.com/ax3l/9489132
cc @psychocoderHPC @naromero77 @svenevs

CUDA 10.1+ supports ICC 19.0

---

var/spack/repos/builtin/packages/py-torch/package.py

This is the same solution I used for `py-pillow`.

py-torch: make sure unit tests are registered

---

var/spack/repos/builtin/packages/g4abla/package.py
var/spack/repos/builtin/packages/g4emlow/package.py
var/spack/repos/builtin/packages/g4ensdfstate/package.py
var/spack/repos/builtin/packages/g4incl/package.py
var/spack/repos/builtin/packages/g4ndl/package.py
var/spack/repos/builtin/packages/g4neutronxs/package.py
var/spack/repos/builtin/packages/g4particlexs/package.py
var/spack/repos/builtin/packages/g4photonevaporation/package.py
var/spack/repos/builtin/packages/g4pii/package.py
var/spack/repos/builtin/packages/g4radioactivedecay/package.py
var/spack/repos/builtin/packages/g4realsurface/package.py
var/spack/repos/builtin/packages/g4saiddata/package.py
var/spack/repos/builtin/packages/g4tendl/package.py
var/spack/repos/builtin/packages/geant4-data/package.py
var/spack/repos/builtin/packages/geant4/geant4-10.4.3-cxx17-removed-features.patch
var/spack/repos/builtin/packages/geant4/package.py
var/spack/repos/builtin/packages/vecgeom/package.py

This is a fairly major refactor and simplification of Geant4 and its associated data packages, and *will* changes hashes of previous installs. I think this is worthwhile for long term maintenance of the package, so this PR is "Draft" for now to get early eyes on it and discuss with interested parties.
The primary change is the removal of the `data` variant so the physics model data packages are always installed by the `g4XXX` packages, then used by Geant4 itself through the `geant4-data` package. `geant4-data` is now a `BundlePackage` whose version maps to that of `geant4` and depends on the `g4XXX` packages at the exact versions the `geant4` version supports. It creates a "view" (more on that later) of the data so Geant4's install mechanisms sees a single directory. Each `g4XXX` package …

geant4: new version 10.6 plus simplifications

---

var/spack/repos/builtin/packages/jasper/package.py

I was having build issues with 2.0.14, but 2.0.16 successfully installs on Scientific Linux 6 with GCC 6.1.0.
Note that new versions of JasPer are only available through their GitHub repo. The official GitHub repo is listed in the downloads section of the homepage.

JasPer: add 2.0.16

---

var/spack/repos/builtin/packages/autoconf-archive/package.py

Successfully installs on Scientific Linux 6 with GCC 6.1.0.

autoconf-archive: add new package

---

lib/spack/docs/build_settings.rst
lib/spack/spack/package.py
lib/spack/spack/package_prefs.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/mirror.py
lib/spack/spack/test/module_parsing.py
lib/spack/spack/test/spec_dag.py
lib/spack/spack/util/module_cmd.py

Currently, to force Spack to use an external MPI, you have to specify `buildable: False` for every MPI provider in Spack in your packages.yaml file. This is both tedious and fragile, as new MPI providers can be added and break your workflow when you do a git pull.
This PR allows you to specify an entire virtual dependency as non-buildable, and specify particular implementations to be built:
```yaml
packages:
all:
providers:
mpi: [mpich]
mpi:
buildable: false
paths:
mpich@3.2 %gcc@7.3.0: /usr/packages/mpich-3.2-gcc-7.3.0
```
will force all Spack builds to use the specified mpich install.

packages.yaml: allow virtuals to specify buildable: false

---

var/spack/repos/builtin/packages/extrae/package.py

Looks like the upstream maintainers changed the package provided by the same filename (sigh...)  So update the recipe to match.
In addition binutils 2.34 includes some API changes that Extrae has not yet caught up with, so version requirements added.

Extrae: update package shasum and binutils version

---

share/spack/csh/spack.csh
share/spack/setup-env.sh

@cookgb can you test this out?
It's not hard to add unit tests for this, but currently our tests only create a single environment (`spack_test_env`). I could rename this to `spack-test-h` or something like that.
Fixes #15425

Allow Spack Environments with '-h' in the name

---

var/spack/repos/builtin/packages/slurm/package.py

* Add version 18-08-9-1
* Add variant to allow setting the sysconfdir
About sysconfdir:
slurm has a server and a client.
To use the correct communication channel, the client needs to be able to read the correct config.  This config is in PREFIX/etc.
Let's assume one has the server part installed as a system package. This generally is a good idea, so that the server gets started during boot. This means, that the config is in `/etc/slurm`.
If one now wants to use the client part (library!) via spack, one has a problem: spack's slurm looks in `SPACK-PACKAGE-PREFIX/etc` for the config.
There needs to be a way to let the spack installed package use the system's config.
So add a variant to override the path during build:
`sysconfdir=/etc/slurm`.
This is much like what happened in #15307 for …

slurm: new version, system configuration path

---

var/spack/repos/builtin/packages/llvm/package.py

Main change is that `libelf` and `libffi` libraries are not a hard dependency for CPU-only builds. Also, `flang` was previously removed and then appeared again -- a regression that occured in the previous PR? FYI: Legacy flang lives in its own Spack package and f18 has not been upstreamed into llvm yet, but we are getting really close.
@trws

Minor LLVM libomptarget fixes

---

var/spack/repos/builtin/packages/hdf5/package.py

HDF5 1.12 broke backward compatibility, so we're preferring version 1.10 for now.  Packages that need the new API should specify:
depends_on("hdf5@1.12:")
to be explicit. We can eventually change the preference, but at the moment most libraries have not udpated to use the new HDF5.

hdf5: prefer version 1.10 for now

---

var/spack/repos/builtin/packages/yaml-cpp/package.py

This pull request adds a variant to yaml-cpp for building static libraries. Default is set to false to preserve preexisting behavior.

package: add static library build option for yaml-cpp

---

var/spack/repos/builtin/packages/cgns/package.py

The CGNS package was missing quite a few build options. This PR adds some of the missing ones ass additional variatns, but sets the default to false to preserve preexisting behavior.

package: add variants to cgns

---

var/spack/repos/builtin/packages/cryptsetup/package.py

Also confined the included patch to the earlier versions, as indicated.

Version bump: cryptsetup 2.3.1

---

var/spack/repos/builtin/packages/unqlite/0001-Removed-the-STATIC-key-word-to-enable-building-a-sha.patch
var/spack/repos/builtin/packages/unqlite/package.py

This PR adds a patch to unqlite to enable building it a shared library instead of of static one, and adds the necessary cmake_args to build the shared library by default from Spack.

unqlite: Patching unqlite to be able to build a shared library

---

var/spack/repos/builtin/packages/intel-mkl-dnn/package.py

Successfully installs on macOS 10.15.4 with Clang 11.0.3.

intel-mkl-dnn: add 1.3

---

var/spack/repos/builtin/packages/mpip/package.py

Adds variants for enabling/disabling demangling and setjmp. Preexisting behavior is preserved in default settings.

mpip: add demangling and setjmp variants

---

var/spack/repos/builtin/packages/pmix/package.py

Adds the option for enabling or disabling pmi backwards compatibility when building pmix.

pmix: add option for toggling pmi backwards compatibility

---

.github/ISSUE_TEMPLATE/bug_report.md
lib/spack/spack/cmd/debug.py
lib/spack/spack/cmd/python.py
lib/spack/spack/test/cmd/debug.py
lib/spack/spack/test/cmd/python.py
share/spack/spack-completion.bash

This flag will help us diagnose bug reports. It's more reliable than asking users to run `python --version`, as Spack includes magic to use Python 3 automatically if the `python3` executable is found.

Add command to facilitate easy Spack/Python/OS reporting

---

var/spack/repos/builtin/packages/precice/package.py

This PR adds version 2.0.2 of the xSDK member preCICE.

precice: Add version 2.0.2

---

lib/spack/spack/test/cmd/env.py
lib/spack/spack/user_environment.py

For an environment that contains externally-defined packages (i.e. with `buildable: False` in `packages.yaml`), Spack was treating external packages as having the same prefix as other packages in the view. This allows external packages to retain their true prefix (as they are not actually linked into the view like Spack-installed packages).
~I haven't yet thoroughly checked this to ensure e.g. that this keeps system paths out of the shell modifications.~ (EDIT: there is now a test for that)
Fixes https://github.com/spack/spack/issues/14797
Fixes https://github.com/spack/spack/issues/14743
TODOs:

Environments/views: only override spec prefix for non-external packages

---

lib/spack/docs/workflows.rst
lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/load.py
lib/spack/spack/test/cmd/load.py
share/spack/spack-completion.bash

This features adds the "--first" option for "spack load" which circumvents the error condition when multiple packages match the requested spec.  Instead, it just loads the first matching package.
The motivation for this feature is the situation where spack is being used in an automated workflow (like CI) where we would like to install and load dependencies for a build outside of spack.  In this case, we need (e.g.) cmake@3.16.2, but we don't care about the details beyond that.  When multiple specs match, there is an error that breaks the whole build.  Instead, just load one!
This feature was discussed with @luszczek .

Add option "--first" for "spack load"

---

var/spack/repos/builtin/packages/unqlite/package.py

The PR corresponding to the patch in the unqlite package was merged. I have restricted the patch to version 1.1.9 as master doesn't need it anymore.

unqlite: restricted patch to version 1.1.9

---

var/spack/repos/builtin/packages/papi/package.py

The process for configuring papi with lmsensors support has changed between version 5.7 and 6.0.

Added support for new config process for papi@6:+lmsensors

---

var/spack/repos/builtin/packages/llvm/package.py

Minor addition to LLVM package. In support of the near-future upstreaming of f18 into LLVM.
Tested with GCC 7.5 on Ubuntu Linux.
Hoping @trws can review.

LLVM package now supports MLIR

---

var/spack/repos/builtin/packages/dnnl/package.py
var/spack/repos/builtin/packages/py-torch/package.py

This PR includes the following changes:
The previous package built fine, but a few of the unit tests were failing (see https://github.com/intel/mkl-dnn/issues/680). With the TBB runtime, all tests pass on macOS 10.15.4 with Clang 11.0.3.
@rsdubtso Thanks for your help in debugging this! If you see anything else in our package that should be changed, let me know. Also, if you or any other DNNL devs would like to be added as "maintainers" of this package, let me know. You don't have to be Spack experts, it just gives us someone to ping when a user encounters build issues or someone submits a PR to change the Spack package and we need reviewers.

Package rename: intel-mkl-dnn -> dnnl

---

var/spack/repos/builtin/packages/py-espressopp/package.py

py-espressopp: pin py-numpy to py2 version

---

var/spack/repos/builtin/packages/eztrace/package.py

There were some configure problems in eztrace that caused error when installing with spack. I fixed the problems in eztrace and release version 1.1-10.
We also moved the git repos from inria gforge to gitlab.com
This patch uses the latest version of eztrace  from gitlab.com

Version bump: eztrace-1.1-10

---

lib/spack/spack/util/executable.py

Sphinx 3.0 inspects signatures for type hints, and when doing so will error on this method.  Thanks for spotting this quickly @adamjstewart.

verify `other.exe` attr exists before use in __eq__

---

var/spack/repos/builtin/packages/py-sphinx/package.py

Successfully installs on macOS 10.15.4 with Clang 11.0.3 and Python 3.7.6.

py-sphinx: add 3.0.0

---

var/spack/repos/builtin/packages/boost/package.py
var/spack/repos/builtin/packages/py-espressopp/package.py

Also reported in https://github.com/espressopp/espressopp/issues/300#issuecomment-609449146
Fix #15869

boost: boost-python in 1.72.0 broken with cxxstd=98

---

lib/spack/spack/util/environment.py

fixes #15775
`spack.util.environment_after_sourcing_files` compares the local environment against a shell environment after having sourced a file; but this ends up including the default shell profile and rc, which might differ from the local environment.
To change this, compare against the default shell environment, expressed here as (effectively) `source /dev/null`.

Source devnull in environment_after_sourcing_files

---

lib/spack/spack/test/data/sourceme_lmod.sh
lib/spack/spack/test/environment_modifications.py
lib/spack/spack/util/environment.py

fixes #15775
Add all the variables listed [here](https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html) to the list of those blacklisted when constructing environment modifications by sourcing files.

Blacklist Lmod variable modifications when sourcing files

---

var/spack/repos/builtin/packages/py-smart-open/package.py

The checksum for 1.8.4 was for the PyPI tarball, not the GitHub tarball. Switched to downloading from PyPI.

py-smart-open: fix url/checksum, add deps

---

var/spack/repos/builtin/packages/nccl/package.py

loads libibverbs via dlopen(), add dependency on rdma-core

nccl: supports infiniband/RoCE since 2.3.5-5

---

var/spack/repos/builtin/packages/pdt/package.py

Adds variant to pdt for building with pic support. As far as I could tell there was no way to explicitly disable this, only explicitly turn it on so there is no disabling in an else statement.

pdt: add PIC support as variant

---

var/spack/repos/builtin/packages/fish/package.py

Versions >= 3.1 do not support Autotools. Versions < 3 do not support building with CMake.

fish: add version 3.1.0 and switch to cmake

---

.github/ISSUE_TEMPLATE/build_error.md

This PR simplifies the template that describes the process of reporting a build error for a Spack package. It removes a lot of debugging things that I don't believe are particularly useful, and adds several new things. The simpler the process is, the more likely users are to fill in the template instead of ignoring it.

Simplify Build Error template

---

var/spack/repos/builtin/packages/intel/package.py

fixes #15811
See https://software.intel.com/en-us/articles/intel-compiler-and-composer-update-version-numbers-to-compiler-version-number-mapping

intel: fixed version number (update4 is 18.0.5)

---

var/spack/repos/builtin/packages/cryptsetup/package.py

cryptsetup: restrict the version of automake if @2.2.1

---

lib/spack/docs/pipelines.rst

Currently the `spack ci start` command does two things:
1. generate the pipeline (as the `.gitlab-ci.yml` file)
2. push that generated file to `DOWNSTREAM_CI_REPO` with a generated branch name
This second step is needed until gitlab provides the dynamic child pipelines feature.  In the meantime, there are issues with the various ways available for authenticating that `git push` in step 2 above.  This edit to the documentation will hopefully make the caveats clearer to users of the current system, until we can do away with pushing the generated pipeline file.

pipelines: Document dynamic generation limitations

---

var/spack/repos/builtin/packages/lua/package.py

Looks like something changed and a case was missed.
Function doesn't have a spec arg, need to dereference it off of
self.
Builds on OS X.

Fix lua build, missing deref of self for spec

---

var/spack/repos/builtin/packages/llvm/package.py

@trws 
Make use of Spack's builtin CUDA build system. This will allow us to express conflicts between CUDA arch and the CUDA Toolkit automatically.

LLVM Use Spack's Builtin CUDA support

---

var/spack/repos/builtin/packages/openfoam-org/package.py

fixes #15863
Since `openfoam-org` needs "FlexInclude.h" `flex` needs to be also a link dependency.

openfoam: modified flex to be a build + link dependency

---

var/spack/repos/builtin/packages/hugo/package.py

- Add info for version 0.68.3
- Add variant to package that enables the "extended" features.  It
works with both of the existing versions (not sure how far back it
goes, but confirmed that it's valid fro 0.53).
Tested on OS X with go@1.14.1.

Update hugo version and add extended variant

---

var/spack/repos/builtin/packages/environment-modules/package.py

New feature release in the v4 series.
Release announcement: https://timeline.noticeable.io/cbzeG7wTvAIqj21zbUmx/posts/modules-latest-aka-4-5-0-released
In addition to introducing new version 4.5.0, the quarantine variable list of Modules is updated to also include `LD_PRELOAD` in addition to `LD_LIBRARY_PATH` (to avoid side-effect when the first depends on the latter).

environment-modules: add version 4.5.0

---

var/spack/repos/builtin/packages/py-onnx/package.py

avoids a 'Callable has no attribute __abc_registry' error. See
onnx/onnx#2199 and python/typing#573

py-onnx: only use py-typing if python < 3.5

---

var/spack/repos/builtin/packages/f18/package.py

@trws 
Most likely this will be the last update to `f18` before it gets merged into `llvm.`
Changes included are:
- Update LLVM dependencies
- Support FIR
- Workaround for flang test failure

F18 update April 2020

---

var/spack/repos/builtin/packages/openjdk/package.py

The most recent change to the openjdk package set expand=False for all versions
of the package. This means only the unexpanded archive will be installed, which is not correct.

Fixed bad expand option for openjdk versions.

---

var/spack/repos/builtin/packages/py-tensorflow-estimator/package.py

Change the build to work again, and be more in line with the other
tensorflow packages. Add version 2.1.

py-tensorflow-estimator: fix build

---

var/spack/repos/builtin/packages/py-gpaw/package.py

From the documentation of GPAW, an additional variant of libvdwxc is added https://wiki.fysik.dtu.dk/gpaw/documentation/xc/libvdwxc.html
I suggest to enable the libvdwxc variant by default.

py-gpaw: Add libvdwxc as variant 

---

var/spack/repos/builtin/packages/glib/meson-gettext.patch
var/spack/repos/builtin/packages/glib/package.py

Newer versions of glib require Meson, so this PR adds support for that using a hybrid approach. glib@5.28: will be built using Meson, older versions still make use of Autotools.
I have done test builds of all versions added in this PR (plus a few dependents). I will also forward the Meson patch upstream soon.

glib: Add new stable versions

---

lib/spack/spack/compiler.py

Fixes https://github.com/spack/spack/issues/15776
Skip collection of compiler link paths if compiler does not define a verbose flag. This includes NAG.
`verbose_flag()` is not implemented for the NAG compiler in Spack. It is possible that `-V` is the appropriate choice for this. Since link-path detection logic involves compiling a C file, I'm not sure if it should be run at all if the available exe is meant for compiling Fortran.

NAG compiler fix: skip implicit RPATH detection

---

var/spack/repos/builtin/packages/py-torch/package.py

version/tag hack so that 1.4.0 is still workable.
see pytorch/pytorch#35149

py-torch: Fix v1.4.0 by adding v1.4.1

---

var/spack/repos/builtin/packages/podio/package.py

This adds a recipe for the PODIO datamodel library, which is used in HEP and was previously in HSF/hep-spack.

Add Recipe for PODIO

---

var/spack/repos/builtin/packages/netcdf-c/package.py
var/spack/repos/builtin/packages/netcdf-cxx4/package.py
var/spack/repos/builtin/packages/netcdf-fortran/package.py

It looks like the official FTP server (ftp://ftp.unidata.ucar.edu/pub/netcdf) provides only recent versions of the packages and according to the [official page](https://www.unidata.ucar.edu/downloads/netcdf/) older versions should be downloaded from GitHub. The [fallback solution](https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/) that we used doesn't offer old versions anymore too. Hence, it's time to finally switch to GitHub. Unfortunately, the tarballs that are available there have slightly different contents, which is why we need to update the checksums too. I am going to show the difference in the following comments.
Closes #15752

NetCDF packages: switch to the official FTP server

---

var/spack/repos/builtin/packages/primer3/package.py

- The Primer3 project moved to GitHub.
- update the URL
- compare the tarballs 2.3.7 from Sourceforge and github, no
significant differences (e.g. the Sourceforge tarball contained a
couple of "tmp" files).
- update the signature for the 2.3.7 tarball.
- @2.3.7 doesn't build with gcc@8.4.0, there's a dubious pointer/int
comparison that causes an error.  It was fixed upstream in newer
versions, apply simple patch to this version so that it continues to
be build-able with newer compilers.  See:
- https://github.com/primer3-org/primer3/issues/2
- https://github.com/primer3-org/primer3/issues/3
- Add info for @2.5.0, which builds cleanly.

primer3: move to github, add 2.5.0, fix 2.3.7

---

var/spack/repos/builtin/packages/aperture-photometry/package.py

Added a new version `2.8.2` because we could not find the URL that can get version `2.7.2`.tar.

aperture-photometry: add new version

---

var/spack/repos/builtin/packages/py-clint/package.py

depends on `py-args` in #15903

py-clint: new package at 0.5.1

---

var/spack/repos/builtin/packages/aws-parallelcluster/package.py

Signed-off-by: Tim Lane <tilne@amazon.com>

update URL and sha256 for aws-parallelcluster 2.6.1

---

var/spack/repos/builtin/packages/yaml-cpp/package.py

The old api is found in version 0.3.0 which uses a different release
name, so the url function was updated to properly find the older
releases. Also, this removes the boost constraint on the 0.3.0 version
which does not need it.

Update yaml-cpp package to enable for build of old api

---

lib/spack/spack/compilers/fj.py

This option is no longer needed, as the option "-Nclang" is now specified elsewhere.
Delete `setup_custom_environment`.

fujitsu compiler: Delete custom environment function.

---

var/spack/repos/builtin/packages/opencv/package.py

1. depends on blas when +lapack
2. set cuda nvcc flags for cuda_arch
3. let cuda/contrib builds work
4. depends on hdf5 when cuda/contrib
5. depends on ant when +java
6. allow protobuf version to be different
7. let opencv recompile it's protoc files.

opencv: assorted fixes

---

var/spack/repos/builtin/packages/hdf/package.py

This adds a boolean 'libtirpc' variant to the hdf package.
Default is false, which will reproduce previous behavior (which
was to rely either on system xdr headers/library, or have hdf use
it's builtin xdr lib/headers (which are only for 32 bit))
If true, a dependency is added on 'libtirpc', and the LIBS and
CPPFLAGS are updated in the configure command to find the libtirpc
library and xdr.h header.
This is needed as RHEL8 (and presumably other distros have or will be)
removed xdr.h from glib-headers package,which was breaking the previous
behavior of using system xdr headers.

hdf: Add option to link against libtirpc package

---

var/spack/repos/builtin/packages/gdal/package.py

If hdf was built with +libtirpc, we need to add -ltirpc to our link
flags.

gdal: Patch to support hdf linked against libtirpc

---

var/spack/repos/builtin/packages/gromacs/package.py

It is only a couple of files, so adding a variant seems unneeded.

gromacs: install header files

---

var/spack/repos/builtin/packages/go/package.py

Added latest minor release for Go: https://golang.org/doc/devel/release.html#go1.14.minor

Add Go versions 1.14.2 and 1.13.10

---

var/spack/repos/builtin/packages/tau/package.py

This PR adds new variants to the Tau package. Unfortunately, as best I could tell, Tau has no way to explicitly disable a config option, only enable it explicitly. Because of this this PR contains no logic for explicitly disabling these new config options. 
New variants are added for enabling profiling, profile parameters, profile callpaths, tau to slog2 conversion, and the cputime option.

tau: added new variants

---

var/spack/repos/builtin/packages/py-sacremoses/package.py

Successfully installs on macOS 10.15.4 with Python 3.7.6 and Clang 11.0.3, although there are some weird error messages during the installation process: https://github.com/alvations/sacremoses/issues/91

py-sacremoses: add new package

---

var/spack/repos/builtin/packages/ffmpeg/package.py
var/spack/repos/builtin/packages/libxml2/package.py
var/spack/repos/builtin/packages/py-youtube-dl/package.py

This PR adds the py-youtube-dl program. In addition, there are a couple
of dependency packages that needed to be updated.
* ffmpeg
This is needed by py-youtube-dl. However, the spack ffmpeg recipe does
not include a lot of options, specifically, a dependency on openssl for
working with the https protocol.
- Added updated version.
- Added variants for the different licensing options.
- Added "meta" variants for X and drawtext. These turn on/off several
options.
- Set variants and dependencies for many options. The defaults are based
on the configuration settings in ffmpeg.
- Set dependencies that were missing or that will likely get pulled in
from the system.
* libxml2
The ffmpeg+libxml2 variant initially failed to build. The issue is that
libxml2 sets the headers property to
include_dir = …

new package: py-youtube-dl + fixes for dependencies

---

lib/spack/spack/database.py
lib/spack/spack/test/cmd/uninstall.py

fixes #15773
The performance improvements done in #14693 where leaving the DB in an inconsistent state when specs were removed from it. This PR updates the DB internal state whenever it is written to file, but does that using a dictionary that still resides in memory to maintain the performance gain of #14693.

database: maintain in memory consistency when removing specs

---

var/spack/repos/builtin/packages/bart/Makefile.patch
var/spack/repos/builtin/packages/bart/bart_path.patch
var/spack/repos/builtin/packages/bart/package.py

This PR adds the BART (Berkeley Advanced Reconstruction Toolset)
package.
Despite the presence of CMake files, this package builds with a
Makefile. It looks like the project is moving away from cmake. The patch
for MKL has been committed upstream so should only be necessary for this
version of BART.  The Makefile patch is meant for working with Spack and
would not be useful upstream. The bart scripts are still setup to use
bart with the subcommands being individual binaries. This patches those
to use the single binary with built-in subcommands and assumes that
spack is providing the TOOLBOX environment variable and setting PATH.

new package: BART

---

var/spack/repos/builtin/packages/boost/darwin_clang_version.patch
var/spack/repos/builtin/packages/boost/package.py

Applying to boost @1.56.0:1.72.0 as that's the version range, where this patch can be cleanly applied. I was not able to test this myself, but got positive feedback.
See: https://github.com/boostorg/build/issues/440
See: https://github.com/macports/macports-ports/pull/6726
Maintainer-Ping: @hainest

boost: Fix for Version Comparison on Newer Clang on Darwin

---

var/spack/repos/builtin/packages/py-sacremoses/package.py

I just added this package yesterday and reported a strange build warning at https://github.com/alvations/sacremoses/issues/91. A new release contains a fix, so I figure there's no point in keeping the old release in the package.
Successfully builds on macOS 10.15.4 with Clang 11.0.3 and Python 3.7.6.

py-sacremoses: add new version

---

var/spack/repos/builtin/packages/bazel/package.py

To better help in troubleshooting build issues. Job limit might also
help with the memory limit issues we've been seeing.

bazel: increase logging during build, set job limit

---

var/spack/repos/builtin/packages/rust/package.py

Fixes #16007 
Dependencies come from https://github.com/rust-lang/rust#building-on-nix
@AndrewGaspar

Rust: add missing dependencies

---

var/spack/repos/builtin/packages/py-vcf-kit/package.py

depends on `py-clint` pending in #15905

py-vcf-kit: new package at 0.1.6

---

lib/spack/spack/build_systems/sourceware.py
lib/spack/spack/pkgkit.py
var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/elfutils/package.py
var/spack/repos/builtin/packages/libffi/package.py
var/spack/repos/builtin/packages/lvm2/package.py
var/spack/repos/builtin/packages/valgrind/package.py

sourceware.org is often quite overrun and times out or returns in certificate errors.
Since libffi, bzip2, elfutils, etc. are quite fundamental in build chains, let's add some official mirrors.
This should fix the bi-daily errors I see on nightly integration tests.

sourceware.org: mirror mixin

---

var/spack/repos/builtin/packages/muscle/package.py

The build directory was changed for this Makefile package in newer versions, but I haven't been able to modify the `build_directory` at build time, so I used a symlink to keep the package working.
Is there a better way to approach this?

muscle: add 3.8.31

---

var/spack/repos/builtin/packages/pfft/package.py

pfft had been checking for +double, etc. in fftw spec, which no longer
are present (replaced by Multivalued variant precision).

pfft: fix to handle 'precision' variant in fftw

---

var/spack/repos/builtin/packages/py-tokenizers/package.py

`py-transformers` explicitly requires _exactly_ `py-tokenizers` 0.5.2.
Had some discussion with @AndrewGaspar about the problems with Rust nightly/dev and needing internet access to download dependencies. It seems he's got some ideas on how to fix this in the future.

py-tokenizers: add 0.5.2

---

var/spack/repos/builtin/packages/rust/package.py

This PR adds support for building pre-release versions of Rust, including the latest beta and nightly releases, along with building from the master branch at https://github.com/rust-lang/rust.
These releases all only build with `-n`/`--no-checksum`.
The "beta" and "nightly" versions are not "advertised" because spack requires all `version`s to have a checksum, unless they're a source control version.
"beta" and "nightly" _should_ build offline, but I haven't tested it. "master" will not because it fetches its Rust dependencies from Rust's package manager.
It's hypothetically possible to support specific nightly releases of Rust, but this PR doesn't support that. If anybody is interested in implementing this, the source code for a specific nightly release of Rust is hosted at a slightly …

Add support for pre-release builds of Rust (beta, master, nightly)

---

lib/spack/docs/basic_usage.rst
lib/spack/docs/module_file_support.rst
lib/spack/docs/packaging_guide.rst

Package extensions: fixed a link in docs

---

var/spack/repos/builtin/packages/tau/package.py

It was brought to my attention that my recently added variants to the Tau package have been deprecated or are redundant and should not be included. This pull request reverses changes made in #16005

tau: remove deprecated variants

---

var/spack/repos/builtin/packages/py-memory-profiler/package.py

Successfully installs on macOS 10.15.4 with Python 3.7.6 and Clang 11.0.3.

py-memory-profiler: add new version

---

var/spack/repos/builtin/packages/netcdf-cxx4/package.py

This PR adds the following variants for building netcdf-cxx4:
- PIC
- DAP
- JNA
- Doxygen documentation
- ncgen4
- pnetcdf
- netcdf4
- shared libraries
- static libraries
All variants have explicit toggles for enable/disable and I did my best to preserve existing behaviors with the default values.

netcdf-cxx4: Add new variants

---

lib/spack/spack/package.py

Replaces #15559 
This PR allows status values to be lists since not all versions will necessarily return the same command exit code. 
Testing has been performed using a (local) version of the openmpi test (see #15456 ).

install tests: added support for multiple test command status values (updated)

---

var/spack/repos/builtin/packages/petsc/package.py

Minor typo that causes the concretizer to miss adding the `hypre` dependency due to a missing `:`.

Fix PETSc typo

---

var/spack/repos/builtin/packages/charliecloud/package.py

* raise an appropriate error when attempting to build
`Charliecloud` on Mac OSX, since it will otherwise fail
with a more confusing configure stage link check failure
cc @reidpr @junghans 
Technically, the configure stage will almost certainly fail with `FreeBSD` as well since linker checks are Linux-specific at the moment, but maybe start with this for now.

MAINT: Charliecloud OSX error

---

var/spack/repos/builtin/packages/libgit2/package.py
var/spack/repos/builtin/packages/libssh2/package.py

Fixes #15887 
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/libssh2-1.8.0-bwme3nb5vpustesfddxwqbevjk5zm2gd/lib/libssh2.dylib 
/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/libssh2-1.8.0-bwme3nb5vpustesfddxwqbevjk5zm2gd/lib/libssh2.dylib:
libssh2.1.dylib (compatibility version 1.0.0, current version 1.0.1)
/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/openssl-1.1.1f-hsoj6gr47qcrz623ak4ngcccg4hmcwpn/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/openssl-1.1.1f-hsoj6gr47qcrz623ak4ngcccg4hmcwpn/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
/usr/lib/libSystem.B.dylib …
```

libssh2: fix linking on macOS

---

var/spack/repos/builtin/packages/grpc/package.py

Current default version was missing a dependency. Usually provided via `git submodule`, `grpc` release packages are known to be missing vendored dependencies. Fix #15619. Adding myself as maintainer.

Fix grpc@1.27.0:

---

lib/spack/spack/build_systems/xorg.py
lib/spack/spack/pkgkit.py
lib/spack/spack/test/build_systems.py
var/spack/repos/builtin.mock/packages/mirror-gnu-broken/package.py
var/spack/repos/builtin.mock/packages/mirror-gnu/package.py
var/spack/repos/builtin.mock/packages/mirror-sourceware-broken/mirror-gnu-broken/package.py
var/spack/repos/builtin.mock/packages/mirror-sourceware-broken/package.py
var/spack/repos/builtin.mock/packages/mirror-sourceware/package.py
var/spack/repos/builtin.mock/packages/mirror-xorg-broken/package.py
var/spack/repos/builtin.mock/packages/mirror-xorg/package.py
var/spack/repos/builtin/packages/util-macros/package.py

According to my nightly CI/CD tests, x.org is another large provider of software in common build chains that is often down.
Added a hand-selected amount of mirrors that is well up-to-sync. Tested with `util-macros` that has a quite "recent" patch release.
Other packages to follow in an individual PR.

x.org: mirror mixin

---

var/spack/repos/builtin/packages/libtree/package.py

Bumps versions of https://github.com/haampie/libtree

libtree: new versions 1.0.4 and 1.1.0

---

var/spack/repos/builtin/packages/py-cmake-format/package.py
var/spack/repos/builtin/packages/py-six/package.py

* Provide a new python package `py-cmake-format`. This package is similar to the familiar _clang-format_, but it standardizes the format of CMake files, https://pypi.python.org/pypi/cmake-format
* Requires a slightly newer version of `py-six`, so I updated that `package.py` in the same PR.
```
cmake-format project provides Quality Assurance (QA) tools for cmake.
- cmake-annotate can generate pretty HTML from your listfiles
- cmake-format   can format your listfiles nicely so that they don’t look 
like crap.
- cmake-lint     can check your listfiles for problems
- ctest-to       can parse a ctest output tree and translate it into a more 
structured format (either JSON or XML).
```

New package: py-cmake-format

---

lib/spack/spack/repo.py
lib/spack/spack/test/cmd/list.py

Currently, tags are case sensitive, which is unintuitive:
```console
$ spack list -t hpc
==> 2 packages.
nek5000  nektools
$ spack list -t HPC
==> 1 packages.
mfem
$ spack list -t Hpc
==> 0 packages.
```
This change makes them case insensitive:
```console
$ spack list -t hpc
==> 3 packages.
mfem  nek5000  nektools
$ spack list -t HPC
==> 3 packages.
mfem  nek5000  nektools
$ spack list -t Hpc
==> 3 packages.
mfem  nek5000  nektools
```

Make tags case insensitive

---

var/spack/repos/builtin/packages/libsigsegv/package.py
var/spack/repos/builtin/packages/libsigsegv/test/smoke_test.c
var/spack/repos/builtin/packages/libsigsegv/test/smoke_test.out

Replaces #15091 
The preliminary "smoke" tests for `libsigsegv` involve building a small C program and ensuring the output from running it match expectations.  This PR updates the previous one to use the latest version of `run_test` from `features/spack-test` branch.
Compilation options were gleaned from those generated during the normal test build process for the library.

tests: Preliminary libsigsegv smoke tests (updated)

---

var/spack/repos/builtin/packages/mesa/package.py

Mesa links against libtinfo so needs to depend on ncurses. It also needs
a little help finding the library directory so an LDFLAGS configure
option is added.

Add ncurses+termlib dependency to mesa

---

lib/spack/spack/cmd/buildcache.py

provided (#15662).
Prior to this fix, the checked Spec object would not be populated, and
concretization would fail.

Bugfix: For spack buildcache check, Handle specs where only the hash is

---

etc/spack/defaults/darwin/modules.yaml

This commit removes the `DYLD_LIBRARY_PATH` variable from the default
`modules.yaml` for darwin. The rationale behind deleting this
environment variable is that paths in this environment variable take
precedence over the default locations of libraries (usually the
install path of the library), which can lead to linking errors in some
circumstances. For example, executables intended to link with Apple's
system BLAS and LAPACK will instead link to a spack-installed
implementation (e.g., OpenBLAS), causing runtime errors.
These errors are resolved by instead relying on paths set in
`DYLD_FALLBACK_LIBRARY_PATH`, which is lower in precedence than default
locations of libraries.

darwin: cut DYLD_LIBRARY_PATH from default modules

---

var/spack/repos/builtin/packages/sz/package.py

At least the v2.0.2.0 tar ball contains compiled object files etc, which
cause the build to fail on other architectures (ppc64le in particular), so
this patch adds a `make clean` after configuring first.

fix sz package

---

lib/spack/spack/build_systems/autotools.py

During the `autoreconf` phase, we need to explicitly pass a list of directories in which to look for m4 headers. Previously, we only checked for `pkgconfig`, but there are many other packages that provide m4 headers. For example, among the software I currently have installed, I see the following packages with m4 headers:
* automake
* cmake
* freetype
* gettext
* libgpg-error
* libksba
* libassuan
* curl
* libgcrypt
* libtool
* npth
* autoconf-archive
For a concrete example, while working on #15783, autoreconf failed unless autoconf-archive was added. I've also had problems with gettext being missing in the past.

AutotoolsPackage: add aclocal for all build deps

---

var/spack/repos/builtin/packages/mpfr/package.py

For the `mpfr` package, we use the aggregated `allpatches` patch for each version. Unfortunately, this patch is added to from time-to-time, so the checksum changed. This PR updates the checksum, and switches older patched to sha256. The older patches did not change, only the latest patch.
This PR also adds a dependency on `autoconf-archive`. Without this, `mpfr` fails during the build stage with the following error message:
```
configure:14208: error: possibly undefined macro: AX_PTHREAD
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
make: *** [configure] Error 1
make: *** Waiting for unfinished jobs....
```
Depends on #15784

MPFR: fix patch checksum, add dependencies

---

lib/spack/env/cc
lib/spack/spack/test/cc.py

Spack attempts to inject it's paths just before the actual
system include directories. Currently, if a build utilizes
-isystem, Spack's headers will be injected using -I, and that
effectively inserts them before any specified -isystem headers.
This leads to unexpected failures. Here, we assume that if a build
attempts to use -isystem (implying that the underlying
compiler supports the flag) - we change to injecting the paths
into the end of the -isystem paths. There is a potential
concern if the build includes system paths in -I *and*
uses -isystem, but I think that's probably an unlikely usage.
See:
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
Fixes #14488, Fixes #14234

compiler wrappers: fix out-of-order injection scenario

---

var/spack/repos/builtin/packages/jdk/package.py

The version number I used doesn't match other versions in the package; but it's what Oracle is using, even in `-version`. Since this is the only version 14, I don't know whether it should be `14.2020.03_17`, or if they'll do more traditional versioning later.
```console
$ java -version
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```
Note that the previous "preferred" version isn't available from oracle as a download any longer; so this update is required to get the package to work again.

Version bump: jdk 14

---

lib/spack/spack/relocate.py
lib/spack/spack/test/packaging.py
lib/spack/spack/test/relocate.py

This PR introduces trivial refactoring in:
- `get_existing_elf_rpaths`
- `get_relative_elf_rpaths`
- `get_normalized_elf_rpaths`
- `set_placeholder`
mainly to be more consistent with practices used in other parts of the code and to simplify functions locally. It also adds or reworks unit tests for these functions and extends their docstrings.

Add more unit tests to "spack.relocate"

---

var/spack/repos/builtin/packages/netcdf-c/package.py

If hdf was built with +libtirpc, we need to add -ltirpc to our link
flags.

netcdf-c: Patch to support hdf linked against libtirpc

---

var/spack/repos/builtin/packages/netcdf-c/package.py
var/spack/repos/builtin/packages/netcdf-fortran/package.py

This PR adds the following variants for building netcdf-fortran:
- PIC
- DAP
- JNA
- Doxygen documentation
- ncgen4
- pnetcdf
- netcdf4
All variants have explicit toggles for enable/disable and I did my best to preserve existing behaviors with the default values.

netcdf-fortran: add new variants

---

lib/spack/spack/cmd/dev_build.py
lib/spack/spack/installer.py
lib/spack/spack/package.py
lib/spack/spack/test/cmd/dev_build.py
share/spack/spack-completion.bash

This is a proposal to change or add to the `--until` option of `spack dev-build`.
Often, I want to run my own CMake/configure/manually-build-step and taking CMake packages as an example, there is often no phase before the first `cmake` phase to stop *after* (this is what `--until` does).
`--until` currently stops *after* a phase, which makes `-u install` (or whatever is the last phase of a package) useless as this is the same as no option. I would generally propose to change the meaning of `-u|--until` to stop at start of that specified phase, but in case we want to avoid breakage we can also add something like `-b|--before`.
Note: somehow the build environment is not set up when testing this, e.g. no `LD_LIBRARY_PATH` and `CMAKE_PREFIX_PATH` is set on `spack dev-build --before cmake …

dev-build: stop before phase

---

lib/spack/spack/cmd/dev_build.py
lib/spack/spack/test/cmd/dev_build.py
share/spack/spack-completion.bash

Add a `--drop-in <shell>` option to `spack dev-build`. This option will automatically run a `spack build-env <spec> -- <shell>` at the end of a `dev-build`, e.g. to quickly drop-and-devel into a build phase of a package.
Example usage:
```
spack dev-build --before cmake --drop-in bash openpmd-api@develop
```

dev-build: --drop-in <shell>

---

lib/spack/spack/architecture.py
lib/spack/spack/cmd/compiler.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/data/config/packages.yaml

For tests that use the real Spack package repository, the config needs to avoid using MPI providers that are not intended to be installed by Spack. Without this, it is possible that Spack tests which concretize the MPI virtual will end up trying to use an implementation that it shouldn't (e.g. one that is always provided externally).
See: https://github.com/spack/spack/pull/15666 (and specifically the tests for it at https://travis-ci.org/github/spack/spack/jobs/672203234)

Set MPI providers for test config

---

var/spack/repos/builtin/packages/openmpi/package.py

Open MPI will detect and link against GPFS if it is present on the system. This variant allows this to be disabled, even if GPFS is present.
Closes #15746

Add a gpfs variant to openmpi package

---

lib/spack/spack/cmd/__init__.py
lib/spack/spack/test/cmd/is_git_repo.py

If spack is checked out in a [git worktree](https://git-scm.com/docs/git-worktree), all git-related commands fail because the `spack_is_git_repo()`-check is not thorough enough.
When developing in a feature-branch in a seperate worktree, this is annoying as all unittests regarding git-related spack commands fail, cluttering the test results with false-positives.

Fix git-related commands not working in worktrees

---

lib/spack/docs/environments.rst
lib/spack/spack/spec_list.py
lib/spack/spack/test/cmd/env.py

Fixes #15231 
>It would be very useful to be able to use definitions as requirements in specs so as to make environments very easy to share and reuse:
> For example we declare the compiler, core compiler and mpi:
```
definitions:
- mygcc: [ gcc@8.3.0 ]
- mybasegcc: [ gcc@4.8.5 ]
- mympi: [ mpich@3.3.2+slurm pmi=pmi2 ]
specs:
- matrix:
- [$mygcc]
- [$%mybasegcc]
- matrix:
- [openblas@0.3.8, $mympi , fftw~mpi]
- [$%mygcc ]
- matrix:
- [openfoam,  fftw]
- [$^mympi]
- [$%mygcc]
```
This feature only applies to the `^` and `%` sigils, as only compilers and dependencies have an inherent overlap with package names.
@ilbiondo @alalazo

environments: allow sigils to apply to entire reference

---

lib/spack/spack/directory_layout.py
lib/spack/spack/test/config_values.py

Bug report from slack:
> Hi All,
> I've set: `install_hash_length: 4` in my config.yaml, yet when I install software, Spack still uses the full length hash.  This is correctly picked up when I type: `spack config get config`
>
> I know that UI can use the alternate method: `install_path_scheme: '{name}/{version}/{hash:7}'` but just thought I'd ask to see if anyone else had noticed this?
>
> (I'm using 0.14.1)
This bug was caused by comparing a value that is case-insensitive against a lower-case string. This PR fixes it and adds testing.
Developer note: This PR adds a new testing file `lib/spack/spack/test/config_values.py` for testing that configuration values are picked up properly. The existing `lib/spack/spack/test/config.py` is focused on the internal functions of the config system, …

Bugfix: config:install_hash_length ignored

---

var/spack/repos/builtin/packages/openfoam/package.py

I want `openfoam` to recognize Fujitsu compiler.
So, I created directory included setting information of Fujitsu compiler based on Clang.

openfoam: correspond to build with Fujitsu compiler.

---

.codecov.yml
.github/workflows/macos_unit_tests.yaml
.travis.yml
README.md
lib/spack/spack/test/package_sanity.py

Add unit test on MacOS using Github Actions

---

lib/spack/spack/build_systems/intel.py

- seems to be a workaround for #11140 and #12493 not finding an appropriate libfabrics.so
Fixes #11140
Fixes #12493
Fixes #15522

add libfabric/lib to SPACK_COMPILER_EXTRA_RPATHS when bulding with intelmpi@2019+

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/cmd/install.py
lib/spack/spack/installer.py
lib/spack/spack/test/installer.py
share/spack/spack-completion.bash

Fixes #15182 
Fixes #15684 
This change restores the ability to terminate `spack install` using `ctrl-c`*.
It also adds support for a `--fail-fast` install option.  Instead of proceeding with a "best effort" installation of packages associated with a `spack install`, `spack install --fail-fast` will terminate the installation process upon detection of an install failure (i.e., by the process or another, overlapping install process).
*Note that I am able to successfully terminate an installation using `develop` by entering `ctrl-c` twice in a row.  This PR reduces the number of times it needs to be entered to one.
TODO
------
Follow-On Work
----------------
- If #15415 is merged before this PR, `environment.py` will need to be modified to support `--fast-fail`

features: terminate installs on ctrl-c and --fail-fast failures

---

lib/spack/spack/cmd/modules/__init__.py
lib/spack/spack/modules/common.py
lib/spack/spack/test/cmd/module.py
lib/spack/spack/test/modules/tcl.py

Uncovered after we switched our CI to generate modules for packages one-by-one rather than in bulk.
Generating a module for a single package overwrote the complete module index with a single entry, and broke our downstream Spack instances that needed the upstream module index (with all packages inside it).

Module index should not be unconditionally overwritten

---

lib/spack/spack/build_environment.py
lib/spack/spack/util/environment.py

It happens that the listed variables (see the changes) are set in the environment and affect the installation process of Autotools packages. With this PR, Spack unsets them when it's run with `--clean` flag (by default).
Probably, putting this logic to the `setup_environment` of `AutotoolsPackage` is better but I don't know the best way to get the value of `args.dirty` from there.

Unset environment variables that are used by Autotools packages.

---

var/spack/repos/builtin/packages/mpich/package.py

This is in principle supported already, but requires a patch to avoid build errors.
Closes https://github.com/spack/spack/issues/15302.

mpich: Allow building with external hwloc library

---

var/spack/repos/builtin/packages/gcc/package.py

On Centos (RHEL) 7, a static libstdc++ is not available by default and
was required to compile stage1.
Now we use static libstdc++ only for stage > 1.
Almost like in PR #8972 binutils dependency has been modified to 'run', but also to 'build' instead of 'link'.
Fixes #17294
Fixes #17325

Fix gcc + binutils compilation.

---

lib/spack/spack/main.py

fixes #12228
The issue has all the relevant details. Basically an activated environment and `--config-scope` do not work together.
The fix is by Tim Fuller @tjfulle who gets all the credit for analyzing the problem and suggesting this fix.
The fix looks reasonable to me, so I decided to create a PR from it.

Fix #12228: make environments and --config-scope work

---

var/spack/repos/builtin/packages/libimobiledevice/package.py

This PR adds `libimobiledevice, needed for iOS interaction from various Unix systems.
There's a small catch with this PR that I'm not sure what to do with; the `1.2.0` version (latest) requires `SSLv3` which we don't have variants for in `openssl`. As this is deprecated by the IETF, I don't want to add that variant.
As such, should I simply remove the `1.2.0` version from this package for now, or leave it so that people can link OpenSSL manually?

libimobiledevice: new package

---

lib/spack/spack/spec.py

This prints out debug information about which specs are applying which constraints.
Spack's greedy concretizer can make mistakes that later cause it to think that a spec cannot be concretized. See for example https://github.com/spack/spack/issues/14792. At the point where it encounters a conflict, it is difficult to know which other specs applied the constraints that are now causing a conflict. This prints out a list of all the constraints applied by all specs. If you get an error like
```
python requires gettext variant ~libxml2, but spec asked for +libxml2
```
you can pipe the debug output to a file and then grep for instances of
* dependencies requiring gettext+libxml2
* dependencies asking for gettext by itself (and if this occurs early enough in the concretization, Spack can choose a …

More debug info for concretizer errors

---

var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/trilinos/package.py

... in order to not break the installation of older versions.
I hope this fixes [issue 15423](https://github.com/spack/spack/issues/15423)
Also adjusting dealii package to just explicitly set GO if trilinos >= 12.18.1 is installed and use the old default otherwise.
Maybe this is a good chance to also merge [pull request 14215](https://github.com/spack/spack/pull/14215)

trilinos: setting old GO default values for older trilinos versions

---

lib/spack/spack/cmd/dev_build.py
lib/spack/spack/cmd/develop.py
lib/spack/spack/cmd/install.py
lib/spack/spack/concretize.py
lib/spack/spack/directives.py
lib/spack/spack/environment.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/installer.py
lib/spack/spack/package.py
lib/spack/spack/spec.py
lib/spack/spack/stage.py
lib/spack/spack/test/cache_fetch.py
lib/spack/spack/test/cmd/dev_build.py
lib/spack/spack/test/cmd/develop.py
lib/spack/spack/test/cmd/location.py
lib/spack/spack/test/cmd/undevelop.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/concretize_preferences.py
lib/spack/spack/test/git_fetch.py
lib/spack/spack/test/hg_fetch.py
lib/spack/spack/test/install.py
lib/spack/spack/test/spec_semantics.py
lib/spack/spack/test/svn_fetch.py
lib/spack/spack/variant.py
share/spack/spack-completion.bash
var/spack/repos/builtin.mock/packages/dependent-of-dev-build/package.py

closes #18401 
**Updated 2020-05-15**
fixes #12003
With this feature, we allow developers to specify package(s) they are working on in an environment.
For example, if I were a developer of both `trilinos` and `hdf5`, I could specify in an environment
```
spack:
specs:
- trilinos
- hdf5
- mpich
dev-build:
trilinos:
source: /path/to/my/trilinos/source
version: mytrilinosversion
hdf5:
source: /path/to/my/hdf5/source
version: myhdf5version
concretization: together
```
I could then install my development versions of both packages, with trilinos using my development version of hdf5 with the simple command `spack install`.
TODO:
MOVED TO OTHER PRs:
Proposed workflow:
1. `spack env create myenv`  create an environment managed by Spack
2. `spack env activate myenv`  tell spack to use that …

Environments: specify packages for developer builds

---

lib/spack/spack/hooks/sbang.py
lib/spack/spack/paths.py
lib/spack/spack/test/sbang.py
var/spack/repos/builtin/packages/gobject-introspection/package.py

`sbang` is not always accessible to users of packages, e.g., if Spack
is installed in someone's home directory and they deploy software
for others.  Avoid this by:
1. Always installing the `sbang` script in the `install_tree`
2. Relocating binaries to point to the copy in the `install_tree` 
and not the one in the Spack installation.

sbang: put sbang in the install_tree

---

lib/spack/spack/cmd/modules/lmod.py
lib/spack/spack/cmd/modules/tcl.py
lib/spack/spack/modules/common.py
lib/spack/spack/test/cmd/module.py
share/spack/spack-completion.bash

This PR introduces the command
```
spack module tcl setdefault <package>
```
similar to the lmod command.
Closes #13714

Add setdefault option to tcl module
