spack/spack

var/spack/repos/builtin/packages/pegtl/package.py
=> pegtl: version bump

var/spack/repos/builtin/packages/angsd/package.py
=> New pacakge angsd

var/spack/repos/builtin/packages/ngmlr/package.py
=> Add package for ngmlr

var/spack/repos/builtin/packages/beast2/package.py
=> New package beast2

var/spack/repos/builtin/packages/muscle/package.py
=> Add package for muscle

var/spack/repos/builtin/packages/primer3/package.py
Built and mildly tested on CentOS 7.
=> Add package for primer3

var/spack/repos/builtin/packages/intel-parallel-studio/package.py, var/spack/repos/builtin/packages/intel/package.py
=> Update intel-parallel-studio and intel packages

lib/spack/docs/getting_started.rst
I was recommended to make a pull request to fix the examples packages.yaml for cray systems in issue #4566. The details of the problem in the original packages.yaml is in the issue.
=> Fix packages.yaml for Cray

var/spack/repos/builtin/packages/kahip/package.py
possible alternative to metis, scotch.
=> new package for KaHIP

var/spack/repos/builtin/packages/antlr/gcc.patch, var/spack/repos/builtin/packages/antlr/package.py
The tarball used until now is not available anymore.
=> antlr: Use official sources

var/spack/repos/builtin/packages/trilinos/package.py
=> Trilinos: add ForTrilinos resource

var/spack/repos/builtin/packages/cntk/lock-file.patch, var/spack/repos/builtin/packages/cntk/package.py
See - https://github.com/Microsoft/CNTK/issues/62
=> Apply patch to allow users to change path of lock file

var/spack/repos/builtin/packages/mpix-launch-swift/package.py
A way to launch MPI applications inside MPI applications
=> mpix-launch-swift: MPIX_Launch library tailored to work using swift-t

var/spack/repos/builtin/packages/dataspaces/package.py
This is a package for installing DataSpaces (http://www.dataspaces.org) server binary and libraries.  This package was created as part of the CODAR ECP project in support of the Savanna reference framework.
DataSpaces is a middleware for asynchronous in-memory coupling of applications using dedicated staging nodes.
=> New package: DataSpaces

var/spack/repos/builtin/packages/ampliconnoise/package.py
Adding new package ampliconnoise
=> Package ampliconnoise

var/spack/repos/builtin/packages/bucky/package.py
=> New package bucky

var/spack/repos/builtin/packages/butter/package.py
=> New package butter

var/spack/repos/builtin/packages/cdbfasta/package.py
=> cdbfasta: new package

var/spack/repos/builtin/packages/cap3/package.py
=> cap3: new package

var/spack/repos/builtin/packages/emboss/package.py
=> emboss: new package

var/spack/repos/builtin/packages/isaac-server/package.py
adds a new release of isaac-server.
follow-up to #4685, forgot to add the new version to the second package, too :)
=> ISAAC Server 1.3.1: New version

var/spack/repos/builtin/packages/tealeaf/package.py
New Package.  TeaLeaf Proxy Application
=> Added TeaLeaf Package

var/spack/repos/builtin/packages/quinoa/package.py
=> New package: quinoa

var/spack/repos/builtin/packages/tophat/package.py
=> Add a package for tophat

var/spack/repos/builtin/packages/comd/package.py
I hope everything works fine. I'm open to any suggestions.
=> New package: CoMD

var/spack/repos/builtin/packages/ea-utils/package.py
=> ea-utils: new package

var/spack/repos/builtin/packages/csdp/package.py
=> csdp: new pacakge

var/spack/repos/builtin/packages/exabayes/package.py
=> exabayes: new pacakge

var/spack/repos/builtin/packages/miniaero/package.py
Added Proxy Application MiniAero
=> New Package: MiniAero

var/spack/repos/builtin/packages/hpccg/package.py
=> New Package: HPCCG

var/spack/repos/builtin/packages/miniamr/package.py
=> New Package: MiniAMR

var/spack/repos/builtin/packages/fseq/package.py
=> fseq: new package

var/spack/repos/builtin/packages/genometools/package.py
adding new package genometools
=> genometools: new package

lib/spack/docs/packaging_guide.rst
=> Typo: submdoules -> submodules

var/spack/repos/builtin/packages/libsvm/package.py, var/spack/repos/builtin/packages/mitofates/package.py
adding new packages mitofates and libsvm
=> mitofates: new package and dependency libsvm

var/spack/repos/builtin/packages/mcl/package.py
=> mcl: new package

var/spack/repos/builtin/packages/daligner/package.py
=> Add package for daligner

var/spack/repos/builtin/packages/maverick/package.py
=> maverick: new package

var/spack/repos/builtin/packages/infernal/package.py
=> infernal: new package

var/spack/repos/builtin/packages/idba/package.py
=> idba: new package

var/spack/repos/builtin/packages/graphmap/package.py
=> graphmap: new package

var/spack/repos/builtin/packages/cloverleaf3d/package.py
Adding CloverLeaf3D Package.  Still using build_targets while #4704 is open.
=> New Package: CloverLeaf3D

var/spack/repos/builtin/packages/hybpiper/package.py, var/spack/repos/builtin/packages/spades/package.py
Adding new package hybpiper along with spades dependency
=> hybpiper: new package

var/spack/repos/builtin/packages/pathfinder/package.py
=> New Package: Pathfinder

var/spack/repos/builtin/packages/minife/package.py
=> New Package: miniFE

var/spack/repos/builtin/packages/somatic-sniper/package.py
=> Add package for Somatic Sniper

var/spack/repos/builtin/packages/muse/package.py
=> Add package for MuSE

var/spack/repos/builtin/packages/orfm/package.py
=> orfm: new package

var/spack/repos/builtin/packages/minismac2d/package.py
Adding miniSMAC2d package.  This is a fortran package that uses the C preprocessor to handle macros.  Does spack have any support for using cpp directly?
=> New Package: miniSMAC2D

var/spack/repos/builtin/packages/libbeagle/package.py, var/spack/repos/builtin/packages/mrbayes/package.py
adding new packages mrbayes and dependency libbeagle
=> mrbayes: new package

var/spack/repos/builtin/packages/qhull/package.py, var/spack/repos/builtin/packages/qhull/qhull-unused-intel-17.02.patch
See issue [here](https://github.com/qhull/qhull/issues/24)
=> qhull: fix compilation with Intel 17.02

var/spack/repos/builtin/packages/partitionfinder/package.py
adding new package partitionfinder
=> partitionfinder: new package

var/spack/repos/builtin/packages/tig/package.py
This adds a package for [tig](https://jonas.github.io/tig/), which is an ncurses-based text-mode interface for git. It is a simple autotools project.
=> New Package: tig

var/spack/repos/builtin/packages/pcma/package.py
=> pcma: new package

lib/spack/spack/build_systems/cmake.py, var/spack/repos/builtin/packages/bcl2fastq2/package.py, var/spack/repos/builtin/packages/clfft/package.py, var/spack/repos/builtin/packages/clhep/package.py, var/spack/repos/builtin/packages/cpprestsdk/package.py, var/spack/repos/builtin/packages/isaac-server/package.py, var/spack/repos/builtin/packages/isaac/package.py, var/spack/repos/builtin/packages/quinoa/package.py, var/spack/repos/builtin/packages/spades/package.py
Fixes #4383 if everyone agrees that this is the right thing to do. I tried to make it behave similarly to `AutotoolsPackage`.
@ax3l Can you test this?
=> Change path to CMakeLists.txt to be relative to root, not pwd

var/spack/repos/builtin/packages/raxml/package.py
=> raxml: new package

var/spack/repos/builtin/packages/busco/package.py
=> New package busco

var/spack/repos/builtin/packages/price/package.py
=> price: new package

var/spack/repos/builtin/packages/poamsa/package.py
=> poamsa: new package

var/spack/repos/builtin/packages/xproto/package.py
=> Always install xproto in serial

var/spack/repos/builtin/packages/kentutils/package.py
=> kentutils: new pacakge

var/spack/repos/builtin/packages/snbone/package.py
Submitted new separate pull requests as per PR #4738.
=> New Package: SNbone.

var/spack/repos/builtin/packages/satsuma2/package.py
=> satsuma2: new package

var/spack/repos/builtin/packages/salmon/package.py
=> salmon: new package

var/spack/repos/builtin/packages/sickle/package.py
=> sickle: new package

var/spack/repos/builtin/packages/seqprep/package.py
=> seqprep: new package

var/spack/repos/builtin/packages/smalt/package.py
=> smalt: new package

var/spack/repos/builtin/packages/singularity/package.py
adding new package singularity
=> singularity: new package

var/spack/repos/builtin/packages/lmdb/package.py
Also improves the description a bit.
Edit: I also added a pkg-config file to make LMDB easier to use. At least Debian and Fedora also do this.
=> lmdb: Update to 0.9.21

var/spack/repos/builtin/packages/sortmerna/package.py
=> sortmerna: new package

var/spack/repos/builtin/packages/revbayes/package.py
=> revbayes: new package

var/spack/repos/builtin/packages/sparta/package.py
=> sparta: new package

var/spack/repos/builtin/packages/mvapich2/package.py
Add cuda variant for mvapich2 and mark bison as a build-time dependency.
=> Add cuda variant for mvapich2.

var/spack/repos/builtin/packages/py-theano/package.py
Allow users to install theano from git
=> Add a py-theano version from git repo

var/spack/repos/builtin/packages/stringtie/package.py
=> stringtie: new package

var/spack/repos/builtin/packages/subread/package.py
Adding new package subread -- I used spack's charm package as a template for determining system/Makefile that needs to be used
=> subread: new package

var/spack/repos/builtin/packages/structure/package.py
adding new package "structure"
=> structure: new package

var/spack/repos/builtin/packages/swarm/package.py
=> swarm: new package

var/spack/repos/builtin/packages/stacks/package.py
=> stacks: new package

var/spack/repos/builtin/packages/gobject-introspection/package.py
discovered while building octave.
=> fix GobjectIntrospection on Darwin

var/spack/repos/builtin/packages/zstd/package.py
This adds the 1.3.0 checksum of zstd
=> Update zstd version

var/spack/repos/builtin/packages/sumaclust/package.py
=> sumaclust: new package

var/spack/repos/builtin/packages/tabix/package.py
=> tabix: new package

var/spack/repos/builtin/packages/cleaveland4/package.py, var/spack/repos/builtin/packages/perl-math-cdf/package.py, var/spack/repos/builtin/packages/viennarna/package.py
adding new package cleaveland4 along with dependencies viennarna and perl-math-cdf
=> cleaveland4: new package

var/spack/repos/builtin/packages/trimgalore/package.py
=> trimgalore: new package

var/spack/repos/builtin/packages/transposome/package.py
adding new package transposome
=> transposome: new package

var/spack/repos/builtin/packages/shortstack/package.py
=> shortstack: new package

var/spack/repos/builtin/packages/bml/package.py
Updated repository URL of bml library to LANL organization
=> Updated Organization of BML Repository

var/spack/repos/builtin/packages/snptest/package.py
adding new package snptest. Only available as precompiled binaries
=> snptest: new package

var/spack/repos/builtin/packages/m4/package.py
=> Fix for m4%clang

var/spack/repos/builtin/packages/apr/package.py
Also converts `apr` to `AutotoolsPackage`.
=> Add latest version of apr

var/spack/repos/builtin/packages/trilinos/package.py, var/spack/repos/builtin/packages/xsdk/package.py
=> Fix xsdk build broken by petsc and trilinos

var/spack/repos/builtin/packages/trilinos/package.py
=> Fix trilinos dependency on superlu-dist

var/spack/repos/builtin/packages/chlorop/chlorop.patch, var/spack/repos/builtin/packages/chlorop/package.py
This adds the chlorop package, not much in the way of dependencies.
=> chlorop: new package

var/spack/repos/builtin/packages/snap-berkeley/package.py, var/spack/repos/builtin/packages/snap/package.py
adding new package snap
Note: I was only able to get this to compile with gcc 4.8.5, not 6.3.0 or 7.1.0. I don't know if 5.x.x would work
=> snap-berkeley: new package

var/spack/repos/builtin/packages/velvet/package.py
=> velvet: new package

var/spack/repos/builtin/packages/vsearch/package.py
=> vsearch: new package

var/spack/repos/builtin/packages/rsem/package.py
=> rsem: new package

var/spack/repos/builtin/packages/abyss/package.py, var/spack/repos/builtin/packages/igraph/package.py, var/spack/repos/builtin/packages/py-igraph/package.py, var/spack/repos/builtin/packages/transabyss/package.py
adding new package transabyss along with edits to abyss, and dependencies py-igraph and igraph
=> transabyss: new package

var/spack/repos/builtin/packages/archer/package.py
(introduced during Package -> CMakePackage conversion)
=> Fix typo : spec to self.spec

var/spack/repos/builtin/packages/cmake/package.py
Add new versions:
- 3.8.2
- 3.9.0
=> CMake: 3.9.0

var/spack/repos/builtin/packages/molcas/install_driver.patch, var/spack/repos/builtin/packages/molcas/package.py
=> Add a new package for molcas

var/spack/repos/builtin/packages/dyninst/package.py
This version is required for openspeedshop
=> Add new version of dyninst package

var/spack/repos/builtin/packages/varscan/package.py, var/spack/repos/builtin/packages/varscan/varscan.sh
adding new package varscan with wrapper script
=> varscan: new package

var/spack/repos/builtin/packages/astral/astral.sh, var/spack/repos/builtin/packages/astral/package.py
adding new package astral along with wrapper for jar file. wrapper based on trimmomatic
=> astral: new package

var/spack/repos/builtin/packages/vmatch/package.py
=> vmatch: new package

var/spack/repos/builtin/packages/rtax/package.py, var/spack/repos/builtin/packages/usearch/package.py
adding new package rtax and dependency usearch (which is only available as a precompiled binary file)
=> rtax: new package

var/spack/repos/builtin/packages/xplor-nih/package.py
=> xplor-nih: new package

var/spack/repos/builtin/packages/kripke/package.py
=> Kripke: Fixed minor issues from Cmake conversion

var/spack/repos/builtin/packages/alglib/Makefile, var/spack/repos/builtin/packages/alglib/package.py
trying to figure out how to compile all `*.cpp` from python:
```
==> '/Users/davydden/spack/lib/spack/env/cc' '-c' '-fPIC' '*.cpp'
clang: error: no such file or directory: '*.cpp'
clang: error: no input files
```
=> Alglib : new package

var/spack/repos/builtin/packages/itsx/package.py, var/spack/repos/builtin/packages/pipits/package.py, var/spack/repos/builtin/packages/py-biom-format/package.py, var/spack/repos/builtin/packages/py-pipits/package.py, var/spack/repos/builtin/packages/rdp-classifier/package.py
adding new packages pipits, rdp-classifier, itsx, and py-biom-format
=> pipits: new package

var/spack/repos/builtin/packages/shapeit/package.py
=> shapeit: new package

var/spack/repos/builtin/packages/soapsnp/package.py
=> soapsnp: new package

var/spack/repos/builtin/packages/haploview/haploview.sh, var/spack/repos/builtin/packages/haploview/package.py
=> haploview: new package

var/spack/repos/builtin/packages/soap2/package.py
=> soap2: new package

var/spack/repos/builtin/packages/soapindel/package.py
=> soapindel: new package

var/spack/repos/builtin/packages/fastphase/package.py
adding new package fastphase. Unfortunately doesn't have a versioned url anywhere 😞
=> fastphase: new package

var/spack/repos/builtin/packages/kallisto/package.py
adding new package kallisto. specifically needs mpich, tried with openmpi and received linker error
=> kallisto: new package

var/spack/repos/builtin/packages/gblocks/package.py
=> gblocks: new package

var/spack/repos/builtin/packages/mothur/package.py
=> mothur: new package

var/spack/repos/builtin/packages/impute2/package.py
=> impute2: new package

var/spack/repos/builtin/packages/fimpute/package.py
adding new package fimpute. No versioned url for this one
=> fimpute: new package

var/spack/repos/builtin/packages/augustus/package.py, var/spack/repos/builtin/packages/braker/package.py, var/spack/repos/builtin/packages/genemark-et/package.py
adding new packages braker and genemark, and adding new version to augustus
=> braker & genemark-et: new packages

var/spack/repos/builtin/packages/gapfiller/package.py
=> gapfiller: new package

var/spack/repos/builtin/packages/sspace-longread/package.py
adding new package sspace-longread
=> sspace-longread: new package

var/spack/repos/builtin/packages/sspace-standard/package.py
adding new package sspace-standard
=> sspace-standard: new pacakge

var/spack/repos/builtin/packages/signalp/package.py
=> signalp: new package

var/spack/repos/builtin/packages/callpath/package.py, var/spack/repos/builtin/packages/kealib/package.py, var/spack/repos/builtin/packages/llvm-lld/package.py, var/spack/repos/builtin/packages/magics/package.py
@adamjstewart It looks like there were a few conversion issues from #4975 regarding references to spec. Some have been fixed in other PRs, but here are a few that were missed.
=> packages need to reference self.spec instead of spec

var/spack/repos/builtin/packages/mpest/package.py
=> mpest: new package

var/spack/repos/builtin/packages/falcon/package.py, var/spack/repos/builtin/packages/pacbio-daligner/package.py, var/spack/repos/builtin/packages/pacbio-damasker/package.py, var/spack/repos/builtin/packages/pacbio-dazz-db/package.py, var/spack/repos/builtin/packages/pacbio-dextractor/package.py, var/spack/repos/builtin/packages/py-networkx/package.py, var/spack/repos/builtin/packages/py-pypeflow/package.py
This adds the Falcon program from pacbio. There are a number of supporting programs this requires (special forks of them at that), worked heavily from https://github.com/PacificBiosciences/FALCON-integrate to get this to work.
=> adding falcon

lib/spack/spack/util/executable.py
Alternative to https://github.com/LLNL/spack/pull/5033
I have not confirmed that it resolves all the same issues, though I think it should.
Fixes #5032 
Fixes #4339 
Fixes #3842
Closes #4355 
Closes #5033
=> Decode process stream only for python3

var/spack/repos/builtin/packages/ncview/package.py
Seems like the download URL has changed.
=> ncview: Fix download URL

var/spack/repos/builtin/packages/apex/package.py, var/spack/repos/builtin/packages/ompt-openmp/package.py
@adamjstewart sorry, I missed the apex package in #5075 fixes for #4975. Please take a look at this one too.
=> fix reference to spec in apex package

var/spack/repos/builtin/packages/cdhit/package.py
=> cdhit: new package

var/spack/repos/builtin/packages/mpiblast/mpiBLAST-1.6.0-patch-110806, var/spack/repos/builtin/packages/mpiblast/package.py
adding new package mpiblast + patch
=> mpiblast: new package

var/spack/repos/builtin/packages/preseq/package.py
=> preseq: new package

var/spack/repos/builtin/packages/phylip/package.py
=> phylip: new package

var/spack/repos/builtin/packages/thrift/package.py
Hi, I've added the versions 0.10.0 and 0.9.3
=> Adding Thrift versions 0.10.0 and 0.9.3

var/spack/repos/builtin/packages/py-misopy/package.py
=> py-misopy: new package

var/spack/repos/builtin/packages/gapcloser/package.py
=> gapcloser: new package

var/spack/repos/builtin/packages/discovar/package.py
=> discovar: new package

var/spack/repos/builtin/packages/dialign-tx/package.py
=> dialign-tx: new package

var/spack/repos/builtin/packages/py-scikit-learn/package.py, var/spack/repos/builtin/packages/tppred/package.py
adding new package tppred, updating py-scikit-learn to add version that tppred uses
=> tppred: new package

lib/spack/spack/binary_distribution.py
signing and checksum checks
Fixes #5123
=> Fix formating of generated index.html. Allow yes-to-all to override

var/spack/repos/builtin/packages/py-faststructure/package.py
adding new package py-faststructure
=> py-faststructure: new package

var/spack/repos/builtin/packages/cmake/package.py, var/spack/repos/builtin/packages/rhash/package.py
Fixes #620 
Still need to test on Linux, but passes all tests on macOS. @manish2479 can you test this out to see if it solves your problem?
=> Add new package for rhash, a cmake dependency

var/spack/repos/builtin/packages/microbiomeutil/package.py
adding new package microbiomeutil
=> microbiomeutil: new package

var/spack/repos/builtin/packages/paml/package.py
=> paml: new package

lib/spack/docs/workflows.rst
Add a workflow how to use spack on Travis-CI.
depending if and how we can simplify #5101: add a multi-compiler, multi-C++-standard, multi-software
build matrix example. (Looking at you, https://github.com/travis-ci/travis-ci/issues/5959 👀 )
update from yesterdays discussion: the new [binary repos](https://github.com/LLNL/spack/pull/4854) can also help a lot here.
=> Docs: Travis-CI Workflow

var/spack/repos/builtin/packages/pbmpi/package.py
=> pbmpi: new package

var/spack/repos/builtin/packages/libfabric/package.py, var/spack/repos/builtin/packages/pbmpi/package.py
meant to go with pbmpi but forgot to add to branch
=> new package libfabric

var/spack/repos/builtin/packages/pagit/package.py
=> pagit: new package

var/spack/repos/builtin/packages/gaussian/package.py
Gaussian 09, this is a paid/licensed software.
=> Add a new package for gaussian

var/spack/repos/builtin/packages/nextflow/package.py
=> Add info for nextflow@v0.25.6

var/spack/repos/builtin/packages/plink/package.py, var/spack/repos/builtin/packages/r-corpcor/package.py, var/spack/repos/builtin/packages/r-mvtnorm/package.py, var/spack/repos/builtin/packages/vegas2/package.py
adding new package vegas2 along with dependencies plink and r-corpcor, and fixed r-mvtnorm package as the 1.0-5 versioned url was no longer available
=> vegas2: new package

var/spack/repos/builtin/packages/parsimonator/package.py
adding new package parsimonator
=> parsimonator: new package

var/spack/repos/builtin/packages/corset/package.py
=> corset: new package

var/spack/repos/builtin/packages/cufflinks/package.py
=> cufflinks: new package

.codecov.yml, .travis.yml, share/spack/qa/configuration/packages.yaml, var/spack/repos/builtin/packages/r-rcpp/package.py
This PR builds on #5068 and tries the new 'Build stage' feature of Travis.
=> Travi CI groups jobs in stages

var/spack/repos/builtin/packages/py-pyrad/package.py
=> py-pyrad: new package

var/spack/repos/builtin/packages/probconsrna/package.py, var/spack/repos/builtin/packages/tcoffee/package.py, var/spack/repos/builtin/packages/tmalign/package.py
adding new package tcoffee and dependencies probconsrna and tmalign. Small update to dialign-tx to make usable with tcoffee
=> tcoffee: new package

lib/spack/spack/config.py, lib/spack/spack/test/config.py, lib/spack/spack/test/data/config/modules.yaml
PR that puts `OrderedDicts` back in charge.
=> Restore the old order!

lib/spack/spack/test/sbang.py
cc @tgamblin Maybe these tests should be refactored and be separate entities...
=> add test for lua and node handling in sbang patching (cf #5086)

var/spack/repos/builtin/packages/pgdspider/package.py, var/spack/repos/builtin/packages/pgdspider/pgdspider.sh
=> pgdspider: new package

lib/spack/spack/cmd/install.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/install.py, share/spack/spack-completion.bash
=> copy source into prefix

lib/spack/spack/cmd/gpg.py, lib/spack/spack/test/cmd/gpg.py
---
Please do not squash merge these commits; the individual messages have details in them.
=> Fix gpg tests

var/spack/repos/builtin/packages/ray/package.py
=> ray: new package

var/spack/repos/builtin/packages/adol-c/package.py, var/spack/repos/builtin/packages/dealii/package.py, var/spack/repos/builtin/packages/expat/package.py, var/spack/repos/builtin/packages/nanoflann/package.py, var/spack/repos/builtin/packages/sundials/package.py
fixes https://github.com/LLNL/spack/issues/5173
p.s. @markcmiller86 in 39cb589510e95fa44ca634b2cdac9a56a34b1809 you extended `sundials` a bit and it looks like it worked for you on macOS. Could you please check if this PR does not break it for you?
=> dealii: add nanoflann, sundials and adol-c  plus fixes on macOS

lib/spack/spack/build_systems/autotools.py
Fixes #5128.
Should cover other OS distros too.
=> patch config.guess for any ppc64le arch

var/spack/repos/builtin/packages/hapcut2/package.py
=> hapcut2: new package

var/spack/repos/builtin/packages/mpich/mpich32_clang.patch, var/spack/repos/builtin/packages/mpich/package.py
see https://lists.mpich.org/pipermail/discuss/2016-May/004764.html, https://lists.mpich.org/pipermail/discuss/2016-June/004768.html
and https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpich.rb#L35-L39
=> mpich: fix MPI_Barrier segfault

var/spack/repos/builtin/packages/jags/package.py
=> jags: new package

var/spack/repos/builtin/packages/kmergenie/package.py
=> kmergenie: new package

var/spack/repos/builtin/packages/meson/package.py
Adding a spec for the meson build system
=> New package: meson build system

var/spack/repos/builtin/packages/osu-micro-benchmarks/package.py
Changed hardcoded mpi wrapper names
Changed Package to AutotoolsPackage
=> Fix osu-micro-benchmarks build

var/spack/repos/builtin/packages/llvm/package.py
Updated llvm to version 4.0.1 Fixed indentation of dict literal.
=> Added version 4.0.1 to llvm

var/spack/repos/builtin/packages/lua-bitlib/package.py, var/spack/repos/builtin/packages/lua-lpeg/package.py, var/spack/repos/builtin/packages/lua-mpack/package.py, var/spack/repos/builtin/packages/neovim/package.py
As an aside, this would have been much easier if resource(expand=False) worked.
=> add neovim package with deps

var/spack/repos/builtin/packages/ior/package.py
Suggestions from #5298 and remove hardcoded mpi wrapper path
=> Change IOR to AutotoolsPackage and remove hardcoded mpicc path

var/spack/repos/builtin/packages/berkeley-db/package.py
=> berkeley-db: initial commit

var/spack/repos/builtin/packages/parsplice/package.py
=> parsplice: initial commit

share/spack/setup-env.sh
```bash
$ ps -p $$
PID TTY           TIME CMD
98195 ttys004    0:00.02 -bash
```
=> setup-env.sh: filter preceding - on OSX

var/spack/repos/builtin/packages/nauty/package.py
nauty package missing help2man and gmp dependencies
=> Added missing dependencies to nauty package

var/spack/repos/builtin/packages/trilinos/package.py
Added support for building NOX package to Trilinis Spackage
=> Added Support for NOX Package to Trilinos Spackage

var/spack/repos/builtin/packages/gromacs/package.py
=> gromacs: added 2016.4

var/spack/repos/builtin/packages/numactl/package.py
Adds the [numactl](https://github.com/numactl/numactl) tools and libnuma.
=> New Package: numactl

var/spack/repos/builtin/packages/trilinos/package.py
~~waiting for reply~~ https://github.com/trilinos/Trilinos/issues/1737
@aprokop ping.
=> trilinos: update md5 for 12.10.1

var/spack/repos/builtin/packages/lammps/package.py
=> lammps: fix checksum

var/spack/repos/builtin/packages/adios/package.py
=> adios: fixed conditional dependencies on libevpath and dataspaces

var/spack/repos/builtin/packages/targetp/package.py
=> targetp: new package

var/spack/repos/builtin/packages/bbmap/package.py
=> bbmap: new package

var/spack/repos/builtin/packages/tmhmm/package.py
=> tmhmm: new package

var/spack/repos/builtin/packages/mariadb/package.py, var/spack/repos/builtin/packages/orthomcl/package.py
Adding new package orthomcl, along with fix for mariadb url. Old url does not exist anymore.
=> orthomcl: new package

lib/spack/docs/packaging_guide.rst
=> update Blas/Lapack section of packaging guide

var/spack/repos/builtin/packages/mirdeep/package.py, var/spack/repos/builtin/packages/perl-devel-cycle/package.py, var/spack/repos/builtin/packages/perl-font-ttf/package.py, var/spack/repos/builtin/packages/perl-padwalker/package.py, var/spack/repos/builtin/packages/perl-pdf-api2/package.py, var/spack/repos/builtin/packages/perl-sub-uplevel/package.py, var/spack/repos/builtin/packages/perl-test-exception/package.py, var/spack/repos/builtin/packages/perl-test-memory-cycle/package.py, var/spack/repos/builtin/packages/randfold/package.py, var/spack/repos/builtin/packages/squid/package.py
adding new package mirdeep, along with dependencies squid, randfold, and perl-pdf-api2 and its dependencies
=> mirdeep: new package

var/spack/repos/builtin/packages/r-survival/package.py
updated r-survival to version 2.41-3
=> r-survival: updated to version 2.41-3

var/spack/repos/builtin/packages/dealii/package.py
=> dealii: add cuda support

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-biocinstaller/package.py
adding new package r-biocinstaller
=> r-biocinstaller: added version 1.26.1

var/spack/repos/builtin/packages/r-zlibbioc/package.py
=> r-zlibbioc: new package

var/spack/repos/builtin/packages/openmpi/package.py
=> OpenMPI:  add 2.1.2 bug fix release

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-s4vectors/package.py
=> r-s4vectors: created new package

var/spack/repos/builtin/packages/git-lfs/package.py
=> Add info for git-lfs@2.2.1 and @2.3.0

var/spack/repos/builtin/packages/lftp/package.py
=> Add info for lftp@4.8.1

var/spack/repos/builtin/packages/httpie/package.py
=> Add info for httpie@0.9.9

var/spack/repos/builtin/packages/tmux/package.py
=> Add info for tmux@2.5

var/spack/repos/builtin/packages/superlu-dist/package.py
from the off. website:
> December 31, 2016 Version 5.1.3  Version 5.1.3 (last update: 09/17/2017)
=> superlu-dist: fix has after 09/17/2017 update

var/spack/repos/builtin/packages/r-xvector/package.py
Added a new package r-xvector.
This package depends on r-zlibbioc, r-biocgenerics, r-s4vectors, r-iranges.
r-iranges is in another open PR.
=> r-xvector: created new package

var/spack/repos/builtin/packages/r-affyio/package.py
=> r-affyio: created new package

var/spack/repos/builtin/packages/r-preprocesscore/package.py
added new package r-preprocesscore
=> r-preprocesscore: created new package

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-assertthat/package.py
Update version of package r-assertthat.
=> r-assertthat: update version to 0.2.0

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-bit/package.py
=> r-bit: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-tibble/package.py
=> r-tibble: update version.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-memoise/package.py
=> r-memoise: update version.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-bh/package.py
=> r-bh: update version.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-rsqlite/package.py
=> r-rsqlite: Update version to 2.0.

var/spack/repos/builtin/packages/parsplice/package.py
As requested by @tgamblin in https://github.com/LLNL/spack/pull/5314#issuecomment-328736161.
=> parsplice: add version 1.1

var/spack/repos/builtin/packages/hdf5/package.py
in reference to https://github.com/LLNL/spack/pull/5372
=> hdf5: fix macOS build by not using numactl

var/spack/repos/builtin/packages/assimp/package.py, var/spack/repos/builtin/packages/dealii/package.py
=> add assimp package. link against it in dealii

var/spack/repos/builtin/packages/lmod/package.py
=> Add info for lmod@7.7 and lmod@7.6.14

var/spack/repos/builtin/packages/conduit/package.py
=> update for conduit 0.3.0 release

var/spack/repos/builtin/packages/py-flake8/package.py, var/spack/repos/builtin/packages/py-mccabe/package.py
Fixes #5420.
@cyrush: can you try this out and see whether it fixes your issue?
=> py-mccabe: don't require pytest-runner for install

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-blob/package.py
=> r-blob: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-bit64/package.py
=> r-bit64: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-pkgconfig/package.py
=> r-pkgconfig: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-plogr/package.py
=> r-plogr: new package.

var/spack/repos/builtin/packages/r-genefilter/package.py
=> r-genefilter: New package.

var/spack/repos/builtin/packages/r-affy/package.py
=> r-affy: created new package

var/spack/repos/builtin/packages/astyle/package.py
=> astyle: homepage dead, use mirror

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-annotate/package.py
=> r-annotate: new package.

var/spack/repos/builtin/packages/r-rcurl/package.py
=> r-rcurl: created new package

var/spack/repos/builtin/packages/r-gplots/package.py
=> r-gplots: Create New Package.

var/spack/repos/builtin/packages/mpich/package.py
Add support for development version, including the new ch4 device implementation.
=> Additional MPICH configs

var/spack/repos/builtin/packages/lammps/package.py
=> lammps: add user-omp package

var/spack/repos/builtin/packages/coevp/package.py
Added spackage for baseline (mpi, no other dependencies) CoEVP
=> Added CoEVP Spackage

var/spack/repos/builtin/packages/trilinos/package.py
Added support for shards, intrepid, and intrepid2 variants to trilinos
spackage
=> Added shards and intrepid(2) to trilinos

var/spack/repos/builtin/packages/bml/package.py
Adding support for 1.2.2 of BML in preparation for exasp2
=> Added Support for BML 1.2.2

var/spack/repos/builtin/packages/r-simpleaffy/package.py
Added new package r-simpleaffy.
=> r-simpleaffy: created new package

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-a4core/package.py
=> r-a4core: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-rocr/package.py
=> r-rocr: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-pamr/package.py
=> r-pamr: new package

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-varselrf/package.py
=> r-varselrf: new package.

var/spack/repos/builtin/packages/branson/package.py
Added spackage for branson proxy for monte carlo
=> Added Branson spackage

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-sfsmisc/package.py
=> r-sfsmisc: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-rda/package.py
=> r-rda: new package.

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-jsonlite/package.py
=> r-jsonlite: Update version to 1.5

var/spack/repos/builtin/packages/cloc/package.py
+ Count, or compute differences of, physical lines of source code in the given files (may be archives such as compressed tarballs or zip files) and/or recursively below the given directories.
+ https://github.com/AlDanial/cloc
=> Provide a new Perl package 'cloc'.

var/spack/repos/builtin/packages/tcsh/package.py
The patches are taken from the Fedora package.
=> tcsh: New package

var/spack/repos/builtin/packages/py-quantities/package.py, var/spack/repos/builtin/packages/r-ggvis/package.py
=> r-ggvis: Update version to 0.4.3

var/spack/repos/builtin/packages/tycho2/package.py
=> tycho2: initial commit

var/spack/repos/builtin/packages/r-rlang/package.py
=> r-rlang: created new package

var/spack/repos/builtin/packages/masa/package.py
=> Adding masa package.

var/spack/repos/builtin/packages/metaphysicl/package.py
=> Add metaphysicl package

var/spack/repos/builtin/packages/r-yaqcaffy/package.py
=> r-yaqcaffy: created new package

var/spack/repos/builtin/packages/r-gcrma/package.py
=> r-gcrma: created new package

var/spack/repos/builtin/packages/r-biostrings/package.py
Added new package r-biostrings.
=> r-biostrings: new package

var/spack/repos/builtin/packages/r-gdata/package.py
=> r-gdata: update version to 2.18.0

var/spack/repos/builtin/packages/r-a4preproc/package.py
=> r-a4preproc: Create new package.

var/spack/repos/builtin/packages/nalu/package.py, var/spack/repos/builtin/packages/trilinos/package.py
Adding new Trilinos version and updating Nalu to utilize it. Also adding requirement of `trilinos+shards` since it was added as a new Trilinos variant.
=> Adding new Trilinos version and updating Nalu to utilize it

var/spack/repos/builtin/packages/r-biomart/package.py
=> r-biomart: created new package

var/spack/repos/builtin/packages/r-downloader/package.py
Added new package r-downloader.
=> r-downloader: created new package

var/spack/repos/builtin/packages/masa/package.py
Masa requires python if +python
=> Masa requires python if +python

var/spack/repos/builtin/packages/r-limma/package.py
Added version 3.32.7 for r-limma.
=> r-limma: added version 3.32.7

var/spack/repos/builtin/packages/hisat2/package.py
=> hisat2: new package

var/spack/repos/builtin/packages/linkphase3/package.py
=> linkphase3: new package

var/spack/repos/builtin/packages/yajl/package.py
=> Added Spackage for YAJL

var/spack/repos/builtin/packages/bml/package.py
Added support for BML+mpi variant. Currently restricted to master
(develop) branch pending release of next bml tag
=> Added support for BML+mpi variant

var/spack/repos/builtin/packages/r-locfit/package.py
=> r-locfit: created new package

var/spack/repos/builtin/packages/mrtrix3/package.py
=> mrtrix3: new package

lib/spack/docs/packaging_guide.rst, lib/spack/spack/directives.py, lib/spack/spack/patch.py
This was part of #5459, but I will break it out to make it easier to review!
=> patch: add workdir option

var/spack/repos/builtin/packages/sra-toolkit/package.py
=> sra-toolkit: new package

var/spack/repos/builtin/packages/exasp2/package.py
Added spackage of ExaSP2 Proxy Application
=> ExaSP2 Spackage

var/spack/repos/builtin/packages/multitail/package.py
=> Add package for multitail@6.4.2

var/spack/repos/builtin/packages/r-edger/package.py
=> r-edger: created new package

var/spack/repos/builtin/packages/tassel/package.py
=> tassel: new package

var/spack/repos/builtin/packages/sandbox/package.py
=> sandbox: initial commit

var/spack/repos/builtin/packages/cmake/package.py
Adds the latest release of CMake.
=> CMake: 3.9.4

var/spack/repos/builtin/packages/r-abaenrichment/package.py
=> r-abaenrichment: Create new package.

var/spack/repos/builtin/packages/r-boot/package.py
=> r-boot: Update version to 1.3-20

var/spack/repos/builtin/packages/r-acde/package.py
=> r-acde: Create new package.

var/spack/repos/builtin/packages/r-absseq/package.py
=> r-absseq: Create new package.

var/spack/repos/builtin/packages/r-cluster/package.py
=> r-cluster: Update version to 2.0.6.

var/spack/repos/builtin/packages/r-acgh/package.py
=> r-acgh: Create new package.

var/spack/repos/builtin/packages/r-acme/package.py
=> r-acme: Create new package.

var/spack/repos/builtin/packages/maven/package.py
@peetsv gets any credit and most of the blame for this work, I'm just passing it over the wall.
=> maven: new version

var/spack/repos/builtin/packages/the-silver-searcher/package.py
@peetsv gets any credit and most of the blame for this work, I'm just passing it over the wall.
=> The silver searcher: new version

var/spack/repos/builtin/packages/r-hms/package.py
=> r-hms: new package

var/spack/repos/builtin/packages/r-genomeinfodbdata/package.py
Added new package r-genomeinfodbdata.
=> r-genomeinfodbdata: new package

var/spack/repos/builtin/packages/r-affxparser/package.py
=> r-affxparser: Create new package.

var/spack/repos/builtin/packages/r-affycomp/package.py
=> r-affycomp: Create new package.

var/spack/repos/builtin/packages/hypre/package.py
=> hypre: add 2.12.1

var/spack/repos/builtin/packages/espressopp/package.py
=> espressopp: added v1.9.5

var/spack/repos/builtin/packages/strelka/package.py
I'd welcome suggestions for a prettier way to handle the long line complains in the sbang patching code.
=> strelka: new package

var/spack/repos/builtin/packages/r-affycontam/package.py
=> r-affycontam: Create new package.

var/spack/repos/builtin/packages/r-affydata/package.py
=> r-affydata: Create new package.

var/spack/repos/builtin/packages/r-affycompatible/package.py
Add package: r-affycompatible.
=> r-affycompatible: Create new package.

var/spack/repos/builtin/packages/r-adsplit/package.py, var/spack/repos/builtin/packages/r-rlang/package.py, var/spack/repos/builtin/packages/r-s4vectors/package.py
Add package: r-adsplit. Update version for r-s4vectors and r-rlang.
=> r-adsplit: Create new package and update version for its dependencies.

var/spack/repos/builtin/packages/snap-korf/package.py
Adding new package for snap-korf.
=> snap-korf: new package

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py, var/spack/repos/builtin/packages/miniamr/package.py
=> Add a bundle package for the ECP proxy applications suite

var/spack/repos/builtin/packages/r-delayedarray/package.py
Added new package r-delayedarray.
=> r-delayedarray: created new package

var/spack/repos/builtin/packages/r-biocparallel/package.py
Added new package r-biocparallel.
=> r-biocparallel: created new package

var/spack/repos/builtin/packages/r-futile-logger/package.py
Added new package r-futile-logger.
=> r-futile-logger: created new package

var/spack/repos/builtin/packages/r-lambda-r/package.py
=> r-lambda-r: created new package

var/spack/repos/builtin/packages/r-futile-options/package.py
Added new package r-futile-options.
=> r-futile-options: created new package

var/spack/repos/builtin/packages/r-genomeinfodbdata/package.py
Added versioned dependency on r.
=> r-genomeinfodbdata: added versioned dependency on r

var/spack/repos/builtin/packages/libpcap/package.py
Add a package script for libpcap with the current version (1.8.1)
=> Initial version of libpcap

var/spack/repos/builtin/packages/minimap2/package.py, var/spack/repos/builtin/packages/py-mappy/package.py
Adding new package minimap2 and dependency py-mappy.
=> minimap2: new package

lib/spack/spack/operating_systems/mac_os.py, var/spack/repos/builtin/packages/bison/package.py, var/spack/repos/builtin/packages/bison/secure_snprintf.patch, var/spack/repos/builtin/packages/gcc/darwin/apfs.patch, var/spack/repos/builtin/packages/gcc/package.py, var/spack/repos/builtin/packages/oce/package.py, var/spack/repos/builtin/packages/trilinos/package.py
~~it's WIP as I will probably push more fixes (currently building the stack...)~~ I built everything I wanted on High Sierra (`dealii` stack with everything turned on).
~~p.s. Github does not show the last commit here, which is however visible in the "Commits" section as well as in "Files changed".~~
=> various fixes for macOS high sierra

var/spack/repos/builtin/packages/gettext/package.py
fixes https://github.com/LLNL/spack/issues/5721
@alalazo ping.
=> gettext: fix prefix

var/spack/repos/builtin/packages/r-stringi/package.py
Added list_url and version 1.1.5 and 1.1.3 for r-stringi.
=> r-stringi: added list_url and version 1.1.5 and 1.1.3

var/spack/repos/builtin/packages/r-stringr/package.py
Added list_url and version 1.2.0 for r-stringr.
=> r-stringr: added list_url and version 1.2.0

var/spack/repos/builtin/packages/oce/package.py, var/spack/repos/builtin/packages/trilinos/package.py
fixes https://github.com/LLNL/spack/issues/5742
@balay please test
=> trilinos / oce : add missing if before calling macOS_version

var/spack/repos/builtin/packages/m4/package.py
=> Fix m4 to compile with Intel

var/spack/repos/builtin/packages/py-espressopp/package.py
espressopp is a python module.
=> espressopp -> py-espressopp

var/spack/repos/builtin/packages/py-espresso/package.py
=> py-espresso: initial commit

var/spack/repos/builtin/packages/r-rmpi/package.py
Added list_url and updated the md5 for version 0.6-6.
=> r-rmpi: added list_url and updated md5

var/spack/repos/builtin/packages/krims/package.py, var/spack/repos/builtin/packages/lazyten/package.py
This PR adds the [krims](https://lazyten.org/krims) and [lazyten](https://lazyten.org) projects to spack.
Let me know if you see possible improvements.
=> Add krims and lazyten

var/spack/repos/builtin/packages/portage/package.py
/cc @ddaniel @angelaherring @cmsquared @cferenba @nray
=> portage: fixes + added v1.1.*

var/spack/repos/builtin/packages/singularity/package.py
Added version 2.4 to Spack
Many changes in this release:
https://github.com/singularityware/singularity/releases/tag/2.4
=> singularity 2.4 added

var/spack/repos/builtin/packages/flang/package.py
flang-compiler/flang#85 got merged.
=> flang: clean up

var/spack/repos/builtin/packages/py-mpi4py/package.py
- Add cython dependency for develop version
- Add explicit python dependency
=> py-mpi4py: Add develop version and dependencies

var/spack/repos/builtin/packages/r-genomicfeatures/package.py
Added new package r-genomicfeatures.
=> r-genomicfeatures: new package

var/spack/repos/builtin/packages/r-affyilm/package.py
=> r-affyilm: Create new package.

var/spack/repos/builtin/packages/r-rtracklayer/package.py
added new package r-rtracklayer.
=> r-rtracklayer: new package

var/spack/repos/builtin/packages/r-affyexpress/package.py
=> r-affyexpress: Create new package.

var/spack/repos/builtin/packages/libxml2/package.py
=> libxml2: use spack's xz

var/spack/repos/builtin/packages/perl/package.py
The perllocal.pod files list and describe non-core packages installed by users; they are not used by perl itself. In a normal perl installation, the perllocal.pod files are appended when new packages are installed. Under spack, perl packages each create their own perllocal.pod file. During package activation, the multiple perllocal.pod files conflict with each other, so that only one perl package can be activated at any time.
The solution proposed here ignores the perllocal.pod files during package activation, using code derived from the python package. We choose not to merge the files, as is done for some files in python packages, because they are not required for correct operation of perl and ignoring them is much simpler.
=> perl: ignore perllocal.pod files during package activation

var/spack/repos/builtin/packages/r-bumphunter/package.py
Added new package r-bumphunter.
=> r-bumphunter: new package

var/spack/repos/builtin/packages/mfem/package.py
Changes needed for xsdk package integration.
=> Updated external package versions.

var/spack/repos/builtin/packages/r-beanplot/package.py
=> r-beanplot: created new package

var/spack/repos/builtin/packages/r-affypdnn/package.py
=> r-affypdnn: Create new package.

var/spack/repos/builtin/packages/r-affyplm/package.py
=> r-affyplm: Create new package.

var/spack/repos/builtin/packages/r-nor1mix/package.py
=> r-nor1mix: created new package

var/spack/repos/builtin/packages/r-affyqcreport/package.py
=> r-affyqcreport: Create new package.

var/spack/repos/builtin/packages/r-affyrnadegradation/package.py
Add package: r-affyrnadegradation.
=> r-affyrnadegradation: Create new package.

var/spack/repos/builtin/packages/r-siggenes/package.py
=> r-siggenes: new package

var/spack/repos/builtin/packages/r-illuminaio/package.py
Added new package r-illuminaio.
=> r-illuminaio: created new package

var/spack/repos/builtin/packages/r-base64/package.py
=> r-base64: created new package

var/spack/repos/builtin/packages/r-markdown/package.py
Update version for r-markdown.
=> r-markdown: Update version to 0.8.

var/spack/repos/builtin/packages/r-testit/package.py
=> r-testit: Update version to 0.7

var/spack/repos/builtin/packages/r-sourcetools/package.py
=> r-sourcetools: Create new package.

var/spack/repos/builtin/packages/r-crayon/package.py
=> r-crayon: Update version to 1.3.4

var/spack/repos/builtin/packages/r-formatr/package.py
=> r-formatr: Update version to 1.5

var/spack/repos/builtin/packages/r-yaml/package.py
=> r-yaml: Update version to 2.1.14

var/spack/repos/builtin/packages/r-curl/package.py
Added list_url and version 3.0 to r-curl.
=> r-curl: added list_url and version 3.0

var/spack/repos/builtin/packages/r-rcpparmadillo/package.py
=> r-rcpparmadillo: Create new package.

var/spack/repos/builtin/packages/r-httr/package.py
Added list_url and version 1.3.1 to r-httr.
=> r-httr: added list_url and version 1.3.1

var/spack/repos/builtin/packages/r-knitr/package.py
=> r-knitr: Update version to 1.17.

var/spack/repos/builtin/packages/r-geoquery/package.py
=> r-geoquery: created new package

var/spack/repos/builtin/packages/r-checkmate/package.py
=> r-checkmate: Create new package.

var/spack/repos/builtin/packages/r-htmlwidgets/package.py
Update version for r-htmlwidgets.
=> r-htmlwidgets: Update verion to 0.9

var/spack/repos/builtin/packages/r-htmltable/package.py
=> r-htmltable: Create new package.

var/spack/repos/builtin/packages/r-latticeextra/package.py
=> r-latticeextra: Create new package.

var/spack/repos/builtin/packages/r-acepack/package.py
=> r-acepack: Create new package.

var/spack/repos/builtin/packages/r-mass/package.py
=> r-mass: Update version to 7.3-47

var/spack/repos/builtin/packages/r-data-table/package.py
Added list_url and version 1.10.4-2 to r-data-table.
=> r-data-table: added list_url and version 1.10.4-2

var/spack/repos/builtin/packages/r-reshape/package.py
Created new package r-reshape.
=> r-reshape: created new package

var/spack/repos/builtin/packages/r-genomicalignments/package.py
Added new package r-genomicalignments.
=> r-genomicalignments: created new package

var/spack/repos/builtin/packages/r-nlme/package.py
Added list_url and version 3.1-131 to r-nlme.
=> r-nlme: added list_url and version 3.1-131

var/spack/repos/builtin/packages/r-minfi/package.py
=> r-minfi: created new package

var/spack/repos/builtin/packages/sw4lite/package.py
Added Spackage for CXX version of SW4Lite proxy. Fortran will follow once
race conditions involving .mod files are resolved
=> Added Spackage for SW4Lite proxy

var/spack/repos/builtin/packages/gdbm/package.py
=> gdbm: pass in proper CPPFLAGS

var/spack/repos/builtin/packages/r-hmisc/package.py
=> r-hmisc: Create new package.

var/spack/repos/builtin/packages/r-doparallel/package.py
Added list_url and version 1.0.11 to r-doparallel.
=> r-doparallel: added list_url and version 1.0.11

var/spack/repos/builtin/packages/r-scales/package.py
=> r-scales: Update url.

var/spack/repos/builtin/packages/r-quantro/package.py
=> r-quantro: created new package

var/spack/repos/builtin/packages/r-formula/package.py
=> r-formula: Update version to 1.2-2

var/spack/repos/builtin/packages/r-yarn/package.py
=> r-yarn: created new package

var/spack/repos/builtin/packages/r-lsei/package.py
=> r-lsei: new package

var/spack/repos/builtin/packages/r-bsgenome/package.py
=> r-bsgenome: created new package

var/spack/repos/builtin/packages/r-gseabase/package.py
=> r-gseabase: Create new package.

var/spack/repos/builtin/packages/r-variantannotation/package.py
New package r-variantannotation.
=> r-variantannotation: created new package

var/spack/repos/builtin/packages/r-rbgl/package.py
=> r-rbgl: Create new package.

var/spack/repos/builtin/packages/r-desolve/package.py, var/spack/repos/builtin/packages/r-geiger/package.py, var/spack/repos/builtin/packages/r-ncbit/package.py, var/spack/repos/builtin/packages/r-subplex/package.py
adding package r-geiger along with dependencies
=> r-geiger and dependencies

var/spack/repos/builtin/packages/r-gridextra/package.py
Update version for r-gridextra.
=> r-gridextra: Update version to 2.3

var/spack/repos/builtin/packages/r-geneplotter/package.py
=> r-geneplotter: Create new package.

var/spack/repos/builtin/packages/mfem/package.py
Added missing hypre defendency from mfem's hypre-enabled version
=> Added Hypre Dependency to mfem+hypre

var/spack/repos/builtin/packages/parallel/package.py
I'm just throwing this over the corporate wall.
Credit goes to @peetsv.
---
Parallel installs a bunch of perl scripts.  This commit makes the dependency on perl explicit and fixes the sbang lines.
=> Parallel fix sbangs

var/spack/repos/builtin/packages/py-xlsxwriter/package.py
adding new package py-xlsxwriter
=> py-xlsxwriter: new package

var/spack/repos/builtin/packages/llvm/package.py
=> Make clang use libc++ by default

var/spack/repos/builtin/packages/flang/package.py
=> flang: fixed llvm dep

var/spack/repos/builtin/packages/laghos/package.py, var/spack/repos/builtin/packages/mfem/package.py
=> Laghos: new package

var/spack/repos/builtin/packages/minife/package.py
=> minife: version bump to v2.1.0

var/spack/repos/builtin/packages/miniamr/package.py
/cc @bhatele @nmhamster @ctvaugh
=> miniamr: bump to v1.4.0

var/spack/repos/builtin/packages/r-protgenerics/package.py
=> r-protgenerics: created new package

var/spack/repos/builtin/packages/r-annotationfilter/package.py
New package r-annotationfilter.
=> r-annotationfilter: created new package

var/spack/repos/builtin/packages/r-aims/package.py
=> r-aims: Create new package.

var/spack/repos/builtin/packages/r-agilp/package.py
=> r-agilp: Create new package.

var/spack/repos/builtin/packages/r-agdex/package.py
=> r-agdex: Create new package.

var/spack/repos/builtin/packages/r-deseq2/package.py
=> r-deseq2: Create new package.

var/spack/repos/builtin/packages/r-annotationhub/package.py
=> r-annotationhub: created new package

var/spack/repos/builtin/packages/r-mcmcglmm/package.py, var/spack/repos/builtin/packages/r-tensora/package.py
adding new package r-mcmcglmm as well as dependency r-tensora
=> r-mcmcglmm: new package

var/spack/repos/builtin/packages/r-gostats/package.py
=> r-gostats: Create new package.

var/spack/repos/builtin/packages/r-annotationforge/package.py
Add package: r-annotaionforge.
=> r-annotationforge: Create new package.

var/spack/repos/builtin/packages/r-interactivedisplaybase/package.py
New package r-interactivedisplaybase.
=> r-interactivedisplaybase: created new package

var/spack/repos/builtin/packages/r-oligoclasses/package.py
=> r-oligoclasses: Create new package.

var/spack/repos/builtin/packages/r-pfam-db/package.py
=> r-pfam-db: Create new package.

var/spack/repos/builtin/packages/r-utils/package.py
=> r-utils: Create new package.

var/spack/repos/builtin/packages/r-oo/package.py
=> r-oo: Create new package.

var/spack/repos/builtin/packages/r-methodss3/package.py
=> r-methodss3: Create new package.

var/spack/repos/builtin/packages/r-category/package.py
=> r-category: Create new package.

var/spack/repos/builtin/packages/r-graph/package.py
=> r-graph: Create new package.

var/spack/repos/builtin/packages/comd/package.py
=> comd: add v1.1

var/spack/repos/builtin/packages/swfft/package.py
/cc @bhatele @hfinkel @adrianpope
=> SWFFT: initial commit

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py
=> ecp-proxy-apps: add more package

var/spack/repos/builtin/packages/byobu/package.py
Add the byobu window manager (frontend to tmux).
=> Byobu: Create new package

lib/spack/spack/fetch_strategy.py, lib/spack/spack/test/url_fetch.py, var/spack/repos/builtin.mock/packages/url-list-test/package.py
Function from_list_url() doesn't work after #5476. This should fix that.
=> Bugfix: from_list_url().

var/spack/repos/builtin/packages/r-aldex2/package.py
=> r-aldex2: Create new package.

var/spack/repos/builtin/packages/r-organismdb/package.py, var/spack/repos/builtin/packages/r-organismdbi/package.py
=> r-organismdbi: new package

var/spack/repos/builtin/packages/r-e1071/package.py
=> r-e1071: Add list_url.

var/spack/repos/builtin/packages/r-geomorph/package.py, var/spack/repos/builtin/packages/r-rgl/package.py
Added missing dependencies to r-rgl and r-shiny. Adding new package r-geomorph
=> r-geomorph and other r fixes

var/spack/repos/builtin/packages/r-iranges/package.py
Changed url to git and added versioned dependency on r for package r-iranges.
=> r-iranges: changed url to git and added versioned dependency on r

var/spack/repos/builtin/packages/minitri/package.py
miniTri  requires C++, so I should set this instead of C.
=> Changed from setting C compiler to setting C++ compiler

var/spack/repos/builtin/packages/comd/package.py
git repo has moved from exmatex to ECP-copa
=> comd: update the git repo

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py
=> ecp-proxy-apps: release number changed to 1.0

var/spack/repos/builtin/packages/r-biovizbase/package.py
=> r-biovizbase: Create new package.

var/spack/repos/builtin/packages/r-backports/package.py
=> r-backports: Create new package.

var/spack/repos/builtin/packages/r-proxy/package.py
=> r-proxy: created new package

var/spack/repos/builtin/packages/r-pcamethods/package.py
=> r-pcamethods: created new package

var/spack/repos/builtin/packages/r-ensembldb/package.py
=> r-ensembldb: created new package

var/spack/repos/builtin/packages/r-alpine/package.py
=> r-alpine: Create new package.

var/spack/repos/builtin/packages/r-speedglm/package.py
=> r-speedglm: Create new package.

var/spack/repos/builtin/packages/r-ggally/package.py
=> r-ggally: new package

var/spack/repos/builtin/packages/r-segmented/package.py
Update version for r-segmented.
=> r-segmented: Update version to 0.5-2.2

var/spack/repos/builtin/packages/r-seqinr/package.py
=> r-seqinr: Update version to 3.4-5

var/spack/repos/builtin/packages/r-prettyunits/package.py
=> r-prettyunits: created new package

var/spack/repos/builtin/packages/r-progress/package.py
=> r-progress: new package

var/spack/repos/builtin/packages/sundials/package.py
Update Sundials package to v3.0.0
=> sundials: update to v3.0.0

var/spack/repos/builtin/packages/blaze/package.py
Add latest version of the Blaze library
=> Add v3.2 of Blaze library

var/spack/repos/builtin/packages/candle-benchmarks/package.py
/cc @bvanessen @brettinanl @bhatele @jmohdyusof
=> candle-benchmarks: initial commit

var/spack/repos/builtin/packages/nekbone/package.py
=> nekbone: add v17

var/spack/repos/builtin/packages/sw4lite/package.py
@bhatele I ran into similar issues with minighost.  When building in parallel I ended up with modules not being available when needed.
=> sw4lite: Added -lgfortran and set to serial build

var/spack/repos/builtin/packages/r-gviz/package.py
=> r-gviz: Create new package.

var/spack/repos/builtin/packages/r-ggbio/package.py
=> r-ggbio: new package

var/spack/repos/builtin/packages/r-als/package.py
=> r-als: Create new package.

var/spack/repos/builtin/packages/r-nnls/package.py
=> r-nnls: Create new package.

var/spack/repos/builtin/packages/r-iso/package.py
=> r-iso: Create new package.

var/spack/repos/builtin/packages/r-ptw/package.py
=> r-ptw: Create new package.

var/spack/repos/builtin/packages/r-nloptr/package.py
=> r-nloptr: Create new package.

var/spack/repos/builtin/packages/r-somaticsignatures/package.py
New package r-somaticsignatures.
=> r-somaticsignatures: created new package

var/spack/repos/builtin/packages/llvm/package.py
Preinstall some llvm shared libraries so tblgen will work.
=> Fix for LLVM build with +shared_libs on CENTOS7

var/spack/repos/builtin/packages/r-pmcmr/package.py
=> r-pmcmr: new package

var/spack/repos/builtin/packages/r-shape/package.py
=> r-shape: created new package

var/spack/repos/builtin/packages/r-complexheatmap/package.py
=> r-complexheatmap: created new package

var/spack/repos/builtin/packages/r-agimicrorna/package.py
=> r-agimicrorna: Create new package.

var/spack/repos/builtin/packages/r-affycoretools/package.py, var/spack/repos/builtin/packages/r-ff/package.py
Add package: r-affycoretools and r-ff.
=> r-affycoretools: Create new package and its dependency r-ff.

var/spack/repos/builtin/packages/r-globaloptions/package.py
=> r-globaloptions: new package

var/spack/repos/builtin/packages/r-alsace/package.py
=> r-alsace: Create new package.

var/spack/repos/builtin/packages/r-circlize/package.py
=> r-circlize: new package

var/spack/repos/builtin/packages/r-gtrellis/package.py
=> r-gtrellis: created new package

var/spack/repos/builtin/packages/r-getoptlong/package.py
=> r-getoptlong: created new package

var/spack/repos/builtin/packages/arlecore/package.py
adding new package arlecore. no versioned url available
=> arlecore: new package

var/spack/repos/builtin/packages/hwloc/package.py
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
=> hwloc: add version 1.11.8

var/spack/repos/builtin/packages/r-go-db/package.py, var/spack/repos/builtin/packages/r-gseabase/package.py, var/spack/repos/builtin/packages/r-pfam-db/package.py, var/spack/repos/builtin/packages/r-reportingtools/package.py
Add package r-reportingtools and update url for pfam-db, go-db, gseabase.
=> Add package r-reportingtools and update url for its dependencies.

lib/spack/llnl/util/link_tree.py, lib/spack/spack/cmd/activate.py, lib/spack/spack/cmd/deactivate.py, lib/spack/spack/cmd/extensions.py, lib/spack/spack/cmd/test.py, lib/spack/spack/cmd/view.py, lib/spack/spack/database.py, lib/spack/spack/directory_layout.py, lib/spack/spack/filesystem_view.py, lib/spack/spack/hooks/extensions.py, lib/spack/spack/package.py, lib/spack/spack/spec.py, lib/spack/spack/store.py, lib/spack/spack/test/cmd/view.py, lib/spack/spack/test/conftest.py, lib/spack/spack/test/spec_yaml.py, lib/spack/spack/test/test_activations.py, var/spack/repos/builtin.mock/packages/extension1/package.py, var/spack/repos/builtin.mock/packages/extension2/package.py, var/spack/repos/builtin/packages/aspell/package.py, var/spack/repos/builtin/packages/perl/package.py, var/spack/repos/builtin/packages/python/package.py
---
This is a rebase of #3227 that should be a lot easier to review. Basically, extension availability for views is now computed based on the view itself rather than looking globally.
Cc: @scheibelp
=> Fsview extensions

var/spack/repos/builtin/packages/r-hypergraph/package.py
=> r-hypergraph: Create new package.

var/spack/repos/builtin/packages/r-makecdfenv/package.py
=> r-makecdfenv: Create new package.

var/spack/repos/builtin/packages/r-altcdfenvs/package.py
=> r-altcdfenvs: Create new package.

var/spack/repos/builtin/packages/r-impute/package.py
=> r-impute: Create new package.

var/spack/repos/builtin/packages/r-samr/package.py
=> r-samr: Create new package.

var/spack/repos/builtin/packages/r-deseq/package.py
=> r-deseq: Create new package.

var/spack/repos/builtin/packages/r-statmod/package.py
=> r-statmod: Create new package.

var/spack/repos/builtin/packages/r-keggrest/package.py
=> r-keggrest: created new package

var/spack/repos/builtin/packages/r-yapsa/package.py
=> r-yapsa: created new package

var/spack/repos/builtin/packages/isaac/package.py
=> ISAAC 1.3.3

var/spack/repos/builtin/packages/relion/package.py
=> added relion v 2.1

var/spack/repos/builtin/packages/motioncor2/package.py
Compiled binary
http://msg.ucsf.edu/MotionCor2/MotionCor2-UserManual-09-06-2017
=> added new package - MotionCor2

var/spack/repos/builtin/packages/likwid/package.py
=> likwid: Use external lua if possible

var/spack/repos/builtin/packages/macsio/package.py, var/spack/repos/builtin/packages/typhonio/package.py
Added a new package for the TyphonIO library and edited the MACSio package to use it. 
Adding watcher: @gonsie
=> TyphonIO: new package + Updated MACSio package

var/spack/repos/builtin/packages/r-xmapbridge/package.py
=> r-xmapbridge: created new package

var/spack/repos/builtin/packages/r-bamsignals/package.py
=> r-bamsignals: Create new package.

var/spack/repos/builtin/packages/r-mergemaid/package.py
=> r-mergemaid: created new package

var/spack/repos/builtin/packages/r-dnacopy/package.py
=> r-dnacopy: Create new package.

var/spack/repos/builtin/packages/r-ggdendro/package.py
=> r-ggdendro: Create new package.

var/spack/repos/builtin/packages/r-xde/package.py
=> r-xde: created new package

var/spack/repos/builtin/packages/r-mzid/package.py
=> r-mzid: created new package

var/spack/repos/builtin/packages/r-reordercluster/package.py
Add package: r-reordercluster.
=> r-reordercluster: Create new package.

var/spack/repos/builtin/packages/r-maldiquant/package.py
=> r-maldiquant: created new package

var/spack/repos/builtin/packages/r-cowplot/package.py
=> r-cowplot: Create new package.

var/spack/repos/builtin/packages/fpc/package.py
=> fpc: new package

var/spack/repos/builtin/packages/jellyfish/package.py, var/spack/repos/builtin/packages/kraken/package.py
Adding new package kraken and dependency jellyfish
=> kraken: new package

var/spack/repos/builtin/packages/r-rhtslib/package.py
=> r-rhtslib: Create new package.

var/spack/repos/builtin/packages/flecsi/package.py
=> flecsi: fix build

var/spack/repos/builtin/packages/r-aneufinder/package.py
=> r-aneufinder: Create new package.

var/spack/repos/builtin/packages/r-aneufinderdata/package.py
Add package: r-aneufinderdata.
=> r-aneufinderdata: Create new package.

var/spack/repos/builtin/packages/r-qvalue/package.py
=> r-qvalue: Create new package.

var/spack/repos/builtin/packages/r-anaquin/package.py
=> r-anaquin: Create new package.

var/spack/repos/builtin/packages/r-tiff/package.py
=> r-tiff: created new package

var/spack/repos/builtin/packages/r-ampliqueso/package.py
=> r-ampliqueso: Create new package.

var/spack/repos/builtin/packages/guidance/package.py
=> guidance: new package

var/spack/repos/builtin/packages/gasnet/package.py, var/spack/repos/builtin/packages/legion/package.py
=> gasnet: add 1.30.0

var/spack/repos/builtin/packages/r-forecast/package.py
=> r-forecast: Create new package.

var/spack/repos/builtin/packages/r-fracdiff/package.py
=> r-fracdiff: Create new package.

var/spack/repos/builtin/packages/r-timedate/package.py
=> r-timedate: Create new package.

var/spack/repos/builtin/packages/r-xml2/package.py
=> r-xml2: created new package

var/spack/repos/builtin/packages/r-quantmod/package.py
Update version for r-quantmod.
=> r-quantmod: Update version to 0.4-11

var/spack/repos/builtin/packages/r-hexbin/package.py, var/spack/repos/builtin/packages/r-vsn/package.py
New package r-vsn and updated md5 for r-hexbin.
=> r-vsn: new package

var/spack/repos/builtin/packages/r-gsubfn/package.py
=> r-gsubfn: Create new package.

var/spack/repos/builtin/packages/r-sqldf/package.py
=> r-sqldf: Create new package.

var/spack/repos/builtin/packages/r-msnbase/package.py
=> r-msnbase: new package

var/spack/repos/builtin/packages/r-mzr/package.py
=> r-mzr: new package

var/spack/repos/builtin/packages/r-tseries/package.py
=> r-tseries: Create new package.

var/spack/repos/builtin/packages/r-selectr/package.py
=> r-selectr: created new package

var/spack/repos/builtin/packages/fastme/package.py
This package comes with some goofy broken symlinks, but force_autoreconf seems to fix that.
=> fastme: new package

var/spack/repos/builtin/packages/r-rvest/package.py
=> r-rvest: created new package

var/spack/repos/builtin/packages/r-rex/package.py
=> r-rex: Create new package.

var/spack/repos/builtin/packages/r-callr/package.py
=> r-callr: created new package

var/spack/repos/builtin/packages/sundials/package.py, var/spack/repos/builtin/packages/sundials/test_nvector_parhyp.patch
Add patch to remove unnecessary OpenMP include and commented out function call in hypre vector testing file.
=> add patch for building sundials

var/spack/repos/builtin/packages/sundials/package.py
=> add sundials 3.1.0

var/spack/repos/builtin/packages/r-analysispageserver/package.py
Add package: r-analysispageserver.
=> r-analysispageserver: Create new package.

var/spack/repos/builtin/packages/mesa/package.py
I moved from PR #5802  the commit that fix the mesa urls
=> mesa: fixed url for version

var/spack/repos/builtin/packages/r-rematch/package.py
=> r-rematch: Create new package.

var/spack/repos/builtin/packages/r-cellranger/package.py
=> r-cellranger: Create new package.

var/spack/repos/builtin/packages/r-readxl/package.py
=> r-readxl: Create new package.

var/spack/repos/builtin/packages/r-covr/package.py
=> r-covr: Create new package.

var/spack/repos/builtin/packages/r-purrr/package.py
=> r-purrr: Create new package.

var/spack/repos/builtin/packages/r-clipr/package.py
=> r-clipr: created new package

var/spack/repos/builtin/packages/xclip/package.py
=> xclip: created new package

var/spack/repos/builtin/packages/ascent/package.py, var/spack/repos/builtin/packages/conduit/package.py, var/spack/repos/builtin/packages/intel-tbb/package.py, var/spack/repos/builtin/packages/intel-tbb/tbb_gcc_rtm_key.patch, var/spack/repos/builtin/packages/vtkh/package.py, var/spack/repos/builtin/packages/vtkm/package.py
Adds ALPINE Ascent
Adds Ascent deps VTK-h, VTK-m
Updates to Conduit
=> add alpine ascent

var/spack/repos/builtin/packages/r-reprex/package.py
=> feature/r-reprex: new package

var/spack/repos/builtin/packages/mfem/package.py
A fix for some MFEM builds with MPI.
=> Fixed mfem mpi build issue.

lib/spack/docs/tutorial/examples/1.package.py, lib/spack/docs/tutorial/examples/2.package.py, lib/spack/docs/tutorial/examples/3.package.py, lib/spack/docs/tutorial/examples/4.package.py, lib/spack/docs/tutorial/examples/5.package.py, lib/spack/docs/tutorial_packaging.rst, lib/spack/spack/variant.py
Moved the packaging tutorial to build a generic package.  Updated it to include new output.
=> Update packaging tutorial

lib/spack/docs/tutorial.rst, lib/spack/docs/tutorial_configuration.rst
Other than 3 spots where I've noted "ADD BINARY CACHING OUTPUT" this is a complete first draft of the configurations section of the tutorial.
=> Add configuration tutorial

lib/spack/docs/tutorial_configuration.rst
I will never understand how our concretizer works...
=> Last minute edits to the Configuration Tutorial

lib/spack/docs/tutorial.rst, lib/spack/docs/tutorial/examples/1.package.py, lib/spack/docs/tutorial/examples/Autotools/0.package.py, lib/spack/docs/tutorial/examples/Autotools/1.package.py, lib/spack/docs/tutorial/examples/Autotools/autotools_class.py, lib/spack/docs/tutorial/examples/Cmake/0.package.py, lib/spack/docs/tutorial/examples/Cmake/1.package.py, lib/spack/docs/tutorial/examples/Cmake/2.package.py, lib/spack/docs/tutorial/examples/Cmake/cmake_class.py, lib/spack/docs/tutorial/examples/Makefile/0.package.py, lib/spack/docs/tutorial/examples/Makefile/1.package.py, lib/spack/docs/tutorial/examples/Makefile/2.package.py, lib/spack/docs/tutorial/examples/Makefile/3.package.py, lib/spack/docs/tutorial/examples/Makefile/makefile_class.py, lib/spack/docs/tutorial/examples/PyPackage/0.package.py, lib/spack/docs/tutorial/examples/PyPackage/1.package.py, lib/spack/docs/tutorial/examples/PyPackage/python_package_class.py, lib/spack/docs/tutorial_buildsystems.rst
First draft of the build system portion of the SC17 tutorial. Please let me know whether I should add more content or less. I haven't had a chance to find out how long this section will take. 
Suggestions from other non-reviewers would also be appreciated.
=> Add build systems tutorial for SC17

lib/spack/docs/tutorial/examples/Autotools/1.package.py, lib/spack/docs/tutorial_buildsystems.rst
=> Updates to build systems tutorial

var/spack/repos/builtin/packages/openmpi/package.py, var/spack/repos/builtin/packages/ucx/package.py
=> ucx: initial commit

var/spack/repos/builtin/packages/bash/package.py, var/spack/repos/builtin/packages/mpibash/package.py
=> mpibash: move to autotools

issue_template.md
I pushed this branch in the main repository to foster collaboration. Feel free to edit this!
=> Added an issue template for Github

var/spack/repos/builtin/packages/r-glue/package.py
=> r-glue: created new package

var/spack/repos/builtin/packages/r-bindr/package.py
=> r-bindr: created new package

var/spack/repos/builtin/packages/r-mnormt/package.py
=> r-mnormt: created new package

var/spack/repos/builtin/packages/r-forcats/package.py
=> r-forcats: created new package

var/spack/repos/builtin/packages/lmod/package.py
Builds for me on Ubuntu 16 with GCC 5.
=> Add the latest version of Lmod

var/spack/repos/builtin/packages/openmpi/package.py
=> Open MPI: add 2.0.4 release to package file

var/spack/repos/builtin/packages/r-dbplyr/package.py
=> r-dbplyr: created new package

var/spack/repos/builtin/packages/r-janitor/package.py
=> r-janitor: created new package

lib/spack/docs/tutorial/examples/Autotools/0.package.py, lib/spack/docs/tutorial/examples/Autotools/1.package.py, lib/spack/docs/tutorial/examples/Autotools/autotools_class.py, lib/spack/docs/tutorial/examples/Cmake/0.package.py, lib/spack/docs/tutorial/examples/Cmake/1.package.py, lib/spack/docs/tutorial/examples/Cmake/2.package.py, lib/spack/docs/tutorial/examples/Cmake/cmake_class.py, lib/spack/docs/tutorial/examples/Makefile/0.package.py, lib/spack/docs/tutorial/examples/Makefile/1.package.py, lib/spack/docs/tutorial/examples/Makefile/2.package.py, lib/spack/docs/tutorial/examples/Makefile/3.package.py, lib/spack/docs/tutorial/examples/Makefile/makefile_class.py, lib/spack/docs/tutorial/examples/PyPackage/0.package.py, lib/spack/docs/tutorial/examples/PyPackage/1.package.py, lib/spack/docs/tutorial/examples/PyPackage/python_package_class.py, var/spack/repos/builtin/packages/typhonio/package.py
```
git grep --files-with-matches github.com/llnl/spack | xargs sed -i '/github.com/s@llnl/spack@spack/spack@'
```
=> llnl/spack -> spack/spack

var/spack/repos/builtin/packages/cp2k/package.py
I don't know how best to do these as separate PRs as they build on one another. I try to keep separate tasks into logically complete commits. I'd appreciate some feedback especially on "cp2k: add smm variant to select from libxsmm or libsmm". Thanks!
=> cp2k: add dependency on smm and libxc & new version 5.1

var/spack/repos/builtin/packages/py-petsc4py/package.py
- Added explicit dependency on python and numpy
=> py-petsc4py: Update version to 3.8.0 and add dependencies

var/spack/repos/builtin/packages/msgpack-c/package.py, var/spack/repos/builtin/packages/neovim/package.py
Add some Cflags to MsgPack-C to make the compile task function under GCC7
Add a new version of neovim and fix a missing dependency
=> Minor package fixes

var/spack/repos/builtin/packages/r-sva/package.py
=> r-sva: Create new package.

var/spack/repos/builtin/packages/r-shortread/package.py
=> r-shortread: Create new package.

var/spack/repos/builtin/packages/r-rhdf5/package.py
=> r-rhdf5: Create new package.

var/spack/repos/builtin/packages/r-clusterprofiler/package.py
Add package: r-clusterprofiler.
=> r-clusterprofiler: Create new package.

var/spack/repos/builtin/packages/r-fgsea/package.py
=> r-fgsea: Create new package.

var/spack/repos/builtin/packages/r-do-db/package.py
=> r-do-db: Create new package.

var/spack/repos/builtin/packages/r-gosemsim/package.py
=> r-gosemsim: Create new package.

var/spack/repos/builtin/packages/r-rvcheck/package.py
=> r-rvcheck: Create new package.

var/spack/repos/builtin/packages/r-dose/package.py
=> r-dose: Create new package.

var/spack/repos/builtin/packages/rlwrap/package.py
Builds and passes all tests on macOS High Sierra with the Clang compiler.
=> Add a new package for rlwrap

lib/spack/spack/build_systems/cuda.py, var/spack/repos/builtin/packages/dealii/package.py
Ready for review.
~~this is a **work-in-progress**. Absolutely not tested and is certainly broken. For now the PR is only meant to accompany the discussion in https://github.com/LLNL/spack/issues/6005 .~~ 
~~I will be testing this PR mid November when my colleague @BenBrands who has CUDA is back to the office.~~
fixes https://github.com/spack/spack/issues/6005
=> dealii: add and use CudaPackage with all related variants and conflicts

var/spack/repos/builtin/packages/elpa/package.py
=> elpa: add 2017.05.002 and 2017.05.003

var/spack/repos/builtin/packages/masurca/package.py
=> masurca: new package

var/spack/repos/builtin/packages/r-modelr/package.py
=> r-modelr: created new package

var/spack/repos/builtin/packages/r-psych/package.py
=> r-psych: created new package

var/spack/repos/builtin/packages/r-haven/package.py
=> r-haven: created new package

var/spack/repos/builtin/packages/r-broom/package.py, var/spack/repos/builtin/packages/r-dplyr/package.py
- Added new package r-broom.
- Changed list_url for r-dplyr and added missing dependencies.
=> r-broom: new package

var/spack/repos/builtin/packages/mira/package.py
=> mira: new package

var/spack/repos/builtin/packages/gotcha/package.py
This adds a package for Gotcha
=> gotcha: new package

var/spack/repos/builtin/packages/phantompeakqualtools/package.py, var/spack/repos/builtin/packages/r-phantompeakqualtools/package.py
Adding new package phantompeakqualtools
=> phantompeakqualtools: new package

var/spack/repos/builtin/packages/flux/package.py, var/spack/repos/builtin/packages/py-brian2/package.py, var/spack/repos/builtin/packages/py-elephant/package.py, var/spack/repos/builtin/packages/py-pythonqwt/package.py, var/spack/repos/builtin/packages/py-qtconsole/package.py, var/spack/repos/builtin/packages/star-ccm-plus/package.py, var/spack/repos/builtin/packages/typhonio/package.py
=> Changed every 'docs' variant into 'doc'

var/spack/repos/builtin/packages/openblas/openblas_icc_fortran2.patch, var/spack/repos/builtin/packages/openblas/package.py
=> Add a patch for Intel 18.0.1

var/spack/repos/builtin/packages/openblas/package.py
=> Openblas needs FC, not F77

var/spack/repos/builtin/packages/libcint/package.py
This PR adds [libcint](https://github.com/sunqm/libcint) to Spack.
=> New Package: Add libcint to spack

var/spack/repos/builtin/packages/dialign-tx/dialign-1-0-2-gcc-5-4-0.patch, var/spack/repos/builtin/packages/dialign-tx/package.py
Small changes necessary to compile with gcc@5.4.0
=> dialign-tx adding patch for gcc@5.4.0

var/spack/repos/builtin/packages/gapbs/package.py
This is the reference implementation for the [GAP Benchmark Suite](http://gap.cs.berkeley.edu/benchmark.html).
=> New Package: GAP Benchmark Suite

var/spack/repos/builtin/packages/netlib-lapack/package.py, var/spack/repos/builtin/packages/plasma/add_netlib_lapacke_detection.patch, var/spack/repos/builtin/packages/plasma/package.py
=> plasma: extract plasma changes from xsdk-0.3.0

var/spack/repos/builtin/packages/r-cli/package.py
=> r-cli: new package

var/spack/repos/builtin/packages/r-dbi/package.py, var/spack/repos/builtin/packages/r-dorng/package.py, var/spack/repos/builtin/packages/r-downloader/package.py, var/spack/repos/builtin/packages/r-futile-logger/package.py, var/spack/repos/builtin/packages/r-getoptlong/package.py, var/spack/repos/builtin/packages/r-ggvis/package.py, var/spack/repos/builtin/packages/r-glmnet/package.py, var/spack/repos/builtin/packages/r-htmltools/package.py, var/spack/repos/builtin/packages/r-httpuv/package.py, var/spack/repos/builtin/packages/r-hwriter/package.py, var/spack/repos/builtin/packages/r-jsonlite/package.py, var/spack/repos/builtin/packages/r-lattice/package.py, var/spack/repos/builtin/packages/r-locfit/package.py, var/spack/repos/builtin/packages/r-matrix/package.py, var/spack/repos/builtin/packages/r-matrixstats/package.py, var/spack/repos/builtin/packages/r-memoise/package.py, var/spack/repos/builtin/packages/r-mpm/package.py, var/spack/repos/builtin/packages/r-nor1mix/package.py, var/spack/repos/builtin/packages/r-pkgconfig/package.py, var/spack/repos/builtin/packages/r-r6/package.py, var/spack/repos/builtin/packages/r-rcurl/package.py, var/spack/repos/builtin/packages/r-shiny/package.py, var/spack/repos/builtin/packages/r-tibble/package.py
More fixes to R modules similar to #6473 and #6462
=> Adding list_url to several R module packages

var/spack/repos/builtin/packages/r-topgo/package.py
=> r-topgo: Create new package.

var/spack/repos/builtin/packages/r-rcppcctz/package.py
=> r-rcppcctz: created new package

var/spack/repos/builtin/packages/r-classint/package.py
=> r-classint: created new package

var/spack/repos/builtin/packages/scr/package.py
@gonsie will add new version information.
=> update scr package for cray

var/spack/repos/builtin/packages/py-astroid/package.py
=> Fix astroid dependency and mark broken version

.travis.yml
Brew suggests this solution, let's see if it works.
fixes #6513
=> travis: removed /usr/local/include/c++ before installing gcc on OSX

var/spack/repos/builtin/packages/flit/package.py, var/spack/repos/builtin/packages/py-toml/package.py
Add the FLiT package along with py-toml
=> Flit package

var/spack/repos/builtin/packages/r-nanotime/package.py
=> r-nanotime: new package

var/spack/repos/builtin/packages/r-phyloseq/package.py
=> r-phyloseq: Create new package.

var/spack/repos/builtin/packages/r-biomformat/package.py
=> r-biomformat: Create new package.

var/spack/repos/builtin/packages/r-units/package.py
=> r-units: new package

var/spack/repos/builtin/packages/r-udunits2/package.py
=> r-udunits2: new package r-udunits2

var/spack/repos/builtin/packages/adios/package.py
=> ADIOS: 1.13.0

var/spack/repos/builtin/packages/r-fftwtools/package.py
=> r-fftwtools: new package

var/spack/repos/builtin/packages/py-h5py/package.py
py-pkgconfigig should be py-pkgconfig
=> fix a typo in py-h5py

var/spack/repos/builtin/packages/dealii/package.py, var/spack/repos/builtin/packages/netcdf-cxx/package.py, var/spack/repos/builtin/packages/netcdf-cxx4/package.py
build tested on `macOS + clang + netlib-scalapack` and `Ubuntu + gcc + intel-mkl`.
ps. most changes are from `"` to `'`.
p.s. FYI @BenBrands
=> dealii: add scalapack and various cleanups

var/spack/repos/builtin/packages/r/package.py
Add package `R` version `3.4.3`.
=> Added package r version 3.4.3

.mailmap, var/spack/repos/builtin/packages/adios/package.py, var/spack/repos/builtin/packages/adios2/package.py, var/spack/repos/builtin/packages/cuda-memtest/package.py, var/spack/repos/builtin/packages/gearshifft/package.py, var/spack/repos/builtin/packages/isaac-server/package.py, var/spack/repos/builtin/packages/isaac/package.py, var/spack/repos/builtin/packages/jansson/package.py, var/spack/repos/builtin/packages/libsplash/package.py, var/spack/repos/builtin/packages/libwebsockets/package.py, var/spack/repos/builtin/packages/mallocmc/package.py, var/spack/repos/builtin/packages/pngwriter/package.py, var/spack/repos/builtin/packages/xsimd/package.py, var/spack/repos/builtin/packages/xtensor/package.py, var/spack/repos/builtin/packages/xtl/package.py
Add myself as maintainer to the packages we contributed. On some of them we also maintain the mainline.
=> Add Maintainer

var/spack/repos/builtin/packages/cgns/package.py, var/spack/repos/builtin/packages/trilinos/package.py
This adds capability to CGNS and allows me to use it in Trilinos.
=> Update CGNS and add CGNS capability to Trilinos

var/spack/repos/builtin/packages/mrbayes/package.py
Fixing the mrbayes package to use a more recent repo for downloads. Fixes #6564
=> mrbayes: package fix

var/spack/repos/builtin/packages/r-org-hs-eg-db/package.py
=> r-org-hs-eg-db: Create new package.

var/spack/repos/builtin/packages/r-kegggraph/package.py
=> r-kegggraph: Create new package.

var/spack/repos/builtin/packages/r-pathview/package.py
=> r-pathview: Create new package.
