spack/spack

var/spack/repos/builtin/packages/nco/NUL-0-NULL.patch
var/spack/repos/builtin/packages/nco/package.py

This patch is needed to be able to build nco with GCC 7.

nco: Add patch to fix invalid conversion from char to char*

---

var/spack/repos/builtin/packages/ffmpeg/package.py

Add the ```yasm``` dependency to the ```ffmpeg```-package, while not strictly necessary resulting ```ffmpeg```-builds might be very slow (https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) without it

Fix ffmpeg (add missing yasm dependency)

---

var/spack/repos/builtin/packages/hdf5-blosc/package.py

Fixes #3676.
Well, it doesn't really fix the issue that:
```python
from __future__ import print_function
```
breaks a package, but it does remove the offending line from `hdf5-blosc`.

Fix future import in hdf5-blosc

---

var/spack/repos/builtin/packages/scorep/gcc7.patch
var/spack/repos/builtin/packages/scorep/package.py

Score-P's GCC plugin currently does not compile with GCC 7. This PR fixes that (the patch has already been sent to the upstream developers).

scorep: Fix build with GCC 7

---

lib/spack/spack/build_systems/cmake.py
lib/spack/spack/package.py
var/spack/repos/builtin/packages/archer/package.py
var/spack/repos/builtin/packages/llvm-openmp-ompt/package.py

Spack's `CMakePackage` base class now supports two generators: Unix Makefiles and Ninja.
Unfortunately, I can't test this due to #4985 and #4986.

Add better generator support to CMakePackage

---

lib/spack/docs/binary_caches.rst
lib/spack/docs/index.rst
share/spack/spack-completion.bash

The `spack buildcache` command was added a couple days ago in #4854, but there were a couple things missing:
1. Forgot to update the tab completion script with the new command
2. Docs didn't format well: http://spack.readthedocs.io/en/latest/binary_caches.html
This PR adds tab completion and updates the docs to fit better with the rest of our documentation.
@gartung Can you see if these changes look good to you?

Clean up docs on and add tab completion for buildcache command

---

lib/spack/spack/schema/config.py

This PR allows additional unused properties at the top-level of the config.yaml file. Having these properties permits to use two different versions of Spack, one of which adds a new property, without receiving error messages due to the presence of this new property in a configuration cache stored in the user's home.
---
Currently adding an entry to `config.yaml` and switching back to a version of Spack where this entry is not allowed gives an error similar to:
```console
$ spack help
File "/home/mculpo/PycharmProjects/spack/bin/spack", line 80, in <module>
import spack.main  # noqa
File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/__init__.py", line 84, in <module>
import spack.repository
File …
```

Relaxed constraints on config.yaml structure

---

lib/spack/spack/spec.py

Fixes #5066
This PR improves the error message for unsatisfiable specs by showing in tree format both the spec that cannot satisfy the constraint and the spec that asked for that constraint. After that follows a readable (?) error message.
---
The new error message for the example in #5066 is:
```hconsole
$ spack spec  mfem@3.2~debug+examples+hypre+lapack~mpfr+mpi+netcdf~openmp+petsc+suite-sparse+sundials+superlu-dist~threadsafe %gcc
Input spec
mfem@3.2%gcc~debug+examples+hypre+lapack~mpfr+mpi+netcdf~openmp+petsc+suite-sparse+sundials+superlu-dist~threadsafe
Normalized
mfem@3.2%gcc~debug+examples+hypre+lapack~mpfr+mpi+netcdf~openmp+petsc+suite-sparse+sundials+superlu-dist~threadsafe
^blas
^cmake@2.8:
^hdf5
^zlib@1.2.5: …
```

Improved error message for unsatisfiable specs

---

var/spack/repos/builtin/packages/libxslt/package.py

this is a fix to an installation that failed due to configure for some reason not finding the libiconv shipped with glibc, but still trying to link against it
see http://xmlsoft.org/FAQ.html

explicitly add libiconv dependency to libxslt

---

lib/spack/spack/cmd/info.py
lib/spack/spack/test/cmd/info.py

fixes #2708
This uses `llnl.util.tty.color` to colorize the output of `spack info`. It also adds a section to display the preferred version before listing all the safe versions in order.

Colorize spack info. Adds prominence to preferred version.

---

var/spack/repos/builtin/packages/check/package.py
var/spack/repos/builtin/packages/groff/gropdf.patch
var/spack/repos/builtin/packages/groff/package.py
var/spack/repos/builtin/packages/libpipeline/package.py
var/spack/repos/builtin/packages/man-db/package.py

Proposed closing #4839 :blush:
- not entirely sure if `check` is needed or if it can be avoided
- not sure what to do with the compression libraries
- do I need to explicitly `'--with-bzip2={0}/bzip2'.format(self.spec['bzip2'].prefix.bin)`?
- I just sort of assume that spack does that stuff but wasn't sure
Once you `spack load man-db` you should be able to view any other man page of things that show up in your `MANPATH` (for which many `spack` packages populate)!
@samfux84 does this work for you on that box?  I could very well have missed stuff given how quickly I threw this together :wink:

add man-db package and friends

---

var/spack/repos/builtin/packages/boost/package.py

Our software stack depends on both ```graph``` and ```mpi```, this PR changes the ```+mpi``` variant of boost to also include the standard ```graph```-library.

build boost with graph library even when +mpi

---

bin/sbang
lib/spack/spack/hooks/sbang.py

I'm migrating our current ```spack``` version from one from march to a current one. While doing that I'm going to open PR's for a couple of things that should be upstream. Most of these will be new packages of different versions of existing ones. This one is a bit different:
It adds hook-magic for node-js files. This seems to have caused problems with ```py-jupyter-notebook``` at some point in history. However I didn't run into problems when installing our software stack even without it, feel free to close this if you prefer it not to be merged.

Add sbang hook support for node-js

---

var/spack/repos/builtin/packages/tk/package.py

+ gitk (and possibly other tools) expects to find the Tk executable `wish`, so add a symlink with this name that points to the the versioned filename.
+ Example: `wish --> wish8.6`
+ Fixes #4167

For Tk, also provide a symlink for wishX.X.

---

var/spack/repos/builtin/packages/muscle/package.py

fixing muscle. Previously, with the `-static` flag, the build would fail:
```
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [muscle] Error 1
/tmp/las_thoma15/spack-stage/
```
Build is now successful

muscle: fix

---

var/spack/repos/builtin/packages/lbann/package.py

LBANN makes some hwloc calls but was missing an explicit dependency.

lbann: add depends_on hwloc

---

lib/spack/spack/test/modules.py

- Mac OS X Sierra has no `/usr/include` by default
- Instead of assuming there's an `include` directory in `/usr`, mock up a directory that looks like we expect.

Make test_inspect_path work on Mac OS X without XCode

---

lib/spack/spack/spec.py

Fixes #5156.
- `_separators` regex in spec.py could be constructed such that '^' came
first in the character matcher, e.g. '[^@#/]'.  This inverts the match
and causes transient KeyErrors.
- Fixed to escape all characters in the constructed regex.
- This bug comes up in Python3 due to its more randomized hash iteration
order, but it could probably also happen in a Python 2 implementation.

Fix issue with color formatting regular expression.

---

lib/spack/llnl/util/lang.py
lib/spack/llnl/util/tty/log.py
lib/spack/spack/build_environment.py
lib/spack/spack/error.py
lib/spack/spack/main.py
lib/spack/spack/package.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/log.py
var/spack/repos/builtin.mock/packages/printing-package/package.py

This reworks I/O redirection in Spack to avoid race cases, to make output more deterministic, and to ensure that everything gets logged in `build.out`.  Previously output could be different if you just ran `spack install` or ran `spack install | cat`.  This PR tries to make the output more deterministic and to simplify the interface to the `log_output` context handler.
```python
with log_output('logfile.txt') as log_redirection:
with log_redirection:
```
After:
```python
with log_output('logfile.txt'):
```
If you also want the output to be echoed to ``stdout``, use the `echo` parameter::
```python
with log_output('logfile.txt', echo=True):
```
And, if you just want to echo *some* stuff from the parent, use ``force_echo``:
```python
with log_output('logfile.txt', echo=False) as logger: …
```

Rework output redirection

---

var/spack/repos/builtin/packages/protobuf/package.py

New release of protobuf (3.4.0).
Already required in gRPC (develop, no official package yet).

Protobuf: 3.4

---

lib/spack/spack/directives.py
lib/spack/spack/spec.py
var/spack/repos/builtin/packages/espresso/package.py

fixes #4965
Users can now add an optional custom message to the conflicts directive. Layout on screen has been changed to improve readability and the long spec is shown in tree format. Two conflicts in `espresso` have been modified to showcase the feature.
In the current branch the error message is:
```console
$ spack spec espresso+scalapack~mpi
Input spec
espresso~mpi+scalapack
Normalized
espresso~mpi+scalapack
^blas
^fftw~mpi
^lapack
Concretized
==> Error: Conflicts in concretized spec "espresso@6.1.0%gcc@4.8+elpa~hdf5~mpi~openmp+scalapack arch=linux-ubuntu14-x86_64 /bzaylez"
List of matching conflicts for spec:
espresso@6.1.0%gcc@4.8+elpa~hdf5~mpi~openmp+scalapack …
```

Added custom messages for conflicts directive

---

lib/spack/docs/config_yaml.rst
lib/spack/docs/configuration.rst
lib/spack/spack/util/path.py

This will be useful for users wishing to install an external package in their home directory or an external repo in their home directory. They can then specify the location of these items using $home.

Add environment variables to directory substitution

---

var/spack/repos/builtin/packages/cdo/package.py

Updates for package 'cdo'.

---

var/spack/repos/builtin/packages/libaec/package.py

Provided list_url variable lets Spack find URL for a particular version.

Package 'libaec': no need to specify per version urls.

---

var/spack/repos/builtin/packages/boost/package.py

Adds the latest boost release.
Downloads seem to be pointing to bintray from the official homepage.

Boost: 1.65.0

---

lib/spack/llnl/util/tty/log.py
lib/spack/spack/build_environment.py
lib/spack/spack/cmd/install.py
lib/spack/spack/error.py
lib/spack/spack/main.py
lib/spack/spack/package.py
lib/spack/spack/stage.py
lib/spack/spack/test/cmd/dependencies.py
lib/spack/spack/test/cmd/dependents.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/cmd/python.py
lib/spack/spack/test/cmd/url.py
lib/spack/spack/util/log_parse.py

Currently, if you get a build error in Spack, you get this:
```console
$ spack install elfutils
==> Installing elfutils
==> Using cached archive: /Users/gamblin2/src/spack/var/spack/cache/elfutils/elfutils-0.163.tar.bz2
==> Staging archive: /Users/gamblin2/src/spack/var/spack/stage/elfutils-0.163-qyris2qgf3oq4fob5ss6hsfijy4crd6a/elfutils-0.163.tar.bz2
==> Created stage in /Users/gamblin2/src/spack/var/spack/stage/elfutils-0.163-qyris2qgf3oq4fob5ss6hsfijy4crd6a
==> No patches needed for elfutils
==> Building elfutils [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: ProcessError: Command exited with status 1:
'/Users/gamblin2/src/spack/var/spack/stage/elfutils-0.163-qyris2qgf3oq4fob5ss6hsfijy4crd6a/elfutils-0.163/configure' …
```

Show build log on build failure

---

var/spack/repos/builtin/packages/boost/package.py

Adds a development version of boost, based on their github [super repo](https://github.com/boostorg/boost).
Git clones the submodules forever, but it installs! :)
Useful for testing since boost tends to break complex software dependencies quite often. This helps testing it before releases.

Boost: develop

---

lib/spack/spack/spec.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/optional_deps.py
lib/spack/spack/test/spec_dag.py

The `*dep_like` argument of `Spec.__init__` is meant only for unit tests. This PR removes it from the call signature and introduces a static method `Spec.from_literal` to be used in tests.

Simplified Spec.__init__ signature by removing the '*dep_like' argument

---

var/spack/repos/builtin/packages/libfabric/package.py

Can now specify transports using a multivalued variant. 
For example:
``` bash
spack install libfabric fabrics=udp,verbs,sockets
```

Added variants to libfabric

---

etc/spack/defaults/packages.yaml
var/spack/repos/builtin/packages/isaac-server/jpeg.patch
var/spack/repos/builtin/packages/isaac-server/package.py
var/spack/repos/builtin/packages/isaac/package.py
var/spack/repos/builtin/packages/jasper/package.py
var/spack/repos/builtin/packages/libjpeg-turbo/package.py
var/spack/repos/builtin/packages/libjpeg/package.py
var/spack/repos/builtin/packages/libtiff/package.py
var/spack/repos/builtin/packages/opencv/package.py

This implements #1286
@ax3l, I had to fix 'isaac-server'. Could you, please, check if it is installed correctly with both libjpeg and libjpeg-turbo. And a question regarding 'isaac': are you sure that a header-only library needs all those dependencies?
@bvanessen, @mwilliammyers, @mathstuf, @alalazo could you check if I didn't break 'opencv'?

Make jpeg a virtual dependency.

---

var/spack/repos/builtin/packages/pkgconf/package.py

pkgconf is a new pkg-config implementation with additional features and no external dependencies.
For a detailed comparison, see: http://pkgconf.org/features.html
(This is just the new package split out of #5198 based on @davydden's advice.)

pkgconf: New package

---

lib/spack/spack/util/web.py

This PR prevents Spack from failing silently when it can't retrieve a list of urls due to a certificate verification problem. The PR also turns the verification off when 'spack -k'.

Respect --insecure (-k) flag when fetching list_url.

---

lib/spack/spack/build_environment.py

- "1 error found" instead of "1 errors found"
- don't print any build log context if no errors were found; just refer
the user to the build log.

Improve grammar in build log error message.

---

lib/spack/env/cc

Fixes #5137 
Users can specify that extra directories need to be RPATHed for a given compiler in compilers.yaml using the ```extra_rpaths``` entry, but this does not also ensure that the libraries are linked at build time. This modifies the logic so each extra RPATH directory also gets a ```-L``` entry so the directory is available at build time.

Link extra_rpaths from compilers.yaml at build time

---

lib/spack/spack/operating_systems/linux_distro.py

Since #1329 was closed, here is an updated version of the PR.
Ubuntu uses a YY.{04,10} release scheme, where YY.04 is not necessarily binary-compatible with YY.10. Therefore, it makes sense to also use the month part of the version.

Improve Ubuntu arch detection

---

lib/spack/spack/cmd/create.py

Since I had to adapt this for two new packages now, I guess it is easier to simply update the template. :-)

Fix copyright years in spack create template

---

lib/spack/spack/build_environment.py

This change is done to avoid inconsistencies during refactoring. The rationale is that functions at different levels in the call stack all define a default for the 'dirty' argument. This PR removes the default value for all the functions except the top-level one (`PackageBase.do_install`).
In this way not defining 'dirty' will result in an error, instead of the default value being used. This will reduce the risk of having an inconsistent behavior after a refactoring.

Removed default value for the function argument 'dirty'

---

lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/find.py
share/spack/spack-completion.bash

Occationally, a package can be built with different compilers for
some components. In these situations, it helps to be able to see
the full compiler version information. -F has been added to find
to accomplish this task.

Add -F option to find method

---

var/spack/repos/builtin/packages/py-fastaindex/package.py
var/spack/repos/builtin/packages/py-pyscaf/package.py
var/spack/repos/builtin/packages/redundans/package.py

adding new package redundans along with dependencies py-pyscaf and py-fastaindex. 
pypi.io [link](https://pypi.io/packages/source/f/FastaIndex/FastaIndex-0.11rc7.tar.gz)  for py-fastaindex doesn't work, resorting to github release.

redundans: new package

---

lib/spack/spack/spec.py

This modifies the `Spec` constructor so that `SpecParser` parses directly into the `Spec` being created, without creating an extra object or requiring a bunch of duplicated assignment statements.

Make Spec construction simpler.

---

lib/spack/spack/spec.py
lib/spack/spack/test/spec_semantics.py

The private method `Spec._dup` was missing a line (when setting compiler flags the parent spec was not set to `self`). This resulted in an inconsistent state of the duplicated Spec. This problem has been fixed here. The docstring of `Spec._dup` has been updated.
~The logic in `Spec.__init__` to assign members to `self` from `spec_list[0]` has been substituted by a call to `Spec._dup`. Even though the latter performs a copy while the former only an assignment, no performance hit has been noticed on an Ubuntu 14.04 platform. Unit tests take from 140 to 150 seconds, and `spack spec trilinos` takes  about 24 seconds, regardless of the change.~

Fixed bug in Spec._dup + updated docstring

---

lib/spack/spack/util/log_parse.py

When compiling llvm I got warnings that spack thought were errors. Things like this:
```
11502 /home/xap/local/opt/spack/var/spack/stage/llvm-4.0.0-zy57t3src64pg4hijvf2hy2xzhwsbkab/llvm-4.0.0.src/lib/Support/YAMLParser.cpp:2119:5: note: here
>> 11503 case Token::TK_Error:
11504      ^~~~
11505 /home/xap/local/opt/spack/var/spack/stage/llvm-4.0.0-zy57t3src64pg4hijvf2hy2xzhwsbkab/llvm-4.0.0.src/lib/Support/YAMLParser.cpp:2130:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
11506        getNext();
11507        ~~~~~~~^~
```
The problem is that matching "error:" should really check that it is a word.
I *think* adding `\b` should fix it, but have not tested it, and there may be a better way to do this.

Slightly better error matching when parsing spack logs

---

lib/spack/spack/cmd/info.py
lib/spack/spack/package.py
var/spack/repos/builtin/packages/dealii/package.py

fixes https://github.com/LLNL/spack/issues/2532
Currently prints:
```
$ spack info dealii
CMakePackage:   dealii
Description:
C++ software library providing well-documented tools to build finite
element codes for a broad variety of PDEs.
Homepage: https://www.dealii.org
Maintainers: @davydden @jppelteret
Preferred version:
8.5.1      https://github.com/dealii/dealii/releases/download/v8.5.1/dealii-8.5.1.tar.gz
...
```
p.s. @jppelteret i hope you don't mind me adding you as dealii maintainer.

add optional package maintainers

---

lib/spack/spack/build_systems/cmake.py
var/spack/repos/builtin/packages/llvm/package.py

Fixes #5258
I wasn't aware of this, but it appears that Package subclasses can override the variants of their parents. The llvm Cmake package was using the default Cmake build_type ```RelWithDebInfo``` which was significantly increasing the size of the package. This redefines the ```build_type``` variant for llvm and sets the default value to ```Release```.
Another option would be to set the default ```build_type``` to Release for all Cmake packages. I opted to set this specifically for llvm because it seemed particularly important that llvm control its default build type.

Set default cmake build_type to 'Release' for llvm

---

var/spack/repos/builtin/packages/allinea-forge/package.py
var/spack/repos/builtin/packages/allinea-reports/package.py

Fix below error : 
```
→ spack install -v allinea-forge
==> Installing allinea-forge
==> Using cached archive: /gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/var/spack/cache/allinea-forge/allinea-forge-6.0.4.tar
==> Already staged allinea-forge-6.0.4-hhqjib4p5cdy2ckk3kjjpuru4nvgpybd in /gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/var/spack/stage/allinea-forge-6.0.4-hhqjib4p5cdy2ckk3kjjpuru4nvgpybd
==> No patches needed for allinea-forge
==> Building allinea-forge [Package]
==> Found already existing license /gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/etc/spack/licenses/allinea-forge/Licence
==> Executing phase : 'install'
==> Error: TypeError: 'NoneType' object is not callable …
```

Fix allinea-forge and allinea-reports installation

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/env.py
lib/spack/spack/test/cmd/env.py

This command broke after #5109. It was using the default value for the `dirty` argument in `setup_package`. Now it adopts the same logic as in `spack install`. Trivial unit test included.

Fixed bug in `spack env` due to missing argument.

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/find.py
lib/spack/spack/cmd/info.py
lib/spack/spack/cmd/list.py
lib/spack/spack/file_cache.py
lib/spack/spack/repository.py
lib/spack/spack/test/cmd/find.py
lib/spack/spack/test/cmd/info.py
lib/spack/spack/test/cmd/list.py
var/spack/repos/builtin.mock/packages/mpich2/package.py
var/spack/repos/builtin/packages/aspa/package.py

Fixes #4781 
Fixes #1456
Fixes #1526
The querying commands `spack list`, `spack find` and `spack info` have been modified to support querying by tags. Tests have been added to check that the feature is working correctly under what I think will be the most frequent use cases.
```console
$ spack list --tags proxy-app
==> 8 packages.
aspa  cloverleaf3d  hpccg  miniaero  miniamr  minife  pathfinder  tealeaf
```
```console
$ spack find
==> 70 installed packages.
-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
autoconf@2.69  cloverleaf3d@1.0  flex@2.6.1        hdf5@1.10.1      libevent@2.0.21      libtool@2.4.6  mpich@3.2             netlib-scalapack@2.0.2  openmpi@2.1.1      scotch@6.0.4        voropp@0.4.6
automake@1.15  cmake@3.8.0       flex@2.6.1        hdf5@1.10.1 …
```

Added support for querying by tags

---

var/spack/repos/builtin/packages/mlhka/package.py

adding new package mlhka. In install phase, installing the binary only works if I specify `with working_dir(self.stage.source_path)`. If that's not specified I get a file not found error

mlhka: new package

---

lib/spack/spack/util/environment.py

First, quote the environment variable values.  Second, export the
variables. sorry, this is bourn-shell syntax.  Happy to consider a
shell-independent way to do this, but spack is already using sh-like
"env=value"

dump environment in sourceable form

---

lib/spack/docs/getting_started.rst
lib/spack/docs/module_file_support.rst
lib/spack/spack/cmd/bootstrap.py
lib/spack/spack/cmd/clone.py
share/spack/setup-env.sh
var/spack/repos/builtin/packages/environment-modules/package.py

This branch adds the ability to automatically build and enable environment-modules as part of `spack-env.sh`. The added code detects whether either dotkit or modules is available, and if neither is available, `environment-modules` is built and module function is introduced.
This change makes spack more portable as module support is automatically setup.

Bootstrap environment-modules

---

lib/spack/llnl/util/filesystem.py
lib/spack/spack/test/file_list.py

@alalazo @davydden 
Our previous name detection in HeaderList and LibraryList was very primitive. We were searching for the first period in the filename and assuming everything after it was an extension. In https://github.com/LLNL/spack/pull/5097#discussion_r133383164, @pramodskumbhar pointed out that some libraries, like `libpython3.6.dylib`, include a period in the library name. We also can't search for the last period, as some libraries are versioned, like `libmpi.so.20.10.1`. This PR searches for common library and header extensions and uses that to strip extensions.

Fix name detection in HeaderList and LibraryList

---

var/spack/repos/builtin/packages/caffe/package.py

Caffe's CMakeList.txt has:
```
set(python_version "2" CACHE STRING "Specify which Python version to use")
```
If we are compiling caffe with `python@3:`, then caffe finds python from `/usr/bin/`:
```
-- Could NOT find PythonInterp: Found unsuitable version "2.6.6", but required is at least "2.7" (found /usr/bin/python2)
-- Could NOT find PythonLibs: Found unsuitable version "2.6.6", but required is at least "2.7" (found /usr/lib64/libpython2.6.so)
-- To find NumPy Python interpretator is required to be found.
-- Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION) (Required is at least version "1.7.1")
....
--
-- Configuring done
CMake Error at CMakeLists.txt:104 (add_dependencies):
The dependency target "pycaffe" of target "pytest" does not exist.
```
this patch make sure …

Fix caffe build issue with python 3

---

var/spack/repos/builtin/packages/libgpuarray/package.py

Fix:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.0 or higher is required.  You are running version 2.8.12.2
```

Fix CMake minimum version

---

var/spack/repos/builtin/packages/paraview/package.py

Fix below error:
```
==> 'cmake' '/gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/var/spack/stage/paraview-5.4.0-l'-DVTK_USE_SYSTEM_ZLIB:BOOL=ON' '-DPARAVIEW_USE_MPI:BOOL=ON' '-DMPIEXEC:FILEPATH=/gpfs/bbp.cscs.ch/scratch/gss/bgq/kumbhar-adm/SPACK_HOME/install_home/bbpviz/install/linux-rhel6-x86_64/intel-17.0.4/intel-mpi-2017.3.196-s2b64uud/bin/mpiexec'
CMake Error at CMakeLists.txt:31 (cmake_minimum_required):
CMake 3.3 or higher is required.  You are running version 2.8.12.2
```
Paraview [doc](https://www.paraview.org/Wiki/ParaView:Build_And_Install) says:
```
The ParaView build process requires CMake version 3.3 or higher and a working compiler. 
```
The `CMakePackage` base class just specify `depends_on('cmake')` resulting into above mentioned error.

Paraview requires CMake version 3.3 or higher

---

var/spack/repos/builtin/packages/caffe/package.py

Caffe's CMake finds different installations of dependency resulting in link issues. Here is example where I install dependencies in `new_spack_path` and Caffe find some from `old_path`: 
```
==> openblas is already installed in /some_path/new_spack_path/install/linux-rhel6-x86_64/gcc-5.3.0/openblas-0.2.20-tgtgdmq2
==> Installing caffe
==> Using cached archive: /gpfs/bbp.cscs.ch/scratch/gss/bgq/kumbhar-adm/SPACK_HOME/var/spack/cache/caffe/caffe-1.0.tar.gz
==> Already staged caffe-1.0-5oxpymqlimusuqdvzvrtv4llf66i3hr2 in /gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/var/spack/stage/caffe-1.0-5oxpymqlimusuqdvzvrtv4llf66i3hr2
==> No patches needed for caffe
==> Building caffe [CMakePackage]
==> Executing phase: 'cmake'
==> 'cmake' …
```

Improve caffe dependency detection with extra CMake flags

---

var/spack/repos/builtin/packages/py-matplotlib/package.py

While building matplotlib  with intel compiler we get:
```
spack install  'py-matplotlib@2.0.2+image%intel@17.0.4^py-numpy+blas+lapack@1.13.1^python@3.5.2^intel-mkl
.....
building 'matplotlib._qhull' extension
/gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/lib/spack/env/intel/icc -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fPIC -DMPL_DEVNULL=/dev/null -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib__qhull_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -I/gpfs/bbp.cscs.ch/scratch/gss/bgq/kumbhar-adm/SPACK_HOME/install_home/bbpviz/install/linux-rhel6-x86_64/intel-17.0.4/py-numpy-1.13.1-i6vgp46b/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include -I/usr/include -I. -I/gpfs/bbp.cscs.ch/scratch/gss/bgq/kumbhar-adm/SPACK_HOME/install_home …
```

Fix matplotlib build issue with intel compiler

---

var/spack/repos/builtin/packages/pdt/package.py

PDT dependency of TAU profiler doesn't use `CC`, `CXX` eb variables and need command line argument for compiler identification: 
```
$ ./configure --help
Program Database Toolkit (PDT) Configuration
--------------------------------------------
Looks like an x86_64 machine...
Looking for C++ compilers ... done
Usage: ./configure [-KAI|-KCC|-GNU|-CC|-c++|-cxx|-xlC|-pgCC|-icpc|-ecpc]
[-arch=ibm64|ibm64linux|solaris2-64|sunx86_64|IRIXO32|
IRIXN32|IRIX64|ia64|i386_linux|crayxmt|arm64_linux|ibm64linux]
[-help]
[-compdir=<compdir>]
[-enable-old-headers]
[-useropt=<options>]
[-prefix=<dir>]
[-exec-prefix=<dir>]
```
If we don't pass compiler id then it uses gcc and result in link time errors while building tau: 
```
checking whether gcc and cc understand -c and -o together... pgc++    -O2 …
```

Improve PDToolkit support for different compilers

---

var/spack/repos/builtin/packages/adios/package.py

Fix below two issues:
m4 dependency missing:
```
/gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/lib/spack/spack/build_systems/autotools.py:210, in autoreconf:
7             missing = [x for x in autotools if x not in spec]
8             if missing:
9                 msg = 'Cannot generate configure: missing dependencies {0}'
>> 10                raise RuntimeError(msg.format(missing))
11            tty.msg('Configure script not found: trying to generate it')
12            tty.warn('*********************************************************')
```
ADIOS [doc](http://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.9.0.pdf) suggest to set `MPICC`, `MPICXX`. Without this I got : 
```
env/intel/icc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether …
```

Fix Autotools build error due to missing m4 and MPICC/MPICXX

---

var/spack/repos/builtin/packages/glog/package.py

Installing glog with system gcc worked fine. But I have also `gcc 5.3.0` compiled by Spack. While compiling with this newer gcc I had multiple link errors:
```
libtool: link: /gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/lib/spack/env/gcc/g++ -pthread -I/usr/include -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -pthread -o .libs/demangle_unittest src/demangle_unittest-demangle_unittest.o -pthread  ./.libs/libglog.so -lunwind -L/usr/lib64 -lgtest -lgflags -lpthread -pthread -Wl,-rpath -Wl,/gpfs/bbp.cscs.ch/scratch/gss/bgq/kumbhar-adm/SPACK_HOME/install_home/bbpviz/install/linux-rhel6-x86_64/gcc-5.3.0/glog-0.3.4-3lulcx7y/lib
libtool: link: /gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/spack/lib/spack/env/gcc/g++ -pthread -I/usr/include …
```

Change glog from Autotools to CMakePackage

---

var/spack/repos/builtin/packages/caffe/package.py

There are some opencv dependencies missing such as "core" that are mandatory in order to complete the caffe build.

Missing opencv dependencies

---

var/spack/repos/builtin/packages/armadillo/package.py
var/spack/repos/builtin/packages/armadillo/undef_linux.patch

- most compilers `#define linux 1`
- armadillo does raw pasting of include directories in code
- this means macro expansion of `linux-x86_64` -> `1-x86_64`
- new version, previous download url seems broken
- lib64 instead of lib?
- needs verification, was required for intel, works for others
This is some ridiculous hacking, but it seems to work.  This PR needs review over the patching, there **has** to be a better way to get the extracted archive directory....RIGHT????
I found it by `__dict__` crawling.  Which is never exactly promising.
Fixes #2061 
Fixes #2808

fix armadillo macro expansions

---

share/spack/setup-env.sh

These were discovered with bash 4.1.2.
Add quotations around a variable to prevent the destruction of a
newline. Without this fix a conditional doesn't work properly.
Remove square brackets around a conditional meant to be evaluated based
on the return code of a command. This wasn't working properly with an
old bash.
Fix a typo.

Fix two bugs from the bootstrap update

---

var/spack/repos/builtin/packages/elemental/cmake_0.87.7.patch
var/spack/repos/builtin/packages/elemental/package.py

partly submitted upstream https://github.com/elemental/Elemental/pull/242 and partly [already fixed](https://github.com/elemental/Elemental/blob/master/cmake/configure_files/ElementalConfig.cmake.in#L16).
p.s. that's relevant for downstream projects only.

elemental: fix broken Config.cmake

---

lib/spack/spack/build_systems/autotools.py
lib/spack/spack/test/build_systems.py
var/spack/repos/builtin.mock/packages/a/package.py
var/spack/repos/builtin/packages/adios/package.py
var/spack/repos/builtin/packages/openmpi/package.py
var/spack/repos/builtin/packages/viennarna/package.py

Fixes #4112
This commit extends the support of the `AutotoolsPackage` methods `with_or_without` and `enable_or_disable` to bool-valued variants. It also defines for those function a convenience short-cut if the
activation parameter is the prefix of a spec (like in `--with-{pkg}={prefix}`).
I added a couple of examples to show how the packages would look like once ported.

'with_or_without' accepts bool variants

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/spec.py
lib/spack/spack/test/directory_layout.py

Fixes #5281.
@obreitwi @ax3l @alalazo @scheibelp @healther 
_concrete attribute.
- The various concrete() methods on different types of Specs would
attempt to statically compute whether the Spec was concrete.
- This dates back to when DAGs were simpler and there were no optional
dependencies.  It's actually NOT possible to compute statically
whether a Spec is concrete now.  The ONLY way you know is if it goes
through concretization and is marked concrete once that completes.
- This commit removes all simple concreteness checks and relies only on
the _concrete attribute.  This should make thinking about
concreteness simpler.
- Specs read from files and Specs that are destructively copied from
concrete Specs now need to be marked concrete explicitly.
- These spots may previously have …

clean up concreteness detection

---

var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/dealii/package.py

otherwise from `BZIP2_DIR` only `dealii` may end-up with:
```
```

dealii: explicitly specify bzip2 libs

---

var/spack/repos/builtin/packages/libbson/package.py
var/spack/repos/builtin/packages/libmongoc/package.py

This also introduces the ssl, snappy and zlib variants for libmongoc.

Update libbson and libmongoc to 1.7.0

---

var/spack/repos/builtin/packages/openblas/package.py

also add a dummy to `atlas` for consistency.

Openblas ilp64

---

lib/spack/spack/build_environment.py
lib/spack/spack/spec.py

The correct place to set the mutual references between spec and package objects at the end of concretization. After a call to concretize we should now be ensured that spec is the same object as spec.package.spec.
Code in `build_environment.py` that was performing the same operation has been turned into an assertion to be defensive on the new behavior.
----
Needed by #3183 after the merge of #5332 (but it seems of general use, hence the PR)

Spec.concretize() sets mutual spec-package references

---

var/spack/repos/builtin/packages/boost/package.py

Add hash & url of the latest boost bugfix release, 1.65.1:
http://www.boost.org/users/history/version_1_65_1.html
Besides other fixed issues, it adds compatibility for the upcoming CUDA 9 release.

Boost: 1.65.1

---

var/spack/repos/builtin/packages/libsodium/package.py

updates the URLs for libsodium releases. Fixes broken builds (404).

libsodium: update URLs

---

var/spack/repos/builtin/packages/adios/package.py

This fixes the build of the ADIOS package.
The `with_or_without` interface of the Autotools builds seems to have changed, this fixes it.

ADIOS: Fix Build (Autotools)

---

share/spack/setup-env.sh

This quiets the module parts of `setup-env.sh` and addresses some of the concerns in #5351.

Remove echo statements from setup-env.sh

---

var/spack/repos/builtin/packages/intel-tbb/package.py

Seems like tbb release tarball was silently updated:
```
$ spack install -v intel-tbb
==> Installing intel-tbb
==> Fetching from /Users/kumbhar/workarena/software/sources/spack/var/spack/cache/intel-tbb/intel-tbb-2017.6.tar.gz failed.
==> Fetching https://github.com/01org/tbb/archive/2017_U6.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: sha1 checksum failed for /Users/kumbhar/workarena/software/sources/spack/var/spack/stage/intel-tbb-2017.6-mrccgn36heynwzxrzefxyxwajx5wfvpr/2017_U6.tar.gz
Expected 5b0909fbb1741724f7a0ce83232f50b166788af0 but got c0a722fd1ae66b40aeab25da6049086ef5f02f17
ChecksumError: ChecksumError: sha1 checksum failed for /Users/kumbhar/workarena/software/sources/spack/var/spack/stage/intel-tbb-2017.6-mrccg …
```

Fix checksum of Intel TBB package

---

var/spack/repos/builtin/packages/ncl/package.py
var/spack/repos/builtin/packages/ncl/ymake-filter.patch

Fixes a problem in ymake-filter: The line buffer is currently hardcoded to be 2048 bytes large but some Makefiles contain lines longer than that. This caused the Makefiles to sometimes not be generated, consequently failing parts of the build.
This used to work with GCC 6 but since updating to GCC 7, I have observed sporadic errors when building ncl. The patch has already been forwarded to upstream.

ncl: Fix buffer overflow in ymake-filter

---

var/spack/repos/builtin/packages/augustus/package.py

Fixing url for augustus. We need v 3.2.3 but sometime after the new version came out the urls got moved around

augustus: url fix

---

lib/spack/spack/build_systems/cmake.py

To be on the safe side and make CMake packages pick up direct dependencies from where we want, i think we shall set `CMAKE_PREFIX_PATH` which is the first place [find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html) will look at.
**~~do not merge yet~~:** there are some issues i don't quite understand
```
$ spack install lammps
==> openmpi is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/openmpi-2.1.1-4vl27tg7gal5kqxsfislmkta2cb2vus2
==> cmake is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/cmake-3.7.2-x2vsvmeg76dkdsslny3rhgwk66fej5nh
==> Installing lammps
==> Error: TypeError: sequence item 0: expected string, Spec found
TypeError: TypeError: sequence item 0: expected string, …
```

set CMAKE_PREFIX_PATH for cmake packages

---

var/spack/repos/builtin/packages/openmpi/package.py

Open MPI 3.0.0 is released!  Add to spack.

Open MPI:  add Open MPI 3.0.0

---

lib/spack/spack/test/module_parsing.py
lib/spack/spack/util/module_cmd.py

Also inspect `PATH` to help locate an external package.
Fixes #5141

Improve external package location detection algorithm.

---

lib/spack/spack/build_systems/cmake.py

#5364 added `CMAKE_PREFIX_PATH` but didn't filter system paths.
See [5364-comment](https://github.com/LLNL/spack/pull/5364#issuecomment-330037055).

Filter system paths from CMAKE_PREFIX_PATH

---

var/spack/repos/builtin/packages/intel-tbb/package.py

from the release notes
> If you build Intel(R) TBB from sources with GCC 6, specify
the -flifetime-dse=1 option to prevent crashes at runtime,
or use Intel(R) TBB makefiles that automatically set this option.
my understanding that we use TBB's makefiles, so this should happen automatically.

tbb: add 2018

---

lib/spack/spack/test/cmd/install.py
lib/spack/spack/util/log_parse.py
var/spack/repos/builtin.mock/packages/build-error/package.py

Fix a bug introduced in #5236.
- `'\b'` in regular expression needs to be in a raw string (`r'\b'`)
- Regression test that would've caught this was unintentionally disabled
- Reviewer (me) didn't catch this either 😬 
@aprokop

Fix log error parsing bug introduced in c830eda

---

lib/spack/spack/build_environment.py
lib/spack/spack/cmd/install.py
lib/spack/spack/package.py
lib/spack/spack/test/cmd/install.py

#5387 should be merged before this.
that caused them, in the 'pkg' attribute.
InstallErrors and prints the log to stderr if it exists.
Note that adding a reference to the Pakcage allows a lot of stuff
currently handled by do_install() and build_environment to be handled
externally.
@pramodskumbhar: does this do what you wanted in #5016?
@alalazo @adamjstewart

Add --show-log-on-error option to `spack install`

---

var/spack/repos/builtin/packages/scorep/package.py

Supersede #5368
(used cname short form for 80 char limit)

Improve scorep package with different compilers and mpi providers

---

var/spack/repos/builtin/packages/hdf5/package.py

When installing the default HDF5 (with defaults: `+fortran`, `+mpi`) with `clang@4.0.1` (and `gfortran@5.4.0` as `FC`), the linking of `libhdf5_fortran` fails on a missing `-lnuma` with the default `openmpi@2.1.1` during the `build` stage.
```bash
spack install hdf5 %clang@4.0.1
```
This fixes it by adding `numactl` which ships `libnuma`.
Note: Installs without MPI or Fortran succeeded already, so I only added it on `+mpi+fortran`.
```bash
spack install hdf5~mpi %clang@4.0.1
spack install hdf5~fortran %clang@4.0.1
```

HDF5: Fortran MPI needs Numactl

---

var/spack/repos/builtin/packages/cgns/package.py

+ The recipe for cgns seems to be wrong. CMake complains about variables set but not used (`HDF5_NEEDS_ZLIB`, `HDF5_NEEDS_MPI` and `HDF5_NEEDS_SZIP`) and fails to find HDF5.
+ This change-set removes these variables from the cmake configure line, replacing them with `'-DHDF5_DIR=%s' % spec['hdf5'].prefix`
+ cgns also has trouble with parallel make, so I set `parallel = False`.

Update recipe for cgns to avoid build warnings/errors:

---

var/spack/repos/builtin/packages/sambamba/Makefile.patch
var/spack/repos/builtin/packages/sambamba/package.py

Depends on the ldc package (#5279) that alalazo's working on.
It requires a patch to the Makefile because one of ldc's library functions mentions dlopen.  I *think* that ldc should be handling this.  See the discusssion in #5279.
It also requires a "static" ldc.  Again, see #5279.
Finally, it needs "undeaD" as a resource, but I'm guessing at the appropriate release.  See lomereiter/sambamba#312.
Also need to investigate whether it requires `parallel=False` (`spack create` added that...).

[WIP]: Sambamba new package

---

var/spack/repos/builtin/packages/mono/package.py

Add new version infor for mono@5.4.0.167.
Lightly tested on CentOS 7.

Add info for mono@5.4.0.167

---

var/spack/repos/builtin/packages/cereal/package.py

The include line failed when I tried to install it, I'm not too sure why it is there in the first place, removing it solved my problem and it seems to be a working installation.

fix install method of cereal

---

var/spack/repos/builtin/packages/texlive/package.py

TeXLive updates their installer without changing its name.  We've been playing keep-up with them, but I'm proposing it's not worth it.
I seem to end up installing it '--no-checksum' anyway.
This commit updates the package to make that approach official, removing the checksum, adding a note to the description and a bigger note/comment inthe package body.

Use trusted/historic site for texlive installer

---

var/spack/repos/builtin/packages/openblas/package.py

closes #4275 
This PR creates the ```cpu_target``` variant for openblas. We had the issue of building openblas on cluster nodes which had a more modern CPU architecture, with the architecture specific optimisations automatically turned on. This lead to ```illegal instruction``` failures (e.g., in matplotlib) on the frontends.

Add cpu_target variant to openblas

---

lib/spack/spack/concretize.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/spec_syntax.py

Fixes #3724
Prior to this commit, Spack chooses whatever compiler appears first in compilers.yaml when there are no preferences. This changes the logic to prefer newer compiler versions by default.

Prefer later versions of compilers by default

---

var/spack/repos/builtin/packages/py-csvkit/package.py
var/spack/repos/builtin/packages/py-dateutil/package.py
var/spack/repos/builtin/packages/py-dbf/package.py
var/spack/repos/builtin/packages/py-openpyxl/package.py

Spack doesn't (or can't?) check versions in python package requirements. py-csvkit will install, but running any of the commands will fail when it doesn't find preferred dependency versions.

Version fixes for py-csvkit

---

var/spack/repos/builtin/packages/pmix/package.py

Open MPI has been relying on versions of PMIx since the 2.0.0
release.  Although the embedded version can be used, it makes
more sense long term for Spack to know about the PMIx package,
and to build Open MPI against PMIx as an external package.
There are other software components that may eventually be
reliant on PMIx including MPICH, GASNet, the OpenSHMEM reference
implementation, etc.
This is also partly motivated by the desire to have ECP ST
projects be released through Spack.

PMIx: add PMIx package to Spack

---

var/spack/repos/builtin/packages/plumed/package.py

Due to the logic in configure.ac, we may be using both the system linker (`LD_RO='ld -r -o'`) and the linker tied to the compiler (`LD=$CXX`). This may produce weird link-time errors when the two executables are not the same.
The PR works around the issue by saying LD_RO does not exist.

plumed: fixed possible linking issue

---

var/spack/repos/builtin/packages/emacs/package.py

25.3 is a security update: info here: https://lists.gnu.org/archive/html/info-gnu/2017-09/msg00006.html
Build both +X and ~X on CentOS 7 and lightly tested.

Add info for emacs@25.3

---

var/spack/repos/builtin/packages/git/package.py
var/spack/repos/builtin/packages/pcre/package.py

Update the git package to git@1.14.1.
This requires a pcre that has been built with `--enable-jit`, so I've
added a variant to pcre to support that and arranged so that gits
before 2.14 depend on pcre and after 2.14 depend on pcre+jit.
Lightly tested on CentOS 7.

Update git to @2.14.1, requires pcre+jit variant

---

var/spack/repos/builtin/packages/ack/package.py

Lightly tested on CentOS 7 with Spack's perl 5.24.1.

Update Ack with info for version 2.18

---

var/spack/repos/builtin/packages/atlas/package.py
var/spack/repos/builtin/packages/elemental/package.py
var/spack/repos/builtin/packages/intel-mkl/package.py
var/spack/repos/builtin/packages/intel-parallel-studio/package.py
var/spack/repos/builtin/packages/openblas/package.py

build on Ubuntu 16 + gcc 5.4.0:
macOS Sierra + clang + gfortran:
in the later case for externally provided `intel-mkl@2018.0.128` in `opt/intel` we have:
```
LIBBLAS = -L/opt/intel/mkl/lib -L/usr/lib -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lpthread -lm -ldl
SCALAP = -L/opt/intel/mkl/lib -lmkl_scalapack_lp64 -lmkl_blacs_mpich_lp64
```
```
$ otool -L /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/dealii-develop-n6julmgj2gj6twxodwe275zys4ily3fw/lib/libdeal_II.dylib  | grep "mkl"
@rpath/libmkl_scalapack_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libmkl_blacs_mpich_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libmkl_core.dylib …
```

blas_lapack: add multithreading variant consistent in all implementations.

---

var/spack/repos/builtin/packages/llvm/llvm_gcc7.patch
var/spack/repos/builtin/packages/llvm/package.py

Fix #4986.
Tested `spack install llvm@4.0.0 %gcc@7.1.0`.
EDIT: Fixed ^ to % for gcc.

llvm: patch lldb for gcc-7

---

var/spack/repos/builtin/packages/mosh/package.py
var/spack/repos/builtin/packages/protobuf/package.py

Required an update to the protobuf digest value, which seems to be amongst the set creamed by GitHub's change.
@tgamblin, @alalazo -- Is this an appropriate way to handle an example the digest conflicts or should I wait for something system wide?

New version for mosh1.3.2

---

lib/spack/spack/environment.py
lib/spack/spack/modules/common.py
lib/spack/spack/test/environment.py
lib/spack/spack/util/environment.py

closes #5201
Currently, if a user sets an external package to have a prefix that is one of the system paths (like `/usr`) the module files that are generated will prepend `/usr/bin` to `PATH`, etc. This is particularly nasty at the time when a module file is unloaded, and e.g. paths like `/usr/bin` will be discarded from `PATH`.
This PR solves the issue skipping system paths when a prefix inspection is made to generate module files.

module files: system paths are excluded from path inspection

---

var/spack/repos/builtin/packages/protobuf/package.py

GitHub releases with additional `.tar.gz` source archive uploads to their actual tag tend to return random selections of which archive shall be taken. Related to  #5356
This fixes it for protobuf with a hack to prioritize *GitHub Source Archives* over *additional release artifacts*. The interesting observation is also, that the pick from the `list_url` is also *not deterministic*.
I would propose to rewrite `lib/spack/spack/util/web` to use for pages, links and versions an ordered dict to get at least determinism into the version url fetching.
Before (note the wrong pick in the `3.3.0` & `3.4.0` release!):
```
$ spack checksum protobuf
==> Found 10 versions of protobuf:
3.4.1     https://github.com/google/protobuf/archive/v3.4.1.tar.gz
3.4.0rc3 …
```

Fix Protobuf URLs

---

var/spack/repos/builtin/packages/r-xml/package.py

Updated url for package r-xml. The previous one expired. Added version 3.98-1.9.

r-xml: updated url and added version 3.98-1.9

---

var/spack/repos/builtin/packages/glib/package.py
var/spack/repos/builtin/packages/libx11/package.py
var/spack/repos/builtin/packages/likwid/package.py
var/spack/repos/builtin/packages/shared-mime-info/package.py

While building packages in a minimal chroot, I found some packages that are missing a dependency on perl and/or hardcore perl paths in their scripts.

Missing perl dependencies

---

var/spack/repos/builtin/packages/autoconf/package.py
var/spack/repos/builtin/packages/automake/package.py

While building a few packages in a minimal chroot, I noticed that autoconf and automake are missing a perl dependency. When adding it, a few of the tools fail because the shebang is too long, so we have to fix those up. We also have to remove `-w` from the shebang because of https://unix.stackexchange.com/questions/14887/the-way-to-use-usr-bin-env-sed-f-in-shebang. Fun times.
This also seems to fix #3719 for me (Fedora 26).

autoconf, automake: Add missing perl dependency

---

var/spack/repos/builtin/packages/snappy/package.py

Convert to CMakePackage and add a pkg-config file (otherwise libmongoc's pkg-config file does not contain all required flags).

snappy: Update to 1.1.7

---

share/spack/setup-env.sh

type's output can be localized, causing the grep to fail.

Fix _spack_fn_exists

---

var/spack/repos/builtin/packages/sz/package.py

Hi,
I didn't realize the previous SPACK version I was working on is not the latest one. 
I have pulled the SPACK again, and there should be no merge conflicts now. 
Please use the latest version of SZ instead in your package. 
We added the executable (called sz) in the new version, and also fixed some bugs. 
Thanks.
Best,
Sheng

Pull request for new version of SZ1.4.11

---

var/spack/repos/builtin/packages/paraview/package.py

- add depend qualifier for `mesa+swrender` when building with `+osmesa`
- make +qt a conflict when +osmesa is specified
- new paraview version (5.4.1 from August)

Adjust paraview configuration

---

var/spack/repos/builtin/packages/ncl/package.py

If csh is not installed globally, ncl fails to compile. This PR fixes that by adding a dependency on tcsh (depends on #5194). All ncl scripts hardcode /bin/csh, so we have to fix them up.

ncl: Add tcsh dependency

---

var/spack/repos/builtin/packages/snappy/package.py

The switch to CMake caused snappy to build static libraries, which breaks (at least) leveldb.
Edit: Also fixes a small problem with the pkg-config file.

snappy: Build shared library by default

---

var/spack/repos/builtin/packages/openfoam-com/package.py

partially resolves #5428
- The newest openfoam version requires openmpi+thread_multiple for
collated output.
Added in two safety mechanisms.
- A spec-level conflict, but also raise an InstallError if the mpi
provider has resolved to openmpi without the +thread_multiple
variant. This additional check unfortunately seems to be required
for the additional openmpi constraint, since openfoam only directly
depends_on 'mpi', not on 'openmpi'.
Without this runtime check, the user could easily compile and
install with the incorrect openmpi configuration and experience
various issues with openfoam.

Restrict openfoam to using openmpi+thread_multiple

---

var/spack/repos/builtin/packages/amrex/package.py

The tag for amrex to download the develop version was incorrect. It was `develop` but needed to be `development`

One liner to fix tag for Amrex development branch

---

lib/spack/spack/modules/common.py
lib/spack/spack/test/modules/lmod.py

closes #5473
Prior to this PR we were not exiting early for external packages, which caused the `configure_options` property of the contexts to fail with e.g. a key error because the DAG gets truncated for them. More importantly Spack configure options don't make any sense for externals.
Now we exit early, and leave a message in the module file clarifying that this package has been installed outside of Spack.

modules: specialized configure_options for external packages

---

lib/spack/docs/mirrors.rst

Mirrors are directories (that use `file://` URLS, not files.

Typo: file -> directory

---

lib/spack/external/ctest_log_parser.py
lib/spack/spack/build_environment.py
lib/spack/spack/test/util/log_parser.py
lib/spack/spack/util/log_parse.py

https://github.com/Kitware/CMake/blob/master/Source/CTest/cmCTestBuildHandler.cxx
These are BSD licensed, so the port is in `externa/ctest_log_parser.py`
@aprokop: this doesn't cause a regression on your error message from #5236, does it?
@pramodskumbhar: FYI

Port CTest's log scraping logic to Spack

---

var/spack/repos/builtin/packages/cuda/package.py

The first stable release of CUDA 9, v9.0.176, is out.
This adds its installer and checksum.

CUDA 9.0.176

---

var/spack/repos/builtin/packages/mpfr/package.py

This is a partial fix for #5564.
This package used to trust that `configure` would discover `gmp` from its environment.
It's safer to tell it where to find `gmp` explicitly.
This does that by adding a configure_args() that provides a `--with-gmp=...` argument for configure.
Lightly tested on CentOS 7.
I'm still running in to something that looks like #5578.

Tell configure about gmp (partial fix for #5564)

---

var/spack/repos/builtin/packages/libpng/package.py

explicitly set the zlib path for libpng configure.
Unfortunately, the standard [`--with-zlib=/the/zlib/path`](https://sourceforge.net/p/libpng/bugs/210/#33f1) is not supported (yet?) or broken in `libpng`, so we set flags. 
Reviewers: Please cross-check if this works well with additional flags set by users, so e.g. a user's `-O3` is still propagated.
fixes:
```
[ ... ]
92    checking for memset... yes
93    checking for pow... no
94    checking for pow in -lm... yes
95    checking for clock_gettime... yes
96    checking for zlibVersion in -lz... no
97    checking for z_zlibVersion in -lz... no
>> 98    configure: error: zlib not installed
```
Seen on a minimal ubuntu image (yes, zlib is not installed in *all* environments ^^)

libpng: zlib path

---

lib/spack/spack/build_environment.py

Fixes https://github.com/LLNL/spack/issues/5564
#5132 added a bug in dependency collection: a generator storing link dependencies was iterated over twice. The first iteration exhausted it and so they were not available when retrieved the second time.

Fix environment dependency collection bug

---

var/spack/repos/builtin/packages/openssl/package.py

Fix missing `-lz` on `make` of OpenSSL.
Spotted on a system without a system-wide zlib installation.

OpenSSL: Fix Zlib

---

var/spack/repos/builtin/packages/xerces-c/package.py

The main location only carries the latest release, while all previous (and current) ones are available at the archive location.

xerces-c: Fix url

---

lib/spack/spack/spec.py
lib/spack/spack/test/patch.py

refers #5587
closes #5593
The implementation introduced in #5476 used `dedupe` to set a private member of a `MultiValuedVariant` object. `dedupe` is meant to give a stable deduplication of the items in a sequence, and *returns an object whose value depends on the order of the items in its argument*. 
Now the private member is set implicitly using the associated property setter. The logic changes from stable deduplication to a totally ordered deduplication (i.e. instead of `dedupe(t)` it uses `sorted(set(t))`). 
This should also grant that packages that shuffle the same set of patch directives maintain the same hash. I didn't try that out, but looking at the implementation I expect:
```python
class A(Package):
patch('foo.patch')
patch('bar.patch')
patch('baz.patch')
```
to have a different …

Patches: the underlying MV variant now uses the property setter

---

var/spack/repos/builtin.mock/packages/extendee/package.py
var/spack/repos/builtin.mock/packages/extension1/package.py
var/spack/repos/builtin.mock/packages/extension2/package.py

Tests fail locally because the install prefix doesn't exist. Make them
exist.

extensions: create install prefixes

---

lib/spack/spack/spec.py

Fix #5602
@tgamblin @becker33
This fixes a loop that was iterating through the keys of a dictionary when it was intending to use the values.

spec.patches: access values rather than keys

---

lib/spack/spack/cmd/module.py
lib/spack/spack/hooks/module_file_generation.py
lib/spack/spack/modules/common.py
lib/spack/spack/spec.py
lib/spack/spack/test/data/modules/tcl/alter_environment.yaml
lib/spack/spack/test/data/modules/tcl/invalid_naming_scheme.yaml
lib/spack/spack/test/data/modules/tcl/invalid_token_in_env_var_name.yaml
lib/spack/spack/test/modules/tcl.py

closes #2884 
closes #4684 
This PR restricts the token that can be expanded in the module file naming scheme and in the name of an environment variable to just `PACKAGE`, `VERSION`, `COMPILER`, `COMPILERNAME`, `COMPILERVER` and  `ARCHITECTURE` (as discussed in #2884). It does so extending `Spec.format` with an optional parameter that contains a list of transformation functions (one for each token, the default being the identity function).
This new mechanism is then exploited to solve #4684. This PR changes the behavior for the expansion of tokens in environment variable names so that it respects the case sensitivity of the literal parts (token expanded in that context are still made uppercase).
With a `modules.yaml` that looks like:
```yaml
modules:
tcl:
naming_scheme: …
```

module files: restricted token expansion + case sensitivity

---

lib/spack/docs/packaging_guide.rst

Identify the flag handlers feature as beta.
I/We have come to believe that the initial implementation of this feature was significantly flawed. The methods will stay, but the exact semantics behind them are likely to change.
To minimize user pain as they change I've added a warning to the documentation saying that they are in beta.

Add beta warning for flag handlers

---

var/spack/repos/builtin/packages/esmf/gcc.patch
var/spack/repos/builtin/packages/esmf/mvapich2.patch
var/spack/repos/builtin/packages/esmf/package.py

- Use libs instead of lapack_libs (see #3364).
- Add a patch to fix building with recent versions of gcc.
- Add a patch to fix building with mvapich2.

esmf: Fix build

---

lib/spack/spack/spec.py
lib/spack/spack/test/install.py
var/spack/repos/builtin.mock/packages/conflicting-dependent/package.py
var/spack/repos/builtin.mock/packages/dependency-install/package.py
var/spack/repos/builtin.mock/packages/dependent-install/package.py

@tgamblin @becker33
Fixes: https://github.com/LLNL/spack/issues/5565
This includes a number of edits to address issues where spack concretization attempts to set properties on already-installed specs. This is a WIP at the moment since I haven't thought all the changes through, but I can replicate #5565 and this appears to resolve it.
* Don't set patches on packages if they have been concretized
* Don't invoke `_concretize_helper` on already-concretized packages (which can add variants for example) - this may not strictly be an issue in #5565 but came up in my debugging. EDIT: this likely shares some logic with https://github.com/LLNL/spack/pull/4939
* Don't add new dependencies to already-concretized specs: this was the trickiest part since the concretization deconstructs the DAG on each …

Don't change properties on already-installed packages

---

var/spack/repos/builtin/packages/fsl/package.py

Adding new package fsl. Got kind of hacky in `setup_environment` to make `self.stage.source_path` have a value if a new stage is created or `spack clean` has been run. I found that `FSLDIR` was being set to `None` when these conditions are true, because `spack_env` is set before the stage is created. What I did forces the stage to be created so that there is a value for `self.stage.source_path`. **Please** let me know if there is a better way of doing this that I am unaware of! 😄 
I can confirm that, with installation using this `package.py` I created, this package's GUI components are all working correctly when connected to an X11-forwarding server.
In `setup_environment`, the `run_env` being set are all from `fsl.sh`. The reason I did not source the file at runtime like I did at …

fsl: new package

---

var/spack/repos/builtin/packages/libx11/package.py
var/spack/repos/builtin/packages/libxau/package.py
var/spack/repos/builtin/packages/libxrender/package.py

The libxcb build was failing like so:
```
[ ... ]
131   checking whether to build developer documentation... yes
132   checking for doxygen... /usr/bin/doxygen
133   checking for dot... /usr/bin/dot
134   checking for CHECK... no
135   checking for XCBPROTO... yes
136   checking for NEEDED... no
>> 137   configure: error: Package requirements (pthread-stubs xau >= 0.99.2) were not met:
138
139   Package 'xproto', required by 'xau', not found
140
141   Consider adjusting the PKG_CONFIG_PATH environment variable if you
142   installed software in a non-standard prefix.
143
```
This adds a link dependency on libxproto that allows the libxcb build to
succeed.

Add link dependency on xproto to xau (recent dependency mechanics changes?)

---

var/spack/repos/builtin/packages/ncl/package.py

Currently, ncl is configured using a transient temp directory. This leads to warnings such as this when executing ncl later on:
```
warning:"/tmp/ncl_ncar_xxxxxx" tmp dir does not exist or is not writable: NCL functionality may be limited -- check TMPDIR environment variable
```
As this also breaks some functionality, use the system temp directory instead (typically `/tmp`).
esmf is required for some ncl scripts (such as `ESMF_regridding.ncl`).

ncl: Fix temp directory and depend on esmf

---

var/spack/repos/builtin/packages/git/package.py
var/spack/repos/builtin/packages/lua-luafilesystem/package.py

I am trying to build `lmod` on Ubuntu 16.04 and Ubuntu 14.04, and it currently fails because of [this](https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined). Setting an external git requires the changes in this PR.

git + luafilesystem: minor fixes

---

var/spack/repos/builtin/packages/vardictjava/package.py

This is a simple package that drops their shell wrapper into prefix.bin and their jar files into prefix.lib (based on the approach used by the picard package).

Add a package for VarDictJava@1.5.1

---

var/spack/repos/builtin/packages/nghttp2/package.py

Add a package for nghttp2, which is useful for the soon-to-be-submitted update adding HTTP/2 support to the curl package.
@peetsv gets any credit and most of the blame for this work, I'm just passing it over the wall.

Nghttp2 new package

---

lib/spack/spack/spec.py
lib/spack/spack/test/database.py

Fixes https://github.com/LLNL/spack/issues/5633
@becker33 @tgamblin
spec and spec.package.spec can refer to different objects in the database. When these two instances of spec differ in terms of the value of the 'concrete' property, Spec._mark_concrete can fail when checking Spec.package.installed (which requires package.spec to be concrete). This skips the check for spec.package.installed when _mark_concrete is called with 'True' (in other words, when the database is marking all specs as being concrete).
For a concrete example of
> spec and spec.package.spec can refer to different objects in the database.
In #5633 we have a case like X->Y where X is libtiff and Y is libjpeg-turbo which itself has 1 build dependency
* repository.get was first called with the non-concrete copy of …

Don't check package.installed in _mark_concrete if value=True

---

var/spack/repos/builtin/packages/curl/package.py

This add info for a new version of curl and builds it with nghttp2 support.
It requires the nghttp2 libraries from #5627, I've marked it don't merge and will update the label if/when that one lands.
@peetsv gets any credit and most of the blame for this work, I'm just passing it over the wall.

curl: new version and added HTTP/2 support

---

var/spack/repos/builtin/packages/node-js/package.py

I see below error:
```
==> No patches needed for node-js
==> Building node-js [Package]
==> Executing phase: 'install'
'make' '-j16' 'install'
18 errors found in build log:
[ ... ]
9154  /usr/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
9155  /usr/bin/ld: skipping incompatible /usr/lib/librt.so when searching for -lrt
9156  /usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
9157  /usr/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
9158  /usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
9159  ../src/tls_wrap.cc: In member function ‘void node::TLSWrap::InitSSL()’:
>> 9160  ../src/tls_wrap.cc:145:64: error: ‘SSL_set_cert_cb’ was …
```

Fix node-js : requires openssl min 1.0.2

---

var/spack/repos/builtin/packages/libpng/package.py

Add `-I` and `-L` flags for zlib more elegant to `libpng` as suggested by @hartzell (via @junghans). Follow-up to #5581

libpng: zlib flags more elegant

---

lib/spack/spack/__init__.py
lib/spack/spack/build_systems/aspell_dict.py
var/spack/repos/builtin/packages/aspell/package.py
var/spack/repos/builtin/packages/aspell6-de/package.py
var/spack/repos/builtin/packages/aspell6-en/package.py
var/spack/repos/builtin/packages/aspell6-es/package.py

[edit: added question about python 3 and urlparse and then touched it up]
Add a package definition for aspell.
Add a handful of dictionaries to convince myself that the support for a bunch of dictionaries works.
I'd appreciate a bit of feedback on the dictionary handling.  In particular:
1. I feel dirty after modifying the dict array in place.  My functional training voice wants me to map across it and make a richer data structure that gets used in the other bits.  What's the pythonic thing?
2. What to do about dictionaries?  Homebrew seems to have just [grabbed them all].  Do we want to do that?  If not, I've taken care of mine.  Should I leave "yours" up to "you" (for various definitions of "not me")?
If we grab them all, it'd be nice to automate the generation of the md5's.  Someone …

Add package for aspell and ass't dictionaries

---

var/spack/repos/builtin/packages/fastqvalidator/package.py

This fix removes the gcc-7.1.0 conflict. Uses most recent commits from FastQValidator as well as libStatGen, which was fixed for gcc 7.1.0 in https://github.com/statgen/fastQValidator/issues/14

fastqvalidator: package fix

---

var/spack/repos/builtin/packages/plumed/package.py

closes #5506
The application of patches to upstream executables has been reworked according to the suggestions of the main developer in #5506. In particular we are not maintaining a dictionary that maps plumed versions to the versions of patchable executables, and we are using a non-interactive command to patch applications.
All the comments on substituting plumed at run-time do not apply here, since we use RPATH and we want to maintain a 1:1 relationship between the DAG hash and the plumed library used.

plumed: reworked patching applications, added new version

---

var/spack/repos/builtin/packages/strelka/package.py

Relax/correct the constraint on the version of boost used by Strelka to match the docs.

Strelka should depend on boost 1.56.0 *or newer*

---

lib/spack/spack/build_environment.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/cmd/fetch.py
lib/spack/spack/cmd/mirror.py
lib/spack/spack/package.py
lib/spack/spack/spec.py

This is actually 3 fixes.  The main fix in this PR beautifies `spack install` output:
- `do_install()` was originally depth-first recursive, and printed `<pkg> already installed in ...` multiple times for packages as recursive calls encountered them.
- For much cleaner output, use `spec.traverse(order='post')` to install dependencies instead.
- Now info about each install is printed only once.
We can probably make things cleaner still, but this gets rid of the largest current source of noise in `install()` output.
All tasks:
The install fix turns 197 lines of `spack install xsdk` output into 152 lines, by getting rid of stuff like this:
```
$ spack install --fake xsdk
...
==> Successfully installed trilinos
Fetch: .  Build: 4.30s.  Total: 4.30s.
[+] …
```

Better install output

---

var/spack/repos/builtin/packages/bcftools/package.py
var/spack/repos/builtin/packages/htslib/package.py
var/spack/repos/builtin/packages/samtools/package.py

Adding checksums for samtools suite 1.6. (htslib, samtools, bcftools)
bcftools built its own htslib instead of depending on it like samtools does, so I fixed that and some library dependencies too.

samtools: add version 1.6 + some fixes

---

lib/spack/spack/concretize.py
lib/spack/spack/provider_index.py
lib/spack/spack/repository.py
lib/spack/spack/variant.py

This isn't a rework of the concretizer but it speeds things up a LOT.
The main culprits were:
1. Variant code and `provider_index` were calling `spec.package` when they
could use `spec.package_class`
- `spec.package` looks up a package instance by `Spec`, which requires a
(fast-ish but not that fast) DAG compare.
- `spec.package_class` just looks up the package's class by name, and you
should use this when all you need is metadata (most of the time).
- not really clear that the current way packages are looked up is
necessary -- we can consider refactoring that in the future.
2. `Repository.repo_for_pkg` parses a `str` argument into a `Spec` when
called with one, via `@_autospec`, but this is not needed.
- Add some faster code to handle strings directly and avoid parsing
This **speeds up …

Speed up concretization

---

lib/spack/spack/cmd/gpg.py
lib/spack/spack/test/cmd/gpg.py

Currently running `spack gpg list` with no arguments returns nothing. You must supply either the `--trusted` or the `--signing` options. The idea here is to return some initial data to the user when the command is run. The alternative is to return an error, telling the user to select one of the two options.
This fixes #5677

Make --trusted default when running spack gpg list

---

var/spack/repos/builtin/packages/petsc/package.py

Also fix flake8 warning "import os should be before import sys"

petsc: update to latest 3.8 version [and include 3.7.7]

---

var/spack/repos/builtin/packages/kaks-calculator/package.py

Adding new package kaks-calculator. 
> Is there an upstream bug report?
Kind of. The creator evidently knows about this problem, according to the webpage where I found the fix on: https://www.researchgate.net/post/Can_someone_help_me_with_a_problem_about_KaKs_calculator20_used_in_linux_systems
> I contacted the author and he suggested me to 
add the following line at the beginning of file "base.h"
#include <string.h>

kaks-calculator: new package

---

var/spack/repos/builtin/packages/boost/package.py

This option is used for historical compatibility reasons on older code bases.

Add the option for a versioned layout to boost

---

var/spack/repos/builtin/packages/openblas/package.py

we already have `develop` in `openblas`, no need for a second one 😄 
in reference to https://github.com/LLNL/spack/pull/5747

openblas: remove extra develop version

---

lib/spack/docs/workflows.rst

Close #4480: This adds a workflow section on how to use spack on Docker.
It provides an example on the best-practices I collected over the last months and circumvents the common pitfalls I tapped in.
Works with MPI, CUDA, Modules, execution as root, etc.
If you want to give it a swing, I pushed [an image](https://github.com/ax3l/dockerfiles/tree/master/spack/base) (without CUDA but MPI capable) of the latest `dev` to dockerhub. Just run
```bash
docker run -it ax3l/spack
```
and do `spack ...` magic!
Note: For the pushed image above, I already added a bit of convenience (+380MB) such as an editor, openssh server for MPI, installed `tar` via spack, etc. If you want to set up a CI job I would recommend to keep it more minimal, see the example for the docs in this PR.
Setting up a regularly …

Docker Workflow

---

var/spack/repos/builtin/packages/m4/package.py

That way the user can still append things to CFLAGS.
This PR is a result of the discussion at #5728.

Use cflags instead of the args variable

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/relocate.py
lib/spack/spack/test/packaging.py

I found a bug while testing this on linux where the rpath was set relative to the working copy directory instead of the original directory.

This fixes a bug in creating rpaths relative to $ORIGIN on linux.

---

lib/spack/spack/compilers/__init__.py
lib/spack/spack/concretize.py
lib/spack/spack/spec.py

Like #5716, this is still not a rework of the concretizer, but it removes a ton of redundant work from our existing concretization algorithm.
Look at the individual commit messages for details.  But, here are the improvements:
Before:
* `xsdk` (30 nodes): 6s
* `dealii` (44 nodes): 10s
* `r-rminer` (134 nodes): 1m38s
After:
* `xsdk`: 1.7s (3.5x)
* `dealii`: 2.5s (4x)
* `r-rminer`: 5s (19x)
- this one also prevents Spack from running `xcrun` zillions of times on macs
`r-rminer` is kind of the upper bound package so far.  Compared to before #5716, concretizing this package is probably 100x faster.  Sorry for all the wasted time everyone! 😳 
@alalazo @adamjstewart @davydden @scheibelp 
@baberlevi (I know you guys do tons of R stuff)

Even faster concretization

---

var/spack/repos/builtin/packages/sundials/package.py

Change to CMake subclass
Update web addresses
Add 3.0.0-beta-2 version
Add new and missing Sundials configuration options
Add conflicts for some variants
Add xSDK configuration
Update lists of example program Makefiles

Update Sundials package

---

var/spack/repos/builtin/packages/superlu-dist/package.py

The interface to +int64 changed from  -D_LONGINT to XSDK_INDEX_SIZE=64. This change
uses the appropriate interface for for the given version
@xiaoyeli

superlu_dist: update to latest version 5.2.1

---

lib/spack/llnl/util/filesystem.py

Fixes #5727.
According to [Sphinx Autodoc](http://www.sphinx-doc.org/en/stable/ext/autodoc.html):
> For modules, `__all__` will be respected when looking for members

Ensure that FileList makes it into the documentation

---

var/spack/repos/builtin/packages/m4/package.py

This reverts commit 6c3184820aa1052016d92f7ff0419b8085d8ad14.

Revert "Use cflags instead of the args variable (#5756)"

---

var/spack/repos/builtin/packages/boost/package.py

boost: call_once_variadic.patch is already part of 1.56.0

---

var/spack/repos/builtin/packages/boost/package.py

`1.64` had issues with serialization (`make_array` and others) when built with
`+mpi+python`. see https://github.com/LLNL/spack/issues/3963
It appears that those issues are fixed in `1.65.1` so we can remove preferred tag from `1.63`.
At the very least I don't have issues with `1.65.1` reported here https://github.com/LLNL/spack/issues/3963#issuecomment-296554280 .

boost: remove preferred 1.63

---

lib/spack/llnl/util/filesystem.py
var/spack/repos/builtin/packages/armadillo/package.py

Currently the `find` function and hence `find_libraries` as well as `find_system_libraries` raise an `OSError` if the `root` path of their search does not exist. In my opinion it makes more sense to return an empty dictionary instead.
Note, that this probably affects many packages which use `find`, `find_libraries` or variants thereof. I initially encountered the error while installing `armadillo` on an Ubuntu 14.04 machine, where arpack is placed in a `lib` subfolder and not `lib64` as the `armadillo` Spack package expects it.
I fix that issue in the second commit. My point is, that this requires the extra explicit check whether the returned `LibraryList` is not empty. I am not really happy about this boilerplate, so please point me in a proper direction if you have a better idea how to …

armadillo: use libs to provide arpack and superlu libraries

---

var/spack/repos/builtin/packages/paraview/package.py

In replacement of #5744 and related to issue #5735 . This sets `GIT_EXECUTABLE=FALSE` to avoid Paraview using `git describe` to determine its own version number. I have tested that it avoids finding the `git` executable:
```
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
-- Could not use git to determine source version, using version 5.4.1
```

Forcing Paraview to avoid using git describe to determine its own version number

---

lib/spack/spack/cmd/clone.py
lib/spack/spack/fetch_strategy.py
lib/spack/spack/package.py
lib/spack/spack/stage.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/conftest.py
lib/spack/spack/test/environment.py
lib/spack/spack/test/git_fetch.py
lib/spack/spack/test/hg_fetch.py
lib/spack/spack/test/install.py
lib/spack/spack/test/mirror.py
lib/spack/spack/test/packaging.py
lib/spack/spack/test/stage.py
lib/spack/spack/test/svn_fetch.py
lib/spack/spack/test/url_fetch.py
var/spack/repos/builtin.mock/packages/canfail/package.py

This PR does a few things:
- This cleans up some of the nastiness where reordering would cause tests to fail.
- This also makes Spack functions (e.g., `do_stage()`) nicer to work with.
@hartzell: The last bullet above caused empty stages to be erroneously created for already-installed dependencies.  I wonder if that has to do with the problem you saw in #4977.  The stages for dependencies would be re-created by recursive calls to `do_install()`, even when `do_install()` decided nothing to bail b/c the dependency was already installed.  I am curious whether this, and to a lesser extent  #5714, help with #4977.

Clean up use of stages and os.chdir()

---

lib/spack/docs/workflows.rst

- The shell script uses arrays and hence only works on sophisticated shells and not the default `sh`. For clarity the shebang `#!/bin/bash` has been used instead.
- Duplicated word `in` removed.

Minor typos and corrections in `workflows.rst`

---

lib/spack/llnl/util/filesystem.py

I'm tracking down a problem with the perl package that's been generating this error:
```
OSError: OSError: [Errno 2] No such file or directory: '/blah/blah/blah/lib/5.24.1/x86_64-linux/Config.pm~'
```
The real problem is upstream/elsewhere, but it's being masked by an exception raised in filter_file`s finally block.
In my case, `backup` is `False`.
The backup is created around line 127, the `re.sub()` calls fails (working on that), the `except` block fires and moves the backup file back, then the finally block tries to remove the non-existent backup file.
This change just avoids trying to remove the non-existent file.

filter_file, don't remove absent backup file

---

var/spack/repos/builtin/packages/perl/package.py

(edits for typos, prose)
See #5745 for ~come~ some backstory.
Perl installs a couple of config files that need to be munged so that they don't refer to the spack compiler.  These files are installed by perl read-only.  The munging uses `filter_file`, and behind the scenes `filter_file` moves its file to a safe place, and tries to create a working file that is both O_WRONLY and has the perms of the original file.  On one of my systems with an NFSv4 filesystem, the combination of `r--r--r--` and O_WRONLY throws a permissions error.  Building on a local/`xfs` filesystem on the same host works.
This commit adds a simple context manager that temporarily makes the files writable.  
I'm not sure that `make_tmp_writable`:
1. ~is the best name, will people confuse it with `/tmp`?~
2. should really …

Make perl install munging work on NFSv4

---

var/spack/repos/builtin/packages/dealii/package.py

dealii has couple of failing tests with serialization in `1.65.1` https://github.com/dealii/dealii/issues/5262, probably related to this issue in boost https://svn.boost.org/trac10/ticket/13186 . `1.66` is not out yet, but I wanted to make sure that I can specify two version ranges.
p.s. Let me know If I shall put back `preferred` to `1.63` and revert https://github.com/LLNL/spack/pull/5770

dealii: blacklist boost 1.64 and 1.65

---

var/spack/repos/builtin/packages/bcl2fastq2/package.py

(edit, refer to PR, not commit...)
#5776 (commit c14f2dc) cleaned up the way the the current working directory is
managed (less magic state).
bcl2fastq is packaged like a russian doll, rather than an archive file
that contains the source, theirs a zip file that contains a tar.gz
file that contains the source.  The package definition has a bit of
extra code that unpacks the inner tarball.
That extra bit of code now needs to explicitly arrange to be in the
correct directory before it does its work.

bcl2fastq needs `with working_dir:` after changes in #5776

---

lib/spack/spack/cmd/blame.py
lib/spack/spack/test/cmd/blame.py

- Previously `spack blame` only worked for package names; now it works for paths as well, so developers can use it on core spack files.

spack blame can take a path to a file in the spack repo

---

lib/spack/docs/getting_started.rst
lib/spack/spack/compilers/clang.py

Closes #2363 
Closes #2496
It seems that the Xcode command-line tools are sufficient to install most packages on macOS, but the full Xcode suite is required to install `qt`. This PR updates the documentation to reflect this.

Update Getting Started docs to clarify that full Xcode suite is required for qt

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/test/packaging.py

Added better matching of partial specs passed to spack buildcache create,list,install.
Skip virtual and external packages that are dependencies when installing buildcaches.
Skip downloading of spec.yaml and gpg2 keys if they exist in the stage directory unless -f is used.

buildcache command updates

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/module.py
lib/spack/spack/test/cmd/module.py

fixes #5721
This is to solve the fact that lmod needs to be configured by the user (to specify a core compiler).

module-type argument defaults to 'tcl' instead of every known type

---

lib/spack/docs/getting_started.rst

This PR removes a tip in the documentation that is in my opinion controversial. As it is just my opinion though, feel free to close this without mercy if the majority thinks differently.

Removed tip suggesting the use of 2 Spack instances

---

var/spack/repos/builtin/packages/jansson/package.py

Jansson builds only a static library by default, which is probably
not what most users want. Add Cmake args to enable shared libraries
for the jansson spack package.

jansson: enable shared library

---

lib/spack/spack/package.py

Flake is taking an issue with bare except statements like
```
try:
...
except:
...
```
raising the error `[E722] do not use bare except`. There are 2 places in `package.py` where this was happening already.

package.py: replace bare except with catch for SpackError

---

var/spack/repos/builtin/packages/hdf5/package.py
var/spack/repos/builtin/packages/netcdf/package.py

An update for HDF5:
- some refactoring;
- allows for thread safety and high-level interface at the same time ('hl' becomes a variant);
- returns 'unsupported' variant (see #520) to allow unsupported combinations only when it's specified explicitly;
- additional conflict statement for mpi and cxx.
I would also make \~mpi by default because every time we want to install something that needs just NetCDF we have to write: install A+netcdf ^netcdf\~mpi ^hdf5\~mpi to avoid compilation of MPI library. But I don't know which case is more often.
There will be a discussion probably.

Update for 'hdf5'.

---

var/spack/repos/builtin/packages/r-a4/package.py
var/spack/repos/builtin/packages/r-a4base/package.py
var/spack/repos/builtin/packages/r-a4classif/package.py
var/spack/repos/builtin/packages/r-a4core/package.py
var/spack/repos/builtin/packages/r-a4preproc/package.py
var/spack/repos/builtin/packages/r-a4reporting/package.py
var/spack/repos/builtin/packages/r-abaenrichment/package.py
var/spack/repos/builtin/packages/r-absseq/package.py
var/spack/repos/builtin/packages/r-acgh/package.py
var/spack/repos/builtin/packages/r-acme/package.py
var/spack/repos/builtin/packages/r-adsplit/package.py
var/spack/repos/builtin/packages/r-affxparser/package.py
var/spack/repos/builtin/packages/r-affycomp/package.py
var/spack/repos/builtin/packages/r-affycompatible/package.py
var/spack/repos/builtin/packages/r-affycontam/package.py
var/spack/repos/builtin/packages/r-annaffy/package.py
var/spack/repos/builtin/packages/r-annotate/package.py
var/spack/repos/builtin/packages/r-annotationdbi/package.py
var/spack/repos/builtin/packages/r-genefilter/package.py
var/spack/repos/builtin/packages/r-limma/package.py
var/spack/repos/builtin/packages/r-mlinterfaces/package.py
var/spack/repos/builtin/packages/r-multtest/package.py

Update url and add r dependency for bioconductor packages r-a4, r-a4base, r-a4classif, r-a4core, r-a4preproc, r-a4reporting. Through these changes, when bioconductor update their packages, spack can refer to the old version and don't need to update each time.

bioconductor update

---

lib/spack/spack/cmd/flake8.py

#5867 does two calls to `flake8` and the return value wasn't handled correctly.  This fixes that.

Fix bug in spack flake8 when no files differ from develop

---

lib/spack/llnl/util/filesystem.py
lib/spack/spack/cmd/install.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/util/filesystem.py

`spack install` can now reinstall a spec even if it has dependents, via the `--overwrite` option. This option moves the current installation in a temporary directory. If the reinstallation is successful the temporary is removed, otherwise a rollback is performed.
This PR permits to reinstall a 'faulty' production installation even if dependents are already in place.  A common use case is `python`. Its package doesn't fail if some builtin modules cannot be built, and if the build of an entire environment is automated you may discover the missing modules after a fair amount of python packages have already been installed.
An example of use:
```console
$ spack install zlib
==> zlib is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14.04-x86_64/gcc-4.8/zlib-1.2.11 …
```

'spack install' can overwrite an existing installation

---

var/spack/repos/builtin/packages/hypre/package.py

This allows to build `hypre` both with and without MPI.

hypre: allow to build without mpi

---

var/spack/repos/builtin/packages/oce/package.py
var/spack/repos/builtin/packages/oce/xlocale.patch

Patch to handle missing xlocale.h, based on https://github.com/tpaviot/oce/issues/675
fixes https://github.com/LLNL/spack/issues/5713

oce: fix Glibc 2.26 does not provide xlocale.h

---

var/spack/repos/builtin/packages/r-openssl/package.py

Changed homepage url to the CRAN package homepage, added list_url and added version 0.9.7 for package r-openssl.

r-openssl: added version 0.9.7

---

var/spack/repos/builtin/packages/perl-b-hooks-endofscope/package.py
var/spack/repos/builtin/packages/perl-class-load-xs/package.py
var/spack/repos/builtin/packages/perl-class-load/package.py
var/spack/repos/builtin/packages/perl-cpan-meta-check/package.py
var/spack/repos/builtin/packages/perl-data-optlist/package.py
var/spack/repos/builtin/packages/perl-devel-globaldestruction/package.py
var/spack/repos/builtin/packages/perl-devel-overloadinfo/package.py
var/spack/repos/builtin/packages/perl-devel-stacktrace/package.py
var/spack/repos/builtin/packages/perl-dist-checkconflicts/package.py
var/spack/repos/builtin/packages/perl-eval-closure/package.py
var/spack/repos/builtin/packages/perl-file-pushd/package.py
var/spack/repos/builtin/packages/perl-module-runtime-conflicts/package.py
var/spack/repos/builtin/packages/perl-moose/package.py
var/spack/repos/builtin/packages/perl-mro-compat/package.py
var/spack/repos/builtin/packages/perl-namespace-clean/package.py
var/spack/repos/builtin/packages/perl-package-deprecationmanager/package.py
var/spack/repos/builtin/packages/perl-package-stash-xs/package.py
var/spack/repos/builtin/packages/perl-package-stash/package.py
var/spack/repos/builtin/packages/perl-params-util/package.py
var/spack/repos/builtin/packages/perl-sub-exporter-progressive/package.py
var/spack/repos/builtin/packages/perl-sub-exporter/package.py
var/spack/repos/builtin/packages/perl-sub-identify/package.py
var/spack/repos/builtin/packages/perl-sub-install/package.py
var/spack/repos/builtin/packages/perl-sub-name/package.py
var/spack/repos/builtin/packages/perl-test-cleannamespaces/package.py
var/spack/repos/builtin/packages/perl-test-fatal/package.py
var/spack/repos/builtin/packages/perl-test-needs/package.py
var/spack/repos/builtin/packages/perl-test-requires/package.py
var/spack/repos/builtin/packages/perl-test-warnings/package.py

Adding perl-moose as well as its tree of dependencies. One dependency, perl-test-deep, is part of https://github.com/LLNL/spack/pull/5845 and will need to be merged in order for this to work.

adding perl-moose and dependencies

---

var/spack/repos/builtin/packages/bedtools2/package.py

[edit, give credit/blame to @peetsv]
I'm just throwing this over the wall.
Credit/blame goes to @peetsv.
---
Our users need an older version of bedtools.

Add info for bedtools2@2.23.0

---

var/spack/repos/builtin/packages/bcftools/package.py
var/spack/repos/builtin/packages/htslib/package.py

I'm forwarding this for an internal user.
@peetsv gets the credit and the blame....
---
Our users need an old version of bcftools.
I requires the matching version of htslib.  That particular version of htslib requires the autotools machinery too.

Add old version to bcftools

---

var/spack/repos/builtin/packages/scalpel/package.py

Scalpel's a bit of a mess, it expects it's users to just unpack the
tarball, build it in the resulting directory and install that
directory onto their PATH.  My install step recapitulates this into
prefix.bin.  The alternative was rewiring their scripts (perl), which
use `FindBin` and expect things to be located in the same dir that the
script itself is.
Sigh.
Lightly tested on CentOS 7.

Add package for scalpel@0.5.3

---

var/spack/repos/builtin/packages/zlib/package.py

Chasing a performance regression has lead me to this change, going from default optimization gives a significant performance win. The sweet spot for zlib is apparently `-O2`, both `-Ofast` and `-O3` are slightly worse (regression is about 3% compared with `-O2`) in my testing. 
Happy to share my methodology with people so we can benchmark on a wider variety of systems.

Zlib gets a 50-60% performance win when compiled with -O2

---

var/spack/repos/builtin/packages/delly2/package.py

adding new package delly2. Makefile makes submodules of delly, which are old versions of packages we have current spack recipes for. For example, the boost submodule version is 1.57, which fails to build. Using newest version with spack works fine, and delly executes correctly.

delly2: new package

---

lib/spack/spack/cmd/flake8.py

I've found this handy.  It might be useful in the outside world also...
---
Internally we work against a branch named 'llnl/develop', which mirrors the public repository's `develop` branch.
It's useful to be able to run flake8 on our changes, using `llnl/develop` as the base branch instead of `develop`.
Internally the flake8 subcommand generates the list of changes files using a hardcoded range of `develop...`.
This makes the base of that range a command line option, with a default of `develop`.
That lets us do this:
```
spack flake8 --base llnl/develop
```
which uses a range of `llnl/develop...`.

Specify base branch for flake8 comparison

---

var/spack/repos/builtin/packages/netcdf/package.py

This is an update for NetCDF.
There are several questions that need to be answered before this gets merged:
1. There was a workaround introduced by @adamjstewart in #1553. Do we still need it? I tried to run the commands from the discussion and they seem to work.
2. What do we do with options 'parallel4' and 'pnetcdf'? Should it be just one option 'mpi' that enables both parallel I/O features? If not, what should be the default values for these variants? Both set to True? See also #2377.
3. Should the package depend on 'mpi'? From one hand, we should run the MPI wrapper. From another hand, netcdf itself does not need mpi and `self.spec['mpi'].mpicc` is set for hdf5/pnetcdf anyway and we can use it.

Update for 'netcdf'.

---

var/spack/repos/builtin/packages/opencv/package.py

this corrects the opencv 3.3.0 hash, this was failing for me up until I changed it.

tweak opencv version

---

lib/spack/spack/repository.py
lib/spack/spack/test/repo.py

Fixes #5754
Previously when RepoPath.repo_for_pkg was invoked with a string,
it did not check if the string included a namespace. Any
namespace-qualified package provided as a string would not be found
(at which point the behavior was to return the highest-precedence
repository).

Check for namespace-qualified packages in repo_for_pkg

---

lib/spack/spack/package.py

Now one can quickly visually see in the terminal which packages are installed
and where each package begins and ends in the log.
Here is how it looks like now:
The line
```
==> Installing openmpi
```
now becomes redundant, but I left it there, since the colorized output is produced by a different mechanism than the `tty.message` output, and I don't know if you want to perhaps keep the `tty` output.
I can also change the colors etc. But it's now much more usable to see what package is being built.

Colorize "Installing pkg_name"

---

var/spack/repos/builtin/packages/paraview/package.py

Fixing the second half of issue #5735 which involves some customizations to the module file for Paraview where a nonstandard directory structure is added to the library paths.

Customization of the Paraview module file to its nonstandard directory structure

---

lib/spack/docs/binary_caches.rst
lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/test/packaging.py

Add symlinks=True to install_tree when making working copy of install directory to avoid triplicate copies of lib*.so.
Move creation of install prefix until after gpg verification so an empty install prefix dir is not created. 
Buildcache create/install do not work with /hash any longer. Change command hints to reflect that change.

Buildcache command fixes 2

---

var/spack/repos/builtin/packages/exodusii/cmake-exodus.patch
var/spack/repos/builtin/packages/exodusii/package.py

The problem is that spack passes -G "Unix Makefiles" into cmake, which normally
works. But in the Exodus package, it is being passed into a bash wrapper
script. In there, the $@ then loses the information about "Unix Makefiles"
being just one argument, and in effect passes -G Unix Makefiles into the cmake
(without quotes), and so cmake only sees -G Unix, and then fails. This is a
known problem with bash with no simple solutions. As a workaround, this patch
skips the first two arguments, i.e., -G and "Unix Makefiles". This makes it
work.
Fixes #5895.

Exodus: skip the -G "Unix Makefiles" part

---

lib/spack/spack/package.py

The satisfies query was backwards. The input spec need to satisfy the
extends spec for this to be true.

package: fix extension query predicate

---

var/spack/repos/builtin/packages/go/package.py

The go team released 1.9.2 which includes fixes for some things that 1.9.1 broke:
> ... include fixes to the compiler, linker, runtime, documentation, go command, and the crypto/x509, database/sql, log, and net/smtp packages. They include a fix to a bug introduced in Go 1.9.1 and Go 1.8.4 that broke "go get" of non-Git repositories under certain conditions.

Add info for go@1.9.2

---

var/spack/repos/builtin/packages/gnuplot/package.py

`5.2.0` lightly tested on macOS High Sierra

gnuplot: add 5.2.0 and 5.0.7

---

var/spack/repos/builtin/packages/libaec/package.py

I had to change the 1.0.0 and 1.0.1 checksum as we are now using the git snapshot instead of the auto-tools generated tarball, which has a custom url for each release. As we are using cmake that doesn't really change anything.

libaec: add v1.0.2 and generic url

---

var/spack/repos/builtin/packages/likwid/package.py

Looks like likwid's checksum for 4.3.0 was updated recently (see https://github.com/RRZE-HPC/likwid/releases).

likwid: Update checksum

---

var/spack/repos/builtin/packages/bowtie2/bowtie2-2.3.0.patch
var/spack/repos/builtin/packages/bowtie2/package.py

Add support for bowtie2@2.3.0
- digest
- a patch for 2.3.0 that parallels the existing package.  Truth be told it builds (for me) without this, but I'm assuming that they're there for a reason...).
- tune up dependencies
- need tbb
- don't need readline or zlib
Several things were installed with sbang's that use `/usr/bin/env` to fine perl or python.  Fix the dependency and clean up the sbang lines.

Add bowtie2@2.3.0, fix dependencies and sbangs

---

var/spack/repos/builtin/packages/json-cwx/package.py

Fixed the json-cwx package added in #6018 (tested locally)
- Checksum copied from json-c was incorrect and has been replaced
- Json-cwx built with autotools but has configure script, so added required autotools dependencies.
- Added autogen.sh executable to autoreconf phase.

Updated json-cwx/package.py to build correctly

---

var/spack/repos/builtin/packages/r-ggplot2/package.py

Dependency r-scales version changed to be greater or equal to 0.4.1 according to CRAN web page of ggplot2.

r-ggplot2: dependency r-scales version changed to be greater or equal to 0.4.1

---

var/spack/repos/builtin/packages/trilinos/package.py

Netcdf was recently updated here. If I did `spack spec nalu`, I would get an unsatisfiable error in concretization. Trilinos was not adding the netcdf dependency correctly when using `trilinos+pnetcdf` after the 12.12.1 version showed up. This consolidates the netcdf dependency lines into one and now the netcdf dependency is correctly put into the spec when using `+pnetcdf` and the current default version 12.12.1 of trilinos.

Merging netcdf dependency lines in trilinos into one line for better coverage

---

var/spack/repos/builtin/packages/htslib/package.py

A recent update (#5907) to htslib added a different URL for an old version of htslib.
Now the package is using that URL as the pattern for the newer versions too.
I have a vague memory of running into this before, that it's a known issue.
This fixes it by adding an explicit `url_for_version` routine.

Fix tarball URL's for htslib

---

var/spack/repos/builtin/packages/adios2/package.py

Fetching the source package was failing the checksum test, this should fix that.

Fix incorrect checksum value for adios2 tarball

---

var/spack/repos/builtin/packages/raja/package.py

As per subject; it's a trivial change.

Fix spack build for RAJA: master requires submodules

---

var/spack/repos/builtin/packages/macsio/package.py

- The cmake args for each plugin are now in the form of `ENABLE_SILO_PLUGIN` rather than just `ENABLE_SILO`
- Added an argument to specify the CXX compiler to use as the mpi compiler to eliminate some build errors coming from OpenMPI when not using the mpicxx wrapper explicitly

Changed plugin CMake args

---

var/spack/repos/builtin/packages/docbook-xml/package.py
var/spack/repos/builtin/packages/docbook-xsl/package.py
var/spack/repos/builtin/packages/flux/package.py

Update the version of flux-core in spack to flux-core v0.8.0, along with required dependency fixes and general spec updates.
In order to get a2x working to build the docs, the docbook-xml and docbook-xsl packages had to be updated to remove the set of XML_CATALOG_FILES in the dependent environment. I'm not exactly sure why, but this caused this environment variable to not be set at all, or set incorrectly, and thus causing errors in xmllint during manpage builds.

flux: update flux-core to v0.8.0

---

var/spack/repos/builtin/packages/lua/liblua-shared.patch
var/spack/repos/builtin/packages/lua/package.py

Patch is taken from Arch Linux.

lua: Build a shared library

---

lib/spack/spack/spec.py
lib/spack/spack/variant.py

Fixes https://github.com/LLNL/spack/issues/5913
When a user-provided spec refers to an already-installed package, packages with patches applied were causing validation errors based on the recorded variants in the package's class. This specifically avoids validation related to the `patches` variant managed by the concretizer.

Fix user specs which include already-installed packages

---

lib/spack/env/cc
lib/spack/spack/build_environment.py
lib/spack/spack/test/cc.py

The name of the debug log written by the cc compiler wrapper is given by `Spec.short_spec`, which includes the architecture. Somewhere along the line `Spec.format` started adding spaces around the architecture property so the filename started including spaces; the cc wrapper script appears to ignore this, so files like `spack-cc-bzip2-....in.log` (which record the wrapped compiler invocations) were not being generated. This updates the value of `SPACK_SHORT_SPEC` to a value without spaces (just includes the name and hash).

update filename used for cc wrapper invocation debug log

---

var/spack/repos/builtin/packages/xqilla/package.py

This fixes a small typo that causes the configure stage to fail.

xqilla: Use append instead of extend

---

var/spack/repos/builtin/packages/the-silver-searcher/package.py

otherwise failed to build on almost fresh Ubuntu 16.04 with gcc 5.4.0

the-silver-searcher: add missing dependency

---

var/spack/repos/builtin/packages/sundials/package.py

```
$ spack spec sundials +hypre ^hypre@2.12.1
Input spec
sundials+hypre
^hypre@2.12.1
Normalized
==> Error: sundials does not depend on hypre
```
Works as expected.
This bug was reported by Julian Andrej over Slack. The problem is that previously, `sundials+hypre` didn't depend on `hypre`, `sundials+hypre+int64` and `sundials+hypre~int64` depended on `hypre`. Spack's concretizer isn't currently smart enough to realize that this represents the entire space of possibilities, and tries to decide whether or not the package actually depends on `hypre` before it makes a final decision as to the value of `+int64`. By specifying that `sundials+hypre` _always_ depends on `hypre`, we can get around this problem.

sundials+hypre depends on hypre

---

lib/spack/spack/compiler.py
lib/spack/spack/compilers/clang.py
lib/spack/spack/environment.py

Fixes #6051.
This makes Spack builds on OS X faithful to `compilers.yaml` unless they have to be different (e.g. for XCode builds).  Now *only* packages that set `use_xcode=True` will use the XCode compiler wrappers for clang.
@balay: can you see if this fixes your issue?
@mathstuf @davydden 
Ping @alalazo b/c this adds a `force=True` option to `EnvironmentModifications`, in cases where you know you're overwriting an already-set value.

Only use XCode clang wrappers for packages that set use_xcode=True

---

var/spack/repos/builtin/packages/adios/package.py

- hdf5's +hl variant is required because the build uses libhdf5_hl.
- sz is only compatible up to version 1.4.10 because the library has been renamed to libSZ in 1.4.11.

adios: Fix hdf5 and sz dependencies

---

var/spack/repos/builtin/packages/bdftopcf/package.py

These are technically "link" depends of libxfont, but they have no
actual libraries.
Fixes #5936.
---
This is the easy fix. The proper fix may be to make these `link` depends of `libxfont` and deal with the extra prefixes required.
Cc: @luigi-calori

bdftopcf: require xproto and fontsproto at build time

---

lib/spack/spack/compilers/gcc.py

Fixes #5778.
---
Cc: @rezaltm @balay

gcc: use -dumpfullversion for version 7

---

lib/spack/spack/test/conftest.py

If `user.useConfigOnly` is set globally and no name or e-mail is configured, the git_fetch tests fail.

Configure user for mock Git repository

---

var/spack/repos/builtin/packages/isaac-server/package.py
var/spack/repos/builtin/packages/isaac/package.py

Add a new release of ISAAC.
Other changes:
- jpeg patch only needed before release 1.3.2
- adjust boost dependency as soon as CUDA9 support is needed

ISAAC 1.3.2

---

lib/spack/spack/cmd/fetch.py

Fixes #6123.
`spack fetch` shouldn't attempt to fetch external deps when invoked with `--dependencies`.

spack fetch --dependencies should not fetch externals.

---

lib/spack/spack/stage.py

When a failed patch was detected, the resource stage was asked to re-expand by calling `fetcher.reset()`.
This however caused the root package to be extracted again, removing the nested copies/symbolic links of the resources.  As ResourceStage did not handle `restage` explicitly, it would only unpack the resources to their respective stage folder and not also put them in the root stage.
For example when attempting to apply patches to `llvm/tools/clang` (which is in the cfe resource):
```
==> Already staged llvm-5.0.0-4wbencqbmejbxkcpmeztwvkf6koy7jlm in .../stage/llvm-5.0.0-4wbencqbmejbxkcpmeztwvkf6koy7jlm
...
==> Already staged resource-cfe-4wbencqbmejbxkcpmeztwvkf6koy7jlm in .../stage/resource-cfe-4wbencqbmejbxkcpmeztwvkf6koy7jlm
==> Moving resource stage
source : …
```

Fix staging of resources for failed patches

---

var/spack/repos/builtin/packages/trilinos/package.py

Adding another variant `ROL` (that can be enabled using Trilinos' cmake variable `Trilinos_ENABLE_ROL`).

add rol variant

---

var/spack/repos/builtin/packages/petsc/package.py

has a fix for build error with MKL

petsc: update to version 3.8.1

---

var/spack/repos/builtin/packages/graphviz/package.py

Dear maintainers,
A small patch to support GTS in Graphviz.
Thank you very much for your great work!
Cheers,
Jean-Baptiste.
----------------
Enable support for the GNU Triangulated Surface Library
- New variant +gts for graphviz
- Optionnal dependency for GTS (already packaged)

Graphviz : Add a GTS variant

---

lib/spack/spack/cmd/common/__init__.py
lib/spack/spack/cmd/load.py
lib/spack/spack/cmd/unload.py
lib/spack/spack/cmd/unuse.py
lib/spack/spack/cmd/use.py

@alalazo would you prefer this was done in a different manner?
Fixes #6126
#3183 removed the print_help function from the "modules" module.
This adds it back so that if a user invokes 'spack load foo' without
having sourced an environment setup script, they will be prompted
to do so.

Add back help placeholder for "spack load"

---

var/spack/repos/builtin/packages/libxtst/package.py
var/spack/repos/builtin/packages/xdpyinfo/package.py
var/spack/repos/builtin/packages/xfs/package.py
var/spack/repos/builtin/packages/xinput/package.py

On some X11 packages there are similar configure step errors that can be fixed by adding "*proto" dependencies.
This is fixes #6157 and is similar to  already merged #6112 which closed #5936

some missing X11  "*proto" dependencies

---

var/spack/repos/builtin/packages/trilinos/package.py

Without this change - I get the following error [triggered by 161dca6d5 c9810f808 changes]
$ ./bin/spack install trilinos+hdf5
hdf5@1.10.1%gcc@7~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-fedora27-x86_64
while trying to concretize the partial spec:
netcdf+mpi
^m4
^mpich@3.3a2%gcc@7 device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=linux-fedora27-x86_64
^zlib@1.2.11%gcc@7+optimize+pic+shared arch=linux-fedora27-x86_64
netcdf requires hdf5 variant +hl, but spec asked for ~hl

trilinos: update hdf5 dependency to use 'hdf5+hl'

---

lib/spack/docs/workflows.rst

New versions of OpenMPI need `--allow-run-as-root` for running as root:
http://www.open-mpi.de/doc/v2.0/man1/mpirun.1.php#toc22
This is important in Docker containers, which usually run as root.

Docker Docs: MPI as Root

---

var/spack/repos/builtin/packages/ncbi-rmblastn/package.py
var/spack/repos/builtin/packages/repeatmasker/package.py
var/spack/repos/builtin/packages/trf/package.py

Adding repeatmasker along with dependency trf, and ncbi-rmblastn search engine, which is what repeatmasker is being configured to use. Other search engine configure options can be added eventually, but I am just adding the one that our group will be using.

repeatmasker: new package

---

lib/spack/spack/cmd/view.py
lib/spack/spack/test/cmd/view.py

This fixes a "typo" in `spack view hardlink` as introduced in #3227 / #5415. (`os.hardlink` does not exist)

Fix spack view hardlink

---

var/spack/repos/builtin/packages/nghttp2/package.py

nghttp2 depends on python, and requires the install directory to exist,
and contain the python module directory which it will eventually
install the python modules into.
These issues were discovered while attempting to implement `lmod` support for `setup-env.sh`

Fix for nghttp2 installation

---

var/spack/repos/builtin/packages/lammps/package.py

Currently there is no way to enable default packages.
1. Could we enable default packages in lammps by default? Building these packages doesn't really take long.
2. Could we enable python embedding/interface whenever `BUILD_SHARED_LIBS` is `ON`? The use case of lammps' shared library typically involves using it with python interface.
`DEFAULT_PACKAGES` include:
```
ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE
GRANULAR KSPACE MANYBODY MC MEAM MISC MOLECULE PERI QEQ REAX REPLICA
RIGID SHOCK SNAP SRD
```
cmake variable `ENABLE_ALL` enables all default packages.
(manybody is part of `DEFAULT_PACKAGES`)
@junghans

lammps: enable default packages

---

CONTRIBUTING.md

Supersedes #2478.  This just points to the guide everyone uses.

Add basic CONTRIBUTING.md that points to contribution guide docs

---

var/spack/repos/builtin/packages/libxsmm/package.py

This allows dependents to use `spec['libxsmm'].libs`.

libxsmm: add libs property

---

var/spack/repos/builtin/packages/perl/package.py

remove (Tcl) modules prepend-path empty lines generated in perl dependent packages,
see #5900
On my cluster we use Tcl modules, we have not git installed on all nodes, 
when installing with spack:
module install git
then activating with
module load git
the command fails for empty prepend-path lines added by perl package

fix perl dependent modules, #5900

---

var/spack/repos/builtin/packages/root/package.py

ROOT needs to have a consistent version of binutils, as it is sensitive to the version of libopcodes. You can't move the code from one system (with the same OS) as another.

ROOT needs to have a consistent version of binutils

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/relocate.py
lib/spack/spack/test/packaging.py

Testing showed that buildcache install wants to download build dependencies as well and link and run dependencies. Changed buildcache install  to only install tarballs for link and run dependencies.
Testing of relative rpath tarballs installation showed the relative rpaths were being replaced with absolute rpaths. Reworked the relative rpath tarball creation and installation to add and check for relativerpath flag in buildcache info file. 
Reworked the macho object modification to be more like the elf object modification.
Changed some warnings to failures when pgp2 is not avaiable or a key isn't available. The create command would complete making one think that the .spack files were created when only the .tar.gz files were created.
Fixed bug where files (and links) with with text in …

spack buildcache create and install updates for relative rpath tarballs and macOS tarballs.

---

var/spack/repos/builtin/packages/magma/package.py

- add gcc dependency per cuda versions
- Fix for cuda-9.0  as it does not support sm20
nvcc fatal   : Unsupported gpu architecture 'compute_20'
@luszczek @keitat @tgamblin

magma: cuda updates [from xsdk-0.3.0 branch]

---

CODE_OF_CONDUCT.md

Spack is already a fairly large community, and it's important to make sure we're clear about standards and how we'll address any problems that arise.
We're adopting the contributor covenant for now (which is GitHub's default).  It's thankfully not something we've needed to use yet, but this is good to have in case we actually do have a problem one day.

Add a code of conduct to Spack

---

var/spack/repos/builtin/packages/elfutils/package.py

Resolves an arcane error I found in elfutils on recent ubuntu systems.

elfutils: add --no-as-needed flag for library ordering issue

---

lib/spack/spack/compiler.py
lib/spack/spack/concretize.py
lib/spack/spack/spec.py
lib/spack/spack/test/compilers.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/data/compilers.yaml

@becker33
Fixes #6154
For compiler options which set values using the syntax "-flag value"
(with a space between the flag and the flag's value) the flag and
value were treated as separate and reordered. This updates Spack's
logic to treat the flag and value as a single unit, even if there is
a space. It assumes that only flags are prefixed with "-".

Group flags and values separated by space

---

var/spack/repos/builtin/packages/swig/package.py

FindSWIG.cmake provided with cmake tries to find the swig binary under the following names and in the following order: `swig3.0`, `swig2.0`, `swig`. Swig installs only a binary called `swig`, which can get overriden by an external version. The symlink prevents that from happening.

Create symlink for 'swig' binary after installation.

---

var/spack/repos/builtin/packages/nekbone/package.py

The examples installed require the `data.rea` and `SIZE` files to run.  The individual `README` files are just short explanations of the test. ex: `example1/README`
```
This example will run a
series of tests from:
1 to 50 elements per process
with polynomial order = 8
and
1 to 50 elements per process
with polynomial order = 10
The multi-grid preconditioner
is turn off.
```

Nekbone: Installing data files for example runs

---

var/spack/repos/builtin/packages/petsc/package.py

Includes pkgconfig fix [for mfem static build failure]
Fix #6222

petsc: update to version 3.8.2

---

lib/spack/spack/package.py

Specs are stored in the build cache without build-only deps. This makes install remove the build-only deps before comparing to the specs in the cache.

Don't include build-only dependencies in build cache hash

---

lib/spack/docs/tutorial.rst
lib/spack/docs/tutorial_advanced_packaging.rst

As in #5657 :bowing_man: to anybody reviewing this.
You can view the documentation locally by fetching this PR and:
```console
$ cd lib/spack/docs
$ make
$ <your-favorite-browser> _build/html/index.html
```

SC17: advanced packaging tutorial

---

lib/spack/spack/variant.py

- Previously variant values had to be a tuple or a callable predicate.
- This allows 'any' as shorthand for `lambda x: True` and type objects
as shorthand for "any value of this type", e.g.:
```python
variant('some_value', values=any, description='anything at all')
variant('a_number', values=int, description='any integer')
```
- Makes variant definitions more readable, keeps lambdas out of
packages for common cases.
@alalazo: do you think you'll have time to do multi-value variant documentation?

Allow types and 'any' in variant definitions.

---

var/spack/repos/builtin/packages/relion/package.py

Hi
Most users reply upon GPUs to accelerate Relion so the default variant for Cuda should be True.
Also Double Precision should be the default for CPU per [this feedback from developers](https://github.com/3dem/relion/issues/309#issuecomment-342788027).

relion 2.1 - changed default variants

---

var/spack/repos/builtin/packages/icu4c/package.py

Previous versions try to include xlocale.h, which fails on glibc >= 2.26.

icu4c: Update to 60.1

---

var/spack/repos/builtin/packages/ncl/package.py

ncl's build system will happily continue in case of errors, which might result in the ncl binary not being built.

ncl: Check for ncl binary after installation

---

var/spack/repos/builtin/packages/py-h5py/package.py

py-h5py seems to be failing to build due to this error:
fatal error: hdf5_hl.h: No such file or directory
Ensuring that it depends on the hl variant of hdf5 fixes this.

py-h5py: make sure to depend on the hl variant of hdf5

---

var/spack/repos/builtin/packages/likwid/package.py

Looks like likwid's hash has changed again. Let's hope this is actually the final release.

likwid: Fix hash for 4.3.0

---

lib/spack/spack/directives.py

Fixes #6299
Error messages in 'directives' were split across multiple lines and not
properly concatenated, which led to truncated messages.

Fix truncated error messages in directives

---

var/spack/repos/builtin/packages/xsimd/package.py
var/spack/repos/builtin/packages/xtensor/package.py
var/spack/repos/builtin/packages/xtl/package.py

Adds the QuantStack libs (C++, header-only) needed for [xtensor](https://github.com/QuantStack/xtensor).

xtensor, xtl, xsimd

---

share/spack/setup-env.sh

This should reduce the delay the users experience when sourcing the setup file to activate shell support. It works by generating at once all the commands that needs to be evaluated (they are stored in a string and later `eval`ed by the shell).
I am not proficient enough with shell scripting to tell if this is portable across shells, so please somebody double check.
@ax3l Does this help with #6302 ?

Reduce the calls to the python interpreter during initialization

---

var/spack/repos/builtin/packages/meraculous/package.py
var/spack/repos/builtin/packages/perl-log-log4perl/package.py

Adding new package meraculous. Patch method fixes error where meraculous would not compile with gcc 4.8.5. Will **not** compile with gcc 6.3.0 or 7.1.0.

meraculous: new package

---

var/spack/repos/builtin/packages/nut/package.py

Install libnut.a and bh-3 (small application that demonstrates the library).  
I had no issues building serial with gcc@4.8.5 or gcc@7.2.0 so I removed the conflict (didn't test the others).  I did have an issue with the openmp version with gcc@7.2.0, but its the same outside of spack.

NuT: Add Installation of libnut.a and demo app

---

var/spack/repos/builtin/packages/hepmc/package.py

* Added new version 3.0.0
* Fixed checksum for version 2.06.09
+ HepMC migrated its website [[1]](http://lcgapp.cern.ch/project/simu/HepMC) to [[2]](http://hepmc.web.cern.ch/hepmc/), so [1] is now deprecated.
+ Current checksum for 2.06.09 corresponds to the tarfile hosted in [1] but the url points to [2], therefore the fetch step fails.
* Added `url_for_version`: since versions older than 2.06.09 are only hosted by [1]

hepmc: fix checksum and urls, add new version 3.0.0

---

var/spack/repos/builtin/packages/siesta/package.py

This package has a custom build system and requires building twice to produce its two binaries, but is otherwise fairly simple. I successfully tested multiple configurations (GCC and Intel, with and without Intel MKL, Open MPI and Intel MPI). Issues in the build system forced me to disable parallel builds and add some minor workarounds for Intel.

siesta: new package

---

var/spack/repos/builtin/packages/pocl/package.py

This PR fixes issue #4669 by properly arranging source and destination of the symlink which is generated and hence makes a pocl 0.14 installation possible again.

Fix to allow installing pocl 0.14 again

---

lib/spack/docs/known_issues.rst

#2895 was fixed by #5415 and #5600 (thanks @mathstuf!). This PR removes `spack extensions` from the list of Known Issues.

Remove spack extensions from list of known issues

---

var/spack/repos/builtin/packages/parallel-netcdf/package.py

I've started to implement Intel MPI and parallel-netcdf would not build without specifying the MPI compilers through these variables at configure.

Using MPI environment compiler variables for pnetcdf.

---

var/spack/repos/builtin/packages/py-yt/package.py

Yt-Project is now on Github instead of Bitbucket. 
- Change url and development url.
- Add v3.4.0

py-yt: Yt-project is moved. Add new version.

---

var/spack/repos/builtin/packages/zoltan/package.py

add parmetis support to zoltan for use of multi-level graph based partitioning procedures

zoltan: add optional dependency on parmetis

---

var/spack/repos/builtin/packages/gcc/package.py

GCC sets CC and CXX flags in it's environment module

---

var/spack/repos/builtin/packages/bohrium/package.py

This PR adds bohrium to spack. Right now it is work in progress and the built package is still not functional, so please do not merge the PR just yet. I have tried a few things to find out what goes wrong during the build, but maybe you folks can give me some pointers for further investigation.
Here are the things I did:
- The package builds fine with all variant combinations, that I tried (With CUDA and OpenCL, with only one of them, with python3.6, with python 2.7, with and without any of BLAS or LAPACK)
- If I try to use the package's python extension like so
```sh
spack module loads --dependencies bohrium > /tmp/modules.bohrium
. /tmp/modules.bohrium
python -c 'import bohrium'
```
I get the issue of an unresolved symbol, which turns out to originate from the `libstdc++` library, …

Add bohrium to spack

---

var/spack/repos/builtin/packages/express/package.py

Adding new package express. Had to get slightly dirty trying to hack around the `$` in `CMakeLists.txt`.
Error present when compiling with gcc 6.3.0 and 7.1.0 as follows:
```
error: no matching function for call to ‘Target::cached_effective_length(const boost::shared_ptr<BiasBoss>&) const’
```
added appropriate versioned `conflicts()` spec in `package.py` to accommodate for this.

express: new package

---

var/spack/repos/builtin/packages/boost/package.py

boost@1.54.0 won't build with gcc@5.4.0 without the same bit of patchery that fixes 1.55.0.
e.g. (from around line 40046 of my build.out)
```
[...]
libs/thread/src/pthread/thread.cpp: In function ‘boost::detail::thread_data_base* boost::detail::get_current_thread_data()’:
libs/thread/src/pthread/thread.cpp:140:88: error: no matching function for call to ‘call_once(boost::once_flag&, void (&)())’
boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
[...]
```
This PR just changes a 5 to a 4 ("You're not paying me to change one character, you paying me to know what character to change.  Wait, you're not paying me at all...").
boost@1.54.0 and boost@1.55.0 both build with gcc@5.4.0 on a CentOS 7 DO droplet.

boost@1.54 also needs the call_once patch

---

var/spack/repos/builtin/packages/siesta/configure.patch
var/spack/repos/builtin/packages/siesta/package.py

This is a follow-up to #6346 to add NetCDF support.
While technically it is an optional dependency, the Siesta documentation recommends its use because it makes a number of additional features available and speeds up others. So I decided not to make this a Spack variant but a hard dependency.
The configure script has trouble when multiple libraries are specified with `--with-netcdf`, so I had to include a patch. This patch also removes an outdated reference to `libnetcdf_f90.a` from the generated configuration, which otherwise causes build errors.

siesta: add netcdf support

---

var/spack/repos/builtin/packages/octave/package.py

Fix #6368 . Octave GUI requries qt+opengl to build.

Octave GUI depends on qt+opengl.

---

var/spack/repos/builtin/packages/gearshifft/package.py

With pocl builds fixed in #6372 and #6440, we can now also use the OpenCL implementations in gearshifft :)
ccing @tdd11235813 @psteinb
```bash
spack install gearshifft
spack load gearshifft
```
and instead of the default `+cufft +clfft +fftw +openmp` you can also specify to install and load the arguments `gearshifft ~cufft ~fftw` etc. instead to disable some features.

gearshifft: enable clFFT

---

var/spack/repos/builtin/packages/bohrium/package.py

A few expansions to the recently added bohrium package:
- Allow to build opencv extension methods
- Fix the config file to a predictable location, add a property for that and export the location to the environment

Expand bohrium package

---

var/spack/repos/builtin/packages/pocl/package.py

Follow-up to #6372: `libtool` is also needed for linking, otherwise downstream dependencies such as `clfft` will fail linking against pocl's libOpenCL.so with errors such as:
```
>> 182   /usr/bin/ld: warning: libltdl.so.7, needed by /usr/local/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/pocl-0.14-rwo73qzkcxfupndxoz3pcl2s34o5pt6i/lib/libOpenCL.so, not found (try using -rpath or -rpath-link)
>> 183   /usr/local/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/pocl-0.14-rwo73qzkcxfupndxoz3pcl2s34o5pt6i/lib/libOpenCL.so: undefined reference to `lt_dlinit'
>> 184   /usr/local/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/pocl-0.14-rwo73qzkcxfupndxoz3pcl2s34o5pt6i/lib/libOpenCL.so: undefined reference to `lt_dlerror'
>> 185   /usr/local/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/pocl-0.14-rwo73qz …
```

pocl: fix link to libtool

---

var/spack/repos/builtin/packages/opencv/package.py

The libraries in opencv are only prefixed with "opencv_" but not called "opencv.*.so", so the default `libs` handler from `spec.py` does not collect the opencv libraries properly.

Implement opencv libs property

---

lib/spack/spack/main.py

This has been bothering me more than I'd like to admit. We use the long flag for `spack help --spec` but the short flag for `spack help -a`. This PR fixes that.

Use long flag in spack help message

---

var/spack/repos/builtin/packages/glog/package.py

glog < 0.3.5 can't be compiled with CMake as it was only introduced in version 0.3.5. This pull requests supports classic Makefile with version < 0.3.5 and CMake for version >= 0.3.5

fix compilation glog's compilation for <= 0.3.4 and added 0.3.5

---

var/spack/repos/builtin/packages/r-hms/package.py

Adding a `list_url` for `r-hms`.
Ran into a 404 error due to the version `0.3` being moved to the cran archive with the release of `hms-0.4.0`

Adding list_url to r-hms package

---

var/spack/repos/builtin/packages/viennarna/package.py

Adding a later version of ViennaRNA package.
I did have to disable the swig bits, due to missing file dependencies.

 ViennaRNA: adding version 2.4.3 + disable swig

---

lib/spack/spack/cmd/spec.py

Showing "Normalized" in the output doesn't give users additional information, as this step is essentially an implementation detail of concretization. This PR skips it and shows just the input spec and the concretized one. Printing partial hashes for input spec has been disabled.
```console
$ spack spec -Il hdf5@1.10.1+mpi ^mpich
Input spec
hcaag73  hdf5@1.10.1+mpi
ty5c2nn      ^mpich
Normalized
4kdzf64  hdf5@1.10.1+mpi
ty5c2nn      ^mpich
j52z7qb      ^zlib@1.1.2:
Concretized
7x2qtxi  hdf5@1.10.1%gcc@4.8~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu14.04-x86_64 
i5jrs3r      ^mpich@3.2%gcc@4.8 device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=linux-ubuntu14.04-x86_64 …
```

spack spec: simplified output

---

lib/spack/spack/repository.py

fixes #6442 
Although the manual construction of the error message is very inelegant

add path to package.py in case of a syntax error

---

var/spack/repos/builtin/packages/py-enum34/package.py

I'm not sure whether this kind of conflict and dependency statements are generally usable yet. In our use case we didn't see anything break. If this is not yet ready feel free to close this PR and we will track this for now in our fork only

add conflicts to py-enum34

---

var/spack/repos/builtin/packages/py-pylint/package.py

remove breaking version and cleanup of dependencies in package py-lint

---

var/spack/repos/builtin/packages/libmongoc/package.py

The pkg-config file for libmongoc broke after the update to 1.8.1 because the library paths for snappy and zlib are missing.
The patch has already been submitted upstream (https://github.com/mongodb/mongo-c-driver/pull/466).

libmongoc: Fix pkg-config file not containing snappy and zlib paths

---

var/spack/repos/builtin/packages/globus-toolkit/package.py

Looks like globus removes old versions from their source tree, so I propose to replace it by the currently last version. I tested it in my spack env and this version downloads and builds without a problem.
Not sure how future-proof this package is (since iirc the support of the globus toolkit will drop soon), but updating the version isn't really much work and it still seems to be in quite a bit of use.

Update globus-toolkit package version and hash

---

lib/spack/spack/directives.py

The original docstring had confusing wording re: what is going to symlinked and where when using the `extend` directive, and how exactly the symlinking is performed (not automatically on install, but using `spack activate`). See #5559.

Improve docstring of spack.directives.extend

---

var/spack/repos/builtin/packages/cgal/package.py

Fixes #6414. See #6414 for explanation of why the checksum kept changing. Hopefully this should be a more stable URL to download from.
Also adds the latest version of CGAL.

Fix CGAL checksum and switch to more stable URL

---

lib/spack/spack/cmd/__init__.py
lib/spack/spack/test/cmd/install.py
lib/spack/spack/test/concretize.py
lib/spack/spack/test/conftest.py

fixes #6430
fixes #6001
With respect to the test case in #6430 :
```console
$ spack install visit
==> Error: Conflicts in concretized spec "visit@2.12.2%gcc@4.8 build_type=RelWithDebInfo arch=linux-ubuntu14.04-x86_64 /os5zygv"
List of matching conflicts for spec:
netcdf@4.4.1.1%gcc@4.8~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-ubuntu14.04-x86_64 
^hdf5@1.10.1%gcc@4.8~cxx~debug~fortran+hl~mpi+pic+shared~szip~threadsafe arch=linux-ubuntu14.04-x86_64 
^zlib@1.2.11%gcc@4.8+optimize+pic+shared arch=linux-ubuntu14.04-x86_64 
^m4@1.4.18%gcc@4.8 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-ubuntu14.04-x86_64 
^libsigsegv@2.11%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
^openmpi@3.0.0%gcc@4.8~cuda fabrics= ~java schedulers= …
```

'spack install' conflict messages are as verbose as 'spack spec'

---

lib/spack/docs/getting_started.rst

gpg creation: added suggestion on how to set-up rngd

---

var/spack/repos/builtin/packages/hwloc/package.py

This adds an option that enables building of static libraries of hwloc. This is done by adding a new variant inside the existing package.

Added variant static for hwloc

---

lib/spack/spack/cmd/checksum.py

Remove reference to deprecated spack md5 command

---

var/spack/repos/builtin/packages/kvasir-mpl/package.py

Adds the [Kvasir MPL](https://github.com/kvasir-io/mpl) as a package

New package Kvasir Metaprogramming Library

---

var/spack/repos/builtin/packages/gcc/package.py

gcc: remove all variant

---

var/spack/repos/builtin/packages/hwloc/package.py

Change of variant name from `static` to `shared`.

Rename variant static to shared

---

var/spack/repos/builtin/packages/libpng/package.py

Recent versions of `libpng` (e.g. 1.6.34) warn/abort that includes for `zlib` need to be passed properly via `CPPFLAGS`. This fixes it.
This was already pointed out in the [original post](https://sourceforge.net/p/libpng/bugs/210/#33f1) also linked in the package.
Follow-up to #5656 and #5581

libpng: CPPFLAGS for -I

---

var/spack/repos/builtin/packages/openjpeg/package.py

In the beginning, I thought this would be just a workaround for #6524 but actually, all version tuples of OpenJPEG officially have the same length: https://github.com/uclouvain/openjpeg/releases.

OpenJPEG: all version tuples have the same length.

---

var/spack/repos/builtin/packages/c-blosc/package.py

Adds a newer release of c-blosc, adds the new flags for external library builds, adds missing dependencies.

c-blosc: 1.12.1

---

var/spack/repos/builtin/packages/adios/package.py

The latest release of ADIOS needs a [newer version of SZ](https://github.com/ornladios/ADIOS/issues/159#issuecomment-348942954) due to an upstream library naming change. Follow-up to #6539

ADIOS 1.13.0: Newer SZ Versions

---

var/spack/repos/builtin/packages/adios/package.py

Add additional transform libraries to ADIOS, [LZ4 and blosc](https://arxiv.org/abs/1706.00522).
Also modifies existing transforms to the versions they were introduced (otherwise this was resulting in unknown configure flags).

ADIOS 1.13.0: LZ4 & blosc support

---

var/spack/repos/builtin/packages/opennurbs/package.py

This adds the OpenNurbs package which is like SuperLU in that there exists a new version that uses CMake, but the older version I personally need uses makefiles, which is used when choosing the `percept` custom version of OpenNurbs. I am adding this package because I will later be adding the Percept application which requires OpenNurbs.

Add opennurbs package

---

var/spack/repos/builtin/packages/gnupg/package.py
var/spack/repos/builtin/packages/libassuan/package.py
var/spack/repos/builtin/packages/libgcrypt/package.py
var/spack/repos/builtin/packages/npth/package.py

I updated gnupg to the most recent version `2.2.3`. 
Updated dependencies:
* libassuan 2.4.5
* libgcrypt 1.8.1
* npth 1.5
I did not find any note if this kind of PR is wanted or not?

Update gnupg to 2.2.3

---

lib/spack/spack/build_systems/cmake.py

`CMAKE_INSTALL_RPATH` is [semicolon-separated](https://cmake.org/cmake/help/v3.10/variable/CMAKE_INSTALL_RPATH.html). Otherwise, it is not interpreted as a list. Colons are not a problem in situations when lists of rpaths are stored to the objects as colon-separated lists. It's not the case of MacOS, though.
BTW, I am not sure that we need to set CMAKE_INSTALL_RPATH at all since rpaths are set by the wrappers anyway.

CMAKE_INSTALL_RPATH is semicolon-separated

---

lib/spack/spack/config.py

According to the documentation here:
http://www.sphinx-doc.org/en/stable/ext/autodoc.html
> For module data members and class attributes, documentation can either be put into a comment with special formatting (using a #: to start the comment instead of just #), or in a docstring after the definition.

config.py: fixed comments that refer to variables following them

---

var/spack/repos/builtin/packages/wx/math_include.patch
var/spack/repos/builtin/packages/wx/package.py

- depends on GTK+ with X enabled   (btw, non-X backends are deprecated/removed in GTK+):
```
Installing gtkplus
[...]
configure: error: Package requirements (cairo-xlib >= 1.6) were not met:
112   
113   Package 'cairo-xlib', required by 'virtual:world', not found
```
- patch for 3.0.1-3.0.2: missing include caused multiple   `error: call of overloaded ‘abs(XYPOSITION)’ is ambiguous`   (seen in GCC 6.3.0); fixed in 3.0.3+
- ~~`extends('python')`: needed for python bindings it builds, was missing and caused issues when building/distr. depending packages on requirement step~~

wxWidgets: fix GTK builds

---

var/spack/repos/builtin/packages/openfast/package.py

I've started implementing intel-mpi and need to give openfast more hints for it to find the MPI implementation.

Update openfast package to explicity pass MPI location during configure

---

var/spack/repos/builtin/packages/hdf5/h5f90global-mult-obj-same-equivalence-same-common-block.patch
var/spack/repos/builtin/packages/hdf5/package.py

This is known issue.  See
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/747951.
Without this patch, hdf5 fails to build with Intel 18 due to the error:
```
PPFC     H5f90global.lo
libtool: compile:
/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.2-intel-18.0.1/bin/mpif90
-I. -I../../src -O3 -I../../src -I../../fortran/src -fPIC -c H5f90global.F90
-fPIC -o .libs/H5f90global.o
/yellow/usr/projects/user_contrib/spack.20170926/lib/spack/env/intel/ifort: line
358:
/yellow/users/kellyt/spack-cc-hdf5@1.10.1%intel@18.0.1+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe
arch=linux-rhel7-x86_64 /v3lut6o.in.log: No such file or directory
/yellow/usr/projects/user_contrib/spack.20170926/lib/spack/env/intel/ifort: line
359: …
```

Provide a patch to allow hdf5@1.10.1 to build with intel/18.0.1.

---

var/spack/repos/builtin/packages/qrupdate/package.py

```
$ otool -L /Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/qrupdate-1.1.2-t55vinef7373d5raoagedhrasf2kfnst/lib/libqrupdate.dylib
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/qrupdate-1.1.2-t55vinef7373d5raoagedhrasf2kfnst/lib/libqrupdate.dylib:
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/qrupdate-1.1.2-t55vinef7373d5raoagedhrasf2kfnst/lib/libqrupdate.1.1.dylib (compatibility version 0.0.0, current version 0.0.0)
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/openblas-0.2.20-a2w7heujstxj3l65sbcbonk4yh6ta55z/lib/libopenblas_sandybridge-r0.2.20.dylib (compatibility version 0.0.0, current version 0.0.0)
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-appl …
```

qrupdate: fix blas/lapack and compilation of macOS

---

var/spack/repos/builtin/packages/dealii/boost_1.65.1_singleton.patch
var/spack/repos/builtin/packages/dealii/package.py

(i) blacklst 1.65.0 due to issues on Ubuntu with gcc 5.4.0
(ii) add a patch for 1.65.1 to fix serialization
(iii) simplify boost's depends_on()
p.s. i was wrong about 1.65.0 https://github.com/dealii/dealii/pull/5572#issuecomment-349295859

dealii: update and fix boost dependency

---

var/spack/repos/builtin/packages/r-rhtslib/package.py

While installing `r-rhtslib` the following error was reported:
```
585   aclocal.m4:17: warning: this file was generated for autoconf 2.69.
586   You have another version of autoconf.  It may work, but is not guaranteed to.
587   If you have problems, you may need to regenerate the build system entirely.
588   To do so, use the procedure documented by the package, typically 'autoreconf'.
>> 589   configure.ac:30: error: Autoconf version 2.67 or higher is required
>> 590   configure.ac:30: the top level
591   autom4te: /usr/bin/m4 failed with exit status: 63
592   WARNING: 'autoconf' is probably too old.
593            You should only need it if you modified 'configure.ac',
594            or m4 files included by it.
595            The 'autoconf' program is part of the GNU Autoconf package: …
```

Added missing dependency

---

var/spack/repos/builtin/packages/openjpeg/macos.patch
var/spack/repos/builtin/packages/openjpeg/package.py

https://github.com/uclouvain/openjpeg/issues/367
https://github.com/uclouvain/openjpeg/commit/b9a247b559e62e55f5561624cf4a19aee3c8afdc
Works for versions `1.5.x` too.

Package 'openjpeg': fix install name id on OSX builds

---

var/spack/repos/builtin/packages/laghos/package.py

We needed to update the v1.0 tag of Laghos and hash has changed (we are not planning to update this tag again).

Updated hash for v1.0 tag of Laghos

---

var/spack/repos/builtin/packages/openssl/package.py

I think a critical piece of software like openSSL should _always_ be kept as up-to-date as possible.

📦 Update openSSL to 1.0.2m/1.1.0g

---

var/spack/repos/builtin/packages/libaio/package.py

While installing a dependant package the following error was reported:
```
==> Installing libaio
curl: (51) SSL: certificate subject name 'debian.inf.tu-dresden.de' does not match target host name 'ftp.de.debian.org'
==> Fetching https://ftp.de.debian.org/debian/pool/main/liba/libaio/libaio_0.3.110.orig.tar.gz
==> Fetching from https://ftp.de.debian.org/debian/pool/main/liba/libaio/libaio_0.3.110.orig.tar.gz failed.
==> Error: FetchError: All fetchers failed for libaio-0.3.110-6cecraupuqdz6cf7wnld2mn6yqwkrc2j
FetchError: FetchError: All fetchers failed for libaio-0.3.110-6cecraupuqdz6cf7wnld2mn6yqwkrc2j
/mnt/grsoftfs3/software/spack/lib/spack/spack/package.py:993, in do_fetch:
25                                     self.spec.format('$_$@'), ck_msg)
26    
27            self.stage.create() …
```

Fix in download url for package libaio

---

var/spack/repos/builtin/packages/py-plotly/package.py
var/spack/repos/builtin/packages/py-pytz/package.py
var/spack/repos/builtin/packages/py-requests/package.py
var/spack/repos/builtin/packages/py-six/package.py

The requirements of py-plotlit are rather strict fixed to specific versions, so I did not add an "upper versions" `:` to the constrains.
See
https://github.com/plotly/plotly.py/blob/master/requirements.txt

Add: Py-Plotly

---

var/spack/repos/builtin/packages/py-astropy/package.py

`py-markupsafe` was missing during `spack install` as a build error.

Fix AstroPy: Missing Markupsafe

---

var/spack/repos/builtin/packages/py-flake8/package.py

Note: This exposes a compatibility issue with `py-ipython` which depends on `py-backports-shutil-get-terminal-size` which depends (as build dependency only) on `py-setuptools:30.99.99`. 
Currently it is not possible to concretize a spec that has conflicting build and run dependencies. All other packages (in all of spack) depend on `py-setuptools@x.y:` so I'm not sure if that adds to much pressure on a concretizer that is able to handle such cases, but for our meta-package it results in a broken `py-flake8` build and after this is merged will result in a failure to concretize.
Is there an estimate on when the new concretizer will be implemented? @scheibelp @tgamblin @adamjstewart

add restriction to py-setuptools dependency on py-flake8

---

lib/spack/docs/getting_started.rst

fixes #2440
The "Getting started" guide should be short and sweet. This commit simplifies the "Environment-Modules" section pruning:
- outdated / wrong suggestions as noted in #2440
- uncommon setups that are better treated in a reference guide

Simplified "Environment-Modules" section in getting started guide.

---

lib/spack/spack/cmd/edit.py

-d, --docs option will edit doc files.
Also improves edit command suffix extrapolation for core files. Previously assumed all files are '*.py', which doesn't work or docs. Now checks filesystem for all files of that name, and will die gracefully if != 1.
You can also now specify a full name including suffix for internal files. 
No change in behavior for package files.

add -d option for edit command

---

var/spack/repos/builtin/packages/openssl/package.py

From 07.12.2017, fixes CVE-2017-3737
This issue does not affect OpenSSL 1.1.0.
OpenSSL 1.0.2 users should upgrade to 1.0.2n.

openssl: Update to 1.0.2n

---

var/spack/repos/builtin/packages/minisign/package.py

A dead simple tool to sign files and verify signatures.
See https://jedisct1.github.io/minisign
Build is confirmed to be working on Debian 9 and latest spack@develop.

Add new package minisign

---

.gitignore

I noticed recently that when I install packages with the `-d` option, I have started getting a bunch of log files in the root directory of the repository:
```console
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
spack-cc-binutils-4an3yhe.in.log
spack-cc-binutils-4an3yhe.out.log
...
```
This PR make sure that git ignores those to avoid cluttering up status output.

Ignore log files that appear in root dir with "spack -d install ..."

---

lib/spack/spack/compiler.py
lib/spack/spack/test/compilers.py

Fixes #6200
For compilers that successfully run a version detection script but don't actually return a version (i.e. an empty string), Spack was keeping track of the empty version and then failing when attempting to construct a compiler spec. This skips any attempt to add a compiler entry when no version is reported (but logs when a compiler fails to report a version).

Skip collection of compilers which report an empty version

---

var/spack/repos/builtin/packages/py-moltemplate/package.py

[README](https://github.com/jewettaij/moltemplate/blob/master/README.md#installation-example) suggest using `pip`, but `PythonPackage` worked just fine. The package is mostly python, but the main usage AFAICT is from the bash script `moltemplate.sh`.
EDIT: `spack activate py-setuptools@35.0.2` fixed issue below.
~~WIP as I currently have~~
```
$ spack load python
$ spack load py-moltemplate@2.5.8
// run script:
moltemplate.sh v2.5.8 2017-11-06
File ".../spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/py-moltemplate-2.5.8-xi3ehimlchbhrb6jbcatb6fdnipeeg6c/bin/lttree.py", line 7, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
any hints are more than welcome.
@vishalkenchan any ideas?

moltemplate: add new package

---

var/spack/repos/builtin/packages/metasv/package.py

Prerequisites for MetaSV 0.5.4 are in other pull requests.
Specifically:
py-pybedtools: new package #6657 or #6487
py-pyvcf: new package #6665

MetaSV: adding new package

---

var/spack/repos/builtin/packages/petsc/package.py

Add `clanguage` variant to petsc library. The default value is `C` which expands to `--with-clanguage=C` during configuration.

Add clanguage variant for petsc

---

var/spack/repos/builtin/packages/hadoop/package.py

The url for Hadoop 2.6.4 no longer exists, and the mirror doesn't have a 2.6.4 area anymore. This PR replaces it with the latest stable, 2.9.0.

Hadoop: Replace broken url

---

var/spack/repos/builtin/packages/netlib-lapack/package.py

Build the LAPACKE interface with TMG routines to get a more complete liblapacke.
Functions like LAPACKE_zlatms* are currently missing.

build lapacke with tmg

---

var/spack/repos/builtin/packages/signify/package.py

OpenBSD tool to sign and verify signatures on files.
See https://github.com/aperezdc/signify
Build is confirmed to be working on Debian 9 and spack@95a384f05107cc80e0da7d5e7a5b75380ebf76f3.

Add new package signify

---

lib/spack/spack/cmd/install.py
lib/spack/spack/package.py

fixes #5940
This PR changes the option '--restage' of 'spack install' to '--dont-restage', inverting its meaning and the default behavior of the command.

spack install: restaging is the default

---

var/spack/repos/builtin/packages/openfoam-org/50-etc.patch
var/spack/repos/builtin/packages/openfoam-org/package.py

- similar to PR https://github.com/spack/spack/pull/6336 but retaining
and improving the bashrc patch.
Reuse the settings patch from 41, nothing changed there.
@pkoro

CONFIG: adjust openfoam-org for new version

---

var/spack/repos/builtin/packages/coinhsl/package.py

CoinHSL does not seem to be able to be built in parallel.
This commit forces serial compilation.
Fixes #6655

CoinHSL : Prevent CoinHSL from building in parallel

---

var/spack/repos/builtin/packages/sqlite/package.py

Fix for #6698. The patch needs to be applied to additional versions. The sqlite community had a fix in https://www.sqlite.org/src/info/b9a58daca80a815e, which should have made it into the 3.19.0 version, but a subsequent change in https://www.sqlite.org/src/info/17e0bb12d82b510b did not carry over that change. Hopefully this will get resolved in the next sqlite release, so I am optimistically only applying the patch through the current latest version of sqlite.

apply sqlite B0 patch to additional versions

---

var/spack/repos/builtin/packages/octave-optim/package.py
var/spack/repos/builtin/packages/octave-struct/package.py

```
$octave
> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
optim  |   1.5.2 | /spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/octave-optim-1.5.2-4z4rlp2l7z4xa4qejacp2mm25wt3xtol/optim-1.5.2
splines  |   1.3.1 | /spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/octave-splines-1.3.1-gixlgu2uljonbdqoddq4yodo6mvyzagc/splines-1.3.1
struct  |  1.0.14 | /spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/octave-struct-1.0.14-fiab2zsdhyzus6uhksi5uj3pesaxz6na/struct-1.0.14
```
**A general comment**: I think we need some custom `uninstall` for packages that extend `octave`. If I understand [documentation](https://www.gnu.org/software/octave/doc/v4.2.0/Installing-and-Removing-Packages.html) right, from …

octave: add optim and struct packages

---

lib/spack/spack/util/module_cmd.py

User reported a syntax error when lmod automatically swapped modules on module load.
Problem: Spack previously combined stdout and stderr from modulecmd because some systems use stdout and some use stderr. Systems that use stdout sometimes print messages from modulecmd through stderr
Solution: Check stdout for modulecmd output and use it if present, ignoring stderr. If no stdout, use stderr.

separate stdout and stderr for module loading

---

lib/spack/spack/cmd/edit.py

Fixes a Python 3 compatibility bug introduced by #6416.
When run with Python 3, I get the following error message:
```
$ spack edit -b python
==> Error: object of type 'filter' has no len()
```
In Python 2, `filter()` returns a list, but in Python 3, `filter()` returns an iterator, and iterators have no length.
@becker33 
P.S. Thoughts on how to write unit tests for `spack edit`? We're currently getting 37% coverage...

Fix python3 compatibility bug in spack edit command

---

lib/spack/spack/config.py

fixes #4573 
This PR is a quick fix for #4573. It seems that for some reasons there's a type check within the `update_config` function that permits to reassign objects only if they are instances of `list`. Here I work around the issue modifying the minimum number of lines possible.
I plan having a closer look at the `spack.config` module in the near future and see if I can propose an improvement of the API.
@pramodk

spack mirror: removing a mirror is not a no-op anymore

---

lib/spack/external/distro.py

Updates our vendored copy of `distro` to the latest release: 1.2.0 (2017-12-24).

Update to distro 1.0.4

---

lib/spack/external/argparse.py

I just noticed that the vendored version of argparse we were using (1.2.1) is from 2014-05-09. There is a new release available (1.4.0) from 2015-09-12 which should be stable.

Update to the latest version of argparse

---

lib/spack/spack/test/cmd/help.py

This one is raising a lot of exceptions and I don't know why (see Travis output). @tgamblin is this a consequence of the way `spack help` was implemented? Is there an easy way around it?

Add unit tests for spack help command

---

var/spack/repos/builtin/packages/py-biopython/package.py

[http://biopython.org/DIST/docs/install/Installation.html#htoc21](http://biopython.org/DIST/docs/install/Installation.html#htoc21)
> as of Biopython 1.50, mxTextTools is no longer used at all.

py-biopython: remove py-mx dependency for recent versions

---

lib/spack/spack/test/cmd/clean.py

Attempting to get one more line of coverage for when no arguments are given and it defaults to stage.

Add additional unit tests for spack clean command

---

var/spack/repos/builtin/packages/py-mpi4py/package.py

Fixes #6760. Just waiting for an acknowledgement from @shuds13.

Cython only needed for develop version of mpi4py

---

var/spack/repos/builtin/packages/paraview/package.py

I've been needing to add these lines to packages when using Intel MPI it seems since their compiler wrappers are in nonstandard places.

Explicitly specifying MPI compilers in Cmake for Paraview.

---

var/spack/repos/builtin/packages/tioga/package.py

Since I've been implementing Intel MPI I've been needing to add explicit listing of the MPI compilers to Cmake for the packages I'm using.

Explicitly listing the MPI compilers for Cmake configure for Tioga.

---

var/spack/repos/builtin/packages/augustus/package.py

Without a url set for the 3.3 version explicitly, spack attempts to fetch the 3.3 package from the binaries/old folder (like 3.2.3), rather than using the url value for the class

adding specific version url for augustus 3.3 due to old folder structure

---

var/spack/repos/builtin/packages/nginx/package.py

This fixes build issues with most recent gcc versions.
See issue #6252.

Updated 'nginx' from v1.12.0 to v1.13.8.

---

var/spack/repos/builtin/packages/perl-file-which/package.py

"Perl implementation of the which utility as an API" 
Package only depends on core-utils.
'spack test' successful

create perl-file-which package

---

var/spack/repos/builtin/packages/esmf/darwin_dylib_install_name.patch
var/spack/repos/builtin/packages/esmf/package.py

This PR contains fixes that I found necessary to install and use esmf on several platforms.
When using spack to build fortran programs that depend on esmf modules, the esmf `.mod` files are not found unless they are installed in the `include` directory of the esmf package (https://github.com/spack/spack/commit/bd816fe05ebf04c11f0b122dac5e25788c08aac0).
On Cray XC40 platforms, esmf needs a nudge (https://github.com/spack/spack/commit/1a5e0c10f03c6605b0f8bcbae786f537c0edc364) to use the mpi configuration instead of mpiuni (i.e. single process).
On OSX platforms, esmf executables attempt to load the esmf libraries from the build directory, which is removed after installation. Special linker commands are needed to create libraries that are loaded via rpath instead of their absolute path at …

Esmf fixes for Cray, OSX and mpich

---

var/spack/repos/builtin/packages/jags/package.py

openblas gives the following error when installing jags:
`1 error found in build log:
[ ... ]
181   checking for sgemm_ in -lcxml... no
182   checking for sgemm_ in -ldxml... no
183   checking for sgemm_ in -lscs... no
184   checking for sgemm_ in -lcomplib.sgimath... no
185   checking for sgemm_ in -lblas... (cached) no
186   checking for sgemm_ in -lblas... (cached) no
>> 187   configure: error: "You need to install the LAPACK library"`
Seems to install fine with atlas.  Might work with other lapack providers, so rather then depend on atlas, I'm adding a conflict for openblas.
Also added tags.

jags: lapack fix

---

var/spack/repos/builtin/packages/mesa/package.py

fixes https://github.com/spack/spack/issues/6697
builds fine on macOS high sierra with clang 9.

mesa: disable binutils on macOS

---

var/spack/repos/builtin/packages/likwid/package.py

according to the user forum, it's stable now https://groups.google.com/forum/#!topic/likwid-users/FyD38kQ_2JI

likwid: add stable 4.3.0

---

lib/spack/docs/packaging_guide.rst
lib/spack/spack/__init__.py
lib/spack/spack/build_systems/octave.py
lib/spack/spack/cmd/create.py
var/spack/repos/builtin/packages/bohrium/package.py
var/spack/repos/builtin/packages/dealii/package.py
var/spack/repos/builtin/packages/octave-optim/package.py
var/spack/repos/builtin/packages/octave-splines/package.py
var/spack/repos/builtin/packages/octave-struct/package.py

EDIT: I think I figure out the installation. 
Overriding `uninstall` is still tricky as I can't get to `octave` executable the same way I did with `install`:
```
def do_uninstall(self, force=False):
"""Uninstall this package by spec."""
name = 'spline'
inspect.getmodule(self).octave('pkg uninstall %s' % name)
Package.uninstall_by_spec(self.spec, force)
```
produces
```
==> Error: 'module' object has no attribute 'octave'
```
I guess I leave this for another time unless someone knows an easy fix.
----
~~it's WIP as I am bit confused why `setup_dependent_package()` is not called, defined in `octave` package~~ https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/octave/package.py#L234-L241
Maybe I just need to follow `PythonPackage` which has
```
import inspect
def …
```

add OctavePackage

---

var/spack/repos/builtin/packages/atom-dft/package.py
var/spack/repos/builtin/packages/libgridxc/package.py
var/spack/repos/builtin/packages/xmlf90/package.py

ATOM is a companion tool to SIESTA (for which there is still an open pull request #6466). I decided to name the package _atom-dft_ as to not confuse people who think of the Atom text editor when they see a package named _atom_.
Two dependency libraries are included in this pull request, though they are probably not useful for anything outside the SIESTA ecosystem.

atom-dft: new package plus dependencies

---

var/spack/repos/builtin/packages/rsem/package.py

It looks like the software was re-released requiring a new md5sum.

rsem: update version 1.3.0 md5sum

---

lib/spack/spack/fetch_strategy.py

Some servers report a `content-type` header instead of `Content-Type`:
```
HTTP/1.1 302 Found
Server: nginx/1.12.2
Date: Tue, 21 Nov 2017 09:32:49 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 325
Connection: keep-alive
Location: https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.bz2
HTTP/2 200 
server: nginx/1.12.2
date: Tue, 21 Nov 2017 09:32:50 GMT
content-type: application/x-tar
content-length: 9267606
last-modified: Wed, 13 Sep 2017 03:15:44 GMT
accept-ranges: bytes
```
Should fix #6347.

Fix HTML detection

---

var/spack/repos/builtin/packages/flex/package.py

As discussed in issue #6812, this PR documents that there is a build issue when flex v2.6.4 is built with gcc >=7.2.0.

Flex v2.6.4 conflicts with gcc@7.2.0

---

var/spack/repos/builtin/packages/motioncor2/package.py

- Add 1.0.4. 
- Motioncor2 depends on libtiff.so.3 .

Add a new version and runtime dependency for MotionCor2.

---

var/spack/repos/builtin/packages/r-rjags/package.py

new package r-rjags: "Interface to the JAGS MCMC library"
passes all spack tests execept the following which is expected I think:
XFAIL lib/spack/spack/test/cmd/help.py::test_reuse_after_help

package/r-rjags: create new package

---

var/spack/repos/builtin/packages/curl/package.py

nghttp2 requires a C++11 compiler, and doesn't build out of the box on RHEL6.

make nghttp2 optional for curl - it does not build w/older compilers

---

var/spack/repos/builtin/packages/openssl/package.py

perl is required for the configure script.

openssl: Add perl dependency

---

var/spack/repos/builtin/packages/neuron/package.py

This is still based on `Package` and not on `AutotoolsPackage `. For cross-compiling environment we need to follow two step compilation process and hence it's bit complicated (but still doable). In it's current format it has been tested on all platforms (OS X, Linux, BG-Q, Cray, KNL) and hence submitting this in the current form.

Adding NEURON simulator package

---

var/spack/repos/builtin/packages/metis/package.py

+ Ideally, we would make Metis a CMakePackage, but `metis@:5` doesn't use CMake.
+ For now, provide a `build_type=` variant similar what is found in CMakePackage.
+ There is a potential for duplicate specification of `CMAKE_BUILD_TYPE` if both variants `+debug` and `build_type=` are specified. I am looking for advice on how this can be resolved.

Provide build_type variant for Metis.

---

lib/spack/spack/cmd/configure.py

```
$ spack configure xz
==> Checking dependencies for ['xz']
```
```
$ spack configure xz cflags=-O2
==> Checking dependencies for ['xz', 'cflags=-O2']
```
```
$ spack configure xz cflags=-O2
==> Checking dependencies for xz
```

Fix spack configure output

---

var/spack/repos/builtin/packages/openfast/package.py

More issues I'm fixing with my packages as I've been implementing Intel MKL and MPI where I need to explicitly pass the BLAS and LAPACK libraries to OpenFAST so that it uses the libraries Spack administers. OpenFAST also needs `hdf5+hl` since the `+hl` HDF5 variant showed up.

Updating OpenFAST to use explicit lapack and blas libraries from Spack.

---

var/spack/repos/builtin/packages/blitz/package.py

`blitz@1.0.0` does not build with `gcc@7`, as explained in https://github.com/blitzpp/blitz/issues/17. The latest release fixes these problems, so I have added the new version of blitz to the spack package (and made it the default).

Blitz 1.0.1

---

var/spack/repos/builtin/packages/siesta/configure.patch
var/spack/repos/builtin/packages/siesta/package.py

As requested by @junghans in #6431, I have restricted the patch to specific versions. Since it also applies cleanly to 3.2 and older (the last substantial change to that file was in 2006) and should remain valid for any upcoming 4.0.x version, I used a version range. 4.1, once it's released, won't need the patch anymore, but will require changes to the  `configure` method.

Siesta: only apply patch to <4.1 and fix Intel compiler

---

var/spack/repos/builtin/packages/rmlab/package.py

Control the find_package of the PNG variant explicitly.
This avoids picking up an "external" PNGwriter install in case `~png` is picked by changing the default "AUTO" search to explicit "ON" (required) of "OFF" (ignore if exists).

Rmlab: Control PNG

---

var/spack/repos/builtin/packages/ghostscript/package.py

Added `libxext` dependency to `ghostscript`. The package build fails on vanilla `​​linux-ubuntu16.04-x86_64​` (clean install inside a `Docker` image), while on *regular* desktop systems it looked like the system-shipped `libxext` was masking this issue.

Fix missing dependency in ghostscript

---

var/spack/repos/builtin/packages/git/package.py

Fixes #6841 
Fixes #1436
[edit, wordsmithing]
Spack needs to pass information about where the linker can find `libintl`.  We're currently using `LDFLAGS` to do so.  The `LDFLAGS` info is pasted into the command line upstream of the a file (`libgit.a`) that includes unresolved symbols that need that library.  This approach fails on Ubuntu, although it seems to work on CentOS (see #6841 for additional background).
This change allows git to build on a Ubuntu 16.04.3 droplet.
TODO:

[WIP] Fix git gettext/libintl handling (builds on ubuntu)

---

var/spack/repos/builtin/packages/git/package.py

The git Makefile comes with two targets, `check` and `test`. However, these targets are completely different. `make test` runs the unit tests, while `make check` runs a static analysis tool called `sparse`. Instead of adding a new dependency to `git`, I decided to override the default `check` phase and only run `make test`. I have a feeling `make check` is intended for developers only.

Fix tests for git package

---

lib/spack/spack/fetch_strategy.py

Unrelated to #6876, but I noticed this bug while poking around.

Fix a typo in fetch_strategy error message formatting

---

share/spack/spack-completion.bash

The optional arguments to the `spack install` command have wildly diverged from our Bash tab completion. This PR fixes that.

Fix bash tab completion for spack install

---

lib/spack/spack/test/cmd/arch.py

There isn't an easy way of confirming that the output of the `spack arch` command is correct without duplicating the code itself, but if that seems like a good idea to others I can do that.

Add unit tests for spack arch command

---

var/spack/repos/builtin/packages/emacs/package.py

Building emacs on darwin throws an error when trying to build an Emacs
app in the `nextstep/Emacs.app` path of the build tree. For now, disable
building this app.
It's possible to enable building the app also; Homebrew offers options
to this effect, and also adds Mac-specific options for starting the
emacs daemon. However, for the sake of simplicity and getting a
workable up-to-date emacs installation on my machine as quickly as
possible, this commit focuses on a minimal viable modification.

emacs: on darwin, do not build Cocoa app

---

var/spack/repos/builtin/packages/libiconv/package.py

Older versions of libiconv don't work with newer versions of GCC

---

lib/spack/spack/main.py
lib/spack/spack/test/cmd/cd.py

```
$ spack cd
==> Error: module 'spack.modules' has no attribute 'print_help'
```
```
$ spack cd
==> This command requires spack's shell integration.
To initialize spack's shell commands, you must run one of
the commands below.  Choose the right command for your shell.
For bash and zsh:
. /Users/Adam/spack/share/spack/setup-env.sh
For csh and tcsh:
setenv SPACK_ROOT /Users/Adam/spack
source /Users/Adam/spack/share/spack/setup-env.csh
This exposes a 'spack' shell function, which you can use like
$ spack load package-foo
Running the Spack executable directly (for example, invoking
./bin/spack) will bypass the shell function and print this
placeholder message, even if you have sourced one of the above
shell integration scripts.
```
No one else noticed this because they probably use Spack's …

Fix bug in placeholder spack cd command and add unit tests

---

lib/spack/external/six.py

Updates our vendored copy of `six` from 1.10.0 (2015-10-07) to 1.11.0 (2017-09-17).

Update to the latest version of six

---

lib/spack/spack/test/cmd/versions.py
lib/spack/spack/util/web.py

Fixes #6690.
This is an attempt to get better coverage of the `spack versions` command.
Not sure how people feel about tests that require internet access. Even with internet access, these tests sometimes get results and sometimes don't, so I was hesitant to require a certain output for any of these packages. This is more of a "I can run this command and it doesn't crash" test than a "spack versions is actually working correctly" test.

Add unit tests for spack versions command

---

.coveragerc
share/spack/qa/setup.sh

On a local workstation, it seems that tracking multiple processes during coverage may result in malformed coverage reports for unit tests and not for build tests.
Given that multiple processes make a difference in coverage mainly for build tests, try to disable the tracking for unit tests to see if we get more stable coverage results.

Track multiple processes on Travis only for build tests

---

var/spack/repos/builtin/packages/libharu/package.py

I found, that libharu would not build on the current develop branch of spack, due to missing commands at build time. This is fixed by adding libtool, autoconf and automake as build-time dependencies.
However, I doubt that this is the correct approach. The package class inherits from AutotoolsPackage, should it thus not also inherit these dependencies?

package libharu: Add build deps

---

lib/spack/docs/contribution_guide.rst

From https://github.com/spack/spack/pull/4155#issuecomment-356553166:
> Should this advice to use `spack activate py-flake8` be added to the "Flake8 warnings" in https://github.com/spack/spack/blob/develop/lib/spack/docs/contribution_guide.rst? I just ran into the bug in #4154 also, and eventually stumbled into this thread after trying to kludge around the problem.
Also updated the error message for Sphinx as I could no longer reproduce the bug when setuptools is not in the `PYTHONPATH`.
@goxberry

Add suggestion to Contribution Guide to activate flake8

---

lib/spack/external/__init__.py

This PR is intended to keep track of all of the external libraries that Spack vendors. More importantly, it tracks where they came from and which versions we are vendoring. This comes in handy when upgrading packages as it also lists when a package no longer supports Python 2.6 and cannot be upgraded any further.
Many of these libraries are currently being upgraded in other PRs, so this PR depends on the following PRs to be merged first:

Keep track of source and versions for external libraries

---

.travis.yml

According to Travis docs the exit code of `after_success` doesn't affect the build result. Instead, uploading the coverage data as the last step of the script will cause the job to fail if the command exits with non-zero.
https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build
relates to #6872

Travis: upload the coverage data as part of the script

---

share/spack/qa/run-build-tests

Currently, when a build test fails, there isn't an easy way to see what caused it. Instead, Travis gives us the error message:
> This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.
This PR reduces the verbosity of our build. I think our error parsing of the build log is good enough that we no longer need the full output.

Reduce verbosity of build tests

---

lib/spack/spack/spec.py

Fixes #6905
External packages can have unspecified properties, in particular all children of external packages are stripped.
This updates the conflict-checking logic to require that the conflict spec matches exactly and that all fields mentioned in the conflict spec are present in the concretized spec in order to report a conflict. This will automatically skip all conflict checks for dependencies of externals.

Fix conflict checking for external packages.

---

var/spack/repos/builtin/packages/coinhsl/package.py

Add version 2014.01.10 to the `coinhsl` package and make it the preferred version, because this version is the latest stable release.

coinhsl: add version 2014.01.10

---

lib/spack/spack/build_environment.py
var/spack/repos/builtin/packages/python/package.py

Test dependencies which were python extensions were not being set up. This updates the python package definition to understand the 'test' deptype.

Fix support for test dependencies which are python extensions

---

var/spack/repos/builtin/packages/autoconf/package.py
var/spack/repos/builtin/packages/canu/package.py
var/spack/repos/builtin/packages/likwid/package.py
var/spack/repos/builtin/packages/repeatmasker/package.py
var/spack/repos/builtin/packages/vcftools/package.py

Instead, use `spec['perl'].command.path`.
Just some cleanup based on the feedback in #6910.

Do not construct path to perl command manually

---

var/spack/repos/builtin/packages/catch/package.py

Also updated all the sums from previous versions. For some reason the old sha1sums were not working, though the files for the old versions doesn't show any new info due to the change on github repository.

Updated catch to newer version (up to 2.1.0)

---

var/spack/repos/builtin/packages/py-fparser/package.py

Python implementation of a Fortran 66/77/90/95/2003 language parser.
This package can be used as a basis for tools that analyse, optimise and parallelise Fortran software. See, for example, https://github.com/stfc/PSyclone.

Py-fparser: python parser for Fortran code

---

var/spack/repos/builtin/packages/graphviz/package.py

It looks like the Graphviz guys migrated their repo to a brand new platform that broke all the previously working download URLs. They are now providing source packages for version `2.40.1` only. After lurking around the web, I've found the missing package (`graphviz-2.38.0.tar.gz`) on the Fedora package repo. The file hash is the same.

Fix no longer existing download url in graphviz

---

var/spack/repos/builtin/packages/ruby/package.py

Fix "unqualified variable spec['openssl']" error in the ruby package
that arises when trying to install the `+openssl` variant by
referencing the `spec` field in the `Ruby` class. A similar error
arises when trying to install the `+readline` variant; this error is
also fixed by this patch.

ruby: fix +openssl & +readline variants

---

var/spack/repos/builtin/packages/ipopt/package.py

Add latest version of IPOPT. Relax METIS version linking requirements after looking at IPOPT source code and METIS 5 manual, and discovering that the only METIS API calls in IPOPT are to functions that have the same call signature (and semantics) in METIS 4 and METIS 5.

ipopt: add version 3.12.8, relax metis version requirements

---

var/spack/repos/builtin/packages/pango/package.py

```
Safe versions:  
1.41.0    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.41.0.tar.xz
1.40.3    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.3.tar.xz
1.40.1    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.1.tar.xz
1.36.8    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.36.8.tar.xz
```
```
Safe versions:  
1.41.0    http://ftp.gnome.org/pub/GNOME/sources/pango/1.41/pango-1.41.0.tar.xz
1.40.3    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.3.tar.xz
1.40.1    http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.1.tar.xz
1.36.8    http://ftp.gnome.org/pub/GNOME/sources/pango/1.36/pango-1.36.8.tar.xz
```
@adamryczkowski can you see if this fixes #6938?

Add url_for_version to pango package

---

lib/spack/docs/.gitignore
lib/spack/docs/Makefile
lib/spack/docs/conf.py
lib/spack/docs/package_list.rst
lib/spack/spack/cmd/list.py

Fixes #6857.
- Generating the HTML from for >2300 packages from RST in Sphinx seems to
take forever.
- Add an option to `spack list` to generate straight HTML instead.
- This reduces the doc build time to about a minute from over 5 minutes on my mac.
I'd really like to get rid of the package list altogether and have a searchable site for packages (like the brew formula page).  But that will take longer and this was an easy fix.

Speed up doc builds with spack list --format=html

---

lib/spack/spack/cmd/install.py
lib/spack/spack/cmd/spec.py
lib/spack/spack/spec.py
lib/spack/spack/test/cmd/install.py

The feature added in #4611 is currently broken. This commit fixes the behavior of the command and adds unit tests to ensure the basic semantic is maintained.
It also changes slightly the behavior of `Spec.concretized` to avoid copying caches before the concretization (as this may result in a wrong hash computation for the DAG).
@nazavode

Fix installing specs from yaml file

---

README.md

The logo link in the main `README.md` accidentally pointed to the `features/svg-logo` branch, and is broken now that that's been deleted.  This fixes it to point to the logo on `develop`.

Fix logo link in README.md to point to the develop branch.

---

var/spack/repos/builtin/packages/ipopt/package.py

This commit changes the IPOPT package file to pass in default empty
flags for CFLAGS, CPPFLAGS, CXXFLAGS, FFLAGS, and LDFLAGS to prevent
IPOPT from using default compiler flags that can override spack
provided flags.
Tries to address part of #6640

IPOPT : Add empty compiler flags for IPOPT build to use spack flags

---

lib/spack/spack/build_environment.py
lib/spack/spack/test/flag_handlers.py
var/spack/repos/builtin/packages/parmetis/package.py

The flag_handlers method was being set as a bound method, but when reset in the package.py file it was being set as an unbound method (all python2 issues).
This gets the underlying function information in either case, which is the same.
The bug was uncovered for parmetis in #6858. This is a partial fix. Included are changes to the parmetis package.py file to make use of flag_handlers.
(The other part of the fix is in #6970.)

Fix type issues with setting flag handlers

---

lib/spack/spack/spec.py
lib/spack/spack/test/test_activations.py

This commit removes logic from Spec that was there only to be used in tests, and allows to set a new prefix cleanly in user's code.

Added a setter to the Spec.prefix property

---

var/spack/repos/builtin/packages/vtk/package.py

Fix bugs in building VTK 6.1.0:
* NetCDF C++ bindings detection failures fixed by specifying header directory in `NETCDF_CXX_IN?CLUDE_DIR` and full library path in `NETCDF_CXX_LIBRARY`
* Makefile bug fixed by disabling garbage collection flags for Objective-C, which have been removed since VTK 6.2.0. XCode 5.1 removed garbage collection for Objective-C binaries, so compiling with garbage collection flags using recent versions of XCode would result in compile-time errors

Fix vtk 6.1.0 bugs

---

var/spack/repos/builtin/packages/qt/qt4-corewlan-new-osx.patch

Update the qt4 CoreWLAN patch to apply to macOS/OS X 10.12 and 10.13,
which both still use the CoreWLAN framework in their SDKs (although
it's apparently deprecated?!). Without this patch update, `spack
install qt@4.8.6` fails on macOS/OS X 10.12 because the linker
cannot find headers from the CoreWLAN framework.

qt@4 : update corewlan patch for OS X 10.1[23]

---

.coveragerc
share/spack/qa/run-build-tests
share/spack/qa/run-unit-tests
share/spack/qa/setup.sh

According to what was discovered in #6887, one of the problems is calling 'coverage combine' twice without the '-a' flag. This removes the first call within our test scripts.

Restore multiprocessing in unit tests

---

var/spack/repos/builtin/packages/abinit/package.py

The old URL for Abinit 8.2.2 does not work anymore. This PR makes it work for Abinit 8.6.3, I tested it. But I haven't tested the older versions.

Add Abinit 8.6.3

---

var/spack/repos/builtin/packages/flex/package.py

I just ran into the same problem as @simoatze in #6942 and was confused because I have been compiling flex 2.6.4 with GCC 7 for quite some time. Some further debugging shows that newer Ubuntu releases seem to cause the problem and not GCC 7 (tested on Ubuntu 16.04, Ubuntu 17.10 and and Fedora 27). There is probably some other underlying problem but I could not find it (Ubuntu 17.10 and Fedora 27 use the same glibc version, for example).
By the way: is it possible to somehow specify `arch=linux-ubuntu17.10-*` or do we only care about `x86_64` anyway?
Edit: Arch and Gentoo also do not carry any GCC7-specific patches (Fedora and Ubuntu still use older flex versions).

flex: restrict GCC conflict to newer Ubuntu releases

---

etc/spack/defaults/packages.yaml
var/spack/repos/builtin/packages/mesa/package.py
var/spack/repos/builtin/packages/opengl/package.py
var/spack/repos/builtin/packages/qt/package.py
var/spack/repos/builtin/packages/vtk/package.py

After a lot of experimentation and messing around, I think I have settled on what I think are the goals for the VTK spack package.  Please chime in if you disagree or have different thoughts on the matter.
We need the following four *independent* options:
1. python wrapping (yes or no)
2. qt (yes or no)
** should not imply software rendering by choosing qt
3. hardware vs. software rendering
** if doing software rendering, there is no reason not to use llvm by default to speed it up
** down the road we might like to have offscreen hardware rendering (via EGL) when GPUs supporting it are available
4. rendering backend (opengl1 or opengl2) will become less important as the opengl1 backend will be deprecated soon.
~~I tried to achieve these goals by only changing the `vtk` package, but I'm …

Add more vtk options

---

lib/spack/spack/cmd/create.py

- Previously would print the spec's namespace twice, rather
than printing the spec's namespace, followed by the repo's namespace.

Fix error message typo in 'spack create' cmd

---

var/spack/repos/builtin/packages/argp-standalone/argp-fmtstream.h.patch
var/spack/repos/builtin/packages/argp-standalone/package.py

Adds a package for the standalone version of the argp argument parsing
interface from glibc for unix-style command options.

argp-standalone@1.3: new package

---

var/spack/repos/builtin/packages/slurm/package.py

The `configure` in `slurm` assumes `readline` support by default and omits the corresponding `--with-readline` option, only the opposite `--without-readline` is recognized, any attempt to specify `--with-readline` is treated as `without`:
```console
$ spack stage slurm
$ spack cd slurm
$ ./configure --with-readline=/usr/lib
[...]
checking for whether to include readline suport... doh!
configure: error: bad value "/usr/lib" for --without-readline
```

Fix readline variant handling in slurm

---

var/spack/repos/builtin/packages/netlib-lapack/package.py
var/spack/repos/builtin/packages/netlib-xblas/package.py

* add new package: netlib-xblas
* add variants to disable building Fortran interfaces, disable building plain BLAS routines as part of XBLAS
* add XBLAS option to netlib-lapack

netlib-xblas 1.0.248: new package

---

var/spack/repos/builtin/packages/libtool/package.py

On Darwin and other BSD systems, the system 'libtool' and 'libtoolize'
are BSD libtool and libtoolize, respectively. Some build systems
require the GNU versions of these commands, so BSD package systems
tend to name the GNU versions 'glibtool' and 'glibtoolize',
respectively, to avoid namespace collisions.
A problem with the current libtool package is that it installs the GNU
libtool commands as 'libtool' and 'libtoolize', respectively, but
build systems on BSD platforms will attempt to run 'glibtool' and
'glibtoolize'. The expedient solution to this problem is to symlink
'libtool' to 'glibtool' and 'libtoolize' to 'glibtoolize', because
attempting to patch the detection logic one build system at a time
seems impractical.
The motivation for this patch came when trying to run `spack …

libtool: symlink libtool{ize} to glibtool{ize}

---

lib/spack/spack/build_systems/python.py

Avoid adding an "outside" python user site (e.g a user's home) directory during python package installs.
Implements #6611
Fixes packages with auto-find side effects such as `py-setuptools` (https://github.com/pypa/setuptools/issues/1229) that cause `py-matplotlib` to fail to build #6558

Python Installs: No User Site Dir

---

lib/spack/spack/cmd/install.py
lib/spack/spack/test/cmd/install.py

This enables multiple `--file` options for `install`:
```
$ spack install -f spec1.yaml  -f spec2.yaml -f spec3.yaml
```
Allows to mix specs from cli and `yaml` files at the same time:
```
$ spack install -f spec1.yaml  -f spec2.yaml qt mpi graphviz
```
During the streamlining of arguments handling logic in `install`, #6983 has been fixed. Added regressions for it, and tests for the new feature.

Enable install of multiple specs from yaml files

---

var/spack/repos/builtin/packages/bzip2/package.py

Looking at build logs, it seems that prior to this commit `bzip2` was using `cc`, and relying on the PATH to be set correctly to find Spack wrappers. This commit improves the robustness of the recipe, by using the absolute path of the wrapper.

bzip2 now uses 'spack_cc' as a compiler

---

var/spack/repos/builtin/packages/r/package.py

Add configure arguments that specify the location of the tcl and tk config scripts.
Tested on Centos7 w/ the system gcc (4.8.x) on a DO droplet.  Both with and without X build.  `capabilities("tcltk")` is `true` for both.  Even when configured with `+X`, `capabilities("X11")` is only true if `DISPLAY` is set (a valid X session).
I'm not entirely certain of the current R, X, Tk, Linux, and MacOS subtleties, so this would benefit from a review by someone who is.
Fixes #7072

Tell R's configure about tcltk config

---

var/spack/repos/builtin/packages/binutils/package.py
var/spack/repos/builtin/packages/libtool/package.py

Packages with binutils dependencies (e.g., LLVM) will add binutils to the spack environment path during builds, which causes build systems to preferentially use spack's `ar` and `ld` over the system `ar` and `ld`. This namespace resolution is problematic because it results in warnings from the linker stating that the static libraries built are for the wrong architecture.
The fix is to follow Homebrew's convention of prepending 'g' to the GNU versions of any native BSD system utility. This PR also fixes the error I made in #7060.
It's possible that more packages need this sort of fix (e.g., `tar`, `sed`), but I haven't yet run into issues with those tools yet.

libtool, binutils: fix darwin linking

---

.travis.yml

This is a backport of #6515. I think we need it to set up MacOS correctly for the cron job on `master`, but it does not affect in any way the release from a user's perspective.
Failed build [here](https://travis-ci.org/spack/spack/builds/331480288)

travis: removed /usr/local/include/c++ before installing gcc on OSX

---

lib/spack/spack/cmd/install.py
lib/spack/spack/report.py
lib/spack/spack/test/cmd/install.py
templates/reports/junit.xml
var/spack/repos/builtin.mock/packages/raiser/package.py

The generation of a JUnit report was previously part of the install command. This commit factors the logic into its own module, and uses a template for the generation of the report.
It also improves report generation, that now can deal with multiple specs installed at once. Finally,  extending the list of supported formats is much easier than before, as it entails just writing a new template.
refers #2917
Running this command:
```console
spack install --log-format=junit --log-file=hdf5.xml szip  hdf5+szip~mpi tar
```
produces the following file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
<testsuite name="libszip_qabk3nm"
errors="0"
tests="1"
failures="0"
time="5.741205215454102"
timestamp="Thu, 18 Jan 2018 07:41:18" >
<properties>
<property name="architecture" …
```

Cleaned up JUnit report generation on install

---

lib/spack/spack/compilers/clang.py
lib/spack/spack/compilers/gcc.py
lib/spack/spack/compilers/intel.py
lib/spack/spack/compilers/nag.py

Fixes #7016.
In GCC 7, `-dumpversion` was changed to return the major version, not the full version. Use `-dumpfullversion` to get around this. This change was already made for `gcc` and `g++` in #6111, but not for `gfortran`, resulting in the issue reported in #7016. This PR fixes that.
Tested on:
@hfp

Fix gfortran 7 detection

---

conftest.py
lib/spack/spack/test/cmd/dependencies.py
lib/spack/spack/test/cmd/dependents.py
lib/spack/spack/test/cmd/find.py
lib/spack/spack/test/cmd/gpg.py
lib/spack/spack/test/cmd/graph.py
lib/spack/spack/test/cmd/list.py
lib/spack/spack/test/cmd/module.py
lib/spack/spack/test/cmd/uninstall.py
lib/spack/spack/test/cmd/url.py
lib/spack/spack/test/cmd/versions.py
lib/spack/spack/test/database.py
lib/spack/spack/test/package_sanity.py
lib/spack/spack/test/python_version.py
lib/spack/spack/test/spec_syntax.py
pytest.ini

This PR marks the slowest unit tests in our suite, so if you run:
```console
$ spack test -m "not slowtest"
```
you'll deselect them. On my laptop this runs in ~70 sec. instead of ~230 sec. for the full suite. Can be quite useful to integrate testing in development workflow (for instance having the IDE running  `spack test -m "not slowtest"` for you in the background).
@nazavode

Mark slow unit tests

---

var/spack/repos/builtin/packages/rtags/package.py

could not fetch previous `url`:
```
==> Fetching https://andersbakken.github.io/rtags-releases/rtags-2.12.tar.gz
curl: (22) The requested URL returned error: 404
==> Fetching from https://andersbakken.github.io/rtags-releases/rtags-2.12.tar.gz failed.
==> Error: FetchError: All fetchers failed for rtags-2.12-x2xgt54mk2x6qxvog2kxo2dti6yyjzvo
FetchError: FetchError: All fetchers failed for rtags-2.12-x2xgt54mk2x6qxvog2kxo2dti6yyjzvo
/Users/davydden/spack/lib/spack/spack/package.py:993, in do_fetch:
25                                     self.spec.format('$_$@'), ck_msg)
26
27            self.stage.create()
>> 28            self.stage.fetch(mirror_only)
29            self._fetch_time = time.time() - start_time
30
31            if spack.do_checksum and self.version in self.versions:
```

rtags: add 2.17

---

var/spack/repos/builtin/packages/python/package.py

Otherwise not all autotools are smart enough.
Not sure if this is in general a good idea though. Or whether it is preferable to fix the problem for the offending packages on a case by case basis. 
Unfortunately I don't remember the packages that reacted badly...

symlink python3 to python

---

var/spack/repos/builtin/packages/libdwarf/package.py

Prior to this PR, `libdwarf` did not build on Darwin. This PR fixes compilation on Darwin and:
* fixes the dynamic library suffix for the installed `libdwarf` library
* adds the `zlib` dependency so that `libdwarf` links to Spack-installed zlib, instead of the system-installed zlib

libdwarf: fix linking, fix build on Darwin

---

var/spack/repos/builtin/packages/lz4/package.py

Fix the dylib name of `lz4`. This commit fixes a linking error when trying to build `libarchive` on Darwin.

lz4 platform=darwin: fix dylib name

---

lib/spack/external/ctest_log_parser.py
lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/edit.py
lib/spack/spack/cmd/log_parse.py
lib/spack/spack/main.py
lib/spack/spack/util/log_parse.py

When a build errors out, Spack goes through the build log and scrapes it for errors and warnings (see #5016, #5561).  We found that this was taking forever (like an hour) on large logs.  It turns out that [Python regular expressions are slow](https://swtch.com/~rsc/regexp/regexp1.html), and this affects our log scraping in bad ways.
This PR does several things:
Here's `spack log-parse`:
```
$ spack log-parse -h
usage: spack log-parse [-h] [--show SHOW] [-c CONTEXT] [-p] [-w WIDTH]
[-j JOBS]
file
filter errors and warnings from build logs
positional arguments:
file                  a log file containing build output, or - for stdin
optional arguments:
-h, --help            show this help message and exit
--show SHOW           comma-separated list of what to show; options: errors,
warnings …
```

Improve log parsing performance

---

lib/spack/docs/tutorial_advanced_packaging.rst

So far most edits are organization. One section was removed. 
* Remove the section "What happens at subscript time?" - this is overly-detailed for the tutorial (perhaps it should move somewhere @alalazo do you have a thought on where?)
* Move the sections "Extra query parameters" and "Attach attributes to other packages" into the section group "Other Packaging Topics". The goal was to organize so that the following sections (considered most interesting) come first:
* A motivating example (`cmake_args` using `.libs` and implementation of `netlib-lapack.lapack_libs`)
* Single package providing multiple virtual specs
* Set environment variables in dependent packages at build-time (updated section title)
* Set environment variables in your own package (updated section title)
* Updated section …

Update tutorial on advanced packaging

---

lib/spack/spack/modules/common.py

Module generation catches a few types of errors in configure_args. This PR adds NameError to that list. This catches errors due to fields populated by setup_package being unavailable at module generation time.

Catch NameErrors in module generation

---

lib/spack/spack/cmd/activate.py
lib/spack/spack/filesystem_view.py
lib/spack/spack/package.py

includes:
* with_dependency flag for do_activate
* ignore_conflicts flag for do_activate
* start of cleanup of activate cmd
@scheibelp this is the commit that I was talking in #7159 about. I didn't have much time to look at it again, so take my comments with some care.
Essentially this delegates the ignore-conflicts stuff to `package.activate` and removes the `--force` flag. It also delegates the dependency resolution to the view generator and not on the single extension (this prevents double adding, but feels somewhat hacky).
Feel free to comment and point out errors

Add ignore_conflicts to package activation

---

var/spack/repos/builtin/packages/fish/package.py

The Fish Shell puts release tarballs on Github now; the old URL is a dead link.

Update fish url for fish 2.7.1

---

lib/spack/docs/tutorial_basics.rst

This allows users to share a common location for the public key to trust for the tutorial.

Change location of public key in basic tutorial

---

var/spack/repos/builtin/packages/libsplash/package.py

Adds the latest release of libSplash (1.7.0) and newly learned CMake flags for explicit dependency control.
Modifies HDF5 dependency: non-MPI splash does (and did) never run with a parallel HDF5, due to it's internal cross-dependencies on MPI.

libSplash: 1.7.0

---

var/spack/repos/builtin/packages/petsc/package.py

This ensures that PETSc configure is invoked using the specified
python@2.6:2.8 (Spack uses "python2") rather than whatever "python" is
found in the environment (might be 2 or 3).

petsc: explicitly use python('configure', ...)

---

var/spack/repos/builtin/packages/py-pybind11/package.py

Add the latest release of `pybind11` and its `develop` version.

pybind11: 2.2.[1,2] & develop

---

var/spack/repos/builtin/packages/python/package.py

fixes #7128
Before this PR packages that were indirectly dependent on python might have failed due to the inconsistency between the python found in the environment and the standard libraries set in `PYTHONHOME`.
@nazavode

Set a default python that is consistent with the libraries in PYTHONHOME

---

.travis.yml

I think the main issue here is that we ship a custom version of a system library (`argparse`), and this is prone to fail if `argparse` is imported before we hack `sys.path` internally.
Probably a better solution would be not to customize argparse, but instead have a wrapper on top of whatever the system provides.

Use python3.6 to test building docs

---

var/spack/repos/builtin/packages/ascent/package.py
var/spack/repos/builtin/packages/conduit/package.py

* remove variants disabling blas and lapack for py-numpy, issues building these have been resolved
* for CMake greater than 3.10, FindMPI changed, so use MPIEXE_EXECUTABLE instead of MPIEXE for 3.10 and newer

updates to conduit and ascent packages

---

lib/spack/docs/command_index.in
lib/spack/docs/conf.py
lib/spack/docs/getting_started.rst
lib/spack/docs/mirrors.rst
lib/spack/external/argparse.py
lib/spack/llnl/util/argparsewriter.py
lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/bootstrap.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/cmd/commands.py
lib/spack/spack/cmd/compiler.py
lib/spack/spack/cmd/compilers.py
lib/spack/spack/cmd/config.py
lib/spack/spack/cmd/diy.py
lib/spack/spack/cmd/flake8.py
lib/spack/spack/cmd/gpg.py
lib/spack/spack/cmd/install.py
lib/spack/spack/cmd/log_parse.py
lib/spack/spack/cmd/mirror.py
lib/spack/spack/cmd/repo.py
lib/spack/spack/cmd/setup.py
lib/spack/spack/config.py
lib/spack/spack/main.py
lib/spack/spack/test/cmd/commands.py

This improves the command reference in the docs. Previously, the command reference listed only commands for which we explicitly wrote documentation.  Now it lists all Spack commands and shows their usage.  This was sort of inspired by the [Docker CLI reference](https://docs.docker.com/engine/reference/commandline/docker/).
This also contains a number of improvements to `spack <cmd> -h` output.
You can [look at a preview here](https://spack.readthedocs.io/en/features-better-command-index/command_index.html).
@JusticeForMikeBrown: you might like this, as it would've saved you a few issue submissions.

Improve the Spack command reference 

---

var/spack/repos/builtin/packages/metis/package.py

Fix for installing `metis@4.0.3~shared`.

Fix for building METIS 4.0.3 with '~shared'.

---

var/spack/repos/builtin/packages/ipopt/package.py

Running `spack module refresh -m lmod --delete-tree -y` throws the
following warning:
```console
==> Warning: Could not write module file [/Users/oxberry1/spack/share/spack/lmod/darwin-sierra-x86_64/openblas/0.2.20-ibhtl5q/clang/5.0.1/ipopt/3.12.9.lua]
==> Warning:    --> global name 'prefix' is not defined <--
```
This warning arises because the variable expansions in
`spack.modules.BaseFileWriter` occur at module/package scope. Even
though `prefix` is an argument to `install` methods in e.g.,
`MakefilePackage`, so using this argument within package methods is
legal, doing so defeats the introspection logic in
`spack.modules.BaseFileWriter`. Replacing `prefix` with `self.prefix`
resolves the problem, because the introspection logic in
`spack.modules.BaseFileWriter` can use introspection …

[bugfix] ipopt: fix lmod global name 'prefix' undefined bug

---

var/spack/repos/builtin/packages/gdbm/package.py

Prior to this commit, running `spack module refresh` with `gdbm`
installed throws the warning:
```console
==> Warning: Could not write module file [/Users/oxberry1/spack/share/spack/lmod/darwin-sierra-x86_64/Core/gdbm/1.14.1.lua]
==> Warning:    --> global name 'spack_cc' is not defined <--
```
This warning is repeated for every `gdbm` installation in Spack.
The cause of the issue seems to be the same as in spack/spack (#6089):
using `spack_cc`, `spack_cxx`, or similar inside `configure_args`
causes the warnings to throw when module files are generated.
Moving the use of `spack_cc` into `setup_environment` seems to fix the
problem, even though it's a bit of a kludge.
I've tested this commit both on my MacBook Pro with clang@8.1.0-apple and gcc@7.3.0, and on RHEL 7 with intel@16.0.3 (which …

[bugfix] gdbm: fix lmod global name 'spack_cc' undefined

---

var/spack/repos/builtin/packages/hypre/package.py

Add a libs method to `hypre` to override the default `libs` method
behavior, which will not locate hypre's libraries. Add linkage to
LAPACK & BLAS as recommended in #7165.

hypre: add libs method

---

var/spack/repos/builtin/packages/xbraid/package.py

XBraid installs `libbraid.a`, but the default `libs` method
implementation will search for `libxbraid`, which does not exist. This
commit fixes the behavior of the `libs` method for the `xbraid`
package by overriding package's `libs` method.

xbraid: add libs method

---

var/spack/repos/builtin/packages/libtool/package.py

Version 4 of the libtool/darwin debacle:
`AutotoolsPackage` hardcodes `libtool` & `libtoolize` into the `autoreconf`
stage, so the commands `libtool` and `libtoolize` MUST be present, and
shimming in `glibtoolize` into `AutotoolsPackage` when `sys.platfrom ==
'darwin'` does not work.
`join_path(spec['libtool'].prefix.bin, 'libtool')` still shadows system
BSD libtool (in `apple-cctools`, see PR #7177), but this shadowing could
be okay, depending on the combination of dependent specs.
Should fix #7140, and hopefully partially address raised in #7172.

libtool: actually do symlinking correctly on darwin

---

var/spack/repos/builtin/packages/adios2/package.py

Adds the first stable API release of ADIOS2, v.2.1.0.
Also adds a missing `pybind11` CMake flag for proper Python selection (needed in both the new and previous version).

ADIOS 2.1.0

---

var/spack/repos/builtin/packages/mfem/package.py

Spack's hypre package depends on LAPACK and BLAS, so linking to hypre
requires linking to the LAPACK and BLAS libraries used to build hypre.

mfem: have hypre link line also link lapack+blas

---

var/spack/repos/builtin/packages/netlib-scalapack/package.py

This is useful when traversing a concretized dag for link dependencies, e.g. in the `.all_libs` property proposed in PR #7256.

netlib-scalapack: add the libs property

---

var/spack/repos/builtin/packages/augustus/package.py

The package archive was updated on 2018-01-26, but the version number was not incremented.
I contacted the developers, and was told:
"No functionality has changed. In this update only some object files were removed, that could theoretically interfere with compilation"
While installing, also found that the bamtools libraries now seem to be in lib64, so updated the makefile filter. Installed successfully.

Augustus update hash

---

var/spack/repos/builtin/packages/py-pyvcf/package.py

py-pyvcf: versions 0.6.7 and 0.6.8

---

var/spack/repos/builtin/packages/cbench/package.py

The edit phase of `cbench` was used to set environment variables. Though this works, the variables set this way are not dumped to `build.env`. This commit fixes the issue by setting those variables in the
`setup_environment` function.

cbench set its environment using `setup_environment`

---

var/spack/repos/builtin/packages/clamr/package.py

clamr: needs cmake-3.1

---

var/spack/repos/builtin/packages/bml/package.py

bml: enable MPI by default

---

var/spack/repos/builtin/packages/nalu/package.py

Yaml-cpp hasn't tagged a release in over 2 years, yet they have fixed many things and now have the ability to use `find_package` in CMake. Since we use this feature in Nalu, we require the latest `yaml-cpp` until they tag a new release. I have also deprecated the now unnecessary `ENABLE_INSTALL` flag.

Nalu now requires yaml-cpp@develop

---

lib/spack/llnl/util/filesystem.py

This updates the fix_darwin_install_name function to use the Spack
Executable object to run install_name_tool, which ensures that
process output is formatted as a 'str' for python2 and python3.
Originally fix_darwin_install_name was invoking subprocess.Popen
directly.

Make fix_darwin_install_name python3-compatible

---

lib/spack/docs/requirements.txt

Later versions of Sphinx fail due to possible clashes with our custom `argparse`.

Pin Sphinx version to v1.7.0

---

var/spack/repos/builtin/packages/llvm/package.py

Restricting python dependency, so that it works with py3 in compatible versions (@5:) and removing broken target see https://reviews.llvm.org/D19942 ("Remove bit-rotten CppBackend.")

Fix python dependencies of llvm and remove broken backend

---

var/spack/repos/builtin/packages/cpu-features/package.py

Adds Google's new [`cpu_features`](https://github.com/google/cpu_features) library.
Install was added [recently](https://github.com/google/cpu_features/issues/18), so don't take the `0.1.0` release but the current `master` until a new version is published.

cpu_features

---

lib/spack/docs/tutorial/examples/Autotools/0.package.py
lib/spack/docs/tutorial/examples/Autotools/1.package.py

AutoTools -> Autotools
Fix for #7249

Fix class name in build system tutorials

---

var/spack/repos/builtin/packages/bzip2/package.py
var/spack/repos/builtin/packages/fftw/package.py
var/spack/repos/builtin/packages/intel-parallel-studio/package.py
var/spack/repos/builtin/packages/libxsmm/package.py
var/spack/repos/builtin/packages/netcdf-cxx/package.py
var/spack/repos/builtin/packages/netcdf-cxx4/package.py
var/spack/repos/builtin/packages/netlib-xblas/package.py
var/spack/repos/builtin/packages/opencv/package.py

i introduced those in https://github.com/spack/spack/pull/6552 and I don't understand how it worked as `find_libraries` seem to have `recursive` for at least 7 months https://github.com/spack/spack/blame/develop/lib/spack/llnl/util/filesystem.py#L1069

change recurse into recursive in a few places

---

lib/spack/spack/spec.py

This allows properties like `.headers` and `.libs` to simply return `None` to produce a reasonable error message. Currently, returning `None` from these properties raises an `AttributeError` which is not appropriate.

[spack/spec.py] raise a query failure error if a property query returns None

---

var/spack/repos/builtin/packages/mpich/package.py

MPICH git needs submodules since October 30, 2017 (see pmodels/mpich@c04a18f5606c7df381d3092327b96fe42a59cf2c). Fixes #7246.

mpich@develop: needs git submodules

---

var/spack/repos/builtin/packages/rsync/package.py

Fix the source link to rsync downloads.
The old link only contained the latest release, the new link contains all.

Rsync: Fix Src Link

---

var/spack/repos/builtin/packages/ruby/package.py
var/spack/repos/builtin/packages/ruby/ruby_23_gcc7.patch
var/spack/repos/builtin/packages/ruby/ruby_24_gcc7.patch

* pkgconfig fixes a "libffi.a requires -fPIC" build error (i.e. unrelated to the gcc issue...)
* the patches solve the mentioned problem on GCC 7.x
* patch for ruby 2.3 (also applies to 2.2) from: https://bugs.ruby-lang.org/issues/13150#note-14
* patch for ruby 2.4 from https://github.com/ruby/ruby/commit/8788489ca967599f83d96083f244f91c83286a88.patch

fix ruby build on gcc >= 7

---

var/spack/repos/builtin/packages/silo/package.py

add -ldl to silo ldflags when building with static hdf5

---

lib/spack/spack/mixins.py

Fixes #7366
Spack functionality which filters spack compiler wrappers from installed files was assuming that all compilers defined `fc` and `f77`; compilers which don't define `fc` or `f77` in `compilers.yaml` were getting reference errors. This adds a guard to the access of `fc`, `f77`, `cc`, and `cxx`.

only filter compiler paths for binaries provided by the compiler

---

var/spack/repos/builtin/packages/openmpi/package.py

This removes some redundant headers from sub-directories, returned by the default `.headers` handler.
Needs #7277

openmpi: add package-specific 'headers' property

---

var/spack/repos/builtin/packages/py-bsddb3/package.py
var/spack/repos/builtin/packages/py-pyfasta/package.py

Just noticed 2 Python packages with version-specific URLs. Converted them to the more generic pypi.io URL format. Also confirmed that they can still be downloaded.

Fix version-specific URLs for Python packages

---

lib/spack/spack/platforms/cray.py
var/spack/repos/builtin/packages/pkg-config/package.py
var/spack/repos/builtin/packages/pkgconf/package.py

Was breaking on Cray machines because it did not include the cray
pkgconfig paths. This adds the same lines from pkg-config to pkgconf.
Apologies for the sin of copy pasted code but since it's only two lines I think it's okay.
I'm also not sure if we need to add AC_LOCAL_PATH as well. It works on Crays without it.

Fix pkgconf on Crays

---

var/spack/repos/builtin/packages/braker/package.py

BRAKER1_v1.11.tar.gz is moved to http://bioinf.uni-greifswald.de/augustus/binaries/old. Added list_url and list_depth to fix fetching problem.

braker: added list_url and list_depth

---

var/spack/repos/builtin/packages/mosh/package.py

I tried a test-build on a fairly minimal debian stretch and encountered that `mosh` depends on some `pkg-config` (also mentioned here: https://github.com/mobile-shell/mosh/wiki/Build-Instructions).

mosh build depends on pkg-config

---

var/spack/repos/builtin/packages/libsplash/package.py
var/spack/repos/builtin/packages/libsplash/root_cmake_1.7.0.patch

Fix installs as "root" user for the last libSplash release.
Missing quoting of string compares resulted in a CMake error when run as root (e.g. in a Docker build).
Reference: https://github.com/ComputationalRadiationPhysics/libSplash/pull/277

libSplash 1.7.0: Root Fix

---

var/spack/repos/builtin/packages/suite-sparse/package.py

The new `libs` property handles queries for any subset of the SuiteSparse libraries.

suite-sparse: add a package-specific 'libs' property

---

var/spack/repos/builtin/packages/mumps/package.py

The default behaviour of the `.libs` property is not appropriate for mumps.

mumps: add the libs property

---

var/spack/repos/builtin/packages/likwid/package.py

likwid uses the current directory when building the paths to its internal libraries. Spack overwrites `PWD`, causing likwid to not find `hwloc.h`.
Does it make sense to fix Spack to not overwrite `PWD`? I found at least one more package where this seems to be a problem (cp2k).

likwid: Fix build

---

lib/spack/spack/cmd/activate.py
var/spack/repos/builtin/packages/log4cxx/package.py

While installing `log4cxx` on a minimal ubuntu this patch was needed to make `log4cxx` build. Our current working hypothesis is that it worked previously because the systems `apr` was picked up automatically by configure.
I'm not sure whether this is a more wide-spread issue or not.

fix apr pick up of log4cxx

---

var/spack/repos/builtin/packages/sqlite/package.py

This commit adds sqlite 3.22.0 to the spack repository

Add sqlite 3.22.0

---

var/spack/repos/builtin/packages/cmor/package.py

This adds version `3.3.0` of package cmor and fixes a dependency issue. 
The dependency of hdf5 is changed because of a conflict it created together with the dependency of netcdf (which is also a dep for cmor). Before the change the dependency was like this: 
cmor depends on hdf5<1.8
cmor depends on netcdf
netcdf depends on hdf5>1.8.9
So this could not be resolved. The exact error was:
```
$ spack install cmor
==> Error: Invalid Version range: 1.8.9:1.8
```
I am not sure if my change is ok. Let me know. 
Also, the error message would be more helpful if it would include the package name. In this case it was easy to spot it, but in cases where there are lots of dependencies it may be trickier. I don't know if this is something worth looking into.

Add cmor version 3.3.0

---

var/spack/repos/builtin/packages/sosflow/package.py

SOSflow depends on MPI and pkg-config, but neither of these
dependencies are currently in the spack package, so this commit adds
them.

sosflow: add missing dependencies

---

var/spack/repos/builtin/packages/py-affine/package.py
var/spack/repos/builtin/packages/py-cligj/package.py
var/spack/repos/builtin/packages/py-rasterio/package.py
var/spack/repos/builtin/packages/py-snuggs/package.py

This is pretty straightforward.
If #2310 were fixed, then this PR (py-rasterio) could be improved.  If not, it is not dissimilar from other packages already in Spack.

py-rasterio: Added with dependencies.

---

var/spack/repos/builtin/packages/pkgconf/package.py

This is a copypaste from `pkg-config` package. Should also fix #7006 and related issues on Cray machines.

Setup dependent environment for pkgconf.

---

var/spack/repos/builtin/packages/geos/package.py

Add versions released after 3.5.0 (3.4.3, 3.5.1, and 3.6.x)

geos: add versions 3.4.3, 3.5.1, and 3.6.0 thru 3.6.2

---

var/spack/repos/builtin/packages/relion/package.py

Though per #6070 should this auto-detect hardware?  I still have to do:
```spack install relion@2.1+cuda cuda_arch=62```
Otherwise ```-DCUDA_ARCH``` will be used as cmake argument but contain no value.

Relion 2.1 - Now Using CudaPackage class 

---

var/spack/repos/builtin/packages/py-ase/package.py
var/spack/repos/builtin/packages/py-gpaw/package.py

Hi,
There is an existing PR for py-gpaw [#4554](https://github.com/spack/spack/pull/4554), but I did not notice it before I had already written an implementation of `py-gpaw`-package.
This implementation takes into account the various dependencies of GPAW. We have this version in production in our cluster environment.
This implementation has:
- variant for MPI
- variant for FFTW
- variant for ScaLAPACK
All of the combinations have been tested in practice with
```sh
mpirun -np 2 gpaw-python $(which gpaw) test
```
for MPI variant and
```sh
python $(which gpaw) test
```
for non-MPI variant.
The script is missing tests during installation as gpaw-setups would need to be loaded.
To test:
1. `git clone https://github.com/simo-tuomisto/spack.git`
2. `source spack/share/spack/setup-env.sh`
3. …

py-gpaw package with variants for MPI, FFTW and ScaLAPACK

---

lib/spack/spack/build_systems/cuda.py

CudaPackage is always used as a mixin. As such it should inherit from PackageBase, and not Package.

Changed CudaPackage base class to PackageBase

---

var/spack/repos/builtin/packages/exasp2/package.py

Generalized ExaSP2 Install to use glob due to changes in naming
convention between previous release and current development branch

Generalized ExaSP2 Install

---

var/spack/repos/builtin/packages/hoomd-blue/package.py

Updated hoomd-blue to latest tagged version v2.2.2 and added conflict for older versions only for gcc@6+
gcc@7+  are still not supported so added conflict for that also.

hoomd-blue version bump and compiler updated

---

var/spack/repos/builtin/packages/lua/package.py

This is needed when using system lua on RHEL and clones where lua is installed in /usr/lib64

Update the lua package to generate LUA_PATH and LUA_CPATH with lib and lib64 paths.

---

var/spack/repos/builtin/packages/boost/package.py

There became two additional releases available on [bintray](https://dl.bintray.com/boostorg/release).
Change to bintray for 1.64 and 1.63 as well since SF downloads are too instable.

Boost: More Bintray

---

lib/spack/spack/architecture.py

Potential fix for https://github.com/spack/spack/issues/7356
It appears that `OperatingSystem` should be careful to format the provided name, since it looks like that name may contain a `-` (which is used by `ArchSpec` to delineate between platform, os, and target), for example if the `distname` reported by `external.distro.linux_distribution` (as used in `LinuxDistro`) contains a `-` (I should say I'm not 100% sure if `external.distro.linux_distribution` allows `-` but a cursory glance suggests it may be possible).

replace dash with underscore in os name

---

lib/spack/spack/stage.py

This seems to fix an issue with the rubygems ssl cert resource on the ruby package #7130 
Tested lua and git which also both have resources, and those still seem to work as expected.

resource: fixing a problem with shutil.move and symlinks to dirs

---

lib/spack/spack/binary_distribution.py
lib/spack/spack/cmd/buildcache.py
lib/spack/spack/package.py
lib/spack/spack/test/packaging.py

buildcache command add options
Add create -u --unsigned option to replace -y --yes_to_all to allow tests on macOS when gpg2 is unavailable.
Add keys -t --trust option to replace -y yes_to_all to allow installation of all downloaded keys.

spack buildcache command : add options for testing with unsigned tarballs on macOS

---

lib/spack/llnl/util/lang.py
lib/spack/spack/test/concretize.py

fixes #7239 
fixes #7452
@jrood-nrel @goxberry

Constructing a SpecBuildInterface from another gives no inconsistent MRO

---

lib/spack/spack/cmd/dependencies.py
lib/spack/spack/graph.py
lib/spack/spack/package.py

`spack dependencies --transitive` was not working properly.  
- transitive dependencies were not being handled correctly
- restructure code to do recursion and mark visited packages properly

Fix bugs in `spack dependencies` command

---

var/spack/repos/builtin/packages/tcl/package.py
var/spack/repos/builtin/packages/tk/package.py

This PR makes the `tcl` package extendable just like any other scripting language provided by the Spack builtin repo. I was initially thinking about adding a `TclPackage` mixin class (just like `CudaPackage`) but the resulting type would have been too minimal to justify a core change (imho, seeking advice from @tgamblin @alalazo here):
```python
class TclPackage(Package):
extends('tcl')
```

Treat tcl as extendable

---

var/spack/repos/builtin/packages/intel-tbb/package.py

Adds a `shared` variant to intel-tbb, which defaults to True
When `~shared`, uses `extra_inc=big_iron.inc` to create static libraries.

add an option to build tbb statically

---

var/spack/repos/builtin/packages/llvm/package.py

Relase notes: http://releases.llvm.org/6.0.0/docs/ReleaseNotes.html
**Before merge!!!**
For automation, I wrote a really simply bash script (~~fix for linux `md5sum` pending when i switch to that computer~~ fixed, i forgot i already wrote the platform dependent md5 stuff somewhere else xD).  I was thinking of adding a `# NOTE` comment just above `releases`
https://github.com/spack/spack/blob/39bfa12f22b56cd35340bedd92f262ba05f9e125/var/spack/repos/builtin/packages/llvm/package.py#L165
Saying something like
```py
```
and then just include the script at the bottom.  I couldn't figure out how to make `spack checksum` work...
```bash
#!/usr/bin/env bash
VERSION="6.0.0"
if ! [[ -f "llvm-$VERSION.src.tar.xz" ]]; then
curl -LO "http://releases.llvm.org/$VERSION/llvm-$VERSION.src.tar.xz"
fi
if ! …
```

llvm 6.0.0 released as stable

---

var/spack/repos/builtin/packages/mscgen/package.py

Mscgen is a small program that parses Message Sequence Chart descriptions and produces PNG, SVG, EPS or server side image maps (ismaps) as the output.
See http://www.mcternan.me.uk/mscgen/.

Provide new package: mscgen.

---

var/spack/repos/builtin/packages/xterm/package.py

The original URL does not work anymore.

Xterm: Fix URL

---

var/spack/repos/builtin/packages/cube/package.py
var/spack/repos/builtin/packages/cube/qt-version.patch

cube's configure only recognizes qt versions with single digit version components and breaks with qt 5.10. Patch the configure files directly to avoid having to regenerate them.

cube: Fix qt detection

---

var/spack/repos/builtin/packages/nasm/package.py

Add latest version of nasm

---

var/spack/repos/builtin/packages/libjpeg/package.py

Add latest version of libjpeg

---

var/spack/repos/builtin/packages/libjpeg-turbo/package.py

Add latest version of libjpeg-turbo

---

var/spack/repos/builtin/packages/glpk/package.py

Add latest version of GLPK

---

var/spack/repos/builtin/packages/suite-sparse/package.py

Add latest version of SuiteSparse

---

var/spack/repos/builtin/packages/pocl/package.py

It seems there has been a change in concretization that resulted in a request for a llvm latest (5.0.1) while not satisfying the later more precise request for a version.
Remove the first line and only rely on the last.
Proposed fix for concretion error reported in #7460

pocl: fix spec

---

var/spack/repos/builtin/packages/py-setuptools/package.py

Newer versions of `py-setuptools` no longer require any dependencies, they are once again vendored.

Add latest version of py-setuptools

---

var/spack/repos/builtin/packages/pkg-config/package.py
var/spack/repos/builtin/packages/pkgconf/package.py

https://github.com/spack/spack/pull/7171 and https://github.com/spack/spack/pull/7102 were both merged recently and duplicate some logic to update `PKG_CONFIG_PATH` on the cray platform.
Based on the feedback in #7171 this keeps the cray-specific `PKG_CONFIG_PATH` modifications in the `Cray` platform definition but keeps the `ACLOCAL` modification for `pkgconf` from #7102.
@skosukhin @mamelara @alalazo

Fixed duplicated handling of PKG_CONFIG_PATH for crays

---

var/spack/repos/builtin/packages/py-pygobject/package.py
var/spack/repos/builtin/packages/py-pygtk/package.py

I tried a test-build on a fairly minimal Debian Stretch (minimal + packages `git-core, curl, ca-certificates, python, procps, gcc, g++, file, make, patch, libc6-dev, xz-utils, lbzip2, sudo, ssh, unzip`) and encountered that `py-py{gobjects,gtk}` depend on `pkg-config`.

py-py{gobject,gtk} require pkgconfig for build

---

var/spack/repos/builtin/packages/scotch/package.py

The restrict compilation option with icc causes deadlock when multithreading is used. This issue has already been reported to the Scotch development team, but for current versions it is more reliable not to use the restrict compilation option.

scotch%intel: remove restrict

---

var/spack/repos/builtin/packages/intel-xed/package.py

This patch adds the 'intel-xed' package, the Intel X86 Encoder Decoder
library for encoding and decoding x86 machine instructions.
XED was previously closed source inside Intel, but is now available on
GitHub (yeah!) at github.com/intelxed.
XED homepage: https://intelxed.github.io/
There is one small point I was unsure how to do.  XED only runs on
x86.  It won't even build on powerpc.
I'm guessing you'd want to handle this by adding a conflict().
I want to say, conflict('arch != x86'), but I was unsure of the
correct syntax for that.
This is probably a 1-line change, if someone can show me what the
correct spec for that is.
Mark Krentel

intel-xed: new package

---

var/spack/repos/builtin/packages/elfutils/package.py

Elfutils doesn't build with clang because it uses nested functions in C, which is implemented in gcc, but not in clang.

elfutils: document conflict with clang

---

lib/spack/spack/util/crypto.py

FIPS-compliant machines reject md5 hashing by default
On some systems, the `hashlib` library for python has a `usedforsecurity` option. This attempts to set that as `False` where possible to make use of `md5` hashes but also prints a warning (the goal being that a package installer can add a PR to update the checksums for the packages they build).

Support MD5 with a warning when OpenSSL is compiled in FIPS mode

---

var/spack/repos/builtin/packages/openmpi/package.py

note the libmpi.so itself didn't have changes, only other
components of the package had updates.

Open MPI: add 2.1.3

---

var/spack/repos/builtin/packages/trilinos/package.py

I saw the same behavior as in https://github.com/spack/spack/pull/7224 for Trilinos so I changed a `prefix.lib` to `self.prefix.lib` and it seems to allow me to refresh modules for Trilinos correctly.

Using self.prefix in Trilinos to avoid global name prefix undefined bug

---

var/spack/repos/builtin/packages/pandaseq/package.py

found more dependencies when trying to install in a clean container
should be the same as #7031 - will see if CI passes on this one

pandaseq: needs bzip and libtool as link

---

lib/spack/spack/cmd/mirror.py
lib/spack/spack/concretize.py
lib/spack/spack/test/concretize.py

Fixes #5147
When creating a mirror with ```spack mirror create <spec>``` the spec should be able to specify compilers and operating systems that don't exist on the current system. This disables compiler existence checks for ```spack mirror create```.

Enable creation of mirrors for systems with different compilers

---

var/spack/repos/builtin/packages/jchronoss/package.py

JCHRONOSS is a validation process, designed to scale in HPC environments, to increase time to test result.
This tool is aware of cluster users & admins, to adapt the workload according to needs, to keep in mind the shortest time between coding and validating step.
The software is compliant with batch managers like SLURM or Torque and can produce multiple output format (JSON, JUNIT, YAML,...) that can then be directly uploaded in any reporting platform (like Jenkins). When people can't have a fully-integrated reviewing interface, JCHRONOSS provides a lightweight result viewer, to check results trends without leaving the cluster.
You can find Doxygen-based documentation and more information on the website: [http://jchronoss.hpcframework.com](http://jchronoss.hpcframework.com)
Please let me …

New Package: jchronoss

---

var/spack/repos/builtin/packages/py-pybedtools/package.py

Trying to install metasv, which depends on this version.
Pypi says the hash is different than what's listed in this package.py :
https://pypi.python.org/pypi/pybedtools/0.6.9
@peetsv - I see you just recently added this older version for the same reason (metasv) - would like you to review before this is merged.

py-pybedtools: fix hash for 0.6.9

---

var/spack/repos/builtin/packages/libxi/package.py

* `pkgconfig` is needed by the package's build flow
*  `fixesproto` is a transient dependency which cannot be found via `libxfixes` (?)

libXi requires pkgconfig and fixesproto

---

lib/spack/spack/concretize.py
lib/spack/spack/test/concretize.py

Currently, if you request a non-default architecture, that only applies to the root spec where it was specified. This PR changes that behavior to propagate the architecture change down the dag (in the same way that we propagate compilers to maintain ABI compatibility).
This fixes a bug reported out of channel by Anthony Agelastos, whose github handle I don't know.

Propagate architecture information during concretization

---

lib/spack/spack/package.py

fixes #7543
This is very likely an hot-fix, while a more permanent solution is needed. See this comment for more insight:
https://github.com/spack/spack/pull/7193#discussion_r176448831
on the problem.

Recover the old patching order for packages.

---

lib/spack/llnl/util/lang.py
lib/spack/spack/cmd/find.py
lib/spack/spack/database.py
lib/spack/spack/test/cmd/find.py
lib/spack/spack/test/database.py
lib/spack/spack/test/llnl/util/lang.py

Information on the date and time of installation of a spec is recorded into the database. The information is retained on reindexing. The DB can now be queried for specs that have been installed in a given time window. This query possibility is exposed to command line via two new options of the `find` command.
With the following command:
```console
$ spack install  hdf5~mpi~cxx~fortran
```
you'll generate a database that contains date and time information. Now you can query from command line based on date and time of installation:
```console
$ spack find
==> 2 installed packages.
-- linux-ubuntu14.04-x86_64 / gcc@4.8 ---------------------------
hdf5@1.10.1  zlib@1.2.11
$ spack find --start-date="2019"
==> 0 installed packages.
$ spack find --start-date="2 days ago" 
==> 1 installed …
```

Record installation date and time in DB

---

var/spack/repos/builtin/packages/isl/package.py

Builds and passes all tests on macOS 10.13.3 with Clang 9.0.0.

Add latest version of ISL

---

var/spack/repos/builtin/packages/mpc/package.py

Builds and passes all tests on macOS 10.13.3 with Clang 9.0.0.

Add latest version of MPC

---

var/spack/repos/builtin/packages/nwchem/package.py

Used names with __ in class level constructs to avoid rebinding
fixes #3129

nwchem: fixed accidental rebinding or `url` name at class level

---

var/spack/repos/builtin/packages/llvm/package.py

LLVM + LLDB requires py-six. we also need to specify that we want to use the Spack-installed py-six, rather than have lldb use its own version. (this replaces my backwards merge in #7052).

llvm+python +lldbdepnds on py-six

---

var/spack/repos/builtin/packages/giflib/bsd-head.patch
var/spack/repos/builtin/packages/giflib/package.py

Contributed this patch upstream to the developers. We'll see what they say.
With this patch, unit tests pass on macOS 10.13.3 and CentOS 6.9.

Fix giflib unit tests on macOS/BSD

---

var/spack/repos/builtin/packages/py-cvxopt/package.py

Adds a package for the `cvxopt` convex optimization solver. Passes all tests with and without optional dependencies on macOS 10.13.3 with Clang 9.0.0.
I didn't add a package for Mosek because it's proprietary and I couldn't figure out how to get it to build. Conda builds Mosek, so it should be doable. Can anyone find Conda's build recipe for Mosek?
Depends on #7526 (which has now been merged).

Add py-cvxopt package

---

var/spack/repos/builtin/packages/dyninst/package.py

Not sure if there's a nice way to specify a single git URL, rather than have the same one per version...

Dyninst links broken, everything switched to github

---

var/spack/repos/builtin/packages/tcl/package.py

Fix `tclsh` command found in transitive dependencies' environment. The issue was exactly the same as #7128 but for Tcl and due to human (mine) error this time.

Fix tclsh command for transitive dependencies

---

etc/spack/defaults/config.yaml
lib/spack/spack/spec.py
lib/spack/spack/test/directory_layout.py
lib/spack/spack/test/spec_semantics.py

I think this is a nice change to have. You can create directories separated based off of operating system, target and platform. Helpful for HPC support teams and certainly helpful to NERSC.

Add the ability to separate architecture in path scheme

---

lib/spack/spack/operating_systems/cnl.py

Previously we defaulted all Cray OS versions to 10.
Part of my work with @mamelara to upstream as much as possible of his NERSC-specific logic.

Grab Cray os version from PrgEnv module versions

---

lib/spack/spack/__init__.py

We've been forgetting to increment Spack's internal version. We should probably push this to the last couple of release branches as well.

Increment Spack version

---

lib/spack/spack/platforms/cray.py
lib/spack/spack/util/module_cmd.py

Unload modules cray-mpich, darshan, and cray-libsci from the environment. This prevents any silent linking of mpich and cray-libsci. Also for compilation, it is recommended that darshan be unloaded.

Cray clean environment

---

lib/spack/spack/repository.py

This further reduces startup time from #7585.  Spack was making many calls to `stat()` at startup, causing the command to run very slowly.
- FastPackageChecker was being called at startup every time Spack runs,
which takes a long time on networked filesystems.  Startup was taking
5-7 seconds due to this call.
- The checker was intended to avaoid importing all packages (which is
really expensive) when all it needs is to stat them.  So it's only
"fast" for parts of the code that *need* it.
- This commit makes repositories instantiate the checker lazily, so it's
only constructed when needed.
`strace` of `spack python -c 'exit()'`:
before (up to 5-8s if files fell out of NFS cache):
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- …
```

Avoid stat-ing all packages at startup.

---

var/spack/repos/builtin/packages/python/package.py

Enable default optimizations for production builds. Uses `--with-icc` if built with Intel compilers.

python: updated versions + enable default optimizations

---

var/spack/repos/builtin/packages/openssl/package.py

Spack's openssl package is currently a bit useless because it can not verify any certificates. This PR adds a `system-certs` variant that symlinks the system certificates into the package.

openssl: Add variant to use system certificates

---

var/spack/repos/builtin/packages/zeromq/package.py

pkg-config is also required for release versions.

zeromq: fix build

---

var/spack/repos/builtin/packages/openmpi/package.py

This commit intents to:
1. Remove `pmi` from the `fabrics` list since Process Manager Interface is not a fabric.
2. Add configuration flags `--with-slurm --with-pmi` for OpenMPI (>1.5.4) when `schedulers=slurm` is specified.

Remove pmi from the fabric list.

---

var/spack/repos/builtin/packages/vim/package.py

This seems to be the minimal set of X-related libraries needed for vim+x build (btw. vim's `configure` step does NOT break if `--with-x` is specified but no X libs are found).

Add missing X-libs dependencies to vim+x

---

lib/spack/spack/binary_distribution.py

Since placeholders are always used when creating new buildcaches, the placeholder must be replaced even if old and new install path are the same.

Always relocate buildcaches unless they were created with relative paths.

---

var/spack/repos/builtin/packages/catch/package.py

Catch v1 and v2 are maintained independently since v2 requires C++11
support. Updating both to the latest.

[new versions] Add Catch v2.2.1 and v1.12.1

---

var/spack/repos/builtin/packages/openmpi/package.py

More details are in commits short description. 
The last commit might be controversial. In case people disagree on removing `mpirun` and `mpiexec` links to avoid conflicts with `srun` if `slurm` is the scheduler I'll delete it from the PR.

openmpi: updated package

---

var/spack/repos/builtin/packages/bohrium/package.py

- Add most recent Bohrium version.
- Change proxy parameter default to `False` to resemble the defaults used upstream.

Add recent bohrium version

---

var/spack/repos/builtin/packages/scons/package.py

Fixes #7613. @ch741
@alalazo @lee218llnl @tgamblin we might have a problem on our hands. The once venerable https://pypi.io links are no longer working for the SCons package. There is currently no evidence that this affects any other Python package, but we might need to consider alternative download methods in the future. This may require #2718. If done correctly, a `PyPIFetchStrategy` could also allow us to hook into `spack versions` and provide a list of available versions.
Also added the latest version of SCons. It looks like they finally support Python 3. Successfully installed with Python 3.6.4 and Clang 9.0.0 on macOS 10.13.3.

Fix download URL for SCons and add latest version

---

lib/spack/docs/mirrors.rst

Use `$HOME` for cli commands in `mirrors.yaml` and add "username" example strings in the file itself.
Fix #7628

mirrors.yaml: does not expand ~

---

var/spack/repos/builtin/packages/tut/package.py
var/spack/repos/builtin/packages/tut/python3-octal.patch

When building `tut` with Python 3, I see the following error message:
```
File "waftools/gcov.py", line 16
os.chmod(wrapper.name, 0777)
^
SyntaxError: invalid token
```
In Python 2, integers that start with a leading 0 are interpreted as octals. In Python 3, this is not the case, and the number must start with 0o or else it will be a SyntaxError. This patch allows me to build `tut` with Python 3. I also confirmed that it still works for Python 2. All build tests pass.
I submitted this patch upstream as well: https://github.com/mrzechonek/tut-framework/pull/15

Fix Python3 bug in tut

---

var/spack/repos/builtin/packages/mumps/package.py

* Fix a bug when checking for 'xl' or 'xl_r' compiler.
* Add support for parallel build - the 's', 'c', 'd', and 'z' targets
are build separately allowing parallel builds.
* When build '+shared', inject all dependencies into the link lines of
the mumps libraries.
* Run the examples only when installing with the '--test' Spack option.
This should resolve #3006. The issue in #7309 seems to not be resolved.
Note: there is no list of maintainers in the package, so I'm not sure who to cc here.

[MUMPS] Various improvements in the package

---

lib/spack/llnl/util/filesystem.py
lib/spack/spack/package.py
lib/spack/spack/spec.py
lib/spack/spack/test/database.py

This bug was first reported by @muffgaga in https://github.com/spack/spack/pull/7611#discussion_r177663583. This PR implements his suggested fix.
The problem is that the default libs handler always added `lib` to the start of the package name, even when the package name already started with `lib`. This would result in `spec['libiconv'].libs` searching for `liblibiconv.so`. The solution is to only add `lib` when the package name doesn't start with `lib`.

Avoid double 'lib' for packages whose name already starts with lib

---

var/spack/repos/builtin/packages/kokkos/package.py

Current versions of kokkos cannot build with hwloc v2.x due to changes in the associated structs. Requiring v1.11.9 for the time being until it becomes clear what the kokkos model for support will be.

Current versions of kokkos conflict with hwloc 2.x

---

lib/spack/spack/test/llnl/util/file_list.py

Okay, I have no idea why I'm the only one who seems to have encountered this bug, but I can reliably reproduce it with Python 3.6.4 on macOS 10.13.3 and with Python 2.7.13 on CentOS 6.9.
I decided to run the full test suite today for the first time in a long time and discovered that the `test_find_with_globbing` unit test doesn't pass for me. After closer inspection, my `matches` and `expected` look like:
```
Matches:  ['/Users/Adam/spack/lib/spack/spack/test/data/directory_search/a/foobar.txt', '/Users/Adam/spack/lib/spack/spack/test/data/directory_search/c/bar.txt', '/Users/Adam/spack/lib/spack/spack/test/data/directory_search/b/bar.txp']
Expected: ['/Users/Adam/spack/lib/spack/spack/test/data/directory_search/a/foobar.txt', '/Users/Adam/spack/lib/spack/spack/test/data/directory_search/b …
```

Fix bug in test_find_with_globbing unit test

---

lib/spack/spack/cmd/view.py

Makes `view` operate on `[Spec, ...]` instead of `[str, ...]`. Should fix #7548. 
We use this patch in production and I simply forgot to bring it upstream, cc: @obreitwi

make view understand hashes

---

var/spack/repos/builtin/packages/xerces-c/package.py

The build requires libiconv (but still it doesn't find it when not providing LDFLAGS).
Regarding the LDFLAGS: A patch to the configure flow would be the better solution…

Fix build of xerces-c

---

var/spack/repos/builtin/packages/catch/package.py

Add a proper install variant for Catch(2) that installs a CMake config package, https://github.com/catchorg/Catch2/pull/1170.
This allows to use Catch2 downstram with `pkg-config` and CMake's `find_package(Catch2)` commands via standard environment hints such as `CMAKE_PREFIX_PATH`.

Catch2: CMake Config Package

---

var/spack/repos/builtin/packages/gcc/package.py

Fixes #7689.
@gozwei Can you test this? It should fix your `gcc%clang` problems. I'm not sure if it will fix your `gcc%gcc` problems, but `%gcc` never works great on macOS.
This PR extends the patch added in #5647 to other recent versions of GCC. This patch is also used by [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb#L57,L65). According to the [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81797), this patch is likely necessary for older versions of GCC as well, so we may need to expand this range in the future. It has been fixed upstream for GCC 6.5, 7.4, and 8.1.
Confirmed that the patch applies to GCC 6.1, 6.4, and 7.3. Confirmed that the installation succeeds for GCC 7.3 on macOS 10.13.3 with Clang 9.0.0. I didn't get around to testing …

Fix GCC 6/7 build on APFS

---

var/spack/repos/builtin/packages/go-bootstrap/package.py
var/spack/repos/builtin/packages/go/package.py

Also update go-bootstrap to the 20171003 snapshot.

go: Update to 1.10.1

---

lib/spack/spack/package.py
lib/spack/spack/test/concretize.py

fixes #7705
`Package.provides` now checks constraints to ensure that a spec provides a given virtual package. Note that `strict=True` is not passed to satisfies as this function is also used during concretization.

Package.provides accounts for v deps that are provided conditionally

---

share/spack/qa/run-unit-tests

fixes #7593
Unit tests on OSX are trying to concretize `mpileaks`, and they fail due to a conflict in the package:
```console
"%gcc@7.2.0:" conflicts with "elfutils@0.163"
```
This solves the issue asking explicitly to concretize against `elfutils@1.170`

Fixes conflicts in OSX nightly tests

---

var/spack/repos/builtin/packages/mesa-glu/package.py
var/spack/repos/builtin/packages/openglu/package.py

In the spirit of #6551, add a `glu` virtual package:
* openglu: add package, provides glu, external-only
* mesa-glu: now provides 'glu' (GL Utility library)
This virtual package is needed for libraries like GLVis (https://github.com/LLNL/glvis) that need to link to GLU.

glu: new virtual package; openglu: new package

---

var/spack/repos/builtin/packages/py-kiwisolver/package.py
var/spack/repos/builtin/packages/py-matplotlib/package.py

kiwisolver is a required dependency as of [2.2.0](https://github.com/matplotlib/matplotlib/releases/tag/v2.2.0)
This only turns up when actually trying to import matplotlib... Build goes through without and their dependency management is abyssal... (read: I gave up trying to understand it)

Add missing dependency to py-matplotlib

---

var/spack/repos/builtin/packages/libfabric/package.py

Making the latest stable version of libfabric (v1.6) the default version, bumping up the bugfix version of the 1.5 series, and adding the TCP and SHM core providers.

libfabric: Version bumps and provider additions

---

lib/spack/spack/directives.py

Popping the when spec from kwargs in the extends directive breaks
class inheritance. Inheriting classes do not find their when spec.
We now get the when spec from kwargs instead, leaving it to be found
by any downstream package classes.
As an example suppose two packages foo and bar
```
$ cat foo/package.py
...
class Foo(Package):
...
variant('python', default=False, description="")
extends('python', when='+python')
...
$ cat bar/package.py
...
class Bar(Foo):
...
$ spack spec foo
Input spec
foo
Concretized
foo@1.2.11%clang@6.1~python arch=darwin-sierra-x86_64 
$ spack spec bar
Input spec
bar
Concretized
bar@1.2.11%clang@6.1~python arch=darwin-sierra-x86_64 …
```

Fix when_spec inheritance for extensions

---

lib/spack/docs/getting_started.rst

Discourage users from putting `paths:` in their `packages.yaml` to avoid problems with the cray programming environment and compiler wrapper.

cray: add comment about module use in packages.yaml

---

lib/spack/spack/cmd/__init__.py
lib/spack/spack/cmd/providers.py
lib/spack/spack/test/cmd/providers.py

fixes #1355
`spack providers` now outputs a sensible error message if non-virtual specs are provided as arguments:
```console
$ spack providers zlib
==> Error: non-virtual specs cannot be part of the query [zlib]
Virtual packages:
D, awk, blas, daal, elf, gl, glu, golang, ipp, java, jpeg, lapack, mkl, mpe, mpi, opencl, openfoam, pil, pkgconfig, scalapack, szip, tbb
```
Formatting of the output changed slightly:
```console
$ spack providers mpi lapack
mpi:
intel-mpi  intel-parallel-studio  mpich  mpich@1:  mpich@3:  mvapich2  openmpi  openmpi@1.6.5  openmpi@1.7.5:  openmpi@2.0.0:  spectrum-mpi
lapack:
atlas  intel-mkl  intel-parallel-studio  netlib-lapack  openblas  veclibfort
```
Calling the command without arguments prints the list of valid virtual packages:
```console
$ spack providers …
```

Better error message for spack providers

---

lib/spack/spack/cmd/activate.py

Activating a package that is already activated now sends a `tty.msg`
and returns.
```
-bash-4.2$ ~/spack/bin/spack activate aspell6-en
==> Package aspell6-en/lc4v24f is already activated.
```
~TODO: I'm not sure if a naked `return` is sufficient or if I should return a particular value?~
Closes #7750

Activation of activated package just msg's

---

share/spack/spack-completion.bash

We no longer have to manually update the list of Spack providers in our autocompletion scripts thanks to @alalazo's #7748.

Autocomplete spack providers

---

var/spack/repos/builtin/packages/adios/package.py
var/spack/repos/builtin/packages/sz/package.py

ADIOS 1.13.1 fixes several issues with zero-sized block reading and writing when compression transports are used.
SZ 1.4.12.3 is used in the latest ADIOS release.
cc @pnorbert

ADIOS 1.13.1 & SZ 1.4.12.3

---

var/spack/repos/builtin/packages/xrandr/package.py

Without this dependency I get:
``` 
82    configure: error: Package requirements (xrandr >= 1.5 xrender x11 xproto >= 7.0.17) were not met:
83
84    Package 'randrproto', required by 'xrandr', not found
```

xrandr: needs randrproto

---

lib/spack/spack/cmd/common/arguments.py
lib/spack/spack/cmd/diy.py
lib/spack/spack/cmd/install.py

It seems that #5043 is currently stalled which was the primary location changes from #2771 were supposed to go.
Rather than continue this, I've made a new PR with these changes adopted to the current `develop` branch.
Once this is merged, I'll close #2771.

Add -d option to diy to specify source path move -j to common args

---

var/spack/repos/builtin/packages/glew/package.py

glew was looking for opengl dependencies, but no dependency for opengl listed. Since we have a gl provider now, adding that.
guessing this just worked against system opengl previously

glew: adding gl dependency

---

var/spack/repos/builtin/packages/suite-sparse/graphblas_libm_dep.patch
var/spack/repos/builtin/packages/suite-sparse/package.py

+ I am unable to build `suite-sparse@5.2.0` with `clang@6.0.0`.  The build fails with the error:
```
2397    [ 99%] Linking C executable wildtype_demo
2398    make[4]: Leaving directory
`/tmp/spack-stage/spack-stage-w0XYhK/SuiteSparse/GraphBLAS/build'
>> 2399    libgraphblas.so.2.0.1: undefined reference to `__fpclassify'
>> 2400    clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
>> 2401    make[4]: *** [wildtype_demo] Error 1
```
+ This error appears because libgraphblas.so requires `-lm`, but that link dependency is not explicitly listed in `GraphBLAS\CMakeLists.txt.`
+ A patch file is provided to add this dependency.  The patch is only applied when the compiler is `%clang`.

Suite-sparse: provide patch to fix builts with clang@6.0.0.

---

var/spack/repos/builtin/packages/freetype/package.py

Headers are a level deeper than usual, and dependent wasn't finding them until I added this.
I'm a little confused why this hasn't been an issue with other dependents, so if I need to adjust for this in the dependent package instead, let me know.

freetype: adding subdir to cpath for deps

---

var/spack/repos/builtin/packages/libxml2/package.py

Like the change for freetype #7818 , headers are a level deeper than usual, and dependent wasn't finding them until I added this.
I'm a little confused why this hasn't been an issue with other dependents, so if I need to adjust for this in the dependent package instead, let me know.

libxml2: adding subdir to cpath for deps

---

var/spack/repos/builtin/packages/openpmd-api/package.py

Add a new package for openPMD-api.
openPMD is a meta-data standard (markup, schema) for hierarchical, scientific particle and mesh based data.
openPMD-api is a library wrapping the underlying backends ([HDF5](hierarchical), [ADIOS](https://github.com/ornladios/ADIOS), ...) into a single, object-aware API.
* Repository: https://github.com/openPMD/openPMD-api
* Project: https://github.com/openPMD http://www.openPMD.org

openPMD-api

---

var/spack/repos/builtin/packages/mono/package.py

Add a new version 5.4.1.7 for mono which has been built successfully against GCC 5.4.0.

Add a new version 5.4.1.7 for mono.

---

var/spack/repos/builtin/packages/hypre/package.py
var/spack/repos/builtin/packages/petsc/package.py
var/spack/repos/builtin/packages/slepc/package.py

~~keep 3.8.x as preferred as 3.9.0 does not build on macOS (did not test Linux)~~

petsc and slepc: add 3.9.0

---

share/spack/setup-env.sh

Fix `spack load` with extended packet specifications that include spaces.
Solved by using perfect parameter forwarding via temporary array.
To be consistent with the current used shell features in `setup-env.sh` this PR is **not** compatible with the `dash` shell (there are no arrays in `dash`). PR #4048 is adding `dash` compatibility. To be `dash` shell compatible the usage of the temporary array `_sp_spec` must be removed and `"${_sp_spec[@]}"` must be substituted with `"$@"`.
```
$ spack install zlib
$ spack install zlib cppflags='-O3 -march=native'
$ spack install zlib cppflags='-O2 -march=native'
$ spack find -d -L -f zlib
==> 3 installed packages.
-- linux-linuxmint18-x86_64 / gcc@5.4.0 -------------------------
k5hg4kkxiutkfl6n53ogz5wnlbdrsdtf    zlib@1.2.11%gcc …
```

environment shell: fix `spack load`

---

var/spack/repos/builtin/packages/openmpi/package.py

MPI_THREAD_MULTIPLE support changed in Open MPI 3.0.

Openmpi update multithread

---

var/spack/repos/builtin/packages/libnl/package.py

New package, based on #6978 and #4168
The comments in #4168 addressed questions around which repo is canonical - seems there was consensus on using the thom311/libnl github repo.

libnl: new package

---

var/spack/repos/builtin/packages/ucx/package.py

breaking up #6978 
depends on #7835

ucx: needs numactl and rdma-core

---

var/spack/repos/builtin/packages/libfabric/package.py

Based on #6978 
Adding one new fabric, and removing one very old one.
Adding dependencies that exist in spack.  Anyone currently using this was using system libraries, and can continue to do so via setting dependencies to continue to use system libs via packages.yaml

Libfabric: updating fabrics & adding deps

---

var/spack/repos/builtin/packages/openmpi/package.py

This separates the changes for openmpi from #6978 and integrates with latest changes from develop.

openmpi: libfabric support, ucx cleanup

---

var/spack/repos/builtin/packages/kokkos/package.py

Fixes #7888
Added OpenMP variant for kokkos that can be disabled to build and test
on platforms where OpenMP is not available or desired. Also updated
version list

Added OpenMP Variant for Kokkos

---

var/spack/repos/builtin/packages/adol-c/package.py

importantly, also prevent from picking up system boost.
proofs:
```
$ otool -L /Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/adol-c-2.6.3-oaah6ba3w3jwxtld5we3krrbuuljgkj7/lib64/libadolc.dylib
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/adol-c-2.6.3-oaah6ba3w3jwxtld5we3krrbuuljgkj7/lib64/libadolc.dylib:
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/adol-c-2.6.3-oaah6ba3w3jwxtld5we3krrbuuljgkj7/lib64/libadolc.2.dylib (compatibility version 4.0.0, current version 4.0.0)
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/boost-1.67.0.b1-wi73ssw4tozdvzykmqopq7k5dhl2pfr6/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib …
```

adol-c: add boost optional dependency

---

var/spack/repos/builtin/packages/mfem/package.py

This commit fixes #7900.
In short: in the absence of constraints to the contrary, spack will
download the preferred version of a package, which is usually the most
recent non-develop version. On a clean spack installation without
hypre installed, `spack install mfem` will download hypre 2.14.0,
which is API-incompatible with mfem 3.3.2 (and earlier versions of
mfem), so spack will throw compiler errors re: the API mismatch.
This commit fixes that error by restricting mfem release versions
3.3.2 and earlier to hypre version 2.10.0 to 2.13.999 (only 2.13.0
currently exists, but if it has a non-2.14.x maintenance release,
these versions of hypre should also be permitted).

mfem: add valid range of hypre version numbers

---

var/spack/repos/builtin/packages/gdbm/package.py

A funny story, actually.
Tired of strange warnings that Spack generated each time I installed `gdbm`, I decided to figure out what was the reason for them. The warnings were the following:
```
==> Installing gdbm
==> Warning: Suspicious requests to set or unset 'CC' found
==> Warning:            env.set('CC', join_path(link_dir, compiler.link_paths['cc'])) at /scratch/local1/spack/lib/spack/spack/build_environment.py:146
==> Warning:    --->    spack_env.set('CC', spack_cc) at /scratch/local1/spack/var/spack/repos/builtin/packages/gdbm/package.py:49
```
The strange thing about these warnings is that the two referenced lines of code do the same thing: they set `CC` to Spack's wrapper. Setting `CC` in the package script is redundant, isn't it? But why did this line appear in the code?
This …

Package 'gdbm': do not set CC.

---

lib/spack/spack/test/url_parse.py
lib/spack/spack/url.py
var/spack/repos/builtin/packages/busco/package.py
var/spack/repos/builtin/packages/hacckernels/package.py
var/spack/repos/builtin/packages/icet/package.py
var/spack/repos/builtin/packages/libaec/package.py
var/spack/repos/builtin/packages/parsplice/package.py
var/spack/repos/builtin/packages/swfft/package.py
var/spack/repos/builtin/packages/swiftsim/package.py
var/spack/repos/builtin/packages/vecgeom/package.py
var/spack/repos/builtin/packages/vtkm/package.py

Currently, Spack recognises a URL that leads to a git snapshot with a given tag:
`https://gitlab*/project/name/repository/archive.tar.gz?ref=v1.0.0`
Such URLs are not GitLab API endpoints and their stability is not guaranteed. For example, they were unintentionally broken in GitLab 10.7. Although they will be fixed in GitLab 10.7.1, the developers [recommend switching to API URLs](https://gitlab.com/gitlab-org/gitlab-ce/issues/45586), which look like:
`https://gitlab*/api/v4/projects/project%2Fname/repository/archive.tar.gz?sha=v1.0.0`
With this PR Spack will be able to recognise GitLab API URLs and make correct version substitution in them.

Use GitLab's API endpoint for fetching a git snapshot.

---

lib/spack/spack/test/versions.py
lib/spack/spack/version.py

Simple addition to avoid having to type `len(version.version)` to check the number of components a version has, with test.
Use case:  
```python
def url_for_version(self, version):
url = 'https://github.com/01org/tbb/archive/{0}.tar.gz'
if (version[0] >= 2017) and len(version) > 1:
return url.format('{0}_U{1}'.format(version[0], version[1]))
else:
return url.format(version)
```
Currently, `len(version.version)` must be used instead.

Allow len(Version) to return number of split components.

---

var/spack/repos/builtin/packages/xrootd/package.py
var/spack/repos/builtin/packages/xrootd/python-support.patch

Add configurable HTTP, Python and readline support.
Add previously missing dependencies.
Minor patch to improve Python support (see https://github.com/xrootd/xrootd/pull/695).

Update xrootd with recent versions through 4.8.3 and add variants.

---

var/spack/repos/builtin/packages/eospac/flang.patch
var/spack/repos/builtin/packages/eospac/package.py

When building eospac with `%clang`, spack's Fortran compiler wrapper is called 'flang', which is rejected by the eospac build system. Allow compilation with `%clang` by patching the eospac build system.
My testing only covers `%clang` where flang is actually gfortran.  However, this patch only registers 'flang' as a known Fortran compiler and does not set any flags or options that are compiler specific.

Patch eospac package to allow compilation with %clang.

---

var/spack/repos/builtin/packages/mpifileutils/package.py

- roll back to dtcmp v1.0.3 due to API change on DTCMP_Segmented_exscan
- add option to build master branch from github

mpifileutils: roll back to dtcmp v1.0.3, add option to build master branch

---

var/spack/repos/builtin/packages/mvapich2/package.py

- add regcache variant to enable/disable memory registration cache
- add file_systems variant to list ROMIO file system components to be built
- avoid empty --with-pm= option if user specifies no process_managers value
- fix missing leading dash in --disable-silent-rules

mvapich2: add registration cache and file systems variants

---

var/spack/repos/builtin/packages/bookleaf-cpp/package.py
var/spack/repos/builtin/packages/typhon/package.py

Adds packages for [BookLeaf_Cpp](https://github.com/UK-MAC/BookLeaf_Cpp), an unstructured hydro mini-app and [Typhon](https://github.com/UK-MAC/Typhon), its sister comms library.

Added BookLeaf_Cpp and Typhon packages.

---

var/spack/repos/builtin/packages/python/package.py

@adamjstewart @healther 
This PR makes #7103 optional.  I believe #7103 is not a good idea for the following reasons:
1. It is not the way the Python distro does things.   `python3` is the standard name for the Python3 executable, and `python`, according to the standard, always means Python2.  By default, Spack installations should conform to the standard.
2. It does weird things to my Spack.  Consider what I did:
1. Download Spack, start using it.  (Spack running with my System's /usr/bin/ptyhon).
2. Install my software stack, which includes Python3
3. Do a `module load` of my software stack.
4. All of a sudden, the `spack` command is now running with Python3, not Python2.  What horrible inconsistencies might that cause, AFTER I've built a lot of stuff?  (To be fair, Spack works with …

make symlinking python3->python optional

---

var/spack/repos/builtin/packages/ruby-svn2git/package.py

https://github.com/nirvdrum/svn2git
svn2git is a tiny utility for migrating projects from Subversion to Git while keeping the trunk, branches and tags where they should be. It uses git-svn to clone an svn repository and does some clean-up to make sure branches and tags are imported in a meaningful way, and that the code checked into master ends up being what's currently in your svn trunk rather than whichever svn branch your last commit was in.

New Package: ruby-svn2git

---

var/spack/repos/builtin/packages/py-cython/package.py

Following the example of `python`, add a `spec.command` property, to be used by other packages.

py-cython: update

---

var/spack/repos/builtin/packages/gmp/package.py

Add version needed for `ghc-bootstrap`

gmp: update
