spack/spack

- var/spack/repos/builtin/packages/py-htseq/package.py
> py-htseq: Create new package.

- var/spack/repos/builtin/packages/r-tigris/package.py
> r-tigris: Create new package.

- var/spack/repos/builtin/packages/r-rgdal/package.py
> r-rgdal: Create new package.

- var/spack/repos/builtin/packages/r-tidycensus/package.py
> r-tidycensus: Create new package.

- var/spack/repos/builtin/packages/nekbone/package.py
Minor changes. I installed the `makenek` file so that user can use this to
build any example she wants. Feel free to merge as it is if this looks okay.
> Update the Nekbone package

- var/spack/repos/builtin/packages/nekcem/package.py
User can use the `makenek` script to build NekCEM cases.
> Add NekCEM package to spack

- var/spack/repos/builtin/packages/ascent/package.py
- var/spack/repos/builtin/packages/conduit/package.py
- var/spack/repos/builtin/packages/vtkh/package.py
retry of PR: https://github.com/spack/spack/pull/6350
> updates to conduit and ascent packages (new PR)

- var/spack/repos/builtin/packages/neovim/package.py
> Fix reference to self.versions in neovim package

- var/spack/repos/builtin/packages/xsdk/package.py
cc: @keitat @curfman @jwillenbring @tgamblin
> disable plasma in xsdk 0.3.0

- var/spack/repos/builtin/packages/bazel/fix_env_handling.patch
- var/spack/repos/builtin/packages/bazel/link.patch
> Fix bazel build after introduction of SPACK_DEBUG_LOG_ID in #5837

- var/spack/repos/builtin/packages/intel-parallel-studio/package.py
> Patch psxevars.sh and psxevars.csh only when year>2016.

- var/spack/repos/builtin/packages/py-pysam/package.py
> py-pysam: adding old version 0.7.7

- var/spack/repos/builtin/packages/tasmanian/package.py
builds ok on macOS.
@BenBrands ping.
> tasmanian: add new package

- var/spack/repos/builtin/packages/libharu/package.py
This solved the issue I described in #6681, at least for me on OS X High Sierra.
> libharu: Make dependencies on zlib and libpng explicit

- lib/spack/spack/environment.py
More details in the referenced issue.
> misc fixes, changed to EnvironmentModifications (issue #6501)

- var/spack/repos/builtin/packages/mefit/package.py
> mefit: Create new package.

- var/spack/repos/builtin/packages/petsc/package.py
Adds petsc library version `3.8.3`
> Add petsc version 3.8.3

- var/spack/repos/builtin/packages/caliper/package.py
Adds version 1.6.0 and some variants
> Caliper update, add version 1.6.0

- var/spack/repos/builtin/packages/bwa/package.py
bwa: added version 0.7.16a and checksum
> Features/bwa 0.7.16a

- var/spack/repos/builtin/packages/mercurial/package.py
make mercurial/package.py python3 compatible
> fix post install method for py3 in mercurial

- var/spack/repos/builtin/packages/relion/package.py
This is now the recommended version to use.
> relion - added new stable version 2.1

- var/spack/repos/builtin/packages/igv/package.py
Integrative Genomics Viewer (IGV) v2.4.5 & 2.3.50
> IGV: Add new package

- var/spack/repos/builtin/packages/emacs/package.py
- var/spack/repos/builtin/packages/ncurses/package.py
This is what it took for me to get this build working. Just tested with 25.3.
I find using el-get goes much smoother with gnutls.
> Building with gnutls on Centos 7

- var/spack/repos/builtin/packages/gdb/package.py
This PR adds version 8.0 to the GDB builtin package.
> GDB: Adds version 8.0

- var/spack/repos/builtin/packages/flang/package.py
- var/spack/repos/builtin/packages/llvm/package.py
> clang,flang: update CC, CXX environment in installation module

- lib/spack/spack/test/cmd/list.py
Because we can do better than 31.82% coverage...
> Add more unit tests for spack list command

- var/spack/repos/builtin/packages/rmlab/package.py
Adds the C++ File API library [lines-are-beautiful](https://github.com/ax3l/lines-are-beautiful) for the [reMarkable e-ink tablet](https://remarkable.com/).
> Add: lines-are-beautiful

- var/spack/repos/builtin/packages/gatk/package.py
> gatk: boilerplate cleanup

- var/spack/repos/builtin/packages/kaldi/package.py
The current install only installs the executables from 'bin' however there are many other tools which are useful to install.
> Install all the cli tools from all the sub-directories

- var/spack/repos/builtin/packages/py-adios/package.py
The ADIOS1 numpy bindings depend on an installed, fully loaded ADIOS C library + its config tools to build properly.
~~A few question for reviewers are inline, where I did not know how to express things properly.~~
> New Package: py-adios

- var/spack/repos/builtin/packages/singularity/package.py
Centos 6 needs branch per [this issue I opened](https://github.com/singularityware/singularity/issues/1056)
> singularity - added master branch

- var/spack/repos/builtin/packages/libtiff/package.py
> Add libtiff@3 required by MotionCor2.

- var/spack/repos/builtin/packages/qt/package.py
- var/spack/repos/builtin/packages/qt/restore-pc-files.patch
fixes https://github.com/spack/spack/issues/4959
> qt: add 5.10.0, fix macOS build, clean-up comments/TODOs

- var/spack/repos/builtin/packages/r-rgeos/package.py
> r-rgeos: Create new package.

- var/spack/repos/builtin/packages/r-rgraphviz/package.py
> r-rgraphviz: Create new package.

- var/spack/repos/builtin/packages/i3/package.py
- var/spack/repos/builtin/packages/libev/package.py
- var/spack/repos/builtin/packages/libxkbcommon/package.py
- var/spack/repos/builtin/packages/startup-notification/package.py
- var/spack/repos/builtin/packages/xcb-util-xrm/package.py
Added package for [i3 window manager](i3wm.org) including the needed dependencies.
> Added i3 and its dependencies.

- var/spack/repos/builtin/packages/openssl/package.py
Reverting #5188 until #6830 is resolved.
> Revert "openssl: Add perl dependency"

- var/spack/repos/builtin/packages/py-mongo/package.py
> Fix pymongo package

- var/spack/repos/builtin/packages/py-psyclone/package.py
PSyclone is a Parallelisation System for finite element, finite volume and finite difference codes. It is being developed for the UK Met Office's next generation of weather and climate models, which are intended to scale across millions of processors. The primary role of Psyclone is to provide node-based parallel performance for a target architecture, which may consist of multi/many-core processors, GPGPUs and accelerators in various combinations. Psyclone offers the potential for portable performance without manual changes to code in scientific algorithms or computational kernels.
This package depends on py-fparser (please see PR #6794).
> py-psyclone: Parallelisation System for climate models

- lib/spack/docs/contribution_guide.rst
I decided to add documentation on some of the questions I get asked multiple times per day:
- How do I restart my failed Travis tests?
- Are Codecov tests required to pass if I only modified package files?
> Add documentation on Codecov

- var/spack/repos/builtin/packages/adios2/package.py
- var/spack/repos/builtin/packages/gearshifft/package.py
Remove unnecessary double brackets in ADIOS2 and gearshifft packages.
> Cleanup: Remove Dbl Brackets

- var/spack/repos/builtin/packages/vtk/package.py
Fixes #6850.
@sknigh Can you test this and make sure it still builds for you?
> Remove std_cmake_args from VTK definition

- var/spack/repos/builtin/packages/astyle/package.py
Fixed URL for astyle package (Gentoo url is not working at the moment).
ping @davydden
> changed url for astyle

- var/spack/repos/builtin/packages/openfoam-org/package.py
> Explicitly cast Version to str in openfoam-org

- var/spack/repos/builtin/packages/opa-psm2/package.py
opa-psm2 provides libpsm2.so library files
> opa-psm2: new package

- var/spack/repos/builtin/packages/geant4/package.py
> Geant4: fix qt dependency

- var/spack/repos/builtin/packages/cairo/package.py
- var/spack/repos/builtin/packages/gdbm/package.py
- var/spack/repos/builtin/packages/glib/package.py
- var/spack/repos/builtin/packages/i3/package.py
- var/spack/repos/builtin/packages/pango/package.py
- var/spack/repos/builtin/packages/pcre/package.py
- var/spack/repos/builtin/packages/pkgconf/package.py
Updating the main i3 dependencies to their latest versions.
> Updated i3 dependencies.

- var/spack/repos/builtin/packages/r-rprojroot/package.py
> r-rprojroot: Create new package.

- var/spack/repos/builtin/packages/r-bookdown/package.py
> r-bookdown: Create new package.

- var/spack/repos/builtin/packages/r-biocstyle/package.py
> r-biocstyle: Create new package.

- var/spack/repos/builtin/packages/intel-parallel-studio/package.py
> fix ips 2018 vtune directory name

- var/spack/repos/builtin/packages/bash-completion/package.py
- var/spack/repos/builtin/packages/bash/package.py
- var/spack/repos/builtin/packages/binutils/package.py
- var/spack/repos/builtin/packages/cmake/package.py
- var/spack/repos/builtin/packages/gdb/package.py
- var/spack/repos/builtin/packages/texinfo/package.py
- var/spack/repos/builtin/packages/valgrind/package.py
Updated some developer tools to their latest versions.
> Updated misc devel tools.

- var/spack/repos/builtin/packages/libbson/package.py
- var/spack/repos/builtin/packages/libmongoc/package.py
I have also added myself as a maintainer to the two packages.
> libbson, libmongoc: Update to 1.9.1

- var/spack/repos/builtin/packages/gccxml/gcc-5.patch
- var/spack/repos/builtin/packages/gccxml/package.py
> add patch for gccxml with gcc@5:

- var/spack/repos/builtin/packages/glib/package.py
Newer versions of glib require python. Fix up the python sbangs the same way we already fix up the perl ones.
Fixes #6899
> glib: Fix python handling

- var/spack/repos/builtin/packages/catalyst/package.py
New package file to install Catalyst as a module.
> Catalyst package

- var/spack/repos/builtin/packages/r-rappdirs/package.py
> r-rappdirs: Create new package.

- .travis.yml
This in case we don't want to merge #5842 yet. Otherwise let's merge that first, and I'll rebase this on top.
> Added flags to unit tests + OSX build done once per day

- var/spack/repos/builtin/packages/ucx/package.py
> ucx: update for release 1.2.2

- var/spack/repos/builtin/packages/miniqmc/package.py
> miniqmc: initial commit

- var/spack/repos/builtin/packages/sniffles/package.py
> sniffles: add version 1.0.7

- var/spack/repos/builtin/packages/r-getopt/package.py
> r-getopt: new package

- var/spack/repos/builtin/packages/visit/package.py
* Add versions 2.12.3, 2.13.0
* Enable building with `hdf5+mpi` via variant
* Add `qwt` dependency
> Visit 2.13.0

- var/spack/repos/builtin/packages/ack/package.py
> Package: Ack update for ver. 2.22

- var/spack/repos/builtin/packages/r-gdsfmt/package.py
> r-gdsfmt: new package

- var/spack/repos/builtin/packages/r-snprelate/package.py
Added new package r-snprelate.
> r-snprelate: new package

- var/spack/repos/builtin/packages/cfitsio/package.py
Added new 3.420 version of cfitsio.
> Version update for cfitsio

- var/spack/repos/builtin/packages/gslib/package.py
This is still a WIP. Please don't merge yet. Feedback is always appreciated.
(this will be changed in `gslib` side in future releases)
> Add gslib to spack

- var/spack/repos/builtin/packages/dia/package.py
- var/spack/repos/builtin/packages/emacs/package.py
- var/spack/repos/builtin/packages/gtkplus/package.py
- var/spack/repos/builtin/packages/icedtea/package.py
- var/spack/repos/builtin/packages/py-pygtk/package.py
- var/spack/repos/builtin/packages/slurm/package.py
- var/spack/repos/builtin/packages/wx/package.py
Fixes #6940 by hardconding X11 support as graphical backend.
> Fix gtkplus build by hardcoding X11 support

- var/spack/repos/builtin/packages/rna-seqc/rna-seqc.sh
Helper script improvements per #4640
> rna-seqc: JAVA_{ARGS,OPTS} for helper script

- var/spack/repos/builtin/packages/py-openpmd-validator/package.py
Adds the new package for [openPMD validator tools](https://github.com/openPMD/openPMD-validator).
> openPMD-validator

- var/spack/repos/builtin/packages/pngwriter/package.py
Adds the latest release of PNGwriter, including Windows and CMake config package support.
> PNGwriter: 0.7.0

- var/spack/repos/builtin/packages/gdal/package.py
Solves #7150.  Based on existing code, as per suggestion by @davydden
> macOS Fix for GDAL

- var/spack/repos/builtin/packages/nek5000/package.py
And minor polishing.
@adamjstewart: Please review.
> Update Nek5000 package to Version 17

- var/spack/repos/builtin/packages/libxsmm/package.py
See https://github.com/hfp/libxsmm/releases/tag/1.8.3.
> LIBXSMM 1.8.3

- var/spack/repos/builtin/packages/comd/package.py
> comd: more sane default

- var/spack/repos/builtin/packages/petsc/package.py
Fixes metis dependencies for installing petsc +int64
> fix petsc int64 metis dependencies

- var/spack/repos/builtin/packages/hpgmg/package.py
Pulling master.tar.gz from the repository results in a different hash
any time a developer pushes.  Also, that tarball is a bit heavy because
the repository contains some presentations.  So now we use a static
tarball with docs stripped that is hosted at hpgmg.org.
Cc: @acfisher
> hpgmg: use a stripped, static tarball and add debug/opt variants

- var/spack/repos/builtin/packages/xsimd/package.py
- var/spack/repos/builtin/packages/xtensor/package.py
- var/spack/repos/builtin/packages/xtl/package.py
Add the latest xtensor release and its dependencies.
cc: @JohanMabille @SylvainCorlay @wolfv
> xtensor 0.15.1

- var/spack/repos/builtin/packages/raja/package.py
This PR adds CUDA support and tags our stable release versions in addition to master and develop branches.
> Update RAJA with more versions and CUDA support

- var/spack/repos/builtin/packages/fluxbox/package.py
This is a lightweight minimal window manager to be used in vnc sessions on headless clusters
> fluxbox lightweight window manager

- var/spack/repos/builtin/packages/grackle/package.py
Hi,
In Grackle, the code can be compiled with float or double. Therefore I have added a new variant for it.
Best regards,
> Add float option to grackle

- var/spack/repos/builtin/packages/fftw/package.py
> FFTW: expose optimization handles via variants (SIMD + FMA)

- lib/spack/llnl/util/filesystem.py
- lib/spack/spack/__init__.py
- lib/spack/spack/directives.py
- lib/spack/spack/mixins.py
- lib/spack/spack/package.py
- lib/spack/spack/spec.py
- lib/spack/spack/test/llnl/util/file_list.py
- var/spack/repos/builtin/packages/arpack-ng/package.py
- var/spack/repos/builtin/packages/atlas/package.py
- var/spack/repos/builtin/packages/elemental/package.py
- var/spack/repos/builtin/packages/elpa/package.py
- var/spack/repos/builtin/packages/hdf5/package.py
- var/spack/repos/builtin/packages/intel-mpi/package.py
- var/spack/repos/builtin/packages/libxc/package.py
- var/spack/repos/builtin/packages/mpich/package.py
- var/spack/repos/builtin/packages/mvapich2/package.py
- var/spack/repos/builtin/packages/ncurses/package.py
- var/spack/repos/builtin/packages/netcdf-fortran/package.py
- var/spack/repos/builtin/packages/netlib-lapack/package.py
- var/spack/repos/builtin/packages/netlib-scalapack/package.py
- var/spack/repos/builtin/packages/openmpi/package.py
- var/spack/repos/builtin/packages/openspeedshop/package.py
- var/spack/repos/builtin/packages/r/package.py
- var/spack/repos/builtin/packages/scotch/package.py
- var/spack/repos/builtin/packages/veclibfort/package.py
- var/spack/repos/builtin/packages/zlib/package.py
This PR starts from a complaint from one of our users about `hdf5` compiler wrappers, that were still configured to use Spack wrappers. As I saw the code to filter those files repeated over and over in different packages I tried to factorize it in one place. Mixins seem a good enough approach to factor out common behavior that appears across different build systems.
> Use mixins to modularize common behaviors across build-systems

- var/spack/repos/builtin/packages/r-matrix/package.py
- var/spack/repos/builtin/packages/r-rcppblaze/package.py
> r-rcppblaze: new package

- var/spack/repos/builtin/packages/r-jaspar2018/package.py
> r-jaspar2018: Create new package.

- var/spack/repos/builtin/packages/r-mgcv/package.py
- var/spack/repos/builtin/packages/r-powerlaw/package.py
Added new package r-powerlaw. 
Added new versions to r-mgcv (a dependency).
> r-powerlaw: new package

- var/spack/repos/builtin/packages/py-pybedtools/package.py
> py-pybedtools: adding older version 0.6.9

- var/spack/repos/builtin/packages/r-tfmpvalue/package.py
Added new package r-tfmpvalue.
> r-tfmpvalue: new package

- var/spack/repos/builtin/packages/r-seqlogo/package.py
> r-seqlogo: new package

- var/spack/repos/builtin/packages/pmix/package.py
> pmix: add 2.1.0 and more

- var/spack/repos/builtin/packages/igvtools/igvtools.sh
- var/spack/repos/builtin/packages/igvtools/package.py
See the discussion about installing jar files in #4386.
> igvtools: Create new package

- var/spack/repos/builtin/packages/postgresql/package.py
> postgresql: add new version (10.2)

- var/spack/repos/builtin/packages/silo/package.py
> Silo: depend on Non-mpi hdf5

- var/spack/repos/builtin/packages/gmap-gsnap/package.py
simple update to the latest version. Number of bug fixes.
> updating package: gmap-gsnap

- var/spack/repos/builtin/packages/sundials/package.py
... plus a couple of small tweaks.
cc: @gardner48
> sundials: add the 'headers' and 'libs' properties

- var/spack/repos/builtin/packages/soapdenovo2/package.py
Added new package soapdenove2.
> soapdenove2: new package

- var/spack/repos/builtin/packages/nut/package.py
> nut: needs cmake-3.0

- var/spack/repos/builtin/packages/intel-mkl/package.py
- var/spack/repos/builtin/packages/intel-parallel-studio/package.py
fixes https://github.com/spack/spack/issues/7279
@pramodskumbhar please test.
> mkl: fix order of libs

- var/spack/repos/builtin/packages/cohmm/package.py
Found as part of proxyapps/proxy-ci#2
> cohmm: use more sane defaults

- var/spack/repos/builtin/packages/py-maestrowf/package.py
Added the maestrowf Python package.
> maestrowf: new package

- var/spack/repos/builtin/packages/accfft/package.py
The shared build depends on https://github.com/amirgholami/accfft/pull/13 to work. 
@amirgholami If you could tag a release, I would gladly add it here with a version number and a proper checksum :wink: 
@ursache You might be interested in this package.
> accfft: added new package

- var/spack/repos/builtin/packages/hpgmg/package.py
> hpgmg: more sane defaults for a proxy

- var/spack/repos/builtin/packages/ebms/package.py
> ebms: needs mpi-2

- var/spack/repos/builtin/packages/branson/package.py
> branson: needs mpi-2

- var/spack/repos/builtin/packages/spglib/fix_cmake_install.patch
- var/spack/repos/builtin/packages/spglib/fix_cpp.patch
- var/spack/repos/builtin/packages/spglib/package.py
PR with changes accepted upstream: 
- https://github.com/atztogo/spglib/pull/47
- https://github.com/atztogo/spglib/pull/48
> spglib: add new package

- var/spack/repos/builtin/packages/snbone/package.py
> snbone: fix build gcc-4.8

- var/spack/repos/builtin/packages/minighost/package.py
> minighost: fix mpi build

- var/spack/repos/builtin/packages/mpark-variant/package.py
Adds Michael Park's C++11 `std::variant` (a C++17 stdlib feature).
https://github.com/mpark/variant
> MPark.Variant

- var/spack/repos/builtin/packages/aspcud/package.py
> aspcud@1.9.4: new package

- var/spack/repos/builtin/packages/minighost/package.py
Fixup for #7310 
@alalazo 
Part of proxyapps/proxy-ci#2
> minighost: fixed a typo

- var/spack/repos/builtin/packages/examinimd/package.py
Added spackage for examinimd proxy app. We are currently still waiting on the developers to tag a release but the build process will not change and the current version can already be used for research and development purposes.
> Added initial Spackage for examinimd

- var/spack/repos/builtin/packages/zfp/package.py
Update to newest ZFP version, 0.5.2.
Cut down on and minor corrections to info text too
> Updating zfp version

- var/spack/repos/builtin/packages/examinimd/package.py
> examinimd: fix a typo

- var/spack/repos/builtin/packages/minighost/package.py
> minighost: fix build on Ubuntu

- var/spack/repos/builtin/packages/gdb/package.py
explicitly point to the python libs
> help gdb pick up python3

- var/spack/repos/builtin/packages/hiop/package.py
Added new package hiop
cc @cnpetra
> hiop: new package

- var/spack/repos/builtin/packages/minismac2d/package.py
Needs #7267
Part of proxyapps/proxy-ci#2
> minismac2d: fix build with external Debian MPI

- var/spack/repos/builtin/packages/minighost/package.py
Part of proxyapps/proxy-ci#2
Build with this: https://travis-ci.org/proxyapps/proxy-ci/builds/347498068
> minighost: another Ubuntu fix

- var/spack/repos/builtin/packages/exasp2/package.py
> exasp2: add v1.0

- var/spack/repos/builtin/packages/snpeff/package.py
- var/spack/repos/builtin/packages/snpeff/snpEff.sh
> snpEff: Create new package.

- var/spack/repos/builtin/packages/neuron/package.py
* find the bin directory dynamically for use in run_env and spack_env
* replace filter_compilers with filter_compiler_wrappers
* update checksum for "current" 7.5 version
Signed-off-by: Ricardo Silva <ricardo.silva@epfl.ch>
> Make neuron package more generic

- var/spack/repos/builtin/packages/gromacs/package.py
> gromacs: add v2018

- var/spack/repos/builtin/packages/pnmpi/package.py
Add PnMPI, a dynamic MPI tool infrastructure that builds on top of the
PMPI interface.
> pnmpi@1.7: new package

- var/spack/repos/builtin/packages/orthofinder/package.py
> orthofinder: Create new package.

- var/spack/repos/builtin/packages/dislin/package.py
> dislin: new package

- var/spack/repos/builtin/packages/star/package.py
tried as a build only dependency, didn't work.
> star: needs zlib

- var/spack/repos/builtin/packages/r-ape/package.py
- var/spack/repos/builtin/packages/r-fastmatch/package.py
- var/spack/repos/builtin/packages/r-igraph/package.py
- var/spack/repos/builtin/packages/r-phangorn/package.py
Added new package r-phangorn. Added or modified some of its dependencies.
> New package r-phangorn and its dependencies

- var/spack/repos/builtin/packages/json-c/package.py
0.12.1 does not compile with GCC 7.
> json-c: Update to 0.13.1

- var/spack/repos/builtin/packages/r-cner/package.py
- var/spack/repos/builtin/packages/r-keggrest/package.py
Added new package r-cner.
Added version 1.18.1 to its dependency r-keggrest.
> r-cner: new package

- var/spack/repos/builtin/packages/tcptrace/package.py
- var/spack/repos/builtin/packages/tcptrace/tcpdump.patch
Also added missing deps for libpcap.
> Added tcptrace

- var/spack/repos/builtin/packages/ceed/package.py
- var/spack/repos/builtin/packages/hpgmg/package.py
- var/spack/repos/builtin/packages/libceed/package.py
- var/spack/repos/builtin/packages/occa/package.py
With these changes I can build most of the CEED distribution on my Mac laptop and desktop -- the only outstanding issue is Magma on the desktop.
> Small changes for CEED on Mac

- var/spack/repos/builtin/packages/fenics/package.py
Resolves the hdf5 issue described in #7145.
> Fix dependency conflict in FEniCS.

- var/spack/repos/builtin/packages/r-tfbstools/package.py
> r-tfbstools: new package

- var/spack/repos/builtin/packages/tcl/package.py
As  pointed out [here](https://wiki.tcl.tk/1787), the *extension* environment variable `TCLLIBPATH` must be a **space-separated** list of paths and **not** a proper shell list.
> tcl: fix 'extends' behaviour

- var/spack/repos/builtin/packages/postgresql/package.py
> postgresql: add newest version 10.3

- var/spack/repos/builtin/packages/phylip/package.py
can't find 3.696 for download anymore
> phylip: new version

- var/spack/repos/builtin/packages/examinimd/package.py
Added the tagged 1.0 release of ExaMiniMD to the spackage
> Added Tagged Release of ExaMiniMD

- var/spack/repos/builtin/packages/hwloc/package.py
- var/spack/repos/builtin/packages/openmpi/package.py
This includes:
* Added latest available versions (1.11.9, 2.0.0)
* Added variants to enable graphical output from lstopo
* Enabled build of the bundled netloc package if @2.0.0:
* Added dependency from numactl if @:1.11.9
@nazavode @rmsds
> hwloc: updated package

- var/spack/repos/builtin/packages/hwloc/package.py
> hwloc: constrain dependency on numactl

- var/spack/repos/builtin/packages/py-perf/package.py
- var/spack/repos/builtin/packages/py-performance/package.py
@adamjstewart @lee218llnl @xjrc I was thinking: why not using this package to get numbers for #7496 ?
> py-performance: added package

- var/spack/repos/builtin/packages/libxsmm/package.py
See https://github.com/hfp/libxsmm/releases/tag/1.9
> LIBXSMM 1.9

- var/spack/repos/builtin/packages/bazel/fix_env_handling-0.9.0.patch
- var/spack/repos/builtin/packages/bazel/package.py
- var/spack/repos/builtin/packages/bazel/unix_cc_configure.patch
Some code got moved around so the patches needed to be updated
> Update the patches to work with bazel 0.9.0

- var/spack/repos/builtin/packages/glib/package.py
fixes #6965
closes #6968 
@nazavode
> glib: updated package and fixed issues with dtrace

- var/spack/repos/builtin/packages/python/package.py
I extracted the non-controversial parts of #7496 here. Let me no if this is fine with you to merge.
> python: dbm module + version 3.6.4

- var/spack/repos/builtin/packages/dsdp/malloc.patch
- var/spack/repos/builtin/packages/dsdp/package.py
Largely based on the Homebrew package:
https://github.com/sjackman/homebrew-science-deprecated/blob/master/dsdp.rb
> Add DSDP package

- var/spack/repos/builtin/packages/ghost/package.py
- var/spack/repos/builtin/packages/intel-mkl/package.py
- var/spack/repos/builtin/packages/netlib-lapack/package.py
> Ghost as cuda package

- var/spack/repos/builtin/packages/py-vmd-python/package.py
Prerequisite for another package named "dabble" coming soon
> VMD-python v2.0.10 - new package

- var/spack/repos/builtin/packages/orfm/package.py
found while installing in a clean container
> orfm: needs zlib

- var/spack/repos/builtin/packages/libepoxy/package.py
- var/spack/repos/builtin/packages/mesa/package.py
- var/spack/repos/builtin/packages/xorg-server/package.py
Fix installation for xorg-server.
> Xorg-server: Add dependencies and fix installation.

- var/spack/repos/builtin/packages/unzip/package.py
Adding unzip which I based on the existing zip package.
> Adding unzip package.

- var/spack/repos/builtin/packages/phylip/package.py
- var/spack/repos/builtin/packages/snphylo/package.py
Added new package snphylo and added new version of its dependency.
> snphylo: new package

- var/spack/repos/builtin/packages/suite-sparse/package.py
fixes https://github.com/spack/spack/issues/7537
@adamjstewart @cpraveen  ping.
> suite-sparse: add cmake dependency for 5.2.0

- var/spack/repos/builtin/packages/jags/package.py
> package/JAGS: new version (4.3)

- var/spack/repos/builtin/packages/r-dirichletmultinomial/package.py
Add package: r-dirichletmultinomial.
> r-dirichletmultinomial: Create new package.

- var/spack/repos/builtin/packages/subversion/package.py
> add versions 1.9.6 1.9.7

- var/spack/repos/builtin/packages/py-pyutilib/package.py
> package/py-pyutilib: create new package

- lib/spack/spack/package.py
Fixes #6876.
There's probably a better place to do this, but this PR does indeed fix the problem reported in #6876.
> Fix error raising during install with Python 3

- var/spack/repos/builtin/packages/hypre/package.py
... plus a small tweak in the 'libs' property.
> [hypre] add the 'headers' property

- var/spack/repos/builtin/packages/bc/package.py
- var/spack/repos/builtin/packages/ed/package.py
Tested on OSX Clang, Linux GCC, and it even builds on Cray GCC:
```
[+] ..../spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/bc-1.07-4hajyfsalyspe6e6mp4a3gcqzc3lwipm
```
> Adding bc and ed packages.

- var/spack/repos/builtin/packages/glib/package.py
Fixes #7575.
@peetsv can you see if this fixes your problem?
> Only add python flag for newer versions of glib

- share/spack/spack-completion.bash
Spack's Bash tab completion was woefully out of date. This PR fixes that.
> Various updates to Spack's Bash completion

- etc/spack/defaults/config.yaml
* `spack purge` now is `spack clean`
> fix defaults/config.yaml comments

- var/spack/repos/builtin/packages/seqan/package.py
> new package: Seqan (bioinformatics)

- var/spack/repos/builtin/packages/r-dplyr/package.py
- var/spack/repos/builtin/packages/r-lubridate/package.py
- var/spack/repos/builtin/packages/r-rlang/package.py
- var/spack/repos/builtin/packages/r-rstudioapi/package.py
- var/spack/repos/builtin/packages/r-tidyr/package.py
- var/spack/repos/builtin/packages/r-tidyselect/package.py
- var/spack/repos/builtin/packages/r-tidyverse/package.py
- New package r-tidyverse and r-tidyselect
- New version and dependencies added for some packages
> New package r-tidyverse and r-tidyselect

- var/spack/repos/builtin/packages/liblockfile/install_as_nonroot.patch
- var/spack/repos/builtin/packages/liblockfile/package.py
* --enable-shared *additionally* builds shared libraries
(and it builds fast, so no variant here)
> Adds liblockfile (and patch to avoid need for root)

- var/spack/repos/builtin/packages/r-snowfall/package.py
required dependency for phantompeakqualtools
somehow #6403 made it through without it
> R-snowfall: new package

- var/spack/repos/builtin/packages/libcint/package.py
Update of the versions and hashes for the libcint package.
> Add latest libcint versions

- var/spack/repos/builtin/packages/libhio/0001-configury-fix-a-problem-with-bz2-configury.patch
- var/spack/repos/builtin/packages/libhio/0001-hdf5-make-docs-optional.patch
- var/spack/repos/builtin/packages/libhio/package.py
spack brought out some configury/make issues with
libhio, so some patches come along for the ride.
> libhio: add libhio package to spack

- var/spack/repos/builtin/packages/gurobi/package.py
> gurobi: new package

- var/spack/repos/builtin/packages/boost/package.py
* explicitly specify user-config.jam as it isn't found
via the environment variable on older boost versions
(cf. what debian/rules does)
=> fixes +mpi build
* fix "error: Ambiguous key" error on :1.58.999 boost
(cf. https://github.com/boostorg/boost/blob/boost-1.59.0/bootstrap.sh#L357)
> Fix build of boost@:1.58.999 +python (and +mpi)

- var/spack/repos/builtin/packages/r-gss/package.py
> r-gss: new package

- var/spack/repos/builtin/packages/r-flexclust/package.py
> r-flexclust: new package

- var/spack/repos/builtin/packages/boost/array_binary_tree.patch
- var/spack/repos/builtin/packages/boost/package.py
- var/spack/repos/builtin/packages/dealii/package.py
- var/spack/repos/builtin/packages/muparser/auto_ptr.patch
- var/spack/repos/builtin/packages/muparser/package.py
> fix dealii dependencies for Clang 9.1.0 C++17

- var/spack/repos/builtin/packages/soapdenovo-trans/package.py
Add new package: soapdenovo-trans.
> soapdenovo-trans: Create new package.

- var/spack/repos/builtin/packages/octopus/package.py
tested on Ubuntu with gcc.
p.s. eventually we should adopt more of https://github.com/macports/macports-ports/blob/master/science/octopus/Portfile
> octopus: add 7.3

- var/spack/repos/builtin/packages/python/package.py
- var/spack/repos/builtin/packages/tcl/package.py
Fixes #7676.
@chissg can you test this?
> Don't prepend Tcl/Python to PATH if in system directory

- var/spack/repos/builtin/packages/hapdip/package.py
- var/spack/repos/builtin/packages/k8/package.py
Add new package: k8 and hapdip.
> hapdip: Create new package and its dependency k8.

- var/spack/repos/builtin/packages/serf/package.py
> Package 'serf': link to the spack provided zlib installation.

- var/spack/repos/builtin/packages/darshan-runtime/package.py
- var/spack/repos/builtin/packages/darshan-util/package.py
Adds Darshan 3.1.6 for darshan-util and darshan-runtime packages.  Also adds optional bzip2 variant for darshan-util.
> Darshan 3.1.6

- lib/spack/spack/cmd/view.py
- var/spack/repos/builtin/packages/py-pyfaidx/package.py
> py-pyfaidx: adding new package

- var/spack/repos/builtin/packages/adios2/package.py
- var/spack/repos/builtin/packages/nlohmann-json/package.py
Adds a spack package for the JSON C++ library
https://github.com/nlohmann/json
> Add Package: nlohmann_json

- var/spack/repos/builtin/packages/fermi/package.py
> fermi: Create new package.

- var/spack/repos/builtin/packages/c-lime/package.py
This adds a package that adds the C-LIME File Format library.
> Added C-Lime Package

- var/spack/repos/builtin/packages/py-gdbgui/package.py
depends on ~#7709 - #7714, #7720-#7723 #7721~
> add package py-gdbgui

- var/spack/repos/builtin/packages/opengl/package.py
> opengl: make error throw on install, not fetch

- var/spack/repos/builtin/packages/r-rsolnp/package.py
- var/spack/repos/builtin/packages/r-spem/package.py
- var/spack/repos/builtin/packages/r-truncnorm/package.py
New package r-spem and its dependencies.
> New package r-spem

- etc/spack/defaults/packages.yaml
> Specify default providers for the glu virtual package

- var/spack/repos/builtin/packages/supernova/package.py
> supernova: new package

- var/spack/repos/builtin/packages/ucx/package.py
> UCX: update for release 1.3.0

- var/spack/repos/builtin/packages/r-cluster/package.py
- var/spack/repos/builtin/packages/r-tmixclust/package.py
New package r-tmuixclust.
The hash for r-cluster@2.0.6 is changed.
> New package r-tmixclust

- var/spack/repos/builtin/packages/py-editdistance/package.py
- var/spack/repos/builtin/packages/r-cner/package.py
- var/spack/repos/builtin/packages/r-genomeinfodbdata/package.py
- var/spack/repos/builtin/packages/r-org-hs-eg-db/package.py
- var/spack/repos/builtin/packages/r-phangorn/package.py
- var/spack/repos/builtin/packages/r-yarn/package.py
Not sure how these slipped in. 
@healther 
@fanne-stat 
@lingnanyuan
> Fix www.example.com homepages

- var/spack/repos/builtin/packages/flux/package.py
> flux: changed default value for doc variant to False

- var/spack/repos/builtin/packages/libcint/package.py
Add latest libcint version 3.0.11.
> Add libcint version 3.0.11

- var/spack/repos/builtin/packages/fermikit/package.py
> fermikit: new package

- var/spack/repos/builtin/packages/miniasm/package.py
> miniasm: new package

- var/spack/repos/builtin/packages/psmc/package.py
> psmc: new package

- lib/spack/spack/directory_layout.py
Small bug fix, should be a quick merge.
> Fix bug/oversight in formatting error message.

- var/spack/repos/builtin/packages/racon/package.py
new package: racon (bioinformatics)
https://github.com/isovic/racon
> new package: racon (bioinformatics)

- var/spack/repos/builtin/packages/omega-h/package.py
Adding the Omega_h mesh adaptation library as a package
> omega-h: new package

- var/spack/repos/builtin/packages/colm/package.py
- var/spack/repos/builtin/packages/ragel/package.py
- Ragel is a parser and finite state machine generator that can be
used as an alternative means for solving parsing problems without
Flex.
> New colm, ragel packages

- var/spack/repos/builtin/packages/pdf2svg/package.py
- var/spack/repos/builtin/packages/poppler/package.py
- var/spack/repos/builtin/packages/py-weblogo/package.py
Includes additional dependency packages:
* pdf2svg
* poppler
> py-weblogo: Create new package

- var/spack/repos/builtin/packages/fabtests/package.py
> fabtests: new package

- var/spack/repos/builtin/packages/py-numpy/package.py
Added checksums for newer versions of numpy! 
modified:   var/spack/repos/builtin/packages/py-numpy/package.py
> Added checksums for newer versions of numpy

- var/spack/repos/builtin/packages/rdma-core/package.py
based on #4168 and #6978 
depends on #7833
> rdma-core: new package

- var/spack/repos/builtin/packages/psm/package.py
based on PR #6978 
breaking up into smaller PRs
> psm: new package

- var/spack/repos/builtin/packages/automake/package.py
- var/spack/repos/builtin/packages/git/package.py
- var/spack/repos/builtin/packages/hadoop/package.py
- var/spack/repos/builtin/packages/jdk/package.py
- var/spack/repos/builtin/packages/lmod/package.py
- var/spack/repos/builtin/packages/picard/package.py
- var/spack/repos/builtin/packages/scala/package.py
- var/spack/repos/builtin/packages/spark/package.py
- var/spack/repos/builtin/packages/tar/package.py
- var/spack/repos/builtin/packages/tmux/package.py
I am in the process of updating the software deployed on our clusters. So expect a few more trivial PRs like this one in the next month :grin:
> Added the latest versions of a few packages

- var/spack/repos/builtin/packages/r/package.py
> add versions 3.4.3. and 3.5.0

- var/spack/repos/builtin/packages/mfem/package.py
Fix #7916
Fix proxyapps/proxy-ci#13
> mfem: fix concretization

- lib/spack/docs/contribution_guide.rst
I always forget how to do this and end up asking @alalazo for help. Rediscovered how to do this through trial and error, so I figured it was worth documenting.
> Document how to run unit tests with print statements

- var/spack/repos/builtin/packages/openmc/package.py
https://github.com/spack/spack/issues/7965#issuecomment-385953224
> openmc is not a proxy

- var/spack/repos/builtin/packages/py-pyside/package.py
Add comments explaining versioning issues.
> py-pyside: comments

- var/spack/repos/builtin/packages/py-scipy/package.py
Make use of new 'test' dependency type for `py-nose`.
> py-scipy: update

- var/spack/repos/builtin/packages/everytrace/package.py
Updated to latest version
Add maintainer
Add new variants
> Everytrace: update

- var/spack/repos/builtin/packages/pfunit/package.py
Use new official GitHub repo for pFUnit
Add variants for shared libraries
Make it work with Python3
> pfunit: update

- var/spack/repos/builtin/packages/pism/package.py
Alaska's Parallel Ice Sheet Model
> pism: new package

- var/spack/repos/builtin/packages/gdal/package.py
Make python dependency optional.
> gdal: update

- var/spack/repos/builtin/packages/papyrus/package.py
Papyrus is a distributed key-value store developed from the ECP PROTEAS project.
> a new package: papyrus.

- var/spack/repos/builtin/packages/gcc/package.py
Built once on Centos 7 w/ external GCC 4.8.5 compiler
> Added GCC 8.1.0

- var/spack/repos/builtin/packages/opencv/package.py
Next minor release for OpenCV is available :)
> [new version] add opencv 3.4.1

- var/spack/repos/builtin/packages/trilinos/package.py
- Reordered packages alphabetically
- Added `kokkos` variant
- Added conflicts for some things
> trilinos: minor cleanup

- var/spack/repos/builtin/packages/pixman/clang.patch
- var/spack/repos/builtin/packages/pixman/package.py
Fixes #7911.
Does this suffice or should I check for non apple-clang as well?
> Add patch to pixman for clang 5.0 and up

- var/spack/repos/builtin/packages/perl/package.py
5.26.2 is the current stable version according to https://www.perl.org
> perl: add 5.26.2

- var/spack/repos/builtin/packages/sundials/package.py
Add v3.1.1 and development version of Sundials
Update minimum required version of CMake
> Add new Sundials versions

- var/spack/repos/builtin/packages/r-mmwrweek/package.py
> r-mmwrweek: new package

- var/spack/repos/builtin/packages/masurca/package.py
version >= 3.2.4 needed for handling pacbio reads
> masurca: new version

- var/spack/repos/builtin/packages/pmix/package.py
> pmix: add 1.2.5 and 2.0.3 bug fix releases

- var/spack/repos/builtin/packages/r-cdcfluview/package.py
> r-cdcfluview: new package

- var/spack/repos/builtin/packages/plink/package.py
> plink: new source version 1.9-beta5

- var/spack/repos/builtin/packages/charliecloud/package.py
/cc @olifre @reidpr @trandles-lanl
> charliecloud: initial commit

- var/spack/repos/builtin/packages/py-numexpr3/package.py
Add a new pacakge numexpr3 since it's not available by specifying a version of the old py-numexpr pacakge. (Hopefully Cmake support can be added later! )
> Add numexpr 3

- var/spack/repos/builtin/packages/dealii/package.py
@adamjstewart @alalazo sorry for the noise, another change of hash.
> dealii: another fix for quick tests only in 9.0 and thus hash

- var/spack/repos/builtin/packages/charliecloud/package.py
> charliecloud: fix copyright

- var/spack/repos/builtin/packages/r-rcppeigen/package.py
- var/spack/repos/builtin/packages/r-rstan/package.py
- var/spack/repos/builtin/packages/r-stanheaders/package.py
New verison of rstan, and corresponding new versions of r-rcppeigen and r-stanheaders
> r-rstan: new version and dependents

- var/spack/repos/builtin/packages/pv/package.py
> pv: initial commit

- var/spack/repos/builtin/packages/netlib-lapack/ibm-xl.patch
- var/spack/repos/builtin/packages/netlib-lapack/package.py
Changed netlib-lapack spackage file to add Fortran flags correctly for XL compiler.
> Changed netlib-lapack to fix an error in the CMake setup.

- var/spack/repos/builtin/packages/cube/package.py
- var/spack/repos/builtin/packages/opari2/package.py
- var/spack/repos/builtin/packages/otf2/package.py
- var/spack/repos/builtin/packages/scorep/package.py
Works for me, but it would be great if someone else could test this, too.
> Update scorep and friends to newest versions

- var/spack/repos/builtin/packages/trinity/package.py
> trinity: add perl+threads dependency

- lib/spack/docs/getting_started.rst
I added a bit of additional information.
I'm unsure about my RestructuredText markup, feedback welcome.
Closes #8209
> Add info about haveged to gpg/randomness note

- var/spack/repos/builtin/packages/bazel/fix_env_handling-0.13.0.patch
- var/spack/repos/builtin/packages/bazel/package.py
Added versions 0.12.0 and 0.13.0 and updated the necessary patch.
> Add latest versions of bazel

- var/spack/repos/builtin/packages/flang/package.py
Fix #7885 (together with #8272).
> flang: add non-develop version

- var/spack/repos/builtin/packages/gdal/package.py
- var/spack/repos/builtin/packages/gdal/uuid.patch
Also adds dozens of optional dependencies.
Still needs a lot of testing.
> Add GDAL 2.3.0

- var/spack/repos/builtin/packages/openfst/package.py
This adds FAR support as a variant
> Add far variant to openfst package

- var/spack/repos/builtin/packages/nasm/package.py
> nasm: Fix compilation with GCC 8

- lib/spack/docs/packaging_guide.rst
Fixes #8268 
@davydden @mcneish1
> Document specs with multiple version ranges

- lib/spack/docs/tutorial_configuration.rst
fixes https://github.com/spack/spack/issues/7141
> improve Advanced Compiler Configuration part of tutorial

- var/spack/repos/builtin/packages/eospac/package.py
This PR just adds support to build/install 6.4.0beta2.
> make provision to install version 6.4.0beta.2

- var/spack/repos/builtin/packages/phast/package.py
> New package: phast

- var/spack/repos/builtin/packages/eospac/package.py
This PR just provides sane version names for the various releases of this package.
> clean up version names

- var/spack/repos/builtin/packages/libhio/package.py
version(' @1.4.1.2', '38c7d33210155e5796b16d536d1b5cfe')
@junghans 
@hppritcha
> libhio: added version 1.4.1.2

- var/spack/repos/builtin/packages/py-numpy/package.py
- var/spack/repos/builtin/packages/py-scikit-learn/package.py
- var/spack/repos/builtin/packages/py-scipy/package.py
py-scikit-learn: added version 0.19.1
py-numpy: added version 1.14.3
py-scipy: added version 1.1.0
> py-scikit-learn: updated version and dependencies

- var/spack/repos/builtin/packages/sz/package.py
We release a new version for SZ, in which there are some useful functions added.
Details about versions are README of http://github.com/disheng222/SZ
Thanks.
> add 1.4.13.4 for SZ

- var/spack/repos/builtin/packages/r-splitstackshape/package.py
Add new package: r-splitstackshape.
> r-splitstackshape: Create new package.

- var/spack/repos/builtin/packages/isaac-server/package.py
Forgot to bump this package with the library release in  #6152
> ISAAC Server 1.3.3

- var/spack/repos/builtin/packages/py-numpy/package.py
the type 'test' exists now :-)
> numpy: nosetest

- var/spack/repos/builtin/packages/r-jomo/package.py
- var/spack/repos/builtin/packages/r-mitml/package.py
- var/spack/repos/builtin/packages/r-pan/package.py
new package r-mitml and its denpendency r-jomo and r-pan.
> r-mitml: new package and its dependency r-jomo and r-pan

- var/spack/repos/builtin/packages/py-psutil/package.py
> add version 5.4.5 to py-psutil

- var/spack/repos/builtin/packages/fermisciencetools/package.py
New package fermisciencetools.
> Fermi Science Tools: New package

- var/spack/repos/builtin/packages/scotch/metis-headers-6.0.4.patch
- var/spack/repos/builtin/packages/scotch/package.py
Updated scotch to release from 2018-02-15, included patch described at https://gforge.inria.fr/tracker/?func=detail&atid=1082&aid=19521&group_id=248
> new version scotch@6.0.5a

- var/spack/repos/builtin/packages/r-mice/package.py
> r-mice: new package

- var/spack/repos/builtin/packages/boost/package.py
fix https://github.com/spack/spack/issues/8437
@chissg ping.
> boost: fix cxxstd=default

- var/spack/repos/builtin/packages/quantum-espresso/package.py
The patch to select ELPA API needs to be applied to version 6.2.0 too.
The link line of hdf5 is computed incorrectly from the configuration part of the build-system. To fix this the relevant file (make.inc) is patched.
> Fixed compilation of quantum-espresso

- var/spack/repos/builtin/packages/isaac-server/package.py
- var/spack/repos/builtin/packages/isaac/package.py
New ISAAC release, [version 1.4.0](https://github.com/ComputationalRadiationPhysics/isaac/releases/tag/v1.4.0).
> Package: ISAAC 1.4.0

- var/spack/repos/builtin/packages/glvis/package.py
Also, update all checksums to be SHA-256.
Building the new version (3.4) requires PR #8453.
> [GLVis] Add new version: 3.4

- var/spack/repos/builtin/packages/blasr-libcpp/package.py
> blasr-libcpp: new package

- var/spack/repos/builtin/packages/mpilander/package.py
[MPILander](https://github.com/MPILander/MPILander) - There can only be one (MPI process)!
The final MPI implementation.
> Add: MPILander

- var/spack/repos/builtin/packages/mfem/mfem-3.3-3.4-petsc-3.9.patch
- var/spack/repos/builtin/packages/mfem/mfem-3.4.patch
- var/spack/repos/builtin/packages/mfem/package.py
- var/spack/repos/builtin/packages/mfem/test_builds.sh
Add a new version (3.4.0) and a new variant (pumi).
> [MFEM] New version: 3.4

- var/spack/repos/builtin/packages/xsdk/package.py
cc: @goxberry @tzanio @markcmiller86 @acfisher @v-dobrev
cc:  @jwillenbring @davydden 
fixes #8460
> xsdk: update xsdk@develop dependency on mfem@develop

- var/spack/repos/builtin/packages/geopm/package.py
Update to latest version https://github.com/geopm/geopm/releases/tag/v0.5.0
> geopm: Update to version 0.5.0

- var/spack/repos/builtin/packages/gdal/package.py
Fixes #8469.
I accidentally broke our GDAL Python binding support in #8263 when I removed the `py-numpy` dependency. GDAL doesn't have great installation documentation, and `numpy` isn't listed anywhere, so it got lost in the sea of dependencies. If you dig deep enough and read the `swig/python/setup.py` file, you'll see that `numpy` is an optional dependency needed to convert GeoTIFF files read by GDAL into numpy arrays.
GDAL was also installing its Python bindings directly to the `site-packages` directory of the Python installation prefix, not to the GDAL installation prefix. This is now fixed.
I also added import tests. If you run `spack install --test=root gdal+python`, Spack will try to import common `osgeo` modules. Hopefully this will catch things next time someone erroneously …
> Fix GDAL Python bindings and add import tests

- var/spack/repos/builtin/packages/superlu-dist/package.py
==> Trying to clone git repository: https://github.com/xiaoyeli/superlu_dist at tag master
Fetching tags only, you probably meant:
git fetch --tags
@keitat @jwillenbring @xiaoyeli
> superlu_dist: 'master' is branch - not tag

- var/spack/repos/builtin/packages/nalu-wind/package.py
- var/spack/repos/builtin/packages/nalu/package.py
We have a new version of Nalu, called Nalu-Wind, for our exascale project that I am adding with this pull request. I am also updating Nalu to allow for building with shared libraries. They also don't build against anything but the `master` and `develop` branches of Trilinos for the foreseeable future.
> Updates to Nalu package(s)

- var/spack/repos/builtin/packages/albany/package.py
* Add package.py to support the Albany GitHub project builds.
* Update the Trilinos package.py script to provide additional
options needed for Albany.
> Albany: Add Albany package.

- var/spack/repos/builtin/packages/glib/package.py
> glib: Update to 2.56.1

- var/spack/repos/builtin/packages/openpmd-api/package.py
update the dependencies of openPMD-api
> openPMD-api: update dependencies

- var/spack/repos/builtin/packages/poppler/package.py
The old one is no longer there
> poppler needs it test repo URL updated

- var/spack/repos/builtin/packages/silo/package.py
To benefit from updates to config.guess for newer architectures.
More info: https://github.com/spack/spack/issues/2063
> silo: Make silo use AutotoolsPackage

- var/spack/repos/builtin/packages/ncbi-magicblast/package.py
Added new package ncbi-magicblast
> New package ncbi-magicblast

- lib/spack/spack/main.py
- This adds `spack -H`, which does the same thing as `spack help --all`
- I've also intuitively told users to type this and I've been wrong b/c it doesn't exist.
- I keep typing this accidentally based on `spack test -h` and `spack test -H`, and this PR finally makes my fingers happy.
> help: add `spack -H` shortcut for `spack help --all`

- var/spack/repos/builtin/packages/coreutils/package.py
Add latest version of coreutils.
> coreutils: add version 8.29

- var/spack/repos/builtin/packages/perl-compress-raw-bzip2/package.py
- var/spack/repos/builtin/packages/perl-compress-raw-zlib/package.py
- var/spack/repos/builtin/packages/perl-io-compress/package.py
Recreate a RP due to #8080 was closed unexpectedly.
> A new perl package: perl-io-compress.

- share/spack/docker/docker-compose.yml
- share/spack/docker/spack_scilinux/Dockerfile
- share/spack/docker/spack_scilinux/handle-prompt.sh
- share/spack/docker/spack_scilinux/handle-ssh.sh
- share/spack/docker/spack_scilinux/modules.yaml
Adding a Dockerfile for SL7 because running in the centos docker image I cannot install buildcache files created on my SL7 desktop.
> Add Dockerfile for Scientific Linux 7 (RHEL7 recompile)

- var/spack/repos/builtin/packages/nmap/package.py
Not much new here, just a new version of nmap to a add availability.
> Added nmap version 7.70

- var/spack/repos/builtin/packages/bml/package.py
- var/spack/repos/builtin/packages/latte/package.py
- var/spack/repos/builtin/packages/qmd-progress/package.py
> latte and friends: version bump

- var/spack/repos/builtin/packages/py-pyserial/package.py
Not sure how this ever successfully installed. @healther
> Fix base class for py-pyserial

- var/spack/repos/builtin/packages/py-rpy2/package.py
> added rpy2 2.9.4 and added py-jinja2 dependency

- var/spack/repos/builtin/packages/ncbi-toolkit/package.py
> ncbitoolkit: Create new package.

- var/spack/repos/builtin/packages/of-precice/package.py
- var/spack/repos/builtin/packages/precice/package.py
preCICE (Precise Code Interaction Coupling Environment) is a
coupling library for partitioned multi-physics simulations.
Partitioned means that preCICE couples existing programs (solvers)
capable of simulating a subpart of the complete physics involved in
a simulation.
of-precice: new package
preCICE adapter for OpenFOAM
Closes #8643
> precice: new package (issue #8643)

- var/spack/repos/builtin/packages/express/package.py
similar to #7447 this needs to handle the change in bamtools lib location
> express: bamtools lib handling

- lib/spack/docs/getting_started.rst
- lib/spack/spack/fetch_strategy.py
This makes it similar to what the URL strategy prints.
> fetch: remove 'trying' when cloning repos

- var/spack/repos/builtin/packages/gtkorvo-atl/package.py
- var/spack/repos/builtin/packages/gtkorvo-dill/package.py
- var/spack/repos/builtin/packages/gtkorvo-enet/package.py
- var/spack/repos/builtin/packages/libevpath/package.py
- var/spack/repos/builtin/packages/libffs/package.py
Version updates for packages from the GTKorvo suite.
> Gtkorvo updates

- var/spack/repos/builtin/packages/openmpi/package.py
> openmpi: add 3.1.1

- var/spack/repos/builtin/packages/mitofates/DirichletRegulator_fast.patch
- var/spack/repos/builtin/packages/mitofates/package.py
Mitofates was not actually working, this passes our test now
depends on #8672 and #8671
> mitofates: more deps and a patch to make it functional

- var/spack/repos/builtin/packages/flang/package.py
- var/spack/repos/builtin/packages/pgmath/package.py
Fix #8072 
/cc @MarquitoForrest @sscalpone
> flang: add support for llvm-6

- var/spack/repos/builtin/packages/py-backcall/package.py
As discussed in ```https://github.com/spack/spack/pull/8309```
> Add py-backcall

- bin/spack
- lib/spack/spack/cmd/clean.py
closes #8608 
* update help of `clean --all` to include `-p`
* remove old orphaned .pyc removal
@adamjstewart will the first line work this way?
> clean up of spack clean

- var/spack/repos/builtin/packages/lammps/package.py
> lammps: added v20180629

- var/spack/repos/builtin/packages/perl/package.py
> Make read only source file writeable in perl before patch

- var/spack/repos/builtin/packages/beast1/package.py
> beast1: add libbeagle support

- README.md
This adds a link to [@spackpm](https://twitter.com/spackpm) to `README.md`
> readme: add our @spackpm Twitter handle

- var/spack/repos/builtin/packages/mfem/package.py
> mfem: mfem-3.3-3.4-petsc-3.9.patch is not needed for latest develop version

- var/spack/repos/builtin/packages/templight-tools/package.py
- var/spack/repos/builtin/packages/templight/develop-20180720.patch
- var/spack/repos/builtin/packages/templight/package.py
Here is an attempt to package [Templight](https://github.com/mikael-s-persson/templight), a clang patch/wrapper which allows C++ developers to profile the effect of template instantiations on compilation times and compiler memory consumption, and to interactively walk through templight instantations in a GDB-like fashion in order to more quickly resolve template metaprogramming bugs. This is very useful whenever doing any advanced C++ programming, or dealing with libraries that do.
This package needed a bit of work. The main reason is that the templight authors believe that the only road towards templight stabilization is to have it integrated into upstream LLVM, and therefore did not bother with a proper release process, in spite of numerous user requests. As of today, the official build …
> Templight package

- var/spack/repos/builtin/packages/tasmanian/package.py
* added Tasmanian versions 5.1
* added Tasmanian development version (future 6.0)
* added options through `+~` flags
* added and tested the `+xsdkflags`
> updated Tasmanian spack with latest options

- var/spack/repos/builtin/packages/libunwind/package.py
Document a conflict on Darwin discussed in #8823.
> libunwind: document platform=darwin conflict

- lib/spack/docs/repositories.rst
- lib/spack/docs/tutorial.rst
- lib/spack/docs/tutorial_advanced_packaging.rst
Todd - just testing a few things with Margaret - take these edits or leave them, your choice!
> docs: minor text changes

- var/spack/repos/builtin/packages/laghos/package.py
> Update hompage for laghos

- var/spack/repos/builtin/packages/py-biom-format/package.py
> Py biom format fix

- var/spack/repos/builtin/packages/openmpi/package.py
The current version of openmpi gets configuration errors when the schedulars=slurm this is due to notbeing able to find the pmi library.  And as it turns out you will get execution errors from slurm that it is not using its own pmi library.  So I created the slurm requirement and pointed to slurm to show where to get the pmi library.
Secondly, I got build errors when the fabrics=mxm due to not having the libiberty library available and added the binutils+libiberty dependency.
> Fix openmpi to work with slurm/pmi and mxm

- var/spack/repos/builtin/packages/xsd/package.py
This PR adds a package for XSD CodeSynthesis (https://www.codesynthesis.com/products/xsd/).
> xsd: added XSD package

- var/spack/repos/builtin/packages/amg/package.py
- var/spack/repos/builtin/packages/amg2013/package.py
- var/spack/repos/builtin/packages/kripke/package.py
- var/spack/repos/builtin/packages/lcals/package.py
- var/spack/repos/builtin/packages/lulesh/package.py
Fixes #8846 
Fixes #8847 
Fixes #8848 
Fixes #8849
> Update broken codesign.llnl.gov urls

- var/spack/repos/builtin/packages/simplemoc/package.py
> simplemoc: version bump

- var/spack/repos/builtin/packages/kim-api/package.py
> kim-api: initial commit

- lib/spack/docs/known_issues.rst
> Remove default variant bug from list of known issues

- var/spack/repos/builtin/packages/glvis/package.py
- var/spack/repos/builtin/packages/mesa-glu/package.py
- var/spack/repos/builtin/packages/mesa/package.py
- var/spack/repos/builtin/packages/opengl/package.py
- var/spack/repos/builtin/packages/openglu/package.py
Also fix dependency version in glvis package.
Fixes build errors mentioned in #8454.
@imnasnainaec Can you see if this solves all of your build problems?
> Add libs attribute to mesa and mesa-glu packages

- share/spack/templates/modules/modulefile.tcl
Rebase of #7807 
closes #7807 
fixes #7806
@TheQueasle Can you have a look at this? I'll rebase and merge if it's fine with you (that should keep authorship of the two commits in the PR).
> Fix error during 'module whatis'

- var/spack/repos/builtin/packages/axl/package.py
- var/spack/repos/builtin/packages/er/package.py
- var/spack/repos/builtin/packages/kvtree/package.py
- var/spack/repos/builtin/packages/rankstr/package.py
- var/spack/repos/builtin/packages/redset/package.py
- var/spack/repos/builtin/packages/shuffile/package.py
- var/spack/repos/builtin/packages/veloc/package.py
Update of several dependencies for official 1.0 release.
> ECP VELOC Package update

- var/spack/repos/builtin/packages/amrex/package.py
- var/spack/repos/builtin/packages/xsdk/package.py
> xsdk: add slepc and amrex [and handle clang conflict wrt amrex]

- var/spack/repos/builtin/packages/r-genomicranges/package.py
moved around some where clauses for consistency with other bioconductor packages
> r-genomicranges: new version

- var/spack/repos/builtin/packages/cdo/package.py
hi guys!
just added the two lastest release of CDO
> add cdo releases 1.9.4 and 1.9.5

- var/spack/repos/builtin/packages/lammps/package.py
> lammps: add v20180822

- var/spack/repos/builtin/packages/range-v3/package.py
This is a range library for C++ which aims to be a testbed for eventual language standardization.
> range-v3 package

- var/spack/repos/builtin/packages/braker/package.py
Use augustus@3.2.3 as dependency because latest version shows sam.h not found.
> braker: add new version 2.1.0

- var/spack/repos/builtin/packages/gasnet/package.py
> gasnet: version bump

- var/spack/repos/builtin/packages/channelflow/package.py
Will update the package in a following PR, as soon as a release tag is available.
> New package: channelflow

- var/spack/repos/builtin/packages/gdal/package.py
Successfully builds on Blue Waters using GCC 7.3.0.
> GDAL: add version 2.3.1

- var/spack/repos/builtin/packages/codes/codes-1.0.0.patch
- var/spack/repos/builtin/packages/codes/package.py
> New package: CODES simulation framework

- var/spack/repos/builtin/packages/py-picrust/package.py
> Feature/py picrust New Package

- var/spack/repos/builtin/packages/r-summarizedexperiment/package.py
according to: https://bioconductor.org/packages/3.5/bioc/html/SummarizedExperiment.html 
biocgenerics should have also been a dependency of the older version, so added that
> r-summarizedexperiment: new version

- var/spack/repos/builtin/packages/xsdk/package.py
fixes https://github.com/spack/spack/issues/9189
> xsdk: disable assimp in deal.II

- var/spack/repos/builtin/packages/py-espresso/2244.patch
- var/spack/repos/builtin/packages/py-espresso/package.py
For https://github.com/espressomd/espresso/issues/1032
> py-espresso: added v4.0.0

- var/spack/repos/builtin/packages/python/package.py
Fixes bugs 2 and 3 from #9154.
This solution should be more robust and elegant, and uses fewer lines of code.
> Improve spec['python'].command support for bwpy

- var/spack/repos/builtin/packages/comd/package.py
- var/spack/repos/builtin/packages/ecp-proxy-apps/package.py
> ecp-proxy-apps: update dependencies for release 1.0 and 1.1

- var/spack/repos/builtin/packages/mxnet/package.py
There were multiple issues getting this to compile with spack's nnvm and dmlc.
I switched the build to use the distributions included with the mxnet source.
> mxnet: added 1.3.0

- var/spack/repos/builtin/packages/motioncor2/package.py
older versions no longer listed on homepage
> motioncor2 - added version 1.1.0 and removed old versions

- var/spack/repos/builtin/packages/py-networkx/package.py
> py-networkx: new version

- var/spack/repos/builtin/packages/miniamr/package.py
> miniamr: added v1.4.1

- var/spack/repos/builtin/packages/plumed/package.py
updating plumed to support newer version of gromacs
> plumed: updating plumed to latest version

- var/spack/repos/builtin/packages/eigen/package.py
> add eigen@3.3.5

- var/spack/repos/builtin/packages/breakdancer/package.py
* perl dependencies weren't there
* added the last release in addition to the master branch
* put perl program in the path
> breakdancer: fix several issues

- var/spack/repos/builtin/packages/dotnet-core-sdk/package.py
Changed to fixed 'install_tree' function desired in #8751 .
> dotnet-core-sdk: install_tree

- var/spack/repos/builtin/packages/rdma-core/package.py
See [this](https://github.com/spack/spack/pull/9072#issuecomment-421492369).
> Update rdma-core : new version and conflict with intel

- lib/spack/spack/util/executable.py
If a Spack `Executable` is run with `error`/`output` set as `str`, those outputs from the process are captured. If the process fails, Spack was not reporting them as part of the exception (so that information was lost).
Cases where `error`/`output` are set to be a file or were unspecified (in which case the parent process streams are used) were not an issue.
> report error/output for failed processes when stderr is captured

- var/spack/repos/builtin/packages/minivite/package.py
cc: @junghans. I just have to add the release tag.
> miniVite: new package

- var/spack/repos/builtin/packages/r-processx/package.py
Requires package introduced in #9341.
> r-processx: new package starting at 3.1.0

- var/spack/repos/builtin/packages/cuda/package.py
> Added Cuda 10

- var/spack/repos/builtin/packages/tcl/package.py
- var/spack/repos/builtin/packages/tk/package.py
> Set libs property for tcl and tk

- var/spack/repos/builtin/packages/perl-cgi/package.py
No longer included in Perl as of 5.20.
> perl-cgi: new package starting at 4.37

- var/spack/repos/builtin/packages/picsarlite/package.py
also removed variants which shouldn't be there
> PICSARlite: actually builds PICSARlite now instead of PICSAR

- var/spack/repos/builtin/packages/claw/package.py
- New package file for the CLAW Compiler project: https://claw-project.github.io/
* The CLAW Compiler is a Fortran source-to-source compiler targeting performance portability problem   in climate and weather model.
> CLAW Compiler: Add Spack Package

- var/spack/repos/builtin/packages/paraview/package.py
This PR includes new versions to build/install.
> ParaView version bump

- var/spack/repos/builtin/packages/sundials/package.py
Add SUNDIALS 3.2.0 and 4.0.0-dev.2 releases.
> SUNDIALS: add new versions

- var/spack/repos/builtin/packages/mesa/package.py
Apparently this dependency was missing.
> Package mesa: added dependency on zlib

- var/spack/repos/builtin/packages/charliecloud/package.py
> add Charliecloud 0.9.2 and 0.9.3

- var/spack/repos/builtin/packages/pacvim/package.py
No FixMe's, working installation
> Pacvim new

- var/spack/repos/builtin/packages/pplacer/package.py
Simple package - copies files and directory out of a zip file
> New package: pplacer

- var/spack/repos/builtin/packages/tldd/package.py
* https://gitlab.com/miscripts/tldd
> New package: tldd

- var/spack/repos/builtin/packages/nlohmann-json/package.py
> Added nlohmann-json v3.3.0

- var/spack/repos/builtin/packages/matlab/package.py
Newest version of Matlab: R2018b
> matlab: new version

- var/spack/repos/builtin/packages/openblas/package.py
see https://github.com/xianyi/OpenBLAS/issues/1735#issuecomment-422954465 and https://github.com/xianyi/OpenBLAS/issues/1761#issuecomment-421039174
> openblas: fix experimental USE_TLS makefile option

- var/spack/repos/builtin/packages/ncdu/package.py
This project has updated it's revisions.  I ran spack checksum and upgraded the package.
> Upgrading ncdu versions.

- lib/spack/spack/report.py
- lib/spack/spack/reporters/cdash.py
* Better default arguments
* Improve documentation to include a usage example
> Make CDash reporting easier to use

- var/spack/repos/builtin/packages/superlu-dist/package.py
Update spack script of superlu-dist to use CMake build
> Update superlu-dist package.py to support latest release v6.0.0

- var/spack/repos/builtin/packages/libepoxy/package.py
- Add missing pkgconfig dependency
- Explicitly disable egl
> libepoxy: fix build

- var/spack/repos/builtin/packages/codes/package.py
- var/spack/repos/builtin/packages/dia/package.py
- var/spack/repos/builtin/packages/nest/package.py
pkgconfig is the virtual provider, pkg-config is a specific implementation.
> codes, dia, nest: fix pkg-config dependency

- var/spack/repos/builtin/packages/superlu-dist/package.py
fixes https://github.com/spack/spack/issues/9514
> superlu-dist: fix v5.3.0 buid - its attempting to build internal blas

- var/spack/repos/builtin/packages/cube/package.py
- var/spack/repos/builtin/packages/cubelib/package.py
- var/spack/repos/builtin/packages/cubew/package.py
- var/spack/repos/builtin/packages/opari2/package.py
- var/spack/repos/builtin/packages/scorep/package.py
- cube: Add 4.4.2, add conflicts for ~gui
- cubelib: Add 4.4.2
- cubew: Add 4.4.1
- opari2: Add 2.0.4
- scorep: Add 4.1
> Update scorep and friends

- var/spack/repos/builtin/packages/sra-toolkit/package.py
* before the same files were copied 3 times
> sra-toolkit: new version and installation fix

- var/spack/repos/builtin/packages/ssht/package.py
SSHT is a fast spin-weighted spherical harmonic transform library.
(ssht github)[https://github.com/astro-informatics/ssht]
> ssht: new package

- var/spack/repos/builtin/packages/cabana/package.py
> cabana: initial commit

- var/spack/repos/builtin/packages/omega-h/package.py
> Fixes to Omega_h C++ compiler flags

- var/spack/repos/builtin/packages/omega-h/package.py
> omega-h: update to versions 9.19.0, 9.19.1

- var/spack/repos/builtin/packages/py-hdfs/package.py
> py-hdfs: new package

- var/spack/repos/builtin/packages/r-animation/package.py
Added a list_url variable. Works.
> ranimation: added list_url

- var/spack/repos/builtin/packages/qt/package.py
Tested with cube, seems to work fine.
> qt: add 5.11.2

- var/spack/repos/builtin/packages/binutils/package.py
Added version available in RHEL/Centos 7
> Added old binutils version

- var/spack/repos/builtin/packages/warpx/package.py
This is the cleaned up pull request for the new package, warpx
> warpx: new package

- var/spack/repos/builtin/packages/jdk/package.py
Fixes https://github.com/spack/spack/issues/9582
> jdk: added 11.0.1

- var/spack/repos/builtin/packages/dbcsr/package.py
- var/spack/repos/builtin/packages/py-fypp/package.py
@dev-zero @alazzaro FYI. ~~I would appreciate if you could confirm the manual installation phase.~~
> dbcsr: add new package

- var/spack/repos/builtin/packages/dftfe/package.py
* has been tested with gcc 6.4.0 and intel/18
> New package: DFT-FE

- var/spack/repos/builtin/packages/plasma/package.py
> plasma: 18.10.0 update

- var/spack/repos/builtin/packages/flux-core/package.py
- var/spack/repos/builtin/packages/flux-sched/package.py
- Keep dependencies up to date with recent flux develop.
- Add new flux-sched release.
- Fix git tags not being available in certain circumstances.
- Fix typo in variant name
> flux-core & flux-sched: update versions and dependencies, fix git tags

- lib/spack/spack/modules/common.py
- lib/spack/spack/test/data/modules/tcl/autoload_with_constraints.yaml
- lib/spack/spack/test/modules/tcl.py
fixes #9624 
Changes:
@SteVwonder
> Fix autoload of direct dependencies for python

- var/spack/repos/builtin/packages/cabana/package.py
For https://github.com/ECP-copa/Cabana/issues/1
> cabana: added v0.1.0

- var/spack/repos/builtin/packages/damaris/package.py
Added support for VisIt and Catalyst dependencies in Damaris.
Also changed the commit hash to a git tag.
> damaris: added support for VisIt and Catalyst

- var/spack/repos/builtin/packages/diy/package.py
[DIY](https://github.com/diatomic/diy) is a data-parallel header-only C++ library.
> diy: new package

- var/spack/repos/builtin/packages/strumpack/package.py
> strumpack: update to version 3.1.1

- var/spack/repos/builtin/packages/vtk/package.py
In #9510 I left some stuff from copy/paste. Removing them.
> vtk: Fix leftovers

- var/spack/repos/builtin/packages/regcm/package.py
Hi,
I wrote a new package for RegCM, a regional climate model simulator software by ICTP: https://gforge.ictp.it/gf/project/regcm/
Any feedbacks are appreciated.
> New package for RegCM, regional climate model.

- var/spack/repos/builtin/packages/henson/package.py
[Henson](https://github.com/mrzv/henson) is a tool for in situ processing, using cooperative multitasking.
> henson: new package

- var/spack/repos/builtin/packages/freetype/package.py
> freetype: make sure freetype-config is enabled in 2.9.1:

- var/spack/repos/builtin/packages/dealii/package.py
- var/spack/repos/builtin/packages/muparser/package.py
fixes https://github.com/spack/spack/issues/9723
@jthies please test.
> muparser: minor fixes to 2.2.5 and add 2.2.6 with CMake

- etc/spack/defaults/config.yaml
- lib/spack/docs/config_yaml.rst
> Minor changes to Basic Settings docs for SC18

- lib/spack/docs/tutorial_configuration.rst
> Updates to Configuration Tutorial for SC18

- lib/spack/docs/tutorial.rst
- lib/spack/docs/tutorial_environments.rst
- tutorial goes through three sections:
- installing and uninstalling environments
- dealing with many specs
- spack.yaml and spack.lock and workflows
> docs: add environments tutorial

- var/spack/repos/builtin/packages/r-convevol/package.py
depends on package introduced in #9766
> r-convevol: new package at 1.3

- var/spack/repos/builtin/packages/r-manipulatewidget/package.py
depends on packages and fixes in #9823, #9824, #9730 
supplies new dependency for #9796
> r-manipulatewidget: new package at 0.10.0

- var/spack/repos/builtin/packages/gnuplot/package.py
fixes https://github.com/spack/spack/issues/9721
> gnuplot: add X11 dependency and QT terminal

- var/spack/repos/builtin/packages/nlohmann-json/package.py
> nlohmann-json: 3.4.0

- var/spack/repos/builtin/packages/flatcc/package.py
flatcc is going to be a dependency for the UnifyCR project and we'd like to maintain a simple Spack build with all of our dependencies.
> flatcc: new package

- var/spack/repos/builtin/packages/libmesh/package.py
Updates to libMesh:
-- added v1.3.1 checksum
-- added vtk variant
-- bugfix for enabling petsc when slepc variant is specified
> Updates to libMesh

- var/spack/repos/builtin/packages/axel/package.py
- var/spack/repos/builtin/packages/mscgen/package.py
- var/spack/repos/builtin/packages/py-pyarrow/package.py
- var/spack/repos/builtin/packages/unifycr/package.py
pkgconfig is the correct virtual provider.
> Fix pkg-config dependencies

- var/spack/repos/builtin/packages/dcmtk/package.py
Add new package dcmtk.  All optional dependencies which exist in spack are expressed as variants.
> New package: dcmtk

- var/spack/repos/builtin/packages/openimageio/package.py
Add new package openimageio.  Note that this depends on an updated version of openexr in PR #9714
> New package: openimageio

- lib/spack/docs/tutorial_modules.rst
Found a couple bugs while trying to copy and paste the exact tutorial content.
> Fix bugs in Modules Tutorial

- var/spack/repos/builtin/packages/claw/package.py
@alalazo Just added the latest version available
> CLAW Compiler: add new version 1.2.0 to the package

- var/spack/repos/builtin/packages/nyancat/package.py
Because sometimes silly programs can be useful.
> New Package: Nyancat

- var/spack/repos/builtin/packages/nginx/package.py
> nginx: add 1.15.6

- var/spack/repos/builtin/packages/argobots/package.py
Added `develop` version (taking code from git) and `+valgrind` variant.
> Argobots: added @develop version and +valgrind variant

- var/spack/repos/builtin/packages/citcoms/package.py
- var/spack/repos/builtin/packages/exchanger/package.py
- var/spack/repos/builtin/packages/fstrack/package.py
- var/spack/repos/builtin/packages/gmt/package.py
- var/spack/repos/builtin/packages/gmt/type.patch
- var/spack/repos/builtin/packages/hc/package.py
- var/spack/repos/builtin/packages/py-merlin/package.py
- var/spack/repos/builtin/packages/py-pythia/package.py
A friend of mine needed some geodynamics software so I helped her package it in Spack. Most of these seem to install okay, although we never got fstrack working correctly. But I figure a half-working package is better than no package. 
Installed successfully on both CentOS 7 and RHEL 7.
@asemple243
> Add GMT, CitcomS, and fstrack packages

- var/spack/repos/builtin/packages/py-cython/package.py
> py-cython: add new versions

- var/spack/repos/builtin/packages/mixcr/package.py
This new package will install [MiXCR](https://mixcr.readthedocs.io/en/master/index.html), which is a universal software for fast and accurate analysis of T- and B- cell receptor repertoire sequencing data.
> mixcr: Added a new package for MiXCR.

- var/spack/repos/builtin/packages/samtools/package.py
> samtools: add zlib/bzip2 dependency for versions 1.2 to 1.6

- var/spack/repos/builtin/packages/pango/package.py
takes care of #9894 for package pango.
> package/pango: disable gtk-docs

- var/spack/repos/builtin/packages/r-geomorph/package.py
> r-geomorph: new version

- var/spack/repos/builtin/packages/harfbuzz/package.py
disable building of gtk-docs and hence take care of #9885 
also add new version
> package/harfbuzz: disable building of gtk-docs, add new version

- var/spack/repos/builtin/packages/circos/package.py
depends on perl packages introduced in #9760
> circos: new package starting at 0.69-6

- var/spack/repos/builtin/packages/perl-clone/package.py
- var/spack/repos/builtin/packages/perl-config-general/package.py
- var/spack/repos/builtin/packages/perl-extutils-config/package.py
- var/spack/repos/builtin/packages/perl-extutils-helpers/package.py
- var/spack/repos/builtin/packages/perl-extutils-installpaths/package.py
- var/spack/repos/builtin/packages/perl-math-bezier/package.py
- var/spack/repos/builtin/packages/perl-math-round/package.py
- var/spack/repos/builtin/packages/perl-math-vecstat/package.py
- var/spack/repos/builtin/packages/perl-module-build-tiny/package.py
- var/spack/repos/builtin/packages/perl-number-format/package.py
- var/spack/repos/builtin/packages/perl-params-validate/package.py
- var/spack/repos/builtin/packages/perl-readonly/package.py
- var/spack/repos/builtin/packages/perl-regexp-common/package.py
- var/spack/repos/builtin/packages/perl-scalar-list-utils/package.py
- var/spack/repos/builtin/packages/perl-set-intspan/package.py
- var/spack/repos/builtin/packages/perl-statistics-basic/package.py
- var/spack/repos/builtin/packages/perl-text-format/package.py
Didn't want to flood the PRs with all of these packages so they are bundled into a single commit.
> add several new perl modules

- var/spack/repos/builtin/packages/mercury/package.py
Added a package for the Mercury library.
> Package: Mercury

- var/spack/repos/builtin/packages/asciidoctor/package.py
Faster, easier to use, less impossible to install correctly
implementation of asciidoc.
> package: add asciidoctor gem

- var/spack/repos/builtin/packages/p4est/package.py
fixes https://github.com/spack/spack/issues/9912
> p4est: apply patches to 2.0 only

- var/spack/repos/builtin/packages/freexl/package.py
- var/spack/repos/builtin/packages/libspatialite/package.py
Includes a package for dependency freexl
> libspatialite: new package

- var/spack/repos/builtin/packages/r-bayesm/package.py
- var/spack/repos/builtin/packages/r-compositions/package.py
- var/spack/repos/builtin/packages/r-energy/package.py
Also includes r-energy, r-bayesm, as they are dependencies of this package
> r-compositions: new package, including its dependencies

- var/spack/repos/builtin/packages/p4est/package.py
> p4est: fix a typo

- var/spack/repos/builtin/packages/tfel/package.py
The TFEL package is described here: http://tfel.sourceforge.net/
> new package: add support for the tfel package

- var/spack/repos/builtin/packages/git/package.py
Also fixes instructions for new releases
> git: add version 2.19.2

- var/spack/repos/builtin/packages/plasma/package.py
Add PLASMA version 18.11.0 and Lua variant
> Add PLASMA version 18.11.0 and Lua variant

- var/spack/repos/builtin/packages/py-jupyter-console/package.py
- var/spack/repos/builtin/packages/py-jupyter-core/package.py
- var/spack/repos/builtin/packages/py-lxml/package.py
- var/spack/repos/builtin/packages/py-pexpect/package.py
- var/spack/repos/builtin/packages/py-pytables/package.py
- var/spack/repos/builtin/packages/py-terminado/package.py
- var/spack/repos/builtin/packages/py-zmq/package.py
Let me know if you want me to submit a separate PR for each of them.
> New versions for a few python modules

- var/spack/repos/builtin/packages/phist/package.py
previously #9849 (accidently force pushed in the branch)
@balay
> Phist 1.7.4

- var/spack/repos/builtin/packages/parallel-netcdf/package.py
Added latest versions. (1.10.0, 1.9.0, 1.8.1)
> PNETCDF: Update with current versions

- var/spack/repos/builtin/packages/py-pint/package.py
* **Pint** is a Python package to define, operate and manipulate physical quantities: the product of a numerical value and a unit of measurement. It allows arithmetic operations between them and conversions from and to different units. 
* https://pint.readthedocs.io/en/latest/
> Provide a new spackage for py-pint.

- var/spack/repos/builtin/packages/c-blosc/package.py
Add latest version of c-blosc.
> c-blosc: 1.15.0

- var/spack/repos/builtin/packages/dealii/package.py
https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html?highlight=HeaderList#tips-for-configuring-client-packages-to-use-mkl
> dealii: do not hardcode prefix.include for BLAS/LAPACK

- var/spack/repos/builtin/packages/biobloom/package.py
depends on sdsl-lite introduced in #10013
> biobloom: new package at 2.2.0

- var/spack/repos/builtin/packages/pfunit/mpi-test.patch
- var/spack/repos/builtin/packages/pfunit/package.py
> pfunit: add mpi-test patch

- var/spack/repos/builtin/packages/rust/package.py
> Rewrite Rust package

- var/spack/repos/builtin/packages/cdo/package.py
Not sure how this ever worked but something seems to have changed so we now have to use the correct URLs.
> cdo: fix URLs

- var/spack/repos/builtin/packages/scallop/package.py
> scallop: new package at 0.10.3

- var/spack/repos/builtin/packages/pumi/package.py
This PR adds a shared library variant to PUMI.
> pumi: shared variant

- var/spack/repos/builtin/packages/flux-core/package.py
- var/spack/repos/builtin/packages/flux-sched/package.py
> flux-core & flux-sched: fix compilation and dependencies

- var/spack/repos/builtin/packages/scr/package.py
added sha256 for SCR v1.2.0 - v1.2.2
> new SCR releases

- var/spack/repos/builtin/packages/boost/package.py
> boost: add 1.69.0

- var/spack/repos/builtin/packages/superlu-dist/package.py
> superlu-dist: update v6.1.0 checksum

- var/spack/repos/builtin/packages/elsd/package.py
- var/spack/repos/builtin/packages/elsdc/package.py
Needed this for a course project, so I decided to write a package for it.
Successfully built and tested on macOS Mojave 10.14.1 with Clang 10.0.0 and on Cray CNL5 (Blue Waters) with GCC 4.9.3.
> Add new packages for ELSD and ELSDc

- share/spack/spack-completion.bash
This PR updates Spack's Bash completion script. Several new commands and flags were added recently, especially with the addition of [Spack Environments](https://spack.readthedocs.io/en/latest/tutorial_environments.html).
> Update Spack's Bash completion script

- var/spack/repos/builtin/packages/cairo/package.py
PDF backend is needed by GTK+, which is still a work in progress.
> Add pdf variant to cairo

- var/spack/repos/builtin/packages/arrow/package.py
- var/spack/repos/builtin/packages/flatbuffers/package.py
Also unpin the version from the arrow package.
> flatbuffers: add 1.10.0

- var/spack/repos/builtin/packages/mapserver/package.py
I confess I have only tested the client-side part of this, and only the Python binding. The rest builds fine, but I have not actually tried to run a server with the result.
> mapserver: new package

- var/spack/repos/builtin/packages/libbsd/package.py
> Restrict patch to oldest version of libbsd

- var/spack/repos/builtin/packages/docbook-xml/package.py
Also simplifies the install method.
> Add list_url to docbook-xml

- var/spack/repos/builtin/packages/libxslt/package.py
I'm not sure if this actually works, but it's a step in the right direction. Also adds python import tests.
> Add python bindings to libxslt

- var/spack/repos/builtin/packages/openfoam-com/package.py
Latest version and md5sum. No other changes.
> OpenFOAM-v1812 - new version

- var/spack/repos/builtin/packages/r3d/package.py
This PR simply adds a Spackage for the R3D voxelization package.
> R3D spackage

- var/spack/repos/builtin/packages/petsc/package.py
> petsc-3.10.3: syncs with superlu-dist-6.1.

- var/spack/repos/builtin/packages/r-corhmm/package.py
> r-corhmm: new package at 1.22

- var/spack/repos/builtin/packages/dealii/package.py
> dealii: fix build with some Intel compilers

- var/spack/repos/builtin/packages/slepc/package.py
> slepc: fix homepage URL

- var/spack/repos/builtin/packages/mawk/package.py
> mawk: added 1.3.4_p20171017

- var/spack/repos/builtin/packages/pgmath/package.py
Workaround for https://github.com/flang-compiler/flang/issues/434#issuecomment-378159723 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901477.
Fix #10183
> pgmath: depend on awk

- var/spack/repos/builtin/packages/stata/package.py
I've tested this works on my systems and gives a successful install of STATA 15. I would like to get feedback for it to be included in Spack.
> Add Stata package

- var/spack/repos/builtin/packages/xgboost/package.py
Was originally introduced in #7699 but seems to have gone inactive pending changes.
> xgboost: new package at 0.81

- .travis.yml
Codecov upload was accidentally removed in #9805
> bugfix: add codecov upload back to travis.yml

- var/spack/repos/builtin/packages/fenics/package.py
> FEniCS: workaround concretization issue with PETSc

- var/spack/repos/builtin/packages/catch/package.py
Add the 2.5.0 release of catch2.
> Catch2: v2.5.0

- var/spack/repos/builtin/packages/osmctools/package.py
> Added package osmctools

- var/spack/repos/builtin/packages/py-html5lib/package.py
> new version 1.0.1 for py-html5lib

- var/spack/repos/builtin/packages/openpa/package.py
> Package OpenPA: added openpa package

- var/spack/repos/builtin/packages/bash/package.py
> Added bash 5.0

- var/spack/repos/builtin/packages/r-dbplyr/package.py
* added new versions
* tightened up `depends_on()` specs per https://cran.r-project.org/web/packages/dbplyr/index.html
> r-dbplyr: new versions

- var/spack/repos/builtin/packages/fish/package.py
> Updated fish to 3.0.0

- var/spack/repos/builtin/packages/eospac/package.py
> EOSPAC version bump

- var/spack/repos/builtin/packages/hpctoolkit/package.py
Add variants 'cray' and 'bgq' to build for Cray and Blue Gene compute
nodes.  These systems need separate options to find the MPI compiler
for hpcprof-mpi.
> hpctoolkit: variants to build for cray and blue gene

- lib/spack/spack/test/concretize.py
- var/spack/repos/builtin/packages/dealii/package.py
fixes https://github.com/spack/spack/issues/10281
@scottwittenburg FYI, please comment when this is ready to merge.
> dealii: fix concretization of xsdk package

- var/spack/repos/builtin/packages/libxslt/package.py
> Add libxslt v1.1.33 info

- var/spack/repos/builtin/packages/span-lite/package.py
Add [v0.4.0 of span-lite](https://github.com/martinmoene/span-lite/releases/tag/v0.4.0)
> Add span-lite version

- var/spack/repos/builtin/packages/r/package.py
Fixes #10348
@mforde84 @hartzell
> r requires cairo+pdf

- var/spack/repos/builtin/packages/py-modred/package.py
- var/spack/repos/builtin/packages/py-modred/v2x-setuptools-8.0.patch
Parallelized python module for finding modal decompositions and
reduced order models.
> py-modred: New package

- var/spack/repos/builtin/packages/hugo/package.py
> Add package for Hugo (static website generator)

- var/spack/repos/builtin/packages/py-whatshap/package.py
depends on packages introduced in #10375 and #10376
> py-whatshap: new package at 0.17

- share/spack/qa/run-docker-tests
Hopefully the last minor quirk in the way of docker images.
> fix issue where docker images were being pushed without login

- var/spack/repos/builtin/packages/py-espresso/package.py
> py-espresso: add v4.0.1

- var/spack/repos/builtin/packages/ncl/package.py
It seems that #10135 broke ncl.
> ncl: require cairo with pdf support

- var/spack/repos/builtin/packages/cudnn/package.py
this is needed for some versions pre-compiled code
> Add cudnn 7.2

- var/spack/repos/builtin/packages/slate/package.py
Added new package for the SLATE ECP project.
> New package for SLATE

- var/spack/repos/builtin/packages/r-pkgmaker/package.py
depends on new packages `r-runit`(#10416), `r-bibtex`(#10417)
> r-pkgmaker: add 0.27, new dependencies

- var/spack/repos/builtin/packages/hdf5/package.py
Add support for building the development branch of HDF5.
> HDF5: Add develop Version

- var/spack/repos/builtin/packages/plumed/package.py
> plumed: new versions

- var/spack/repos/builtin/packages/catch/package.py
Add the latest Catch2 release.
> Catch2: v2.6.0

- var/spack/repos/builtin/packages/augustus/package.py
build would fail due to bam2wig trying to load dependencies from $HOME, patches makefile to point to spack installations
> augustus: fix bam2wig auxprog build

- var/spack/repos/builtin/packages/mpark-variant/package.py
Add the latest release of Michael Park's C++ Variant lib.
> MPark: Variant v1.4.0

- var/spack/repos/builtin/packages/wordnet/package.py
This new package installs [Wordnet](https://wordnet.princeton.edu/).
> wordnet: Added package for WordNet.

- var/spack/repos/builtin/packages/py-black/package.py
- var/spack/repos/builtin/packages/py-toml/package.py
Also adds a new version of py-toml based on py-black's dependencies.
> Add py-black

- var/spack/repos/builtin/packages/jdk/package.py
> jdk: add version 1.8.0_202

- var/spack/repos/builtin/packages/phrap-crossmatch-swat/package.py
licensed package -- developers must be directly contacted by email
> phrap-crossmatch-swat: new package at 1.090518

- var/spack/repos/builtin/packages/py-libensemble/package.py
- var/spack/repos/builtin/packages/py-petsc4py/package.py
- py-petsc4py: add in py-petsc4py@develop support
- py-libensemble: add py-libensemble@develop dependency on py-petsc4py@develop
cc: @shuds13
> petsc4py and libensemble: add @develop dependencies

- var/spack/repos/builtin/packages/repeatmasker/package.py
depends on phrap-crossmatch-swat introduced in #10529
> repeatmasker: add variant for cross_match engine

- lib/spack/spack/build_systems/cuda.py
follow up to https://github.com/spack/spack/pull/10460/
> CudaPackage: fix wrong version range

- lib/spack/llnl/util/tty/__init__.py
- lib/spack/spack/fetch_strategy.py
- lib/spack/spack/main.py
- lib/spack/spack/package.py
- lib/spack/spack/test/cmd/install.py
- Include millisecond timestamps when debugging output (-d) is enabled.
- Add support for tty suppression.
> Spack tty features

- var/spack/repos/builtin/packages/catch/package.py
add the lastest bugfix release of Catch2
> Catch2: v2.6.1

- var/spack/repos/builtin/packages/nlohmann-json/package.py
Add the latest bugfix release.
> NLohmann-JSON: v3.5.0

- var/spack/repos/builtin/packages/mvapich2/package.py
- Add support for nemesis:ofi netmod
- Add missing pkg-config and libxml2 dependencies
> mvapich2: Improve package

- var/spack/repos/builtin/packages/ior/package.py
- new GitHub home
- new 3.2 release
> update IOR package

- var/spack/repos/builtin/packages/quantum-espresso/package.py
Here are the updates in this PR:
- Change HDF5 variant to a multi-valued variant
- Fix HDF5 dependency to include high-level library
- Add support for serial HDF5 interface
> Quantum ESPRESSO HDF5 update

- var/spack/repos/builtin/packages/libyaml/package.py
As an avid user of the [asdf](https://github.com/asdf-vm/asdf) tool, this appears to be the only missing dependency. I had to write it for myself, but I figured it would be a good candidate to submit back here!
Let me know if there's anything I can change to better align with styles and whatnot. I've never really worked with Python before. What I have is a best guess based on documentation and looking at a couple of sample packages.
> Added libyaml package

- var/spack/repos/builtin/packages/cdo/package.py
new release of CDO is available
> update to cdo-1.9.6

- var/spack/repos/builtin/packages/dealii/package.py
follow up to https://github.com/spack/spack/pull/9481
> dealii: fix default of cuda_arch

- var/spack/repos/builtin/packages/mpifileutils/package.py
Version update: We switched from autotools to cmake. 
This will conflict with #10411, but that isn't getting merged any time soon.
> mpiFileUtils v0.9

- lib/spack/spack/cmd/help.py
Closes #10686 
Thoughts on the wording/placement/color?
> Add /hash to spack help --spec

- var/spack/repos/builtin/packages/r-vfs/package.py
depends on r-nleqslv in #10696
> r-vfs: new package at 1.0.2

- var/spack/repos/builtin/packages/quantum-espresso/package.py
This is a bug fix to my last QE PR. Unfortunately, I didn't not cover all the different cases that were conflicts. 
Also some clean up of variable names.
> Quantum ESPRESSO Serial HDF5 Bug Fix

- var/spack/repos/builtin/packages/routino/package.py
Add Routino : Route Planner for OpenStreetMap Data (https://www.routino.org/)
> Routino: add new package

- var/spack/repos/builtin/packages/libplist/package.py
This PR adds the `libplist` package. It's a dependency of Google's Flutter toolchain.
> libplist: new package

- var/spack/repos/builtin/packages/phred/package.py
part of the software collection introduced in #10529,
developers must be contacted via email to receive the source code.
> phred: new package

- var/spack/repos/builtin/packages/qmcpack/package.py
- Make compatible with new QE multi-value HDF5 variants
- Fixed some CUDA buglets
> QMCPACK Update Minor

- var/spack/repos/builtin/packages/libusb/package.py
This PR adds the `libusb` package!
> libusb: new package

- lib/spack/spack/cmd/bootstrap.py
- var/spack/repos/builtin/packages/environment-modules/package.py
> Update environment-modules package

- var/spack/repos/builtin/packages/otf2/package.py
Minor fix in url path for package `otf2`.
> Fix in download url for otf2 package

- var/spack/repos/builtin/packages/mpich/package.py
- Add missing pkg-config, libpciaccess and libxml2 dependencies
- Add missing slurm dependency for mpich@3.3:
- Add missing configure flag for libfabric
> mpich: Improve package

- lib/spack/spack/cmd/bootstrap.py
- share/spack/setup-env.sh
fixes #10708 
Exposed by #10717
> Fix shell integration with environment-modules@4

- var/spack/repos/builtin/packages/trilinos/package.py
- var/spack/repos/builtin/packages/xsdk/package.py
xsdk: switch from 12.14.0-rc1 to 12.14.1
> Trilinos: add release 12.14.1

- var/spack/repos/builtin/packages/petsc/package.py
As per https://lists.mcs.anl.gov/pipermail/petsc-users/2019-February/037816.html
CC :  @balay
> PETSc, build for KNL

- lib/spack/spack/binary_distribution.py
- lib/spack/spack/relocate.py
- lib/spack/spack/test/packaging.py
Resubmit of #10287 
pending merge of #9199 and rebasing
> Buildcache updates: Resubmit of #10287 

- var/spack/repos/builtin/packages/r-bfastspatial/package.py
depends on r-bfast in #10733 and r-gdalutils in #10731
> r-bfastspatial: new package at 0.6.2

- var/spack/repos/builtin/packages/eqr/package.py
- var/spack/repos/builtin/packages/py-mdanalysis/package.py
- var/spack/repos/builtin/packages/r-cli/package.py
- var/spack/repos/builtin/packages/r-dplyr/package.py
- var/spack/repos/builtin/packages/r-fansi/package.py
- var/spack/repos/builtin/packages/r-pillar/package.py
- var/spack/repos/builtin/packages/r-pkgconfig/package.py
- var/spack/repos/builtin/packages/r-rlang/package.py
- var/spack/repos/builtin/packages/r-tibble/package.py
- var/spack/repos/builtin/packages/r-utf8/package.py
- var/spack/repos/builtin/packages/stc/package.py
- var/spack/repos/builtin/packages/turbine/package.py
Added new R packages and updated versions.
> Package Updates for ECP CANDLE Supervisor

- var/spack/repos/builtin/packages/pal/package.py
This commit adds a new package: pal. It has been built sucessfully against gcc@5.4.0 on CentOS 7.
> pal: a new package.

- var/spack/repos/builtin/packages/libusbmuxd/package.py
This PR adds the `libusbmuxd` package!
> libusbmuxd: new package

- var/spack/repos/builtin/packages/rsem/package.py
Tested on CentOS 7 with gcc 8.2.0
> rsem: update to release 1.3.1

- var/spack/repos/builtin/packages/unifycr/package.py
UnifyCR has had a few dependency changes to make the backend more efficient and a new pre-release version has been released as well to mark these changes. Prior versions are no longer supported.
This adds those dependencies and the new version to _unifycr/package.py_ and removes anything dealing with now unsupported prior versions.
> unifycr: dependency changes and new version

- var/spack/repos/builtin/packages/bsseeker2/package.py
Fixed up download URLs too, not sure that's the best way to handle it.  Requesting review.
> bsseeker2: Add versions 2.1.8 and 2.1.5

- lib/spack/spack/compilers/clang.py
- lib/spack/spack/test/compilers.py
fixes #10191
As a bonus we test a single regex instead of multiple ones.
> Improved detection of Clang versions

- var/spack/repos/builtin/packages/py-crossmap/package.py
Was removed after license update, rewritten
> py-crossmap: new package at 0.3.3

- var/spack/repos/builtin/packages/mvapich2/package.py
Added psm2 fabric support. According to the documentation PSM2 fabric support was added with version 2.2, added conflict with versions below 2.2.
> added psm2 fabric support and conflict with versions below 2.2

- var/spack/repos/builtin/packages/draco/package.py
Added spackage for draco library
> Added Spackage for Draco Library

- lib/spack/spack/test/environment_modifications.py
- lib/spack/spack/util/environment.py
list.clear not present in python2
> Fix clearing EnvironmentModifications with python2

- var/spack/repos/builtin/packages/mysql/package.py
- var/spack/repos/builtin/packages/py-mysqldb1/package.py
This fixes the missing mysql package dependency on mysqldb1, and of course adds mysql
> Fix mysqldb1

- var/spack/repos/builtin/packages/py-biomine/package.py
Requires #10867 as a dependency.
> py-biomine: Create new package

- var/spack/repos/builtin/packages/libplist/package.py
- var/spack/repos/builtin/packages/libusbmuxd/package.py
pkgconfig is the correct virtual provider.
> libplist, libusbmuxd: Fix pkgconfig dependency

- var/spack/repos/builtin/packages/py-espressopp/package.py
> py-espressopp: add v2.0.2

- var/spack/repos/builtin/packages/cabana/package.py
/cc @sslattery @dalg24 @jgalarowicz
> cabana: cuda backend

- var/spack/repos/builtin/packages/branson/package.py
+ Also update dependencies (newer version have fewer dependencies).
> Branson: provide new versions.

- var/spack/repos/builtin/packages/yara/package.py
Built on Centos 7 with gcc 8.2
> Added Yara Package

- var/spack/repos/builtin/packages/gettext/package.py
fixes https://github.com/spack/spack/issues/10916
@erimar77 thanks, indeed solved the issue.
> gettext: fix dependency type of xz

- lib/spack/spack/modules/lmod.py
No big deal, but while I was reading through this bit....
> Minor commentary correction, TCL -> lmod

- var/spack/repos/builtin/packages/dealii/package.py
- var/spack/repos/builtin/packages/ginkgo/package.py
- var/spack/repos/builtin/packages/ginkgo/static.patch
@pratikvn @gflegar @tcojean  FYI.
~~blocked by~~ https://github.com/ginkgo-project/ginkgo/issues/270 EDIT: added some workarounds suggested upstream.
> add ginkgo package, use it in dealii along with symengine

- var/spack/repos/builtin/packages/acts-core/package.py
Prepare Spack for building today's ACTS release.
> Add ACTS version 0.8.2

- var/spack/repos/builtin/packages/bowtie/package.py
> bowtie: Add missing zlib dependency

- var/spack/repos/builtin/packages/netgen/package.py
> netgen: update broken URL

- var/spack/repos/builtin/packages/petsc/package.py
- var/spack/repos/builtin/packages/petsc/xcode_stub_out_of_sync.patch
fixes https://github.com/spack/spack/issues/10608
> petsc: workaround xcode stub-out-of-sync issue

- var/spack/repos/builtin/packages/environment-modules/package.py
New bugfix version in the v4.2 series.
Release notes: https://modules.readthedocs.io/en/latest/NEWS.html#modules-4-2-3-2019-03-23
> environment-modules: add version 4.2.3

- var/spack/repos/builtin/packages/chapel/package.py
Simple spack package for chapel, doesn't requires any configuration options.
> Added a package for chapel.

- var/spack/repos/builtin/packages/hypre/package.py
- var/spack/repos/builtin/packages/hypre/superlu-dist-link.patch
- add a patch to fix build error with superlu-dist
cc: @ulrikeyang
> hypre: add superlu-dist variant

- var/spack/repos/builtin/packages/xsdk/package.py
- disable sundials varaiant for dealii and mfem - as they are incomatible with sundials@4.1.0
cc: @balos1
> xsdk: enable sundials@4.1.0 for xsdk@develop

- var/spack/repos/builtin/packages/gl2ps/package.py
Don't attempt to build the PDF if we haven't said we want it (with +doc).
> gl2ps: add missing dependencies and doc variant.

- var/spack/repos/builtin/packages/mmg/package.py
This PR adds a package for the mmg tools.
> Add package MMG

- lib/spack/spack/build_systems/cuda.py
Fix CUDA-Intel compiler conflicts, especially with more recent version of the Intel compiler.
> Fixed some issues with CUDA-Intel compiler conflicts.

- lib/spack/spack/test/pytest.ini
See https://github.com/spack/spack/pull/8612#discussion_r268773666
> Added regression marker to pytest.ini

- var/spack/repos/builtin/packages/boost/package.py
Fix build of versions <1.62.0 by removing Fiber from list of libraries to build.
Also compactify C++ standard handling and additionally remove `default` option due to difficulty of detecting compiler version-related conflicts with Fiber choice.
Add known conflict with C++17 for boost <1.63.0.
Improve variant management for Fiber; add variants for Context and Coroutine libraries.
> boost: Fix build of versions <1.62.0 

- var/spack/repos/builtin/packages/kokkos/package.py
Some updates to the Kokkos package:
- Build with pthreads
- Two new versions of Kokkos
Cc @womeld @crtrott
> Kokkos: pthreads variant and new kokkos versions

- var/spack/repos/builtin/packages/r-rinside/package.py
0.2.14 seems to have disappeared.
> Update r-rinside to 0.2.15

- var/spack/repos/builtin/packages/py-ipykernel/package.py
- var/spack/repos/builtin/packages/py-ipython/package.py
- var/spack/repos/builtin/packages/py-jupyter-console/package.py
- var/spack/repos/builtin/packages/py-jupyter-notebook/package.py
- var/spack/repos/builtin/packages/py-prompt-toolkit/package.py
This is several package fixes to make jupyter build and work correctly.
> Py jupyter fixes

- lib/spack/spack/main.py
Add arch spec for envrionment-modules for #10883
> Add arch=spack.architecture.sys_type() to environment-modules spec

- lib/spack/spack/build_systems/intel.py
- var/spack/repos/builtin/packages/intel-mkl/package.py
- var/spack/repos/builtin/packages/intel-parallel-studio/package.py
part of https://github.com/spack/spack/pull/9032
> add libs property to IntelMkl and IntelParallelStudio

- lib/spack/llnl/util/lang.py
See https://github.com/spack/spack/pull/10931#discussion_r269732383 and following discussion
> Simplified llnl.util.lang.memoized so that Sphinx can extract signature

- var/spack/repos/builtin/packages/flux-core/package.py
- var/spack/repos/builtin/packages/flux-sched/package.py
> add pkg-config as dependence for flux packages

- var/spack/repos/builtin/packages/macsio/package.py
Not sure how this spackage ever worked.
> macsio: fix install

- var/spack/repos/builtin/packages/r-roxygen2/package.py
depends on `r-commonmark` in #11049, `r-desc` in #11048, `r-pkgload` in #11047, `r-pkgbuild` in #11046
> r-roxygen2: added 6.1.1, more dependencies

- var/spack/repos/builtin/packages/kim-api/package.py
- var/spack/repos/builtin/packages/openkim-models/package.py
Updates for most recent release of kim-api
> Updates/rename of kim-api and openkim-models packages

- var/spack/repos/builtin/packages/ross/package.py
- added sha256 for various versions.
- v7.0.1 fixes some environment hacking to properly find MPI and system architecture
> ross version 7.0.1

- var/spack/repos/builtin/packages/hypre/package.py
ref: https://github.com/spack/spack/pull/10985
cc:  @v-dobrev @ulrikeyang
> hypre: disable variant superlu-dist default

- var/spack/repos/builtin/packages/kokkos/package.py
see https://github.com/spack/spack/pull/10943#issuecomment-475303870
> kokkos: update cuda conflict

- var/spack/repos/builtin/packages/cdhit/package.py
Tested on CentOS 7 w/ gcc 8.2.0
> cdhit: add new release 4.8.1

- var/spack/repos/builtin/packages/fzf/github_mirrors.patch
- var/spack/repos/builtin/packages/fzf/package.py
Also add installation of vim plugin support provided with package via
'+vim' variant.
> fzf package use install instead of edit

- var/spack/repos/builtin/packages/amrex/package.py
amrex@develop now supports enabling SUNDIALS 4 in CMake
cc: @balay
> amrex: add sundials variant

- var/spack/repos/builtin/packages/xsdk/package.py
This uses https://github.com/spack/spack/pull/11147
cc: @balos1 @mic84
> xsdk@develop: enable amrex@develop+sundials

- lib/spack/spack/build_systems/intel.py
fixes https://github.com/spack/spack/issues/11135
> intel: optionally take gcc executable from cflags

- var/spack/repos/builtin/packages/petsc/package.py
> petsc: add fftw variant

- var/spack/repos/builtin/packages/fastmath/package.py
> Limit to FASTMath-only packages

- var/spack/repos/builtin/packages/py-petsc4py/package.py
> petsc4py: add verson 3.11.0

- var/spack/repos/builtin/packages/superlu-dist/package.py
Ref: https://github.com/xiaoyeli/superlu_dist/issues/36
Ref: https://github.com/xiaoyeli/superlu_dist/pull/42
cc:@s-sajid-ali @xiaoyeli @BarrySmith
> superlu-dist: fix issue with adding system blas/lapack - when MKL is explicitly specified

- var/spack/repos/builtin/packages/precice/package.py
This PR:
* adds releases with checksums
* updates dependencies
> precice: add releases

- var/spack/repos/builtin/packages/rust/package.py
> Added rust 1.34.0

- var/spack/repos/builtin/packages/llvm/package.py
> Add llvm 8.0.0

- var/spack/repos/builtin/packages/strumpack/intel-19-compile.patch
- var/spack/repos/builtin/packages/strumpack/package.py
Ref: https://github.com/spack/spack/issues/11202
cc: @TiffanyAnn @pghysels
> strumpack@3.1.1: add patch for Intel-19 build failure on cori

- var/spack/repos/builtin/packages/sublime-text/package.py
- Add 3.2.1
- Reformat versions to include proper upstream version tags
- Add gtk dependency
- Add prefix to PATH so sublime_text can be found
@JSquar
> sublime-text: Miscellaneous improvements

- var/spack/repos/builtin/packages/alquimia/package.py
- var/spack/repos/builtin/packages/amrex/package.py
- var/spack/repos/builtin/packages/hypre/package.py
- var/spack/repos/builtin/packages/magma/package.py
- var/spack/repos/builtin/packages/omega-h/package.py
- var/spack/repos/builtin/packages/pflotran/package.py
- var/spack/repos/builtin/packages/plasma/package.py
- var/spack/repos/builtin/packages/pumi/package.py
- var/spack/repos/builtin/packages/slepc/package.py
- var/spack/repos/builtin/packages/strumpack/package.py
- var/spack/repos/builtin/packages/superlu-dist/package.py
- var/spack/repos/builtin/packages/tasmanian/package.py
- var/spack/repos/builtin/packages/trilinos/package.py
- var/spack/repos/builtin/packages/xsdk/package.py
> xsdk: add maintainers

- var/spack/repos/builtin/packages/libsodium/package.py
Adding version 16 and 17 for libsodium
> libsodium: new version

- var/spack/repos/builtin/packages/hypre/package.py
> hypre: add @osborn9 to maintainers

- var/spack/repos/builtin/packages/miniconda2/package.py
- var/spack/repos/builtin/packages/miniconda3/package.py
> Bump miniconda 2 and 3

- var/spack/repos/builtin/packages/dealii/package.py
Ref: https://github.com/dealii/dealii/issues/7934
> dealii: add patch for build with boost@1.70.0

- lib/spack/spack/build_environment.py
- lib/spack/spack/error.py
- lib/spack/spack/spec.py
part of https://github.com/spack/spack/pull/9032
> move NoLibrariesError and NoHeadersError into spack/error.py

- var/spack/repos/builtin/packages/fabtests/package.py
- var/spack/repos/builtin/packages/libfabric/package.py
- var/spack/repos/builtin/packages/mercury/package.py
> Add latest version of mercury

- lib/spack/docs/tutorial_advanced_packaging.rst
- lib/spack/docs/tutorial_configuration.rst
- lib/spack/docs/tutorial_packaging.rst
Updated to prevent sections stomping on each other's toes.
Does not update environments section as @tgamblin is currently re-writing segments of it.
> Fix transitions between tutorial sections

- var/spack/repos/builtin/packages/cp2k/package.py
@alalazo ok for you?
@ltalirz FYI
> Misc CP2K package improvements
