var/spack/repos/builtin/packages/py-numpy/package.py, var/spack/repos/builtin/packages/py-scipy/package.py
Disable parallel build, which can cause problems.
Numpy does not take particularly long even with serial build.
=> py-numpy: update

var/spack/repos/builtin/packages/r-rcpp/package.py
Bump r-rcpp versions to 0.12.15 and 0.12.16 in which 0.12.16 has been built sucessfully on CentOS 7.3 against GCC 5.4.0.
=> Bump r-rcpp versions.

var/spack/repos/builtin/packages/openmpi/package.py
According to this comment:
https://github.com/open-mpi/ompi/issues/4338#issuecomment-383982008
on an OpenMPI issue, using `--enable-static` silently disables slurm support.
=> openmpi: don't build static libraries if slurm is activated

etc/spack/defaults/packages.yaml, lib/spack/spack/test/package_sanity.py
Every virtual package in Spack should have a default provider explicitly set in `etc/spack/defaults/packages.yaml`. This prevents changes in the concretizer from determining which virtual dependency is chosen by default. Of course, it doesn't prevent changes in the explicitly set defaults, but it should at least prevent unwanted surprises.
=> Set default provider for every virtual package

etc/spack/defaults/darwin/packages.yaml
The default compiler on macOS is Clang. Unfortunately, `elfutils` conflicts with Clang. This PR changes the default `elf` provider on macOS to `libelf` to prevent the default compiler and provider from causing problems.
This conflict was introduced in #7096. Related to #7593 and #7635.
=> Change default elf provider on macOS

lib/spack/spack/cmd/info.py
Fixes #7797.
Some URLs contain the @ symbol. Unfortunately, the @ symbol is also used by Spack for colored output. This PR escapes all @ symbols in URLs when running `spack info`.
P.S. Are there any other places in Spack that may be affected by this?
=> Fix coloring of URLs containing @ symbol

var/spack/repos/builtin/packages/gcc/package.py
Reported by @MarquitoForrest [here](https://github.com/spack/spack/commit/4fe6d9aceea5fefd8cc9779228c3a0671fed79d5#commitcomment-28867410).
=> macOS-specific patch no longer applies to GCC 8

lib/spack/spack/util/compression.py
Add support *.TAR.gz extension. For example, `http://www2.mmm.ucar.edu/wrf/src/WRFV3.9.1.1.TAR.gz`.
=> Support *.TAR.gz extension.

lib/spack/spack/spec.py, lib/spack/spack/test/concretize.py, lib/spack/spack/test/spec_syntax.py
Modified string representation of Specs to add a space before deps
fixes #7941
=> Specs add a space before dependencies

var/spack/repos/builtin/packages/pkgconf/package.py
=> pkgconf: use alpine linux mirror to avoid ssl error

var/spack/repos/builtin/packages/openmpi/package.py
Adding new version
Includes: https://github.com/open-mpi/ompi/pull/5010 which fixes https://github.com/open-mpi/ompi/issues/5008
=> openmpi: new version

var/spack/repos/builtin/packages/googletest/package.py
Add Google Test variant to enable/disable building with threads.
=> googletest: add variant to enable/disable threads

var/spack/repos/builtin/packages/py-pybind11/package.py
new release for pybind11, v2.2.3:
https://github.com/pybind/pybind11/blob/v2.2.3/docs/changelog.rst#v223-april-29-2018
Also mark unsupported compiler versions as conflicts.
=> pybind11: v2.2.3

lib/spack/spack/build_systems/autotools.py, lib/spack/spack/build_systems/cmake.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/install.py, var/spack/repos/builtin.mock/packages/a/package.py, var/spack/repos/builtin.mock/packages/archive-files/package.py
fixes #2781
This PR introduces a new attribute for packages that contains a list of glob expressions. Any file that matches will be archived in the `<prefix>/.spack/archived-files` directory.
`AutotoolsPackage` and `CMakePackage` provide a sensible default override for this attribute.
=> Packages can tune the list of files to be archived at the end of install

var/spack/repos/builtin/packages/gdb/package.py
Also add optional lzma dependency for debug information support. I'm not sure if a specific version of xz is required. (https://stackoverflow.com/questions/43482837/warning-cannot-parse-gnu-debugdata-section-lzma-support-was-disabled-at-compi)
=> Add gdb@8.1

var/spack/repos/builtin/packages/llvm/package.py
Building LLVM with LLDB requires that the "lldb_codesign" code
certificate be created (see
https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt for
details). This commit checks for this certificate on Darwin if LLDB is
to be built, and returns an informative error message if this
certificate is unavailable.
Should address #4985.
=> llvm+lldb plaform=darwin: check for lldb_codesign certificate

var/spack/repos/builtin/packages/perl-extutils-pkgconfig/package.py
Fixes error build error
```     
4     *** ExtUtils::PkgConfig requires the pkg-config utility, but it doesn't
5     *** seem to be in your PATH.  Is it correctly installed?
```
=> perl-extutils-pkgconfig: Add pkg-config dependency

var/spack/repos/builtin/packages/protobuf/package.py, var/spack/repos/builtin/packages/py-protobuf/package.py
Work in progress: see below
~To actually enable the c++ implementation, these flags need to be set:
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
[Reason, I think](https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/python/google/protobuf/internal/api_implementation.py#L69)~
EDIT: nope. The c++ stuff gets picked up or not [here](https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/python/google/protobuf/internal/api_implementation.py#L40)
~However, I can't figure out how to do that. I'm not seeing any way to set additional runtime environment variables in the docs (I might have missed them). Even if I found those, if I `spack activate py-protobuf` and then `module load python-[...]` but …
=> Add 3.5.2; Add optional cpp implementation enable for py-protobuf

var/spack/repos/builtin/packages/wireshark/package.py
Trying to build `wireshark` on a system w/o `bison` led to the error
```
...
346     Could NOT find YACC (missing: YACC_EXECUTABLE)
...
```
This PR fixes YACC pick up and removes fallback to system `libpcap`, `pkgconfig` and `git` installations (from the cmake log). Remaining `/usr` things is `libm`
@adamjstewart is there a way to get at the library file of `libpcap` directly?
=> wireshark: stop cmake from picking up /usr paths

var/spack/repos/builtin/packages/llvm/package.py
Fixes https://github.com/spack/spack/issues/8088
https://github.com/spack/spack/pull/7012 added a `@when` condition for a `@run_before` check to constrain that check to only run on Darwin. Spack doesn't appear to support the combination of `@when` and `@run_before` (or `@run_after`). This replaces the external decorator with a check that executes at the beginning of the function.
=> llvm: replace @when with internal check in @run_before

var/spack/repos/builtin/packages/bumpversion/package.py, var/spack/repos/builtin/packages/py-bumpversion/package.py
`bumpversion` is a tool that automagically increments version numbers for projects.  It can update files and do other magic along the way.
I was uncertain whether the package should be called `bumpversion` or `py-bumpversion`.  Is being written in python and/or using the python build system really all it takes to earn a `py-` prefix?
Thoughts?
=> Add package for "bumpversion"

var/spack/repos/builtin/packages/texlive/package.py
Addresses #4811. Note the actual PATH on linux should be `bin/x86_64-linux`. It appears to be in reversed in that issue.
To be honest I haven't had a chance to test this because it seems like something is out of sync with the texlive CTAN servers or whatever. I did test it on another package though and it does what I want. I get this error on all systems I've tried when installing texlive today:
```
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
local: 2017
repository: 2018
Perhaps you need to use a different CTAN mirror?
```
=> Create custom PATH that texlive requires in its module.

var/spack/repos/builtin/packages/boost/package.py
This PR adds the +numpy variant in the boost package.
The Boost.NumPy library is particular: it is not enabled by a build flag when building boost; it is instead enabled automatically when Boost.Python is built and boost detects that Numpy is present on the targeted Python installation. Hence the `+numpy` variant needs the `+python` variant to be active, and it depends on the `py-numpy` package.
=> boost: added the +numpy variant which enables building libboost_numpy

var/spack/repos/builtin/packages/libjpeg-turbo/package.py
Newer version uses of libjpeg-turbo uses cmake.
=> Add cmake for newer version of libjpeg-turbo

var/spack/repos/builtin/packages/yaml-cpp/package.py
`0.5.3` doesn't build with `boost@1.67.0`
=> add version 0.6.2 to yaml-cpp

var/spack/repos/builtin/packages/dealii/package.py
in reference to https://github.com/dealii/dealii/issues/6586 : in the release process one file got lost which only affects quick tests (and not the library itself) :-(  The tarbal was updated to fix this.
=> dealii: update hash due to upstream changes

var/spack/repos/builtin/packages/kaiju/package.py
Kaiju has been built succesfully against GCC 5.4.0 on CentOS 7.4. A test run of `makeDB.sh -m` finishes succesfully after installation.
=> A new pacakge: Kaiju.

var/spack/repos/builtin/packages/salmon/package.py
1.67 results in compile errors:
``error: ‘next’ is not a member of ‘boost’``
=> salmon: adding in version restriction for boost

var/spack/repos/builtin/packages/silo/package.py
Added compatibility for hdf5+mpi to silo spackage to support spackages
with dependency chains that include silo and hf5+mpi
Fix proxyapps/proxy-ci#16
=> Added Shim to Support hdf5+mpi in Spack Silo

var/spack/repos/builtin/packages/petsc/package.py, var/spack/repos/builtin/packages/petsc/xlc-test-3.9.0.diff
Patch petsc test cases so they can be built with the IBM XL compiler after spack install.  These test cases are built in a seperate step, outside of spack, but they need to patched after staging so users don't have to do it in a seperate step.
The test cases are installed under <petsc install directory>/share/petsc/examples and can be built and executed by invoking gmake -f gmakefile.test in that directory.
=> Patch PETSc test cases for IBM XL compiler

var/spack/repos/builtin/packages/py-cloudpickle/package.py, var/spack/repos/builtin/packages/py-dask/package.py, var/spack/repos/builtin/packages/py-locket/package.py, var/spack/repos/builtin/packages/py-partd/package.py, var/spack/repos/builtin/packages/py-pluggy/package.py, var/spack/repos/builtin/packages/py-py/package.py, var/spack/repos/builtin/packages/py-pytest/package.py, var/spack/repos/builtin/packages/py-toolz/package.py, var/spack/repos/builtin/packages/py-zope-event/package.py, var/spack/repos/builtin/packages/py-zope-interface/package.py
Fixes #8108. Closes #8110.
This PR adds missing dependencies to `py-dask`. Although these dependencies aren't required for the core library, they are used by most of the `dask` modules.
Successfully installed everything on macOS 10.13.4 with Clang 9.0.0. Most of the unit tests passed, although the unit tests for `dask` hung for some reason.
@s-sajid-ali @healther
=> Add dependencies for py-dask

var/spack/repos/builtin/packages/flex/package.py
in reference to https://github.com/spack/spack/issues/8152
`2.6.5` is supposed to fix this issue, until then, let's use `2.6.3` by default.
=> flex: use 2.6.3. by default

var/spack/repos/builtin/packages/silo/package.py
This pull request adds support for the version of Silo that our code team uses.  Since Spack sorts this version to become the new preferred default, I list "preferred=True" on version 4.10.2 so that the original default is kept.  Note that the URL specification is necessary because this version of Silo is not kept in a standard location that the others are :(
=> Support version 4.10.2-bsd

var/spack/repos/builtin/packages/trinity/package.py
due to jdk's goofy version numbers, the minor version parsing seems to break without trailing colon
Also changing to java virtual dependency instead of jdk explicitly
=> trinity: fixing jdk dependency

var/spack/repos/builtin/packages/expat/package.py
On SuSE (SLES) 11, I got the following error, in spite of using `--with-libbsd` as added in #4945:
```
lib/xmlparse.c:56:3: error: #error You do not have support for any sources of high quality entropy enabled...
```
[spack-build.out.txt](https://github.com/spack/spack/files/2003247/spack-build.out.txt)
An update to the latest version of `libexpat` solved the problem.  In the meantime, I'm moving this package to GitHub, as per instructions on the upstream website https://sourceforge.net/projects/expat/
> PLEASE NOTE that we are in the process of moving to GitHub: https://github.com/libexpat/libexpat
=> libexpat: Fix for older systems, move to GitHub

var/spack/repos/builtin/packages/nco/package.py
Previously, `nco` was not able to find Spack-installed NetCDF; presumably relying on system-installed NetCDF instead.  If no system-installed NetCDF, this resulted in the error below.  This PR fixes the problem.
```
==> Installing nco
==> Using cached archive: /gpfsm/dnb53/rpfische/spack6/var/spack/cache/nco/nco-4.6.7.tar.gz
==> Staging archive: /gpfsm/dnb53/rpfische/spack6/var/spack/stage/nco-4.6.7-cmbb6euq3cyv25t6t47cu6snbfbrthqz/4.6.7.tar.gz
==> Created stage in /gpfsm/dnb53/rpfische/spack6/var/spack/stage/nco-4.6.7-cmbb6euq3cyv25t6t47cu6snbfbrthqz
==> Applied patch NUL-0-NULL.patch
==> Building nco [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1: …
```
=> nco: Find NetCDF

var/spack/repos/builtin/packages/vim/package.py
Built on ubuntu 18.04 with gcc 7.3
https://www.vim.org/vim-8.1-released.php
They finally added terminal split screen support.
=> Added vim 8.1

var/spack/repos/builtin/packages/antlr/package.py
On my SUSE11 system, ANLTR build of the CSharp bindings was failing due to a lack of system-installed CSharp on the system.  Unless we add csharp support to Spack, we should disable the ANTLR CSharp bindings.
Note the available options for ANTLR's `./configure` script.  This stuff isn't really documented anywhere else:
```
Optional Features:
--disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
--enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
--enable-java           enable or disable ANTLR for Java (enabled)
--enable-cxx            enable or disable ANTLR for C++ (enabled)
--enable-python         enable or disable ANTLR for Python (enabled).
--enable-csharp         enable or disable ANTLR for C# (enabled)
--enable-verbose        turn on verbosity when building …
```
=> antlr: Turn off CSharp

var/spack/repos/builtin/packages/libjpeg-turbo/package.py, var/spack/repos/builtin/packages/opencv/package.py
I'm a little concerned about the `format(dso_suffix)` removal as I have no way to test on osx.
Tested with +zlib+png+jpeg+tiff+jasper.
=> Fix libjpeg library finding and opencv build with nonstandard library directories (#8160)

lib/spack/spack/build_environment.py, lib/spack/spack/cmd/bootstrap.py, lib/spack/spack/cmd/config.py, lib/spack/spack/cmd/create.py, lib/spack/spack/cmd/uninstall.py, lib/spack/spack/operating_systems/cray_frontend.py, lib/spack/spack/package.py, lib/spack/spack/spec.py, lib/spack/spack/stage.py, lib/spack/spack/util/spack_json.py
Fixes #8196.
Fixes issue mentioned by @adamjstewart at [#8090 (comment)](https://github.com/spack/spack/pull/8090#issuecomment-390375659), along with some other lingering undefined names and flake8 errors.
- there were some leftover spack.* names being used after we removed globals and moved everything in the top-level namespace to spack.pkgkit
- point those references to their new homes
=> fix leftover references to spack.<symbol>

var/spack/repos/builtin/packages/libgeotiff/package.py
Successfully installed with and without all variants on macOS 10.13.4 with Clang 9.0.0.
I couldn't find a way to disable the `libtiff` dependency, at least with the Autotools build. They also have a CMake build but I didn't mess with it. The `README` instructions use Autotools, so I assume it is the recommended installation technique.
=> Add libgeotiff package

var/spack/repos/builtin/packages/fyba/package.py, var/spack/repos/builtin/packages/fyba/vfs-mount-darwin.patch
After patching and rebuilding `configure`, I was able to install this successfully on macOS 10.13.4 with Clang 9.0.0.
=> Add FYBA package

var/spack/repos/builtin/packages/xerces-c/package.py
Successfully installed and passed all unit tests on macOS 10.13.4 with Clang 9.0.0.
=> Add Xerces-C++ 3.2.1

var/spack/repos/builtin/packages/curl/package.py
Successfully installed on macOS 10.13.4 with Clang 9.0.0. Passed 924 out of 925 unit tests, not sure why 1 failed. But Homebrew is also using 7.60.0, so I'm not too worried.
=> Add cURL 7.60.0

var/spack/repos/builtin/packages/libxml2/package.py
Successfully installed and passed all unit tests on macOS 10.13.4 with Clang 9.0.0.
=> Add libxml2 2.9.8

var/spack/repos/builtin/packages/sqlite/package.py
Successfully installed on macOS 10.13.4 with Clang 9.0.0.
=> Add sqlite 3.23.1

var/spack/repos/builtin/packages/pcre/package.py
Successfully installed and all unit tests passed on macOS 10.13.4 with Clang 9.0.0.
=> Add PCRE 8.42

var/spack/repos/builtin/packages/pcre2/package.py
Successfully built and passed all unit tests on macOS 10.13.4 with Clang 9.0.0.
=> Add PCRE2 10.31

var/spack/repos/builtin/packages/sbt/package.py
I can restore version `0.13.2` if anybody knows how to have a second `url` that doesn't compromise `spack checksum`.
=> Updated sbt to point to github. Added versions 1.1.4, 0.13.17.

var/spack/repos/builtin/packages/cryptopp/package.py
Successfully installs and passes all tests on macOS 10.13.4 with Clang 9.0.0.
=> Add cryptopp 7.0.0

var/spack/repos/builtin/packages/libjpeg/package.py
The maintainer redid the archive in March, removing a .directory file.
Resolves #8180
@adamjstewart
=> Update the hash of libjpeg v9c.

var/spack/repos/builtin/packages/bmake/package.py
Needed this to test another PR.
Adds the latest version of bmake. Also separates the installation out into multiple phases.
Successfully installs and passes all tests on macOS 10.13.4 with Clang 9.0.0.
=> Add bmake 20180512

var/spack/repos/builtin/packages/poppler-data/package.py, var/spack/repos/builtin/packages/poppler/package.py
Also added the latest version.
Previously, this package would pick up whatever it found on the OS, leading to a non-deterministic build. This PR explicitly enables/disables support for optional components based on what is requested via variants.
Successfully installed on macOS 10.13.4 with Clang 9.0.0.
=> Add missing dependencies to poppler package

var/spack/repos/builtin/packages/lcms/package.py
Successfully installed on macOS 10.13.4 with Clang 9.0.0. Didn't pass its unit tests though...
=> Add lcms 2.9

var/spack/repos/builtin/packages/geos/package.py
I added variants to enable/disable the Python/Ruby bindings for the GEOS package. I also converted the package to `AutotoolsPackage`.
Unfortunately, I couldn't get the Ruby bindings working. I kept getting:
```
Undefined symbols for architecture x86_64:
"_rb_ary_entry", referenced from:
_wrap_create_polygon(int, unsigned long*, unsigned long) in geos_la-geos_wrap.o
"_rb_big2long", referenced from:
SWIG_AUX_NUM2LONG(unsigned long*) in geos_la-geos_wrap.o
"_rb_big2ulong", referenced from:
SWIG_AUX_NUM2ULONG(unsigned long*) in geos_la-geos_wrap.o
"_rb_block_given_p", referenced from:
GeosSTRtree_query_callback(void*, void*) in geos_la-geos_wrap.o
"_rb_cFalseClass", referenced from:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use …
```
=> Add Python/Ruby bindings to GEOS package

var/spack/repos/builtin/packages/py-docopt/package.py
Successfully installs and passes import tests on CentOS 6 with GCC 6.1.0.
=> Add py-docopt package

var/spack/repos/builtin/packages/memkind/package.py
The memkind library is a user extensible heap manager built on top of jemalloc which enables control of memory characteristics and a partitioning of the heap between kinds of memory.
=> Create new package: memkind

var/spack/repos/builtin/packages/charm/package.py
Updating install script for charm.
Changes:
- Updated latest version
- mpi.patch is not needed in versions 6.8.0+
- Added build targets: AMPI, LIBS
- Added backend variants: gni, ofi, pami, pamilrts
- Removed deprecated net backend
- Added compiler and fortran compiler variants
- Added compile time options
- Added more version combinations
- Added check for tracing when papi is enabled
=> charm: Update install script

var/spack/repos/builtin/packages/ncurses/package.py
Successfully installed on SLES 11 (Cray) with CCE 8.5.8. `ncurses` doesn't have any unit tests, but I was able to install vim with it, so I think it's fine.
=> Add ncurses 6.1

var/spack/repos/builtin/packages/pkgconf/package.py
Successfully installed on SLES 11 (Cray) with CCE 8.5.8.
Unfortunately, I couldn't run the unit tests because of a missing dependency on the kyua testing framework. I started working on a package for kyua but it depends on lutok which depends on lua which depends on ncurses which depends on pkgconf, thereby creating a circular dependency. So I added a note about the missing dependency. I'll "leave this as an exercise for the reader" if you really want to properly test pkgconf.
I did install another package using this pkgconf installation, so I'm confident that it's not too broken.
=> Add pkgconf 1.4.2

var/spack/repos/builtin/packages/proj/package.py
Adds the latest versions of PROJ.4. Successfully installs on macOS 10.13.4 with Clang 9.0.0. Unfortunately, I couldn't get the unit tests to pass. Opened an issue: https://github.com/OSGeo/proj.4/issues/1003
=> Add PROJ 5.0.1

var/spack/repos/builtin/packages/kealib/cmake.patch, var/spack/repos/builtin/packages/kealib/package.py
Successfully installs and passes all tests on macOS 10.13.4 with Clang 9.0.0.
Took me forever to figure out how to install this package. No matter what I tried, I kept getting the following error:
```
/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-55/test_keep_exceptions0/tmp/spack-stage/spack-stage-pbhblev6/chchrsc-kealib-c8646188a638/trunk/src/libkea/KEAImageIO.cpp:3607:10: fatal error: 'libkea/kea-config.h' file not found
#include "libkea/kea-config.h"
^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/kea.dir/libkea/KEAImageIO.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/kea.dir/all] Error 2
make: *** [all] Error 2
```
I eventually discovered that this package doesn't support out-of-source builds. I've never seen a CMake package like …
=> Add kealib 1.4.7

var/spack/repos/builtin/packages/openfoam-org/240-etc.patch, var/spack/repos/builtin/packages/openfoam-org/package.py
@olesenm 
Following suggestions/feedback from #7706 for v2.3.1 I switched to 2.4 which is much simpler to add and should be backwards compatible to 2.3.1.
#7706 was closed unintentionally when creating a new branch and better organising my fork.
=> openfoam-org: add v2.4.0

var/spack/repos/builtin/packages/kokkos/package.py
Supersedes #8169 . Adds multi-valued variants for current host and gpu architectures. Includes logic that allows for only one host and one gpu architecture, and populates build arguments appropriately.
=> kokkos: update kokkos spackage to add current host/gpu architectures.

lib/spack/spack/spec.py
Otherwise, specifying compiler flags on the command line fails with:
`Error: 'module' object has no attribute 'compiler'`
Seems to be related to c615d2be06eeaf10058ddece27f69d6e148f44af.
=> Fix missing spack.compiler import

var/spack/repos/builtin/packages/tophat/package.py
The Tophat team merged the patch from
https://github.com/spack/spack/pull/8244 and release v2.1.2
This change requires the old automake if you're building the older
release and is relaxed about the automake it requires if you're
building the v2.1.2 release.
Building v2.1.1 and v2.1.2 works on a CentOS 7 system, I don't have
the necessary bit to actually test the resulting binaries.
Here's the commit note from the change that was ultimately merged
upstream.
Fixes #8025
> Tophat was failing to build with automake@1.16.1, it worked with the
> older automake@1.15.1. This commit adds a patch to Tophat's
> src/Makefile.am which cleans up a few things. The result builds
> successfully with both automake@1.15.1 and automake@1.16.1. I have no
> way to check that the resulting builds Do The Right …
=> Add Tophat v2.1.2, fixes automake issues

var/spack/repos/builtin/packages/opencv/package.py
The recipe previously did not include -DWITH_JASPER as something that could be specified one way or the other.
Other edits:
* BUILD_IPP_IW is BUILD instead of WITH; it was in a different section of the CMakeLists.txt. Move it to the top, as that section is before the one with the WITHs
* Several options were missing :BOOL
* -DWITH_ZLIB doesn't actually exist as an option
(I'm just going to hope that the options in the opencv recipe previously are the only ones people want, there is a _lot_ of potential busywork there)
=> Fix OpenCV JasPer disable

var/spack/repos/builtin/packages/gettext/package.py
Verified that this fixes #2882 without the `~libxml2` workaround.  Thank you @dlukes
=> Fix gettext: Problem with libxml2

var/spack/repos/builtin/packages/fyba/gcc-6.patch, var/spack/repos/builtin/packages/fyba/package.py
To be honest, I don't know the first thing about C. I could lock it down to only patch when using GCC 6, but I don't know what other versions of GCC or what other compilers might be affected. The change seems pretty innocent, so I'm going to err on the side of "always patch" unless someone else knows better. 
Successfully installed with GCC 6.1.0 on CentOS 6.9.
=> Fix compilation of FYBA with GCC 6

var/spack/repos/builtin/packages/nwchem/package.py
It seems that the new versions on github don't require the patching that was needed in previous versions.
=> nwchem: added version 6.8

var/spack/repos/builtin/packages/py-pillow/package.py
Closes #8290.
The newer version of libjpeg-turbo installs the relevant libraries in lib64 and not lib. Since the newer version of libjpeg-turbo is now the preferred version, this will work. If someone wants to install an older libjpeg-turbo and install py-pillow, this won't work. 
While one can set up an if statement for dependencies in spack, I'm unsure about how one would check where jpeg is getting picked up from and if it is coming from libjpeg-turbo<1.5.90, then change the lib64 to lib.
=> py-pillow : update version and fix jpeg dependency

var/spack/repos/builtin/packages/perl/package.py
perl currently fails to build on Fedora 28 due to its glibc version (see https://bugzilla.redhat.com/show_bug.cgi?id=1536752).
=> perl: Fix build on Fedora 28

var/spack/repos/builtin/packages/bedops/package.py
Builds on CentOS 7, executables work.
(this is not a change, but...) It statically links it's executables, so you need the libstdc++-static and glibc-static packages in place.  Simple on CentOS, [trickier](https://stackoverflow.com/questions/44275897/no-package-glibc-static-available) on RHEL.
=> Add info for bedops@v2.4.35

var/spack/repos/builtin/packages/paraview/package.py
This pull request adds a spack_ and run_ environment setting that our code team needs a handle to as it builds out other packages which have a Paraview dependency.  I checked through all of the other sources to see this is a unique name.
=> paraview: set PARAVIEW_VTK_DIR in spack_env and run_env

var/spack/repos/builtin/packages/latte/package.py
Didn't work with MKL for me before this addition.
=> latte: specify blas and lapack explicitly

lib/spack/spack/binary_distribution.py, lib/spack/spack/relocate.py
Trying to relocate a distribution when the new and old paths are equal
leads to failure, because the test that ensures that no unrelocated
bits are left over always fails.
This simply checks if new and old are identical and returns if so.
Tested that it can/will install from a tarball into the same location
from whence the tarball came and into a different location.
Fixes #8217
=> Installing from mirror: don't relocate if old and new paths are identical

var/spack/repos/builtin/packages/pigz/package.py
The URL that we were using for pigz only provides the current
version.  When the author released v2.4 the package became
uninstallable (unless you have the tarball cached).
It turns out that their are tarballs of the tagged source tree
available on GitHub and they're sufficient to build things (no
additional bits needed).
This commit switches the URL to the GitHub archive URL.
Sadly, this changes the v2.3.4 digest, but that version was no longer
available/install-able anyway, so "net-net we're still in positive
territory".
=> Use GitHub URL for pigz, supports > 1 release

var/spack/repos/builtin/packages/camellia/package.py
HDF5 1.10.x is incompatible with Camellia, at least right now, so adding dependency to versions up to 1.8.x.
=> Camellia: add version restriction for HDF5.

var/spack/repos/builtin/packages/subread/package.py
`gcc` was hard-coded in the Makefile, which prevented compiling the packages with Intel
=> subread: use compiler wrappers when compiling

lib/spack/docs/packaging_guide.rst, lib/spack/spack/test/util/prefix.py, lib/spack/spack/util/prefix.py
minor follow up to https://github.com/spack/spack/pull/4591
The idea is to support the following syntax:
```
self.prefix.join('compilers_and_libraries_{0}'.format(self.version)).linux.mkl
```
=> extend Prefix class with join() member to support dynamic directories

lib/spack/spack/cmd/mirror.py, lib/spack/spack/test/cmd/mirror.py
fixes #8083
External specs are supposed to be already installed somewhere, so there's no need to try to download a tarball for them.
=> Skip external specs when creating mirrors

var/spack/repos/builtin/packages/abyss/package.py
The digest value for v1.5.2 appears to have changed.  This value works
for me, today.
The existing value v2.0.2 works as is.
=> Fix digest for abyss@1.5.2

var/spack/repos/builtin/packages/git/package.py
https://www.phoronix.com/scan.php?page=news_item&px=Git-2018-Security-CVE-2018
we should probably add the other updates too, but I had a hard time getting the correct checksums. `git` itself advises `sha256` sums, but these are not consistent with what I'm getting when I manually checksum `2.17.1` https://mirrors.edge.kernel.org/pub/software/scm/git/sha256sums.asc
I'll probably get back to this at the end of the week
=> add 2.17.1 for git

lib/spack/spack/build_environment.py
I would love to slap the first person who thought 0-based indexing was a good idea...
Fixes the following bugs:
```
==> Error: KeyError: 'No spec with name geos in gdal...'
/Users/Adam/spack/var/spack/repos/builtin/packages/gdal/package.py:269, in configure_args:
126   
127           if '+geos' in spec:
128               args.append('--with-geos={0}'.format(spec['geos'].prefix))
>> 129           else:
130               args.append('--with-geos=no')
131   
132           if '+qhull' in spec:
See build log for details:
/Users/Adam/spack/var/spack/stage/gdal-2.3.0-2twd2kcvmb6cnvb3ku4y3h5lh7i6vi4j/gdal-2.3.0/spack-build.out
```
For reference, the bug actually occurs on line 268 of the file, not 269 or 129.
```
==> Error: KeyError: 'No spec with name geos in gdal...' …
```
=> Fix package error message line numbers

lib/spack/llnl/util/tty/color.py, lib/spack/spack/build_environment.py, lib/spack/spack/util/log_parse.py
Okay, I swear this is the last bug I've noticed in our build error messages (so far).
Spack uses its own special color code syntax of the form `@color{text}`. The problem is that if `text` contains the `}` character, Spack prematurely ends the color environment. 
According to the [documentation for the color module](http://spack.readthedocs.io/en/latest/llnl.util.tty.html#module-llnl.util.tty.color), you can escape `}` using `}}` to avoid this problem. This works, however, you end up with `}}` in your output. Also, `color.cescape` doesn't escape this value by default.
My solution was to escape `}` in `color.cescape` and remove it later in `colorize`. I have no idea if this is the right thing to do. According to the docs, escaping `}` should only be necessary when using the `@color{text}` …
=> Fix coloring of error messages containing '}' symbol

lib/spack/spack/build_environment.py
```
==> Error: NameError: name 'foobar' is not defined
NameError: NameError: name 'foobar' is not defined
/Users/Adam/spack/var/spack/repos/builtin/packages/zstd/package.py:41, in install:
0         def install(self, spec, prefix):
1             make('install', 'PREFIX={0}'.format(foobar))
See build log for details:
/Users/Adam/spack/var/spack/stage/zstd-1.3.0-6bt7wh3xgg242a4saz3oojkcxbixoqar/zstd-1.3.0/spack-build.out
```
```
==> Error: NameError: name 'foobar' is not defined
/Users/Adam/spack/var/spack/repos/builtin/packages/zstd/package.py:41, in install:
0         def install(self, spec, prefix):
1             make('install', 'PREFIX={0}'.format(foobar))
See build log for details:
/Users/Adam/spack/var/spack/stage/zstd-1.3.0-6bt7wh3xgg242a4saz3oojkcxbixoqar/zstd-1.3.0/spack-build.out …
```
=> Don't duplicate Python error messages

lib/spack/external/ctest_log_parser.py
Fixes #8199 
Spack's build log error parser is a direct port of CTest's. The regexes it uses may work well for CMake, but they often trigger false positives for Autotools-based packages (see #8199). To reproduce this, uncomment any patches for the `fyba` package and try installing on macOS or with GCC 6.
Previously, any line containing `text:number: ` was matched. This regex has been removed. This resulted in the following error message no longer being caught:
```
INQTID.cpp:18:11: fatal error: 'sys/vfs.h' file not found
```
I removed the requirement for `: fatal error` to be preceded by a space to solve this. _Is the line after this now redundant?_
Fewer false positives for Autotools-based packages.
More false negatives?
=> Less sensitive error detection in build logs

lib/spack/spack/build_systems/cmake.py, var/spack/repos/builtin/packages/py-pybind11/package.py
Add test functionality to pybind11.
Without tests, this will skip the build and dependencies of the tests.
Also adds a check in CMake for targets `check` in `make/ninja check` for tests. This is now the same as in the build systems `Makefile` and `Autotools` and can be useful for manually added CMake targets for projects that do not (yet) use `CTest`.
=> pybind11: test functionality

lib/spack/spack/build_environment.py, lib/spack/spack/environment.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/environment.py
fixes #8345
This PR ensures that CC and similar environment variables are not accidentally modified when loading module files needed by compilers.
@tgamblin @mamelara I was wondering if this PR is fine for Cray too, or if we should have an exception for that.
=> Preserve a few environment variables when loading modules before build

var/spack/repos/builtin/packages/adios/nompi.patch, var/spack/repos/builtin/packages/adios/package.py
Provides a patch for the fix in
https://github.com/ornladios/ADIOS/pull/182
Installed ADIOS MPI-enabled libraries are with that able to also perform serial I/O without the need to start the whole app via `mpiexec`.
=> ADIOS: Serial API with Parallel Lib

var/spack/repos/builtin/packages/sz/package.py
I removed pwrType from the interface SZ_compress_args() which will be convenient for ADIOS developers to use SZ's API. 
This change will be consistent with our future version because pwrType will be deprecated in the later version. 
Please use this version in Spack and I'll notify the corresponding users such as ADIOS for the changes. 
Thanks.
=> new version SZ 1.4.13.5

lib/spack/spack/package.py, lib/spack/spack/test/packages.py
Fixes https://github.com/spack/spack/issues/7885
https://github.com/spack/spack/pull/7193 added the `patches_to_apply` function to collect patches which are then applied in `Package.do_patch`. However this only collects patches that are associated with the `Package` object and does not include `Spec`-related patches (which are applied by dependents, added in https://github.com/spack/spack/pull/5476). ~This updates the `Package.patches_to_apply` function to add `Spec` patches.~
EDIT: turns out `Spec.patches` already collects patches from the package so the `Package.patches_to_apply` function isn't necessary. All uses of `Package.patches_to_apply` are replaced with `Package.spec.patches`.
=> Fix bug where patches specified by dependents were not applied

var/spack/repos/builtin/packages/openpmd-api/package.py
We need a newer version of HDF5 and dropped the boost dependency.
Modernize the test variant to the spack test functionality.
=> openPMD-api: Update Dependencies

var/spack/repos/builtin/packages/ftgl/package.py
- `ftgl` needs to create its own `configure` script, therefore the `automake`, `autoconf`, ... dependencies
- `configure_directory` modification:
+ `ftgl-2.1.2` has the following directory distribution once downloaded, so a change of directory is required: 
```
ftgl-2.1.2-3xaq26mkzqunxhp463tfttgyjzg5oecj
FTGL/
COPYING.txt  
README.txt  
demo  
include      
mac              
src              
unix
spack-build.out  
test  
win32_vcpp
HISTORY.txt
cleanup     
docs  
license.txt  
spack-build.env  
```
+ However this happens to be only for the `2.1.2` version, a more recent `2.1.3-rc5` version does not contain this distribution so the modification of the `configure_directory` would not be needed. Note: this `2.1.3-rc5` has not been included for being a release-candidate.
=> Add new package: ftgl

var/spack/repos/builtin/packages/esmf/package.py, var/spack/repos/builtin/packages/flann/package.py, var/spack/repos/builtin/packages/jsoncpp/package.py, var/spack/repos/builtin/packages/libpipeline/package.py, var/spack/repos/builtin/packages/lz4/package.py, var/spack/repos/builtin/packages/openssl/package.py, var/spack/repos/builtin/packages/py-brian2/package.py, var/spack/repos/builtin/packages/py-elephant/package.py, var/spack/repos/builtin/packages/py-fiscalyear/package.py, var/spack/repos/builtin/packages/py-flake8/package.py, var/spack/repos/builtin/packages/py-mako/package.py, var/spack/repos/builtin/packages/py-matplotlib/package.py, var/spack/repos/builtin/packages/py-mccabe/package.py, var/spack/repos/builtin/packages/py-patsy/package.py, var/spack/repos/builtin/packages/py-pkgconfig/package.py, var/spack/repos/builtin/packages/py-psyclone/package.py, var/spack/repos/builtin/packages/py-py2cairo/package.py, var/spack/repos/builtin/packages/py-pynn/package.py, var/spack/repos/builtin/packages/py-qtconsole/package.py, var/spack/repos/builtin/packages/py-requests/package.py, var/spack/repos/builtin/packages/py-sphinx/package.py, var/spack/repos/builtin/packages/py-sphinxcontrib-websupport/package.py, var/spack/repos/builtin/packages/py-theano/package.py, var/spack/repos/builtin/packages/rr/package.py, var/spack/repos/builtin/packages/wget/package.py
This PR mass-uncomments all `type='test'` dependencies. There are also a couple of other drive-by's (like removing an unnecessary python dependency or so). Note: I haven't tested any of these, and I'm not too sure if doing this en masse is really a good idea. 
Feel free to close if you don't think it is a good idea at all, then I'll take this branch as a source for future work for me. Otherwise I'll point out the packages that I actually mange to get around to build and take it from there
=> add commented test dependencies

var/spack/repos/builtin/packages/googletest/package.py
This PR adds a shared variant to all given versions of this package which builds/installs DLLs if requested with '+shared'.  The previous default (static libs) is NOT preserved; the new default is to produce shared libs.
=> googletest: add a shared variant for all supported versions

var/spack/repos/builtin/packages/qt/package.py
I finally managed to track down the build failure of newer qt's on our system. This PR adds the `-skip wayland` to the qt build for newer qt's. Wayland seems to be a replacement for `x` but wasn't shipped with our (fairly minimal) Ubuntu so the qt-build fails a couple of minutes in.
This is a fairly brutal solution, but I prefer it over adding a variant would only work on some systems. If someone needs it I'll add the links to the qtwayland documentation 
https://wiki.qt.io/QtWayland
https://wayland.freedesktop.org/ubuntu16.04.html
=> fix qt@5.8: build on systems without wayland

var/spack/repos/builtin/packages/sqlite/package.py, var/spack/repos/builtin/packages/sqlitebrowser/package.py
Add `functions` variant to `sqlite`. Modelled largely after the homebrew [recipe](https://searchcode.com/codesearch/view/99133946/)
=> add sqlitebrowser

lib/spack/spack/cmd/clean.py
Continuing the discussion from #8090, this is a quick way to clean up spack's python caches.
Would have probably been helpful to have this ability in #8248, #8267, #8240, #8292
=> add python cache removal to `spack clean`

var/spack/repos/builtin/packages/elemental/package.py, var/spack/repos/builtin/packages/hydrogen/package.py, var/spack/repos/builtin/packages/lbann/package.py
~(Use the `elemental` package for older or non-fork versions of elemental)~
~hydrogen version `develop` should have been getting all of the cmake args, however because `develop` is not in `'@:0.84' or '@0.99:'`, this wasn't working.~
~Fixes hydrogen build on systems without cuda.~
EDIT:
TODO:
- ~look into the int64_blas `ar` path issue - no idea what the problem is~ This is going to be a different PR
=> Fix hydrogen@develop build

var/spack/repos/builtin/packages/intel-tbb/package.py, var/spack/repos/builtin/packages/intel-tbb/tbb_cmakeConfig.patch, var/spack/repos/builtin/packages/intel-tbb/tbb_gcc_rtm_key.patch
Improve to version -> URL translation to be algorithmic rather than manual.
Make binutils build dependency explicit where appropriate because we're sensitive to the assembler used.
Build's use of '-mrtm' is only patched away if it needs to be because the assembler is too old.
=> Update intel-tbb to 2018.3 and improve version URLs, dependencies and patching.

var/spack/repos/builtin/packages/tcl/package.py
This fixes a bug in the Tcl/Tk installation #8151.  Previously, the recipe for `tk` would erroneously pick up the system-installed `tcl.h` file.  This "worked" for newer systems that had TCL 8.6 installed.  The bug was unmasked building on SLES 11, which comes with an older version of TCL.
Long story short, the `tcl` build references the original sources upon install, and the `tk` build requires the `tcl` sources.  TCL sources were installed following the example of #4102.  If the user installs with `spack install --source`, then the sources would be copied twice.  This should not be a serious problem.
@junghans @davydden @tgamblin from #4083:
> Do we need a global variant, which modifies the hash for no reason related to the artifact, or would it make sense to just make this an install …
=> tcl: Install sources

var/spack/repos/builtin/packages/git/package.py
* `gitk` depends on TK at _runtime_. If TK's `wish` program isn't already on the system, `gitk` will fail to launch.
* I've been manually modifying the `git` module file generated by spack to satisfy this requirement.  This PR captures the requirement and automates the installation of `tk` and correct modulefile generation.
* Add a _runtime_ build dependency on `tk`
* Add an environment rule to add the path to TK's `wish` program to `$PATH` for  the generated `git` modulefile.
* After this PR, `spack install git` must also build `tk`.  This is a somewhat deep tree of dependencies.
```
^tk@8.6.8%gcc@4.8.5 arch=linux-rhel7-x86_64 
^libx11@1.6.5%gcc@4.8.5 arch=linux-rhel7-x86_64 
^inputproto@2.3.2%gcc@4.8.5 arch=linux-rhel7-x86_64 
^util-macros@1.19.1%gcc@4.8.5 arch=linux-rhel7-x86_64 …
```
=> Git's gitk needs TK's wish to be found in PATH

var/spack/repos/builtin/packages/superlu-dist/package.py
Latest superlu_dist sources now use INCLUDEDIR.
This change should not affect older superlu_dist version builds
cc: @jwillenbring @xiaoyeli
=> superlu_dist: fix 'spack install superlu-dist@develop'

lib/spack/spack/util/web.py
Fixes a bug in `spack versions` detection. By default, if a package does not specify a `list_url` and does not download from a common repository, Spack runs `dirname` on the URL. Given a URL like https://root.cern.ch/download/root_v6.09.02.source.tar.gz, this returns https://root.cern.ch/download. However, https://root.cern.ch/download gives a 404, while https://root.cern.ch/download/ works just fine. I think this is due to the presence or lack of an `index.html` file in the directory on the server? I don't claim to be a web dev expert 😛 
There are dozens of places this could have been fixed. We could have fixed it in the method that runs `dirname`, but I chose not to do this in case someone tries to add their own `list_url` but forgets the slash. We could have also fixed this in …
=> Fix list_urls missing trailing slash

var/spack/repos/builtin/packages/openfoam-com/package.py
The dev version of openfoam-com has submodules to be downloaded using spack fetch @olesenm
=> openfoam-com: added submodule flag to git fetch

var/spack/repos/builtin/packages/gdal/package.py, var/spack/repos/builtin/packages/gplates/package.py, var/spack/repos/builtin/packages/json-c/package.py
This also adds an older 1.x version to gdal that is required by gplates.
gplates is very particular about some of its dependencies. I have added comments explaining why specific versions were chosen as upper bounds.
If you want to compile this, gplates alone takes roughly four hours on one of our (older) nodes.
=> gplates: new package

var/spack/repos/builtin/packages/dyninst/package.py, var/spack/repos/builtin/packages/elfutils/package.py, var/spack/repos/builtin/packages/libdwarf/package.py
@lee218llnl @adamjstewart  
This PR supercedes #8181.  The submission was redone in order to clean-up extra merge commits.
```Summary:
Add access to the master tree for a dyninst@develop version  Also, fix issues related to trying to build dyninst due to dyninst's transition away from libelf and libdwarf as they move to elfutils and elfutils dwarf. From comments I added to the dyninst package.py file:
```
```
+    # Dyninst depends on libelf and libdwarf prior to 9.3.0
+    # Dyninst depends on elfutils and libdwarf from 9.3.0 to but
+    # not including 10.0.alpha
+    # Dyninst depends on elfutils and elfutils libdw from 10.0.alpha onwards
+    # elf@0 is an abstaction for libelf
+    # elf@1 is an abstaction for elfutils
```
=> Add the ability to build the dyninst master branch under the develop version name.

var/spack/repos/builtin/packages/xsdk/package.py
[error came up with the  prior url pointing to a 'master' branch. so fixing with a switch to a fixed tarball]
cc: @jwillenbring
=> xsdk: fix 'ChecksumError: md5 checksum failed'

var/spack/repos/builtin/packages/netgen/package.py
netgen compilation fails saying missing ```zlib.h```. fixes https://github.com/spack/spack/issues/8470
=> netgen should depend on zlib

var/spack/repos/builtin/packages/suite-sparse/package.py
Use the name of the Fortran compiler to determine what name mangling setting to use, instead of the spack compiler.
%clang can use multiple Fortran compilers with different options (see #8311, #8388, #8389, #8391, #8392, #8394), so we need to know what compiler is used in order to provide the correct options.
=> suite-sparse: Use actual Fortran compiler name to determine name mangling

var/spack/repos/builtin/packages/superlu-dist/package.py
Use no mangling for all spack compiler definitions that use the XL
Fortran compiler.  Do this by checking the Fortran compiler itself as opposed to the compiler suite, as clang can build with IBM XL Fortran compiler as well (see #8311, #8388, #8389, #8391, #8393, #8394).
=> Use no mangling for spack compiler definitions that use xlf

var/spack/repos/builtin/packages/petsc/package.py, var/spack/repos/builtin/packages/trilinos/package.py
Apply IBM XL patches for `trilinos` when using the llvm compiler suite, for when llvm is using xlf as its Fortran compiler.  Related to #8311, #8388, #8389, #8392, #8393, #8394.
=>  Patch trilinos for xlf when using clang

lib/spack/spack/compilers/clang.py
Update the clang compiler definition to use IBM XL Fortran compiler on CORAL systems (linux-rhel7-ppc64le).  This is needed because the llvm suite's `flang` compiler is not available for POWER platforms.  Related to #8311, #8388, #8391, #8392, #8393, #8394.
=> Update the clang compiler definition to use IBM XL Fortran compiler

var/spack/repos/builtin/packages/openssl/package.py
A new version of openssl was released this week.
=> openssl: add new version 1.0.2o

var/spack/repos/builtin/packages/mfem/package.py
This should resolve an issue encountered when building `xsdk@develop`.
=> [mfem] Add BLAS+LAPACK to the required dependencies of SuperLU_DIST

var/spack/repos/builtin/packages/samrai/package.py
This fixes #8491 and updates SAMRAI in the process. I tested 3.11.2, 3.11.5 and 3.12.0. I didn't want to do the full search for what version of boost stopped itself from being found by SAMRAI's configure, but boost v1.60.0 works, so I chose that for now.
=> Updates to SAMRAI

var/spack/repos/builtin/packages/trilinos/package.py
I have found that if NetCDF is specified as an external, I get concretization errors with `trilinos+pnetcdf`. This is because `parallel-netcdf` is only satisfied as a dependency through `netcdf+parallel-netcdf` when in fact, `parallel-netcdf` is a direct dependency of `trilinos+pnetcdf`. This makes `parallel-netcdf` a direct dependency of Trilinos when `trilinos+pnetcdf`.
=> Adding Parallel NetCDF as explicit dependency to Trilinos

var/spack/repos/builtin/packages/cbtf-argonavis-gui/package.py, var/spack/repos/builtin/packages/cbtf-argonavis/package.py, var/spack/repos/builtin/packages/cbtf-krell/package.py, var/spack/repos/builtin/packages/cbtf-lanl/package.py, var/spack/repos/builtin/packages/cbtf/package.py, var/spack/repos/builtin/packages/openspeedshop-utils/package.py, var/spack/repos/builtin/packages/openspeedshop/package.py
Add changes to the Krell packages with version updates and ranges for  the latest release.   Change the ranges on versions, so the packages don't have to change as much when a new release is made.  Also, the changes allows the development version of OpenSpeedShop to use the develop version of Dyninst.
=> Add changes to the Krell packages with version updates and ranges for  the latest release.

var/spack/repos/builtin/packages/opencv/dnn_cuda.patch, var/spack/repos/builtin/packages/opencv/package.py
Fixes #8461
When installing OpenCV 3.4.1 or older versions (I could reproduce the same behavior also with version 3.3.0) with +cuda and +dnn, then the compilation failed, because one of the header files from the OpenCV dnn module has the same name as a cuda header file and the cuda header file is included instead of the OpenCV one.
Issue #8461 contains more information on the problem.
=> Adding patch to Opencv (3.3.0-3.4.1) for fixing conflict between CUDA and OpenCV dnn header file

var/spack/repos/builtin/packages/samrai/package.py
SAMRAI: remove dependency on boost for samrai 3.12.0 or later versions, but keep the older versions continuing working with boost 1.64.0 or earlier. Also, the older versions cannot compile with boost 1.65.0 or above. (#8491)
=> samrai: update package for 3.12.0 and fix compilation bugs for earlier versions

lib/spack/docs/conf.py
Fixes an issue reported by @twang15 in #8491.
If you try to build Spack's documentation with Sphinx 1.7.1+, you encounter the following error message:
```
$ make
sphinx-build -b html -d _build/doctrees  -E . _build/html
Running Sphinx v1.7.5
usage: sphinx-build [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
sphinx-build: error: argument -d/--maxdepth: invalid int value: '_build/doctrees'
Configuration error:
The configuration file (or one of the modules it imports) called sys.exit()
make: *** [html] Error 2
```
This bug was introduced in https://github.com/sphinx-doc/sphinx/pull/4624, which first appears in Sphinx 1.7.1. See https://github.com/sphinx-doc/sphinx/issues/5104 for the nitty-gritty details.
The reason no one has noticed it until now is that we lock down our …
=> Allow docs to be built with Sphinx 1.7.1+

var/spack/repos/builtin/packages/zeromq/package.py
This addresses some build issues with GCC8
=> Bump ZeroMQ from v4.2.2 to v4.2.5

var/spack/repos/builtin/packages/kealib/package.py
Adds the latest version of kealib. Successfully installed and passed all tests on macOS 10.13.4 with Clang 9.0.0.
@gillins
=> Add kealib 1.4.8

var/spack/repos/builtin/packages/dealii/package.py
@jppelteret this is as much as we can do now to help users. Let me know if you prefer to reword anything. Although it's not a fix to the issue, I marking it as such as right now we can't do more.
fixes https://github.com/spack/spack/issues/8504
@christianbaensch would the following error be more helpful (see the bottom of this message, which is more descriptive now) :
```
$ spack spec dealii@8.4.2~mpi~petsc^openblas+ilp64
Input spec
dealii@8.4.2~mpi~petsc
^openblas+ilp64
Concretized
==> Error: Conflicts in concretized spec "dealii@8.4.2%clang@9.1.0-apple+adol-c+arpack+assimp build_type=DebugRelease ~cuda cuda_arch= +doc+gmsh+gsl+hdf5~int64+metis~mpi+nanoflann+netcdf+oce+optflags+p4est~petsc~python+scalapack+slepc+sundials+tr …
```
=> dealii: add msg= to conflicts statements

var/spack/repos/builtin/packages/openmpi/package.py
https://www.open-mpi.org/software/ompi/v3.0/:x
=> openmpi: add latest release 3.0.2

var/spack/repos/builtin/packages/valgrind/package.py
valgrind moved from svn to a git repo:
http://valgrind.org/downloads/repository.html
While the svn repo listed in spack still fetches, it's not the latest and greatest. 
I needed the latest develop branch to build on macOS 10.13 w/ xcode 9
The new url uses the `git://` protocol, which worked for me at home -- however this isn't idea b/c since many companies block a wide range of ports and the git protocol uses 9418.  (I can't fetch from it while at work)
I did also try:  https://sourceware.org/git/valgrind.git 
But this hung spack:
==> Trying to clone git repository: https://sourceware.org/git/valgrind.git 
fatal: dumb http transport does not support shallow capabilities
=> use new valgrind repo

var/spack/repos/builtin/packages/amrex/package.py, var/spack/repos/builtin/packages/boxlib/package.py
Boxlib and AMReX both build static libraries, but the CMake PIC option was wrong. I have verified that this adds in `-fPIC` to the compile lines where it wasn't before.
=> Correcting position independent code setting for boxlib and amrex.

var/spack/repos/builtin/packages/chombo/package.py, var/spack/repos/builtin/packages/lammps/package.py, var/spack/repos/builtin/packages/latte/package.py, var/spack/repos/builtin/packages/nalu/package.py, var/spack/repos/builtin/packages/nek5000/package.py, var/spack/repos/builtin/packages/nwchem/package.py, var/spack/repos/builtin/packages/openmc/package.py, var/spack/repos/builtin/packages/parsplice/package.py, var/spack/repos/builtin/packages/qmcpack/package.py
- All now have both `ecp` and `ecp-apps` tags.
- ECP ST projects will eventually also have `ecp` and `ecp-software` tags.
=> Add tags for ECP applications that are in Spack.

var/spack/repos/builtin/packages/elpa/package.py
absolutely untested as it simply does not configure / build on macOS 😞
=> elpa: add 2018.05.001.rc1 and 2017.11.001

var/spack/repos/builtin/packages/py-pillow/package.py
Rather than create a new version, they changed the 5.1.0 source file?
=> Updating py-pillow with change in checksum for version 5.1.0.

lib/spack/spack/compilers/gcc.py
This is a quick patch to fix gcc@8. Maybe we should come up with something more future-proof. :-)
=> Fix version detection for gcc@8

var/spack/repos/builtin/packages/m4/package.py, var/spack/repos/builtin/packages/m4/secure_snprintf.patch
m4 exited immediately (causing the nettle build to fail).
```
(alice)[11:09:46]spack>>/Users/hartzell/tmp/spack-mac/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/m4-1.4.18-caxsf7l5yd7qbq2bown6bzi5el3ltfwf/bin/m4
Abort trap: 6
(alice)[11:10:18]spack>>fg
```
Tracked down a fix via the Homebrew recipe.  I'll send a note to the
`bug-m4@gnu.org` list to ensure that upstream knows about it.
High Sierra does not seem to need the additional args appended that Sierra does so no changes were necessary in `configure_args`.
Tested by building nettle.
=> Fix m4 on OS X highsierra (allows nettle to build)

var/spack/repos/builtin/packages/plasma/package.py, var/spack/repos/builtin/packages/xsdk/package.py
plasma@develop has another flag 'DHAVE_MKL' that needs to be disabled [for non-mkl build]
add dependency on gcc-6.0
=> xsdk: update xsdk@develop to use plasma@develop

lib/spack/llnl/util/filesystem.py, lib/spack/spack/test/cmd/debug.py, lib/spack/spack/test/llnl/util/lock.py
Fixes #8225.
- Spack was assuming that a group with gid == current uid would always exist.
- This was breaking the travis build for macos.
- also fixed a bug in the `create_db_tarball` test where `.coverage.*` files weren't properly considered.
=> bugfix: fix macos incompatibility in lock test

var/spack/repos/builtin/packages/py-imageio/package.py
Add new package py-imageio.
Don't merge until concretizer can choose dependencies for python 2 vs 3. (Redundant dependencies can be added as a workaround if people need this.)
Note:  ```https://pypi.io/packages/source/I/imageio/imageio-2.3.0.tar.gz``` does not work
=> Add py-imageio for python3

var/spack/repos/builtin/packages/zoltan/package.py
The parmetis build system does not install metis.h and libmetis.  This PR specifies those dependencies via configure arguments.
=> zoltan: depends on metis.h and libmetis

var/spack/repos/builtin/packages/pumi/package.py
This PR adds a variant that enables pumi's fortran interface.
=> pumi: add fortran variant

var/spack/repos/builtin/packages/sbt/package.py
Requires #8565 to work correctly, so only the oldest version is available
=> Provide new version of sbt (simple build tool)

var/spack/repos/builtin/packages/mesa/package.py
- compiles with newer LLVM.
The older mesa-17 versions balk at the changes in the llvm::FastMath
class, where a member function has been removed.
=> New version mesa-18.1.2

var/spack/repos/builtin/packages/caliper/package.py, var/spack/repos/builtin/packages/gotcha/package.py
Add new versions of Caliper and Gotcha. Caliper now uses spack-built gotcha instead of downloading its own.
=> Add Caliper 1.7.0 and Gotcha 1.0.2

var/spack/repos/builtin/packages/kealib/package.py
See https://github.com/spack/spack/pull/8522#issuecomment-400903146 for an explanation of the changes that were needed to add 1.4.9 support.
Installed and tested all 3 versions on macOS 10.13.5 with Clang 9.0.0. Haven't tested with GDAL though.
@gillins
=> Add kealib 1.4.9

var/spack/repos/builtin/packages/cfitsio/package.py
Builds and passes tests on macOS 10.13.5 with Clang 9.0.0.
=> Add CFITSIO 3.450

var/spack/repos/builtin/packages/openfoam-com/common/spack-Allwmake, var/spack/repos/builtin/packages/openfoam-com/common/spack-derived-Allwmake, var/spack/repos/builtin/packages/openfoam-com/package.py, var/spack/repos/builtin/packages/openfoam-org/assets/bin/foamEtcFile
* Some support for packages building with OpenFOAM
- Adjust the wrappers calling the OpenFOAM Allwmake script. Have them
look for a Allwmake-spack file first, which is assumed to contain
special adjustments for compiling with spack.
This file could be delivered as part of a tarball (which is unlikely)
or generated on the fly by the spack sub-package as part of its
patch or configure stage.
CONFIG: change the default paraview variant for openfoam to be False
- the different combinations of paraview backends, off-screen etc
make it difficult to suggest that building with paraview as
a standard dependency makes much sense.
Additionally, building paraview with qt can become quite an issue.
So it makes much more sense to only enable that upon request.
ENH: add a +vtk variant.
- for VTK with …
=> ENH: Building OpenFOAM sub-packages (issue #8579)

var/spack/repos/builtin/packages/amrvis/package.py
This is one of the more difficult applications I've tried to package because it's just makefiles and the makefiles are mostly based on computing sites. I'm open to any better ways to package this thing.
I basically filter all the makefile options that exist to be exactly what I want, using variants where necessary, then remove all the references to `/usr` and `/opt` it searches for libraries in by default, and then I insert lines into the makefile that point the include and library locations to the Spack built libraries. Then I manually install the binary.
=> Add Amrvis package

var/spack/repos/builtin/packages/sbt/package.py
This commit bumps sbt version to 1.1.6. Since url https://dl.bintray.com/sbt/native-packages/sbt/0.13.12/sbt-0.13.12.tgz becomes invalid and I found nowhere on the Internet to download `sbt-0.13.12.tgz`, I deleted version `0.13.12` from the package.
=> Bump sbt to 1.1.6.

var/spack/repos/builtin/packages/gcc/package.py, var/spack/repos/builtin/packages/gcc/signal.patch, var/spack/repos/builtin/packages/gcc/stack_t-4.9.patch, var/spack/repos/builtin/packages/gcc/stack_t.patch, var/spack/repos/builtin/packages/gcc/ucontext_t-java.patch, var/spack/repos/builtin/packages/gcc/ucontext_t.patch
I was trying to build gcc@4.9.4 on Fedora 28, which has a newer version of glibc than what older versions of gcc support. The patches are already included in the 5/6/7/8/trunk branches but this adds them to the earlier versions (including 4.9). Sadly, we cannot simply download the patches because they include changes to the ChangeLog file.
I have done a few full builds of gcc@4.9.4 on Fedora 28 (new glibc) and Ubuntu 16.04 (old glibc) and everything seems to work fine.
=> gcc: Fix build of older versions with recent versions of glibc

var/spack/repos/builtin/packages/wcslib/package.py
Also adds a version-specific URL so that the checksum doesn't fail when a new release is added.
The default variants build in parallel fine for me on macOS 10.13.5 with Clang 9.0.0, but the package fails when I try to build `+cfitsio`.
=> Add missing dependencies and variants to wcslib

var/spack/repos/builtin/packages/glog/package.py
Miraculously, this didn't break anything, but also doesn't run `make`. The only reason that this worked is that `make install` knows that it has to build the libraries first.
The `trinity` package also makes this mistake, but will be fixed in #8516.
=> Glog: make is a function

var/spack/repos/builtin/packages/git/package.py
sha256 source here: https://mirrors.edge.kernel.org/pub/software/scm/git/sha256sums.asc 
edit: Maybe I should add a bit of an explanation here. The idea for this PR started, when I added a newer git version and the sha256 that `spack` got wasn't the one from the signed document linked above. kernel.org is kind of anal regarding chain of trust, so I'd prefer using their infrastructure as much as possible rather than github.com's autogenerated tar-balls (where they don't guarantee checksum stability).
I basically replaced all md5sums into sha256s and moved the url to kernel.org
=> switch git to kernel.org source and sha256

var/spack/repos/builtin/packages/ruby/package.py
I can successfully build this, but it currently crashes during the `post_install` step.
@goxberry It looks like you wrote this logic in #6935. Can you take a look? It seems like the problem is that the destination directory no longer exists. This isn't hard to fix, but I'm wondering if this resource is even needed anymore, or if we are missing a new resource.
=> Add url_for_version and list_url to Ruby package

lib/spack/docs/module_file_support.rst
`use` is an overloaded word between dotkit, modules and spack.  Add additional words to make the distinction clear in the docs.
=> Clear up a bit of modules/dotkit confusion

var/spack/repos/builtin/packages/git/package.py
The entries for git@2.17.1 and git@2.17.0 were swapped.
This fixes them.
=> Fix digests for git@2.17.0 and git@2.17.1

var/spack/repos/builtin/packages/singularity/package.py
- Versions before 2.5.2 suffer from a serious security problem
(https://nvd.nist.gov/vuln/detail/CVE-2018-12021).  Deleted all
versions prior to v2.5.2.
- Update homepage (looks like singularity's going Freemium).
- Use release tarball instead of automagically generated archive
tarball (digest values are more stable).
- No longer need autotools for released versions, just @devel.
- Install needs to be single-threaded, otherwise when installed as
root the various 'chmod' operations race against the copies.
Closes #8656
=> Fix security issue in singularity + misc cleanups

var/spack/repos/builtin/packages/uncrustify/package.py
Since the build system changed for uncrustify at version 0.64,
I had to change the package from an AutotoolsPackage to a plain
Package and use @when annotations to build the packages differently.
=> Added support for uncrustify 0.67.

var/spack/repos/builtin/packages/trilinos/package.py
This updates the dependencies of DataTransferKit to follow recent changes.
=> trilinos: update dtk dependencies

etc/spack/defaults/config.yaml, lib/spack/docs/config_yaml.rst, lib/spack/env/cc, lib/spack/spack/build_environment.py, lib/spack/spack/schema/config.py
Fix #5504
```
export SPACK_ENABLE_CCACHE=yes
export PATH="/path/to/cache${PATH:+:}${PATH}"
spack install libelf
ccache -z
spack uninstall libelf && spack install libelf
ccache -s
```
and yeah
```
cache directory                     /home/junghans/.ccache
primary config                      /home/junghans/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                   114
cache hit (preprocessed)               0
cache miss                             4
called for link                        1
called for preprocessing              18
compile failed                         2
autoconf compile/link                 21
files in cache                       394
cache size                           5.8 MB
max cache size                       5.0 GB
```
=> ccache support

var/spack/repos/builtin/packages/libnova/package.py
requires autoreconf due to
```
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1ubuntu1, but the
libtool: definition of this LT_INIT comes from libtool 2.2.6b.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1ubuntu1
libtool: and run autoconf again.
```
=> libnova: new package

var/spack/repos/builtin/packages/libxshmfence/package.py
libxshmfence@1.2 does not compile with recent versions of glibc.
I have also updated the URL and switched to bz2 tarballs to save bandwidth.
=> libxshmfence: Update to 1.3

var/spack/repos/builtin/packages/mvapich2/package.py
Probably needs more testing. Only tried this on my laptop so far, but when I set `psm` as an external it seems to do what I expect.
=> Adding psm as a dependency of mvapich2.

var/spack/repos/builtin/packages/netlib-lapack/package.py, var/spack/repos/builtin/packages/netlib-lapack/undefined_declarations.patch
There is a problem when linking to netlib-lapack 3.8.0 that has already been fixed upstream: https://github.com/Reference-LAPACK/lapack/issues/228
This PR adds that patch for the affected release.
=> Patch for 'netlib-lapack'.

var/spack/repos/builtin/packages/py-cutadapt/package.py
found this when people were using trimgalore, which calls cutadapt, and leads to:
```
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
=> py-cutadapt: needs py-setuptools at runtime

lib/spack/spack/package.py, lib/spack/spack/test/packages.py, var/spack/repos/builtin.mock/packages/url_override/package.py
fixes #2737
The issue with #2737 was due to the logic with which the nearest URL of a version was computed. This commit changes that logic, so that overrides are local to the versions declaring them.
A unit test has been added to avoid regressions on this issue.
=> Version specific URL overrides won't propagate to newer versions

var/spack/repos/builtin/packages/scotch/libscotchmetis-return-6.0.5a.patch, var/spack/repos/builtin/packages/scotch/package.py
Prevent this error:
metis_graph_part.c:301:7: error: non-void function 'METIS_PartGraphVKway' should return a value
[-Wreturn-type]
=> Scotch: fix compilation of 6.0.5a

var/spack/repos/builtin/packages/mothur/package.py
MPI was removed from Mothur in 2015:
https://github.com/mothur/mothur/commit/5e42a11c07231861c58d2fe1626c4a6b78a52918
So, this dependency was not actually being used
=> mothur: mpi not used

var/spack/repos/builtin/packages/amrvis/package.py
Somehow this mistake eluded me when I first developed this package.
=> Fixing error in amrvis package.

var/spack/repos/builtin/packages/charm/package.py
This allows building MPI applications on top of charm/AMPI without
having to specify another backend.
=> Charm: set default backend to netlrts

lib/spack/spack/main.py, lib/spack/spack/test/cmd/print_shell_vars.py, share/spack/setup-env.sh
This PR is several commits on top of #7774.  Merge that first.
The setup-env.sh script currently makes two calls to spack, but it should only need to make one.
This simplifies setup code, as it only has to eval what Spack prints. 
We should consider eventually making the whole setup script the output of a spack command, now that spack initialization is a faster.
=> add `spack --print-shell-vars` to speed up shell setup

lib/spack/spack/package.py, lib/spack/spack/test/data/packages.yaml, lib/spack/spack/test/database.py, var/spack/repos/builtin.mock/packages/externaltool/package.py
fixes #8036
Before this PR Package.installed was returning True if the spec prefix existed, without checking the DB. This is wrong for external packages, whose prefix exists before being registered into the DB.
Now the property checks for both the prefix and a DB entry.
=> Package.installed now checks both the presence of prefix and a DB entry

var/spack/repos/builtin/packages/trilinos/package.py
@davydden @aprokop I noticed the latest Trilinos `develop` broke the `xlf_seacas.patch` patch so Trilinos fails completely for me when using Clang.
=> Confine the xlf_seacas.patch for trilinos to version 12.12.1

share/spack/setup-env.csh
Fixes #8734.
It looks like this bug was inadvertently introduced in #8101. Another reason why #7604 would be useful.
@anderson2981 can you test this?
=> Add spack to PATH before calling spack in setup-env.csh

var/spack/repos/builtin/packages/openmpi/package.py
This adds variant `cxx_exceptions`, to the openmpi package. When on, this passes `--enable-cxx-exceptions` as a config argument to openmpi. The variant defaults to `True`. 
This option avoids outright openmpi crashes when C++ MPI programs throw exceptions, and allows you to actually see c++ exception messages.
=> openmpi: add c++ exceptions cfg option variant

var/spack/repos/builtin/packages/nwchem/package.py
without link type specified, I could not install nwchem.  I would get a linking error like so:
```
gfortran  -Wl,--export-dynamic  -L/opt/spack/var/spack/stage/nwchem-6.8-fdlc5rncsvahrf26hbuueahg6byx6nt5/nwchem-6.8-release/lib/LINUX64 -L/opt/spack/var/spack/stage/nwchem-6.8-fdlc5rncsvahrf26hbuueahg6byx6nt5/nw
chem-6.8-release/src/tools/install/lib   -o /opt/spack/var/spack/stage/nwchem-6.8-fdlc5rncsvahrf26hbuueahg6byx6nt5/nwchem-6.8-release/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -l
moints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband 
-lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot …
```
=> nwchem: add link type to python dep

var/spack/repos/builtin/packages/kealib/package.py
Successfully installs and passes all tests on macOS 10.13.6 with Clang 9.1.0.
@gillins
=> Add kealib 1.4.10

lib/spack/docs/configuration.rst, lib/spack/spack/config.py, lib/spack/spack/error.py, lib/spack/spack/main.py, lib/spack/spack/test/config.py
This is a slight rework of the very nice #2686 that @citibeth wrote a while ago.  Key differences:
* it accounts for the changes in #7774 
* it improves the way initialization works in `spack.main`
* the argument for passing a configuration scope is `-C` / `--config-scope`
The last one leaves room for a future `-c` / `--config` option that would adjust *one* configuration setting (like `git`'s `-c`).
Basically, this PR lets you do this:
```
spack -C /path/to/special-config install package
```
Where `path/to/special-config` can contain `packages.yaml`, `config.yaml`, etc.
There is more fancy stuff coming in #8231, but we have some users who need to make use of this feature now, and it's still useful even with #8231.  People would like to keep several different configurations in version …
=> Command line scopes

lib/spack/spack/test/stage.py
I kept seeing things like this in my `~/.spack/config.yaml`:
```cosole
$ cat config.yaml 
config:
build_stage:
- /private/var/folders/0s/q_y0zhfj6xdd5n7rn780zz6h001qr7/T/pytest-of-gamblin2/pytest-842/test_keep_exceptions0/tmp
```
Turns out two tests were modifying the *actual* config rather than a temporary test config.  This fixes the fixtures so that doesn't happen.
=> bugfix: stage test no longer modifies ~/.spack/config.yaml

var/spack/repos/builtin/packages/moab/package.py
Dependence on Lapack is necessary for MoAB. MoAB installation had been working because the specific implementation of Blas, i.e. OpenBlas provided Lapacak. However virtual package Lapack and Blas could have a separate implementation, and for such case MoAB install would not work.
Moreover, PR fixes flags for Blas. The previous fix will not work on the same platforms, and MoAB install will throw linking errors for blas and lapack functions.
=> add necessary dependence on lapack, and fix ld_flags for blas

var/spack/repos/builtin/packages/augustus/package.py
With the current version of Augustus package.py when trying to install an error message we'll be displayed as the version 3.3 was moved to the directory **old** (same URL), so I've updated the package including the latest version 3.3.1
=> Augustus updated to version 3.3.1

var/spack/repos/builtin/packages/libbeagle/package.py
also sets ld_library_path so dependents (like beast) can find libbeagle correctly
=> libbeagle: add java dependency so jni hooks get built

var/spack/repos/builtin/packages/trinity/package.py
This ensures the plugins are actually built. One of the plugins is an autotools packages, so added dependencies for that, and it also required the openmp flag to be set.
=> Trinity plugins

lib/spack/spack/directives.py, lib/spack/spack/fetch_strategy.py, lib/spack/spack/package.py, lib/spack/spack/patch.py, lib/spack/spack/test/url_fetch.py, lib/spack/spack/util/web.py, var/spack/repos/builtin.mock/packages/url-list-test/package.py, var/spack/repos/builtin/packages/bohrium/package.py, var/spack/repos/builtin/packages/zsh/package.py
This changes the `spack checksum` and `spack create` commands to generate `sha256` hashes instead of `md5` hashes.  New packages should start using `sha256` instead of `md5` as we transition, per [NIST guidelines](https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions).
Also, while Spack still allows packages to write versions like this:
```python
version('1.0', '2842bab891cfbf3269a3c4bd8f22fef23c9a15a790ba48c6490730cb51ce9b0e')
```
This change makes `spack create` and `spack checksum generate code like this:
```python
version('1.0', sha256='2842bab891cfbf3269a3c4bd8f22fef23c9a15a790ba48c6490730cb51ce9b0e')
```
I think this makes the packages easier to read, if not to write.  New users will at least have something they can google now (`sha256`) rather than just seeing …
=> `spack checksum` now uses sha256 instead of md5

.travis.yml
Python 3.7 was released on June 27, 2018. More information [here](https://docs.python.org/3/whatsnew/3.7.html).
=> Test Spack on Python 3.7 as part of Travis CI

lib/spack/spack/cmd/module.py
Fix this output error:
```
$ spack -m module loads mpileaks
==> Error: `spack module loads -m t -m c -m l ...` has been moved. Try this instead:
$ spack module t loads mpileaks
$ spack module c loads mpileaks
$ spack module l loads mpileaks
```
=> bugfix: `spack module -m` error message is correct with no `-m`

lib/spack/spack/test/url_fetch.py, lib/spack/spack/util/crypto.py
I did this as part of other PRs but it turned out not to be necessary.  It's still useful, so here's a separate PR.
=> core: make `spack.util.crypto` initialization less complicated

lib/spack/spack/cmd/url.py
Because dictionaries aren't sorted in Python 3.
```console
$ spack url summary
==> Generating a summary of URL parsing in Spack...
Total URLs found:          2907
Names correctly parsed:    2522/2907 (86.76%)
Versions correctly parsed: 2462/2907 (84.69%)
==> Statistics on name regular expressions:
Index  Count  Regular Expression
8:   1827   r'^([A-Za-z\\d+\\._-]+)$'
0:    669   r'github\\.com/[^/]+/([^/]+)'
3:     28   r'bitbucket\\.org/[^/]+/([^/]+)'
4:    365   r'pypi\\.(?:python\\.org|io)/packages/source/[A-Za-z\\d]/([^/]+)'
1:      9   r'gitlab[^/]+/api/v4/projects/[^/]+%2F([^/]+)'
6:      5   r'\\?package=([A-Za-z\\d+-]+)'
2:      1   r'gitlab[^/]+/(?!api/v4/projects)[^/]+/([^/]+)'
==> Statistics on version regular expressions:
Index  Count  Regular Expression
0:   1883 …
```
=> Fix order of regexes reported by spack url summary

var/spack/repos/builtin/packages/intel-tbb/disable-tm.patch, var/spack/repos/builtin/packages/intel-tbb/package.py
Fixes #6090.
Some AMD or very old Intel systems don't support transactional memory.
This commit adds a variant (default False) to allow running on those
systems.
=> intel-tbb: Add variant to disable transactional memory.

var/spack/repos/builtin/packages/hmmer/package.py
Added HMMER 3.2.1 and updated URL then removed url_for_version function as no longer required - all HMMER downloads available from updated URL.
=> hmmer: added version 3.2.1 & updated URL

var/spack/repos/builtin/packages/ftgl/package.py, var/spack/repos/builtin/packages/ftgl/remove-extra-qualifier.diff
Trying to build FTGL in a GCC 8.1-based Docker image, I found two issues:
- There is an unnecessary qualifier in a C++ header, which leads to a warning in GCC 8, and for some reason someone thought that enabling -Werror in production builds was a good idea...
- Although the package will build if Doxygen is not present, it will not install because the installer unconditionally assumes that the docs folder is present.
This PR provides two basic workarounds for these issues. However, if someone with autotools experience can have a look at the FTGL source and tell me how to 1/remove this silly -Werror compilation flag and 2/make sure that the absence of docs does not make installation fail, I think better fixes can probably be devised.
=> FTGL package workarounds

var/spack/repos/builtin/packages/py-numpy/package.py
Also fix `setup_dependent_package` to include the ".egg-less"-include
path.
=> py-numpy: Add C{,PLUS}_INCLUDE_PATH in modulefile

share/spack/setup-env.sh
When using zsh, trying to shift when there are no arguments left results in warnings like this: `spack:shift:22: shift count must be <= $#`
=> Fix shift warning on zsh

var/spack/repos/builtin/packages/gcc/package.py
I have used the official SHA512 checksum since we want to deprecate MD5 anyway.
=> gcc: Add 8.2.0

lib/spack/spack/spec.py, lib/spack/spack/test/cmd/spec.py
Resolves #8802.
- previously, output could be confusing when deptypes were only shown for one dependent when a node had *multiple* dependents
- merge the dependency types instead, so all the ways a node is depended on are shown
- also fix default coverage of `Spec.tree()`: it previously defaulted to cover only build and link dependencies, but this is a holdover from when those were the only types.
Example spec:
```
$ spack graph a
o  a
|\
o |  c
| o  b
|/
o  d
$ spack  spec -t --cover edges a
[    ]  a@1.0%clang@8.1.0-apple arch=darwin-highsierra-x86_64 
[ lr ]      ^b@1.0%clang@8.1.0-apple arch=darwin-highsierra-x86_64 
[b   ]          ^d@1.0%clang@8.1.0-apple arch=darwin-highsierra-x86_64 
[ lr ]      ^c@1.0%clang@8.1.0-apple arch=darwin-highsierra-x86_64 
[ lr ] …
```
=> spec: `Spec.tree()` merges deptypes when only covering nodes

var/spack/repos/builtin/packages/gsl/package.py
GSL-2.5 is out.  Notes for the version are at https://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS.
=> GSL: 2.5 is a new version.

var/spack/repos/builtin/packages/openmpi/package.py
This is my proposed solution for #8670 . It solved my problem where I use a GCC not installed in `/usr` for example, with `extra_rpaths` set to point to that GCC's libraries. Then when I build OpenMPI > 1.10.x using `fabrics=verbs`, which uses `--with-verbs` during OpenMPI configure, it finds the infiniband drivers in `/usr/lib64` so then it adds `-Wl,-rpath -Wl,/usr/lib64` to the OpenMPI wrappers. So then when I use the OpenMPI module to build other random software outside of Spack, the wrappers rpath `/usr/lib64` into the executable which then has GLIBC, GLIBCXX runtime errors due to it picking up libraries in `/usr/lib64` which is the system GCC, rather than my GCC I'm _actually_ using which is installed elsewhere.
Therefore this pull request adds in the directories from …
=> Add extra_rpath paths into rpath commands for openmpi wrappers.

lib/spack/docs/workflows.rst
The `--dependencies` and `--exclude` flags are now arguments to the `spack view`
comand rather than the `spack view symlink` command.
Closes #8836
=> docs: update `spack view` argument synatx

lib/spack/spack/test/data/modules/lmod/module_path_separator.yaml, lib/spack/spack/test/modules/lmod.py, share/spack/templates/modules/modulefile.lua, var/spack/repos/builtin.mock/packages/module-path-separator/package.py
=> lmod: fix use of custom separator in prepend_path etc.

var/spack/repos/builtin/packages/cmake/package.py
The problem described in #8317 is fixed for cmake 3.12.0. Let's just put conflict for cmake 3.11.x and Intel.
fixes https://github.com/spack/spack/issues/8317
=> Conflict for cmake 3.11.x and Intel.

var/spack/repos/builtin/packages/netlib-lapack/package.py, var/spack/repos/builtin/packages/netlib-lapack/testing.patch
I am not sure if this PR should be merged because this file is compiled only when testing is enabled and AFAIK only NAG compiler complains about the missing comma. Since some of the tests fail anyway (when compiled with NAG), it doesn't really solve much right now but maybe this will help someone in the future to get the tests run without failures.
=> Small patch for netlib-lapack.

var/spack/repos/builtin/packages/dia/package.py
When using spack on a ubuntu baseline system, I was unable to build dia without adding these build dependencies on _gettext_ and _pkg-config_.
=> Dia has build dependencies on gettext and pkg-config.

var/spack/repos/builtin/packages/openblas/package.py
This commit adds OpenBLAS 0.3.2 to spack, a release containing bugfixes for running multithreaded BLAS.
=> openblas: add version 0.3.2

var/spack/repos/builtin/packages/adios2/package.py
This also enables the bzip2 and zfp variants. The sz variant is currently broken.
=> adios2: add 2.2.0

var/spack/repos/builtin/packages/cmake/nag-response-files.patch, var/spack/repos/builtin/packages/cmake/package.py
The problem is described here: https://gitlab.kitware.com/cmake/cmake/issues/18232
At first, I was going to add something like this to the package I need:
```python
depends_on('cmake', patches=patch('cmake_nag.patch', when='@:3.12'),
type='build', when='%nag+shared')
```
But then I decided that it makes sense to patch CMake.
=> CMake: patch for NAG.

var/spack/repos/builtin/packages/pexsi/package.py
I found that pexsi@0.10.2 cannot be installed due to the following two reasons.
1. pexsi@0.10.2 is not compatible with superlu-dist@5.4.0 due to [Change LargeDiag to LargeDiag_MC64; Add LargeDiag_AWPM](https://github.com/xiaoyeli/superlu_dist/commit/d7dce5a3488f80645023ab8431d82399e5546ebf).
2. In the 'edit' phase, '@MPICXX_LIB' must be substituted before '@MPICXX' is substituted.
=> Update and Bugfix for pexsi/package.py

var/spack/repos/builtin/packages/trilinos/package.py
* `superlu-dist@5.4.0` introduced an API change that is not backward compatible.  This causes the spackage for `trilinos@12.12.1` to fail with the error:
```
6109    $HOME/spack/var/spack/stage/trilinos-12.12.1-2n3hngka6s5cigudpk5o5ojykzl4mtyz/Trilinos-trilinos-release-12-12-1/packages/amesos/src/Amesos_Superludist.cpp: In member function ‘int Amesos_Superludist::Factor()’:
>> 6110    $HOME/spack/var/spack/stage/trilinos-12.12.1-2n3hngka6s5cigudpk5o5ojykzl4mtyz/Trilinos-trilinos-release-12-12-1/packages/amesos/src/Amesos_Superludist.cpp:475:75: error: ‘LargeDiag’ was not declared in this scope
6111         if( RowPerm_ == "LargeDiag" ) PrivateSuperluData_->options_.RowPerm = LargeDiag;
6112                                                                               ^~~~~~~~~
6113 …
```
=> Trilinos: Update rules for superlu-dist version compatibility.

var/spack/repos/builtin/packages/sz/package.py
It looks like the checksum for SZ 2.0.2.0 has changed.
@disheng222 Can you say something about this? Thanks!
=> sz: fix checksum for 2.0.2.0

var/spack/repos/builtin/packages/fluxbox/package.py, var/spack/repos/builtin/packages/gdal/package.py, var/spack/repos/builtin/packages/graphviz/package.py, var/spack/repos/builtin/packages/i3/package.py, var/spack/repos/builtin/packages/mc/package.py, var/spack/repos/builtin/packages/neuron/package.py, var/spack/repos/builtin/packages/pandaseq/package.py, var/spack/repos/builtin/packages/perl-extutils-pkgconfig/package.py, var/spack/repos/builtin/packages/wireshark/package.py
pkgconfig is the correct virtual provider. This fixes strange problems during concretization when both pkg-config and pkgconf are requested.
To be precise, I have the following `packages.yaml`:
```yaml
packages:
ncl:
variants: +gdal
```
This causes the following error during concretization for ncl (see #4119):
```console
$ spack spec ncl
Input spec
ncl
Concretized
==> Error: There are no valid versions for spectrum-mpi that match ':'
```
Trying to force mvapich2 results in the following error:
```console
$ spack spec -I ncl ^mvapich2
Input spec
ncl
^mvapich2
Concretized
==> Error: Multiple providers found for 'pkgconfig': …
```
=> Fix pkg-config dependencies

lib/spack/llnl/util/filesystem.py, var/spack/repos/builtin/packages/libdwarf/package.py
- This was a nasty workaround due to the way our compiler wrappers used
to work.  We don't want to have to modify our elfutils installation to
install libdwarf.
- Since cd9691de5 (#4692), we no longer need this because the package will always
come before dependencies in our include order.
=> libdwarf: remove use of hide_files()

lib/spack/spack/cmd/arch.py, lib/spack/spack/cmd/help.py, lib/spack/spack/test/cmd/arch.py, share/spack/spack-completion.bash
Closes #8876.
@burgreen does this do everything you want?
=> Add spack arch --operating-system and --target flags

lib/spack/spack/cmd/spec.py, lib/spack/spack/test/cmd/spec.py
Some tweaks to `spack spec` behavior.  The extra newline was driving me nuts.
(only one newline now)
=> spack spec: no extra newline with --yaml; error with no specs

lib/spack/env/cc, lib/spack/spack/build_environment.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/cc.py
Fixes #8882.
Fixes #8887.
Reverts spack/spack#4692 while @becker33 and I work on a fix.
=> Revert "cc: package search paths come before dependency paths"

var/spack/repos/builtin/packages/lua-luaposix/package.py, var/spack/repos/builtin/packages/lua/package.py
I ended up on an [Ubuntu] system that hadn't had unzip employed
and discovered lua-luaposix requires it (while buildig Lmod).
Closes #8533
=> Add unzip runtime dependency to lua package

var/spack/repos/builtin/packages/mvapich2/package.py
MVAPICH2 v2.3 has been built sucessfully against GCC 5.4.0 on CentOS 7.
=> Bump mvapich2 to the latest v2.3 release.

var/spack/repos/builtin/packages/libtool/flag_space.patch, var/spack/repos/builtin/packages/libtool/package.py
It takes ages for any patches for libtool to get accepted, merged and released (if at all). This PR introduces version `@develop` with all prerequisites for bootstrapping. It should be noted that the releases can be and must be bootstrapped (with flag `--force`) if any patches are applied to them. So, I suggest that we have only one version `@develop` for any patches that we would like to have. This will also be easier to maintain them: no need to check if a patch works for any other version.
The first patch, which is included in this PR, fixes incorrect parsing of additional linking flags appended by a compiler. The comment in `libtool.m4` says that 
> Some  compilers place space between "-{L,R}" and the path.
but the logic implemented after the comment doesn't actually work. The patch …
=> Libtool: version 'develop'

var/spack/repos/builtin/packages/py-crossmap/package.py
Without this, I get: 
```  
File "setup.py", line 3, in <module>
from setuptools import *
ImportError: No module named setuptools
```
=> py-crossmap: needs py-setuptools

etc/spack/defaults/darwin/packages.yaml, etc/spack/defaults/packages.yaml, var/spack/repos/builtin/packages/apple-libunwind/package.py, var/spack/repos/builtin/packages/caliper/package.py, var/spack/repos/builtin/packages/gperftools/package.py, var/spack/repos/builtin/packages/libunwind/package.py, var/spack/repos/builtin/packages/mfem/package.py
This pull request attempts to implement the suggested steps outlined in #8823 to make `libunwind` a virtual package.
=> libunwind: make it a virtual package

lib/spack/spack/abi.py
I am getting the following issue on scientific linux 6 when using spack with gcc 7
```
$ spack spec heppy
Input spec
heppy
Concretized
==> Error: [Errno 22] Invalid argument: '/path/to/lib64/libstdc++.so'
```
Running with -d shows this stack trace
```
File "/build/paul/spack/bin/spack", line 61, in <module>
File "/var/build/paul/spack/lib/spack/spack/main.py", line 653, in main
return _invoke_command(command, parser, args, unknown)
File "/var/build/paul/spack/lib/spack/spack/main.py", line 432, in _invoke_command
return_val = command(parser, args)
File "/var/build/paul/spack/lib/spack/spack/cmd/spec.py", line 85, in spec
spec.concretize()
File …
```
=> os.path.realpath instead of os.readlink for checking gcc libstdcxx version

lib/spack/llnl/util/tty/log.py
Spack was doing active wait when compiling, spoiling one core.
My fix consists in not setting any timeout for select, instead of
the previous 0 second.
On a two cores machine, that results in a x2 boost for compilation.
=> Fix performance issue when compiling.

var/spack/repos/builtin/packages/elfutils/package.py
Add latest version 0.173.
Add variants bzip2, xz and zlib to support reading compressed DWARF
sections, default True.
Move maintainer-mode to a variant with default False.  This is only
useful for developers who want to modify the source for generated
files.
=> elfutils: update version and add variants

lib/spack/env/cc, lib/spack/spack/build_environment.py, lib/spack/spack/test/build_environment.py, lib/spack/spack/test/cc.py, lib/spack/spack/util/environment.py
Restoring the features from #4692.
**WIP because this is a placeholder. There are no fixes yet.**
@becker33: this is a branch to revert #8888 (or to un-revert #4692, I guess).
There are a few remaining things to do before we can merge this back to `develop`:
I am not sure what's causing the two issues above yet.
The OpenMPI issues I mentioned came from trying to build `petsc` -- OpenMPI won't build with the changes as it gets symbol errors linking `libopen-pal.40.dylib`.  I also noticed that there are warnings in the OpenMPI `clang` build that don't show up without the changes in #4692.  Specifically, stuff like this shows up for all the Spack `-L` arguments:
```
CC       base/btl_base_error.lo
clang: warning: argument unused during compilation: …
```
=> cc: package flags before dependency flags, part 2

var/spack/repos/builtin/packages/superlu-dist/package.py
Fix from @xiaoyeli
Note: currently parmetis is a hard dpependency in spack install of superlu-dist. So fix is to to always add `HAVE_PARMETIS=TRUE` flag to the build
=> superlu_dist should be built with 'HAVE_PARMETIS=TRUE'.

lib/spack/env/cc, lib/spack/spack/test/cc.py
Fixes #8920.
Our `cc` cleanup caused a parsing regression in flag handling.
We added proper quoting to array expansions, but flag variables were never actually converted to arrays, so our quotes made them into joined strings. The old code relied on this and split the arrays by *not* quoting them.
This commit:
@balay: please verify!
@becker33: FYI
=> bugfix: cc handles spaces in flag variables properly

var/spack/repos/builtin/packages/boost/package.py
The "graph" variant is declared twice in the Boost package, with two different defaults. This PR removes the declaration which I identified as being the "wrong" one, as it strays apart from the regular pattern of this package.
=> Remove duplicate declaration of "graph" variant in Boost package

lib/spack/spack/spec.py
As requested in the review of #8718, this change makes the format/length of the `full_hash` match that of the `dag_hash`.
=> Make the full_hash look like the dag_hash

var/spack/repos/builtin/packages/fasta/package.py
Add a package for the fasta sequence alignment tools.
The build system is novel (fasta is "venerable", so...).  The source tree includes nearly 50 variant Makefiles, the installer is expected to pick one that's appropriate and then edit the "XDIR" variable to specify the installation path.  I can only test 64 bit darwin and linux, so that's all I've included.  I'm also assuming that every 64bit x86 system we'll see supports the SSE2 extensions.  Other situations can be dealt with when someone has a test case.
I looked at using MakefilePackage but I didn't see how to specify the name of the Makefile that it used so this seemed cleaner.
Tested on a RHEL7 linux box and a High Sierra Mac by running the author's suggested test case:
```
fasta36 -q seq/mgstm1.aa seq/prot_test.lseg
```
=> Add package for fasta

var/spack/repos/builtin/packages/samtools/package.py
Install samtools headers and lib files to destination for legacy apps, like #8959 .
=> Install headers and lib files to destination for legacy apps

var/spack/repos/builtin/packages/git/package.py
Hi all, 
Just a digest update for the latest version of Git, released in June.
Thanks.
=> git: update with 2.18.0 digests

var/spack/repos/builtin/packages/bzip2/package.py
Fixes #8924 
The bzip.org domain has expired, and it doesn't sound like it will be restored any time soon (https://lwn.net/Articles/762264/). Switching to a mirror with the same version and checksum for the time being.
@JusticeForMikeBrown @balay @hartzell
=> Change bzip2 download URL

var/spack/repos/builtin/packages/zoltan/package.py
- building with the Intel compilers requires explicit linking with the Intel Fortran library (libifcore) similarly to the GCC case
=> zoltan: fix building with Intel compilers

var/spack/repos/builtin/packages/libtool/package.py
The bootstrap script does the cloning of the submodules but it's obviously better (e.g. when creating a mirror) if Spack does the job.
=> libtool: recursive cloning for the develop version.

var/spack/repos/builtin/packages/python/gcc-8-2.7.14.patch, var/spack/repos/builtin/packages/python/package.py
This fixes a compile error caused by a more aggressive optimiser in gcc8, fixed in mainline python2 starting at 2.7.15. I have no idea which other versions of python are affected (From the discussion on their mailing list I assume <3.5 and <2.7.14) and don't have the time to test build a lot of python's. I don't think that this will hit a lot of people in practice, but should be included anyway
=> add patch for gcc@8 for python 2.7.14

lib/spack/spack/cmd/versions.py, lib/spack/spack/package.py, lib/spack/spack/test/cmd/versions.py
This fixes a bug introduced by #3161 and generally improves the behavior of `spack versions` when URLs or versions are not present in a package.
Package with URL but no versions:
```console
$ spack versions zlib
==> Safe versions (already checksummed):
==> Remote versions (not yet checksummed):
1.2.11  1.2.7.3  1.2.6.1  1.2.5.1  1.2.4.3  1.2.3.9  1.2.3.5  1.2.3.1  1.2.2.2  1.2.1.1  1.2.0.6  1.2.0.2  1.1.3  1.0.9  1.0.5  1.0-pre  0.93  0.71
1.2.10  1.2.7.2  1.2.6    1.2.5    1.2.4.2  1.2.3.8  1.2.3.4  1.2.3    1.2.2.1  1.2.1    1.2.0.5  1.2.0.1  1.1.2  1.0.8  1.0.4  0.99     0.92  0.9
1.2.9   1.2.7.1  1.2.5.3  1.2.4.5  1.2.4.1  1.2.3.7  1.2.3.3  1.2.2.4  1.2.2    1.2.0.8  1.2.0.4  1.2.0    1.1.1  1.0.7  1.0.2  0.95     0.91  0.8
1.2.8   1.2.7    1.2.5.2  1.2.4.4  1.2.4    1.2.3.6  1.2.3.2 …
```
=> Fix spack versions behavior when no URL

var/spack/repos/builtin/packages/glib/old-kernels.patch, var/spack/repos/builtin/packages/glib/package.py
Red Hat/Centos 6 users get undefined variables when compiling at 2.56.  This patch removes the undefined variables and puts in the normal value for the buffer size.
=> glib: A patch to enable Red Hat 6 users to be able to compile the current version

var/spack/repos/builtin/packages/openfoam-com/package.py
- foam_add_lib() must be used instead of the undefined foamAddLib()
for adding VTK
=> openfoam-com: correctly use foam_add_lib()

lib/spack/docs/known_issues.rst, var/spack/repos/builtin/packages/blis/package.py
First pass at adding the [blis](https://github.com/flame/blis) linear algebra package.
=> Add blis package

var/spack/repos/builtin/packages/libcint/package.py
Update hashes to sha256 and add new version 3.0.12.
=> libcint: New version 3.0.12

lib/spack/spack/compilers/__init__.py, lib/spack/spack/directives.py, lib/spack/spack/hooks/__init__.py, lib/spack/spack/repo.py, lib/spack/spack/util/imp/__init__.py, lib/spack/spack/util/imp/imp_importer.py, lib/spack/spack/util/imp/importlib_importer.py
Fixes #8968.
- `imp` is deprecated and seems to have started having some weird issues on certain Linux versions.
- `importlib` is the new import system, and it allows us to get deeper into the import system from within Python.  Our `Repo` implementation can be simpler as a result.
Changes:
now and use it if importlib won't work.
=> imports: spack uses importlib when available, instead of imp 

var/spack/repos/builtin/packages/binutils/package.py
This PR adds the latest version of GNU binutils and updates the patch currently applied to `binutils@:2.29.1` to be consistent with GNU binutils upstream.
=> binutils 2.31.1

var/spack/repos/builtin/packages/vtk/package.py
Fixes #8997 
This PR fixes a bug where the system Python 2 gets picked up if Python 3 is in the DAG. By explicitly specifying the Python executable, the build succeeds.
@bassenj Can you test this?
=> Specify Python executable in VTK package

var/spack/repos/builtin/packages/cbtf-argonavis-gui/package.py, var/spack/repos/builtin/packages/qtgraph/package.py
Fix bug where we only supported lib64 when we needed to look at lib on some platforms and lib64 on others.  Found when trying to build on Power systems.
=> Change qtgraph and cbtf-argonavis to create proper module file library paths

lib/spack/llnl/util/filesystem.py, lib/spack/spack/test/llnl/util/filesystem.py, var/spack/repos/builtin/packages/foam-extend/package.py, var/spack/repos/builtin/packages/openfoam-com/package.py, var/spack/repos/builtin/packages/openfoam-org/package.py
Fixes https://github.com/spack/spack/issues/9001
See: https://github.com/spack/spack/pull/8289
This updates the `install_tree` method and its tests:
* `copy_tree`/`install_tree` now preserve relative link targets (if the symlink in the source directory structure is relative, the symlink created in the destination will be relative)
* Added support for `ignore` argument back to `copy_tree`/`install_tree`. It is no longer the object output by `shutil.ignore_patterns`: you pass a function that accepts a path relative to the source and returns whether that path should be copied.
* When a symlink target is absolute, `copy_tree` and `install_tree` now rewrite the source prefix to be the destination prefix 
* `copy_tree` tests no longer check permissions: `copy_tree` doesn't enforce anything …
=> install_tree relative symlinks

var/spack/repos/builtin/packages/openmpi/package.py
Final fix for v2.1 (hopefully)
Test build on LANL CCSCS4, Desktop
dantopa@ccscs4.lanl.gov:spack.log.in.ompi $ cd $(spack location -i openmpi/lrl77yt)
dantopa@ccscs4.lanl.gov:openmpi-**2.1.5**-lrl77ytyucpcld67c6g2bsl7zzolfdyv $ cd lib
dantopa@ccscs4.lanl.gov:lib $ ls -alh
total 20M
drwxr-x--- 4 dantopa dantopa 4.0K Aug 18 14:08 .
drwxr-x--- 8 dantopa dantopa  103 Aug 18 14:07 ..
. . .
lrwxrwxrwx 1 dantopa dantopa   17 Aug 18 14:08 libmpi.so.20 -> l**ibmpi.so.20.10.3**
=> Open MPI: add v2.1.5

var/spack/repos/builtin/packages/libfabric/package.py
libfabric 1.6.1 is out and fixes many problems that we see with 1.6.0.
=> libfabric: Add 1.6.1 release.

lib/spack/spack/build_environment.py, lib/spack/spack/error.py
Previously, if an error occurred during untarring, Spack would crash due to a missing `spack-build.out` file. Now, it exits a little more gracefully, revealing the real error message.
```console
$ spack install gmp
==> Installing gmp
==> Using cached archive: /home/hpc/spack/var/spack/cache/gmp/gmp-6.1.2.tar.bz2
==> Staging archive: /home/hpc/spack/var/spack/stage/gmp-6.1.2-6bsovvkqwx6zscwtbvjj6egrgizbyycm/gmp-6.1.2.tar.bz2
tar (child): lbzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
'/usr/bin/tar' '-xf' '/home/hpc/spack/var/spack/stage/gmp-6.1.2-6bsovvkqwx6zscwtbvjj6egrgizbyycm/gmp-6.1.2.tar.bz2' …
```
=> Fix error caused by missing spack-build.out build log

lib/spack/spack/package.py, lib/spack/spack/test/build_systems.py
fixes #9028
fixes #9067
Unit tests were failing on a system with GNU Make v 4.1
=> Added a new target message to comply with newer versions of GNU Make

var/spack/repos/builtin/packages/r-genomeinfodbdata/package.py
not sure why this one doesn't have a git repo like the rest. can't find it listed on bioconductor site.
=> r-genomeinfodbdata: new version

var/spack/repos/builtin/packages/leveldb/package.py
leveldb headers are typically included via <leveldb/c.h>. The migration to install_tree in 73c978ddd99973e29f2ba42078b10455c1de5ca8 caused the headers to end up in prefix.include, which breaks existing applications.
=> leveldb: Fix header installation

var/spack/repos/builtin/packages/libquo/package.py
This commit accomplishes a few things:
* Changes distribution fetch source
* Removes a deprecated version (1.2.9)
* Changes dependencies based on version type
* Adds a custom autoreconf stage when using the 'develop' version,
omitting this step when building from a distribution
=> libquo: Packaging updates.

lib/spack/spack/package.py
Previously, the following discrepancies existed in the messages printed by `spack activate` and `spack deactivate`:
* `spack activate` would print twice (once before "activating" and once when "activated"), while `spack deactivate` would only print once (when "deactivate")
* Specs when "activating" and when "activated" were colored differently
* Extendee spec was colored but extension spec was not
This PR removes those discrepancies.
=> More consistent colored messages from activate/deactivate

var/spack/repos/builtin/packages/mvapich2/package.py
Seems to work but it would be great if someone else could test this. @adamjstewart @alalazo 
Fixes #2200
=> mvapich2: Use rdma-core for mrail and nemesis*ib* fabrics

etc/spack/defaults/darwin/modules.yaml, etc/spack/defaults/linux/modules.yaml
Fixes #9066 
Are there any other macOS-specific environment variables we should be setting? Are there any other OSes that we support aside from `darwin` and `linux`?
@goxberry
=> Set DYLD_LIBRARY_PATH on macOS

var/spack/repos/builtin/packages/pocl/package.py
This is an attempt to integrate new versions of pocl in the corresponding package. It should not be merged yet as I am still testing the new versions.
Since the tarball URL has changed as part of the 1.0 release process, support for old 0.x versions of pocl now adds a bit of complexity. Should I drop these old releases or do we need to keep them around for compatibility?
=> Update the pocl package

var/spack/repos/builtin/packages/cppgsl/package.py
The [GSL](https://github.com/Microsoft/GSL) is meant to help C++ projects at the task of following the [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines). Since "GSL" is a highly overloaded acronym, I decided to name the package "cppgsl".
=> Add package for the C++ Guideline Support Library

lib/spack/spack/build_systems/python.py, var/spack/repos/builtin/packages/gdal/package.py, var/spack/repos/builtin/packages/py-atomicwrites/package.py, var/spack/repos/builtin/packages/py-funcsigs/package.py, var/spack/repos/builtin/packages/py-more-itertools/package.py, var/spack/repos/builtin/packages/py-numpy/package.py, var/spack/repos/builtin/packages/py-pathlib2/package.py, var/spack/repos/builtin/packages/py-pluggy/package.py, var/spack/repos/builtin/packages/py-py/package.py, var/spack/repos/builtin/packages/py-pytest/package.py, var/spack/repos/builtin/packages/py-scipy/package.py, var/spack/repos/builtin/packages/py-setuptools-scm/package.py, var/spack/repos/builtin/packages/py-setuptools/package.py
Fixes #9037.
However, this also uncovers another bug. When I try to build the latest version of numpy, all of the tests pass, but right before the installation finishes, I see the following error message:
```
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/Users/Adam/spack/var/spack/stage/py-numpy-1.15.1-axflucalynpnnr5camla655764dpyvqz/.pytest_cache/spack-build.out'
/Users/Adam/spack/lib/spack/spack/package.py:1652, in log:
1649            # FIXME : this potentially catches too many things...
1650            pass
1651
>>   1652        # Archive the whole stdout + stderr for the package
1653        install(self.log_path, log_install_path)
1654        # Archive the environment used for the build
1655        install(self.env_path, env_install_path)
```
The correct …
=> Update to latest version of pytest and dependencies

var/spack/repos/builtin/packages/openfoam-com/1806-have-kahip.patch, var/spack/repos/builtin/packages/openfoam-com/package.py
- OpenFOAM-v1806/wmake/scripts/have_kahip must check $KAHIP_ARCH_PATH
instead of $METIS_ARCH_PATH to detect the KAHIB library
- use a local patch file until the issue is hopefully fixed upstream
=> patch for OF.com@18.06 to correctly find KAHIP

var/spack/repos/builtin/packages/trilinos/package.py
The Trilinos/stk configuration is pretty Nalu specific right
now (and is acknowledged as such in a comment in this package.py file), and
this commit enables a module that Nalu will be needing.
Jon Rood suggests tagging him and Andrey: @jrood-nrel @aprokop
=> Add line in trilinos/stk configuration to enable stk_ngp package.

lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/compiler.py, lib/spack/spack/cmd/config.py, lib/spack/spack/cmd/mirror.py, lib/spack/spack/cmd/repo.py, lib/spack/spack/config.py, lib/spack/spack/modules/lmod.py, lib/spack/spack/test/modules/lmod.py
closes #8916
Currently Spack ends with an error if asked to write lmod modules files and the 'core_compilers' entry is not found in `modules.yaml`. After this PR an attempt will be made to guess that entry and the site configuration file will be updated accordingly.
This is similar to what Spack already does to guess compilers on first run.
@svenevs @SteVwonder
=> Spack guesses lmod core compilers

lib/spack/spack/cmd/modules/__init__.py
addresses #9077 (at least it improves the situation)
* now additionally prints hash and options
=> improve spack load error

var/spack/repos/builtin/packages/icedtea/package.py, var/spack/repos/builtin/packages/jdk/package.py, var/spack/repos/builtin/packages/octave/package.py, var/spack/repos/builtin/packages/openmpi/package.py, var/spack/repos/builtin/packages/spark/package.py, var/spack/repos/builtin/packages/thrift/package.py
This PR includes the following changes:
The last point is still a work in progress. Bugs I've discovered so far:
1. It is not possible to write `extends('java')`, you have to write `extends('jdk')` or `extends('icedtea')`. It seems that virtual providers are not extendable. This is important not only for Java, but also for Python. Someday we would like Python to become a virtual provider for CPython, Intel Python, PyPy, IronPython, etc. See #7966.
2. Packages cannot `extend` multiple packages: #987.
3. In order to activate/deactive a Java extension, we need to symlink all `*.jar` files to `spec['java'].lib.ext`. How do I do this? I only know how to merge the two installation prefixes. I guess I could start installing `.jar` files to `prefix.lib.ext` instead of `prefix`...
@hartzell I was …
=> Major overhaul of Java packages

var/spack/repos/builtin/packages/atk/package.py
Currently atk does not build because meson requires python3 and glib python2 by default (fixes #9099). Setting python3 as dependency for atk works as a hot-fix as a start.
=> Hotfix of atk regarding #9099

var/spack/repos/builtin/packages/string-view-lite/package.py
[string-view-lite](https://github.com/martinmoene/string-view-lite) is a header-only library for C++. Installation is as simple as performing a copytree.
=> Adds a package for string-view-lite header only library

var/spack/repos/builtin/packages/span-lite/package.py
[span-lite](https://github.com/martinmoene/span-lite) is a header-only library for C++. Installation is as simple as performing a copytree.
=> Adds a package for span-lite header-only library

var/spack/repos/builtin/packages/optional-lite/package.py
[optional-lite](https://github.com/martinmoene/optional-lite) is a header-only library for C++. Installation is as simple as performing a copytree.
=> Adds a package for optional-lite header-only library

lib/spack/spack/cmd/view.py
After we have now 3 open issues due to merge conflicts in `spack view`, I added a note to the existence of the `-i` (ignore conflicts) option in case of an error.
I'm not sure if I should intercept the error and update the error message or if this should directly be part of the original error message. This is the least invasive solution, nothing more.
Relates to #9029, #7001, #6266
=> on error spack view suggests -i option

var/spack/repos/builtin/packages/commons-lang/package.py, var/spack/repos/builtin/packages/commons-lang3/package.py, var/spack/repos/builtin/packages/commons-logging/package.py, var/spack/repos/builtin/packages/gdal/package.py, var/spack/repos/builtin/packages/jackcess/package.py
I had an old Microsoft Access Database file that I wanted to use, but QGIS doesn't support `.mdb` files. Apparently ArcGIS does, but ArcGIS doesn't support macOS/Linux. This driver allowed me to use `ogr2ogr` to convert it to a shapefile.
GDAL also supports MDB Tools for this purpose, but it sounds like MDB Tools has been unmaintained for quite some time.
Depends on #8613.
@michaelkuhn @neilflood @citibeth may be interested in this.
=> Add MDB driver support to GDAL

var/spack/repos/builtin/packages/binutils/package.py
Add variant 'nls' for native language support with default True.
The default inside binutils was always on, but this gives a way of
turning it off, if desired.
Adjust the dependencies.  Flex is never used for a one-time build.
Bison and m4 should not be needed, except that prior to rev 2.30, gold
did not include its generated files, so bison is needed when +gold.
Drop configure option --enable-interwork.  This option does not exist.
=> binutils: add variant 'nls' for native language support

var/spack/repos/builtin/packages/vim/package.py
Builds and passes tests on Blue Waters with GCC 7.3.0.
=> Vim: add version 8.1.0338

.travis.yml
Fixes #9031.
This cleans up `.travis.yml` (yes you can do multi-line scripts) and brings back macOS in the unit test stage.  Let's see if it's more reliable now.
=> Fix macOS support in .travis.yml

var/spack/repos/builtin/packages/silo/package.py
1. I presently get errors of the sort
```
==> Error: KeyError: 'No spec with name mpi in silo@4.10.2%gcc@8.1.0+fortran+mpi
[...]
$HOME/spack/var/spack/repos/builtin/packages/silo/package.py:84, in configure_args:
81                'FCFLAGS={0}'.format(self.compiler.pic_flag)]
82
83        if '+mpi' in self.spec:
>>     84            config_args.append('CC=%s' % self.spec['mpi'].mpicc)
85            config_args.append('CXX=%s' % self.spec['mpi'].mpicxx)
86            config_args.append('FC=%s' % self.spec['mpi'].mpifc)
```
without the extra explicit MPI dependency. I am a bit of a spack novice; I don't really understand why we need to explicitly write out the dependency when `+mpi` is in the spec, though a lot of other packages (e.g., Zoltan) do it.
2. Silo uses zlib, so we should …
=> Fix two dependencies with silo.

var/spack/repos/builtin/packages/cbtf-argonavis/package.py, var/spack/repos/builtin/packages/cbtf-krell/package.py, var/spack/repos/builtin/packages/cbtf-lanl/package.py, var/spack/repos/builtin/packages/cbtf/package.py, var/spack/repos/builtin/packages/openspeedshop-utils/package.py, var/spack/repos/builtin/packages/openspeedshop/package.py
Update the version numbers and now depend on
the develop version of dyninst because of a
feature in openspeedshop depends on new code
in the dyninst develop tree.  Without dyninst
develop, openspeedshop will not build.
=> Update openspeedshop and cbtf version numbers

var/spack/repos/builtin/packages/openblas/openblas-0.3.2-cmake.patch, var/spack/repos/builtin/packages/openblas/package.py
* Adds OpenBLAS version 0.3.1
* Adds a patch for OpenBLAS versions 0.3.1 and 0.3.2 that fixes `find_package(OpenBLAS)` in CMake. See https://github.com/xianyi/OpenBLAS/pull/1703 for the patch. The patch has already landed upstream and will be released with OpenBLAS 0.3.3.
=> openblas: add @0.3.1, patch CMake export bug in @0.3.1:0.3.2

var/spack/repos/builtin/packages/nlopt/package.py
Earlier release tarballs were actually AutoTools, not CMake.
Fixes #8127.
=> nlopt: Only support release>=2.5.0

var/spack/repos/builtin/packages/aida/package.py
This is old and long-abandoned HEP software, but for some reason a few important projects still rely on it.
As the package does not have a readily usable and well-documented automated installation mechanism, one needs to guess how to install things. I know how to install the C++ headers, which is what is usually needed, but there are also documentation and java files in that package which I don't know how to deal with.
As far as I know, Spack does not usually install docs, and no one is currently using the Java version of AIDA, so perhaps just installing the C++ headers is enough. If not, a bit of help from Java folks would be handy in order to get the installation right :)
=> New package: AIDA

lib/spack/spack/fetch_strategy.py
There are a variety of reasons that could cause a download to fail. The most common one in my experience has either been using the wrong URL when creating a package, or using a URL that has been moved and no longer exists. Previously, the warning message only warned of internet gateway issues.
With this PR, the chance of an invalid URL is mentioned as a possibility. Also fixed the formatting of the warning message.
```console
$ spack fetch animation
==> Fetching https://github.com/yihui/animation/releases/tag/v2.5/animation-2.5.tar.gz
######################################################################## 100.0%
==> Warning: The contents of 
the archive
look like HTML.
The checksum will likely be bad.  If it is, you can use
'spack clean <package>' to remove the bad archive, then
fix your …
```
=> Better warning message when fetching non-existent URL

lib/spack/spack/build_environment.py, lib/spack/spack/build_systems/cmake.py, lib/spack/spack/package.py, lib/spack/spack/test/make_executable.py, lib/spack/spack/util/executable.py
Closes #4503 (implementing the spirit of the request&mdash;parallelism for CMake tests&mdash;rather than the spirit&mdash;using the `ctest` command itself).
The existing implementation of the test target when building a CMake package using the Makefiles generator invokes `make test`, which does not honor the the `-j` option for parallelism. One can either set an environment variable ~~(difficult to handle the overrides currently available)~~ or one can invoke `ctest` instead of `make test`. This implementation (now) does the ~~latter~~ former in order to accommodate packages (see below) for which `make test` runs a set of tests which is distinct from that run by `ctest`.
[Description has been edited from the original due to the evolution of implementation to satisfy issues raised), with …
=> Actually allow parallel test execution under CMake.

var/spack/repos/builtin/packages/trinity/package.py
Depends on #8939 and #9048 - #9063 (others too, but just listing the open PRs)
We were still having runtime issues with Trinity, and I've been having several users run with these individual modules loaded for the last few weeks, and that seems to have done the trick so I'm adding as dependencies.
=> trinity: full dependencies

var/spack/repos/builtin/packages/skilion-onedrive/package.py
`skilion-onedrive` has been built sucessfully on CentOS 7 via
```
$ spack install dmd %gcc@5.4.0
$ source <(spack module tcl loads dmd %gcc@5.4.0)
$ spack install skilion-onedrive %gcc@5.4.0
```
=> Onedrive: a new package.

var/spack/repos/builtin/packages/dmd/package.py
Pack dlang's stdlib into dmd according to https://wiki.dlang.org/Building_under_Posix . After that, `hello.d` and `skilion-onedrive` #9130 have been built succesfully.
=> Pack dlang's stdlib into dmd.

var/spack/repos/builtin/packages/omega-h/package.py
* add 5 most recent versions and git master branch
* add trilinos, gmodel, throw, examples, optimize, symbols, and warnings variants
* disable XSDK so that Trilinos dependencies are found.
=> omega-h: add versions and variants

lib/spack/spack/build_environment.py, lib/spack/spack/spec.py, lib/spack/spack/test/build_environment.py
Fixes #9084 
Fixes #8632 
Fixes a bug that appeared on some Cray systems:
modules that prepended to the `PATH` variable were putting their paths ahead of the spack compiler wrappers. For compiler modules, this was a major problem.
This PR separates the environment sanitation from the environment changes, and moves the module loading operations to between the environment sanitation and the environment changes.
=> Reorder environment cleaning and module loads

var/spack/repos/builtin/packages/openpmd-api/package.py
Due to an internal bug regarding the handling of scalars (ndim must be 0) in numpy prior to 1.15.0, openPMD-api will require the latest numpy 1.15+.
Since there is a small regression with datetime pickling in 1.15.0 from the required fix and spack only packages 1.15.1 currently, we depend on 1.15.1 in the recipe.
=> openPMD-api: ^py-numpy@1.15+

lib/spack/spack/test/flag_handlers.py
This makes the flag_handlers test more robust and allows fixing the perl dependency in openssl (see #9106).
Fixes #6830
=> test: Make flag_handlers tests use mock repo

var/spack/repos/builtin/packages/trilinos/package.py
This patch does not apply cleanly anymore and breaks clang/Mac builds
```
balay@asterix /home/balay/git-repo/github/trilinos (develop=)
$ patch -Np1 < /home/balay/git-repo/github/spack/var/spack/repos/builtin/packages/trilinos/xlf_tpetra.patch
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/packages/tpetra/core/src/Tpetra_Details_libGemm.cpp
|+++ b/packages/tpetra/core/src/Tpetra_Details_libGemm.cpp
--------------------------
File to patch:
```
cc: @jwillenbring @keitat
This was previously changed at 54aab585c4 so cc: @djfitzgerald
=> trilinos: disable xlf_tpetra.patch for trilinos@develop

var/spack/repos/builtin/packages/petsc/package.py
* mpiifort doesn't automatically link all run-time libraries
* scalapack was being picked up accidentaly if intel-mkl was in the spec
(With help from @nrichart)
Signed-off-by: Ricardo Silva <ricardo.silva@epfl.ch>
=> petsc: fix compilation with intel

lib/spack/spack/test/module_parsing.py, lib/spack/spack/util/module_cmd.py
Fixes: https://github.com/spack/spack/issues/9083
The linked issue contains examples where Spack's parsing of `module show` produces incorrect results. This makes the following changes:
* Updates the pattern searching for several paths to avoid the case where they are prefixes of unwanted paths
* Adds a warning message when an extracted path doesn't exist (which may help catch future module parsing bugs faster)
* Adds a test with the content mentioned in #9083
=> Bug fix: module file path parsing

var/spack/repos/builtin/packages/py-espresso/package.py
/cc @KaiSzuttor
See https://github.com/espressomd/espresso/pull/2244
=> py-espresso: apply patch to v4.0.0 only

var/spack/repos/builtin/packages/py-colormath/package.py
=> py-colormath: new version

var/spack/repos/builtin/packages/gatk/package.py
The previous install process enumerated over many unnecessary files including directories which would cause the build to fail.
I added more criteria to the install process to only install necessary executable files.
=> gatk: new version

var/spack/repos/builtin/packages/metasv/package.py
these aren't mentioned on the homepage but are required to the run the tool.
=> metasv: add required dependencies

var/spack/repos/builtin/packages/py-multiqc/package.py
runtime error states 0.0.10 version of spectra is required 
depends on #9224
=> py-multiqc: needs newer py-spectra

var/spack/repos/builtin/packages/hypre/package.py
Add a debug variant to the spack hypre package. This variant is not present in #7606, or any open PR re: hypre, as far as I can tell.
=> hypre: add debug variant

var/spack/repos/builtin/packages/py-h5py/package.py
Successfully installed and tested on macOS 10.13.6 with Clang 9.1.0.
=> py-h5py: add version 2.8.0

var/spack/repos/builtin/packages/opencoarrays/CMakeLists.patch, var/spack/repos/builtin/packages/opencoarrays/package.py
On behalf of Brian Friesen at NERSC. This commit adds a patch that
prevents the package from hanging. The package would hang because
CMakeLists would look for a system MPI. This patch changes the behavior. Also updates the version.
=> OpenCoarrays: update v2.2.0

var/spack/repos/builtin/packages/flann/linux-gcc-cmakev3.11-plus.patch, var/spack/repos/builtin/packages/flann/package.py
See: https://github.com/mariusmuja/flann/issues/369
If a new version is added, maybe they will fix it?  AKA the patch may become irrelevant in the future, but for now it seems valid.  Maybe it would be ok to just wait for the patch to fail and then restrict versions that the patch gets applied to?
=> patch flann // gcc // cmake@3.11+

var/spack/repos/builtin/packages/opencv/package.py
There were some build failures on 3.4.1 and GCC 7.3.1 but I didn't understand what exactly the problem was.  I'm adding the new version, but don't know what to do about a `conflicts` here because it wasn't clear to me what versions of GCC were actually affected.
=> add opencv@3.4.3

var/spack/repos/builtin/packages/libffi/package.py, var/spack/repos/builtin/packages/openssl/package.py, var/spack/repos/builtin/packages/python/package.py, var/spack/repos/builtin/packages/sqlite/package.py
There are some building changes for Python 3.7.0: https://docs.python.org/3/whatsnew/3.7.html#build-changes
It's not allowed anymore to build Python with the bundled `libffi` on non-OSX UNIX. Since I don't know a nice way to express this in the `when` condition (is it possible to negate the condition `platform=darwin`?), I suggest that we build with an external `libffi` on MacOS too.
=> Build Python 3.7 with external libffi.

var/spack/repos/builtin/packages/hypre/darwin-shared-libs-for-hypre-2.13.0.patch, var/spack/repos/builtin/packages/hypre/darwin-shared-libs-for-hypre-2.14.0.patch, var/spack/repos/builtin/packages/hypre/package.py
Add a patch to build hypre with shared libraries on macOS for versions 2.13.0 and later. Patch has been submitted upstream.
=> hypre: patch to build shared libs on darwin for @2.13.0:

var/spack/repos/builtin/packages/amrvis/package.py
Creating a direct dependency on flex and bison were necessary because profiling support requires them. Also turning MPI off as the default since that's generally the first way someone would want to build Amrvis in my opinion.
=> Updating amrvis to allow building with profiling support.

var/spack/repos/builtin/packages/gdb/package.py
This is required at least on RedHat/Fedora.
Many (most?) other people distribute gdb with this support enabled:
http://tomszilagyi.github.io/2018/03/Remote-gdb-with-stl-pp
https://bugzilla.redhat.com/show_bug.cgi?id=1596490
=> gdb: add lzma support by default

var/spack/repos/builtin/packages/libhio/0001-spack-fix-for-spack-to-work-on-non-cray-systems.patch, var/spack/repos/builtin/packages/libhio/package.py
Turns out that there was a configury problem in libhio
which caused issues building the package on non-cray
systems, aka when using mpicc and friends.
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
=> libhio: add patch for 1.4.1.2 release

var/spack/repos/builtin/packages/apple-libunwind/package.py
This commit fixes the absolute path of Apple's `libunwind` library. The current version of the apple-libunwind package will link successfully if the libunwind linking flags are passed using `-L/usr/lib/system -lunwind`, but fail if passed as `/usr/lib/system/libunwind.dylib` with an error `cannot link directly with /usr/lib/system/libunwind.dylib`. The linker will suggest linking with `System.framework` instead; the path used in this commit is equivalent to linking with `System.framework`.  This linker error came up in a project that used CMake and attempted to pass an absolute path to libunwind to the system linker.
=> apple-libunwind: update path to library

var/spack/repos/builtin/packages/hadoop/package.py
The url for the latest Hadoop was broken (3.1.0 doesn't exist).
=> fix url and checksum

lib/spack/spack/test/url_parse.py, lib/spack/spack/url.py, var/spack/repos/builtin/packages/cistem/package.py
Fixes #9259 
```console
$ spack url parse "https://cistem.org/system/tdf/upload3/cistem-1.0.0-beta-source-code.tar.gz?file=1&type=cistem_details&id=37&force=0"
==> Parsing URL: https://cistem.org/system/tdf/upload3/cistem-1.0.0-beta-source-code.tar.gz?file=1&type=cistem_details&id=37&force=0
==> Matched version regex 10: r'^(?:[a-zA-Z\\d+-]+-)?v?(\\d[\\da-zA-Z.-]*)$'
==> Matched  name   regex  8: r'^([A-Za-z\\d+\\._-]+)$'
==> Detected:
https://cistem.org/system/tdf/upload3/cistem-1.0.0-beta-source-code.tar.gz?file=1&type=cistem_details&id=37&force=0
------ ~~~~~~~~~~~~~~~~~~~~~~
name:    cistem
version: 1.0.0-beta-source-code
==> Substituting version 9.9.9b:
https://cistem.org/system/tdf/upload3/cistem-9.9.9b.tar.gz?file=1&type=cistem_details&id=37&force=0
------ ~~~~~~
$ spack url …
```
=> Fix version parsing for cistem package

var/spack/repos/builtin/packages/catch/package.py, var/spack/repos/builtin/packages/openpmd-api/package.py
Add the latest two releases of Catch2. In 2.3.0+, the include changed to a future-proof `<catch2/catch.hpp>` path which dependent projects will break upon.
In Spack mainline, `openPMD-api` is the only project that depends on Catch2. Dependencies have been updated accordingly in it: https://github.com/openPMD/openPMD-api/pull/367
=> Catch2: 2.3.0+

var/spack/repos/builtin/packages/llvm/package.py
Built on Centos 7
```
$ spack find -v llvm
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
llvm@7.0.0+all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb+polly~python~shared_libs
```
=> Added llvm 7.0.0

.travis.yml, share/spack/qa/run-unit-tests
- Many container builds are timing out frequently during Spack tests in Travis CI.
- Travis recommends adding `sudo: required` to see whether this is an infrastructure issue or something else.
- added `sudo: required` to all Linux builds.
=> travis: require sudo in an attempt to avoid build timeouts

var/spack/repos/builtin/packages/qt/package.py
"-ldbus-1" was being passed as a configure arg and was breaking builds with dbus. I couldn't find any reference to this option in the Qt docs.
=> qt: fix dbus builds

etc/spack/defaults/config.yaml, lib/spack/llnl/util/lock.py, lib/spack/spack/database.py, lib/spack/spack/schema/config.py, lib/spack/spack/test/llnl/util/lock.py, lib/spack/spack/util/file_cache.py, lib/spack/spack/util/lock.py
See https://github.com/spack/spack/issues/9166
See https://github.com/spack/spack/issues/8915
This is intended to reduce errors related to lock timeouts by making the following changes
* (new 9/18) locks (those created using `spack.llnl.util.lock.Lock`) now have no timeout by default
* (updated 9/18) increases the default timeout *for database locks*
* (new 9/18) by default locks taken on individual packages do not have a timeout. A timeout can be added by setting `package_lock_timeout` in `config.yaml`
* ~allows users to set `file_lock_timeout` in `config.yaml`~ (update 9/18, this is replaced with two separate configurable timeout parameters)
* (new 9/18) users can configure the whole-database lock timeout using the `db_lock_timout` setting in `config.yaml`
* (updated 9/18) Reduces the …
=> Increase and customize lock timeouts

var/spack/repos/builtin/packages/vtk/package.py
`vtk` currently has a dependency on `mesa+llvm` when the option `+osmesa` is activated.
Since `vtk` can actually be built simply with `mesa`, I suggest removing the dependency on `+llvm` and leave it to the user to chose whether to install with `llvm` support or not. I suggest this in particular because calling `spack install vtk+osmesa ^mesa+llvm` works when the `vtk` package depends on just `mesa`, while calling `spack install vtk+osmesa ^mesa~llvm` does not work when `vtk` depends on `mesa+llvm`.
Additionally right now, `mesa+llvm` doesn't seem to compile on a standard Debian machine.
(Error reported by spack is the following:
```
gallivm/lp_bld_misc.cpp: In function ‘LLVMOpaqueBuilder* lp_create_builder(LLVMContextRef, lp_float_mode)’:
gallivm/lp_bld_misc.cpp:833:13: error: ‘class …
```
=> VTK dependency on "mesa" instead of "mesa+llvm"

var/spack/repos/builtin/packages/hwloc/package.py, var/spack/repos/builtin/packages/libhio/package.py, var/spack/repos/builtin/packages/ucx/package.py
https://github.com/openucx/ucx/releases
==> Successfully installed ucx
Fetch: 1.61s.  Build: 1m 6.61s.  Total: 1m 8.22s.
[+] /scratch/dantopa/spack.current.ccscs4/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/ucx-1.3.1-vsxug5oqz7nnrl5swj4orqosaovq5cvo
dantopa@ccscs4.lanl.gov:spack.current.ccscs4 $ cd var/spack/repos/builtin/packages/ucx/
==> Successfully installed ucx
Fetch: 0.01s.  Build: 1m 7.85s.  Total: 1m 7.86s.
[+] /scratch/users/dantopa/new-spack/spack.arm.hypre/opt/spack/linux-rhel7-aarch64/clang-18.4.1/ucx-1.3.1-aec6oopelqajhialgpwxlikgaaa5ahkq
==> Successfully installed ucx
Fetch: 1.84s.  Build: 1m 26.20s.  Total: 1m 28.04s.
[+] /scratch/users/dantopa/new-spack/spack.arm.hypre/opt/spack/linux-rhel7-aarch64/gcc-8.2.0/ucx-1.3.1-vdt34p5xoj6jhuytj3eievin6hd5fuof
=> Ucx add latest v 1.3.1

var/spack/repos/builtin/packages/paml/package.py
Older versions aren't maintained on the mirror so I had to replace the version.
=> paml: remove broken version, added 4.9h

var/spack/repos/builtin/packages/yaml-cpp/package.py
Change yaml-cpp to conflict with gcc 4.7 instead of 4.8. 4.8 does have a c++11 implementation, and RHEL/Centos 7 still use 4.8.5.
=> Change yaml-cpp compiler conflict

var/spack/repos/builtin/packages/bazel/fix_env_handling-0.13.0.patch, var/spack/repos/builtin/packages/bazel/fix_env_handling-0.17.2.patch, var/spack/repos/builtin/packages/bazel/package.py, var/spack/repos/builtin/packages/bazel/unix_cc_configure-0.17.2.patch
Building bazel yielded errors since commit cd9691de5314fcfaf17d47a63264acef5716c0b6. The first commit fixes the build for older bazel versions, the second commit adds new versions and ports the patches to these versions.
=> Bazel updates

lib/spack/spack/test/module_parsing.py, lib/spack/spack/util/module_cmd.py
Module parsing (to extract package paths from associated module files of Spack external packages) was potentially missing cases where a module named something like `foo-bar/1.0.0` set an environment variable like `FOO_BAR_DIR`, and in that case not finding the package.
This adds some formatting steps when checking the contents of `module show` for a variable set by the module based on the package name.
This is related to https://github.com/spack/spack/issues/9232 but technically this type of parsing would be required for either strategy (in the case of #9232 it's a matter of checking for the right environment variable).
=> Module parsing: improve checking of path variables based on package name

var/spack/repos/builtin/packages/mpich/package.py
patch does not apply to 3.2.1 (released in late 2017).
Given that it fixes the issue discussed in May 2016, most likely
it shall apply only to 3.2
EDIT: apparently I added the patch in https://github.com/spack/spack/pull/5235, probably the way patches are applied changed
=> mpich: fix 3.2 patch

var/spack/repos/builtin/packages/libpfm4/package.py
Add libpfm4 version 4.10.1 (latest).
Set default optimization level (-O2) if not specified in cflags.
=> libpfm4: add version 4.10.1

var/spack/repos/builtin/packages/gmap-gsnap/package.py
fixes an issue introduced by #8087 where builds with no value supplied for the simd variant would fail in the configure phase.
The easiest way to fix it is to add a default value.
=> gmap-gsnap: fixing issue caused by lack of value in simd variant

var/spack/repos/builtin/packages/petsc/package.py, var/spack/repos/builtin/packages/petsc/xlc-test-3.10.1.diff
Adding version 3.10.1 to PETSc's spackage file.
PETSc version 3.9.3 does not build the native test framework correctly, so users will need to build version 3.10.1.
=> Add PETSc 3.10.1 to PETSc's spackage file

var/spack/repos/builtin/packages/gapfiller/package.py
Various GapFiller fixes including:
line endings
/usr/bin/env perl
getopts.pl to Getopt::Std
require the threads perl variant
install into bin.
=> Gapfiller 1.10 f01

var/spack/repos/builtin/packages/lighttpd/package.py
lighttpd was installing to /sbin by default and not getting included in the path.
=> lighttpd: fix bin directory

var/spack/repos/builtin/packages/redundans/package.py
The program refers to both of these at runtime.
=> redundans: add py-numpy dep, snap-berkeley version constraint

var/spack/repos/builtin/packages/p4est/package.py
The version of libsc bundled with p4est will by default always link with '-lgomp' even when the openmp flag is specified. This was fixed in the upstream libsc by two commits which are used to patch.
=> patching p4est to select the proper openmp lib

var/spack/repos/builtin/packages/kokkos/package.py
Essentially, 'variant' does not capture correctly, but '+variant' does, for enabling variants. It was possible to in kokkos e.g. "+serial~openmp" and with kokkos spackage checking for 'serial' and not '+serial', and thus backend would be listed in spack spec but not passed to kokkos configuration. If kokkos is built without a backend choice, it defaults to pthreads - which may be undesirable.
=> kokkos: bugfix for case wherein kokkos backends enabled in spack but not parsed correctly

var/spack/repos/builtin/packages/raxml/package.py
before only one binary was built, this changes the package to build all matching binaries.
unfortunately this breaks parallel builds as well.
=> raxml: build all matching variants

lib/spack/docs/getting_started.rst
Spack may autodetect Linux containers on Cray systems as using the Cray programming environment on the basis of environment variables.
Add documentation to unset the `CRAYPE_VERSION` environment variable when this occurs.
=> Update Spack on Cray docs for singularity platform=linux workaround

var/spack/repos/builtin/packages/py-matplotlib/package.py
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.
=> added py-matplotlib version 3.0.0

var/spack/repos/builtin/packages/abyss/package.py
Configuration option `--enable-maxk` is used to modify the maximum value of `k` parameter which is useful in some cases according to [ABySS documentation](https://github.com/bcgsc/abyss/blob/master/README.md#optimizing-the-parameter-k)
=> Abyss: added variant maxk

var/spack/repos/builtin/packages/candle-benchmarks/package.py
Specifying that Candle-benchmarks requires matplotlib 2.x due to
matplotlib 3.x requiring python 3.x
Candle still seems to have quite a few concretization issues due to how virtual dependencies are handled and further discussion will be required to determine which workarounds are environment specific and which aren't. But the py-matplotlib case is fairly simple
=> Specified Maximum Matplotlib for Candle

var/spack/repos/builtin/packages/py-flake8/package.py
The `py-flake8` package currently has an `enum34` dependency for all versions of Python. However, as the name implies, `enum34` backports the `enum` module from Python 3.4 to Python versions 2.4 through 2.7, and versions 3.1 through 3.3. The presence of the `enum` module in Python 3.4 and later implies that `py-flake8` should not depend on `enum34` for this range of Python versions, so this pull request deletes the `enum34` dependency for Python 3.4 and later.
Furthermore, `spack install py-flake8 ^python@3.7.0` yields the following build error on my system:
```console
==> Executing phase: 'build'
==> '/usr/local/Cellar/python/3.7.0/bin/python3.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute …
```
=> py-flake8 ^python@3.4: :delete enum34 dependency

var/spack/repos/builtin/packages/valgrind/package.py
This allows valgrind to be built with clang 6 on macOS.
=> Valgrind make ubsan and enable64bit variants.

var/spack/repos/builtin/packages/salmon/package.py
Statically linking to libstdc++ will cause the build to fail.
=> salmon: remove static link to libstdc++

var/spack/repos/builtin/packages/vtk/package.py
fixes #9423 
Compilers other than clang don't have the `is_apple` property.
=> Fix: bug in VTK package

var/spack/repos/builtin/packages/catalyst/package.py
The build process of Catalyst requires Python at build time (see line 86) even when the +python variant is not selected.
When the +python variant is selected, Python becomes required at build, link, and run time. There doesn't seem to be any restriction on the version of Python required when +python is not selected.
=> Catalyst Package: made Python mandatory at build time

var/spack/repos/builtin/packages/sspace-standard/package.py
sspace-standard requires a perl with threads
=> sspace-standard: adding threads variant to perl dependency

var/spack/repos/builtin/packages/ant/package.py
Current version wouldn't build with the latest java.
Building javadocs would fail without all of the optional dependencies as well, switched target to `install-lite` which only builds the program.
=> ant: add tested 1.10.0, switch build target

var/spack/repos/builtin/packages/strumpack/package.py
STRUMPACK is a parallel and algebraic linear solver and preconditioner.
It is part of the ECP project "2.3.3.07 STMS08-STRUMPACK/SuperLU: Factorization Based Sparse Solvers and Preconditioners for Exascale".
STRUMPACK can be used from PETSc and MFEM (Trilinos interface is a work in progress).
We plan to update the PETSc and MFEM spack packages once this PR is done.
=> STRUMPACK: new package

var/spack/repos/builtin/packages/candle-benchmarks/package.py
After talks with candle dev, removed unsatisfiable conflict with
candle-benchmark and opencv by disabling gtk in the candle spec
Candle-benchmarks still have issue with multiple providers for virtual dependencies, but that is a larger spack issue
=> Another fix to Candle-benchmark Spec

var/spack/repos/builtin/packages/pythia6/CMakeLists.txt, var/spack/repos/builtin/packages/pythia6/package.py, var/spack/repos/builtin/packages/pythia6/pythia6.patch
This packaging of Pythia6 pulls the pre-split sources from HepForge. With the `+root` variant, two extra source files are pulled from https://root.cern.ch/ to enable compatibility with `root`.
=> New package pythia6, including optional extra code for compatibility with Root.

var/spack/repos/builtin/packages/icu4c/package.py, var/spack/repos/builtin/packages/xerces-c/package.py
xerces-c: Add variant for choice of transcoder (gnuiconv, iconv, icu,
macos, windows).  It's important to specify a --enable-transcoder
option on the configure line or else xerces may make a different
choice when multiple transcoders are available.
Pass the compile flags to configure.  For cflags and cxxflags, this is
necessary to respect the value from the spack install line.
Otherwise, xerces (and any autotools package) will choose a default
value that overrides the spack compiler wrapper.
Add xerces version 3.2.2.
icu4c: Move --enable-rpath to a variant.  This is needed on MacOS, but
it breaks the build for xerces on Linux.
=> xerces-c: add variant for transcoder, rework config flags.

lib/spack/docs/packaging_guide.rst, lib/spack/spack/package.py, lib/spack/spack/pkgkit.py, lib/spack/spack/test/flag_handlers.py, var/spack/repos/builtin/packages/hiop/package.py, var/spack/repos/builtin/packages/ipopt/package.py
Previously to use the pre-defined flag_handler methods, you needed to type `flag_handler = Package.env_flags` or the equivalent.
Now you can type `flag_handler = env_flags`.
As a reminder, the default flag handler is `inject_flags`. It uses the spack compiler wrappers to inject the flags. The other two builtin flag handlers are `env_flags` and `build_system_flags`. The `env_flags` flag handler puts the flags into the canonical environment variables. The `build_system_flags` flag_handler is only available for `AutotoolsPackage` or `CMakePackage` packages and puts the flags onto either the `configure` or `cmake` line, respectively.
=> Make builtin flag handlers available in package scope

var/spack/repos/builtin/packages/sspace-standard/package.py
perl scripts were pointing to /usr/bin/perl, changed to point to the spack installation
=> sspace-standard: add perl-perl4-corelibs dep, fix perl scripts

var/spack/repos/builtin/packages/geant4/package.py, var/spack/repos/builtin/packages/moab/package.py
In order to build the software stack for Exnihilo (part of the ExaSMR ECP project), we need more granularity over the options provided by these two packages.
=> Add important variants to MOAB and Geant4

var/spack/repos/builtin/packages/rdma-core/package.py
Looks like #9255 added the wrong checksum, see:
```console
$ md5sum var/spack/cache/rdma-core/rdma-core-17.1.tar.gz 
1d19caf554f815990af5c21356ac4d3a  var/spack/cache/rdma-core/rdma-core-17.1.tar.gz
$ sha256sum var/spack/cache/rdma-core/rdma-core-17.1.tar.gz 
b47444b7c05d3906deb8771eec3e634984dd83f5e620d5e37d3a83f74f0cc1ba  var/spack/cache/rdma-core/rdma-core-17.1.tar.gz
```
=> rdma-core: Fix checksum for @17.1

var/spack/repos/builtin/packages/bison/package.py, var/spack/repos/builtin/packages/bzip2/package.py, var/spack/repos/builtin/packages/diffutils/package.py, var/spack/repos/builtin/packages/findutils/package.py, var/spack/repos/builtin/packages/help2man/package.py, var/spack/repos/builtin/packages/m4/package.py, var/spack/repos/builtin/packages/mpich/package.py, var/spack/repos/builtin/packages/mvapich2/package.py, var/spack/repos/builtin/packages/openssl/package.py, var/spack/repos/builtin/packages/texinfo/package.py
I just started building my default set of packages in a minimal Fedora 29 container and a few packages failed due to missing dependencies or glibc problems.
I have split up the changes into multiple commits to make them easy to revert if necessary.
=> Fix missing dependencies and glibc build failures

var/spack/repos/builtin/packages/netlib-lapack/ibm-xl.patch, var/spack/repos/builtin/packages/netlib-lapack/package.py
Need to use -O3 -qstrict -qnohot, the combination that allows most tests to run.
Modified ibm-xl.patch and netlib-lapack spackage file.
=> Update compile flags for netlib-lapack when building with the XL compiler.

var/spack/repos/builtin/packages/rdma-core/package.py
The rdma-core code base will use the build path to construct string constants at cmake time (see https://github.com/linux-rdma/rdma-core/blob/master/CMakeLists.txt#L102), which can then trigger the failure of compile time string length safety checks in the code base (see https://github.com/linux-rdma/rdma-core/blob/master/librdmacm/acm.c#L170) if the path is too deep.
This problem is relatively easy to trigger in spack if your staging path is something like "/gpfs/mira-home/carns/working/src/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/rdma-core-20-jseuuuvggown67ufiu74quv64aopa2xp/"
This PR explicitly sets a cmake option to override the rundir and set it to a fixed absolute path (/var/run) so that the rdma-core spack package will build reliably regardless of spack staging path.
=> update rdma-core package to specify rundir

etc/spack/defaults/config.yaml
Default config.yaml mis-named `install_path_scheme` as `directory_layout`.
`install_path_scheme` is properly documented and used in the code.
=> Correct name for install_path_scheme in defaults config.yaml

var/spack/repos/builtin/packages/trilinos/package.py
current stable releases of PETSc and Trilinos have non-overlapping
requirements on Superlu-dist. For now turn it off by default in
Trilinos, which requires older versions. Otherwise, any package which use both will fail to concretize by default.
=> trilinos: disable superlu-dist by default

etc/spack/defaults/packages.yaml, lib/spack/docs/build_settings.rst, lib/spack/llnl/util/filesystem.py, lib/spack/spack/directory_layout.py, lib/spack/spack/hooks/permissions_setters.py, lib/spack/spack/package.py, lib/spack/spack/package_prefs.py, lib/spack/spack/schema/packages.py, lib/spack/spack/stage.py, lib/spack/spack/test/concretize_preferences.py
Added three entries to the packages.yaml schema:
`readable`: Takes a string `user`, `group`, or `world`. This describes the highest level of read permissions for the install directory.
`writable`: Takes a string `user`, `group`, or `world`. This describes the highest level of write permissions for the install directory. Note that having `writable` more permissive than `readable` is an error
`group`: All files in the prefix will be owned by this group.
This allows users to configure user/group/other granularity permissions to their installed packages. It does not allow configuration of executable permissions, as those are handled by the build system appropriately for each file. Executable permissions for files that the build system sets as executable are set to the level of `readable`.
The …
=> Configurable permissions on installed files

lib/spack/spack/cmd/buildcache.py
Fixes https://github.com/spack/spack/issues/9375
@gartung (FYI)
Spack packages installed using `spack buildcache` were not running post-install hooks, which create module files and managing licenses (if necessary).
This was already occurring for Spack packages installed with `spack install --use-cache`
=> buildcache install: add modules

var/spack/repos/builtin/packages/py-spyder/package.py
closes #9205
reordered dependencies to confirm to the ordering in setup.py
=> remove py-setuptools dependency from py-spyder

var/spack/repos/builtin/packages/nalu-wind/package.py, var/spack/repos/builtin/packages/nalu/package.py, var/spack/repos/builtin/packages/trilinos/package.py
This is almost all a workaround for this issue with Trilinos https://github.com/trilinos/Trilinos/issues/2994 . I had to add a `shared` variant to Nalu-Wind so that I could use `sys.platform != 'darwin'` to turn `shared` on or off for Trilinos automatically since Trilinos won't build with STK as a shared library on Darwin anymore.
I also changed a FIXME comment in Trilinos that doesn't need to be fixed in my opinion and `hdf5+hl` is fine as it is.
Also, Nalu-Wind is the official ECP application and not Nalu, so I updated the tags to reflect this.
=> Adding conflict to Trilinos and build Nalu-Wind statically by default on Darwin

lib/spack/spack/build_systems/meson.py
If we do not specify libdir explicitly, Meson chooses something like `lib/x86_64-linux-gnu`, which causes problems when trying to find libraries and pkg-config files.
=> meson: explicitly add --libdir

var/spack/repos/builtin/packages/redundans/package.py
This replaces a hard coded path for sspace-standard with the actual path of the package as installed by spack.
=> redundans bugfix

var/spack/repos/builtin/packages/sspace-standard/package.py
Missed this with my last PR for sspace-standard as I was testing on a box where getopts.pl was installed.
=> sspace-standard: fix to use Getopt::Std instead of getopts.pl

lib/spack/docs/getting_started.rst
To be entirely correct, a compiler from a module should include a
'modules:' field in its entry in the compilers.yaml file.  By default,
spack doesn't add this field automatically, so add a note about adding
it manually.
----------
This is a followup to Issue #9376.  This confused me for a long time
where I thought that --dirty was the only workaround.  So, I thought
that an note about an explicit manual step made sense.
=> docs: add note about compilers with modules

var/spack/repos/builtin/packages/omega-h/package.py
@balay 
1. Remove Gmodel altogether. Omega_h doesn't
actually call Gmodel for anything, it was
more or less just doing additional unit
testing for Gmodel
2. Make Trilinos off by default. Most codes do
not need the ParameterList interface, and
Kokkos through Trilinos is not well explored
in Spack
3. Use modern CMake style to choose the zlib
dependency
=> omega-h: fix dependencies

var/spack/repos/builtin/packages/lz4/package.py, var/spack/repos/builtin/packages/mesa/package.py, var/spack/repos/builtin/packages/vtk/package.py, var/spack/repos/builtin/packages/vtk/python3.7-const-char.patch
This PR adds `xdmf` readers and writers to vtk together with `mpi` and `ffmpeg`.
Also fixed minor bugs in `lz4`, that had a wrong `LIBS` variable ovveride in the makefile, `mesa` missing argparse at least on `python@3.7.0`
=> vtk: enhance with Xdmf IO.

var/spack/repos/builtin/packages/pumi/package.py
This PR documents why the spack version string 'develop' is used with the scorec/core master branch.  Discussion on this topic is here: https://github.com/SCOREC/core/issues/188#issuecomment-430299432
=> add pumi version docstring

var/spack/repos/builtin/packages/freetype/package.py
I have not rebuilt all dependents but at least fontconfig and poppler seem to build fine.
=> freetype: Add 2.9.1

var/spack/repos/builtin/packages/spark/package.py
Fixes #9437
Sets the `JAVA_HOME` in the `hadoop` subprocess called during
`spark.setup_environment`.
=> Fix for issue #9437 spark+hadoop

etc/spack/defaults/config.yaml, lib/spack/spack/build_environment.py, lib/spack/spack/schema/config.py
While debugging a rdma-core build failure, I noticed that Spack did not show the errors in the build log. This is because my system is set to German and the log parser does not find any "error" occurrences in the log.
=> Remove language-related variables from build environment

var/spack/repos/builtin/packages/r-rmarkdown/package.py
#9453 added this to the wrong package -- it it required by this one although not mentioned in the dependencies for some reason.
=> r-rmarkdown: add r-catools dependency

var/spack/repos/builtin/packages/samrai/package.py
I know it seems a bit unusual to add a patch supporting this ancient version of SAMRAI (released in 2008) but we need it for a project here at UNC (www.github.com/ibamr/ibamr). This version of SAMRAI has a bunch of (easy to fix) ADL problems and some performance issues; the provided patch addresses both.
=> Update samrai 2.4.4

var/spack/repos/builtin/packages/qt/package.py, var/spack/repos/builtin/packages/qt/qt4-gcc-and-webkit.patch
It seems that Qt's webkit option would not build with earlier gcc versions, so the Qt configure script had some specific exclusions. However, it was not up to date with recent gcc releases. This patch adds gcc 5, 6, 7 and 8 to those assumed to build webkit. I confess I have only tested this on gcc-7, on Linux SLES-12. 
There is also a specific case for hpux/gcc, and I have added the same extra version numbers there, too, totally untested.
=> qt4: Patch configure to allow webkit with recent gcc

var/spack/repos/builtin/packages/blaze/package.py
Add two new version lines, along with sha256 hashes.
=> Update blaze package with new releases 3.3 and 3.4

var/spack/repos/builtin/packages/guile/package.py, var/spack/repos/builtin/packages/libmatheval/package.py, var/spack/repos/builtin/packages/plumed/package.py
* one of the "default on" plugins of plumed has optional libmatheval support
* added missing flex dependency to libmatheval for it to work for plumed
* fix guile build with intel compiler
=> plumed: libmatheval support (and dependencies fixes)

var/spack/repos/builtin/packages/pmix/package.py
VERIFICATION:
$ uname -a
Darwin pn1249300.lanl.gov 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
$ echo $HOSTNAME
Cauchy.Schwarz
$ sysctl -n machdep.cpu.brand_string
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
$ system_profiler | grep Processor
Processor Name: 12-Core Intel Xeon E5
Processor Speed: 2.7 GHz
+++   +++   +++   +++   +++   +++
==> Successfully installed pmix
[+] /Volumes/Tlaltecuhtli/spack/spack.macpro.openmpi/opt/spack/darwin-sierra-x86_64/gcc-8.2.0/pmix-3.0.2-gm3kbt7kryd5o4aey23calasquc2b4fr
==> Successfully installed pmix
[+] /Volumes/Tlaltecuhtli/spack/spack.macpro.openmpi/opt/spack/darwin-sierra-x86_64/gcc-8.2.0/pmix-3.0.1-kgau46xsnavggzjwwzvjkrii3qk2g5uc
==> Successfully installed pmix
[+] …
=> Switch from md5 to sha256 checksums for most recent PMIX versions

var/spack/repos/builtin/packages/atk/package.py
@lee218llnl @JSquar 
py-gtk needs to build with python@2.7 and also requires atk, so the atk python dependency cannot be unconditionally constrained to @3:
This PR generally undoes the edits of https://github.com/spack/spack/pull/9102 (although it keeps the `gettext` dependency). Therefore, to build newer versions of `atk`, you must specify their version on the command line, e.g. `spack install atk@2.28.1`. More on this at https://github.com/spack/spack/issues/8133#issuecomment-389378055
And this now also allows `spack install py-pygtk to succeed`.
See: https://github.com/spack/spack/pull/9102#issuecomment-431514107
=> atk: remove unconditional python@3: constraint

var/spack/repos/builtin/packages/strumpack/package.py
- add new version 3.1.0
- add conflict for parmetis without mpi
- strumpack >= 3.1.0 uses -DTPL_ENABLE_<package> instead of
-DSTRUMPACK_USE_<package>
- require cmake at least 3.2
=> STRUMPACK: update version to 3.1.0

lib/spack/spack/cmd/license.py
- previously, if you built the docs, you'd get license errors for generated .rst files.
- this removes them from the list of licensed files.
=> license: exclude ignored files from the license check

lib/spack/spack/util/module_cmd.py
introduced in #9100
Correctly process PATHs of type "path1:path2"
Fixes the following incorrect warning on cori @ nersc
```
balay@cori10:~/spack.x> spack env m4 >/dev/null
==> Warning: Extracted path from module does not exist:
Extracted path: /opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64
Full line: prepend-path  LD_LIBRARY_PATH /opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 
balay@cori10:~/spack.x> ls -d  /opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64
/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64
balay@cori10:~/spack.x> ls -d …
```
=> Bug fix: Module PATH check

lib/spack/spack/cmd/buildcache.py
Typo in `buildcache install` command line.
=> Fix typo in help message

var/spack/repos/builtin/packages/nalu-wind/package.py, var/spack/repos/builtin/packages/nalu/package.py, var/spack/repos/builtin/packages/openfast/package.py, var/spack/repos/builtin/packages/tioga/package.py
This is a bit of an addendum to https://github.com/spack/spack/pull/9522 . I originally created all these packages in this PR. I realized some of the optional libraries for Nalu-Wind like Tioga and OpenFAST were still set to build static libraries (Nalu had a previous requirement of all static libraries). So I am defaulting them to shared now, and I also added `pic` variants in case the shared/static mix happens somehow, so then it doesn't fail with "relocatable" errors telling the user to use `-fPIC` if some library winds up static.
=> Add pic variants to tioga, openfast, nalu-wind, and nalu

lib/spack/llnl/util/filesystem.py
- #8773 made the default mode 0o777, which is what's documented, but mkdirp actually takes the OS default or umask by default
- This was resulting in directories being created with 777 permissions in a lot of places where they should not be.
=> bugfix: use OS default permissions for mkdirp when mode is not provided

var/spack/repos/builtin/packages/visit/package.py
This PR updates the VisIt package with the following additions:
- HDF5 is now an option that can be disabled
- SILO is now an option that can be disabled
- Python is now an option that can be disabled
- GUI is now an option that can be disabled
- Can enable "parallel" to compile the parallel engine
This allows to better select the needed dependencies and in particular to compile just the engine by disabling the gui, hdf5, and silo variants. This is useful when one wants to compile just the libsim in situ visualization interface (i.e. just the engine).
=> Package VisIt: updated visit package

.flake8, .flake8_packages
It seems they are activated by default since since flake8 3.6.0, and they already caused a few packages to fail CI (see #9622).
=> Ignore flake8 W503 and W504 

var/spack/repos/builtin/packages/r-argparse/package.py
no checksum for r-getopt@1.19 and this package is compatible with the latest version anyway
=> r-argparse: remove unnecessary r-getopt version

var/spack/repos/builtin/packages/nccl/package.py
There is not install target in the top-level Makefile in this version, it moved to src/Makefile.
=> package nccl: Fix install_targets for verison 2.3.5-5:

var/spack/repos/builtin/packages/r-goplot/package.py
r-rcolorbrewer version should have a dash at the end instead of a dot -- this would break the fetch process.
=> r-goplot: fix r-rcolorbrewer version format

var/spack/repos/builtin/packages/catalyst/package.py
The Catalyst developers will make the source available in .tar.xz format from now on (starting from the next release, version 5.6). 5.6-RC1 and 5.6RC2 are already available in .tar.xz.
This PR updates the `url_for_version` function to reflect this.
=> updated URL format for Catalyst package when version is >= 5.6

var/spack/repos/builtin/packages/nag/package.py
MD5 checksums verified by downloading installer over HTTPS:
```
$ curl -sL https://www.nag.com/downloads/impl/npl6a61na_amd64.tgz | md5sum 
9b3cc0f8703c79f6231ae12359535119  -
$ curl -sL https://www.nag.com/downloads/impl/npl6a62na_amd64.tgz | md5sum 
8b119cc3296969bbd68b781f625de272  -
```
=> nag: fix NAG Fortran Compiler MD5 checksum for 6.1; add 6.2 checksum

var/spack/repos/builtin/packages/miniconda2/package.py, var/spack/repos/builtin/packages/miniconda3/package.py
The install() function in the miniconda2 & 3 package.py files referenced
self.url, which is hard-coded to 4.3.11.  That's not necessarily the
version that the user requested, though.  Changed the install() function
to reference self.stage.archive_file.  Also added a version string for
4.5.11.
=> Fix issue with miniconda attempting to install the incorrect version

LICENSE-MIT, README.md
- Add copyright to MIT license so that the "above copyright statement" wording is correct.
- Add SPDX identifier to top-level README.md file.
- Remove analytics beacon in README, which is not that useful anymore (the site is over quota, we should use something real if we want to do this)
=> license: add copyright to MIT license and SPDX in README

var/spack/repos/builtin/packages/fmt/package.py
Update versions and constraints on `cmake` and supported toolchains (as stated by the documentation).
=> fmt: add new versions and update constraints

var/spack/repos/builtin/packages/visit/package.py
PR https://github.com/spack/spack/pull/9494 added a `+mpi` variant to VTK which conflicts with the VisIt package. This PR makes VisIt explicitly request VTK with `~mpi`.
=> Fixing VTK dependency in VisIt package

.travis.yml
- Docker builds are failing on `develop`
- They're not critical for the build to succeed, so allow them to fail until we fix the build
@opadron
=> docker: allow docker build to fail until it's fixed

lib/spack/spack/util/spack_yaml.py
This builds on #8081.
- it was hard to distinguish all-gray filenames
- added rotating colors to `spack config blame`
=> config: `spack config blame` now colors filenames in config output

share/spack/setup-env.sh
`ps` from the `procps` package can be instructed to use a different default output format via the `PS_FORMAT` env variable. Thus unset this variable before calling `ps`.
=> Avoid different output format of `ps`

var/spack/repos/builtin/packages/libmesh/package.py
This commit overhauls the libMesh package script in a number of ways:
1. We now inherit from AutotoolsPackage.
2. libMesh contains about a dozen third-party dependencies that can only be provided by the copy bundled with libMesh. This patch enumerates all such bundled dependencies and disables all of them by default.
3. libMesh supports compilation with external installations of boost, eigen, hdf5, slepc, and tbb; this patch adds all of them to package.py.
4. libMesh will look for a few system executables (xz, bzip, gdb) by default. This is now disabled.
5. libMesh will now used a copy of perl installed by spack instead of trying to find the system copy.
6. Compilation with non-system MPI installations requires an additional flag (--with-mpi=); this has been added.
I am still not sure …
=> Expand the libMesh dependency list.

var/spack/repos/builtin/packages/hoomd-blue/package.py
newer cmake versions cause the build to fail. Also changing install
prefix for cmake to follow the path structure that python expects.
=> hoomd-blue: fixing issue during build with newer cmakes

var/spack/repos/builtin/packages/py-llvmlite/package.py
Change dependency on llvm from >=6.0 to 6.0:6.99.
Refs #9667
=> Update dependencies for py-llvmlite

lib/spack/spack/compilers/clang.py
- Previously clang used a heuristic here based on the architecture to figure out what the preferred mixed fortran compiler was
- This was wrong in, among other places, Linux with clang/gfortran
- new logic looks at the actual name we got from compilers.yaml to pick the best wrapper name based on the mixed compiler name.
- this still isn't perfect but it's a lot better, and it will hopefully last us until compilers are actual dependencies
Previous discussion in #5503
FYI: @junghans @davydden
=> bugfix: set clang compiler symlink name based on compilers.yaml

var/spack/repos/builtin/packages/doxygen/package.py, var/spack/repos/builtin/packages/doxygen/shared_ptr.patch
+ Also provide a patch that allows collaboration diagrams to work properly with
C++ std::shared_ptr<T>. Ref:
https://github.com/Sleepyowl/doxygen/commit/6c380ba91ae41c6d5c409a5163119318932ae2a3?diff=unified
=> Provide a newer doxygen version.

var/spack/repos/builtin/packages/ecp-proxy-apps/package.py
=> ecp-proxy-apps: disable building CANDLE Benchmarks by default

lib/spack/spack/build_environment.py
```
==> '/Users/balay/spack.x/lib/spack/env/gcc/gcc' '-dynamiclib' '-install_name /Users/balay/spack.x/opt/spack/darwin-mojave-x86_64/gcc-8.2.0/lua-5.3.4-2vmbxjspno7oax3fmnxhohptbnxmfa4y/lib/liblua.dylib.5.3' '-Wl,\
-force_load,/Users/balay/spack.x/opt/spack/darwin-mojave-x86_64/gcc-8.2.0/lua-5.3.4-2vmbxjspno7oax3fmnxhohptbnxmfa4y/lib/liblua.a' '-compatibility_version 5.3' '-current_version 5.3.4' '-lm' '-o' '/Users/balay/\
spack.x/opt/spack/darwin-mojave-x86_64/gcc-8.2.0/lua-5.3.4-2vmbxjspno7oax3fmnxhohptbnxmfa4y/lib/liblua.dylib.5.3.4'
gcc-8: error: unrecognized command line option '-install_name /Users/balay/spack.x/opt/spack/darwin-mojave-x86_64/gcc-8.2.0/lua-5.3.4-2vmbxjspno7oax3fmnxhohptbnxmfa4y/lib/liblua.dylib.5.3'
gcc-8: error: unrecognized command line option …
```
=> static_to_shared_library: breaks with lua build on osx with brew/gcc

lib/spack/spack/spec.py
This allows installing software on a namespace basis by including
${NAMESPACE} in `install_path_scheme`. e.g.,
```
cat ~/.spack/config.yaml
config:
install_path_scheme:
"${ARCHITECTURE}/${NAMESPACE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"
```
=> Parse the ${NAMESPACE} format string in a spec's format method.

lib/spack/spack/compilers/arm.py
This new arm.py compiler file identifies the arm hpc compiler to be used on aarch64.  Followup pull requests will exercise autodetection for arm hpc compilers on aarch64 as is done for gcc. 
The main author of this file is Nick Forrington <Nick.Forrington@arm.com> and minor edits and legalese settlement by Srinath Vadlamani <srinath.vadlamani@arm.com>.
=> Arm Compiler

var/spack/repos/builtin/packages/homer/package.py
'+data' variant uses the provided script to install all of the provided data sets (~30gb extra)
=> homer: new package starting at 4.9.1

var/spack/repos/builtin/packages/openmpi/btl_vader.patch, var/spack/repos/builtin/packages/openmpi/package.py
Vader bug causes some MPI codes to sporadically segfault.
=> Added OpenMPI 3.1.3 and a patch

lib/spack/spack/util/web.py
fixes #9739
The non-daemonic pool relies heavily on implementation details of the multiprocessing package. In this commit we provide an implementation that fits recent python versions.
=> Adapted the code of the non-daemonic pool to recent python versions

bin/spack
fixes #9619
fixes #9206
closes #9702 (alternative solution to the same issue)
closes #9261 (alternative solution to the same issue)
`ruamel.yaml` generates a `.pth` file when installed via pip that has the effect of always preferring the version of this package installed at site scope (effectively preventing us from vendoring it).
This mechanism triggers when implicitly importing the `site` module when the python interpreter is started. In this PR we explicitly delete references to `ruamel.yaml` and `ruamel` in `sys.modules`, if any, after we set `sys.path` to search from the directory where we store vendored packages. This ensures that the imports after those statements will be done from our vendored version.
=> Delete references to ruamel.yaml at Spack start-up, if they are present

lib/spack/spack/cmd/install.py, lib/spack/spack/report.py, lib/spack/spack/reporters/cdash.py, lib/spack/spack/test/cmd/install.py
Update the CDash reporter to generate results when nothing goes wrong.  Previously it would only generate and upload a report when errors occured during `spack install`.
=> Report clean results to CDash

lib/spack/spack/binary_distribution.py
@scottwittenburg @gartung 
@becker33 this will fix some broken symlinks for bzip2, for example. However, it may not be essential, as from what I can tell most packages don't use the extra symlinks (e.g. `bzegrep`) that are broken.
Binary caches of packages with absolute symlinks had broken symlinks. From what I can tell, tar doesn't support any notion of matching source/destination roots when unpacking an archive with absolute symlinks. Therefore, this commit just makes a copy of any file that is a symlink while creating a binary cache of a package.
=> Binary caching: remove symlinks, copy files instead

lib/spack/docs/tutorial_advanced_packaging.rst, var/spack/repos/tutorial/packages/armadillo/package.py, var/spack/repos/tutorial/packages/armadillo/undef_linux.patch, var/spack/repos/tutorial/packages/elpa/package.py, var/spack/repos/tutorial/packages/hdf5/h5f90global-mult-obj-same-equivalence-same-common-block.patch, var/spack/repos/tutorial/packages/hdf5/package.py, var/spack/repos/tutorial/packages/hdf5/pre-c99-comments.patch, var/spack/repos/tutorial/packages/mpich/mpich32_clang.patch, var/spack/repos/tutorial/packages/mpich/package.py, var/spack/repos/tutorial/packages/netlib-lapack/ibm-xl.patch, var/spack/repos/tutorial/packages/netlib-lapack/package.py, var/spack/repos/tutorial/packages/netlib-lapack/testing.patch, var/spack/repos/tutorial/packages/netlib-lapack/undefined_declarations.patch, var/spack/repos/tutorial/repo.yaml
@becker33 
This creates a new repository for package installations which are used in https://spack.readthedocs.io/en/latest/tutorial_advanced_packaging.html. It is placed alongside builtin, and disabled by default (you must do `spack repo add --scope=defaults var/spack/repos/tutorial` to enable it).
Thoughts so far on this approach:
* I haven't checked this with the intended docker image (Ubuntu 18.04) but I have completed the advanced packaging tutorial with this on a different system (I intend to test with the target OS by the end of 11/5)
* users will want to do this in a separate Spack repo clone if they aren't using the tutorial docker image, and will also want to be careful when adding the repo (the updated docs suggest using `--scope=defaults` to avoid modifying config under `~`). …
=> New repo for advanced packaging tutorial

var/spack/repos/builtin/packages/sra-toolkit/package.py
* files under `bin` were copied 3 times instead of symlink'ed
* sha256 checksums
* new release 2.9.2 of July 24, 2018
=> sra-toolkit: improvements and new version

lib/spack/spack/binary_distribution.py, lib/spack/spack/cmd/install.py, lib/spack/spack/package.py, lib/spack/spack/test/packaging.py
Turns on binary cache installs by default.
Binary caches can be ignored using the `--no-cache` option to `spack install`.
Binary packaging test also updated to not pollute the test environment with cached available specs for binary packages.
=> Update `spack install` to use cache by default

.travis.yml
- Python 2.6 tests are currently failing due to some issue in Travis that we haven't been able to diagnose.
- They run fine locally and when logging into a Travis session, just not in actual Travis
- Allow them to fail until we can fix this in Travis
=> travis: allow Python 2.6 to fail until we figure out why Travis hangs

var/spack/repos/builtin/packages/cbtf-krell/package.py, var/spack/repos/builtin/packages/dyninst/package.py, var/spack/repos/builtin/packages/intel-tbb/package.py, var/spack/repos/builtin/packages/openspeedshop-utils/package.py, var/spack/repos/builtin/packages/openspeedshop/package.py
Dyninst master and the soon to be released
version requires the tbb package.  This mod
updates the tbb versions adding the one that
dyninst uses and adds the required spack package
changes to dyninst/package.py.
=> Update Dyninst package file for TBB dependency

lib/spack/spack/cmd/install.py
- default is still to use the cache, but we've added back the `--use-cache` argument so that scripts that used it are still correct.
- `--no-cache` is stil present and is mutually exclusive with `--use-cache`
=> install: add --use-cache back so that existing tooling does not break

lib/spack/docs/configuration.rst, lib/spack/spack/main.py
I think the only controversial change here is a change in how our configuration scopes are presented. Previously, we listed the custom scope added via `--config-scope` as "command line" scope. However, there is actually a higher precedence scope of build settings listed on the command line. I separated "command line" into "custom" and "command line" to distinguish this. Let me know how people feel about this change before I make the same change to the Configuration Tutorial.
=> Updates to Configuration Files docs for SC18

lib/spack/spack/cmd/install.py
- forgot to set a default when restoring `--use-cache`.
- this adds the default back and makes it consistent between `--use-cache` and `--no-cache`.
=> bugfix: --use-cache option had incorrect default settings

lib/spack/spack/cmd/config.py, lib/spack/spack/cmd/find.py, lib/spack/spack/cmd/install.py, lib/spack/spack/cmd/uninstall.py, lib/spack/spack/environment.py, lib/spack/spack/test/cmd/config.py, lib/spack/spack/test/config.py, lib/spack/spack/test/conftest.py
- This is not garbage collection (yet) but close.
=> Some small improvements for Spack environments

lib/spack/docs/tutorial_advanced_packaging.rst
Update all examples that need an MPI provider to build with MPICH; reorganize so that fixing MPICH (as part of environment section) comes first in the tutorial (most examples in the tutorial use an MPI provider).
=> Advanced packaging tutorial: reorganize for binary caches

lib/spack/docs/build_settings.rst
Just some minor grammar changes, typos, and mvapich -> mvapich2.
=> Minor changes to Build Customization docs for SC18

lib/spack/docs/tutorial_buildsystems.rst
Found a minor typo in the Build Systems Tutorial.
=> Fix typo in Build Systems Tutorial

var/spack/repos/builtin/packages/r-callr/package.py
found while installing trinity/trinotate
=> r-callr: adding new dependencies

var/spack/repos/builtin/packages/migrate/package.py
spack's filter_file only works line-by-line and this requires a multiline replacement, so i loaded the file in as a string and performed a normal substring replacement
=> migrate: new package starting at 3.6.11

var/spack/repos/builtin/packages/ilmbase/package.py, var/spack/repos/builtin/packages/openexr/package.py
Bump openexr version to 2.3.0 and fix #7274 where compilation can fail due to missing zlib.
=> Add new version for ilmbase and openexr, add zlib dependency to openexr

var/spack/repos/builtin/packages/gplates/package.py
- Add version 2.1.0
- Now that #9264 has been merged, gplates seems to build fine with newer versions of gcc (tested with gcc@8)
- When using the ninja generator, gplates can be built in parallel
=> Improve and update gplates

var/spack/repos/builtin/packages/thrift/package.py
Without pkgconfig, Spack's openssl cannot be found.
=> thrift: add missing pkgconfig dependency

var/spack/repos/builtin/packages/ruby/package.py
Required for openssl@1.1 compatibility.
=> ruby: add 2.5.3

var/spack/repos/builtin/packages/openssh/package.py
Required for openssl@1.1 compatibility.
=> openssh: add 7.9p1

var/spack/repos/builtin/packages/libevent/package.py
2.1.8 is required for openssl@1.1 compatibility.
=> libevent: add 2.1.8 and 2.0.22

var/spack/repos/builtin/packages/libssh/package.py
Required for openssl@1.1 compatibility.
=> libssh: fix fetching and add 0.8.5

var/spack/repos/builtin/packages/wt/package.py
wt does not build with newer versions of boost.
=> wt: add missing pkgconfig dependency and fix boost version range

var/spack/repos/builtin/packages/hypre/package.py
This pull request amends the version range from `@2.14.0:` to `@2.14.0` for the second patch that enables building `hypre` on `darwin` as a shared library because the changes in that patch were incorporated into version 2.15.0.
=> hypre: patch only @2.13.0 and @2.14.0 on darwin

var/spack/repos/builtin/packages/glib/package.py
glib should not use the globally installed gtk-doc. Otherwise, gtk-doc can fail with Python errors such as `ImportError: No module named site`.
This is due to the fact that Spack sets `PYTHONHOME`, which can confuse the global Python installation that is used by gtk-doc.
Fixes #9769
Fixes #9719
=> glib: explicitly disable gtk-doc

var/spack/repos/builtin/packages/eospac/package.py
This PR makes eospac version 6.4.0beta.3 available to install.  Flake8 checks were clean.
=> eospac version bump

var/spack/repos/builtin/packages/boost/package.py
While installing a package depending on the boost library, I've got the following error:
```
24046    /usr/bin/ld: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/boost-1.68.0-xkyf5icz7yn62yjvduwrs3mfru4merj4/lib/libboost_serialization-mt.a(archive_exception.o): re
location R_X86_64_32S against symbol `_ZTVN5boost7archive17archive_exceptionE' can not be used when making a shared object; recompile with -fPIC
24047    /usr/bin/ld: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/boost-1.68.0-xkyf5icz7yn62yjvduwrs3mfru4merj4/lib/libboost_serialization-mt.a(basic_archive.o): reloca
tion R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
24048    /usr/bin/ld: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/bo …
```
=> Add pic variant to cflags in boost.

var/spack/repos/builtin/packages/perl-net-ssleay/package.py
- Add 1.85
- OPENSSL_PREFIX has to be set in the environment, otherwise Spack's openssl will not be found
=> perl-net-ssleay: fix build

var/spack/repos/builtin/packages/node-js/package.py
Required for openssl@1.1 compatibility.
=> node-js: add 10.13.0 and 11.1.0

var/spack/repos/builtin/packages/netcdf-fortran/package.py
We need to specify `LDFLAGS` to get correct `dependency_libs` in `libnetcdff.la`, so packages that use `libtool` for linking could correctly link to all the dependencies even when the building takes place outside of Spack environment, i.e. without Spack's compiler wrappers.
=> netcdf-fortran: add LDFLAGS to fix contents of libnetcdff.la.

var/spack/repos/builtin/packages/libunwind/package.py
Libunwind releases are few and far between, so we need access to
recent snapshots from the git repository.
Pass cflags to configure so that make will respect the value from the
spack install line.
=> libunwind: add version for current snapshot

var/spack/repos/builtin/packages/elfutils/package.py
Pass cflags to configure so that configure gets the values from the
spack install line.
Disable -Werror so that we don't fail the build over a stray warning.
=> elfutils: add version 0.174.

var/spack/repos/builtin/packages/openblas/package.py
These commits add the `blas_libs`, `lapack_libs`, and `headers` properties to `openblas`.
I was running into some issues configuring `hypre`, and one of the errors I encountered was that `hypre`'s `configure` script could not find `lapack`. Adding the `lapack_libs` method fixed the error, and I added the `blas_libs` and `headers` methods for consistency with `netlib-lapack`.
=> openblas: add `headers` property

var/spack/repos/builtin/packages/py-ply/package.py
Update download URL per #9507.  This primary URL hosts current and all old releases, with only select releases available on Github.
=> py-ply: fix download url

var/spack/repos/builtin/packages/ecflow/package.py
Hi,
I wrote a package script for ecFlow, a work flow manager: https://confluence.ecmwf.int/display/ECFLOW/.
The package requires boost being built with `+pic` (#9750), because it links some its libraries to boost static libraries.
I've opened an issue on the upstream platform: https://jira.ecmwf.int/projects/SUP/issues/SUP-2641
=> New package: ecFlow, a work flow manager.

var/spack/repos/builtin/packages/libmongoc/package.py
Added support for newer 1.9.* versions. 
A change in configure arguments was needed: from `--with-libbson=system` to `--with-libbson=auto`
=> libmongoc: updated versions

var/spack/repos/builtin/packages/ucx/package.py
```
dantopa@darwin-fe2.lanl.gov:pr.ucx.spack $ spack install ucx % gcc @ 4.8.5
==> Installing libsigsegv
==> Installing m4
==> Installing pkgconf
==> Installing ncurses
==> Installing readline
==> Installing gdbm
==> Installing perl
==> Installing autoconf
==> Installing automake
==> Installing libtool
==> Installing numactl
==> Installing zlib
==> Installing openssl
==> Installing diffutils
==> Installing bzip2
==> Installing xz
==> Installing libxml2
==> Installing tar
==> Installing gettext
==> Installing help2man
==> Installing bison
==> Installing flex
==> Installing libnl
==> Installing rdma-core
==> Installing ucx
==> Successfully installed ucx
Fetch: 1.17s.  Build: 40.59s.  Total: 41.76s.
[+] /scratch/users/dantopa/new-spack/pr.ucx.spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/ucx …
```
=> Add UCX v1.4.0

var/spack/repos/builtin/packages/intel-parallel-studio/package.py
So I don't have all the download links for all the other 2019.1 composer, and professional editions, etc, and I don't know how to get them, so those will have to come in another PR from someone who has them, but I'm anxious to get this one in.
Edit: If someone has the links, I will gladly add them in.
=> Adding intel-parallel-studio cluster 2019.1 version

var/spack/repos/builtin/packages/h5z-zfp/package.py
H5Z-ZFP uses non-empty ``FC`` variable to decide whether to build its fortran interface. If ``FC`` is defined in environment, then it will have the effect of causing H5Z-ZFP to build its fortran interface even if, for example, the dependent HDF5 library was not built with its fortran features enabled (which are required by H5Z-ZFP's fortran interface). By explicitly setting ``FC`` to empty on the H5Z-ZFP make command-line, we effectively disable building of its fortran interface.
=> Explicitly set FC= empty for non-fortran builds

var/spack/repos/builtin/packages/gtkplus/package.py
This PR takes care of #9894 for package gtkplus.
=> package/gtkplus: disable gtk-docs

var/spack/repos/builtin/packages/r-crosstalk/package.py
confirmed this installed fine under r 3.5, and I don't see any mention of a 3.4 constraint in the docs
=> r-crosstalk: remove unnecessary constraint

var/spack/repos/builtin/packages/openmpi/package.py
I just tested 4.0.0 to get the libmpi.so version and it seems to build and install fine.
=> Adding openmpi version 4.0.0

var/spack/repos/builtin/packages/gdk-pixbuf/package.py
disable docs by default.
resolves #9879 which prevents building of dependencies of packages like opencv
Recently gtk-docs were also disabled at #9771 for glib package.
=> gdk-pixbuf: explicitly disable building of gtk-docs

var/spack/repos/builtin/packages/openssl/package.py
As discussed in #9755, this is a separate PR to make openssl@1.1.1 the default version. I have rebuilt all (direct) openssl dependents and filed PRs to update them if necessary.
It depends on the following PRs: #9755, #9777, #9779, #9781, #9782, #9785, #9793
=> openssl: make 1.1.1 the default version

var/spack/repos/builtin/packages/intel-daal/package.py, var/spack/repos/builtin/packages/intel-ipp/package.py, var/spack/repos/builtin/packages/intel-mkl/package.py, var/spack/repos/builtin/packages/intel-mpi/package.py, var/spack/repos/builtin/packages/intel-tbb/package.py
Sorry for making two pull requests regarding Intel version updates, but I just found out how to get the download links for the free performance libraries. I still don't know how to get all the compiler links without being a paid and registered user though.
=> Add 2019.1 and 2018.4 version of the Intel performance libraries.

var/spack/repos/builtin/packages/dyninst/package.py, var/spack/repos/builtin/packages/elfutils/package.py
Drop versions 8.1.x.  These were > 5 years old, no other spack package
uses them, and they used autotools.  Packages 'stat' and 'mitos' still
use 8.2.1, so we keep that.
Switch class Dyninst to CMakePackage.
Clean up how the versions depend on various packages.  For example,
Dyninst used libelf up to 9.2, and then elfutils starting with 9.3.
This makes things easier going forward.
Add variant 'openmp' (default True) to enable openmp support for
ParseAPI.  This was added in 10.0.0.
Add variant 'static' (default False) to also build static libraries.
This goes back to 9.1.0.
Disable cotire for the 9.3.x versions.  Cotire has no real use in a
one-time build and can break parallel builds with both static and
shared libs.
@mplegendre  @bwelton  @jgalarowicz  @mxz297  comments?
=> dyninst: overhaul package.py to CMakePackage

var/spack/repos/builtin/packages/flecsale/package.py
Found these problems with flecsale while running builds for the openssl update.
=> flecsale: add missing dependencies and fix flecsi runtime model

var/spack/repos/builtin/packages/py-psycopg2/package.py
I note that there is an old PR https://github.com/spack/spack/pull/7728 for this package, bundled in with a server-less subset of postgresql. That seems to have stalled, with a lot of complexity. This PR is simpler, and depends on the full postgresql package, even though the same arguments could apply. 
I also note that I have recently put in a PR https://github.com/spack/spack/pull/9922, which is a different package for a similar Python PostgreSQL client. Other (currently non-spack) software require one or other of them, so it seemed easiest to keep them independent.
=> py-psycopg2: new package

var/spack/repos/builtin/packages/cantera/package.py, var/spack/repos/builtin/packages/py-configparser/package.py, var/spack/repos/builtin/packages/py-enum34/package.py, var/spack/repos/builtin/packages/py-flake8/package.py, var/spack/repos/builtin/packages/py-future/package.py, var/spack/repos/builtin/packages/py-ipython/package.py, var/spack/repos/builtin/packages/py-jsonschema/package.py, var/spack/repos/builtin/packages/py-pybtex/package.py, var/spack/repos/builtin/packages/py-rasterio/package.py, var/spack/repos/builtin/packages/py-singledispatch/package.py, var/spack/repos/builtin/packages/py-slurm-pipeline/package.py, var/spack/repos/builtin/packages/py-sphinx/package.py, var/spack/repos/builtin/packages/py-tornado/package.py, var/spack/repos/builtin/packages/py-traitlets/package.py
#2793 appears to no longer be present, so uncommenting these dependencies.
=> Uncomment dependencies previously disallowed by concretizer

var/spack/repos/builtin/packages/openmpi/package.py
The latest OpenMPI release, v4.0.0, does not build with many GCC/GFortran variants. Since `+mpi` and `+fortran` are our defaults, a lot of users get hit.
Let's wait for some point releases. cc @jrood-nrel 
References:
- #9888
- #9917
- https://github.com/open-mpi/ompi/issues/6105
- https://github.com/open-mpi/ompi/issues/6106
=> OpenMPI: Prefer Last 3.X

var/spack/repos/builtin/packages/lammps/package.py, var/spack/repos/builtin/packages/latte/package.py, var/spack/repos/builtin/packages/voropp/package.py
When trying to build `lammps`, `latte` had what I assume to be an incorrect checksum, and `voropp` needs to be built with `-fPIC`.
I hate to just update a checksum without verifying it. It looks like @junghans created the md5sum before this.
=> Fixing problems with lammps dependencies voropp and latte

lib/spack/spack/spec.py
As I'm starting to identify cleanups required to merge #8718, I noticed that this is the last remaining difference between the `spec.py` in that branch and the one in develop.  I thought it might be low-hanging fruit, mergeable without too much contention.
=> Expose option to save all dependencies when writing spec.yaml

var/spack/repos/builtin/packages/glib/package.py
This can cause build warnings like this:
```
/usr/bin/ld: warning: libpcre.so.3, needed by /usr/lib/x86_64-linux-gnu/libselinux.so, may conflict with libpcre.so.1
```
Additionally, if SELinux is found, this causes `-lselinux` to be included in glib's pkg-config file, which may lead to build failures on nodes where it is not installed globally.
=> glib: disable SELinux explicitly

lib/spack/spack/concretize.py, lib/spack/spack/test/concretize.py, lib/spack/spack/test/data/compilers.yaml, lib/spack/spack/test/spec_semantics.py
fixes #9908
The fastest way to solve the random order of compiler flags, which causes a randomization of the hashes for the same spec, is to employ deduplicated lists instead of sets.
=> Injected flags have a well defined order.

var/spack/repos/builtin/packages/f18/package.py
The package builds, but fails to install, since `make install` is not implemented:
```
==> Executing phase: 'install'
==> 'make' '-j4' 'install'
make: *** No rule to make target 'install'.  Stop.
'make' '-j4' 'install'
300    make[2]: Leaving directory '/home/certik/tmp/spack-stage/spack-stag
e-qO1Uea/f18/spack-build'
301    [100%] Built target f18
302    make[1]: Leaving directory '/home/certik/tmp/spack-stage/spack-stag
e-qO1Uea/f18/spack-build'
303    /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2
.0/cmake-3.12.1-dclg53ocmggeudruqobureixod4ohaeb/bin/cmake -E cmake
_progress_start /home/certik/tmp/spack-stage/spack-stage-qO1Uea/f18
/spack-build/CMakeFiles 0
304    ==> Executing phase: …
```
=> Add f18 package

var/spack/repos/builtin/packages/vtkm/package.py
This commit allows users to enable openmp, rendering, logging and mpi
in vtkm. Meanwhile, it adds support for cuda architecture selection.
[VTK-m 1.3 Release notes](https://gitlab.kitware.com/vtk/vtk-m/tags/v1.3.0)
=> Bump vtkm to version 1.3 and add new features

var/spack/repos/builtin/packages/cmake/package.py
Now that CMake is providing CMake release artifacts on github,
we should prefer those as they have better download speeds and
uptime.
=> Download CMake sources from the Github releases

var/spack/repos/builtin/packages/r-getopt/package.py, var/spack/repos/builtin/packages/r-optparse/package.py
Also included a new version for the r-getopt package, to satisfy the version requirement listed on CRAN for r-optparse.
=> r-optparse: new package

var/spack/repos/builtin/packages/kdiff3/package.py
The dependency on qt had explicit restriction to qt5. The kdiff3 website explicitly says that both qt4 and qt5 are supported, and building with qt4 works fine for me. So, I have expanded back to all versions of qt4, while keeping the version range for qt5.
=> kdiff3: Expand dependency on qt to allow qt4

var/spack/repos/builtin/packages/bcl2fastq2/package.py
[Illumina's computing requirements][reqs] claim support for RHEL/CentOS and go on to say:
> May be possible to install and run on other 64-bit Linux distributions or Unix variants.
It does not build simply on OS X, the sufficient issue is its reliance of malloc.h.  There may be more.
[reqs]: https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software/computing-requirements.html
See #9944 for additional background.
=> Disallow bcl2fastq2 on OS X

share/spack/templates/reports/junit.xml
Some error messages in the junit file may contain output that looks like tags, i.e., `<module>`, and cause Jenkins to fail parsing the files. Escape relevant output.
=> fix: adapt junit template to escape std{out,err}

lib/spack/spack/spec.py
The original error message only prints the spec and not the conflicting dependency constraints.
=> improved constraint conflict error message

var/spack/repos/builtin/packages/boost/package.py
Its in upstream with the upcoming 1.69 release though.
=> boost: 1.68 also needs `boost_1.67.0_pgi.patch`

var/spack/repos/builtin/packages/netcdf/package.py
Added the 4.6.2 version which was recently released.
Changed the url to point to the official Unidata site and added option to retrieve master version from git.
=> NETCDF: Add new versions and update url

var/spack/repos/builtin/packages/matio/package.py
Add several new versions so that current functionality can be accessed.  Current version is now 1.5.13.
Update `url`, `list_url`, and `list_depth` so spack can find available versions
=> MATIO: New versions

var/spack/repos/builtin/packages/exodusii/package.py
Allow pulling master version from git.  Note that I hope to have better versioning "soon"
Add requirement to use Netcdf-4.6.1 or later as those versions no longer require changing the `maxdims` or `maxvars` defines in the netcdf.h include file.  With these versions, Exodus can use an unmodified NetCDF.  These versions of NetCDF are also better than previous versions (code quality, performance, robustness).
It is still possible to run exodusII with previous NetCDF versions, but I don't know how to specify that the dependency where maxdims/maxvars variants are only needed for versions prior to 4.6.0.  
I also removed the explicit dependency on HDF5 as that dependency should be applied through the NetCDF dependency.
=> EXODUS: Update version and dependencies

var/spack/repos/builtin/packages/cgns/package.py
Added the `int64` variant which will build the library using 64-bit integers for certain values.  This gives the capability to have models with more than 2 billion cells and/or nodes.  
Beginning with CGNS-3.1.0, two new typedef variables have been introduced to support 64-bit mode. The `cglong_t` typedef is always a 64-bit integer, and `cgsize_t` will be either a 32-bit or 64-bit integer depending on how the library was built. Many of the C functions in the MLL have been changed to to use `cgsize_t` instead of `int` in the arguments. These functions include any that may exceed the 2Gb limit of an` int`, e.g. zone dimensions, element data, boundary conditions, and connectivity. In Fortran, all integer data is taken to be `integer*4` for 32-bit and `integer*8` for 64-bit builds.
=> CGNS: Add option for 64-bit integers

var/spack/repos/builtin/packages/vtkm/package.py
Clang 8.0 now supports openmp 4.5 and many comerical compilers also support
openmp >= 4.0. This commit removes the openmp version guard and rely on CMake
to throw errors out when openmp version requirement is not satisified.
It also add options for precision control.
=> Remove openmp version guard in vtkm and add precision options

var/spack/repos/builtin/packages/doxygen/package.py
URL to source seems to have changed. 
In addition, I added a new dependency on a fixed flex version if an old doxygen version shall be installed. The problem is that the version checker in code.l does only check subminor version but not minor version. Therefore the version checker thinks that flex@2.6.4 ist older than flex@2.5.33 for example. code.l could be patched but I did not think that it would it is worth the effort since it only affects the oldest doxygen version :-)
=> Fix doxygen package

var/spack/repos/builtin/packages/py-rope/fix_readme_unicode.patch, var/spack/repos/builtin/packages/py-rope/package.py
I was encountering errors when installing `py-rope` as a dependency of something and this unicode character in its readme file was causing it to fail during install. This patch removes the unicode character.
=> Adding patch to remove unicode character from pyrope readme file

lib/spack/spack/multimethod.py, lib/spack/spack/spec.py, lib/spack/spack/test/multimethod.py, lib/spack/spack/test/spec_semantics.py, var/spack/repos/builtin.mock/packages/multimethod-base/package.py, var/spack/repos/builtin.mock/packages/multimethod-diamond-parent/package.py, var/spack/repos/builtin.mock/packages/multimethod-diamond/package.py, var/spack/repos/builtin.mock/packages/multimethod-inheritor/package.py, var/spack/repos/builtin.mock/packages/multimethod/package.py, var/spack/repos/builtin/packages/zlib/package.py
Multimethods (using the `@when` decorator) previously did not work with package inheritance.
If package `foo` extended package `bar` and `bar` used multimethods, `spack install foo` would enter an infinite recursion and hit python's maximum recursion depth.
This was due to our reliance on the `super` method to recurse up the method resolution order. The `super` builtin ~uses~ returns a proxy object that delegates method lookup to the superclass but does not change the bound object of methods of the proxy object. This lead to a recursion error when searching for possible matches for a multimethod.
This PR changes the search algorithm for multimethods to use `inspect.getmro()` to search the MRO DAG for the class and uses an iterative instead of recursive algorithm to ensure we follow MRO …
=> bugfix: multimethod inheritance

var/spack/repos/builtin/packages/gcc/package.py, var/spack/repos/builtin/packages/gcc/sys_ustat.h.patch
=> gcc: Add patch to build GCC with glibc 2.28 and later

var/spack/repos/builtin/packages/catch/package.py
Fix the install of the single header amalgate in catch2.
Thanks for @goxberry for noting the broken build! This PR is a simplified fix for the build issue reported in #9876.
Please be aware that the public API for catch <2.3.0 was `#include <catch.hpp>` which is now for 2.3.0+ `#include <catch2/catch.hpp>`: https://github.com/catchorg/Catch2/releases/tag/v2.3.0
=> Fix Catch2 Single Header

var/spack/repos/builtin/packages/openmpi/package.py
I've tested this for OpenMPI 3.1.3 and adding `--enable-static` didn't disable Slurm for me (I could use `srun` is all I specifically tested). According to https://github.com/open-mpi/ompi/issues/4338 this should be ok now. @ax3l
=> OpenMPI: adding static libraries with slurm support for latest versions.

var/spack/repos/builtin/packages/metis/gklib_nomisleadingindentation_warning.patch, var/spack/repos/builtin/packages/metis/package.py
Added patch to GKlibSystem.cmake to disable warnings (which get
promoted to errors) due to -Wmisleading-indentation being added
to -Wall in gcc 6
=> metis: Fix issues with gcc6 and misleading indentation

lib/spack/spack/util/web.py
This PR addresses a bug discovered in #10025. For `cdo`, the [downloads page](https://code.mpimet.mpg.de/projects/cdo/files) contains two types of links, one with `/download` in the path that downloads the tarball, and one without that brings you to a page with the same link. Currently, `spack.util.web.find_versions_of_archive` behaves non-deterministically, and depending on which version of Python you use, you may get very different results:
```console
$ python3 $(which spack) checksum cdo
==> Found 10 versions of cdo:
1.9.6rc4  https://code.mpimet.mpg.de/attachments/18911/cdo-1.9.6rc4.tar.gz
1.9.5     https://code.mpimet.mpg.de/attachments/download/18264/cdo-1.9.5.tar.gz
1.9.4     https://code.mpimet.mpg.de/attachments/download/17374/cdo-1.9.4.tar.gz
1.9.3 …
```
=> Make downloads from list_url deterministic

var/spack/repos/builtin/packages/gcc/package.py, var/spack/repos/builtin/packages/gcc/sys_ustat-4.9.patch
The sys_ustat.h.patch to file sanitizer_platform_limits_posix.cc from
PR #10046 does not apply cleanly to gcc 4.8 or 4.9 (or earlier).
GCC up to 4.8.x either don't have libsanitizer or else don't include
ustat.h in sanitizer_platform_limits_posix.cc.
GCC 4.9.x includes ustat.h, but needs a slightly different patch.
The patch applies to GCC 5.x up to 6.4, and 7.x up to 7.3 and also
8.1.0.
The patch is already included in the tar files for gcc 6.5.0, 7.4.0
and 8.2.0.
----------
It's quite the matrix for what versions of gcc will compile other
versions of gcc.  For example, I was able to use 4.4.7 to compile
4.8.5, but using 7.3.1 to compile the same 4.8.5 falls over.  Blech.
But that's a problem for another day.
=> gcc: fix sys_ustat.h patch for gcc 4.8 and 4.9

var/spack/repos/builtin/packages/cuda/package.py
It appears certain things expect a `CUDA_HOME` to be set, so this PR creates this variable. For example: https://www.pgroup.com/resources/docs/18.4/openpower/pgi-release-notes/index.htm
=> Add CUDA_HOME variable to cuda module file.

var/spack/repos/builtin/packages/trf/package.py
Changes to the installation method are to persist the original filename (a requirement for us) and provide a symlink named trf to maintain backwards compatibility.
=> trf: add version 4.07b and install fixes

var/spack/repos/builtin/packages/meson/package.py
Successfully builds on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of meson

lib/spack/spack/build_environment.py, lib/spack/spack/modules/common.py, lib/spack/spack/test/build_environment.py, var/spack/repos/builtin.mock/packages/multimodule-inheritance/package.py, var/spack/repos/builtin.mock/packages/simple-inheritance/package.py
Previously, module variables set by the Spack build environment were not available for parent classes when using inheritance to create packages. This was fixed for dependencies previously, but not for the top level package.
More specifically what failed prior to this PR: a Spack package were declared `class Foo(Bar)`, where `Bar` is another Spack package. When `Foo.func()` was called, if `func` is a method defined on `Bar` and inherited by `Foo` that requires module variables from the build environment (like `env['CFLAGS'] = 'baz'`), then Spack would fail with a `NameError`.
This is resolved by this PR, and a regression test is added.
=> Fix spack package inheritance for module variables

share/spack/qa/run-build-tests
Lately many CI runs for PRs are failing due to the `mpich` build that times out on Travis (10 mins. without output). As the timeout seems to happen consistently during the build phase, increasing the verbosity of that test can help working around the issue.
=> Turn on verbose output for MPICH builds in Travis

.travis.yml
closes #9947 
closes #9815
According to this [post](https://blog.travis-ci.com/2018-11-08-xenial-release) `xenial` has been officially released on Travis since a month or so. This PR moves all the CI tests to `xenial` and removes allowed failures for it and python 2.6.
=> Updated the Travis environment to xenial

var/spack/repos/builtin/packages/cairo/package.py
Successfully builds on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of cairo

var/spack/repos/builtin/packages/poppler/package.py
Successfully builds on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of poppler

var/spack/repos/builtin/packages/libxslt/package.py
Successfully builds and passes all tests on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of libxslt

var/spack/repos/builtin/packages/qt/package.py
Looks like I forgot qt in the openssl@1.1 update. This should fix older versions.
=> qt: fix openssl dependency for older versions

var/spack/repos/builtin/packages/googletest/package.py
At some point Google moved Google Test to a new GitHub org called "Abseil" (See: https://www.github.com/abseil/googletest). This ended up breaking the tar ball hashes (though I'm honestly not sure why). I've fixed all the existing versions and added the newer release 1.8.1.
It would be nice if this change could be backported to v0.12 if at all possible (googletest installs basically fail right now without using `--no-checksum`), though I'm not totally clear what the philosophy around releases is for Spack.
=> Fixes for Google Test

var/spack/repos/builtin/packages/clp/package.py
some builds would fail due to some weird stuff going on in the configure phase -- explicitly specifying a `--with-clp-datadir` configure arg seems to fix it.
=> clp: add explicit datadir

var/spack/repos/builtin/packages/libatomic-ops/package.py
Successfully builds and passes all tests on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of libatomic-ops

var/spack/repos/builtin/packages/bdw-gc/package.py
Successfully builds and passes all tests on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of bdw-gc

var/spack/repos/builtin/packages/libsigcpp/package.py
Successfully builds on macOS 10.14.2 with Clang 10.0.0.
=> Add latest version of libsigcpp

.travis.yml, share/spack/qa/configuration/config.yaml
This is save time in build tests phase
=> Enable ccache in travis

lib/spack/spack/cmd/pkg.py
```console
$ spack pkg --help
usage: spack pkg [-h] SUBCOMMAND ...
query packages associated with particular git revisions
positional arguments:
SUBCOMMAND
add
list      List packages associated with a particular spack git revision.
diff      Compare packages available in two different git revisions.
added     Show packages added since a commit.
removed   Show packages removed since a commit.
optional arguments:
-h, --help  show this help message and exit
```
```console
$ spack pkg --help
usage: spack pkg [-h] SUBCOMMAND ...
query packages associated with particular git revisions
positional arguments:
SUBCOMMAND
add       Add a package to the git stage.
list      List packages associated with a particular spack git revision.
diff      Compare packages available in two different git …
```
=> spack pkg add: add help message

.travis.yml
Despite we started using `ccache` on `develop`, it seems the cache itself is not stored from one CI build to the next. This might be due to the fact that our language on Travis is Python and not C nor C++.
Hence here we store the `ccache` directory explicitly.
=> Store ccache directory explicitly in Travis.

share/spack/setup-env.sh
`spack cd --help` was not printing anything. Speed up `spack env --help`.
=> env setup: support --help for cd/env commands

var/spack/repos/builtin/packages/atk/package.py
Also adds minimum version requirements for meson. Successfully builds on Cray CNL5 (Blue Waters) with GCC 7.3.0.
=> Add latest version of atk

var/spack/repos/builtin/packages/zoltan/package.py
- if MPI-wrappers are used for compilation, we can assume that
linking works without manually specifying MPI libs
(guessing may result in wrong libs as reported in https://github.com/spack/spack/issues/8979#issue-350533572)
- thus, only guess the MPI libs and add them explicitly if no
MPI-wrappers are used
- use llnl.util.filesystem.find_libraries instead of a locally
defined routine to guess the MPI libs if needed
(as suggested in https://github.com/spack/spack/issues/8979#issuecomment-412969488)
fixes #8979
=> zoltan: rely on MPI wrappers instead of guessing MPI libraries

var/spack/repos/builtin/packages/freetype/package.py, var/spack/repos/builtin/packages/freetype/windows.patch
Fixes #9729.
I took the patch from https://savannah.nongnu.org/bugs/index.php?54967, generated a new `configure` script, and produced a new patch of the relevant changes. This way, we don't need to add `m4`, `libtool`, `autoconf`, and `automake` dependencies needed by the previous patch.
With this patch, I was able to successfully install freetype with GCC 4.9.3 on Cray CNL5 (Blue Waters).
@jrood-nrel
=> Add patch to fix windows.h include in freetype

lib/spack/spack/cmd/buildcache.py
This specific flag for this specific command is the only one in Spack containing underscores. Since every Unix command I know of uses [dashes](https://stackoverflow.com/q/1253679/5828163), I switched it to dashes for conformity. No changes are needed for the Bash completion script, as the script already thinks it is `--all-root`.
=> spack buildcache: --allow_root -> --allow-root

lib/spack/spack/cmd/gpg.py
```console
$ spack gpg --help
usage: spack gpg [-h] SUBCOMMAND ...
handle GPG actions for spack
positional arguments:
SUBCOMMAND  GPG sub-commands
optional arguments:
-h, --help  show this help message and exit
```
```console
$ spack gpg --help
usage: spack gpg [-h] SUBCOMMAND ...
handle GPG actions for spack
positional arguments:
SUBCOMMAND  GPG sub-commands
verify    verify a signed package
trust     add a key to the keyring
untrust   remove a key from the keyring
sign      sign a package
create    create a new key
list      list keys available in the keyring
init      add the default keys to the keyring
export    export a secret key
optional arguments:
-h, --help  show this help message and exit
```
I don't know much about this command, so I read [the …
=> Add help messages to spack gpg subcommands

var/spack/repos/builtin/packages/libbsd/package.py
Successfully builds and passes all unit tests on Cray CNL5 (Blue Waters) with GCC 7.3.0.
=> Add latest version of libbsd

var/spack/repos/builtin/packages/libxdmcp/package.py
```
4 errors found in build log:
163      CC       Key.lo
164      CC       Read.lo
165      CC       Unwrap.lo
166      CC       Wrap.lo
167      CC       Write.lo
168      CC       Wraphelp.lo
>> 169    Key.c:36:10: fatal error: bsd/stdlib.h: No such file or directory
170     #include <bsd/stdlib.h> /* for arc4random_buf() */
171              ^~~~~~~~~~~~~~
172    compilation terminated.
>> 173    make[2]: *** [Key.lo] Error 1
174    make[2]: *** Waiting for unfinished jobs....
175    make[2]: Leaving directory `/mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-392119gc/libXdmcp-1.1.2'
>> 176    make[1]: *** [all-recursive] Error 1
177    make[1]: Leaving directory `/mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-392119gc/libXdmcp-1.1.2'
>> 178    make: *** [all] Error 2 …
```
=> Add missing libbsd dependency to libxdmcp

var/spack/repos/builtin/packages/ghostscript/package.py
Also adds missing GTK+ dependency.
```
4 errors found in build log:
4645       /bin/sh <./soobj/ldt.tr
4646    make[2]: Leaving directory `/mnt/c/scratch/sciteam/stewart1/spack-stage/spack-stage-6gi4ajdt/ghostscript-9.21'
4647    make -f Makefile DISPLAY_DEV=./soobj/display.dev STDIO_IMPLEMENTATION=c BUILDDIRPREFIX=so GENOPT='' LDFLAGS=' '\
4648        CFLAGS='-fPIC  -O2 -Wall -Wstrict-prototypes -Wundef -Wmissing-declarations -Wmissing-prototypes -Wwrite-strings -Wno-strict-aliasing -Werror=declaration-after-statement -fno-builtin -fno-common -Werror=return-type -DHAVE_STDINT_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBDL=1 -DGX_COLOR_INDEX_TYPE="unsigned long long" -D__USE_UNIX98=1 …
```
=> Add latest version of ghostscript

var/spack/repos/builtin/packages/gdk-pixbuf/package.py
Switches the build system to meson. Also adds a new dependency on `shared-mime-info` for all non-Windows/macOS platforms. Successfully builds on Cray CNL5 (Blue Waters) with GCC 7.3.0.
=> Add latest version of gdk-pixbuf

var/spack/repos/builtin/packages/at-spi2-core/package.py
```
6 errors found in build log:
225    [46/53] /mnt/a/u/sciteam/stewart1/spack/lib/spack/env/gcc/gcc -Iatspi/f291f98@@atspi@sha -Iatspi -I../atspi -I. -I../ -Iregistryd -I../registryd -I/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/dbus-1.12.8-m6jcirtiqk3gha3padz5e5c6etlpfqgm/include/dbus-1.0 -I/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/dbus-1.12.8-m6jcirtiqk3gha3padz5e5c6etlpfqgm/lib/dbus-1.0/include -I/mnt/bwpy/single/usr/include/glib-2.0 -I/mnt/bwpy/single/usr/lib/glib-2.0/include -I/mnt/bwpy/single/usr/include -I/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/libx11-1.6.5-pmbsh6qks353k7ldwkcjzy3ox3k3wdfh/include -I/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-7.3.0/xproto-7.0.31-56jx …
```
=> Add missing gettext dependency to at-spi2-core

var/spack/repos/builtin/packages/rocksdb/package.py
This is a spack package for RocksDB, a persistent key-value store for flash and RAM storage. We use the recommended Makefile build process and added variants for all the optional compression library dependencies.
Here's the project repo: https://github.com/facebook/rocksdb/
And here are their build instructions: https://github.com/facebook/rocksdb/blob/master/INSTALL.md
=> Added RocksDB package

var/spack/repos/builtin/packages/saga-gis/package.py
SAGA is a GIS for Automated Geoscientific Analyses and has been designed for an easy and effective implementation of spatial algorithms.  It offers a comprehensive, growing set of geoscientific methods and provides an easily approachable user interface with many visualisation options. It offers both a cmd (for batch jobs) and a gui mode as well.
The most recent dependencies of saga-gis include at-spi2-core, which is built with meson, which requires python3. I added a fixme line because this implicit dependency requires that saga-gis depends on python3 as well, even though there is no need to (since the need for python3 should be limited to the build system meson). Don't know if there is a better solution available...
=> Add spack package for saga-gis

var/spack/repos/builtin/packages/atlas/package.py
Atlas automatically configures itself and optimizes to run with a fixed number of threads. This can be overridden during compile by setting a flag and atlas will tune itself to use the specified number, rather than all system CPUs. 
Default value is the existing logic, autoconfigure.
=> Add thread count variant to atlas

var/spack/repos/builtin/packages/clp/package.py
#10109 seemed to fix the build at first but later stopped working. I suspect this may be a bug in spack but adding build_directory has worked for another package `time` with the same issue.
=> clp: add build_directory, remove old hack

var/spack/repos/builtin/packages/warpx/package.py
A small fix. WarpX needs fftw3 installed when using psatd.
=> WarpX: Added dependency on fftw when +psatd

var/spack/repos/builtin/packages/mpifileutils/package.py
I'm not sure the mpifileutils package ever properly built, especially if trying to use a system libarchive. In any case, I have a bunch of fixes here:
- this package will not work on macs
- all dependency paths are set on the `./configure` line, rather than relying on pkg-config
- the mfu sub tools need to include `src/common`
=> fix for mpifileutils package

lib/spack/docs/build_systems/mesonpackage.rst
I've been having a hell of a time getting GTK+ and friends to build lately, and since the entire GNOME ecosystem seems to be moving to Meson, I've had to learn a lot about Meson. Adding some new info to the docs.
=> Add additional info to MesonPackage docs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build_error.md, .github/ISSUE_TEMPLATE/feature_request.md
These labels are applied automatically when the issues are created. See [this request](https://github.community/t5/How-to-use-Git-and-GitHub/Apply-labels-automatically-at-issue-creation/td-p/10719) and the corresponding [docs](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/).
=> Added labels in github issue templates

var/spack/repos/builtin/packages/docbook-xsl/docbook-xsl-1.79.2-stack_fix-1.patch, var/spack/repos/builtin/packages/docbook-xsl/package.py
Also adds a patch courtesy of [Linux from Scratch](http://www.linuxfromscratch.org/blfs/view/8.3-systemd/pst/docbook-xsl.html), and simplifies the install method. The SourceForge download no longer works for me. It seems like they've moved to GitHub.
=> Add latest version of docbook-xsl

var/spack/repos/builtin/packages/libxml2/package.py
```
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/libxml2-2.9.8-m6e5jpylv5o4bhxc6ops5oclun3qi52z/lib/libxml2.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/libxml2-2.9.8-m6e5jpylv5o4bhxc6ops5oclun3qi52z/lib/libxml2.dylib:
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/libxml2-2.9.8-m6e5jpylv5o4bhxc6ops5oclun3qi52z/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.8.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/zlib-1.2.11-uw6agnye4za7cpgyyaaejrzorhbhqno5/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11) …
```
=> Add missing libiconv dependency to libxml2

lib/spack/spack/fetch_strategy.py, var/spack/repos/builtin/packages/h5z-zfp/package.py
Currently, only the Git repsository's URL shows up in the `spack info` output, which makes it hard to distinguish different versions:
```
Safe versions:
develop    [git] https://github.com/LLNL/H5Z-ZFP.git
0.8.0      [git] https://github.com/LLNL/H5Z-ZFP.git
0.7.0      [git] https://github.com/LLNL/H5Z-ZFP.git
```
This change adds additional information as shown when cloning a Git repository:
```
Safe versions:
develop    [git] https://github.com/LLNL/H5Z-ZFP.git on branch master
0.8.0      [git] https://github.com/LLNL/H5Z-ZFP.git at commit af165c4
0.7.0      [git] https://github.com/LLNL/H5Z-ZFP.git at commit 58ac811
```
=> fetch_strategy: improve GitFetchStrategy

var/spack/repos/builtin/packages/kallisto/package.py
[Per kallisto package maintainer](https://github.com/pachterlab/kallisto/issues/195#issuecomment-448542235):
> The md5sum is `071e6bfb62be06fd76552298d4cf8144`.  I've checked the file that I downloaded on March 20th 2017 on the machine where I build the binaries as well as the file served from github.
This fixes #10118
FYI @adamjstewart
=> kallisto: updated checksum

lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/activate.py, lib/spack/spack/cmd/add.py, lib/spack/spack/cmd/buildcache.py, lib/spack/spack/cmd/concretize.py, lib/spack/spack/cmd/config.py, lib/spack/spack/cmd/deactivate.py, lib/spack/spack/cmd/dependencies.py, lib/spack/spack/cmd/dependents.py, lib/spack/spack/cmd/env.py, lib/spack/spack/cmd/extensions.py, lib/spack/spack/cmd/find.py, lib/spack/spack/cmd/install.py, lib/spack/spack/cmd/location.py, lib/spack/spack/cmd/remove.py, lib/spack/spack/cmd/stage.py, lib/spack/spack/cmd/uninstall.py, lib/spack/spack/cmd/view.py, lib/spack/spack/environment.py
- Environment support for arguments of some commands were missed in the rollout of spack environments
- For example, `spack location -i` complains about ambiguous specs, even when it's caused by specs outside the current environment
=> env: all commands that disambiguate specs should be env-aware

var/spack/repos/builtin/packages/cgns/package.py
Add ability to use git `master` and `develop` branches of the CGNS library.  The `seacas` package sometimes needs to use the `master` or `develop` branch due to some new changes to the parallel I/O implementation in CGNS which has not yet been released.
=> CGNS: Allow use of git branch versions

lib/spack/spack/cmd/install.py, lib/spack/spack/report.py, lib/spack/spack/reporter.py, lib/spack/spack/reporters/cdash.py, lib/spack/spack/reporters/junit.py, lib/spack/spack/test/cmd/install.py, share/spack/templates/reports/cdash/Site.xml, share/spack/templates/reports/cdash/Update.xml
* More customization options: allow user to specify the build name, site name, and/or track to report to CDash
* Check for a buildId in the response for CDash.  If one is found, print out a link to view the results in CDash
* Record and report the current git commit SHA1 of Spack to CDash
* Report more accurate build time information to CDash (#9590)
* Improve performance of report generation when lots of build output is generated
=> More improvements for CDash reporter

.dockerignore, share/spack/docker/Dockerfile, share/spack/docker/entrypoint.bash, share/spack/docker/handle-prompt.sh, share/spack/docker/handle-ssh.sh
- fixed an issue where some undesirable parts of
the spack source tree were being copied into
the image context.
- added a workaround for a tty ioctl warning on
ubuntu
- adjusted how the main images are built so that
`RUN spack ...` works automatically for child
images that base themselves on them.
=> fix multiple issues with the docker images

.travis.yml, share/spack/docker/Dockerfile, share/spack/qa/run-docker-tests
Fixes issue from #9658.
This PR should not be merged as-is.  This is because I've included an initial [commit](be179569b89b4cae4d352702b82413ac2dbc16ca) that removes a troublesome section of the travis file.  [Here](https://travis-ci.org/opadron/spack/jobs/453687889) is the log of a travis job that ran on the tip of this branch off of my fork.
These results show that 1 - the original issue from #9658 is not related to docker, and is a distinct issue that needs to be addressed, and 2 - the changes in this PR, other than the initial commit, are all that should be necessary for the `docker` stage to produce working images.  I haven't tested pushing to dockerhub, but I don't think it will be an issue.
=> Fix docker builds

var/spack/repos/builtin/packages/py-h5py/package.py
https://github.com/h5py/h5py/releases/tag/2.9.0
=> update h5py to 2.9.0

etc/spack/defaults/config.yaml, lib/spack/docs/config_yaml.rst
/nfs/tmp2 is going away from LC... and doesn’t exist for the world. Why have it here???
=> Remove /nfs/tmp2 option

var/spack/repos/builtin/packages/glib/package.py
Enable explicitly building glib with or without libiconv.
We're seeing something like what was described in #6962.  In our case it seems to be caused by glib depending on libxm2, which in turn has a dependency on libiconv.  This puts the libiconv bits in the build environment and glib trips over them.
Heads up: if you build with `~iconv` but there is something else in the spec that includes libiconv then glib will *still* automagically discover it and the build will fail.
I don't currently have the cycles to dig into glib's configure script and figure out why it's still tripping over the libiconv header when it's explicitly been configured with `--with-libiconv=no`.
In order for our build to succeed, we need to build `glib+iconv`.  I've made the default `~iconv`.  I could make it `+iconv` …
=> Add libiconv variant to glib

var/spack/repos/builtin/packages/py-numba/package.py
Without the colon, spack will complain that there is no checksumed version `0.25` for `py-llvmlite`.
=> py-numba: fix py-llvmlite version

var/spack/repos/builtin/packages/alquimia/package.py, var/spack/repos/builtin/packages/pflotran/package.py, var/spack/repos/builtin/packages/trilinos/package.py, var/spack/repos/builtin/packages/xsdk/package.py
hypre@2.15.1
mfem@3.5.0-rc1
superlu-dist@6.1.0
trilinos@12.14.0-rc1
petsc@3.10.2
dealii@9.0.1
pflotran@xsdk-0.4.0
alquimia@xsdk-0.4.0
sundials@3.2.1
plasma@18.11.1
magma@2.4.0
amrex@18.10.1
slepc@3.10.1
omega-h@9.19.1
strumpack@3.1.1
pumi@2.2.0
tasmanian@6.0
phist@1.7.4
dtk-3.0 [via trilinos features '+dtk+intrepid2+shards']
add option to disable omega-h build [wrt gcc-8 conflict]
spack install xsdk~omega-h
=> xsdk-0.4.0: add/update package versions:

.travis.yml
It looks like `pip install ...` can sometimes [fail](https://travis-ci.org/spack/spack/jobs/470905791) for the docker stage.  I'm guessing that it might have to do with `language: generic` being set instead of `language: python` , so this PR makes that change in the hopes that Travis then runs in an environment where `pip install ...` would "just work".
=> travis: fix pip install for docker stage

lib/spack/spack/test/util/executable.py, lib/spack/spack/util/executable.py
Supersedes #10050.
This fixes bugs in `spack blame` like this:
```console
(spackbook):spack$ spack blame catalyst
==> Error: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```
In this case it was the "à" in "Simone Bnà" that was causing Python to fail.  The #10050 tried to solve this in `colify.py`, but I think the issue is that we weren't properly decoding text at the edges in the first place. I tracked this down to the pipe read in `spack.util.executable`, and just made *that* treat everything as proper unicode.
This also adds a test to verify that we're able to round-trip unicode through an `Executable` object.
=> bugfix: handle unicode properly in spack.util.executable

lib/spack/spack/test/cmd/test_compiler_cmd.py
The unit test `test_compiler_add` stalls frequently on Travis in the Python 2.6 runner. As this test spawns multiple processes and waits for them to join, here we try to see if without spawning the test is more reliable.
=> Don't spawn processes during python 2.6 'test_compiler_add' unit test

var/spack/repos/builtin/packages/libxml2/package.py, var/spack/repos/builtin/packages/libxslt/package.py
See #10195.
With this PR, I am able to install `libxml2+python` and `libxslt+python` on macOS 10.14.2 with Clang 10.0.0 and all tests pass with flying colors.
=> Fix libxml2+python and libxslt+python import tests

var/spack/repos/builtin/packages/pkgconf/package.py
Fixes failed `pkgconf` downloads as reported in https://github.com/spack/spack/pull/10200#issuecomment-449991692.
The checksums don't seem to have changed, at least for the latest version.
@aprokop
=> Fix pkgconf downloads

var/spack/repos/builtin/packages/velvet/package.py
Fixes `fatal error: zlib.h: No such file or directory` installation errors
=> velvet: Add missing zlib dependency to fix installation errors

var/spack/repos/builtin/packages/gdal/package.py
Successfully builds and passes all unit tests on Cray CNL5 (Blue Waters) using GCC 7.3.0.
GDAL 2.4.0 [removes the PHP bindings](https://trac.osgeo.org/gdal/wiki/Release/2.4.0-News).
=> Add GDAL 2.4.0

.travis.yml
This uses the new [Homebrew addon](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-os-x) feature in Travis instead of doing it manually.
Let's see whether we can get this working.
=> Use homebrew addon instead of manually invoking brew

var/spack/repos/builtin/packages/glib/package.py
My early PR, #10165, which added a variant to configure glib to use
libiconv and defaulted to false, seems to be causing more trouble than
the knob is worth.
This changes the glib package to always depend on and use libiconv.
=> Always build glib with iconv

.codecov.yml, .coveragerc, .travis.yml, share/spack/qa/bashcov, share/spack/qa/setup.sh
We don't current have coverage information for the `cc` wrapper, though it's an important part of Spack
=> coverage: use kcov to get coverage for compiler wrappers

.travis.yml, lib/spack/docs/packaging_guide.rst, lib/spack/spack/cmd/resource.py, lib/spack/spack/directives.py, lib/spack/spack/package.py, lib/spack/spack/patch.py, lib/spack/spack/provider_index.py, lib/spack/spack/repo.py, lib/spack/spack/spec.py, lib/spack/spack/test/cmd/env.py, lib/spack/spack/test/cmd/providers.py, lib/spack/spack/test/cmd/resource.py, lib/spack/spack/test/install.py, lib/spack/spack/test/mirror.py, lib/spack/spack/test/patch.py, lib/spack/spack/test/provider_index.py, share/spack/spack-completion.bash, var/spack/repos/builtin/packages/catalyst/package.py
This fixes some bugs with dependency patching discovered by @scottwittenburg, and it makes the patch system a more robust.  The previous logic for getting patches from a `Spec` assumed that all dependents were still in the DAG.  If you extracted a sub-DAG like this:
```python
dealii = Spec('dealii').concretized()
boost_yaml = dealii['boost'].to_yaml()
boost = Spec.from_yaml(boost_yaml)
boost.package.do_install()
```
And then attempted to build the `boost` spec, you'd find that `dealii`'s patches on `boost` would not be applied properly, because Spack couldn't find them anymore.  The prior logic assumed that `dealii` was concretized and built immediately, that `dealii` was an ancestor of `boost` in the DAG, and that `dealii.patches()` was called sometime before `dealii['boost']` was built. …
=> patches: add a patch cache, allow patches to be looked up by sha256

var/spack/repos/builtin/packages/dealii/package.py
otherwise
```
hdf5@1.10.4%clang@10.0.0-apple~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=darwin-mojave-x86_64
^openmpi@3.1.3%clang@10.0.0-apple~cuda+cxx_exceptions fabrics= ~java~legacylaunchers~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=darwin-mojave-x86_64
^hwloc@:1.999
^pkgconf@1.5.4%clang@10.0.0-apple arch=darwin-mojave-x86_64
^zlib@1.2.11%clang@10.0.0-apple+optimize+pic+shared arch=darwin-mojave-x86_64
while trying to concretize the partial spec:
petsc@3.10.3%clang@10.0.0-apple~X clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared~suite-sparse+superlu-dist~trilinos arch=darwin-mojave-x86_64
^hypre@2.14:~int64~internal-superlu …
```
=> dealii: workaround concretization issue with PETSc

var/spack/repos/builtin/packages/flang/package.py, var/spack/repos/builtin/packages/llvm/package.py, var/spack/repos/builtin/packages/pgmath/package.py
This is my first attempt to take over managing the spack package for Flang.
We did a binary release for Flang on GitHub in September, and uploaded corresponding source files and binary files to the Flang repository. Left undone was creating the equivalent spack releases for this.
So, this is a simple pull request to define the new release in the same was as the old ones were.
This is in preparation for me adding the release for December 2018.
Please let me know anything i'm not doing right here (obviously); I read the contribution guide and think I did the necessary, but I can't be certain.
Thanks.
=> flang, llvm, pgmath: Add release for 2018-09-21

var/spack/repos/builtin/packages/bamutil/libstatgen-issue-17.patch, var/spack/repos/builtin/packages/bamutil/libstatgen-issue-19.patch, var/spack/repos/builtin/packages/bamutil/libstatgen-issue-7.patch, var/spack/repos/builtin/packages/bamutil/package.py, var/spack/repos/builtin/packages/bamutil/verifybamid-issue-8.patch
The most recent release of bamutil that we support uses an embedded
copy of libStatGen that has several issues that keep it from building
with newer releases of gcc.
They've all been fixed upstream and the latest release of bamutil
would pick them up if/when we support it.  The build process has
changed though, plus my team needs *this* version.
This commit backports those fixes.
=> bamutil builds with newer gcc's

var/spack/repos/builtin/packages/fastx-toolkit/package.py, var/spack/repos/builtin/packages/fastx-toolkit/pr-22.patch
There's a missing break in a switch statement that newer gcc's
dislike.
Our #4696 simply disallowed newer gcc's.
This fixes the problem instead.
It's been [PR'ed upstream](https://github.com/agordon/fastx_toolkit/pull/22).
Tested with gcc@5.5.0 and gcc@8.2.0 on CentOS.
=> fastx-toolkit builds with newer gcc's

var/spack/repos/builtin/packages/aspell/issue-519.patch, var/spack/repos/builtin/packages/aspell/package.py
Apply fix from aspell issue (519) for a pointer dereference bug that
newer versions of gcc won't let slip past.
There hasn't been a release that includes the fix, this applies the
change to the latest release.
@odoublewen
=> aspell builds with newer gcc's

lib/spack/llnl/util/lang.py, lib/spack/spack/config.py, lib/spack/spack/environment.py, lib/spack/spack/schema/__init__.py, lib/spack/spack/schema/env.py, lib/spack/spack/schema/merged.py, lib/spack/spack/schema/modules.py, lib/spack/spack/test/schema.py
fixes #9857 
This PR improves the validation of `modules.yaml` by introducing a custom validator that checks if an attribute listed in `properties` or `patternProperties` is a valid spec. This new check applied to the test case in #9857 gives:
```console
$ spack install szip
==> Error: /home/mculpo/.spack/linux/modules.yaml:5: "^python@2.7@" is an invalid spec [Invalid version specifier]
```
@tgamblin @adamjstewart @scheibelp and others: can you please double check the schema? `modules.yaml` is fairly complex to check and more eyes could spot more bugs.
@trecakov Can you try this PR on the failure you reported in Slack? Hopefully you'll get an error report pointing to the exact line that needs to be changed.
=> Improve validation of modules.yaml

var/spack/repos/builtin/packages/r-readr/package.py
r-tidyverse needs r-readr@1.1.1.
r-reardr needs a list_url so that it can find the old versions.
=> Add list_url for r-readr, finding old versions

lib/spack/spack/schema/modules.py
refers #9878 
Removed an extra comma after a dict literal.
The extra comma was turning a dict into a tuple, and caused errors during validation of the schema.
=> Fixed broken module file configuration

var/spack/repos/builtin/packages/parallel-netcdf/package.py
PnetCDF-1.11.0 is released.
Also, the canonical download area has been changed and they are now using git, so can also provide a develop and master checkout.
One issue is that they changed the name of the tar files, so 1.11.0 needs special handling (and future versions will also).
All checksums at new location match the checksums from the old location.
=> PARALLEL-NETCDF: Update new version and location

lib/spack/spack/mirror.py, lib/spack/spack/package.py, lib/spack/spack/patch.py, lib/spack/spack/spec.py, lib/spack/spack/test/patch.py
Currently, `spack mirror create bzip2` fails with the following error:
```
==> Warning: Error while fetching bzip2@1.0.6
global name 'spack_cc' is not defined
```
This is due to the fact that `mirror create` invokes `do_patch`, which calls the package's `patch` method. Since `mirror create` does not set up the appropriate environment, variables like `spack_cc` are not set.
This change introduces `fetch` and `clean` methods for patches. They are no-ops for `FilePatch` but perform the appropriate actions for `UrlPatch`. This allows `mirror create` to invoke `do_fetch`, which does not call the package's `patch` method.
=> patch: split up fetch and clean into separate methods

lib/spack/spack/graph.py
Otherwise the `--` in `--dot` is rendered as a single en-dash.
=> bugfix: add missing code block

var/spack/repos/builtin/packages/cudnn/package.py
this is a fix to the download path which has disappeared
=> Fix download path, the existing one has been removed from nvidia's site

lib/spack/spack/stage.py, lib/spack/spack/test/stage.py
Resources can be deleted from the local cache because `ResourceStage` moves its resources to the root stage instead of copying them. If a locally cached resource exists, it is symlinked into the resource stage and then moved out of the local cache. This can be reproduced with the following commands:
1. `spack stage sqlite+functions` (fetches archive and resource)
2. `spack clean`
3. `spack stage sqlite+functions` (uses locally cached versions)
4. `spack clean`
5. `spack stage sqlite+functions` (fetches resource again)
=> stage: fix resources being deleted from local cache

var/spack/repos/builtin/packages/mvapich2/package.py
Without it, mvapich2's build fails when linking (encountered in a minimal Ubuntu 18.04 image).
=> mvapich2: add missing zlib dependency

lib/spack/docs/packaging_guide.rst, lib/spack/spack/build_systems/autotools.py, lib/spack/spack/build_systems/cuda.py, lib/spack/spack/directives.py, lib/spack/spack/pkgkit.py, lib/spack/spack/test/build_systems.py, lib/spack/spack/test/spec_semantics.py, lib/spack/spack/test/variant.py, lib/spack/spack/variant.py, var/spack/repos/builtin.mock/packages/a/package.py, var/spack/repos/builtin.mock/packages/multivalue_variant/package.py, var/spack/repos/builtin/packages/adios/package.py, var/spack/repos/builtin/packages/axl/package.py, var/spack/repos/builtin/packages/glib/package.py, var/spack/repos/builtin/packages/kokkos/package.py, var/spack/repos/builtin/packages/matlab/package.py, var/spack/repos/builtin/packages/mvapich2/package.py, var/spack/repos/builtin/packages/omega-h/package.py, var/spack/repos/builtin/packages/openblas/package.py, var/spack/repos/builtin/packages/openmpi/package.py, var/spack/repos/builtin/packages/py-patsy/package.py, var/spack/repos/builtin/packages/regcm/package.py, var/spack/repos/builtin/packages/scr/package.py, var/spack/repos/builtin/packages/yambo/package.py
fixes #6314 
To sum up the issue: `multi-valued` variants with default set to `None` were not parsable from the command line, as `None` was converted to the empty string.
This PR solves the problem by sanitizing all the packages against having `None` as a default value, and allows for the more declarative syntax discussed in the issue.
The implementation is based on the possibility that the `variant` directive now has to accept as the `values` argument an object that could prescribe its own default value or other settings. A declarative style can be maintained using a [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface) to set these embedded arguments in such an object.
A few packages have been modified to show how the new (optional) syntax looks like.
**Example output with …
=> Complex variants might use a more declarative style

var/spack/repos/builtin/packages/bowtie/issue-87.patch, var/spack/repos/builtin/packages/bowtie/package.py
Bowtie development shifted from Sourceforge to GitHub.  This updates the Spack package to follow.
This commit adds several versions from GitHub, using the archive tarballs.  Note that the tag and URL for 1.2.2 tarball is actually 'v1.2.2_p1'...  Sigh.
Versions 1.2.0 and newer come from GitHub (I'm unsure if the sourceforge 1.2 and github 1.2.0 are identical).
It leaves the old 1.2 release download info in place.
The PR includes a fix from https://github.com/BenLangmead/bowtie/issues/87 that enables %gcc@8.0.0: 
Sadly, v1.2.2 has trouble with "newer" gcc's, so the PR it only adds v1.2.2 for %gcc@6.0.0:.  I'm not sure what gcc's work and/or don't.  Others should feel free to tighten this.  I know that:
- 1.2 -> 1.2.2 work with %gcc@5.5.0;
- 1.2 -> 1.2.1.1 work with %gcc@8.2.0; and
- 1.2.2 …
=> bowtie: new versions and %gcc@8.0.0: fix

lib/spack/spack/cmd/install.py
Fixes https://github.com/spack/spack/issues/10141
As noted in https://github.com/spack/spack/issues/10141, when installing a spec that was stored in a yaml file using the `spack install -f` option, the install was no longer taking place. This has been broken since https://github.com/spack/spack/commit/87aec4134daba7dee43c958151b45ca72c02e617, which overlooked that specs read from files didn't have abstract specs.
This treats the spec initially read from the file as the abstract spec. Note if a user concretizes and writes a spec using logic like:
```
>>> s = Spec('openmpi')
>>> s.concretize()
>>> open('openmpi.yaml', 'w').write(s.to_yaml(all_deps=True))
```
(i.e. in the `spack-python` shell)
That the spec initially read from this file will be the concrete spec (e.g. it will not simply be …
=> Infer abstract spec for file-based installs

var/spack/repos/builtin/packages/m4/package.py
Add "-rtlib=compiler-rt" to CFLAGS when building with either Clang or
the ARM compiler.
Fixes #10279
=> Check for ARM compiler in addition to clang

var/spack/repos/builtin/packages/r-factominer/package.py
* added updated versions
* edited depends_on() per https://cran.r-project.org/web/packages/FactoMineR/index.html
- not sure why three dependencies were commented out.  They are listed in the packages dependencies.  I will check the spack commit history.
- EDIT: [from the blame page](https://github.com/spack/spack/blame/develop/var/spack/repos/builtin/packages/r-factominer/package.py) seems like those three dependencies were commented out in the original commit.  Perhaps the spack packages were not ready yet at the time?
=> r-factominer: new versions

var/spack/repos/builtin/packages/r-dt/package.py
* updated release and checksums
- I need version 0.4, seems like I ought to include the latest (0.5), and why not include the others while I'm at it (?)
* also tightened `depends_on()` per https://cran.r-project.org/web/packages/DT/index.html
Question: the CRAN page above says that `promises` is a dependency.  But it was not previously in this package.py, and `r-promises` doesn't exist in spack.  How is it possible that this worked before then?  
FYI @hartzell
=> r-dt: new versions

var/spack/repos/builtin/packages/r-data-table/package.py
Also updated the R dependency (>= 3.1.0) per https://cran.r-project.org/web/packages/data.table/index.html
=> r-data-table: new versions

var/spack/repos/builtin/packages/r-cowplot/package.py
Filling in dependency versions from https://cran.r-project.org/web/packages/cowplot/index.html
I don't need all these versions of r-cowplot, only the latest, but I figured I should provide them while I'm at it (?)
=> r-cowplot: new versions, more specific dependencies

lib/spack/spack/stage.py
This is proposed as a fix for #10284 which I recently reported.
PR #10152  replaced `shutil.move` with llnl's `copy` and `copy_tree`
https://github.com/spack/spack/pull/10152/files#diff-b96a1a55f58dffde150cbe13f13ae2acL548
I think this is causing the build error with lua that I'm seeing today.  See below for details.  I don't know if this is an acceptable way to fix the issue, but I offer this PR as both a bug report and suggestion of possible fix.
```
$ spack install lua                                                                                                           
[snip]
==> Building lua [Package]                                                                                                                                                      
==> Executing phase: 'install' …
```
=> bug fix: copy permissions when staging

var/spack/repos/builtin/packages/openmpi/package.py
Add the development version of OpenMPI from the git repo in `master`.
cc @jrood-nrel @ggouaillardet
=> OpenMPI: Add Development Version

var/spack/repos/builtin/packages/gromacs/package.py
This PR adds variants to the gromacs package.
- simd determines the SIMD instruction set. Only a single value is allowed. Gromacs 5.1.x does not support all settings, cmake will then complain.
- rdtscp is default on, but some old processors need it off.
=> gromacs: added simd and rdtscp variants

var/spack/repos/builtin/packages/git-fat-git/package.py
Not sure if we should think about a versioning scheme if there is no upstream versioning or if it is okay to have the user figure out what a current commit is...
=> New package: git-fat-git

var/spack/repos/builtin/packages/elfutils/package.py
Add variant 'elfh' (default False) to install the elf.h header file to
the include directory.  This provides access to a newer version of
elf.h and allows an elf application to build with the same elf.h that
libelf.so was built with.
Add version 0.175.
=> elfutils: option to install elf.h header file

var/spack/repos/builtin/packages/petsc/package.py
i.e use configure defaults '-g'
cc: @s-sajid-ali
=> petsc: fix petsc+debug to not reset COPTFLAGS

lib/spack/docs/tutorial_basics.rst
We used gcc@7.2.0 for our spack-installed compiler in the tutorial at version 0.12.0 because gcc@8.1.0 was relatively new and we were worried not all bugs had been shaken out yet. This updates the tutorial script to match.
This should be back-ported onto v0.12.0.
=> tutorial basics section: fix gcc install version

lib/spack/docs/workflows.rst, lib/spack/spack/build_systems/aspell_dict.py, lib/spack/spack/build_systems/python.py, lib/spack/spack/cmd/__init__.py, lib/spack/spack/cmd/view.py, lib/spack/spack/config.py, lib/spack/spack/directory_layout.py, lib/spack/spack/filesystem_view.py, lib/spack/spack/package.py, lib/spack/spack/schema/projections.py, lib/spack/spack/spec.py, lib/spack/spack/test/cmd/view.py, lib/spack/spack/test/config.py, lib/spack/spack/test/test_activations.py, var/spack/repos/builtin.mock/packages/perl-extension/package.py, var/spack/repos/builtin.mock/packages/perl/package.py, var/spack/repos/builtin.mock/packages/py-extension1/package.py, var/spack/repos/builtin.mock/packages/py-extension2/package.py, var/spack/repos/builtin/packages/python/package.py
Allow views to specify projections more complicated than merging every package into a shared prefix. This will allow sites to configure a view for the way they want to present packages to their users.
From the new documentation for views:
The default projection into a view is to link every package into the
root of the view. This can be changed through the ``projections.yaml``
file in the view. The projection configuration file for a view located
at ``/my/view`` is stored in ``/my/view/.spack/projections.yaml``.
When creating a view, the projection configuration file can also be
specified from the command line using the ``--projection-file`` option
to the ``spack view`` command.
The projections configuration file is a mapping of partial specs to
spec format strings, as shown in the example …
=> Allow combinatorial projections in views

lib/spack/spack/cmd/versions.py, lib/spack/spack/test/cmd/versions.py, share/spack/spack-completion.bash
Adds a `--safe-only` flag to the `spack versions` command. Also prevents the printing of tty messages unless printing to the terminal.
The idea for this use case came from @robertmaynard in #10003. With this PR, one can run:
```console
$ spack versions -s cmake | xargs -n 1 spack fetch cmake@
```
or:
```bash
for version in $(spack versions -s cmake)
do
spack fetch cmake@version
done
```
to test downloads of every version of a package.
We should probably have a more thought out command to do this task, but this is a quick, generic hack to give the same functionality.
=> spack versions: only list safe versions

var/spack/repos/builtin/packages/r-rcpp/package.py
* updated hashes for the four latest versions
* dependencies are unchanged (including r@3.0.0 for completeness sake)
FYI @hartzell
=> r-rcpp: new versions

var/spack/repos/builtin/packages/sundials/package.py
The 4.0.1 release is the culmination of the SUNDIALS 4.0.0 preview releases,
i.e. the 4.0.0-dev versions. As such, the 4.0.0-dev releases are now
being removed.
=> sundials: add version 4.0.1 and remove 4.0.0-dev series

var/spack/repos/builtin/packages/boost/bootstrap-path.patch, var/spack/repos/builtin/packages/boost/package.py
Fixes #9613, fixes #3209.
Remove the spack wrapper directories from PATH for the bootstrap step.
This was breaking the build for Cray (and other cross-compile) because
bjam was built for the BE and died on SIGILL on the FE.
This only affects building bjam.  The boost libraries are still built
the normal spack way with the spack wrappers.
----------
I wrote the patch to apply to Cray, without a variant.  Technically,
this patch (or something similar) would be needed on any cross-
compile, anywhere BE code would not run on the FE.
But Cray is the only example I could find that actually fell over.
(It seems to work on Blue Gene without this fix.)  So, I decided that
boost already has enough variants.  But if spack supports a true cross
compile, then this will be needed on all cross compiles. …
=> boost: fix the bjam build for Cray

var/spack/repos/builtin/packages/omega-h/package.py
And breaks with current spak deafult  'RelWithDebInfo'
This is per https://github.com/ibaned/omega_h/issues/282#issuecomment-452824906
This fixes https://github.com/spack/spack/issues/10291
cc: @scottwittenburg  @ibaned
=> omega-h: requires empty CMAKE_BUILD_TYPE

lib/spack/spack/cmd/buildcache.py
The current output of buildcache list is very verbose and I feel like
some details are getting lost. By making the output similar to find, I
think users will be able to get a better overview of what is stored in
the cache.
=> enh: `buildcache list` should behave similar to `find`

lib/spack/spack/binary_distribution.py, lib/spack/spack/relocate.py, lib/spack/spack/spec.py, lib/spack/spack/test/packaging.py
From #9747:
> Binary caches of packages with absolute symlinks had broken symlinks. From what I can tell, tar doesn't support any notion of matching source/destination roots when unpacking an archive with absolute symlinks. Therefore, this commit just makes a copy of any file that is a symlink while creating a binary cache of a package.
#9747 caused other binary relocation bugs and was reverted for v0.12.0. This is an alternative solution that avoids the bugs from #9747.
Instead of copying files for absolute symlinks, we relocate the source path of the symlink. This involves computing the new path, removing the link, and creating a new link with the new path.
@scottwittenburg @gartung @scheibelp @tgamblin
=> Binary caching bugfix: symlink relocation

share/spack/docker/Dockerfile, share/spack/docker/config/arch.bash
Fix Arch Linux docker build.
- Switch from an unsupported base image to a community-supported image, based on the information found [here](https://wiki.archlinux.org/index.php/Docker#Images).
- Perform the equivalent of `sudo apt-get update` prior to installing Arch packages.
- Add a few missing packages.
=> fix archlinux docker build

var/spack/repos/builtin/packages/gdal/package.py
The GRIB driver has no external dependencies, so can be a simple variant like most of the others.
=> gdal: Add variant for GRIB driver

share/spack/qa/run-docker-tests
Huzzah! The docker images are finally building in Travis! :tada: :tada: :tada:
But, they're not actually getting pushed, because of a silly oversight on my part. :(
This PR fixes a typo from when the test suite was initially called `docker build`, instead of simply `docker`.
CC'ing a few of the usual suspects.  It would be great if we could merge this one-liner in quickly, as it very well may be the only thing standing between us and images on docker hub!
=> fix typo in docker test script

lib/spack/docs/tutorial.rst
This updates the tutorial slides to the version for the [2019 ECP Annual Meeting](https://ecpannualmeeting.com/).
=> Update tutorial materials for ECP19

var/spack/repos/builtin/packages/vigra/package.py
I have included variants for everything I could see. I am not really happy with how I had to handle the inclusion of the libboost_python library, but unless I explicitly specify where this is, the cmake claims it can't find it and refuses to build the python bindings. I would welcome any advice on a cleaner way to find the exact name of this .so file.
=> vigra: new package

var/spack/repos/builtin/packages/gtkplus/package.py
I think this is necessary due to #10135
This is the same sort of fix as proposed by @adamjstewart in #10350
=> gtkplus requires cairo+pdf

var/spack/repos/builtin/packages/lmod/package.py
Upstream project [fixed an unbound shell variable](https://github.com/TACC/Lmod/commit/dbc4472dbbda9804b5d996579c55d611d1171fd3), which looks like it made it into versions >= 7.8.6.   This PR adds the latest lmod release, which is 7.8.15.
Tested on Centos 7.6
FYI @hartzell
=> lmod: add version 7.8.15

var/spack/repos/builtin/packages/py-numpy/package.py
Fixes https://github.com/spack/spack/issues/10361
When mkl isnt in the spec, still write an explicit mkl entry to prevent numpy from looking in system dirs; this is hacked in write now and needs some more finesse before merging
=> Exclude system mkl installs from numpy

var/spack/repos/builtin/packages/r-robust/package.py
depends on r-rrcov introduced in #10387
=> r-robust: new package at 0.4-18

lib/spack/spack/cmd/install.py, lib/spack/spack/test/cmd/install.py
Previously, the `--overwrite` flag to the `install` command required a single, previously installed spec.
Now, it can accept multiple specs.
Now, it can accept specs that are not already installed.
It will warn/prompt the user before installing a spec top-level spec that was not previously installed (can be suppressed with the `-y` option)
=> Allow `spack install --overwrite` for nonexistent or multiple packages

var/spack/repos/builtin/packages/cmake/package.py
This also fixes the libuv version dependency for 3.11+
Depends on #10423
=> cmake: Use system libs by default

var/spack/repos/builtin/packages/perl-data-dumper/package.py
This package is added to satisfy a build time dependency for llvm-openmp (see https://github.com/llvm-project/openmp/blob/master/runtime/tools/lib/tools.pm)
=> perl-data-dumper: New package

var/spack/repos/builtin/packages/bcftools/package.py
* if the path to htslib is not specified the bundled one is built instead
* additionally this fixes the build with the intel compiler
=> bcftools: do not use bundled htslib

var/spack/repos/builtin/packages/qmcpack/package.py
This update to the QMCPACK Spack package has a number of updates and bug fixes:
- QMCPACK now uses the FFTW-API provider. You can only need intel-mkl or fftw, but not both.
- QMCPACK release 6.0 is now supported. This requires detection of a compiler that supports C++14, a newer version of boost, a newer version of CMake, etc.
- Relax dependencies on the +da variant
- Issue conflicts when an incompatible compiler-CUDA combination is chosen.
- Added QMCPACK collective I/O variant.
- Some clean-up of Spack code.
- Update conflicts, in particular qmcpack+qe~mpi variant does not work due to limitations in QE 3.6.0. May be able to fix this later by applying patch to QE.
- Correctly set-up Python environment for QMCPACK data analysis scripts
=> QMCPACK Update - Jan 2019

var/spack/repos/builtin/packages/trilinos/package.py
This PR adds a variant to Trilinos for users who wish to run with debug/safety checks enabled.  For example, if the Kokkos package is installed bounds checking will be enabled with `+debug`.
=> add variant for a Trilinos debug build

var/spack/repos/builtin/packages/llvm/package.py
- Bump the version to 7.0.1
- Fix openmp build time dependency (Depends on #10425, will rebase once merged)
- Fix lldb stability issue with libstdc++ < from gcc < 4.9
- See https://github.com/llvm/llvm-project/blob/f9ebacfd299c7711b5b3a3fae5f36b61e14a580e/lldb/cmake/modules/LLDBConfig.cmake#L424-L443 for details
- Since compilers like PGI, Intel, and Cray tend to use the C++ library from some system-supplied GCC installation, there's not currently a reliable way to check in the package file whether or not exception handling is needed.  It's not particularly harmful and generally useful so always enabling it should be a reliable safe bet.
=> llvm: various updates

lib/spack/spack/util/module_cmd.py
While loading/unloading modules, the content can be different in the Spack context vs. executing module commands outside of Spack. When there is an error, the modulecmd output is not available to inspect for issues. This includes modulecmd output as part of the debug output.
=> debug output includes modulecmd output

var/spack/repos/builtin/packages/py-configparser/package.py
This release includes a fix to clean up how configparser used namespaces.
I can now install `py-flake8`, load the resulting `py-flake8` module, and have a working `flake8` command (this was the failure case in #8343).
Chain of details starts here: https://github.com/jaraco/configparser/pull/22
Closes #8343, #7370
FYI: @healther
=> py-configparser: bump version (v3.5.1, which fixes backports namespaces issues)

var/spack/repos/builtin/packages/openmpi/package.py
Verification builds, LANL Darwin:
Intel Xeon
[+] /scratch/users/dantopa/new-spack/spack.pr.open-mpi-2.16/opt/spack/linux-centos7-x86_64/gcc-8.2.0/openmpi-2.1.6-dbgnmvjmaxz2f3qfhu7eveybihyw3iu6
ARM
[+] /scratch/users/dantopa/new-spack/spack.pr.open-mpi-2.16/opt/spack/linux-rhel7-aarch64/gcc-4.8.5/openmpi-2.1.6-pbveyqpfwzgunlip3xs6imuiv3hjnhel
Power9
[+] /scratch/users/dantopa/new-spack/spack.pr.open-mpi-2.16/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/openmpi-2.1.6-nva7q77c7b6ccjcyzczo7amg2da2u7ih
=> Add Open MPI 2.1.6

var/spack/repos/builtin/packages/gtkplus/package.py
=> gtkplus: add gettext dependency

var/spack/repos/builtin/packages/jdk/package.py
For whatever reason, the previous version is no longer available for download at that URL.
The previous version was underspecified so I fixed that.
=> Add JDK 11.0.2_9

var/spack/repos/builtin/packages/opa-psm2/package.py
- Added latest version
- Added variant to disable AVX2 for older hardware
- Changed installation paths for compatibility with dependencies
=> Update opa-psm2 package
